Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_cargl.c File Reference
s_cargl.c File Reference
#include "cdefs-compat.h"
#include <openlibm_complex.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT long double cargl (long double complex z)
Function Documentation
cargl()
OLM_DLLEXPORT long double cargl (long double complex z)
References atan2l(), cimagl(), creall(), and z.
Referenced by cpowl().