Embedded Artistry Framework: src/stdlibs/libc/openlibm/ld80/e_acoshl.c File Reference
e_acoshl.c File Reference
#include <openlibm_math.h>
#include "math_private.h"
Functions
long double acoshl (long double x)
Variables
static const long double one = 1.0
static const long double ln2 = 6.931471805599453094287e-01L
Function Documentation
acoshl()
long double acoshl (long double x)
References GET_LDOUBLE_WORDS, ln2, log1pl(), logl(), one, sqrtl(), and t.
Variable Documentation
ln2
const long double ln2 = 6.931471805599453094287e-01L static
Referenced by acoshl().
one
const long double one = 1.0 static
Referenced by acoshl().