Embedded Artistry libc: src/string/strerror_r.c File Reference
strerror_r.c File Reference
#include <assert.h>
#include <errno.h>
#include <string.h>
Functions
int strerror_r (int err_no, char *buffer, size_t buffer_size)
Function Documentation
strerror_r()
int strerror_r (int err_no, char * buffer, size_t buffer_size)
Definition at line 5 of file strerror_r.c.
 {
     int r = 0;
     char* err_msg = strerror(err_no);
     size_t length = strlen(err_msg);
     assert(buffer);
     if(length >= buffer_size)
     {
         if(buffer_size)
         {
             // -1 so we don't copy an extra byte...
             memcpy(buffer, err_msg, buffer_size - 1);
             // since we will null terminate the string
             buffer[buffer_size - 1] = 0;
         }
         r = ERANGE;
     }
     else
     {
         // +1 for null termination
         memcpy(buffer, err_msg, length + 1);
     }
     return r;
 }
References assert, ERANGE, memcpy(), strerror(), and strlen().