Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_ccoshf.c File Reference
s_ccoshf.c File Reference
#include "cdefs-compat.h"
#include <openlibm_complex.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float complex ccoshf (float complex z)
OLM_DLLEXPORT float complex ccosf (float complex z)
Variables
static const float huge = 0x1p127
Function Documentation
ccosf()
OLM_DLLEXPORT float complex ccosf (float complex z)
References ccoshf(), cimagf(), CMPLXF(), crealf(), and z.
ccoshf()
OLM_DLLEXPORT float complex ccoshf (float complex z)
References __ldexp_cexpf(), cimagf(), CMPLXF(), copysignf(), cosf(), coshf(), crealf(), expf(), fabsf(), GET_FLOAT_WORD, huge, sinf(), sinhf(), and z.
Referenced by ccosf().
Variable Documentation
huge
const float huge = 0x1p127 static
Referenced by ccoshf().