Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_atanl.c File Reference
s_atanl.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "invtrig.h"
#include "math_private.h"
Functions
OLM_DLLEXPORT long double atanl (long double x)
Variables
static const long double one = 1.0
static const long double huge = 1.0e300
Function Documentation
atanl()
OLM_DLLEXPORT long double atanl (long double x)
References ATAN_CONST, ATAN_LINEAR, atanhi, atanlo, BIAS, fabsl(), huge, LDBL_MAX_EXP, LDBL_NBIT, MANH_SIZE, one, s1, s2, T_even(), T_odd(), u, w, and z.
Referenced by atan2l().
Variable Documentation
huge
const long double huge = 1.0e300 static
Referenced by atanl().
one
const long double one = 1.0 static
Referenced by atanl().