Embedded Artistry Framework: src/stdlibs/libc/test/string/string_tests.c File Reference
string_tests.c File Reference
#include <stdlib.h>
#include "string_tests.h"
#include <tests.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Functions
int string_tests (void)
Function Documentation
string_tests()
int string_tests (void)
References memcmp_tests(), memcpy_tests(), memmem_tests(), memmove_tests(), memset_tests(), strcat_tests(), strchr_tests(), strcmp_tests(), strcpy_tests(), strdup_tests(), strlen_tests(), strncat_tests(), strncmp_tests(), strncpy_tests(), strndup_tests(), strnlen_tests(), strnstr_tests(), strrchr_tests(), strstr_tests(), and strtok_tests().
Referenced by main().