Embedded Artistry Framework: FrameworkDemoSimPlatform Class Reference
FrameworkDemoSimPlatform Class Reference
This Platform serves as a base class that the specific framework demo applications Can derive from.
#include <platform.hpp>
Public Member Functions
void init_ () noexcept
void initProcessor_ () noexcept
void initHWPlatform_ () noexcept
void startBlink () noexcept
void echoLogBufferToConsole () noexcept
FrameworkDemoSimPlatform () noexcept
Default constructor supplies a default name for the simulator platform.
FrameworkDemoSimPlatform (const std::string_view &name) noexcept
Child classes can override the simulator platform name using the std::string_view constructor.
~FrameworkDemoSimPlatform ()=default
void init () noexcept
Initialize the platform.
void initProcessor () noexcept
Initialize the processor.
void initHWPlatform () noexcept
Initialize the hardware platform.
constexpr const std::string_view & name () const noexcept
Access the platform's name.
constexpr const char * name_cstr () const noexcept
Access the platform name as a cstring for C API compatibility.
auto findDriver (const std::string_view &name) noexcept
Access a device driver in the registry by name.
auto findDriver (embvm::DriverType_t type) noexcept
Access a device driver in the registry by type.
auto findDriver () noexcept
Access a device driver in the registry by type, cast as the appropriate base class.
auto findDriver (const std::string_view &name) noexcept
Access a device driver in the registry by name, cast as the appropriate base class.
auto findAllDrivers (embvm::DriverType_t type) noexcept
Get a list of all device drivers in the registry by type.
auto findAllDrivers () noexcept
Get a list of all device drivers in the registry by type, cast as the appropriate base class.
size_t driverCount () const noexcept
Get the count of drivers registered with the platform.
Static Public Member Functions
static void earlyInitHook_ () noexcept
static FrameworkDemoSimPlatform & inst () noexcept
Get the global platform instance.
static void earlyInitHook () noexcept
Call early-initialization code.
static void initOS () noexcept
Initialize the OS.
static void initOS (void(*main_thread)()) noexcept
Initialize the with a function to use as the main thread.
static void registerDriver (const std::string_view &name, embvm::DriverBase *driver) noexcept
Platform-level API for registering a new device driver.
static void unregisterDriver (const std::string_view &name, embvm::DriverBase *driver) noexcept
Platform-level API for unregistering a new device driver.
Protected Attributes
const std::string_view name_
Private Types
using VirtualPlatform = embvm::VirtualPlatformBase< FrameworkDemoSimPlatform, PlatformDriverRegistry >
Private Member Functions
void updateToFMode () noexcept
Private Attributes
FWDemoSimulatorHWPlatform hw_platform_
FWDemoSimulatorHWPlatform::TimerHandle_t led_sw_timer_handle
Detailed Description
This Platform serves as a base class that the specific framework demo applications Can derive from.
This class takes a hardware platform as a template. Clients should implement specific instances of this platform as follows:
using VirtualPlatform = embvm::VirtualPlatformBase<
    FrameworkDemoPlatform<SimulatorHWPlatform>, PlatformDriverRegistry>;
Member Typedef Documentation
VirtualPlatform
using FrameworkDemoSimPlatform::VirtualPlatform = embvm::VirtualPlatformBase<FrameworkDemoSimPlatform, PlatformDriverRegistry> private
Constructor & Destructor Documentation
FrameworkDemoSimPlatform() [1/2]
FrameworkDemoSimPlatform::FrameworkDemoSimPlatform () inline noexcept
Default constructor supplies a default name for the simulator platform.
FrameworkDemoSimPlatform() [2/2]
FrameworkDemoSimPlatform::FrameworkDemoSimPlatform (const std::string_view & name) inline explicit noexcept
Child classes can override the simulator platform name using the std::string_view constructor.
~FrameworkDemoSimPlatform()
FrameworkDemoSimPlatform::~FrameworkDemoSimPlatform () default
Member Function Documentation
driverCount()
size_t embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::driverCount () const inline noexcept inherited
Get the count of drivers registered with the platform.
returns Number of drivers currently registered with the platform DriverRegistry.
earlyInitHook()
static void embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::earlyInitHook () inline static noexcept inherited
Call early-initialization code.
Call early initialization code, which is to be run before C runtime initialization, memory relocations, OS initialization, etc. This call is used to handle early setup code that the rest of the initialization process might depend on, such as DRAM initialization.
This function forwards the call to the derived class for the actual implementation.
earlyInitHook_()
static void FrameworkDemoSimPlatform::earlyInitHook_ () inline static noexcept
echoLogBufferToConsole()
void FrameworkDemoSimPlatform::echoLogBufferToConsole () noexcept
References embvm::PlatformLogger_t< TLogger >::inst().
findAllDrivers() [1/2]
auto embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::findAllDrivers (embvm::DriverType_t type) inline noexcept inherited
Get a list of all device drivers in the registry by type.
The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Parameters
type The type of driver being requested (embvm::i2c::master, SystemClock).
Returns
A list of embvm::DriverBase instances. If no matching types are found, an empty list will be returned. The caller must cast to the appropriate type.
findAllDrivers() [2/2]
auto embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::findAllDrivers () inline noexcept inherited
Get a list of all device drivers in the registry by type, cast as the appropriate base class.
The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Returns
A list of driver instances cast as TDriverClass types. If no matching types are found, an empty list will be returned.
findDriver() [1/4]
auto embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::findDriver (const std::string_view & name) inline noexcept inherited
Access a device driver in the registry by name.
Find a driver by name.
This call forwards the information to the DriverRegistry instance.
Returns
An optional_ref to the embvm::DriverBase instance. If no instance is found, the optional reference will be invalid. The caller must cast to the appropriate type.
findDriver() [2/4]
auto embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::findDriver (embvm::DriverType_t type) inline noexcept inherited
Access a device driver in the registry by type.
Find a driver by type. If multiple drivers are found for a type, the first one found will be returned.
This call forwards the information to the DriverRegistry instance.
Returns
An optional_ref to the embvm::DriverBase instance. If no instance is found, the optional reference will be invalid. The caller must cast to the appropriate type.
findDriver() [3/4]
auto embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::findDriver () inline noexcept inherited
Access a device driver in the registry by type, cast as the appropriate base class.
If multiple drivers are found for a type, the first one found will be returned. The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Returns
an type_safe::optional_ref cast to the TDriverClass type. If the driver was not found, the optional_ref will be empty.
findDriver() [4/4]
auto embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::findDriver (const std::string_view & name) inline noexcept inherited
Access a device driver in the registry by name, cast as the appropriate base class.
The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Returns
an type_safe::optional_ref cast to the TDriverClass type. If the driver was not found, the optional_ref will be empty.
init()
void embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::init () inline noexcept inherited
Initialize the platform.
This function is responsible for initializing the platform.
This function forwards the call to the derived class for the actual implementation.
init_()
void FrameworkDemoSimPlatform::init_ () noexcept
References hw_platform_, embvm::PlatformLogger_t< TLogger >::inst(), printf, embvm::tof::sensor::registerReadCallback(), and FWDemoSimulatorHWPlatform::tof0_inst().
initHWPlatform()
void embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::initHWPlatform () inline noexcept inherited
Initialize the hardware platform.
Performs steps necessary to initialize the hardware platform for use by the platform. In many cases, this call should just invoke the hardware platform's init() function. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the hardware platform in situations where non-default values are used.
This function forwards the call to the derived class for the actual implementation.
initHWPlatform_()
void FrameworkDemoSimPlatform::initHWPlatform_ () noexcept
References hw_platform_, embvm::VirtualHwPlatformBase< THWPlatform >::init(), FWDemoSimulatorHWPlatform::screen0_inst(), snprintf, embvm::DriverBase::start(), FWDemoSimulatorHWPlatform::tof0_inst(), and updateToFMode().
initOS() [1/2]
static void embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::initOS () inline static noexcept inherited
Initialize the OS.
Performs steps necessary to initialize the OS for use by the platform. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the OS, since each OS has different startup requirements
This function forwards the call to the derived class for the actual implementation.
initOS() [2/2]
static void embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::initOS (void(*)() main_thread) inline static noexcept inherited
Initialize the with a function to use as the main thread.
Performs steps necessary to initialize the OS for use by the platform. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the OS, since each OS has different startup requirements
This function forwards the call to the derived class for the actual implementation.
Parameters
main_thread a function pointer to use as the main thread routine. This version of initOS should be used for OSes such as FreeRTOS which kill execution of the current thread when the scheduler is started.
initProcessor()
void embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::initProcessor () inline noexcept inherited
Initialize the processor.
Performs steps necessary to initialize the processor for use by the platform. In many cases, this call should just invoke the processor's init() function. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the processor in situations where non-default values are used.
This function forwards the call to the derived class for the actual implementation.
initProcessor_()
void FrameworkDemoSimPlatform::initProcessor_ () noexcept
References hw_platform_, and embvm::VirtualHwPlatformBase< THWPlatform >::initProcessor().
inst()
static FrameworkDemoSimPlatform & embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::inst () inline static noexcept inherited
Get the global platform instance.
Static declaration of the VirtualPlatformBase instance. We use this function to avoid the static initializatio order 'fiasco'. See more: https://isocpp.org/wiki/faq/ctors#static-init-order
name()
constexpr const std::string_view& embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::name () const inline noexcept inherited
Access the platform's name.
Returns
Platform name std::string_view reference.
name_cstr()
constexpr const char* embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::name_cstr () const inline noexcept inherited
Access the platform name as a cstring for C API compatibility.
Returns
Platform name as a C-string.
registerDriver()
static void embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::registerDriver (const std::string_view & name, embvm::DriverBase * driver) inline static noexcept inherited
Platform-level API for registering a new device driver.
Register a device driver with the platform's driver registry.
This call forwards the information to the DriverRegistry instance.
Parameters
name The name (used as a key) the driver will be registered under.
driver Pointer to the embvm::DriverBase object. A pointer is used because there are any number of potential derived classes which will be tracked. To prevent slicing, a pointer to the base class is stored.
startBlink()
void FrameworkDemoSimPlatform::startBlink () noexcept
References FWDemoSimulatorHWPlatform::allocateTimer(), hw_platform_, FWDemoSimulatorHWPlatform::led0_inst(), led_sw_timer_handle, and FWDemoSimulatorHWPlatform::startLEDTimer().
unregisterDriver()
static void embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::unregisterDriver (const std::string_view & name, embvm::DriverBase * driver) inline static noexcept inherited
Platform-level API for unregistering a new device driver.
Unregister a device driver with the platform's driver registry.
This call forwards the information to the DriverRegistry instance.
Parameters
name The name of the driver to remove.
driver Pointer to the embvm::DriverBase object being removed.
updateToFMode()
void FrameworkDemoSimPlatform::updateToFMode () private noexcept
References assert, embvm::tof::defaultRange, hw_platform_, embvm::tof::longRange, embvm::tof::medRange, FWDemoSimulatorHWPlatform::readAndSetToFMode(), embvm::tof::shortRange, and snprintf.
Referenced by initHWPlatform_().
Member Data Documentation
hw_platform_
FWDemoSimulatorHWPlatform FrameworkDemoSimPlatform::hw_platform_ private
Referenced by init_(), initHWPlatform_(), initProcessor_(), startBlink(), and updateToFMode().
led_sw_timer_handle
FWDemoSimulatorHWPlatform::TimerHandle_t FrameworkDemoSimPlatform::led_sw_timer_handle private
Referenced by startBlink().
name_
const std::string_view embvm::VirtualPlatformBase< FrameworkDemoSimPlatform , PlatformDriverRegistry >::name_ protected inherited
The documentation for this class was generated from the following files:
src/platforms/fwdemo/fwdemo_sim/platform.hpp
src/platforms/fwdemo/fwdemo_sim/platform.cpp