Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_fmal.c File Reference
s_fmal.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_fenv.h>
#include <openlibm_math.h>
#include "fpmath.h"
#include "math_private.h"
Classes
struct dd
Functions
static struct dd dd_add (long double a, long double b)
static long double add_adjusted (long double a, long double b)
static long double add_and_denormalize (long double a, long double b, int scale)
static struct dd dd_mul (long double a, long double b)
OLM_DLLEXPORT long double fmal (long double x, long double y, long double z)
Class Documentation
dd
struct dd
Class Members
double hi
long double hi
double lo
long double lo
Function Documentation
add_adjusted()
static long double add_adjusted (long double a, long double b) inline static
References a, b, dd_add(), INFINITY, nextafterl(), sum(), and u.
Referenced by fmal().
add_and_denormalize()
static long double add_and_denormalize (long double a, long double b, int scale) inline static
References a, b, dd_add(), INFINITY, ldexp(), nextafterl(), sum(), and u.
Referenced by fmal().
dd_add()
static struct dd dd_add (long double a, long double b) inline static
References a, b, dd::hi, dd::lo, and s.
Referenced by add_adjusted(), add_and_denormalize(), and fmal().
dd_mul()
static struct dd dd_mul (long double a, long double b) inline static
References a, b, dd::hi, dd::lo, and p.
Referenced by fmal().
fmal()
OLM_DLLEXPORT long double fmal (long double x, long double y, long double z)
References add_adjusted(), add_and_denormalize(), copysignl(), dd_add(), dd_mul(), FE_DOWNWARD, FE_INEXACT, FE_TONEAREST, FE_TOWARDZERO, FE_UNDERFLOW, fegetround(), feraiseexcept(), fesetround(), frexpl(), dd::hi, ilogbl(), INFINITY, isfinite, isnormal, LDBL_MANT_DIG, LDBL_MIN, ldexpl(), dd::lo, nextafterl(), r, and z.