Embedded Artistry Framework: src/stdlibs/libc/test/main.c File Reference
main.c File Reference
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
#include <tests.h>
Functions
int main (void)
Function for application main entry.
Function Documentation
main()
int main (void)
Function for application main entry.
References ctype_tests(), stdlib_tests(), and string_tests().