Embedded Artistry libc: src/wchar/iswalpha.c File Reference
iswalpha.c File Reference
#include <wctype.h>
#include "alpha.h"
Functions
int iswalpha (wint_t wc)
Variables
static const unsigned char table []
Function Documentation
iswalpha()
int iswalpha (wint_t wc)
Definition at line 7 of file iswalpha.c.
 {
     if(wc < 0x20000U)
     {
         return (table[table[wc >> 8] * 32 + ((wc & 255) >> 3)] >> (wc & 7)) & 1;
     }
     if(wc < 0x2fffeU)
     {
         return 1;
     }
     return 0;
 }
References table.
Referenced by __towcase(), iswalnum(), and iswctype().
Variable Documentation
table
const unsigned char table[] static
Definition at line 3 of file iswalpha.c.
Referenced by iswalpha().