Embedded Artistry Framework: src/stdlibs/libc/src/stdlib/strtol.c File Reference
strtol.c File Reference
#include <ctype.h>
#include <limits.h>
#include <stdlib.h>
Functions
long strtol (char *nptr, char **endptr, int base) const
Function Documentation
strtol()
long strtol (char* nptr, char** endptr, int base) const
References isalpha(), isdigit(), isspace(), isupper(), LONG_MAX, LONG_MIN, and s.
Referenced by strtol_test().