Embedded Artistry Framework: embvm::led::gpio< TActiveHigh > Class Template Reference
embvm::led::gpio< TActiveHigh > Class Template Reference final
This class manages a GPIO object which is attached to an LED.
#include <led.hpp>
Public Member Functions
gpio (embvm::gpio::output &g)
Default constructor.
gpio (embvm::gpio::output &g, const char *name)
Construct an led::gpio() with a C-string name.
gpio (embvm::gpio::output &g, const std::string &name)
Construct an led::gpio() with a std::string name.
gpio (embvm::gpio::output &g, const std::string_view &name)
Construct an led::gpio() with a std::string_view name.
~gpio () final=default
Default destructor.
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void on () final
Turn on the LED.
void off () final
Turn off the LED.
void toggle () final
Toggle the LED state.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
LED Driver Type ID.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Attributes
embvm::gpio::output & g_
The GPIO output object which this LED driver is managing.
bool on_ = false
State of the LED, required to implement toggle().
Detailed Description
template<bool TActiveHigh = true>
class embvm::led::gpio< TActiveHigh >
This class manages a GPIO object which is attached to an LED.
This class provides a specialization of the led::base() object. The led::gpio() class manages a embvm::gpio::output object that is connected to an LED in hardware. All interactions with the LED are forwarded to the embvm::gpio::output.
This class is used in the same way as led::base(). The only additonal requirement is that it must be initialized with a embvm::gpio::output object. This driver assumes that is is the sole owner of the embvm::gpio::output object after creation. If other code messes with the embvm::gpio::output state outside of this interface, proper functioning is no longer guaranteed.
Template Parameters
TActiveHigh If true, the LED turns on when the GPIO is set high. If false, the LED turns on when the GPIO is set low.
Constructor & Destructor Documentation
gpio() [1/4]
template<bool TActiveHigh = true> embvm::led::gpio< TActiveHigh >::gpio (embvm::gpio< TActiveHigh >::output & g) inline explicit
Default constructor.
Initializes the led::gpio() instance with a GPIO output object to manage.
Parameters
g The embvm::gpio::output object which the LED driver will manage.
gpio() [2/4]
template<bool TActiveHigh = true> embvm::led::gpio< TActiveHigh >::gpio (embvm::gpio< TActiveHigh >::output & g, const char * name) inline explicit
Construct an led::gpio() with a C-string name.
Initializes the led::gpio() instance with a GPIO output object to manage and uses the specified name.
Parameters
g The embvm::gpio::output object which the LED driver will manage.
name The name of the LED instance.
gpio() [3/4]
template<bool TActiveHigh = true> embvm::led::gpio< TActiveHigh >::gpio (embvm::gpio< TActiveHigh >::output & g, const std::string & name) inline explicit
Construct an led::gpio() with a std::string name.
Initializes the led::gpio() instance with a GPIO output object to manage and uses the specified name.
Parameters
g The embvm::gpio::output object which the LED driver will manage.
name The name of the LED instance.
gpio() [4/4]
template<bool TActiveHigh = true> embvm::led::gpio< TActiveHigh >::gpio (embvm::gpio< TActiveHigh >::output & g, const std::string_view & name) inline explicit
Construct an led::gpio() with a std::string_view name.
Initializes the led::gpio() instance with a GPIO output object to manage and uses the specified name.
Parameters
g The embvm::gpio::output object which the LED driver will manage.
name The name of the LED instance. led::base() uses a std::string_view, so the std::string must remain valid
~gpio()
template<bool TActiveHigh = true> embvm::led::gpio< TActiveHigh >::~gpio () final default
Default destructor.
Member Function Documentation
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
off()
template<bool TActiveHigh = true> void embvm::led::gpio< TActiveHigh >::off () inline final virtual
Turn off the LED.
Postcondition
LED is turned off.
Implements embvm::led::base.
References embvm::led::gpio< TActiveHigh >::g_, embvm::led::gpio< TActiveHigh >::on_, and embvm::gpio::output::set().
Referenced by NRF52DKHWPlatform::leds_off(), NRF52DongleHWPlatform::leds_off(), embvm::led::gpio< TActiveHigh >::start_(), and embvm::led::gpio< TActiveHigh >::toggle().
on()
template<bool TActiveHigh = true> void embvm::led::gpio< TActiveHigh >::on () inline final virtual
Turn on the LED.
Postcondition
LED is turned on.
Implements embvm::led::base.
References embvm::led::gpio< TActiveHigh >::g_, embvm::led::gpio< TActiveHigh >::on_, and embvm::gpio::output::set().
Referenced by embvm::led::gpio< TActiveHigh >::toggle().
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
template<bool TActiveHigh = true> void embvm::led::gpio< TActiveHigh >::start_ () inline final virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::led::base.
References embvm::led::gpio< TActiveHigh >::g_, embvm::led::gpio< TActiveHigh >::off(), and embvm::DriverBase::start().
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
template<bool TActiveHigh = true> void embvm::led::gpio< TActiveHigh >::stop_ () inline final virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::led::base.
References embvm::led::gpio< TActiveHigh >::g_, and embvm::DriverBase::stop().
toggle()
template<bool TActiveHigh = true> void embvm::led::gpio< TActiveHigh >::toggle () inline final virtual
Toggle the LED state.
If the LED is on, turn it off. If the LED is off, turn it on. The logic for implementing toggle is left to the base class, as there may be efficient options that depend on the specific implementation.
Derived classes must implement the toggle() function.
Postcondition
If the LED was off, the LED is now on. If the LED was on, LED is now off.
Implements embvm::led::base.
References embvm::led::gpio< TActiveHigh >::off(), embvm::led::gpio< TActiveHigh >::on(), and embvm::led::gpio< TActiveHigh >::on_.
Referenced by BlinkySimulatorHWPlatform::init_().
type()
static constexpr embvm::DriverType embvm::led::base::type () inline static inherited
LED Driver Type ID.
Returns
LED type ID.
References embvm::LED.
Member Data Documentation
g_
template<bool TActiveHigh = true> embvm::gpio::output& embvm::led::gpio< TActiveHigh >::g_ private
The GPIO output object which this LED driver is managing.
Referenced by embvm::led::gpio< TActiveHigh >::off(), embvm::led::gpio< TActiveHigh >::on(), embvm::led::gpio< TActiveHigh >::start_(), and embvm::led::gpio< TActiveHigh >::stop_().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
on_
template<bool TActiveHigh = true> bool embvm::led::gpio< TActiveHigh >::on_ = false private
State of the LED, required to implement toggle().
Referenced by embvm::led::gpio< TActiveHigh >::off(), embvm::led::gpio< TActiveHigh >::on(), and embvm::led::gpio< TActiveHigh >::toggle().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
The documentation for this class was generated from the following file:
src/core/driver/led.hpp