Embedded Artistry libc: include/ctype.h File Reference
ctype.h File Reference
Macros
#define _CTYPE_A 0x00000100L /* Alpha */
#define _CTYPE_C 0x00000200L /* Control */
#define _CTYPE_D 0x00000400L /* Digit */
#define _CTYPE_G 0x00000800L /* Graph */
#define _CTYPE_L 0x00001000L /* Lower */
#define _CTYPE_P 0x00002000L /* Punct */
#define _CTYPE_S 0x00004000L /* Space */
#define _CTYPE_U 0x00008000L /* Upper */
#define _CTYPE_X 0x00010000L /* X digit */
#define _CTYPE_B 0x00020000L /* Blank */
#define _CTYPE_R 0x00040000L /* Print */
#define _CTYPE_I 0x00080000L /* Ideogram */
#define _CTYPE_T 0x00100000L /* Special */
#define _CTYPE_Q 0x00200000L /* Phonogram */
#define _CTYPE_SW0 0x20000000L /* 0 width character */
#define _CTYPE_SW1 0x40000000L /* 1 width character */
#define _CTYPE_SW2 0x80000000L /* 2 width character */
#define _CTYPE_SW3 0xc0000000L /* 3 width character */
#define _CTYPE_SWM 0xe0000000L /* Mask for screen width data */
#define _CTYPE_SWS 30 /* Bits to shift to get width */
Functions
int isalnum (int ch)
Checks if the given character is an alphanumeric character.
int isalpha (int ch)
Checks if the given character is an alphabetic character.
int isascii (int ch)
Checks if a given character is a 7-bit US-ASCII character.
int isblank (int ch)
Checks if the given character is a blank character.
int iscntrl (int ch)
Checks if the given character is a control character.
int isdigit (int ch)
Checks if the given character is a numeric character.
int isgraph (int ch)
Checks if the given character has a graphical representation.
int islower (int ch)
Checks if the given character is classified as a lowercase character.
int isprint (int ch)
Checks if the given character can be printed.
int ispunct (int ch)
Checks if the given character is a punctuation character.
int isspace (int ch)
Checks if the given character is a whitespace character.
int isupper (int ch)
Checks if the given character is an uppercase character.
int isxdigit (int ch)
Checks if the given character is a hexadecimal numeric character.
int tolower (int ch)
Converts the given character to lowercase.
int toupper (int ch)
Converts the given character to lowercase.
int toascii (int ch)
Converts the given character to ASCII.
Macro Definition Documentation
_CTYPE_A
#define _CTYPE_A 0x00000100L /* Alpha */
Definition at line 8 of file ctype.h.
_CTYPE_B
#define _CTYPE_B 0x00020000L /* Blank */
Definition at line 17 of file ctype.h.
_CTYPE_C
#define _CTYPE_C 0x00000200L /* Control */
Definition at line 9 of file ctype.h.
_CTYPE_D
#define _CTYPE_D 0x00000400L /* Digit */
Definition at line 10 of file ctype.h.
_CTYPE_G
#define _CTYPE_G 0x00000800L /* Graph */
Definition at line 11 of file ctype.h.
_CTYPE_I
#define _CTYPE_I 0x00080000L /* Ideogram */
Definition at line 19 of file ctype.h.
_CTYPE_L
#define _CTYPE_L 0x00001000L /* Lower */
Definition at line 12 of file ctype.h.
_CTYPE_P
#define _CTYPE_P 0x00002000L /* Punct */
Definition at line 13 of file ctype.h.
_CTYPE_Q
#define _CTYPE_Q 0x00200000L /* Phonogram */
Definition at line 21 of file ctype.h.
_CTYPE_R
#define _CTYPE_R 0x00040000L /* Print */
Definition at line 18 of file ctype.h.
_CTYPE_S
#define _CTYPE_S 0x00004000L /* Space */
Definition at line 14 of file ctype.h.
_CTYPE_SW0
#define _CTYPE_SW0 0x20000000L /* 0 width character */
Definition at line 22 of file ctype.h.
_CTYPE_SW1
#define _CTYPE_SW1 0x40000000L /* 1 width character */
Definition at line 23 of file ctype.h.
_CTYPE_SW2
#define _CTYPE_SW2 0x80000000L /* 2 width character */
Definition at line 24 of file ctype.h.
_CTYPE_SW3
#define _CTYPE_SW3 0xc0000000L /* 3 width character */
Definition at line 25 of file ctype.h.
_CTYPE_SWM
#define _CTYPE_SWM 0xe0000000L /* Mask for screen width data */
Definition at line 26 of file ctype.h.
_CTYPE_SWS
#define _CTYPE_SWS 30 /* Bits to shift to get width */
Definition at line 27 of file ctype.h.
_CTYPE_T
#define _CTYPE_T 0x00100000L /* Special */
Definition at line 20 of file ctype.h.
_CTYPE_U
#define _CTYPE_U 0x00008000L /* Upper */
Definition at line 15 of file ctype.h.
_CTYPE_X
#define _CTYPE_X 0x00010000L /* X digit */
Definition at line 16 of file ctype.h.
Function Documentation
isalnum()
int isalnum (int ch)
Checks if the given character is an alphanumeric character.
Checks if the given character is an alphanumeric character using the default locale. The following characters are alphanumeric:
digits (0123456789)
uppercase letters (ABCDEFGHIJKLMNOPQRSTUVWXYZ)
lowercase letters (abcdefghijklmnopqrstuvwxyz)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is an alphanumeric character, 0 otherwise.
Definition at line 5 of file isalnum.c.
 {
     return isalpha(c) || isdigit(c);
 }
References isalpha(), and isdigit().
Referenced by ispunct().
isalpha()
int isalpha (int ch)
Checks if the given character is an alphabetic character.
Checks if the given character is an alphabetic character, i.e. either an uppercase letter (ABCDEFGHIJKLMNOPQRSTUVWXYZ), or a lowercase letter (abcdefghijklmnopqrstuvwxyz)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is an alphabetic character, zero otherwise.
Definition at line 5 of file isalpha.c.
 {
     return ((unsigned)c | 32) - 'a' < 26;
 }
Referenced by isalnum(), strtol(), strtoll(), and strtoul().
isascii()
int isascii (int ch)
Checks if a given character is a 7-bit US-ASCII character.
Checks if a given character 7-bit unsigned char value that fits into the ASCII character set. which is any character between 0 and 0x7f inclusive.
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if ch is a 7-bit US-ASCII character code, zero otherwise.
Definition at line 5 of file isascii.c.
 {
     return !(c & ~0x7f);
 }
isblank()
int isblank (int ch)
Checks if the given character is a blank character.
Checks if the given character is a blank character using the default locale. The following characters classified as blank:
space (0x20)
horizontal tab (0x09)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a blank character, zero otherwise.
Definition at line 5 of file isblank.c.
 {
     return (c == ' ' || c == '\t');
 }
Referenced by iswblank().
iscntrl()
int iscntrl (int ch)
Checks if the given character is a control character.
Checks if the given character is a control character. The following are examples of control character:
codes (0x00-0x1F) and (0x7F)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a control character, zero otherwise.
Definition at line 5 of file iscntrl.c.
 {
     return (unsigned)c < 0x20 || c == 0x7f;
 }
isdigit()
int isdigit (int ch)
Checks if the given character is a numeric character.
Checks if the given character is a numeric character (0123456789).
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a numeric character, zero otherwise.
Definition at line 5 of file isdigit.c.
 {
     return (unsigned)c - '0' < 10;
 }
Referenced by atoi(), atol(), atoll(), isalnum(), isxdigit(), strtol(), strtoll(), and strtoul().
isgraph()
int isgraph (int ch)
Checks if the given character has a graphical representation.
Checks if the given character has a graphical representation using the default locale. The following characters are graphical:
number (0123456789)
uppercase letter (ABCDEFGHIJKLMNOPQRSTUVWXYZ)
letter (abcdefghijklmnopqrstuvwxyz)
punctuation character (!"#$%&'()*+,-./:;<=>?@[]^_`{|}~)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character has a graphical representation character, zero otherwise.
Definition at line 5 of file isgraph.c.
 {
     return (unsigned)c - 0x21 < 0x5e;
 }
Referenced by ispunct().
islower()
int islower (int ch)
Checks if the given character is classified as a lowercase character.
Checks if the given character is classified as a lowercase character using the default local. islower returns true only for the lowercase letters (abcdefghijklmnopqrstuvwxyz). If islower returns true, it is guaranteed that
See also
iscntrl,
isdigit,
ispunct,
isspace will return false for the same character in the same default locale.
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a lowercase letter, zero otherwise.
Definition at line 5 of file islower.c.
 {
     return (unsigned)c - 'a' < 26;
 }
Referenced by toupper().
isprint()
int isprint (int ch)
Checks if the given character can be printed.
Checks if the given character can be printed using the default locale. The following characters are printable:
number (0123456789)
uppercase letter (ABCDEFGHIJKLMNOPQRSTUVWXYZ)
letter (abcdefghijklmnopqrstuvwxyz)
punctuation character (!"#$%&'()*+,-./:;<=>?@[]^_`{|}~)
space (0x20)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character can be printed, zero otherwise.
Definition at line 5 of file isprint.c.
 {
     return (unsigned)c - 0x20 < 0x5f;
 }
ispunct()
int ispunct (int ch)
Checks if the given character is a punctuation character.
Checks if the given character is a punctuation character using the default local. The following characters are classified as punctuation character:
(!"#$%&'()*+,-./:;<=>?@[]^_`{|}~)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a punctuation character, zero otherwise.
Definition at line 5 of file ispunct.c.
 {
     return isgraph(c) && !isalnum(c);
 }
References isalnum(), and isgraph().
isspace()
int isspace (int ch)
Checks if the given character is a whitespace character.
Checks if the given character is a whitespace character. The following are examples of a whitespace character:
space (0x20)
feed (0x0c)
line feed (0x0a)
carriage return (0x0d)
horizontal tab (0x09)
vertical tab (0x0b)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a whitespace character, zero otherwise.
Definition at line 5 of file isspace.c.
 {
     return c == ' ' || (unsigned)c - '\t' < 5;
 }
Referenced by atol(), atoll(), strtol(), strtoll(), strtoul(), and strtoull().
isupper()
int isupper (int ch)
Checks if the given character is an uppercase character.
Checks if the given character is an uppercase character using the default local. isupper returns true only for the uppercase letters (ABCDEFGHIJKLMNOPQRSTUVWXYZ). If isupper returns true, it is guaranteed that
See also
iscntrl,
isdigit,
ispunct,
isspace will return false for the same character in the same default locale.
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is an uppercase letter, zero otherwise.
Definition at line 5 of file isupper.c.
 {
     return (unsigned)c - 'A' < 26;
 }
Referenced by strtol(), strtoll(), strtoul(), and tolower().
isxdigit()
int isxdigit (int ch)
Checks if the given character is a hexadecimal numeric character.
Checks if the given character is a hexadecimal numeric character (0123456789).
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is an hexadecimal numeric character, zero otherwise.
Definition at line 5 of file isxdigit.c.
 {
     return isdigit(c) || ((unsigned)c | 32) - 'a' < 6;
 }
References isdigit().
toascii()
int toascii (int ch)
Converts the given character to ASCII.
Converts the given character to a 7-bit unsigned char value that fits into the ASCII character set.
Parameters
ch character to be converted.
Returns
The value returned is that of the converted letter, or ch if the conversion was not possible.
Definition at line 5 of file toascii.c.
 {
     return c & 0x7f;
 }
tolower()
int tolower (int ch)
Converts the given character to lowercase.
Converts the given character to lowercase according to the character conversion rules defined by the default local, i.e. the following uppercase letters (ABCDEFGHIJKLMNOPQRSTUVWXYZ) are replaced with respective lowercase letters (abcdefghijklmnopqrstuvwxyz).
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch character to be converted.
Returns
Lowercase version of ch or unmodified ch if no lowercase version is listed in the default locale.
Definition at line 5 of file tolower.c.
 {
     if(isupper(c))
     {
         {
             return c | 32;
         }
     }
     return c;
 }
References isupper().
Referenced by towlower().
toupper()
int toupper (int ch)
Converts the given character to lowercase.
Converts the given character to lowercase according to the character conversion rules defined by the default local, i.e. the following lowercase letters (abcdefghijklmnopqrstuvwxyz) are replaced with respective uppercase letters (ABCDEFGHIJKLMNOPQRSTUVWXYZ).
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch character to be converted.
Returns
Uppercase version of ch or unmodified ch if no uppercase version is listed in the default locale.
Definition at line 5 of file toupper.c.
 {
     if(islower(c))
     {
         {
             return c & 0x5f;
         }
     }
     return c;
 }
References islower().
Referenced by towupper().