Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_copysign.c File Reference
s_copysign.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double copysign (double x, double y)
Function Documentation
copysign()
OLM_DLLEXPORT double copysign (double x, double y)
References GET_HIGH_WORD, and SET_HIGH_WORD.
Referenced by __exp__D(), ccosh(), copysign_test(), cproj(), csinh(), csqrt(), ctanh(), fma(), initialize(), scalbn(), and scalbnl().