Embedded Artistry libc: src/wchar/iswspace.c File Reference
iswspace.c File Reference
#include <wchar.h>
#include <wctype.h>
Functions
int iswspace (wint_t wc)
Function Documentation
iswspace()
int iswspace (wint_t wc)
Definition at line 8 of file iswspace.c.
 {
     static const wchar_t spaces[] = {' ',   '\t',   '\n',   '\r',   11,  12,     0x0085, 0x2000,
                                      0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2008, 0x2009,
                                      0x200a, 0x2028, 0x2029, 0x205f, 0x3000, 0};
     return wc && wcschr(spaces, (wchar_t)wc);
 }
References wcschr().
Referenced by iswctype(), and iswgraph().