Embedded Artistry Framework: src/stdlibs/libc/openlibm/i387/fenv.c File Reference
fenv.c File Reference
#include "cdefs-compat.h"
#include "types-compat.h"
#include "math_private.h"
#include "i387/bsd_npx.h"
#include <openlibm_fenv.h>
Macros
#define __fenv_static
#define getfl(x) __asm __volatile("pushfl\n\tpopl %0" : "=mr" (*(x)))
#define setfl(x) __asm __volatile("pushl %0\n\tpopfl" : : "g" (x))
#define cpuid_dx(x)
Functions
int __test_sse (void)
OLM_DLLEXPORT int feclearexcept (int __excepts)
OLM_DLLEXPORT int fegetexceptflag (fexcept_t *__flagp, int __excepts)
OLM_DLLEXPORT int fesetexceptflag (const fexcept_t *flagp, int excepts)
OLM_DLLEXPORT int feraiseexcept (int excepts)
OLM_DLLEXPORT int fetestexcept (int __excepts)
OLM_DLLEXPORT int fegetround (void)
OLM_DLLEXPORT int fesetround (int __round)
int fegetenv (fenv_t *envp)
int feholdexcept (fenv_t *envp)
OLM_DLLEXPORT int fesetenv (const fenv_t *__envp)
OLM_DLLEXPORT int feupdateenv (const fenv_t *envp)
int feenableexcept (int mask)
int fedisableexcept (int mask)
Variables
const fenv_t __fe_dfl_env
enum __sse_support __has_sse
Macro Definition Documentation
__fenv_static
#define __fenv_static
cpuid_dx
#define cpuid_dx (x)
Value:
__asm __volatile("pushl %%ebx\n\tmovl $1, %%eax\n\t"  \
                     "cpuid\n\tpopl %%ebx"            \
                    : "=d" (*(x)) : : "eax", "ecx")
getfl
#define getfl (x) __asm __volatile("pushfl\n\tpopl %0" : "=mr" (*(x)))
setfl
#define setfl (x) __asm __volatile("pushl %0\n\tpopfl" : : "g" (x))
Function Documentation
__test_sse()
int __test_sse (void)
References __has_sse, __SSE_NO, __SSE_YES, cpuid_dx, getfl, and setfl.
feclearexcept()
OLM_DLLEXPORT int feclearexcept (int __excepts) inline
fedisableexcept()
int fedisableexcept (int mask) inline
References __fldcw, __fnstcw, __HAS_SSE, __ldmxcsr, __stmxcsr, _SSE_EMASK_SHIFT, and FE_ALL_EXCEPT.
feenableexcept()
int feenableexcept (int mask) inline
References __fldcw, __fnstcw, __HAS_SSE, __ldmxcsr, __stmxcsr, _SSE_EMASK_SHIFT, and FE_ALL_EXCEPT.
fegetenv()
int fegetenv (fenv_t * envp) inline
References fenv_t::__control, __fldcw, __fnstenv, __HAS_SSE, __set_mxcsr, and __stmxcsr.
fegetexceptflag()
OLM_DLLEXPORT int fegetexceptflag (fexcept_t * __flagp, int __excepts) inline
fegetround()
OLM_DLLEXPORT int fegetround (void) inline
feholdexcept()
int feholdexcept (fenv_t * envp) inline
References __fnclex, __fnstenv, __HAS_SSE, __ldmxcsr, __set_mxcsr, __stmxcsr, _SSE_EMASK_SHIFT, and FE_ALL_EXCEPT.
feraiseexcept()
OLM_DLLEXPORT int feraiseexcept (int excepts) inline
References __fwait, and fesetexceptflag().
fesetenv()
OLM_DLLEXPORT int fesetenv (const fenv_t * __envp) inline
fesetexceptflag()
OLM_DLLEXPORT int fesetexceptflag (const fexcept_t * flagp, int excepts) inline
References __fldenv, __fnstenv, __HAS_SSE, __ldmxcsr, fenv_t::__status, and __stmxcsr.
fesetround()
OLM_DLLEXPORT int fesetround (int __round) inline
fetestexcept()
OLM_DLLEXPORT int fetestexcept (int __excepts) inline
feupdateenv()
OLM_DLLEXPORT int feupdateenv (const fenv_t * envp) inline
References __fnstsw, __HAS_SSE, __stmxcsr, FE_ALL_EXCEPT, feraiseexcept(), and fesetenv().
Variable Documentation
__fe_dfl_env
const fenv_t __fe_dfl_env
Initial value:
= {
    __INITIAL_NPXCW__,
    0x0000,
    0x0000,
    0x1f80,
    0xffffffff,
    { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff }
}
__has_sse
enum __sse_support __has_sse
Initial value:
=
    __SSE_UNK
Referenced by __test_sse().