Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_j1f.c File Reference
e_j1f.c File Reference
#include <assert.h>
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
static float ponef (float)
static float qonef (float)
OLM_DLLEXPORT float __ieee754_j1f (float x)
OLM_DLLEXPORT float __ieee754_y1f (float x)
Variables
static const float huge = 1e30
static const float one = 1.0
static const float invsqrtpi = 5.6418961287e-01
static const float tpi = 6.3661974669e-01
static const float r00 = -6.2500000000e-02
static const float r01 = 1.4070566976e-03
static const float r02 = -1.5995563444e-05
static const float r03 = 4.9672799207e-08
static const float s01 = 1.9153760746e-02
static const float s02 = 1.8594678841e-04
static const float s03 = 1.1771846857e-06
static const float s04 = 5.0463624390e-09
static const float s05 = 1.2354227016e-11
static const float zero = 0.0
static const float U0 [5]
static const float V0 [5]
static const float pr8 [6]
static const float ps8 [5]
static const float pr5 [6]
static const float ps5 [5]
static const float pr3 [6]
static const float ps3 [5]
static const float pr2 [6]
static const float ps2 [5]
static const float qr8 [6]
static const float qs8 [6]
static const float qr5 [6]
static const float qs5 [6]
static const float qr3 [6]
static const float qs3 [6]
static const float qr2 [6]
static const float qs2 [6]
Function Documentation
__ieee754_j1f()
OLM_DLLEXPORT float __ieee754_j1f (float x)
References cosf(), fabsf(), GET_FLOAT_WORD, huge, invsqrtpi, one, ponef(), qonef(), r, r00, r01, r02, r03, s, s01, s02, s03, s04, s05, sinf(), sqrtf(), u, z, and zero.
Referenced by __ieee754_jnf(), and __ieee754_y1f().
__ieee754_y1f()
OLM_DLLEXPORT float __ieee754_y1f (float x)
References __ieee754_j1f(), __ieee754_logf(), cosf(), GET_FLOAT_WORD, invsqrtpi, one, ponef(), qonef(), s, sinf(), sqrtf(), tpi, u, U0, V0, z, and zero.
Referenced by __ieee754_ynf().
ponef()
static float ponef (float x) static
References GET_FLOAT_WORD, one, p, pr2, pr3, pr5, pr8, ps2, ps3, ps5, ps8, r, s, and z.
Referenced by __ieee754_j1f(), and __ieee754_y1f().
qonef()
static float qonef (float x)
References GET_FLOAT_WORD, one, p, qr2, qr3, qr5, qr8, qs2, qs3, qs5, qs8, r, s, and z.
Referenced by __ieee754_j1f(), and __ieee754_y1f().
Variable Documentation
huge
const float huge = 1e30 static
Referenced by __ieee754_j1f().
invsqrtpi
const float invsqrtpi = 5.6418961287e-01 static
Referenced by __ieee754_j1f(), and __ieee754_y1f().
one
const float one = 1.0 static
Referenced by __ieee754_j1f(), __ieee754_y1f(), ponef(), and qonef().
pr2
const float pr2[6] static
Initial value:
= {
  1.0771083225e-07,
  1.1717621982e-01,
  2.3685150146e+00,
  1.2242610931e+01,
  1.7693971634e+01,
  5.0735230446e+00,
}
Referenced by ponef().
pr3
const float pr3[6] static
Initial value:
= {
  3.0250391081e-09,
  1.1718686670e-01,
  3.9329774380e+00,
  3.5119403839e+01,
  9.1055007935e+01,
  4.8559066772e+01,
}
Referenced by ponef().
pr5
const float pr5[6] static
Initial value:
= {
  1.3199052094e-11,
  1.1718749255e-01,
  6.8027510643e+00,
  1.0830818176e+02,
  5.1763616943e+02,
  5.2871520996e+02,
}
Referenced by ponef().
pr8
const float pr8[6] static
Initial value:
= {
  0.0000000000e+00,
  1.1718750000e-01,
  1.3239480972e+01,
  4.1205184937e+02,
  3.8747453613e+03,
  7.9144794922e+03,
}
Referenced by ponef().
ps2
const float ps2[5] static
Initial value:
= {
  2.1436485291e+01,
  1.2529022980e+02,
  2.3227647400e+02,
  1.1767937469e+02,
  8.3646392822e+00,
}
Referenced by ponef().
ps3
const float ps3[5] static
Initial value:
= {
  3.4791309357e+01,
  3.3676245117e+02,
  1.0468714600e+03,
  8.9081134033e+02,
  1.0378793335e+02,
}
Referenced by ponef().
ps5
const float ps5[5] static
Initial value:
= {
  5.9280597687e+01,
  9.9140142822e+02,
  5.3532670898e+03,
  7.8446904297e+03,
  1.5040468750e+03,
}
Referenced by ponef().
ps8
const float ps8[5] static
Initial value:
= {
  1.1420736694e+02,
  3.6509309082e+03,
  3.6956207031e+04,
  9.7602796875e+04,
  3.0804271484e+04,
}
Referenced by ponef().
qr2
const float qr2[6] static
Initial value:
= {
 -1.7838172539e-07,
 -1.0251704603e-01,
 -2.7522056103e+00,
 -1.9663616180e+01,
 -4.2325313568e+01,
 -2.1371921539e+01,
}
Referenced by qonef().
qr3
const float qr3[6] static
Initial value:
= {
 -5.0783124372e-09,
 -1.0253783315e-01,
 -4.6101160049e+00,
 -5.7847221375e+01,
 -2.2824453735e+02,
 -2.1921012878e+02,
}
Referenced by qonef().
qr5
const float qr5[6] static
Initial value:
= {
 -2.0897993405e-11,
 -1.0253904760e-01,
 -8.0564479828e+00,
 -1.8366960144e+02,
 -1.3731937256e+03,
 -2.6124443359e+03,
}
Referenced by qonef().
qr8
const float qr8[6] static
Initial value:
= {
  0.0000000000e+00,
 -1.0253906250e-01,
 -1.6271753311e+01,
 -7.5960174561e+02,
 -1.1849806641e+04,
 -4.8438511719e+04,
}
Referenced by qonef().
qs2
const float qs2[6] static
Initial value:
= {
  2.9533363342e+01,
  2.5298155212e+02,
  7.5750280762e+02,
  7.3939318848e+02,
  1.5594900513e+02,
 -4.9594988823e+00,
}
Referenced by qonef().
qs3
const float qs3[6] static
Initial value:
= {
  4.7665153503e+01,
  6.7386511230e+02,
  3.3801528320e+03,
  5.5477290039e+03,
  1.9031191406e+03,
 -1.3520118713e+02,
}
Referenced by qonef().
qs5
const float qs5[6] static
Initial value:
= {
  8.1276550293e+01,
  1.9917987061e+03,
  1.7468484375e+04,
  4.9851425781e+04,
  2.7948074219e+04,
 -4.7191835938e+03,
}
Referenced by qonef().
qs8
const float qs8[6] static
Initial value:
= {
  1.6139537048e+02,
  7.8253862305e+03,
  1.3387534375e+05,
  7.1965775000e+05,
  6.6660125000e+05,
 -2.9449025000e+05,
}
Referenced by qonef().
r00
const float r00 = -6.2500000000e-02 static
Referenced by __ieee754_j1f().
r01
const float r01 = 1.4070566976e-03 static
Referenced by __ieee754_j1f().
r02
const float r02 = -1.5995563444e-05 static
Referenced by __ieee754_j1f().
r03
const float r03 = 4.9672799207e-08 static
Referenced by __ieee754_j1f().
s01
const float s01 = 1.9153760746e-02 static
Referenced by __ieee754_j1f().
s02
const float s02 = 1.8594678841e-04 static
Referenced by __ieee754_j1f().
s03
const float s03 = 1.1771846857e-06 static
Referenced by __ieee754_j1f().
s04
const float s04 = 5.0463624390e-09 static
Referenced by __ieee754_j1f().
s05
const float s05 = 1.2354227016e-11 static
Referenced by __ieee754_j1f().
tpi
const float tpi = 6.3661974669e-01 static
Referenced by __ieee754_y1f().
U0
const float U0[5] static
Initial value:
= {
 -1.9605709612e-01,
  5.0443872809e-02,
 -1.9125689287e-03,
  2.3525259166e-05,
 -9.1909917899e-08,
}
Referenced by __ieee754_y1f().
V0
const float V0[5] static
Initial value:
= {
  1.9916731864e-02,
  2.0255257550e-04,
  1.3560879779e-06,
  6.2274145840e-09,
  1.6655924903e-11,
}
Referenced by __ieee754_y1f().
zero
const float zero = 0.0 static
Referenced by __ieee754_j1f(), and __ieee754_y1f().