Embedded Artistry Framework: src/stdlibs/libc/test/stdlib/div.c File Reference
div.c File Reference
#include "stdlib_tests.h"
#include <stdlib.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Functions
static void div_test (void **__attribute__((unused)) state)
int div_tests (void)
Variables
struct {
uint64_t x
uint64_t y
uint64_t div
uint64_t mod
} t []
Function Documentation
div_test()
static void div_test (void **__attribute__((unused)) state) static
References div(), and t.
Referenced by div_tests().
div_tests()
int div_tests (void)
References div_test(), div_tests(), and NULL.
Referenced by div_tests(), and stdlib_tests().
Variable Documentation
t
struct { ... } t[]
Referenced by div_test().