Embedded Artistry libc: src/string/strlen.c File Reference
strlen.c File Reference
#include <limits.h>
#include <string.h>
Macros
#define LONGPTR_MASK (sizeof(long) - 1)
#define testbyte(x)
Functions
size_t strlen (const char *str)
Returns the length of the given null-terminated byte string.
Macro Definition Documentation
LONGPTR_MASK
#define LONGPTR_MASK (sizeof(long) - 1)
Definition at line 64 of file strlen.c.
testbyte
#define testbyte (x)
Value:
do                                                  \
    {                                                   \
        if(p[x] == '\0')                                \
            return ((uintptr_t)p - (uintptr_t)str + x); \
    } while(0)
Definition at line 70 of file strlen.c.
Function Documentation
strlen()
size_t strlen (const char * str)
Returns the length of the given null-terminated byte string.
Returns the length of the given null-terminated byte string, that is, the number of characters in a character array whose first element is pointed to by str up to and not including the first null character.
The behavior is undefined if str is not a pointer to a null-terminated byte string.
Parameters
str pointer to the null-terminated byte string to be examined
Returns
The length of the null-terminated byte string str.
Definition at line 77 of file strlen.c.
 {
     const char* p;
     const unsigned long* lp;
     /* Skip the first few bytes until we have an aligned p */
     for(p = str; (uintptr_t)p & LONGPTR_MASK; p++)
     {
         if(*p == '\0')
         {
             return ((uintptr_t)p - (uintptr_t)str);
         }
     }
     /* Scan the rest of the string using word sized operation */
     // Cast to void to prevent alignment warning
     for(lp = (const unsigned long*)(const void*)p;; lp++)
     {
         if((*lp - mask01) & mask80)
         {
             p = (const char*)(lp);
             testbyte(0);
             testbyte(1);
             testbyte(2);
             testbyte(3);
 #if(LONG_BIT >= 64)
             testbyte(4);
             testbyte(5);
             testbyte(6);
             testbyte(7);
 #endif
         }
     }
     /* NOTREACHED */
     // return (0);
 }
References LONGPTR_MASK, and testbyte.
Referenced by __strchrnul(), strcat(), strcpy(), strdup(), strerror_r(), strncat(), strnstr(), strrchr(), and strxfrm().