Embedded Artistry libc: src/stdlib/qsort.c File Reference
qsort.c File Reference
#include <stdlib.h>
#include <string.h>
#include <strings.h>
Macros
#define min(a, b) (a) < (b) ? a : b
#define swapcode(TYPE, parmi, parmj, n)
#define SWAPINIT(a, es)
#define swap(a, b)
#define vecswap(a, b, n)
#define CMP(t, x, y) (cmp((x), (y)))
#define DEPTH(x) (2 * (fls((int)(x)) - 1))
#define thunk NULL
Typedefs
typedef int cmp_t(const void *, const void *)
Functions
static char * med3 (char *, char *, char *, cmp_t *, void *)
static char * med3 (char *a, char *b, char *c, cmp_t *cmp, void *thunk __attribute__((unused)))
static void _qsort (void *a, size_t n, size_t es, #define thunk cmp_t *cmp, int depth_limit)
void qsort (void *a, size_t n, size_t es, cmp_t *cmp)
Macro Definition Documentation
CMP
#define CMP (t, x, y) (cmp((x), (y)))
Definition at line 89 of file qsort.c.
Referenced by _qsort(), and med3().
DEPTH
#define DEPTH (x) (2 * (fls((int)(x)) - 1))
Definition at line 105 of file qsort.c.
Referenced by qsort().
min
#define min (a, b) (a) < (b) ? a : b
Referenced by _qsort().
swap
#define swap (a, b)
Value:
if(swaptype == 0)              \
    {                              \
        long t = *(long*)(a);      \
        *(long*)(a) = *(long*)(b); \
        *(long*)(b) = t;           \
    }                              \
    else                           \
        swapfunc(a, b, es, swaptype)
Definition at line 72 of file qsort.c.
Referenced by _qsort(), and strtoIg().
swapcode
#define swapcode (TYPE, parmi, parmj, n)
Value:
{                                   \
        long i = (n) / sizeof(TYPE);    \
        TYPE* pi = (TYPE*)(parmi);      \
        TYPE* pj = (TYPE*)(parmj);      \
        do                              \
        {                               \
            TYPE t = *pi;               \
            *pi++ = *pj;                \
            *pj++ = t;                  \
        } while(--i > 0);               \
    }
SWAPINIT
#define SWAPINIT (a, es)
Value:
swaptype = ((char*)a - (char*)0) % sizeof(long) || es % sizeof(long) \
                   ? 2                                                   \
                   : es == sizeof(long) ? 0 : 1;
Referenced by _qsort().
thunk
#define thunk NULL
Referenced by _qsort(), and med3().
vecswap
#define vecswap (a, b, n)
Value:
if((n) > 0)          \
    swapfunc(a, b, n, swaptype)
Definition at line 82 of file qsort.c.
Referenced by _qsort().
Typedef Documentation
cmp_t
typedef int cmp_t(const void *, const void *)
Definition at line 37 of file qsort.c.
Function Documentation
_qsort()
static void _qsort (void * a, size_t n, size_t es, #define thunk cmp_t * cmp, int depth_limit) static
Definition at line 112 of file qsort.c.
References CMP, heapsort(), heapsort_r(), med3(), min, qsort_r(), swap, SWAPINIT, thunk, and vecswap.
Referenced by qsort().
 {
     char *pa, *pb, *pc, *pd, *pl, *pm, *pn;
     size_t d, r;
     int cmp_result;
     int swaptype, swap_cnt;
 loop:
     if(depth_limit-- <= 0)
     {
 #ifdef I_AM_QSORT_R
         heapsort_r(a, n, es, thunk, cmp);
 #else
         heapsort(a, n, es, cmp);
 #endif
         return;
     }
     SWAPINIT(a, es);
     swap_cnt = 0;
     if(n < 7)
     {
         for(pm = (char*)a + es; pm < (char*)a + n * es; pm += es)
             for(pl = pm; pl > (char*)a && CMP(thunk, pl - es, pl) > 0; pl -= es)
                 swap(pl, pl - es);
         return;
     }
     pm = (char*)a + (n / 2) * es;
     if(n > 7)
     {
         pl = a;
         pn = (char*)a + (n - 1) * es;
         if(n > 40)
         {
             d = (n / 8) * es;
             pl = med3(pl, pl + d, pl + 2 * d, cmp, thunk);
             pm = med3(pm - d, pm, pm + d, cmp, thunk);
             pn = med3(pn - 2 * d, pn - d, pn, cmp, thunk);
         }
         pm = med3(pl, pm, pn, cmp, thunk);
     }
     swap(a, pm);
     pa = pb = (char*)a + es;
     pc = pd = (char*)a + (n - 1) * es;
     for(;;)
     {
         while(pb <= pc && (cmp_result = CMP(thunk, pb, a)) <= 0)
         {
             if(cmp_result == 0)
             {
                 swap_cnt = 1;
                 swap(pa, pb);
                 pa += es;
             }
             pb += es;
         }
         while(pb <= pc && (cmp_result = CMP(thunk, pc, a)) >= 0)
         {
             if(cmp_result == 0)
             {
                 swap_cnt = 1;
                 swap(pc, pd);
                 pd -= es;
             }
             pc -= es;
         }
         if(pb > pc)
             break;
         swap(pb, pc);
         swap_cnt = 1;
         pb += es;
         pc -= es;
     }
     pn = (char*)a + n * es;
     r = min(pa - (char*)a, pb - pa);
     vecswap(a, pb - r, r);
     r = min(pd - pc, pn - pd - es);
     vecswap(pb, pn - r, r);
     if(swap_cnt == 0)
     { /* Switch to insertion sort */
         r = 1 + n / 4; /* n >= 7, so r >= 2 */
         for(pm = (char*)a + es; pm < (char*)a + n * es; pm += es)
             for(pl = pm; pl > (char*)a && CMP(thunk, pl - es, pl) > 0; pl -= es)
             {
                 swap(pl, pl - es);
                 if(++swap_cnt > r)
                     goto nevermind;
             }
         return;
     }
 nevermind:
     if((r = pb - pa) > es)
 #ifdef I_AM_QSORT_R
         _qsort(a, r / es, es, thunk, cmp, depth_limit);
 #else
         _qsort(a, r / es, es, cmp, depth_limit);
 #endif
     if((r = pd - pc) > es)
     {
         /* Iterate rather than recurse to save stack space */
         a = pn - r;
         n = r / es;
         goto loop;
     }
     /*      qsort(pn - r, r / es, es, cmp);*/
 }
med3() [1/2]
static char* med3 (char * , char * , char * , cmp_t * , void *) inline static
Definition at line 39 of file qsort.c.
Referenced by _qsort().
                                 : b
 /*
  * Qsort routine from Bentley & McIlroy's "Engineering a Sort Function".
  */
 #define swapcode(TYPE, parmi, parmj, n) \
     {                                   \
         long i = (n) / sizeof(TYPE);    \
         TYPE* pi = (TYPE*)(parmi);      \
         TYPE* pj = (TYPE*)(parmj);      \
         do                              \
         {                               \
             TYPE t = *pi;               \
             *pi++ = *pj;                \
             *pj++ = t;                  \
         } while(--i > 0);               \
     }
 #define SWAPINIT(a, es)                                                  \
     swaptype = ((char*)a - (char*)0) % sizeof(long) || es % sizeof(long) \
                    ? 2                                                   \
                    : es == sizeof(long) ? 0 : 1;
 static inline void swapfunc(a, b, n, swaptype) char *a, *b;
 int n, swaptype;
 {
     if(swaptype <= 1)
         swapcode(long, a, b, n) else swapcode(char, a, b, n)
 }
med3() [2/2]
static char* med3 (char * a, char * b, char * c, cmp_t * cmp, void *thunk __attribute__(unused)) inline static
Definition at line 92 of file qsort.c.
References CMP, and thunk.
 {
     return CMP(thunk, a, b) < 0 ? (CMP(thunk, b, c) < 0 ? b : (CMP(thunk, a, c) < 0 ? c : a))
                                 : (CMP(thunk, b, c) > 0 ? b : (CMP(thunk, a, c) < 0 ? a : c));
 }
qsort()
void qsort (void * a, size_t n, size_t es, cmp_t * cmp)
Definition at line 232 of file qsort.c.
References _qsort(), DEPTH, and I_AM_QSORT_R.
 {
     _qsort(a, n, es,
 #ifdef I_AM_QSORT_R
            thunk,
 #endif
            cmp, DEPTH(n));
 }