Embedded Artistry Framework: src/stdlibs/libc/include/locale.h File Reference
locale.h File Reference
Classes
struct lconv
Macros
#define LC_CTYPE 0
#define LC_NUMERIC 1
#define LC_TIME 2
#define LC_COLLATE 3
#define LC_MONETARY 4
#define LC_MESSAGES 5
#define LC_ALL 6
Functions
char * setlocale (int, const char *)
struct lconv * localeconv (void)
Class Documentation
lconv
struct lconv
Class Members
char * currency_symbol
char * decimal_point
char frac_digits
char * grouping
char * int_curr_symbol
char int_frac_digits
char int_n_cs_precedes
char int_n_sep_by_space
char int_n_sign_posn
char int_p_cs_precedes
char int_p_sep_by_space
char int_p_sign_posn
char * mon_decimal_point
char * mon_grouping
char * mon_thousands_sep
char n_cs_precedes
char n_sep_by_space
char n_sign_posn
char * negative_sign
char p_cs_precedes
char p_sep_by_space
char p_sign_posn
char * positive_sign
char * thousands_sep
Macro Definition Documentation
LC_ALL
#define LC_ALL 6
LC_COLLATE
#define LC_COLLATE 3
LC_CTYPE
#define LC_CTYPE 0
LC_MESSAGES
#define LC_MESSAGES 5
LC_MONETARY
#define LC_MONETARY 4
LC_NUMERIC
#define LC_NUMERIC 1
LC_TIME
#define LC_TIME 2
Function Documentation
localeconv()
struct lconv* localeconv (void)
Referenced by g__fmt(), gethex(), strtod(), and strtodg().
setlocale()
char* setlocale (int , const char *)