Embedded Artistry libc: include/wctype.h File Reference
wctype.h File Reference
#include <_types/_wchar_t.h>
Macros
#define WEOF 0xffffffffU
#define WCTYPE_ALNUM 1
#define WCTYPE_ALPHA 2
#define WCTYPE_BLANK 3
#define WCTYPE_CNTRL 4
#define WCTYPE_DIGIT 5
#define WCTYPE_GRAPH 6
#define WCTYPE_LOWER 7
#define WCTYPE_PRINT 8
#define WCTYPE_PUNCT 9
#define WCTYPE_SPACE 10
#define WCTYPE_UPPER 11
#define WCTYPE_XDIGIT 12
Typedefs
typedef const int * wctrans_t
typedef unsigned wint_t
typedef unsigned long wctype_t
Functions
int iswalnum (wint_t)
int iswalpha (wint_t)
int iswblank (wint_t)
int iswcntrl (wint_t)
int iswctype (wint_t, wctype_t)
int iswdigit (wint_t)
int iswgraph (wint_t)
int iswlower (wint_t)
int iswprint (wint_t)
int iswpunct (wint_t)
int iswspace (wint_t)
int iswupper (wint_t)
int iswxdigit (wint_t)
wint_t towctrans (wint_t, wctrans_t)
wint_t towlower (wint_t)
wint_t towupper (wint_t)
wctrans_t wctrans (const char *)
wctype_t wctype (const char *)
Macro Definition Documentation
WCTYPE_ALNUM
#define WCTYPE_ALNUM 1
Definition at line 17 of file wctype.h.
WCTYPE_ALPHA
#define WCTYPE_ALPHA 2
Definition at line 18 of file wctype.h.
WCTYPE_BLANK
#define WCTYPE_BLANK 3
Definition at line 19 of file wctype.h.
WCTYPE_CNTRL
#define WCTYPE_CNTRL 4
Definition at line 20 of file wctype.h.
WCTYPE_DIGIT
#define WCTYPE_DIGIT 5
Definition at line 21 of file wctype.h.
WCTYPE_GRAPH
#define WCTYPE_GRAPH 6
Definition at line 22 of file wctype.h.
WCTYPE_LOWER
#define WCTYPE_LOWER 7
Definition at line 23 of file wctype.h.
WCTYPE_PRINT
#define WCTYPE_PRINT 8
Definition at line 24 of file wctype.h.
WCTYPE_PUNCT
#define WCTYPE_PUNCT 9
Definition at line 25 of file wctype.h.
WCTYPE_SPACE
#define WCTYPE_SPACE 10
Definition at line 26 of file wctype.h.
WCTYPE_UPPER
#define WCTYPE_UPPER 11
Definition at line 27 of file wctype.h.
WCTYPE_XDIGIT
#define WCTYPE_XDIGIT 12
Definition at line 28 of file wctype.h.
WEOF
#define WEOF 0xffffffffU
Definition at line 15 of file wctype.h.
Typedef Documentation
wctrans_t
typedef const int* wctrans_t
Definition at line 10 of file wctype.h.
wctype_t
typedef unsigned long wctype_t
Definition at line 12 of file wctype.h.
wint_t
typedef unsigned wint_t
Definition at line 11 of file wctype.h.
Function Documentation
iswalnum()
int iswalnum (wint_t)
Definition at line 3 of file iswalnum.c.
 {
     return iswdigit(wc) || iswalpha(wc);
 }
References iswalpha(), and iswdigit().
Referenced by iswctype().
iswalpha()
int iswalpha (wint_t)
Definition at line 7 of file iswalpha.c.
 {
     if(wc < 0x20000U)
     {
         return (table[table[wc >> 8] * 32 + ((wc & 255) >> 3)] >> (wc & 7)) & 1;
     }
     if(wc < 0x2fffeU)
     {
         return 1;
     }
     return 0;
 }
References table.
Referenced by __towcase(), iswalnum(), and iswctype().
iswblank()
int iswblank (wint_t)
Definition at line 4 of file iswblank.c.
 {
     return isblank((int)wc);
 }
References isblank().
Referenced by iswctype().
iswcntrl()
int iswcntrl (wint_t)
Definition at line 3 of file iswcntrl.c.
 {
     return (unsigned)wc < 32 || (unsigned)(wc - 0x7f) < 33 || (unsigned)(wc - 0x2028) < 2 ||
            (unsigned)(wc - 0xfff9) < 3;
 }
Referenced by iswctype().
iswctype()
int iswctype (wint_t , wctype_t)
Definition at line 4 of file iswctype.c.
 {
     switch(type)
     {
         case WCTYPE_ALNUM:
             return iswalnum(wc);
         case WCTYPE_ALPHA:
             return iswalpha(wc);
         case WCTYPE_BLANK:
             return iswblank(wc);
         case WCTYPE_CNTRL:
             return iswcntrl(wc);
         case WCTYPE_DIGIT:
             return iswdigit(wc);
         case WCTYPE_GRAPH:
             return iswgraph(wc);
         case WCTYPE_LOWER:
             return iswlower(wc);
         case WCTYPE_PRINT:
             return iswprint(wc);
         case WCTYPE_PUNCT:
             return iswpunct(wc);
         case WCTYPE_SPACE:
             return iswspace(wc);
         case WCTYPE_UPPER:
             return iswupper(wc);
         case WCTYPE_XDIGIT:
             return iswxdigit(wc);
     }
     return 0;
 }
References iswalnum(), iswalpha(), iswblank(), iswcntrl(), iswdigit(), iswgraph(), iswlower(), iswprint(), iswpunct(), iswspace(), iswupper(), iswxdigit(), WCTYPE_ALNUM, WCTYPE_ALPHA, WCTYPE_BLANK, WCTYPE_CNTRL, WCTYPE_DIGIT, WCTYPE_GRAPH, WCTYPE_LOWER, WCTYPE_PRINT, WCTYPE_PUNCT, WCTYPE_SPACE, WCTYPE_UPPER, and WCTYPE_XDIGIT.
iswdigit()
int iswdigit (wint_t)
Definition at line 3 of file iswdigit.c.
 {
     return (unsigned)wc - '0' < 10;
 }
Referenced by iswalnum(), and iswctype().
iswgraph()
int iswgraph (wint_t)
Definition at line 3 of file iswgraph.c.
 {
     /* ISO C defines this function as: */
     return !iswspace(wc) && iswprint(wc);
 }
References iswprint(), and iswspace().
Referenced by iswctype().
iswlower()
int iswlower (wint_t)
Definition at line 3 of file iswlower.c.
 {
     return towupper(wc) != wc;
 }
References towupper().
Referenced by iswctype().
iswprint()
int iswprint (wint_t)
Definition at line 10 of file iswprint.c.
 {
     if(wc < 0xffU)
     {
         return (wc + 1 & 0x7f) >= 0x21;
     }
     if(wc < 0x2028U || wc - 0x202aU < 0xd800 - 0x202a || wc - 0xe000U < 0xfff9 - 0xe000)
     {
         return 1;
     }
     if(wc - 0xfffcU > 0x10ffff - 0xfffc || (wc & 0xfffe) == 0xfffe)
     {
         return 0;
     }
     return 1;
 }
Referenced by iswctype(), and iswgraph().
iswpunct()
int iswpunct (wint_t)
Definition at line 7 of file iswpunct.c.
 {
     if(wc < 0x20000U)
     {
         return (table[table[wc >> 8] * 32 + ((wc & 255) >> 3)] >> (wc & 7)) & 1;
     }
     return 0;
 }
References table.
Referenced by iswctype().
iswspace()
int iswspace (wint_t)
Definition at line 8 of file iswspace.c.
 {
     static const wchar_t spaces[] = {' ',   '\t',   '\n',   '\r',   11,  12,     0x0085, 0x2000,
                                      0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2008, 0x2009,
                                      0x200a, 0x2028, 0x2029, 0x205f, 0x3000, 0};
     return wc && wcschr(spaces, (wchar_t)wc);
 }
References wcschr().
Referenced by iswctype(), and iswgraph().
iswupper()
int iswupper (wint_t)
Definition at line 3 of file iswupper.c.
 {
     return towlower(wc) != wc;
 }
References towlower().
Referenced by iswctype().
iswxdigit()
int iswxdigit (wint_t)
Definition at line 3 of file iswxdigit.c.
 {
     return (unsigned)(wc - '0') < 10 || (unsigned)((wc | 32) - 'a') < 6;
 }
Referenced by iswctype().
towctrans()
wint_t towctrans (wint_t , wctrans_t)
Definition at line 4 of file towctrans.c.
 {
     if(trans == (wctrans_t)1)
     {
         return towupper(wc);
     }
     if(trans == (wctrans_t)2)
     {
         return towlower(wc);
     }
     return wc;
 }
References towlower(), and towupper().
towlower()
wint_t towlower (wint_t)
Definition at line 4 of file towlower.c.
 {
     return (wint_t)(wc < 128 ? tolower((int)wc) : __towcase((wchar_t)wc, 1));
 }
References __towcase(), and tolower().
Referenced by iswupper(), and towctrans().
towupper()
wint_t towupper (wint_t)
Definition at line 4 of file towupper.c.
 {
     return (wint_t)(wc < 128 ? toupper((int)wc) : __towcase((wchar_t)wc, 0));
 }
References __towcase(), and toupper().
Referenced by iswlower(), and towctrans().
wctrans()
wctrans_t wctrans (const char *)
Definition at line 4 of file wctrans.c.
 {
     if(!strcmp(class, "toupper"))
     {
         return (wctrans_t)1;
     }
     if(!strcmp(class, "tolower"))
     {
         return (wctrans_t)2;
     }
     return 0;
 }
References strcmp().
wctype()
wctype_t wctype (const char *)
Definition at line 4 of file wctype.c.
 {
     wctype_t i;
     const char* p;
     /* order must match! */
     static const char names[] = "alnum\0"
                                 "alpha\0"
                                 "blank\0"
                                 "cntrl\0"
                                 "digit\0"
                                 "graph\0"
                                 "lower\0"
                                 "print\0"
                                 "punct\0"
                                 "space\0"
                                 "upper\0"
                                 "xdigit";
     for(i = 1, p = names; *p; i++, p += 6)
     {
         if(*s == *p && !strcmp(s, p))
         {
             return i;
         }
     }
     return 0;
 }
References strcmp().