Embedded Artistry Framework: src/stdlibs/libc/test/string/memmem.c File Reference
memmem.c File Reference
#include "string_tests.h"
#include <string.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Macros
#define N(s, tail, sub)
#define T(s, sub, n)
#define T_NULL(s, sub, n)
Functions
static void check_input (void **state)
int memmem_tests (void)
Macro Definition Documentation
N
#define N (s, tail, sub)
Value:
{                                                     \
        char* p = s tail;                                 \
        char* q = memmem(p, strlen(s), sub, strlen(sub)); \
        assert_ptr_equal(q, NULL);                        \
    }
T
#define T (s, sub, n)
Value:
{                                                     \
        char* p = s;                                      \
        char* q = memmem(p, strlen(p), sub, strlen(sub)); \
        assert_ptr_not_equal(q, NULL);                    \
        assert_ptr_equal(q - p, n);                       \
    }
T_NULL
#define T_NULL (s, sub, n)
Value:
{                                                     \
        char* p = s;                                      \
        char* q = memmem(p, strlen(p), sub, strlen(sub)); \
        assert_ptr_equal(q, NULL);                        \
    }
Function Documentation
check_input()
static void check_input (void ** state) static
References N, T, and T_NULL.
Referenced by memmem_tests().
memmem_tests()
int memmem_tests (void)
References check_input(), memmem_tests(), and NULL.
Referenced by memmem_tests(), and string_tests().