Embedded Artistry Framework: src/stdlibs/libc/test/string/strncat.c File Reference
strncat.c File Reference
#include "string_tests.h"
#include <string.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Functions
static void strncat_test (void **state)
int strncat_tests (void)
Function Documentation
strncat_test()
static void strncat_test (void ** state) static
References b, strcmp(), strcpy(), and strncat().
Referenced by strncat_tests().
strncat_tests()
int strncat_tests (void)
References NULL, and strncat_test().
Referenced by string_tests().