Embedded Artistry libc: src/stdio/putchar_native.c File Reference
putchar_native.c File Reference
#include <printf.h>
#include <stdio.h>
Functions
long write (int, const char *, unsigned long)
void _putchar (char ch)
Function Documentation
_putchar()
void _putchar (char ch)
Definition at line 6 of file putchar_native.c.
 {
     (void)write(1, &ch, 1);
 }
References write().
Referenced by putchar().
write()
long write (int , const char * , unsigned long)
Referenced by _putchar().