Embedded Artistry libc: src/gdtoa/src/gmisc.c File Reference
gmisc.c File Reference
#include "gdtoaimp.h"
Functions
void rshift (Bigint *b, int k)
int trailz (Bigint *b)
Function Documentation
rshift()
void rshift (Bigint * b, int k)
Definition at line 38 of file gmisc.c.
References ALL_ON, kmask, kshift, trailz(), ULbits, Bigint::wds, and Bigint::x.
Referenced by g_ddfmt(), gdtoa(), gethex(), rvOK(), strtodg(), and strtoIg().
 {
     ULong *x, *x1, *xe, y;
     int n;
     x = x1 = b->x;
     n = k >> kshift;
     if (n < b->wds) {
         xe = x + b->wds;
         x += n;
         if (k &= kmask) {
             n = ULbits - k;
             y = *x++ >> k;
             while(x < xe) {
                 *x1++ = (y | (*x << n)) & ALL_ON;
                 y = *x++ >> k;
                 }
             if ((*x1 = y) !=0)
                 x1++;
             }
         else
             while(x < xe)
                 *x1++ = *x++;
         }
     if ((b->wds = x1 - b->x) == 0)
         b->x[0] = 0;
     }
trailz()
int trailz (Bigint * b)
Definition at line 71 of file gmisc.c.
References lo0bits(), ULbits, Bigint::wds, and Bigint::x.
Referenced by gdtoa(), rshift(), and strtodg().
 {
     ULong L, *x, *xe;
     int n = 0;
     x = b->x;
     xe = x + b->wds;
     for(n = 0; x < xe && !*x; x++)
         n += ULbits;
     if (x < xe) {
         L = *x;
         n += lo0bits(&L);
         }
     return n;
     }