Embedded Artistry Framework: src/stdlibs/libc/src/ctype/isspace.c File Reference
isspace.c File Reference
#include <ctype.h>
Functions
int isspace (int c)
Checks if the given character is a whitespace character.
Function Documentation
isspace()
int isspace (int ch)
Checks if the given character is a whitespace character.
Checks if the given character is a whitespace character. The following are examples of a whitespace character:
space (0x20)
feed (0x0c)
line feed (0x0a)
carriage return (0x0d)
horizontal tab (0x09)
vertical tab (0x0b)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a whitespace character, zero otherwise.
Referenced by atol(), atoll(), bad_input(), good_input(), strtol(), strtoll(), strtoul(), and strtoull().