Embedded Artistry Framework: nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking > Class Template Reference
nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking > Class Template Reference final
DMA-capable I2C master (TBlocking)
#include <nrf52_i2c_master.hpp>
Public Types
using cb_t = stdext::inplace_function< void(i2c::op_t, i2c::status)>
Represents the type of the callback operation.
using sweep_list_t = etl::vector< uint8_t, 128 >
using sweep_cb_t = stdext::inplace_function< void(void)>
Public Member Functions
nRFi2cMaster (uint8_t priority=PRIORITY_DEFAULT) noexcept
nRFi2cMaster (const char *name, uint8_t priority=PRIORITY_DEFAULT) noexcept
~nRFi2cMaster ()=default
virtual void configure (i2c::baud baud, i2c::pullups pull=i2c::pullups::external) noexcept
Configure the I2C bus.
i2c::state state () const noexcept
Check the I2C bus status.
i2c::pullups pullups (i2c::pullups pullups) noexcept
Configure pull-ups.
i2c::pullups pullups () const noexcept
Check the pull-up configuration.
void sweep (sweep_list_t &found_list, const sweep_cb_t &cb) noexcept
Perform an I2C bus sweep to identify active devices.
void start () noexcept
Start the driver.
void stop () noexcept
Stop the driver.
void restart () noexcept
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
void setBottomHalfDispatcher (const embutil::IRQDispatcherFunc_t &dispatcher) noexcept
template<typename TCallback >
void invokeCallback (TCallback &cb) noexcept
template<typename TCallback , typename... TArgs>
void invokeCallback (TCallback &cb, TArgs &... args) noexcept
Static Public Member Functions
static constexpr embvm::DriverType type () noexcept
I2C Driver Type ID.
Static Public Attributes
static constexpr uint8_t PRIORITY_DEFAULT = NRF_IRQ_PRIOR_MID
Protected Attributes
i2c::pullups pullups_ = i2c::pullups::external
Tracks the active pull-up configuration.
i2c::state state_ = i2c::state::idle
Tracks the status of the I2C bus.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
embutil::IRQDispatcherFunc_t dispatcher_
Private Member Functions
void start_ () noexcept final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () noexcept final
Derived classes override the start_ method to control driver-specific startup behavior.
void configure_ (embvm::i2c::pullups pullup) noexcept final
Configure the I2C bus for operation.
embvm::i2c::status transfer_ (const embvm::i2c::op_t &op, const embvm::i2c::master::cb_t &cb) noexcept final
template<typename Dummy = embvm::i2c::status>
auto transfer_impl_ (const embvm::i2c::op_t &op, const embvm::i2c::master::cb_t &cb) noexcept -> std::enable_if_t< TBlocking, Dummy >
Blocking Variant.
template<typename Dummy = embvm::i2c::status>
auto transfer_impl_ (const embvm::i2c::op_t &op, const embvm::i2c::master::cb_t &cb) noexcept -> std::enable_if_t<!TBlocking, Dummy >
Non-blocking variant.
embvm::i2c::baud baudrate_ (embvm::i2c::baud baud) noexcept final
embvm::i2c::pullups setPullups_ (embvm::i2c::pullups pullups) noexcept final
Configure pull-ups.
void enableInterrupts () noexcept final
void disableInterrupts () noexcept final
void twim_callback_ (embvm::i2c::status status) noexcept
Private Attributes
const uint8_t priority_
bool busy_ = false
embvm::i2c::master::cb_t active_cb_ {nullptr}
embvm::i2c::op_t active_op_ {}
Detailed Description
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false>
class nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >
DMA-capable I2C master (TBlocking)
Template Parameters
TTWIIndex The instance of the TWI to use. Can be NordicTWIM0 or NordicTWIM1
TSclPin A class representing the SCL pin. This is designed for use with nRFPinID<>:
nRFi2cMaster_TBlocking<0, nRFPinID<0,27>, nRFPinID<0,26>> i2c0;
TSdaPin A class representing the SDA pin. This is designed for use with nRFPinID<>:
nRFi2cMaster_TBlocking<0, nRFPinID<0,27>, nRFPinID<0,26>> i2c0;
Member Typedef Documentation
cb_t
using embvm::i2c::master::cb_t = stdext::inplace_function<void(i2c::op_t, i2c::status)> inherited
Represents the type of the callback operation.
sweep_cb_t
using embvm::i2c::master::sweep_cb_t = stdext::inplace_function<void(void)> inherited
sweep_list_t
using embvm::i2c::master::sweep_list_t = etl::vector<uint8_t, 128> inherited
Constructor & Destructor Documentation
nRFi2cMaster() [1/2]
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::nRFi2cMaster (uint8_t priority = PRIORITY_DEFAULT) inline noexcept
nRFi2cMaster() [2/2]
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::nRFi2cMaster (const char * name, uint8_t priority = PRIORITY_DEFAULT) inline noexcept
~nRFi2cMaster()
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::~nRFi2cMaster () default
Member Function Documentation
baudrate_()
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> embvm::i2c::baud nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::baudrate_ (embvm::i2c::baud baud) inline final private virtual noexcept
Implements embvm::i2c::master.
configure()
virtual void embvm::i2c::master::configure (i2c::baud baud, i2c::pullups pull = i2c::pullups::external) inline virtual noexcept inherited
Configure the I2C bus.
Configures the I2C bus for operation and sets the target baud rate and pull-ups.
Derived classes must implement the configure_() function to set up the target hardware.
Parameters
baud The target baudrate (as an i2c::baud enumeration rather than integral Hz). TODO: Tolerance - allowed relative tolerance for the resulting baudrate
pull The pullup setting, which defaults to external pull-ups (in hardware).
References embvm::i2c::master::configure_(), and embvm::i2c::master::pullups().
Referenced by embvm::i2c::activeMaster< 128 >::configure_(), and FWDemoSimulatorHWPlatform::init_().
configure_()
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> void nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::configure_ (embvm::i2c::pullups pullups) inline final private virtual noexcept
Configure the I2C bus for operation.
This function is implemented by the derived class. It is responsible for configuring the target hardware for operation.
Parameters
pullups The target pull-up configuration.
Implements embvm::i2c::master.
disableInterrupts()
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> void nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::disableInterrupts () inline final private virtual noexcept
Implements embvm::HALDriverBase.
Referenced by nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::stop_().
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
enableInterrupts()
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> void nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::enableInterrupts () inline final private virtual noexcept
Implements embvm::HALDriverBase.
Referenced by nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::start_().
invokeCallback() [1/2]
template<typename TCallback > void embvm::HALDriverBase::invokeCallback (TCallback & cb) inline noexcept inherited
References embvm::HALDriverBase::dispatcher_.
Referenced by embdrv::SimulatorTimer::timer_thread(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::twim_callback_().
invokeCallback() [2/2]
template<typename TCallback , typename... TArgs> void embvm::HALDriverBase::invokeCallback (TCallback & cb, TArgs &... args) inline noexcept inherited
References embvm::HALDriverBase::dispatcher_.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
pullups() [1/2]
i2c::pullups embvm::i2c::master::pullups (i2c::pullups pullups) inline noexcept inherited
Configure pull-ups.
Parameters
pullups The target pull-up setting.
Returns
The configured pull-up setting.
References embvm::i2c::master::pullups_, and embvm::i2c::master::setPullups_().
Referenced by embvm::i2c::activeMaster< 128 >::setPullups_().
pullups() [2/2]
i2c::pullups embvm::i2c::master::pullups () const inline noexcept inherited
Check the pull-up configuration.
Returns
The configured pull-up setting.
References embvm::i2c::master::pullups_.
Referenced by embvm::i2c::master::configure(), nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::setPullups_(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::setPullups_().
restart()
void embvm::DriverBase::restart () inline noexcept inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
setBottomHalfDispatcher()
void embvm::HALDriverBase::setBottomHalfDispatcher (const embutil::IRQDispatcherFunc_t & dispatcher) inline noexcept inherited
References embvm::HALDriverBase::dispatcher_.
Referenced by BlinkySimulatorHWPlatform::init_(), and FWDemoSimulatorHWPlatform::init_().
setPullups_()
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> embvm::i2c::pullups nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::setPullups_ (embvm::i2c::pullups pullups) inline final private virtual noexcept
Configure pull-ups.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the requested pullup setting.
Parameters
pullups The target pull-up setting.
Returns
The configured pull-up setting.
Implements embvm::i2c::master.
start()
void embvm::DriverBase::start () inline noexcept inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> void nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::start_ () inline final private virtual noexcept
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::i2c::master.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
state()
i2c::state embvm::i2c::master::state () const inline noexcept inherited
Check the I2C bus status.
Returns
the status of the I2C bus as an i2c::state enumeration.
References embvm::i2c::master::state_.
stop()
void embvm::DriverBase::stop () inline noexcept inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> void nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::stop_ () inline final private virtual noexcept
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::i2c::master.
sweep()
void embvm::i2c::master::sweep (sweep_list_t & found_list, const sweep_cb_t & cb) noexcept inherited
Perform an I2C bus sweep to identify active devices.
The sweep function pings all I2C addresses. Devices which ACK are stored in a list and returned via callback.
Parameters
[in,out] found_list Caller's memory which will contain the successfully found ping addresses
[in] cb The callback which will be called to indicate that the sweep is complete. After the cb is called, found_list is valid and can be used by the caller.
References embvm::i2c::op_t::address, embvm::i2c::busy, I2C_ADDR_MAX, and embvm::i2c::op_t::op.
transfer_()
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> embvm::i2c::status nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::transfer_ (const embvm::i2c::op_t & op, const embvm::i2c::master::cb_t & cb) inline final private virtual noexcept
Implements embvm::i2c::master.
transfer_impl_() [1/2]
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> template<typename Dummy = embvm::i2c::status> auto nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::transfer_impl_ (const embvm::i2c::op_t & op, const embvm::i2c::master::cb_t & cb) -> std::enable_if_t<TBlocking, Dummy> inline private noexcept
Blocking Variant.
Referenced by nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::transfer_().
transfer_impl_() [2/2]
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> template<typename Dummy = embvm::i2c::status> auto nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::transfer_impl_ (const embvm::i2c::op_t & op, const embvm::i2c::master::cb_t & cb) -> std::enable_if_t<!TBlocking, Dummy> inline private noexcept
Non-blocking variant.
twim_callback_()
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> void nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::twim_callback_ (embvm::i2c::status status) inline private noexcept
Referenced by nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::start_().
type()
static constexpr embvm::DriverType embvm::i2c::master::type () inline static noexcept inherited
I2C Driver Type ID.
Returns
I2C type ID.
References embvm::I2C.
Member Data Documentation
active_cb_
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> embvm::i2c::master::cb_t nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::active_cb_ {nullptr} private
Referenced by nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::transfer_impl_(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::twim_callback_().
active_op_
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> embvm::i2c::op_t nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::active_op_ {} private
Referenced by nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::transfer_impl_(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::twim_callback_().
busy_
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> bool nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::busy_ = false private
Referenced by nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::transfer_impl_(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::twim_callback_().
dispatcher_
embutil::IRQDispatcherFunc_t embvm::HALDriverBase::dispatcher_ protected inherited
Referenced by embvm::HALDriverBase::invokeCallback(), and embvm::HALDriverBase::setBottomHalfDispatcher().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
priority_
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> const uint8_t nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::priority_ private
Referenced by nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::start_().
PRIORITY_DEFAULT
template<NordicTWIM TTWIIndex, typename TSclPin, typename TSdaPin, bool TBlocking = false> constexpr uint8_t nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >::PRIORITY_DEFAULT = NRF_IRQ_PRIOR_MID static
pullups_
i2c::pullups embvm::i2c::master::pullups_ = i2c::pullups::external protected inherited
Tracks the active pull-up configuration.
Referenced by embvm::i2c::master::pullups().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
state_
i2c::state embvm::i2c::master::state_ = i2c::state::idle protected inherited
Tracks the status of the I2C bus.
Referenced by embvm::i2c::master::state().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
The documentation for this class was generated from the following file:
src/processors/arm/nordic/drivers/nrf52_i2c_master.hpp