Embedded Artistry Framework: src/stdlibs/libc/src/wchar/towupper.c File Reference
towupper.c File Reference
#include "_towcase.h"
#include <ctype.h>
Functions
wint_t towupper (wint_t wc)
Function Documentation
towupper()
wint_t towupper (wint_t wc)
References __towcase(), and toupper().
Referenced by iswlower(), and towctrans().