Embedded Artistry Framework: src/stdlibs/libc/src/math/fabsf.c File Reference
fabsf.c File Reference
#include <math.h>
#include <stdint.h>
Functions
float fabsf (float x)
Function Documentation
fabsf()
float fabsf (float x)
References u.
Referenced by __ieee754_asinf(), __ieee754_atan2f(), __ieee754_coshf(), __ieee754_hypotf(), __ieee754_j0f(), __ieee754_j1f(), __ieee754_jnf(), __ieee754_lgammaf_r(), __ieee754_powf(), __ieee754_remainderf(), __ieee754_sinhf(), _cchshf(), _ctansf(), asinhf(), atanf(), casinf(), cchshf(), ccoshf(), csinhf(), csqrtf(), ctanf(), ctanhf(), erfcf(), erff(), logbf(), remquof(), strtof_test(), and tanhf().