Embedded Artistry Framework: src/stdlibs/libc/test/tests.h File Reference
tests.h File Reference
Functions
int string_tests (void)
int ctype_tests (void)
int stdlib_tests (void)
Function Documentation
ctype_tests()
int ctype_tests (void)
References isalnum_tests(), isalpha_tests(), isascii_tests(), isblank_tests(), iscntrl_tests(), isdigit_tests(), isgraph_tests(), islower_tests(), isprint_tests(), ispunct_tests(), isspace_tests(), isupper_tests(), isxdigit_tests(), toascii_tests(), tolower_tests(), and toupper_tests().
Referenced by main().
stdlib_tests()
int stdlib_tests (void)
References abs_tests(), atof_tests(), atoi_tests(), atol_tests(), atoll_tests(), bsearch_tests(), calloc_tests(), div_tests(), heapsort_r_tests(), heapsort_tests(), imaxabs_tests(), imaxdiv_tests(), labs_tests(), ldiv_tests(), llabs_tests(), lldiv_tests(), qsort_r_tests(), qsort_tests(), rand_tests(), realloc_tests(), strtod_tests(), strtof_tests(), strtol_tests(), strtoll_tests(), strtoul_tests(), and strtoull_tests().
Referenced by main().
string_tests()
int string_tests (void)
References memcmp_tests(), memcpy_tests(), memmem_tests(), memmove_tests(), memset_tests(), strcat_tests(), strchr_tests(), strcmp_tests(), strcpy_tests(), strdup_tests(), strlen_tests(), strncat_tests(), strncmp_tests(), strncpy_tests(), strndup_tests(), strnlen_tests(), strnstr_tests(), strrchr_tests(), strstr_tests(), and strtok_tests().
Referenced by main().