Embedded Artistry Framework: src/processors/arm/nordic/drivers/helpers/twim_helper.cpp File Reference
twim_helper.cpp File Reference
#include "twim_helper.hpp"
#include "twim_helper_.hpp"
#include <nordic_nvic.hpp>
Functions
static embvm::i2c::status get_converted_error (NRF_TWIM_Type *twi) noexcept
static void invoke_callback_ (NRF_TWIM_Type *twi) noexcept
static void twim_irq_handler_ (NRF_TWIM_Type *twi) noexcept
void SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQHandler ()
void SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQHandler ()
static NRF_TWIM_Type * getTWIInst (NordicTWIM inst) noexcept
static uint32_t getTWIFrequency (embvm::i2c::baud baudrate) noexcept
Function Documentation
get_converted_error()
static embvm::i2c::status get_converted_error (NRF_TWIM_Type * twi) static noexcept
References embvm::i2c::addrNACK, embvm::i2c::dataNACK, get_errorsrc_(), embvm::i2c::ok, and r.
Referenced by invoke_callback_(), nRFTWIMTranslator::rx_transfer(), nRFTWIMTranslator::rx_transfer_blocking(), nRFTWIMTranslator::tx_transfer(), nRFTWIMTranslator::tx_transfer_blocking(), nRFTWIMTranslator::txrx_transfer(), and nRFTWIMTranslator::txrx_transfer_blocking().
getTWIFrequency()
static uint32_t getTWIFrequency (embvm::i2c::baud baudrate) inline static noexcept
References assert, embvm::i2c::fast, embvm::i2c::lowSpeed, and embvm::i2c::standard.
Referenced by nRFTWITranslator::setFrequency(), and nRFTWIMTranslator::setFrequency().
getTWIInst()
static NRF_TWIM_Type* getTWIInst (NordicTWIM inst) inline static noexcept
References NordicTWIM0, and NordicTWIM1.
Referenced by nRFTWITranslator::disable(), nRFTWIMTranslator::disable(), nRFTWITranslator::disable_interrupts(), nRFTWIMTranslator::disable_interrupts(), nRFTWITranslator::enable(), nRFTWIMTranslator::enable(), nRFTWIMTranslator::enable_interrupts(), nRFTWITranslator::rx_transfer(), nRFTWIMTranslator::rx_transfer(), nRFTWIMTranslator::rx_transfer_blocking(), nRFTWIMTranslator::set_interrupt_priority(), nRFTWITranslator::set_transfer_address(), nRFTWIMTranslator::set_transfer_address(), nRFTWITranslator::setFrequency(), nRFTWIMTranslator::setFrequency(), nRFTWITranslator::setSCLPin(), nRFTWIMTranslator::setSCLPin(), nRFTWITranslator::setSDAPin(), nRFTWIMTranslator::setSDAPin(), nRFTWITranslator::stop_condition(), nRFTWIMTranslator::stop_condition(), nRFTWITranslator::tx_transfer(), nRFTWIMTranslator::tx_transfer(), nRFTWIMTranslator::tx_transfer_blocking(), nRFTWIMTranslator::txrx_transfer(), and nRFTWIMTranslator::txrx_transfer_blocking().
invoke_callback_()
static void invoke_callback_ (NRF_TWIM_Type * twi) static noexcept
References get_converted_error().
Referenced by twim_irq_handler_().
SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQHandler()
void SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQHandler ()
References twim_irq_handler_().
SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQHandler()
void SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQHandler ()
References twim_irq_handler_().
twim_irq_handler_()
static void twim_irq_handler_ (NRF_TWIM_Type * twi) static noexcept
References assert, check_event_(), clear_event_(), disable_shortcuts_(), handle_error_event_(), interrupts_disable_(), interrupts_enable_(), invoke_callback_(), TWIM_EVENT_ERROR, TWIM_EVENT_LASTRX, TWIM_EVENT_LASTTX, TWIM_EVENT_STOPPED, and TWIM_EVENT_SUSPENDED.
Referenced by SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQHandler(), and SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQHandler().