Embedded Artistry libc: src/gdtoa/src/g__fmt.c File Reference
g__fmt.c File Reference
#include "gdtoaimp.h"
Macros
#define decimalpoint '.'
Functions
char * g__fmt (char *b, char *s, const char *se, int decpt, ULong sign)
Macro Definition Documentation
decimalpoint
#define decimalpoint '.'
Function Documentation
g__fmt()
char* g__fmt (char * b, char * s, const char * se, int decpt, ULong sign)
Definition at line 46 of file g__fmt.c.
 {
     char* s0 = s;
 #ifdef USE_LOCALE
     char decimalpoint = *localeconv()->decimal_point;
 #else
 #define decimalpoint '.'
 #endif
     if(sign)
     {
         {
             *b++ = '-';
         }
     }
     if(decpt <= -4 || decpt > se - s + 5)
     {
         int j, k;
         *b++ = *s++;
         if(*s)
         {
             *b++ = decimalpoint;
             while((*b = *s++) != 0)
             {
                 b++;
             }
         }
         *b++ = 'e';
         /* sprintf(b, "%+.2d", decpt - 1); */
         if(--decpt < 0)
         {
             *b++ = '-';
             decpt = -decpt;
         }
         else
         {
             {
                 *b++ = '+';
             }
         }
         for(j = 2, k = 10; 10 * k <= decpt; j++, k *= 10)
         {
         }
         for(;;)
         {
             int i = decpt / k;
             *b++ = (char)i + '0';
             if(--j <= 0)
             {
                 break;
             }
             decpt -= i * k;
             decpt *= 10;
         }
         *b = 0;
     }
     else if(decpt <= 0)
     {
         *b++ = decimalpoint;
         for(; decpt < 0; decpt++)
         {
             {
                 *b++ = '0';
             }
         }
         while((*b = *s++) != 0)
         {
             {
                 b++;
             }
         }
     }
     else
     {
         while((*b = *s++) != 0)
         {
             b++;
             if(--decpt == 0 && *s)
             {
                 {
                     *b++ = decimalpoint;
                 }
             }
         }
         for(; decpt > 0; decpt--)
         {
             {
                 *b++ = '0';
             }
         }
         *b = 0;
     }
     freedtoa(s0);
     return b;
 }
References lconv::decimal_point, decimalpoint, freedtoa(), and localeconv().
Referenced by g_ddfmt(), g_dfmt(), g_ffmt(), g_Qfmt(), g_xfmt(), and g_xLfmt().