Embedded Artistry Framework: nRF52DK_FrameworkDemoPlatform Class Reference
nRF52DK_FrameworkDemoPlatform Class Reference final
#include <platform.hpp>
Public Member Functions
void init_ () noexcept
void initProcessor_ () noexcept
void initHWPlatform_ () noexcept
void startBlink () noexcept
void echoLogBufferToConsole () noexcept
nRF52DK_FrameworkDemoPlatform () noexcept
Default constructor supplies a default name for the simulator platform.
~nRF52DK_FrameworkDemoPlatform ()=default
void init () noexcept
Initialize the platform.
void initProcessor () noexcept
Initialize the processor.
void initHWPlatform () noexcept
Initialize the hardware platform.
constexpr const std::string_view & name () const noexcept
Access the platform's name.
constexpr const char * name_cstr () const noexcept
Access the platform name as a cstring for C API compatibility.
auto findDriver (const std::string_view &name) noexcept
Access a device driver in the registry by name.
auto findDriver (embvm::DriverType_t type) noexcept
Access a device driver in the registry by type.
auto findDriver () noexcept
Access a device driver in the registry by type, cast as the appropriate base class.
auto findDriver (const std::string_view &name) noexcept
Access a device driver in the registry by name, cast as the appropriate base class.
auto findAllDrivers (embvm::DriverType_t type) noexcept
Get a list of all device drivers in the registry by type.
auto findAllDrivers () noexcept
Get a list of all device drivers in the registry by type, cast as the appropriate base class.
size_t driverCount () const noexcept
Get the count of drivers registered with the platform.
Static Public Member Functions
static void earlyInitHook_ () noexcept
static void initOS_ (void(*main_thread)()) noexcept
static nRF52DK_FrameworkDemoPlatform & inst () noexcept
Get the global platform instance.
static void earlyInitHook () noexcept
Call early-initialization code.
static void initOS () noexcept
Initialize the OS.
static void initOS (void(*main_thread)()) noexcept
Initialize the with a function to use as the main thread.
static void registerDriver (const std::string_view &name, embvm::DriverBase *driver) noexcept
Platform-level API for registering a new device driver.
static void unregisterDriver (const std::string_view &name, embvm::DriverBase *driver) noexcept
Platform-level API for unregistering a new device driver.
Protected Attributes
const std::string_view name_
Private Types
using PlatformBase = embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform, PlatformDriverRegistry >
Private Member Functions
void led_blink_thread_ () noexcept
Private Attributes
NRF52DKHWPlatform hw_platform_
embvm::VirtualThread * led_thread_ = nullptr
Thread handle for the created-during-runtime LED thread.
Member Typedef Documentation
PlatformBase
using nRF52DK_FrameworkDemoPlatform::PlatformBase = embvm::VirtualPlatformBase<nRF52DK_FrameworkDemoPlatform, PlatformDriverRegistry> private
Constructor & Destructor Documentation
nRF52DK_FrameworkDemoPlatform()
nRF52DK_FrameworkDemoPlatform::nRF52DK_FrameworkDemoPlatform () inline noexcept
Default constructor supplies a default name for the simulator platform.
~nRF52DK_FrameworkDemoPlatform()
nRF52DK_FrameworkDemoPlatform::~nRF52DK_FrameworkDemoPlatform () default
Member Function Documentation
driverCount()
size_t embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::driverCount () const inline noexcept inherited
Get the count of drivers registered with the platform.
returns Number of drivers currently registered with the platform DriverRegistry.
earlyInitHook()
static void embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::earlyInitHook () inline static noexcept inherited
Call early-initialization code.
Call early initialization code, which is to be run before C runtime initialization, memory relocations, OS initialization, etc. This call is used to handle early setup code that the rest of the initialization process might depend on, such as DRAM initialization.
This function forwards the call to the derived class for the actual implementation.
earlyInitHook_()
void nRF52DK_FrameworkDemoPlatform::earlyInitHook_ () static noexcept
References __HeapBase, __HeapLimit, and malloc_addblock().
echoLogBufferToConsole()
void nRF52DK_FrameworkDemoPlatform::echoLogBufferToConsole () noexcept
References embvm::PlatformLogger_t< TLogger >::inst().
findAllDrivers() [1/2]
auto embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::findAllDrivers (embvm::DriverType_t type) inline noexcept inherited
Get a list of all device drivers in the registry by type.
The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Parameters
type The type of driver being requested (embvm::i2c::master, SystemClock).
Returns
A list of embvm::DriverBase instances. If no matching types are found, an empty list will be returned. The caller must cast to the appropriate type.
findAllDrivers() [2/2]
auto embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::findAllDrivers () inline noexcept inherited
Get a list of all device drivers in the registry by type, cast as the appropriate base class.
The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Returns
A list of driver instances cast as TDriverClass types. If no matching types are found, an empty list will be returned.
findDriver() [1/4]
auto embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::findDriver (const std::string_view & name) inline noexcept inherited
Access a device driver in the registry by name.
Find a driver by name.
This call forwards the information to the DriverRegistry instance.
Returns
An optional_ref to the embvm::DriverBase instance. If no instance is found, the optional reference will be invalid. The caller must cast to the appropriate type.
findDriver() [2/4]
auto embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::findDriver (embvm::DriverType_t type) inline noexcept inherited
Access a device driver in the registry by type.
Find a driver by type. If multiple drivers are found for a type, the first one found will be returned.
This call forwards the information to the DriverRegistry instance.
Returns
An optional_ref to the embvm::DriverBase instance. If no instance is found, the optional reference will be invalid. The caller must cast to the appropriate type.
findDriver() [3/4]
auto embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::findDriver () inline noexcept inherited
Access a device driver in the registry by type, cast as the appropriate base class.
If multiple drivers are found for a type, the first one found will be returned. The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Returns
an type_safe::optional_ref cast to the TDriverClass type. If the driver was not found, the optional_ref will be empty.
findDriver() [4/4]
auto embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::findDriver (const std::string_view & name) inline noexcept inherited
Access a device driver in the registry by name, cast as the appropriate base class.
The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Returns
an type_safe::optional_ref cast to the TDriverClass type. If the driver was not found, the optional_ref will be empty.
init()
void embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::init () inline noexcept inherited
Initialize the platform.
This function is responsible for initializing the platform.
This function forwards the call to the derived class for the actual implementation.
init_()
void nRF52DK_FrameworkDemoPlatform::init_ () noexcept
References embvm::PlatformLogger_t< TLogger >::inst(), and logdebug.
initHWPlatform()
void embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::initHWPlatform () inline noexcept inherited
Initialize the hardware platform.
Performs steps necessary to initialize the hardware platform for use by the platform. In many cases, this call should just invoke the hardware platform's init() function. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the hardware platform in situations where non-default values are used.
This function forwards the call to the derived class for the actual implementation.
initHWPlatform_()
void nRF52DK_FrameworkDemoPlatform::initHWPlatform_ () noexcept
References hw_platform_, embvm::VirtualHwPlatformBase< THWPlatform >::init(), NRF52DKHWPlatform::screen0_inst(), snprintf, and NRF52DKHWPlatform::tof0_inst().
initOS() [1/2]
static void embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::initOS () inline static noexcept inherited
Initialize the OS.
Performs steps necessary to initialize the OS for use by the platform. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the OS, since each OS has different startup requirements
This function forwards the call to the derived class for the actual implementation.
initOS() [2/2]
static void embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::initOS (void(*)() main_thread) inline static noexcept inherited
Initialize the with a function to use as the main thread.
Performs steps necessary to initialize the OS for use by the platform. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the OS, since each OS has different startup requirements
This function forwards the call to the derived class for the actual implementation.
Parameters
main_thread a function pointer to use as the main thread routine. This version of initOS should be used for OSes such as FreeRTOS which kill execution of the current thread when the scheduler is started.
initOS_()
void nRF52DK_FrameworkDemoPlatform::initOS_ (void(*)() main_thread) static noexcept
References embvm::VirtualOSFactory< TFactory >::createThread(), main_thread_func(), embvm::thread::normal, and os::freertos::startScheduler().
initProcessor()
void embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::initProcessor () inline noexcept inherited
Initialize the processor.
Performs steps necessary to initialize the processor for use by the platform. In many cases, this call should just invoke the processor's init() function. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the processor in situations where non-default values are used.
This function forwards the call to the derived class for the actual implementation.
initProcessor_()
void nRF52DK_FrameworkDemoPlatform::initProcessor_ () noexcept
References hw_platform_, and embvm::VirtualHwPlatformBase< THWPlatform >::initProcessor().
inst()
static nRF52DK_FrameworkDemoPlatform & embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::inst () inline static noexcept inherited
Get the global platform instance.
Static declaration of the VirtualPlatformBase instance. We use this function to avoid the static initializatio order 'fiasco'. See more: https://isocpp.org/wiki/faq/ctors#static-init-order
led_blink_thread_()
void nRF52DK_FrameworkDemoPlatform::led_blink_thread_ () private noexcept
References NRF52DKHWPlatform::getLEDInstances(), hw_platform_, and embvm::this_thread::sleep_for().
Referenced by startBlink().
name()
constexpr const std::string_view& embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::name () const inline noexcept inherited
Access the platform's name.
Returns
Platform name std::string_view reference.
name_cstr()
constexpr const char* embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::name_cstr () const inline noexcept inherited
Access the platform name as a cstring for C API compatibility.
Returns
Platform name as a C-string.
registerDriver()
static void embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::registerDriver (const std::string_view & name, embvm::DriverBase * driver) inline static noexcept inherited
Platform-level API for registering a new device driver.
Register a device driver with the platform's driver registry.
This call forwards the information to the DriverRegistry instance.
Parameters
name The name (used as a key) the driver will be registered under.
driver Pointer to the embvm::DriverBase object. A pointer is used because there are any number of potential derived classes which will be tracked. To prevent slicing, a pointer to the base class is stored.
startBlink()
void nRF52DK_FrameworkDemoPlatform::startBlink () noexcept
References assert, BOUNCE, embvm::VirtualOSFactory< TFactory >::createThread(), led_blink_thread_(), led_thread_, and embvm::thread::low.
unregisterDriver()
static void embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::unregisterDriver (const std::string_view & name, embvm::DriverBase * driver) inline static noexcept inherited
Platform-level API for unregistering a new device driver.
Unregister a device driver with the platform's driver registry.
This call forwards the information to the DriverRegistry instance.
Parameters
name The name of the driver to remove.
driver Pointer to the embvm::DriverBase object being removed.
Member Data Documentation
hw_platform_
NRF52DKHWPlatform nRF52DK_FrameworkDemoPlatform::hw_platform_ private
Referenced by initHWPlatform_(), initProcessor_(), and led_blink_thread_().
led_thread_
embvm::VirtualThread* nRF52DK_FrameworkDemoPlatform::led_thread_ = nullptr private
Thread handle for the created-during-runtime LED thread.
We defer initialization of the LED thread so that we can can start the blinking process at a time of our choosing, rather than during the construction process.
This is just one approach at handling startBlink() for this platform. Another approach would be to create the thread statically and use a variable to wake the thread when we are ready for blinking to start.
Referenced by startBlink().
name_
const std::string_view embvm::VirtualPlatformBase< nRF52DK_FrameworkDemoPlatform , PlatformDriverRegistry >::name_ protected inherited
The documentation for this class was generated from the following files:
src/platforms/fwdemo/fwdemo_nrf52dk/platform.hpp
src/platforms/fwdemo/fwdemo_nrf52dk/platform.cpp