Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_nan.c File Reference
s_nan.c File Reference
#include <ctype.h>
#include <float.h>
#include <openlibm_math.h>
#include <stdint.h>
#include <string.h>
#include "math_private.h"
Functions
static __inline int digittoint (int c)
OLM_DLLEXPORT void __scan_nan (u_int32_t *words, int num_words, const char *s)
OLM_DLLEXPORT double nan (const char *s)
OLM_DLLEXPORT float nanf (const char *s)
Function Documentation
__scan_nan()
OLM_DLLEXPORT void __scan_nan (u_int32_t * words, int num_words, const char * s)
References digittoint(), isxdigit(), memset(), OLM_DLLEXPORT, and s.
Referenced by nan(), nanf(), and nanl().
digittoint()
static __inline int digittoint (int c) static
Referenced by __scan_nan().
nan()
OLM_DLLEXPORT double nan (const char * s)
References __scan_nan(), IEEEl2bits::bits, s, and u.
nanf()
OLM_DLLEXPORT float nanf (const char * s)
References __scan_nan(), s, and u.