Embedded Artistry Framework: Aardvark Adapter Drivers
Aardvark Adapter Drivers
Framework Drivers » Simulator Drivers
Aardvark Adapter drivers, usable for Simulator applications.
Classes
class embdrv::aardvarkAdapter
Driver to control the Aardvark Adapter.
class embdrv::aardvarkGPIOInput< TPinID, TPull >
Aardvark GPIO Input driver.
class embdrv::aardvarkGPIOOutput< TPinID >
Aardvark GPIO Output driver.
class embdrv::aardvarkI2CMaster
Create an Aardvark I2C Master Driver.
class embdrv::aardvarkSPIMaster
Create an Aardvark SPI Master Driver.
Macros
#define AARDVARK_IO_COUNT 6
The number of IO pins supported by the AARDVARK sensor.
Enumerations
enum embdrv::aardvarkMode {
embdrv::aardvarkMode::GpioOnly = 0x0, embdrv::aardvarkMode::SpiGpio = 0x01, embdrv::aardvarkMode::GpioI2C = 0x02, embdrv::aardvarkMode::SpiI2C = 0x03,
embdrv::aardvarkMode::Query = 0x80
}
Aardvark master operational modes.
Variables
static constexpr std::array< uint8_t, AARDVARK_IO_COUNT > embdrv::aardvarkIO
aardvark IO pin IDs
Detailed Description
Aardvark Adapter drivers, usable for Simulator applications.
Class Documentation
embdrv::aardvarkAdapter
class embdrv::aardvarkAdapter
Driver to control the Aardvark Adapter.
This class must always be declared for use with Aardvark drivers. The aardvarkAdapter is used to set the operational mode and configure the device hardware.
The aardvarkAdapter instance is then passed to the aardvark drivers:
embdrv::aardvarkAdapter aardvark{embdrv::aardvarkMode::GpioI2C};
embdrv::aardvarkI2CMaster i2c0{aardvark};
embdrv::aardvarkGPIOOutput<5> gpio5{aardvark};
embdrv::aardvarkGPIOInput<4> gpio4{aardvark};
embdrv::aardvarkGPIOInput<3> gpio3{aardvark};
Public Member Functions
aardvarkAdapter (aardvarkMode m=aardvarkMode::SpiI2C, uint8_t USBPort=0)
Create a generic aardvark Adapter.
aardvarkAdapter (const char *name, aardvarkMode m=aardvarkMode::SpiI2C, uint8_t USBPort=0)
Create an aardvarkAdapter with a name.
aardvarkAdapter (const std::string &name, aardvarkMode m=aardvarkMode::SpiI2C, uint8_t USBPort=0)
aardvarkAdapter (const std::string_view &name, aardvarkMode m=aardvarkMode::SpiI2C, uint8_t USBPort=0)
~aardvarkAdapter () override=default
Default destructor.
aardvarkMode mode (aardvarkMode m)
Change the Aardvark Adapter's operational mode.
aardvarkMode mode () const
Get the current mode setting This function does not query the device, it returns the cached mode.
int handle () const
Get the handle for the Aardvark Master The handle is used by related drivers to work with the Aardvark library APIs.
void lock ()
Lock the Aardvark master - used by other Aardvark driver types to ensure exclusion.
void unlock ()
Unlock the Aardvark Master.
bool i2cPullups ()
Query the current i2c pullup setting.
bool i2cPullups (bool en)
Enable/Disable the i2c pullup setting.
bool targetPower ()
Query the current 5V target power setting.
bool targetPower (bool en)
Enable/Disable 5V target power output.
void pullup (uint8_t id, bool en)
Set a pullup for GPIO.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
Private Attributes
std::mutex lock_ {}
The aardvark adapter lock.
uint8_t port_
The USB port the adapter is connected to.
uint8_t pullup_mask_ = 0
Mask representing the pullups currently enabled.
int handle_ = 0
The handle for the aardvark Adapter (provided by the aardvark API).
aardvarkMode mode_
The currently configured Aardvark Adapter mode.
std::atomic< int > started_refcnt_ = 0
Reference count for the number of times this driver has been started.
Constructor & Destructor Documentation
aardvarkAdapter() [1/4]
embdrv::aardvarkAdapter::aardvarkAdapter (aardvarkMode m = aardvarkMode::SpiI2C, uint8_t USBPort = 0) inline explicit
Create a generic aardvark Adapter.
Parameters
m The aardvark adapter mode.
USBPort The id of the USB port the aardvarkAdapter is connected to.
aardvarkAdapter() [2/4]
embdrv::aardvarkAdapter::aardvarkAdapter (const char * name, aardvarkMode m = aardvarkMode::SpiI2C, uint8_t USBPort = 0) inline explicit
Create an aardvarkAdapter with a name.
Parameters
name The name for the aardvarkAdapter driver.
m The aardvark adapter mode.
USBPort The id of the USB port the aardvarkAdapter is connected to.
aardvarkAdapter() [3/4]
embdrv::aardvarkAdapter::aardvarkAdapter (const std::string & name, aardvarkMode m = aardvarkMode::SpiI2C, uint8_t USBPort = 0) inline explicit
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
aardvarkAdapter() [4/4]
embdrv::aardvarkAdapter::aardvarkAdapter (const std::string_view & name, aardvarkMode m = aardvarkMode::SpiI2C, uint8_t USBPort = 0) inline explicit
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
~aardvarkAdapter()
embdrv::aardvarkAdapter::~aardvarkAdapter () override default
Default destructor.
Member Function Documentation
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
handle()
int embdrv::aardvarkAdapter::handle () const inline
Get the handle for the Aardvark Master The handle is used by related drivers to work with the Aardvark library APIs.
Returns
the Aardvark master handle.
References handle_.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkSPIMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkI2CMaster::process_(), embdrv::aardvarkSPIMaster::process_(), embdrv::aardvarkGPIOOutput< 5 >::set(), and embdrv::aardvarkGPIOOutput< 5 >::start_().
i2cPullups() [1/2]
bool aardvarkAdapter::i2cPullups ()
Query the current i2c pullup setting.
Returns
true if I2C pullups are enabled, false if disabled.
References aa_i2c_pullup(), AA_I2C_PULLUP_QUERY, handle_, lock(), r, and unlock().
Referenced by embdrv::aardvarkI2CMaster::setPullups_(), and embdrv::aardvarkGPIOInput< 4 >::start_().
i2cPullups() [2/2]
bool aardvarkAdapter::i2cPullups (bool en)
Enable/Disable the i2c pullup setting.
Parameters
en True enables I2C pullups, false disables them.
Returns
true if I2C pullups are enabled, false if disabled.
References aa_i2c_pullup(), AA_I2C_PULLUP_BOTH, AA_I2C_PULLUP_NONE, handle_, lock(), and unlock().
lock()
void embdrv::aardvarkAdapter::lock () inline
Lock the Aardvark master - used by other Aardvark driver types to ensure exclusion.
Postcondition
The aardvarkAdapter is locked for the client's exclusive use.
References lock_.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkSPIMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), i2cPullups(), mode(), embdrv::aardvarkSPIMaster::process_(), pullup(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::aardvarkGPIOOutput< 5 >::start_(), and targetPower().
mode() [1/2]
aardvarkMode aardvarkAdapter::mode (aardvarkMode m)
Change the Aardvark Adapter's operational mode.
Parameters
m The desired aardvark operational mode.
Returns
the configured aardvark operational mode.
References aa_configure(), handle_, lock(), mode_, and unlock().
Referenced by embdrv::aardvarkGPIOInput< 4 >::start_().
mode() [2/2]
aardvarkMode embdrv::aardvarkAdapter::mode () const inline
Get the current mode setting This function does not query the device, it returns the cached mode.
Returns
the configured aardvark operational mode.
References mode_.
Referenced by start_().
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
pullup()
void aardvarkAdapter::pullup (uint8_t id, bool en)
Set a pullup for GPIO.
Parameters
id The GPIO Id to enable the pullup for
en True enables a pullup, false disables it.
References aa_gpio_pullup(), AA_OK, embdrv::aardvarkIO, assert, handle_, lock(), pullup_mask_, r, and unlock().
Referenced by embdrv::aardvarkGPIOInput< 4 >::pull_().
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void aardvarkAdapter::start_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
References aa_open(), assert, handle_, mode(), mode_, port_, embvm::DriverBase::started(), and started_refcnt_.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), start_(), and stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void aardvarkAdapter::stop_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
References aa_close(), handle_, embvm::DriverBase::started(), and started_refcnt_.
targetPower() [1/2]
bool aardvarkAdapter::targetPower ()
Query the current 5V target power setting.
Returns
true if 5V target power is enabled, false if disabled.
References aa_target_power(), AA_TARGET_POWER_QUERY, handle_, lock(), r, and unlock().
targetPower() [2/2]
bool aardvarkAdapter::targetPower (bool en)
Enable/Disable 5V target power output.
Parameters
en True enables 5V target power output, false disables it.
Returns
true if 5V target power is enabled, false if disabled.
References aa_i2c_pullup(), AA_TARGET_POWER_BOTH, AA_TARGET_POWER_NONE, handle_, lock(), and unlock().
unlock()
void embdrv::aardvarkAdapter::unlock () inline
Unlock the Aardvark Master.
Precondition
The aardvarkAdapter is locked
Postcondition
The aardvarkAdapter is unlocked
References lock_.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkSPIMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), i2cPullups(), mode(), embdrv::aardvarkSPIMaster::process_(), pullup(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::aardvarkGPIOOutput< 5 >::start_(), and targetPower().
Member Data Documentation
handle_
int embdrv::aardvarkAdapter::handle_ = 0 private
The handle for the aardvark Adapter (provided by the aardvark API).
Referenced by handle(), i2cPullups(), mode(), pullup(), start_(), stop_(), and targetPower().
lock_
std::mutex embdrv::aardvarkAdapter::lock_ {} private
The aardvark adapter lock.
Referenced by lock(), and unlock().
mode_
aardvarkMode embdrv::aardvarkAdapter::mode_ private
The currently configured Aardvark Adapter mode.
Referenced by mode(), and start_().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
port_
uint8_t embdrv::aardvarkAdapter::port_ private
The USB port the adapter is connected to.
Referenced by start_().
pullup_mask_
uint8_t embdrv::aardvarkAdapter::pullup_mask_ = 0 private
Mask representing the pullups currently enabled.
Referenced by pullup().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
started_refcnt_
std::atomic<int> embdrv::aardvarkAdapter::started_refcnt_ = 0 private
Reference count for the number of times this driver has been started.
Since multiple client drivers can be created, we don't want to stop the aardvarkAdapter base until all client drivers have been stopped.
Referenced by start_(), and stop_().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
embdrv::aardvarkGPIOInput
class embdrv::aardvarkGPIOInput
template<uint8_t TPinID, embvm::gpio::pull TPull = embvm::gpio::pull::none>
class embdrv::aardvarkGPIOInput< TPinID, TPull >
Aardvark GPIO Input driver.
Create a GPIO input driver using the Aardvark adapter.
This driver requires an aardvarkAdapter to work. The aardvark adapter must be configured with aardvarkMode::GpioI2C, aardvarkMode::SpiGpio, or aardvarkMode::GpioOnly.
embdrv::aardvarkAdapter aardvark{embdrv::aardvarkMode::GpioI2C};
embdrv::aardvarkGPIOInput<4> gpio4{aardvark};
embdrv::aardvarkGPIOInput<3> gpio3{aardvark};
Template Parameters
TPinID The aardvark pin ID to use as a GPIO Input. Must be less than AARDVARK_IO_COUNT.
TPull The pull setting to use with this GPIO.
Public Member Functions
aardvarkGPIOInput (aardvarkAdapter &master)
Construct a generic GPIO input.
aardvarkGPIOInput (aardvarkAdapter &master, const char *name)
Construct a named GPIO Input.
~aardvarkGPIOInput () final=default
Default Destructor.
bool get () final
Get the current GPIO pin state.
gpio::pull pull () const
Get the current pull configuration.
gpio::direction direction () const
Check the direction of the GPIO pin.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
GPIO Driver Type ID.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
embvm::gpio::pull pull_ (embvm::gpio::pull p) final
Set the pull configuration in hardware.
Private Attributes
aardvarkAdapter & master_
The aardvarkAdapter instance associated with this GPIO input.
Constructor & Destructor Documentation
aardvarkGPIOInput() [1/2]
template<uint8_t TPinID, embvm::gpio::pull TPull = embvm::gpio::pull::none> embdrv::aardvarkGPIOInput< TPinID, TPull >::aardvarkGPIOInput (aardvarkAdapter & master) inline explicit
Construct a generic GPIO input.
Parameters
master The aardvarkAdapter instance associated with this GPIO pin.
aardvarkGPIOInput() [2/2]
template<uint8_t TPinID, embvm::gpio::pull TPull = embvm::gpio::pull::none> embdrv::aardvarkGPIOInput< TPinID, TPull >::aardvarkGPIOInput (aardvarkAdapter & master, const char * name) inline explicit
Construct a named GPIO Input.
Parameters
master The aardvarkAdapter instance associated with this GPIO pin.
name The name of the GPIO pin
~aardvarkGPIOInput()
template<uint8_t TPinID, embvm::gpio::pull TPull = embvm::gpio::pull::none> embdrv::aardvarkGPIOInput< TPinID, TPull >::~aardvarkGPIOInput () final default
Default Destructor.
Member Function Documentation
direction()
gpio::direction embvm::gpio::base< TDir >::direction () const inline inherited
Check the direction of the GPIO pin.
Returns
The configured direction of this GPIO pin.
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
get()
template<uint8_t TPinID, embvm::gpio::pull TPull = embvm::gpio::pull::none> bool embdrv::aardvarkGPIOInput< TPinID, TPull >::get () inline final virtual
Get the current GPIO pin state.
Derived classes must implement the get() function.
Returns
true if the GPIO is set (logic 1), false otherwise (logic 0).
Implements embvm::gpio::input< TPull >.
Referenced by FWDemoSimulatorHWPlatform::readAndSetToFMode().
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
pull()
template<gpio::pull TPull = gpio::pull::none> gpio::pull embvm::gpio::input< TPull >::pull () const inline inherited
Get the current pull configuration.
Returns
The currently configured GPIO pull setting.
pull_()
template<uint8_t TPinID, embvm::gpio::pull TPull = embvm::gpio::pull::none> embvm::gpio::pull embdrv::aardvarkGPIOInput< TPinID, TPull >::pull_ (embvm::gpio::pull p) inline final private virtual
Set the pull configuration in hardware.
Derived classes must implement the pull_(gpio::pull p) function.
Returns
The currently configured GPIO pull setting.
Implements embvm::gpio::input< TPull >.
Referenced by embdrv::aardvarkGPIOInput< 4 >::start_().
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
template<uint8_t TPinID, embvm::gpio::pull TPull = embvm::gpio::pull::none> void embdrv::aardvarkGPIOInput< TPinID, TPull >::start_ () inline final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::gpio::input< TPull >.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
template<uint8_t TPinID, embvm::gpio::pull TPull = embvm::gpio::pull::none> void embdrv::aardvarkGPIOInput< TPinID, TPull >::stop_ () inline final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::gpio::input< TPull >.
type()
static constexpr embvm::DriverType embvm::gpio::base< TDir >::type () inline static inherited
GPIO Driver Type ID.
Returns
GPIO type ID.
Member Data Documentation
master_
template<uint8_t TPinID, embvm::gpio::pull TPull = embvm::gpio::pull::none> aardvarkAdapter& embdrv::aardvarkGPIOInput< TPinID, TPull >::master_ private
The aardvarkAdapter instance associated with this GPIO input.
Referenced by embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOInput< 4 >::pull_(), embdrv::aardvarkGPIOInput< 4 >::start_(), and embdrv::aardvarkGPIOInput< 4 >::stop_().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
embdrv::aardvarkGPIOOutput
class embdrv::aardvarkGPIOOutput
template<uint8_t TPinID>
class embdrv::aardvarkGPIOOutput< TPinID >
Aardvark GPIO Output driver.
Create a GPIO output driver using the Aardvark adapter.
This driver requires an aardvarkAdapter to work. The aardvark adapter must be configured with aardvarkMode::GpioI2C, aardvarkMode::SpiGpio, or aardvarkMode::GpioOnly.
embdrv::aardvarkAdapter aardvark{embdrv::aardvarkMode::GpioI2C};
embdrv::aardvarkGPIOOutput<5> gpio5{aardvark};
Template Parameters
TPinID The aardvark pin ID to use as a GPIO output. Must be less than AARDVARK_IO_COUNT.
Public Member Functions
aardvarkGPIOOutput (aardvarkAdapter &master)
Construct a generic GPIO output.
aardvarkGPIOOutput (aardvarkAdapter &master, const char *name)
Construct a named GPIO output.
~aardvarkGPIOOutput () final=default
Default destructor.
void set (bool v) final
Set the current GPIO pin state.
gpio::direction direction () const
Check the direction of the GPIO pin.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
GPIO Driver Type ID.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
Private Attributes
aardvarkAdapter & master_
The aardvarkAdapter instance associated with this GPIO output.
Constructor & Destructor Documentation
aardvarkGPIOOutput() [1/2]
template<uint8_t TPinID> embdrv::aardvarkGPIOOutput< TPinID >::aardvarkGPIOOutput (aardvarkAdapter & master) inline explicit
Construct a generic GPIO output.
Parameters
master The aardvarkAdapter instance associated with this GPIO pin.
aardvarkGPIOOutput() [2/2]
template<uint8_t TPinID> embdrv::aardvarkGPIOOutput< TPinID >::aardvarkGPIOOutput (aardvarkAdapter & master, const char * name) inline explicit
Construct a named GPIO output.
Parameters
master The aardvarkAdapter instance associated with this GPIO pin.
name The name of the GPIO pin
~aardvarkGPIOOutput()
template<uint8_t TPinID> embdrv::aardvarkGPIOOutput< TPinID >::~aardvarkGPIOOutput () final default
Default destructor.
Member Function Documentation
direction()
gpio::direction embvm::gpio::base< TDir >::direction () const inline inherited
Check the direction of the GPIO pin.
Returns
The configured direction of this GPIO pin.
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
set()
template<uint8_t TPinID> void embdrv::aardvarkGPIOOutput< TPinID >::set (bool v) inline final virtual
Set the current GPIO pin state.
Derived classes must implement the set() function.
Parameters
v The desired GPIO state. True for logic 1, false for logic 0.
Implements embvm::gpio::output.
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
template<uint8_t TPinID> void embdrv::aardvarkGPIOOutput< TPinID >::start_ () inline final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::gpio::output.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
template<uint8_t TPinID> void embdrv::aardvarkGPIOOutput< TPinID >::stop_ () inline final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::gpio::output.
type()
static constexpr embvm::DriverType embvm::gpio::base< TDir >::type () inline static inherited
GPIO Driver Type ID.
Returns
GPIO type ID.
Member Data Documentation
master_
template<uint8_t TPinID> aardvarkAdapter& embdrv::aardvarkGPIOOutput< TPinID >::master_ private
The aardvarkAdapter instance associated with this GPIO output.
Referenced by embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::aardvarkGPIOOutput< 5 >::start_(), and embdrv::aardvarkGPIOOutput< 5 >::stop_().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
embdrv::aardvarkI2CMaster
class embdrv::aardvarkI2CMaster
Create an Aardvark I2C Master Driver.
This driver requires an aardvarkAdapter to work. The aardvark adapter must be configured with aardvarkMode::GpioI2C or aardvarkMode::SpiI2C.
This is an active object: it has its own thread of control.
embdrv::aardvarkAdapter aardvark{embdrv::aardvarkMode::GpioI2C};
embdrv::aardvarkI2CMaster i2c0{aardvark};
Public Types
using cb_t = stdext::inplace_function< void(i2c::op_t, i2c::status)>
Represents the type of the callback operation.
using sweep_list_t = etl::vector< uint8_t, 128 >
using sweep_cb_t = stdext::inplace_function< void(void)>
Public Member Functions
aardvarkI2CMaster (aardvarkAdapter &master)
Construct a generic I2C master.
aardvarkI2CMaster (aardvarkAdapter &master, const char *name)
Construct a named I2C master.
~aardvarkI2CMaster () final
Default destructor.
void process_ (storagePair_t op)
Active object process function.
virtual void configure (i2c::baud baud, i2c::pullups pull=i2c::pullups::external)
Configure the I2C bus.
i2c::state state ()
Check the I2C bus status.
i2c::pullups pullups (i2c::pullups pullups)
Configure pull-ups.
i2c::pullups pullups ()
Check the pull-up configuration.
void sweep (sweep_list_t &found_list, const sweep_cb_t &cb)
Perform an I2C bus sweep to identify active devices.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
size_t queuedCount () noexcept
Get the number of operations in the queue.
bool enqueue (std::pair< embvm::i2c::op_t, const embvm::i2c::master::cb_t > t)
Add an operation to the queue.
void shutdown ()
Shutdown the active object.
Static Public Member Functions
static constexpr embvm::DriverType type ()
I2C Driver Type ID.
Protected Attributes
i2c::pullups pullups_ = i2c::pullups::external
Tracks the active pull-up configuration.
i2c::state state_ = i2c::state::idle
Tracks the status of the I2C bus.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Types
using storagePair_t = std::pair< embvm::i2c::op_t, const embvm::i2c::master::cb_t >
The storage type that the active object stores.
Private Member Functions
void configure_ (embvm::i2c::pullups pullup) final
Configure the I2C bus for operation.
embvm::i2c::status transfer_ (const embvm::i2c::op_t &op, const embvm::i2c::master::cb_t &cb) final
embvm::i2c::baud baudrate_ (embvm::i2c::baud baud) final
embvm::i2c::pullups setPullups_ (embvm::i2c::pullups pullups) final
Configure pull-ups.
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
Private Attributes
aardvarkAdapter & master_
The aardvarkAdapter instance associated with this driver.
Member Typedef Documentation
cb_t
using embvm::i2c::master::cb_t = stdext::inplace_function<void(i2c::op_t, i2c::status)> inherited
Represents the type of the callback operation.
storagePair_t
using embdrv::aardvarkI2CMaster::storagePair_t = std::pair<embvm::i2c::op_t, const embvm::i2c::master::cb_t> private
The storage type that the active object stores.
sweep_cb_t
using embvm::i2c::master::sweep_cb_t = stdext::inplace_function<void(void)> inherited
sweep_list_t
using embvm::i2c::master::sweep_list_t = etl::vector<uint8_t, 128> inherited
Constructor & Destructor Documentation
aardvarkI2CMaster() [1/2]
embdrv::aardvarkI2CMaster::aardvarkI2CMaster (aardvarkAdapter & master) inline explicit
Construct a generic I2C master.
Parameters
master The aardvarkAdapter instance associated with this driver.
aardvarkI2CMaster() [2/2]
embdrv::aardvarkI2CMaster::aardvarkI2CMaster (aardvarkAdapter & master, const char * name) inline explicit
Construct a named I2C master.
Parameters
master The aardvarkAdapter instance associated with this driver.
name The name of the driver.
~aardvarkI2CMaster()
aardvarkI2CMaster::~aardvarkI2CMaster () final default
Default destructor.
Member Function Documentation
baudrate_()
embvm::i2c::baud aardvarkI2CMaster::baudrate_ (embvm::i2c::baud baud) final private virtual
Implements embvm::i2c::master.
References aa_i2c_bitrate(), assert, embdrv::aardvarkAdapter::handle(), embdrv::aardvarkAdapter::lock(), master_, embvm::DriverBase::started_, and embdrv::aardvarkAdapter::unlock().
configure()
virtual void embvm::i2c::master::configure (i2c::baud baud, i2c::pullups pull = i2c::pullups::external) inline virtual inherited
Configure the I2C bus.
Configures the I2C bus for operation and sets the target baud rate and pull-ups.
Derived classes must implement the configure_() function to set up the target hardware.
Parameters
baud The target baudrate (as an i2c::baud enumeration rather than integral Hz). TODO: Tolerance - allowed relative tolerance for the resulting baudrate
pull The pullup setting, which defaults to external pull-ups (in hardware).
References embvm::i2c::master::configure_(), and embvm::i2c::master::pullups().
Referenced by embvm::i2c::activeMaster< 128 >::configure_(), and FWDemoSimulatorHWPlatform::init_().
configure_()
void aardvarkI2CMaster::configure_ (embvm::i2c::pullups pullups) final private virtual
Configure the I2C bus for operation.
This function is implemented by the derived class. It is responsible for configuring the target hardware for operation.
Parameters
pullups The target pull-up configuration.
Implements embvm::i2c::master.
References aa_i2c_bus_timeout(), assert, bus_timeout_ms, embdrv::aardvarkAdapter::handle(), embdrv::aardvarkAdapter::lock(), master_, embvm::DriverBase::started_, and embdrv::aardvarkAdapter::unlock().
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
enqueue()
bool embutil::activeObject< aardvarkI2CMaster , std::pair< embvm::i2c::op_t, const embvm::i2c::master::cb_t > , 0 , std::mutex , std::condition_variable >::enqueue (std::pair< embvm::i2c::op_t, const embvm::i2c::master::cb_t > t) inline inherited
Add an operation to the queue.
This function can be called directly, or by functions internal to the activeObject. For example, the "transfer" API enqueues transfer operations.
Parameters
t The operation data object to enqueue for later processing.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
process_()
void aardvarkI2CMaster::process_ (storagePair_t op)
Active object process function.
References aa_i2c_free_bus(), AA_I2C_NO_FLAGS, AA_I2C_NO_STOP, aa_i2c_read_ext(), AA_I2C_WRITE_ERROR, aa_i2c_write_ext(), aa_i2c_write_read(), AA_OK, assert, embvm::i2c::continueWriteNoStop, embvm::i2c::continueWriteStop, convertI2CTransactionErrorCode(), embdrv::aardvarkAdapter::handle(), master_, embvm::i2c::ping, r, embvm::i2c::read, embvm::i2c::restart, embvm::i2c::stop, embvm::i2c::write, embvm::i2c::writeNoStop, and embvm::i2c::writeRead.
pullups() [1/2]
i2c::pullups embvm::i2c::master::pullups (i2c::pullups pullups) inline inherited
Configure pull-ups.
Parameters
pullups The target pull-up setting.
Returns
The configured pull-up setting.
References embvm::i2c::master::pullups_, and embvm::i2c::master::setPullups_().
Referenced by embvm::i2c::activeMaster< 128 >::setPullups_().
pullups() [2/2]
i2c::pullups embvm::i2c::master::pullups () inline inherited
Check the pull-up configuration.
Returns
The configured pull-up setting.
References embvm::i2c::master::pullups_.
Referenced by embvm::i2c::master::configure(), test::i2cTestDriver::configure_(), setPullups_(), test::i2cTestDriver::setPullups_(), nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::setPullups_(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::setPullups_().
queuedCount()
size_t embutil::activeObject< aardvarkI2CMaster , std::pair< embvm::i2c::op_t, const embvm::i2c::master::cb_t > , 0 , std::mutex , std::condition_variable >::queuedCount () inline noexcept inherited
Get the number of operations in the queue.
Returns
the number of queued operations.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
setPullups_()
embvm::i2c::pullups aardvarkI2CMaster::setPullups_ (embvm::i2c::pullups pullups) final private virtual
Configure pull-ups.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the requested pullup setting.
Parameters
pullups The target pull-up setting.
Returns
The configured pull-up setting.
Implements embvm::i2c::master.
References assert, embvm::i2c::external, embdrv::aardvarkAdapter::i2cPullups(), master_, embvm::i2c::master::pullups(), and embvm::DriverBase::started_.
shutdown()
void embutil::activeObject< aardvarkI2CMaster , std::pair< embvm::i2c::op_t, const embvm::i2c::master::cb_t > , 0 , std::mutex , std::condition_variable >::shutdown () inline inherited
Shutdown the active object.
Call this function in the parent class destructor to stop the AO thread operation before destroying the parent class. This will prevent memory access problems due to race conidtions during destruction.
The shutdown process is permanent and cannot be reversed without recreating the object.
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void aardvarkI2CMaster::start_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::i2c::master.
References master_, and embvm::DriverBase::start().
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
state()
i2c::state embvm::i2c::master::state () inline inherited
Check the I2C bus status.
Returns
the status of the I2C bus as an i2c::state enumeration.
References embvm::i2c::master::state_.
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void aardvarkI2CMaster::stop_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::i2c::master.
References master_, and embvm::DriverBase::stop().
sweep()
void embvm::i2c::master::sweep (sweep_list_t & found_list, const sweep_cb_t & cb) inherited
Perform an I2C bus sweep to identify active devices.
The sweep function pings all I2C addresses. Devices which ACK are stored in a list and returned via callback.
Parameters
[in,out] found_list Caller's memory which will contain the successfully found ping addresses
[in] cb The callback which will be called to indicate that the sweep is complete. After the cb is called, found_list is valid and can be used by the caller.
References embvm::i2c::op_t::address, embvm::i2c::busy, embvm::i2c::ok, embvm::i2c::op_t::op, and embvm::i2c::ping.
transfer_()
embvm::i2c::status aardvarkI2CMaster::transfer_ (const embvm::i2c::op_t & op, const embvm::i2c::master::cb_t & cb) final private virtual
Implements embvm::i2c::master.
References embutil::activeObject< aardvarkI2CMaster, std::pair< embvm::i2c::op_t, const embvm::i2c::master::cb_t > >::enqueue(), and embvm::i2c::enqueued.
type()
static constexpr embvm::DriverType embvm::i2c::master::type () inline static inherited
I2C Driver Type ID.
Returns
I2C type ID.
References embvm::I2C.
Member Data Documentation
master_
aardvarkAdapter& embdrv::aardvarkI2CMaster::master_ private
The aardvarkAdapter instance associated with this driver.
Referenced by baudrate_(), configure_(), process_(), setPullups_(), start_(), and stop_().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
pullups_
i2c::pullups embvm::i2c::master::pullups_ = i2c::pullups::external protected inherited
Tracks the active pull-up configuration.
Referenced by embvm::i2c::master::pullups().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by baudrate_(), configure_(), setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
state_
i2c::state embvm::i2c::master::state_ = i2c::state::idle protected inherited
Tracks the status of the I2C bus.
Referenced by embvm::i2c::master::state().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
embdrv::aardvarkSPIMaster
class embdrv::aardvarkSPIMaster
Create an Aardvark SPI Master Driver.
This driver requires an aardvarkAdapter to work. The aardvark adapter must be configured with aardvarkMode::SpiGpio or aardvarkMode::SpiI2C.
This is an active object: it has its own thread of control.
embdrv::aardvarkAdapter aardvark{embdrv::aardvarkMode::SpiI2C};
embdrv::aardvarkSPIMaster spi0{aardvark, "spi0"};
Public Member Functions
aardvarkSPIMaster (aardvarkAdapter &master)
Construct a generic SPI master.
aardvarkSPIMaster (aardvarkAdapter &master, const char *name)
Construct a named SPI master.
~aardvarkSPIMaster () final
Default destructor.
void process_ (storagePair_t op)
Active object process function.
virtual void configure (spi::baud_t baud)
Configure the SPI bus.
spi::mode mode () const
Get the current SPI bus mode.
spi::mode mode (spi::mode mode)
Set the SPI bus mode.
spi::order order () const
Get the current SPI bus byte order.
spi::order order (spi::order order)
Set the SPI bus byte order.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
size_t queuedCount () noexcept
Get the number of operations in the queue.
bool enqueue (std::pair< embvm::spi::op_t, const embvm::spi::master::cb_t > t)
Add an operation to the queue.
void shutdown ()
Shutdown the active object.
Static Public Member Functions
static constexpr embvm::DriverType type ()
SPI Driver Type ID.
Protected Member Functions
embvm::comm::status transfer_ (const spi::op_t &op, const cb_t &cb) override=0
Protected Attributes
spi::mode mode_ = spi::mode::mode0
Stores the active SPI mode configuration.
spi::order order_ = spi::order::msbFirst
Stores the active SPI byte ordering.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Types
using storagePair_t = std::pair< embvm::spi::op_t, const embvm::spi::master::cb_t >
The storage type that the active object stores.
Private Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void configure_ () final
Configure the SPI bus for operation.
uint32_t baudrate_ (uint32_t baud) final
embvm::comm::status transfer_ (const embvm::spi::op_t &op, const embvm::spi::master::cb_t &cb) final
void setMode_ (embvm::spi::mode mode) final
Set the SPI bus mode.
void setOrder_ (embvm::spi::order order) final
Set the SPI bus byte order.
Private Attributes
aardvarkAdapter & master_
The aardvarkAdapter instance associated with this driver.
Member Typedef Documentation
storagePair_t
using embdrv::aardvarkSPIMaster::storagePair_t = std::pair<embvm::spi::op_t, const embvm::spi::master::cb_t> private
The storage type that the active object stores.
Constructor & Destructor Documentation
aardvarkSPIMaster() [1/2]
embdrv::aardvarkSPIMaster::aardvarkSPIMaster (aardvarkAdapter & master) inline explicit
Construct a generic SPI master.
Parameters
master The aardvarkAdapter instance associated with this driver.
aardvarkSPIMaster() [2/2]
embdrv::aardvarkSPIMaster::aardvarkSPIMaster (aardvarkAdapter & master, const char * name) inline explicit
Construct a named SPI master.
Parameters
master The aardvarkAdapter instance associated with this driver.
name The name of the driver.
~aardvarkSPIMaster()
aardvarkSPIMaster::~aardvarkSPIMaster () final default
Default destructor.
Member Function Documentation
baudrate_()
uint32_t aardvarkSPIMaster::baudrate_ (uint32_t baud) final private virtual
Implements embvm::spi::master.
References aa_spi_bitrate(), assert, embdrv::aardvarkAdapter::handle(), embdrv::aardvarkAdapter::lock(), master_, and embdrv::aardvarkAdapter::unlock().
configure()
virtual void embvm::spi::master::configure (spi::baud_t baud) inline virtual inherited
Configure the SPI bus.
Configures the SPI bus for operation and sets the target baud rate.
Derived classes must implement the configure_() function to set up the target hardware.
Parameters
baud The target baudrate, in Hz. TODO: Tolerance - allowed relative tolerance for the resulting baudrate
References embvm::spi::master::configure_().
configure_()
void aardvarkSPIMaster::configure_ () final private virtual
Configure the SPI bus for operation.
This function is implemented by the derived class. It is responsible for configuring the target hardware for operation.
Implements embvm::spi::master.
References AA_SPI_BITORDER_LSB, AA_SPI_BITORDER_MSB, aa_spi_configure(), embdrv::aardvarkAdapter::handle(), embdrv::aardvarkAdapter::lock(), master_, embvm::spi::master::mode_, embvm::spi::msbFirst, embvm::spi::master::order_, embvm::DriverBase::started(), and embdrv::aardvarkAdapter::unlock().
Referenced by setMode_(), and setOrder_().
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
enqueue()
bool embutil::activeObject< aardvarkSPIMaster , std::pair< embvm::spi::op_t, const embvm::spi::master::cb_t > , 0 , std::mutex , std::condition_variable >::enqueue (std::pair< embvm::spi::op_t, const embvm::spi::master::cb_t > t) inline inherited
Add an operation to the queue.
This function can be called directly, or by functions internal to the activeObject. For example, the "transfer" API enqueues transfer operations.
Parameters
t The operation data object to enqueue for later processing.
mode() [1/2]
spi::mode embvm::spi::master::mode () const inline inherited
Get the current SPI bus mode.
Returns
The currently configured mode.
References embvm::spi::master::mode_.
Referenced by embvm::spi::master::mode(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setMode_(), setMode_(), and test::spiTestDriver::setMode_().
mode() [2/2]
spi::mode embvm::spi::master::mode (spi::mode mode) inline inherited
Set the SPI bus mode.
Derived classes must implement the setMode_() function, which is reponsible for configuring the target hardware.
Parameters
mode The desired SPI bus mode.
Returns
The new SPI bus mode.
References embvm::spi::master::mode(), embvm::spi::master::mode_, and embvm::spi::master::setMode_().
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
order() [1/2]
spi::order embvm::spi::master::order () const inline inherited
Get the current SPI bus byte order.
Returns
The currently configured byte order.
References embvm::spi::master::order_.
Referenced by embvm::spi::master::order(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setOrder_(), setOrder_(), and test::spiTestDriver::setOrder_().
order() [2/2]
spi::order embvm::spi::master::order (spi::order order) inline inherited
Set the SPI bus byte order.
Derived classes must implement the setOrder_() function, which is reponsible for configuring the target hardware.
Parameters
order The desired byte ordering.
Returns
The new byte ordering.
References embvm::spi::master::order(), embvm::spi::master::order_, and embvm::spi::master::setOrder_().
process_()
void aardvarkSPIMaster::process_ (storagePair_t op)
Active object process function.
References AA_OK, AA_SPI_DROPPED_EXCESS_BYTES, AA_SPI_NOT_AVAILABLE, AA_SPI_NOT_ENABLED, AA_SPI_SLAVE_READ_ERROR, AA_SPI_SLAVE_TIMEOUT, aa_spi_write(), AA_SPI_WRITE_ERROR, embvm::comm::busy, embvm::comm::error, embdrv::aardvarkAdapter::handle(), embdrv::aardvarkAdapter::lock(), master_, embvm::comm::ok, r, embvm::comm::unknown, and embdrv::aardvarkAdapter::unlock().
queuedCount()
size_t embutil::activeObject< aardvarkSPIMaster , std::pair< embvm::spi::op_t, const embvm::spi::master::cb_t > , 0 , std::mutex , std::condition_variable >::queuedCount () inline noexcept inherited
Get the number of operations in the queue.
Returns
the number of queued operations.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
setMode_()
void aardvarkSPIMaster::setMode_ (embvm::spi::mode mode) final private virtual
Set the SPI bus mode.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the new mode.
Parameters
mode The desired byte ordering.
Implements embvm::spi::master.
References assert, configure_(), embvm::spi::master::mode(), embvm::spi::mode0, embvm::spi::mode3, and embvm::spi::master::mode_.
setOrder_()
void aardvarkSPIMaster::setOrder_ (embvm::spi::order order) final private virtual
Set the SPI bus byte order.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the new byte ordering.
Parameters
order The desired byte ordering.
Implements embvm::spi::master.
References configure_(), embvm::spi::master::order(), and embvm::spi::master::order_.
shutdown()
void embutil::activeObject< aardvarkSPIMaster , std::pair< embvm::spi::op_t, const embvm::spi::master::cb_t > , 0 , std::mutex , std::condition_variable >::shutdown () inline inherited
Shutdown the active object.
Call this function in the parent class destructor to stop the AO thread operation before destroying the parent class. This will prevent memory access problems due to race conidtions during destruction.
The shutdown process is permanent and cannot be reversed without recreating the object.
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void aardvarkSPIMaster::start_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::spi::master.
References master_, and embvm::DriverBase::start().
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void aardvarkSPIMaster::stop_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::spi::master.
References master_, and embvm::DriverBase::stop().
transfer_() [1/2]
embvm::comm::status aardvarkSPIMaster::transfer_ (const embvm::spi::op_t & op, const embvm::spi::master::cb_t & cb) final private
References embutil::activeObject< aardvarkSPIMaster, std::pair< embvm::spi::op_t, const embvm::spi::master::cb_t > >::enqueue(), and embvm::comm::enqueued.
transfer_() [2/2]
embvm::comm::status embvm::spi::master::transfer_ (const spi::op_t & op, const cb_t & cb) override protected pure virtual inherited
type()
static constexpr embvm::DriverType embvm::spi::master::type () inline static inherited
SPI Driver Type ID.
Returns
SPI type ID.
References embvm::SPI.
Member Data Documentation
master_
aardvarkAdapter& embdrv::aardvarkSPIMaster::master_ private
The aardvarkAdapter instance associated with this driver.
Referenced by baudrate_(), configure_(), process_(), start_(), and stop_().
mode_
spi::mode embvm::spi::master::mode_ = spi::mode::mode0 protected inherited
Stores the active SPI mode configuration.
Referenced by configure_(), embvm::spi::master::mode(), and setMode_().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
order_
spi::order embvm::spi::master::order_ = spi::order::msbFirst protected inherited
Stores the active SPI byte ordering.
Referenced by configure_(), embvm::spi::master::order(), and setOrder_().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
Macro Definition Documentation
AARDVARK_IO_COUNT
#define AARDVARK_IO_COUNT 6
The number of IO pins supported by the AARDVARK sensor.
Enumeration Type Documentation
aardvarkMode
enum embdrv::aardvarkMode strong
Aardvark master operational modes.
Enumerator
GpioOnly
Aardvark Device used for GPIO.
Enables the full array of GPIO IOs for use.
SpiGpio
Aardvark device used for SPI + GPIO.
The Non-SPI pins can be used in GPIO mode.
GpioI2C
Aardvark device used for I2C + GPIO.
The non-I2C pins can be used in GPIO mode.
SpiI2C
Aardvark Device used for I2C + SPI.
GPIO use is not supported
Query
Query the current mode.
Variable Documentation
aardvarkIO
constexpr std::array<uint8_t, AARDVARK_IO_COUNT> embdrv::aardvarkIO inline static
Initial value:
= {
    AA_GPIO_SCL, AA_GPIO_SDA, AA_GPIO_MISO, AA_GPIO_SCK, AA_GPIO_MOSI, AA_GPIO_SS}
aardvark IO pin IDs
Referenced by embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkAdapter::pullup(), embdrv::aardvarkGPIOOutput< 5 >::set(), and embdrv::aardvarkGPIOOutput< 5 >::start_().