Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_casinf.c File Reference
s_casinf.c File Reference
#include <openlibm_complex.h>
#include <openlibm_math.h>
Functions
float complex casinf (float complex z)
Function Documentation
casinf()
float complex casinf (float complex z)
References asinf(), cimagf(), clogf(), complex, crealf(), csqrtf(), fabsf(), I, w, and z.
Referenced by cacosf(), and casinhf().