Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_scalbnl.c File Reference
s_scalbnl.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "fpmath.h"
#include "math_private.h"
Functions
OLM_DLLEXPORT long double scalbnl (long double x, int n)
__strong_reference (scalbnl, ldexpl)
Variables
static const long double huge = 0x1p16000L
static const long double tiny = 0x1p-16000L
Function Documentation
__strong_reference()
__strong_reference (scalbnl , ldexpl)
scalbnl()
OLM_DLLEXPORT long double scalbnl (long double x, int n)
References copysign(), copysignl(), huge, k, n, p, tiny, and u.
Referenced by powl(), and scalblnl().
Variable Documentation
huge
const long double huge = 0x1p16000L static
Referenced by scalbnl().
tiny
const long double tiny = 0x1p-16000L static
Referenced by scalbnl().