Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_cacosf.c File Reference
s_cacosf.c File Reference
#include <openlibm_complex.h>
#include <openlibm_math.h>
Functions
float complex cacosf (float complex z)
Function Documentation
cacosf()
float complex cacosf (float complex z)
References casinf(), cimagf(), complex, crealf(), I, w, and z.
Referenced by cacoshf().