Embedded Artistry Framework: src/stdlibs/libc/test/string/string_tests.h File Reference
string_tests.h File Reference
Functions
int memcpy_tests (void)
int memset_tests (void)
int memmem_tests (void)
int memmove_tests (void)
int memcmp_tests (void)
int strcmp_tests (void)
int strcpy_tests (void)
int strdup_tests (void)
int strlen_tests (void)
int strncmp_tests (void)
int strncpy_tests (void)
int strndup_tests (void)
int strnlen_tests (void)
int strnstr_tests (void)
int strstr_tests (void)
int strchr_tests (void)
int strrchr_tests (void)
int strncat_tests (void)
int strcat_tests (void)
int strtok_tests (void)
Function Documentation
memcmp_tests()
int memcmp_tests (void)
References memcmp_test(), memcmp_tests(), and NULL.
Referenced by memcmp_tests(), and string_tests().
memcpy_tests()
int memcpy_tests (void)
References memcpy_aligned_test(), memcpy_tests(), and NULL.
Referenced by memcpy_tests(), and string_tests().
memmem_tests()
int memmem_tests (void)
References check_input(), memmem_tests(), and NULL.
Referenced by memmem_tests(), and string_tests().
memmove_tests()
int memmove_tests (void)
References memmove_test(), memmove_tests(), and NULL.
Referenced by memmove_tests(), and string_tests().
memset_tests()
int memset_tests (void)
References check_input(), memset_aligned_test(), memset_tests(), and NULL.
Referenced by memset_tests(), and string_tests().
strcat_tests()
int strcat_tests (void)
References NULL, strcat_test(), and strcat_tests().
Referenced by strcat_tests(), and string_tests().
strchr_tests()
int strchr_tests (void)
References NULL, strchr_test(), and strchr_tests().
Referenced by strchr_tests(), and string_tests().
strcmp_tests()
int strcmp_tests (void)
References NULL, strcmp_test(), and strcmp_tests().
Referenced by strcmp_tests(), and string_tests().
strcpy_tests()
int strcpy_tests (void)
References NULL, strcpy_test(), and strcpy_tests().
Referenced by strcpy_tests(), and string_tests().
strdup_tests()
int strdup_tests (void)
References NULL, strdup_test(), and strdup_tests().
Referenced by strdup_tests(), and string_tests().
strlen_tests()
int strlen_tests (void)
References NULL, and strlen_test().
Referenced by string_tests().
strncat_tests()
int strncat_tests (void)
References NULL, and strncat_test().
Referenced by string_tests().
strncmp_tests()
int strncmp_tests (void)
References NULL, and strncmp_test().
Referenced by string_tests().
strncpy_tests()
int strncpy_tests (void)
References NULL, and strncpy_test().
Referenced by string_tests().
strndup_tests()
int strndup_tests (void)
References NULL, and strndup_test().
Referenced by string_tests().
strnlen_tests()
int strnlen_tests (void)
References NULL, and strnlen_test().
Referenced by string_tests().
strnstr_tests()
int strnstr_tests (void)
References NULL, strnstr_test(), and strnstr_test_null().
Referenced by string_tests().
strrchr_tests()
int strrchr_tests (void)
References NULL, and strrchr_test().
Referenced by string_tests().
strstr_tests()
int strstr_tests (void)
References NULL, and strstr_test().
Referenced by string_tests().
strtok_tests()
int strtok_tests (void)
References NULL, and strtok_test().
Referenced by string_tests().