Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_atan.c File Reference
s_atan.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double atan (double x)
Variables
static const double atanhi []
static const double atanlo []
static const double aT []
static const double one = 1.0
static const double huge = 1.0e300
Function Documentation
atan()
OLM_DLLEXPORT double atan (double x)
References aT, atanhi, atanlo, fabs(), GET_HIGH_WORD, GET_LOW_WORD, huge, low, one, s1, s2, w, and z.
Referenced by __ieee754_atan2(), atan_test(), and main().
Variable Documentation
aT
const double aT[] static
Initial value:
= {
  3.33333333333329318027e-01,
 -1.99999999998764832476e-01,
  1.42857142725034663711e-01,
 -1.11111104054623557880e-01,
  9.09088713343650656196e-02,
 -7.69187620504482999495e-02,
  6.66107313738753120669e-02,
 -5.83357013379057348645e-02,
  4.97687799461593236017e-02,
 -3.65315727442169155270e-02,
  1.62858201153657823623e-02,
}
Referenced by atan().
atanhi
const double atanhi[] static
Initial value:
= {
  4.63647609000806093515e-01,
  7.85398163397448278999e-01,
  9.82793723247329054082e-01,
  1.57079632679489655800e+00,
}
Referenced by atan().
atanlo
const double atanlo[] static
Initial value:
= {
  2.26987774529616870924e-17,
  3.06161699786838301793e-17,
  1.39033110312309984516e-17,
  6.12323399573676603587e-17,
}
Referenced by atan().
huge
const double huge = 1.0e300 static
Referenced by atan().
one
const double one = 1.0 static
Referenced by atan().