Embedded Artistry Framework: BlinkySimulatorHWPlatform Class Reference
BlinkySimulatorHWPlatform Class Reference
#include <blinky_simulator_hw_platform.hpp>
Public Member Functions
BlinkySimulatorHWPlatform () noexcept
Default constructor.
~BlinkySimulatorHWPlatform () noexcept
Default destructor.
void init_ () noexcept
void initProcessor_ () noexcept
void soft_reset_ () noexcept
void hard_reset_ () noexcept
auto allocateTimer () noexcept
Allocate a software timer.
void startBlink () noexcept
Start the LED timer.
constexpr const std::string_view & name () const noexcept
Returns the Virtual HW Platform's name.
constexpr const char * name_cstr () const noexcept
Returns the platform name as a cstring for C API compatibility.
void initProcessor () noexcept
Initialize the processor.
void init () noexcept
Initialize the hardware platform.
void soft_reset () noexcept
Perform a soft reset of the system (chip reset)
void hard_reset () noexcept
Perform a hard reset of the system (power cycle)
void shutdown () noexcept
Shutdown the system.
Static Public Member Functions
static void earlyInitHook_ () noexcept
static void earlyInitHook () noexcept
Perform any special initialization steps.
Private Types
using PlatformBase = embvm::VirtualHwPlatformBase< BlinkySimulatorHWPlatform >
using TimerManager_t = embvm::TimerManager< 0, std::mutex >
Private Attributes
embutil::InterruptQueue< std::mutex > irq_bottom_half_
embdrv::SimulatorSystemClock sysclock
embdrv::aardvarkAdapter aardvark {embdrv::aardvarkMode::GpioI2C}
embdrv::aardvarkGPIOOutput< 5 > gpio5 {aardvark}
embvm::led::gpioActiveHigh led0 {gpio5}
embdrv::SimulatorTimer timer0
embdrv::SimulatorTimer timer1
TimerManager_t tm_ {timer1}
TimerManager_t::TimerHandle led_sw_timer_handle
SimulatorProcessor processor
Member Typedef Documentation
PlatformBase
using BlinkySimulatorHWPlatform::PlatformBase = embvm::VirtualHwPlatformBase<BlinkySimulatorHWPlatform> private
TimerManager_t
using BlinkySimulatorHWPlatform::TimerManager_t = embvm::TimerManager<0, std::mutex> private
Constructor & Destructor Documentation
BlinkySimulatorHWPlatform()
BlinkySimulatorHWPlatform::BlinkySimulatorHWPlatform () inline noexcept
Default constructor.
~BlinkySimulatorHWPlatform()
BlinkySimulatorHWPlatform::~BlinkySimulatorHWPlatform () noexcept
Default destructor.
Member Function Documentation
allocateTimer()
auto BlinkySimulatorHWPlatform::allocateTimer () inline noexcept
Allocate a software timer.
Allocates a software timer from the underlying timer manager. A handle is returned, which the user can use to configure the timer according to their wishes.
Returns
handle to a software timer object
References embvm::TimerManager< TMaxTimers, TLock, TTimeUnit, TTimeoutCallback, TTimerDevice >::allocate(), and tm_.
Referenced by init_().
earlyInitHook()
static void embvm::VirtualHwPlatformBase< BlinkySimulatorHWPlatform >::earlyInitHook () inline static noexcept inherited
Perform any special initialization steps.
The earlyInitHook_() function must be implemented by the derived class as a static function.
These functions run before the C Run-time setup functions are called, and normal functionality (e.g. OS concepts) are not available.
Early initialization steps represent any super early code that needs to execute. For example, DRAM might need to be initialized before the boot process can relocate memory to its proper location in memory.
These functions are declared static to prevent you from easily using drivers within their confines
earlyInitHook_()
static void BlinkySimulatorHWPlatform::earlyInitHook_ () inline static noexcept
hard_reset()
void embvm::VirtualHwPlatformBase< BlinkySimulatorHWPlatform >::hard_reset () inline noexcept inherited
Perform a hard reset of the system (power cycle)
The hard_reset_() function must be implemented by the derived class.
A hard reset is intended to perform a full power cycle of the system.
Platforms which do not support a hard reset should default to calling soft_reset().
hard_reset_()
void BlinkySimulatorHWPlatform::hard_reset_ () inline noexcept
References soft_reset_().
init()
void embvm::VirtualHwPlatformBase< BlinkySimulatorHWPlatform >::init () inline noexcept inherited
Initialize the hardware platform.
The init_() function must be implemented by the derived class.
Perform any hardware platform initialization steps, such as preparing peripherals for use, setting up callbacks, etc.
init_()
void BlinkySimulatorHWPlatform::init_ () noexcept
References allocateTimer(), embutil::InterruptQueue< TLockType, TSize >::getBoundDispatch(), irq_bottom_half_, led0, led_sw_timer_handle, embvm::HALDriverBase::setBottomHalfDispatcher(), embvm::DriverBase::start(), timer1, and embvm::led::gpio< TActiveHigh >::toggle().
initProcessor()
void embvm::VirtualHwPlatformBase< BlinkySimulatorHWPlatform >::initProcessor () inline noexcept inherited
Initialize the processor.
The initProcessor_() function must be implemented by the derived class.
Perform any steps necessary for initializing the processor & processor peripheral devices for use.
Note that this is only intended to be processor initialization. Platform initialization nis handled by the init() function.
This function will likely invoke the VirtualProcessor::init() function, but the order and actual initialization process is left to the derived class.
initProcessor_()
void BlinkySimulatorHWPlatform::initProcessor_ () inline noexcept
References embvm::VirtualProcessorBase< TProcessor >::init(), and processor.
name()
constexpr const std::string_view& embvm::VirtualHwPlatformBase< BlinkySimulatorHWPlatform >::name () const inline noexcept inherited
Returns the Virtual HW Platform's name.
name_cstr()
constexpr const char* embvm::VirtualHwPlatformBase< BlinkySimulatorHWPlatform >::name_cstr () const inline noexcept inherited
Returns the platform name as a cstring for C API compatibility.
shutdown()
void embvm::VirtualHwPlatformBase< BlinkySimulatorHWPlatform >::shutdown () inline noexcept inherited
Shutdown the system.
The shutdown_() function must be implemented by the derived class.
If your platform supports shutdown capability, take the proper steps to initiate a shutdown.
If the platform does not support shutdown capability, implement your shutdown_() function as an assert to notify users trying to call this API. You could also leave the shutdown_() function undefined. Anyone who calls the shutdown() function on a platform with an undefined shutdown_() function will encounter a compiler error.
The shutdown function is not expected to return.
soft_reset()
void embvm::VirtualHwPlatformBase< BlinkySimulatorHWPlatform >::soft_reset () inline noexcept inherited
Perform a soft reset of the system (chip reset)
The soft_reset_() function must be implemnted by the derived class.
A soft reset is intended to reset the program to the beginning without performing a full power cycle.
A good strategy is to just call virtual processor's reset() function, if one is provided.
soft_reset_()
void BlinkySimulatorHWPlatform::soft_reset_ () inline noexcept
Referenced by hard_reset_().
startBlink()
void BlinkySimulatorHWPlatform::startBlink () inline noexcept
Start the LED timer.
References embvm::DriverBase::start(), and timer1.
Member Data Documentation
aardvark
embdrv::aardvarkAdapter BlinkySimulatorHWPlatform::aardvark {embdrv::aardvarkMode::GpioI2C} private
gpio5
embdrv::aardvarkGPIOOutput<5> BlinkySimulatorHWPlatform::gpio5 {aardvark} private
irq_bottom_half_
embutil::InterruptQueue<std::mutex> BlinkySimulatorHWPlatform::irq_bottom_half_ private
Referenced by init_().
led0
embvm::led::gpioActiveHigh BlinkySimulatorHWPlatform::led0 {gpio5} private
Referenced by init_().
led_sw_timer_handle
TimerManager_t::TimerHandle BlinkySimulatorHWPlatform::led_sw_timer_handle private
Referenced by init_().
processor
SimulatorProcessor BlinkySimulatorHWPlatform::processor private
Referenced by initProcessor_().
sysclock
embdrv::SimulatorSystemClock BlinkySimulatorHWPlatform::sysclock private
timer0
embdrv::SimulatorTimer BlinkySimulatorHWPlatform::timer0 private
timer1
embdrv::SimulatorTimer BlinkySimulatorHWPlatform::timer1 private
Referenced by init_(), and startBlink().
tm_
TimerManager_t BlinkySimulatorHWPlatform::tm_ {timer1} private
Referenced by allocateTimer().
The documentation for this class was generated from the following files:
src/hw_platforms/blinky_simulator/blinky_simulator_hw_platform.hpp
src/hw_platforms/blinky_simulator/blinky_simulator_hw_platform.cpp