Embedded Artistry Framework: embvm::HALDriverBase Class Reference
embvm::HALDriverBase Class Reference abstract
#include <hal_driver.hpp>
Public Member Functions
void setBottomHalfDispatcher (const embutil::IRQDispatcherFunc_t &dispatcher) noexcept
template<typename TCallback >
void invokeCallback (TCallback &cb) noexcept
template<typename TCallback , typename... TArgs>
void invokeCallback (TCallback &cb, TArgs &... args) noexcept
virtual void enableInterrupts () noexcept=0
virtual void disableInterrupts () noexcept=0
Protected Member Functions
HALDriverBase ()=default
virtual ~HALDriverBase ()=default
Protected Attributes
embutil::IRQDispatcherFunc_t dispatcher_
Constructor & Destructor Documentation
HALDriverBase()
embvm::HALDriverBase::HALDriverBase () protected default
~HALDriverBase()
virtual embvm::HALDriverBase::~HALDriverBase () protected virtual default
Member Function Documentation
disableInterrupts()
virtual void embvm::HALDriverBase::disableInterrupts () pure virtual noexcept
Implemented in nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >, nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >, and embdrv::SimulatorTimer.
enableInterrupts()
virtual void embvm::HALDriverBase::enableInterrupts () pure virtual noexcept
Implemented in nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >, nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >, and embdrv::SimulatorTimer.
invokeCallback() [1/2]
template<typename TCallback > void embvm::HALDriverBase::invokeCallback (TCallback & cb) inline noexcept
References dispatcher_.
Referenced by embdrv::SimulatorTimer::timer_thread(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::twim_callback_().
invokeCallback() [2/2]
template<typename TCallback , typename... TArgs> void embvm::HALDriverBase::invokeCallback (TCallback & cb, TArgs &... args) inline noexcept
References dispatcher_.
setBottomHalfDispatcher()
void embvm::HALDriverBase::setBottomHalfDispatcher (const embutil::IRQDispatcherFunc_t & dispatcher) inline noexcept
References dispatcher_.
Referenced by BlinkySimulatorHWPlatform::init_(), and FWDemoSimulatorHWPlatform::init_().
Member Data Documentation
dispatcher_
embutil::IRQDispatcherFunc_t embvm::HALDriverBase::dispatcher_ protected
Referenced by invokeCallback(), and setBottomHalfDispatcher().
The documentation for this class was generated from the following file:
src/core/driver/hal_driver.hpp