Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_creal.c File Reference
s_creal.c File Reference
#include <openlibm_complex.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double creal (double complex z)
Function Documentation
creal()
OLM_DLLEXPORT double creal (double complex z)
References z.
Referenced by __ldexp_cexp(), _ctans(), cabs(), cacos(), carg(), casin(), catan(), ccos(), ccosh(), cexp(), clog(), conj(), cpow(), cproj(), csin(), csinh(), csqrt(), ctan(), and ctanh().