Embedded Artistry Framework: src/processors/arm/nordic/drivers/helpers/gpio_helper.cpp File Reference
gpio_helper.cpp File Reference
#include "gpio_helper.hpp"
#include <processor_includes.hpp>
#include <volatile/volatile.hpp>
Macros
#define NRF_P0 NRF_GPIO
Implementation of the GPIO drivers is handled here so we can keep the ARM/Nordic headers decoupled from the rest of the system.
Functions
static NRF_GPIO_Type * portDecode (uint8_t port)
static void configure (uint8_t port, uint8_t pin, uint8_t dir, uint8_t input, uint8_t pull, uint8_t drive, uint8_t sense) noexcept
Macro Definition Documentation
NRF_P0
#define NRF_P0 NRF_GPIO
Implementation of the GPIO drivers is handled here so we can keep the ARM/Nordic headers decoupled from the rest of the system.
Function Documentation
configure()
static void configure (uint8_t port, uint8_t pin, uint8_t dir, uint8_t input, uint8_t pull, uint8_t drive, uint8_t sense) inline static noexcept
References portDecode(), and embutil::volatile_store().
Referenced by nRFGPIOTranslator::configure_default(), nRFGPIOTranslator::configure_i2c(), nRFGPIOTranslator::configure_input(), and nRFGPIOTranslator::configure_output().
portDecode()
static NRF_GPIO_Type* portDecode (uint8_t port) inline static
References NRF_P0.
Referenced by nRFGPIOTranslator::clear(), configure(), and nRFGPIOTranslator::set().