Embedded Artistry Framework: src/drivers/solomon_systech/ssd1306/ssd1306.cpp File Reference
ssd1306.cpp File Reference
#include "ssd1306.hpp"
#include "font/font5x7.h"
#include "font/font8x16.h"
#include <algorithm>
#include <bits/bits.hpp>
#include <gsl/gsl>
Variables
static constexpr uint8_t font_count_ = UINT8_C(2)
static constexpr uint8_t FONT_HEADER_SIZE = UINT8_C(6)
static uint8_t i2c_data_byte_ = UINT8_C(0x40)
constexpr uint8_t I2C_COMMAND_REG = UINT8_C(0x0)
Variable Documentation
font_count_
constexpr uint8_t font_count_ = UINT8_C(2) static
Referenced by embdrv::ssd1306::fontType(), and embdrv::ssd1306::totalFonts().
FONT_HEADER_SIZE
constexpr uint8_t FONT_HEADER_SIZE = UINT8_C(6) static
Referenced by embdrv::ssd1306::drawCharMultiRow(), and embdrv::ssd1306::drawCharSingleRow().
I2C_COMMAND_REG
constexpr uint8_t I2C_COMMAND_REG = UINT8_C(0x0)
Referenced by embdrv::ssd1306::command().
i2c_data_byte_
uint8_t i2c_data_byte_ = UINT8_C(0x40) static
Referenced by embdrv::ssd1306::data().