Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/k_rem_pio2.c File Reference
k_rem_pio2.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT int __kernel_rem_pio2 (double *x, double *y, int e0, int nx, int prec)
Variables
static const int init_jk [] = {3,4,4,6}
static const int32_t ipio2 []
static const double PIo2 []
static const double zero = 0.0
static const double one = 1.0
static const double two24 = 1.67772160000000000000e+07
static const double twon24 = 5.96046447753906250000e-08
Function Documentation
__kernel_rem_pio2()
OLM_DLLEXPORT int __kernel_rem_pio2 (double * x, double * y, int e0, int nx, int prec)
References floor(), init_jk, ipio2, k, n, one, PIo2, scalbn(), STRICT_ASSIGN, two24, twon24, z, and zero.
Referenced by __ieee754_rem_pio2(), __ieee754_rem_pio2f(), and __ieee754_rem_pio2l().
Variable Documentation
init_jk
const int init_jk[] = {3,4,4,6} static
Referenced by __kernel_rem_pio2().
ipio2
const int32_t ipio2[] static
Referenced by __kernel_rem_pio2().
one
const double one = 1.0 static
Referenced by __kernel_rem_pio2().
PIo2
const double PIo2[] static
Initial value:
= {
  1.57079625129699707031e+00,
  7.54978941586159635335e-08,
  5.39030252995776476554e-15,
  3.28200341580791294123e-22,
  1.27065575308067607349e-29,
  1.22933308981111328932e-36,
  2.73370053816464559624e-44,
  2.16741683877804819444e-51,
}
Referenced by __kernel_rem_pio2().
two24
const double two24 = 1.67772160000000000000e+07 static
Referenced by __kernel_rem_pio2().
twon24
const double twon24 = 5.96046447753906250000e-08 static
Referenced by __kernel_rem_pio2().
zero
const double zero = 0.0 static
Referenced by __kernel_rem_pio2().