Embedded Artistry Framework: embvm::tof::sensor Class Reference
embvm::tof::sensor Class Reference abstract
This class defines common time-of-flight (ToF) sensor interfaces.
#include <time_of_flight.hpp>
Public Types
using read_cb_t = stdext::inplace_function< void(uint16_t)>
ToF Callback function which retuns distance in mm.
Public Member Functions
sensor ()
Default constructor.
sensor (const char *name)
Construct an tof::sensor with a C-string name.
sensor (const std::string &name)
Construct an tof::sensor with a std::string name.
sensor (const std::string_view &name)
Construct an tof::sensor with a std::string_view name.
virtual tof::distance_t getMaxRangeForModeDark (tof::mode m) const =0
Check the maximum range in the dark.
virtual tof::distance_t getMaxRangeForModeStrongLight (tof::mode m) const =0
Check the maximum range in strong light conditions.
tof::mode mode () const noexcept
Get the ToF ranging mode.
virtual tof::mode mode (tof::mode m)=0
Set the ToF ranging mode.
virtual void registerReadCallback (const read_cb_t &cb)=0
Register a callback for the read() function.
virtual void registerReadCallback (read_cb_t &&cb)=0
Register a callback for the read() function.
virtual void read ()=0
Trigger a sensor read.
virtual void reset ()=0
Reset the ToF sensor.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
ToF Driver Type ID.
Protected Member Functions
~sensor () override
Default destructor.
void start_ () override=0
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () override=0
Derived classes override the start_ method to control driver-specific startup behavior.
Protected Attributes
tof::mode mode_ = tof::mode::defaultRange
The configured ranging mode for the ToF sensor.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Detailed Description
This class defines common time-of-flight (ToF) sensor interfaces.
tof::sensor is the base class for time-of-flight (ToF) sensor devices.
Define a ToF Driver
To define a ToF driver, derive from the tof::sensor object:
class vl53l1x final : public tof::sensor
{ ... };
Derived classes must implement the following functions:
read()
reset()
registerReadCallback()
mode()
getMaxRangeForModeDark()
getMaxRangeForModeStrongLight()
Additional sensor-specific functions may be defined. They are simply not available in the public/common interface.
Derived classes must also implement pure virtual embvm::DriverBase functions:
start_()
stop_()
Using a ToF driver
The ToF driver should be configured with the desired ranging mode (tof::mode) using the mode() function.
Once the sensor is configured, a callback should be registered via registerReadCallback(). The callback is required in order to receive results from the read() command.
To get a range result from the sensor, call the read() function. The function operates asynchronously and will return immediately. When the read operation completes, registered callbacks will be called.
Member Typedef Documentation
read_cb_t
using embvm::tof::sensor::read_cb_t = stdext::inplace_function<void(uint16_t)>
ToF Callback function which retuns distance in mm.
Constructor & Destructor Documentation
sensor() [1/4]
embvm::tof::sensor::sensor () inline
Default constructor.
Initializes the tof::sensor instance with a generic name.
sensor() [2/4]
embvm::tof::sensor::sensor (const char * name) inline
Construct an tof::sensor with a C-string name.
Initializes the tof::sensor instance with a name.
Parameters
name The name of the ToF instance.
sensor() [3/4]
embvm::tof::sensor::sensor (const std::string & name) inline
Construct an tof::sensor with a std::string name.
Initializes the tof::sensor instance with a name.
Parameters
name The name of the ToF instance. tof::sensor() uses a std::string_view, so the std::string must remain valid
sensor() [4/4]
embvm::tof::sensor::sensor (const std::string_view & name) inline
Construct an tof::sensor with a std::string_view name.
Initializes the tof::sensor instance with a name.
Parameters
name The name of the ToF instance.
~sensor()
embvm::tof::sensor::~sensor () override protected default
Default destructor.
Member Function Documentation
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
getMaxRangeForModeDark()
virtual tof::distance_t embvm::tof::sensor::getMaxRangeForModeDark (tof::mode m) const pure virtual
Check the maximum range in the dark.
Returns
the sensor's maximum distance capability (in mm) in the dark.
Implemented in embdrv::vl53l1x.
getMaxRangeForModeStrongLight()
virtual tof::distance_t embvm::tof::sensor::getMaxRangeForModeStrongLight (tof::mode m) const pure virtual
Check the maximum range in strong light conditions.
Returns
the sensor's maximum distance capability (in mm) in strong light.
Implemented in embdrv::vl53l1x.
mode() [1/2]
tof::mode embvm::tof::sensor::mode () const inline noexcept
Get the ToF ranging mode.
Returns
the currently configured ToF ranging mode.
References mode_.
mode() [2/2]
virtual tof::mode embvm::tof::sensor::mode (tof::mode m) pure virtual
Set the ToF ranging mode.
Parameters
m The desired ToF ranging mode.
Returns
the active ToF mode.
Implemented in embdrv::vl53l1x.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
read()
virtual void embvm::tof::sensor::read () pure virtual
Trigger a sensor read.
Trigger an asynchronous read of the ToF sensor. The result will be provided to consumers through a callback function. When the read() operation completes, the callback will be invoked with the result.
Implemented in embdrv::vl53l1x.
registerReadCallback() [1/2]
virtual void embvm::tof::sensor::registerReadCallback (const read_cb_t & cb) pure virtual
Register a callback for the read() function.
The read() function works asynchronously, and the result will be provided to consumers through a callback function. When the read() operation completes, the callback will be invoked with the result.
This function must be implemented by the derived class.
Parameters
cb The functor which will be called when read() completes.
Implemented in embdrv::vl53l1x.
Referenced by FrameworkDemoSimPlatform::init_().
registerReadCallback() [2/2]
virtual void embvm::tof::sensor::registerReadCallback (read_cb_t && cb) pure virtual
Register a callback for the read() function.
The read() function works asynchronously, and the result will be provided to consumers through a callback function. When the read() operation completes, the callback will be invoked with the result.
This function must be implemented by the derived class.
Parameters
cb The functor which will be called when read() completes.
Implemented in embdrv::vl53l1x.
reset()
virtual void embvm::tof::sensor::reset () pure virtual
Reset the ToF sensor.
Implemented in embdrv::vl53l1x.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void embvm::tof::sensor::start_ () override protected pure virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in embdrv::vl53l1x.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void embvm::tof::sensor::stop_ () override protected pure virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in embdrv::vl53l1x.
type()
static constexpr embvm::DriverType embvm::tof::sensor::type () inline static
ToF Driver Type ID.
Returns
ToF type ID.
References embvm::TIME_OF_FLIGHT.
Member Data Documentation
mode_
tof::mode embvm::tof::sensor::mode_ = tof::mode::defaultRange protected
The configured ranging mode for the ToF sensor.
Referenced by mode().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
The documentation for this class was generated from the following files:
src/core/driver/time_of_flight.hpp
src/core/driver/internal/time_of_flight.cpp