Embedded Artistry libc: src/string/strrchr.c File Reference
strrchr.c File Reference
#include <string.h>
Functions
void * __memrchr (const void *, int, size_t)
char * strrchr (const char *s, int c)
Finds the last occurrence of c in the null-terminated byte string pointed to by s.
Function Documentation
__memrchr()
void* __memrchr (const void * , int , size_t)
Definition at line 7 of file memrchr.c.
 {
     const unsigned char* s = m;
     c = (unsigned char)c;
     while(n--)
     {
         if(s[n] == c)
         {
             return (void*)(uintptr_t)(s + n);
         }
     }
     return 0;
 }
Referenced by strrchr().
strrchr()
char* strrchr (const char * s, int c)
Finds the last occurrence of c in the null-terminated byte string pointed to by s.
Finds the last occurrence of c (after conversion to char as if by (char)c) in the null-terminated byte string pointed to by s (each character interpreted as unsigned char). The terminating null character is considered to be a part of the string and can be found when searching for '\0'.
The behavior is undefined if s is not a pointer to a null-terminated byte string.
Parameters
s pointer to the null-terminated byte string to be analyzed
c character to search for
Returns
a pointer to the found character in s, or null pointer if no such character is found.
Definition at line 7 of file strrchr.c.
 {
     return __memrchr(s, c, strlen(s) + 1);
 }
References __memrchr(), and strlen().