Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/math_private_openbsd.h File Reference
math_private_openbsd.h File Reference
Classes
union ieee_quad_shape_type
union ieee_quad_shape_type
union ieee_extended_shape_type
union ieee_extended_shape_type
struct ieee_quad_shape_type.parts32
struct ieee_quad_shape_type.parts64
struct ieee_quad_shape_type.parts32
struct ieee_quad_shape_type.parts64
struct ieee_extended_shape_type.parts
struct ieee_extended_shape_type.parts
Macros
#define GET_LDOUBLE_WORDS64(ix0, ix1, d)
#define SET_LDOUBLE_WORDS64(d, ix0, ix1)
#define GET_LDOUBLE_MSW64(v, d)
#define SET_LDOUBLE_MSW64(d, v)
#define GET_LDOUBLE_LSW64(v, d)
#define GET_LDOUBLE_WORDS(se, ix0, ix1, d)
#define SET_LDOUBLE_WORDS(d, se, ix0, ix1)
#define GET_LDOUBLE_MSW(v, d)
#define SET_LDOUBLE_MSW(d, v)
#define GET_LDOUBLE_EXP(se, d)
#define SET_LDOUBLE_EXP(d, se)
Functions
void __scan_nan (uint32_t *__words, int __num_words, const char *__s)
double __exp__D (double, double)
struct Double __log__D (double)
long double __p1evll (long double, void *, int)
long double __polevll (long double, void *, int)
Class Documentation
ieee_quad_shape_type
union ieee_quad_shape_type
Class Members
struct ieee_quad_shape_type parts32
struct ieee_quad_shape_type parts32
struct ieee_quad_shape_type parts64
struct ieee_quad_shape_type parts64
long double value
ieee_quad_shape_type
union ieee_quad_shape_type
Class Members
struct ieee_quad_shape_type parts32
struct ieee_quad_shape_type parts32
struct ieee_quad_shape_type parts64
struct ieee_quad_shape_type parts64
long double value
ieee_extended_shape_type
union ieee_extended_shape_type
Class Members
struct ieee_extended_shape_type parts
struct ieee_extended_shape_type parts
long double value
ieee_extended_shape_type
union ieee_extended_shape_type
Class Members
struct ieee_extended_shape_type parts
struct ieee_extended_shape_type parts
long double value
ieee_quad_shape_type.parts32
struct ieee_quad_shape_type.parts32
Class Members
u_int32_t lswhi
u_int32_t lswlo
u_int32_t mswhi
u_int32_t mswlo
ieee_quad_shape_type.parts64
struct ieee_quad_shape_type.parts64
Class Members
u_int64_t lsw
u_int64_t msw
ieee_quad_shape_type.parts32
struct ieee_quad_shape_type.parts32
Class Members
u_int32_t lswhi
u_int32_t lswlo
u_int32_t mswhi
u_int32_t mswlo
ieee_quad_shape_type.parts64
struct ieee_quad_shape_type.parts64
Class Members
u_int64_t lsw
u_int64_t msw
ieee_extended_shape_type.parts
struct ieee_extended_shape_type.parts
Class Members
int exp:16
u_int32_t lsw
u_int32_t msw
int padl:16
ieee_extended_shape_type.parts
struct ieee_extended_shape_type.parts
Class Members
int exp:16
u_int32_t lsw
u_int32_t msw
int padl:16
Macro Definition Documentation
GET_LDOUBLE_EXP
#define GET_LDOUBLE_EXP (se, d)
Value:
do {                                \
  ieee_extended_shape_type ge_u;                \
  ge_u.value = (d);                     \
  (se) = ge_u.parts.exp;                    \
} while (0)
GET_LDOUBLE_LSW64
#define GET_LDOUBLE_LSW64 (v, d)
Value:
do {                                \
  ieee_quad_shape_type sh_u;                    \
  sh_u.value = (d);                     \
  (v) = sh_u.parts64.lsw;                   \
} while (0)
GET_LDOUBLE_MSW
#define GET_LDOUBLE_MSW (v, d)
Value:
do {                                \
  ieee_extended_shape_type sh_u;                \
  sh_u.value = (d);                     \
  (v) = sh_u.parts.msw;                     \
} while (0)
GET_LDOUBLE_MSW64
#define GET_LDOUBLE_MSW64 (v, d)
Value:
do {                                \
  ieee_quad_shape_type sh_u;                    \
  sh_u.value = (d);                     \
  (v) = sh_u.parts64.msw;                   \
} while (0)
GET_LDOUBLE_WORDS
#define GET_LDOUBLE_WORDS (se, ix0, ix1, d)
Value:
do {                                \
  ieee_extended_shape_type ew_u;                \
  ew_u.value = (d);                     \
  (se) = ew_u.parts.exp;                    \
  (ix0) = ew_u.parts.msw;                   \
  (ix1) = ew_u.parts.lsw;                   \
} while (0)
GET_LDOUBLE_WORDS64
#define GET_LDOUBLE_WORDS64 (ix0, ix1, d)
Value:
do {                                \
  ieee_quad_shape_type qw_u;                    \
  qw_u.value = (d);                     \
  (ix0) = qw_u.parts64.msw;                 \
  (ix1) = qw_u.parts64.lsw;                 \
} while (0)
SET_LDOUBLE_EXP
#define SET_LDOUBLE_EXP (d, se)
Value:
do {                                \
  ieee_extended_shape_type se_u;                \
  se_u.value = (d);                     \
  se_u.parts.exp = (se);                    \
  (d) = se_u.value;                     \
} while (0)
SET_LDOUBLE_MSW
#define SET_LDOUBLE_MSW (d, v)
Value:
do {                                \
  ieee_extended_shape_type sh_u;                \
  sh_u.value = (d);                     \
  sh_u.parts.msw = (v);                     \
  (d) = sh_u.value;                     \
} while (0)
SET_LDOUBLE_MSW64
#define SET_LDOUBLE_MSW64 (d, v)
Value:
do {                                \
  ieee_quad_shape_type sh_u;                    \
  sh_u.value = (d);                     \
  sh_u.parts64.msw = (v);                   \
  (d) = sh_u.value;                     \
} while (0)
SET_LDOUBLE_WORDS
#define SET_LDOUBLE_WORDS (d, se, ix0, ix1)
Value:
do {                                \
  ieee_extended_shape_type iw_u;                \
  iw_u.parts.exp = (se);                    \
  iw_u.parts.msw = (ix0);                   \
  iw_u.parts.lsw = (ix1);                   \
  (d) = iw_u.value;                     \
} while (0)
SET_LDOUBLE_WORDS64
#define SET_LDOUBLE_WORDS64 (d, ix0, ix1)
Value:
do {                                \
  ieee_quad_shape_type qw_u;                    \
  qw_u.parts64.msw = (ix0);                 \
  qw_u.parts64.lsw = (ix1);                 \
  (d) = qw_u.value;                     \
} while (0)
Function Documentation
__exp__D()
double __exp__D (double , double)
References copysign(), invln2, isfinite, k, ln2hi, ln2lo, lnhuge, lntiny, p1, p2, p3, p4, p5, scalbn(), and z.
Referenced by neg_gam(), and tgamma().
__log__D()
struct Double __log__D (double)
Referenced by neg_gam().
__p1evll()
long double __p1evll (long double , void * , int)
References n, and P.
Referenced by log10l(), log1pl(), log2l(), logl(), and powl().
__polevll()
long double __polevll (long double , void * , int)
References n, and P.
Referenced by expl(), log10l(), log1pl(), log2l(), logl(), powl(), stirf(), and tgammal().
__scan_nan()
void __scan_nan (uint32_t * __words, int __num_words, const char * __s)
References digittoint(), isxdigit(), memset(), OLM_DLLEXPORT, and s.
Referenced by nan(), and nanf().