Embedded Artistry Framework: Framework Utilities
Framework Utilities
Embedded Framework utility classes and functions.
Modules
Bit Manipulation
Functions and macros that operate in a bitwise manner.
Scope-bound Resource Management
Utilties that enable SBRM techniques.
Dispatch Queues
Group of worker threads that enables asynchronous processing.
Endian Swap
Functions that can be used to swap the endianness of a value.
Function Queue
Queues for storing function objects.
Instance List
Supports tracking instances which can come and go during runtime.
C Linked List Interface
A linked list library for C modules.
Special Function Register
Safer types for working with special-function registers.
Time Utilities
Functions that work with C and C++ time types.
Volatile load/store
These functions promote safer loading and storing of volatile values.
Classes
class InterruptQueue< TLockType, TSize >
IRQ safe dispatch queue (For running application-level (bottom-half) interrupt handlers)
class embutil::InterruptLock< InterruptLockPolicy >
BasicLockable class which disables/enables interrupts.
Functions
template<class TClass , class Method , Method m, class... Params>
static auto embutil::bounce (void *priv, Params... params) -> decltype(((*reinterpret_cast< TClass * >(priv)).*m)(params...))
Enable a C++ member function to work with a C-style callback interface.
Detailed Description
Embedded Framework utility classes and functions.
Class Documentation
InterruptQueue
class InterruptQueue
template<typename TLockType, const size_t TSize = 32>
class InterruptQueue< TLockType, TSize >
IRQ safe dispatch queue (For running application-level (bottom-half) interrupt handlers)
This dispatch queue can queue operations from a context which cannot acquire a mutex The function queue is fully serial, so each operation will execute in order.
This queue uses only static memory to avoid the potential for dynamic memory allocations in an IRQ context
This queue represents the bottom-half handler of an IRQ system. To avoid operations impacting the IRQ latency, this queue forwards interrupt operations to a standard dispatch queue for execution.
TDisableOp and TEnableOp are functions which enable/disable interrupts. TDisableOp must be an operation which returns a value that can be passed into TEnableOp. TDisableOp's return is used to restore the proper value once interrupts are re-enabled.
Public Member Functions
InterruptQueue ()
~InterruptQueue ()
InterruptQueue (const InterruptQueue &)=delete
Deleted copy constructor.
const InterruptQueue & operator= (const InterruptQueue &)=delete
Deleted copy assignment operator.
InterruptQueue (InterruptQueue &&)=delete
Deleted move constructor.
InterruptQueue & operator= (InterruptQueue &&)=delete
Deleted move assignment operator.
void dispatch (const IRQBottomHalfOp_t &op)
Dispatch an operation to the thread via copy Adds the operation to the queue.
void dispatch (IRQBottomHalfOp_t &&op)
Dispatch an operation to the thread via move Adds the operation to the queue.
auto getBoundDispatch ()
size_t queue_size () const
Return the current number of enqueued operations.
constexpr size_t capacity ()
Return the capacity of the queue.
constexpr size_t thread_count ()
Return the number of threads associated with the interrupt queue (always 1)
Private Member Functions
bool wait_and_pop (IRQBottomHalfOp_t &op)
Convenience function which waits for the queue and pops off of it without requiring excessive locks/unlocks.
void dispatch_thread_handler (void)
Thread handler for dispatch queue threads Sleeps until there is an operation in the thread (or quit_ is set) Processes operations from queue.
Private Attributes
std::thread thread_
embvm::VirtualEventFlag * flags_
etl::queue< IRQBottomHalfOp_t, TSize > q_
TLockType irq_lock_
Static Private Attributes
static constexpr uint32_t WORK_READY_FLAG = (1 << 0)
static constexpr uint32_t QUIT_FLAG = (1 << 1)
Constructor & Destructor Documentation
InterruptQueue() [1/3]
template<typename TLockType, const size_t TSize = 32> InterruptQueue< TLockType, TSize >::InterruptQueue () inline explicit
~InterruptQueue()
template<typename TLockType, const size_t TSize = 32> InterruptQueue< TLockType, TSize >::~InterruptQueue () inline
InterruptQueue() [2/3]
template<typename TLockType, const size_t TSize = 32> InterruptQueue< TLockType, TSize >::InterruptQueue (const InterruptQueue< TLockType, TSize > &) delete
Deleted copy constructor.
InterruptQueue() [3/3]
template<typename TLockType, const size_t TSize = 32> InterruptQueue< TLockType, TSize >::InterruptQueue (InterruptQueue< TLockType, TSize > &&) delete
Deleted move constructor.
Member Function Documentation
capacity()
template<typename TLockType, const size_t TSize = 32> constexpr size_t InterruptQueue< TLockType, TSize >::capacity () inline
Return the capacity of the queue.
dispatch() [1/2]
template<typename TLockType, const size_t TSize = 32> void InterruptQueue< TLockType, TSize >::dispatch (const IRQBottomHalfOp_t & op) inline
Dispatch an operation to the thread via copy Adds the operation to the queue.
Referenced by InterruptQueue< ThumbInterruptLock, 156 >::getBoundDispatch().
dispatch() [2/2]
template<typename TLockType, const size_t TSize = 32> void InterruptQueue< TLockType, TSize >::dispatch (IRQBottomHalfOp_t && op) inline
Dispatch an operation to the thread via move Adds the operation to the queue.
dispatch_thread_handler()
template<typename TLockType, const size_t TSize = 32> void InterruptQueue< TLockType, TSize >::dispatch_thread_handler (void) inline private
Thread handler for dispatch queue threads Sleeps until there is an operation in the thread (or quit_ is set) Processes operations from queue.
Referenced by InterruptQueue< ThumbInterruptLock, 156 >::InterruptQueue().
getBoundDispatch()
template<typename TLockType, const size_t TSize = 32> auto InterruptQueue< TLockType, TSize >::getBoundDispatch () inline
operator=() [1/2]
template<typename TLockType, const size_t TSize = 32> const InterruptQueue& InterruptQueue< TLockType, TSize >::operator= (const InterruptQueue< TLockType, TSize > &) delete
Deleted copy assignment operator.
operator=() [2/2]
template<typename TLockType, const size_t TSize = 32> InterruptQueue& InterruptQueue< TLockType, TSize >::operator= (InterruptQueue< TLockType, TSize > &&) delete
Deleted move assignment operator.
queue_size()
template<typename TLockType, const size_t TSize = 32> size_t InterruptQueue< TLockType, TSize >::queue_size () const inline
Return the current number of enqueued operations.
thread_count()
template<typename TLockType, const size_t TSize = 32> constexpr size_t InterruptQueue< TLockType, TSize >::thread_count () inline
Return the number of threads associated with the interrupt queue (always 1)
wait_and_pop()
template<typename TLockType, const size_t TSize = 32> bool InterruptQueue< TLockType, TSize >::wait_and_pop (IRQBottomHalfOp_t & op) inline private
Convenience function which waits for the queue and pops off of it without requiring excessive locks/unlocks.
Using a reference parameter to receive the result is used to transfer ownership out of the queue in order to avoid the exception safety issues of returning data by-value: if the copy constructor of a by-value return throws, then the data has been removed from the queue, but is lost, whereas with this approach, the potentially problematic copy is performed prior to modifying the queue (see Herb Sutter's Guru Of The Week #8 for a discussion of the issues).4
Returns
false if the thread should exit, true otherwise
Referenced by InterruptQueue< ThumbInterruptLock, 156 >::dispatch_thread_handler().
Member Data Documentation
flags_
template<typename TLockType, const size_t TSize = 32> embvm::VirtualEventFlag* InterruptQueue< TLockType, TSize >::flags_ private
Referenced by InterruptQueue< ThumbInterruptLock, 156 >::dispatch(), InterruptQueue< ThumbInterruptLock, 156 >::InterruptQueue(), InterruptQueue< ThumbInterruptLock, 156 >::wait_and_pop(), and InterruptQueue< ThumbInterruptLock, 156 >::~InterruptQueue().
irq_lock_
template<typename TLockType, const size_t TSize = 32> TLockType InterruptQueue< TLockType, TSize >::irq_lock_ private
Referenced by InterruptQueue< ThumbInterruptLock, 156 >::dispatch(), and InterruptQueue< ThumbInterruptLock, 156 >::wait_and_pop().
q_
template<typename TLockType, const size_t TSize = 32> etl::queue<IRQBottomHalfOp_t, TSize> InterruptQueue< TLockType, TSize >::q_ private
Referenced by InterruptQueue< ThumbInterruptLock, 156 >::capacity(), InterruptQueue< ThumbInterruptLock, 156 >::dispatch(), InterruptQueue< ThumbInterruptLock, 156 >::queue_size(), and InterruptQueue< ThumbInterruptLock, 156 >::wait_and_pop().
QUIT_FLAG
template<typename TLockType, const size_t TSize = 32> constexpr uint32_t InterruptQueue< TLockType, TSize >::QUIT_FLAG = (1 << 1) static private
Referenced by InterruptQueue< ThumbInterruptLock, 156 >::wait_and_pop(), and InterruptQueue< ThumbInterruptLock, 156 >::~InterruptQueue().
thread_
template<typename TLockType, const size_t TSize = 32> std::thread InterruptQueue< TLockType, TSize >::thread_ private
Referenced by InterruptQueue< ThumbInterruptLock, 156 >::InterruptQueue(), and InterruptQueue< ThumbInterruptLock, 156 >::~InterruptQueue().
WORK_READY_FLAG
template<typename TLockType, const size_t TSize = 32> constexpr uint32_t InterruptQueue< TLockType, TSize >::WORK_READY_FLAG = (1 << 0) static private
Referenced by InterruptQueue< ThumbInterruptLock, 156 >::dispatch(), and InterruptQueue< ThumbInterruptLock, 156 >::wait_and_pop().
embutil::InterruptLock
class embutil::InterruptLock
template<typename InterruptLockPolicy>
class embutil::InterruptLock< InterruptLockPolicy >
BasicLockable class which disables/enables interrupts.
This class defines a BasicLockable interface for enabling and disabling interrupts. The lock() function is used to disable interrupts, and unlock() to enable them.
Note
This lock is not re-entrant.
Public Member Functions
InterruptLock ()=default
Default constructor.
~InterruptLock ()=default
Default destructor.
InterruptLock (const InterruptLock &)=delete
Deleted copy constructor.
const InterruptLock & operator= (const InterruptLock &)=delete
Deleted copy assignment operator.
InterruptLock (InterruptLock &&)=default
Deleted move constructor.
InterruptLock & operator= (InterruptLock &&)=default
Deleted move assignment operator.
void lock ()
Disable interrupts to enter critical section.
void unlock ()
Enable interrupts to leave critical section.
Private Attributes
InterruptLockPolicy::TReturn irq_status_
Local storage for the disable function result, which is passed into the enable function to ensure we restore the prior value.
Constructor & Destructor Documentation
InterruptLock() [1/3]
template<typename InterruptLockPolicy > embutil::InterruptLock< InterruptLockPolicy >::InterruptLock () default
Default constructor.
~InterruptLock()
template<typename InterruptLockPolicy > embutil::InterruptLock< InterruptLockPolicy >::~InterruptLock () default
Default destructor.
InterruptLock() [2/3]
template<typename InterruptLockPolicy > embutil::InterruptLock< InterruptLockPolicy >::InterruptLock (const InterruptLock< InterruptLockPolicy > &) delete
Deleted copy constructor.
InterruptLock() [3/3]
template<typename InterruptLockPolicy > embutil::InterruptLock< InterruptLockPolicy >::InterruptLock (InterruptLock< InterruptLockPolicy > &&) default
Deleted move constructor.
Member Function Documentation
lock()
template<typename InterruptLockPolicy > void embutil::InterruptLock< InterruptLockPolicy >::lock () inline
Disable interrupts to enter critical section.
References embutil::InterruptLock< InterruptLockPolicy >::irq_status_.
operator=() [1/2]
template<typename InterruptLockPolicy > const InterruptLock& embutil::InterruptLock< InterruptLockPolicy >::operator= (const InterruptLock< InterruptLockPolicy > &) delete
Deleted copy assignment operator.
operator=() [2/2]
template<typename InterruptLockPolicy > InterruptLock& embutil::InterruptLock< InterruptLockPolicy >::operator= (InterruptLock< InterruptLockPolicy > &&) default
Deleted move assignment operator.
unlock()
template<typename InterruptLockPolicy > void embutil::InterruptLock< InterruptLockPolicy >::unlock () inline
Enable interrupts to leave critical section.
References embutil::InterruptLock< InterruptLockPolicy >::irq_status_.
Member Data Documentation
irq_status_
template<typename InterruptLockPolicy > InterruptLockPolicy::TReturn embutil::InterruptLock< InterruptLockPolicy >::irq_status_ private
Local storage for the disable function result, which is passed into the enable function to ensure we restore the prior value.
Referenced by embutil::InterruptLock< InterruptLockPolicy >::lock(), and embutil::InterruptLock< InterruptLockPolicy >::unlock().
Function Documentation
bounce()
template<class TClass , class Method , Method m, class... Params> static auto embutil::bounce (void * priv, Params... params) -> decltype(((*reinterpret_cast<TClass*>(priv)).*m)(params...)) static
Enable a C++ member function to work with a C-style callback interface.
This function is intended to be passed to a C-style callback system which takes a function pointer and private data pointer as input values. Using C-style callbacks is problematic with object member functions, as you need the object's pointer to get to the correct instance.
This bounce function requires use of the private data pointer in a C-style callback. The data pointer must be used for the object's instance pointer. Any other provided arguments are forwarded to the object's member function, and the return value is passed to the caller.
You can simplify this call with the BOUNCE() macro.
You may need to reinterpret_cast the bounce function to the expected type:
reinterpret_cast<void*(*)(void*)>(BOUNCE(c, function))
You will need to couple a bounce function with the this pointer as a function input to get to the correct instance.
Example usage with a C-style callback interface
posixThread is a C++ class, and posixThread::thread_func() is a member function which we want to pass to pthread_create(). The this pointer is captured and passed into the private input data argument, which is forwarded to the thread.
void* posixThread::thread_func()
{...}
[...]
// Our interfaces demand a void(*)(void*), so we adapt to posix's requirement
// and simply skip out on the return to the caller's perspective
r = pthread_create(&handle_, &attributes,
 reinterpret_cast<void* (*)(void*)>(
    embutil::bounce<posixThread, decltype(&posixThread::thread_func),
 &posixThread::thread_func>), *     reinterpret_cast<void*>(this));
The use case above is too verbose, so we recommend the BOUNCE() macro instead:
BOUNCE(posixThread, thread_func);
Template Parameters
TClass The type of class with the member function to be used as a callback.
Method The type of the member function to use as a callback.
m The function pointer corresponding to the class's member function.
Params Variadic template list of function parameters to forward to the member function.
Parameters
priv The private data pointer, which must always be passed the class's this pointer so bounce can resolve to the correct instance.
params Variadic list of parameters to forward to the member function.
Returns
the value returned by the member function.