Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_catanf.c File Reference
s_catanf.c File Reference
#include <openlibm_complex.h>
#include <openlibm_math.h>
Macros
#define MAXNUMF 1.0e38F
Functions
static float _redupif (float xx)
float complex catanf (float complex z)
Variables
static const double DP1 = 3.140625
static const double DP2 = 9.67502593994140625E-4
static const double DP3 = 1.509957990978376432E-7
Macro Definition Documentation
MAXNUMF
#define MAXNUMF 1.0e38F
Function Documentation
_redupif()
static float _redupif (float xx) static
References DP1, DP2, DP3, and t.
Referenced by catanf().
catanf()
float complex catanf (float complex z)
References _redupif(), a, atan2f(), cimagf(), complex, crealf(), I, logf(), MAXNUMF, t, w, and z.
Referenced by catanhf().
Variable Documentation
DP1
const double DP1 = 3.140625 static
Referenced by _redupif().
DP2
const double DP2 = 9.67502593994140625E-4 static
Referenced by _redupif().
DP3
const double DP3 = 1.509957990978376432E-7 static
Referenced by _redupif().