Embedded Artistry lic: src/string/strncpy.c File Reference
strncpy.c File Reference
#include <string.h>
Functions
char * strncpy (char *__restrict dst, const char *__restrict src, size_t maxlen)
Function Documentation
strncpy()
char* strncpy (char *__restrict dst, const char *__restrict src, size_t maxlen)
Definition at line 26 of file strncpy.c.
References memcpy(), memset(), and strnlen().
 {
     const size_t srclen = strnlen(src, maxlen);
     if(srclen < maxlen)
     {
         //  The stpncpy() and strncpy() functions copy at most maxlen
         //  characters from src into dst.
         memcpy(dst, src, srclen);
         //  If src is less than maxlen characters long, the remainder
         //  of dst is filled with '\0' characters.
         memset(dst + srclen, 0, maxlen - srclen);
     }
     else
     {
         //  Otherwise, dst is not terminated.
         memcpy(dst, src, maxlen);
     }
     //  The strcpy() and strncpy() functions return dst.
     return dst;
 }