Embedded Artistry Framework: src/stdlibs/libc/src/gdtoa/src/strtod.c File Reference
strtod.c File Reference
#include "gdtoaimp.h"
#include <float.h>
#include <math.h>
#include <stdint.h>
#include <fenv.h>
Macros
#define Rounding Flt_Rounds
#define fpi1 fpi
Functions
double strtod (CONST char *s00, char **se)
Macro Definition Documentation
fpi1
#define fpi1 fpi
Rounding
#define Rounding Flt_Rounds
Function Documentation
strtod()
double strtod (CONST char * s00, char ** se)
References Balloc(), Bcopy, Bfree(), Bias, Big0, Big1, bigtens, Bndry_mask, Bndry_mask1, cmp(), CONST, copybits(), d2b(), DBL_DIG, DBL_EPSILON, DBL_MAX_10_EXP, DBL_MAX_EXP, lconv::decimal_point, diff(), dval, ERANGE, errno, exp(), Exp_1, Exp_mask, Exp_msk1, Exp_shift, fabs(), FE_DOWNWARD, FE_TOWARDZERO, FE_UPWARD, fegetround(), FLT_RADIX, Flt_Rounds, fpi1, Frac_mask, gethex(), hexnan(), Honor_FLT_ROUNDS, i2b(), IBM, k, localeconv(), Log2P, Long, LSB, lshift(), match, mult(), FPI::nbits, NULL, P, pow5mult(), ratio(), rounded_product, rounded_quotient, Rounding, s, s0, s1, s2b(), SI, STRTOG_NaNbits, STRTOG_NoNumber, STRTOG_Retmask, STRTOG_Zero, Ten_pmax, tens, Tiny0, Tiny1, tinytens, ulp(), ULtod(), word0, word1, and z.
Referenced by strtod_test().