Embedded Artistry Framework: src/processors/arm/nordic/include/nordic_utils.hpp File Reference
nordic_utils.hpp File Reference
Functions
static bool is_in_nordic_ram (void const *ptr) noexcept
template<typename TPeripheralType >
static uint8_t get_peripheral_id (TPeripheralType *base_addr) noexcept
Function Documentation
get_peripheral_id()
template<typename TPeripheralType > static uint8_t get_peripheral_id (TPeripheralType * base_addr) inline static noexcept
Referenced by NordicNVIC::clear(), NordicNVIC::disable(), NordicNVIC::enable(), NordicNVIC::enabled(), NordicNVIC::handler(), NordicNVIC::pending(), NordicNVIC::priority(), and NordicNVIC::trigger().
is_in_nordic_ram()
static bool is_in_nordic_ram (void const * ptr) inline static noexcept
References u.
Referenced by set_rx_buffer_(), and set_tx_buffer_().