Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_atan2l.c File Reference
e_atan2l.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "invtrig.h"
#include "math_private.h"
Functions
OLM_DLLEXPORT long double atan2l (long double y, long double x)
Variables
static volatile long double tiny = 1.0e-300
static const long double zero = 0.0
static const long double pi = 3.14159265358979323846264338327950280e+00L
Function Documentation
atan2l()
OLM_DLLEXPORT long double atan2l (long double y, long double x)
References atanl(), BIAS, IEEEl2bits::bits, IEEEl2bits::e, fabsl(), k, LDBL_MANT_DIG, LDBL_MAX_EXP, LDBL_NBIT, pi, pi_lo, pio2_hi, pio2_lo, tiny, IEEEl2bits::xbits, z, and zero.
Referenced by cargl(), catanl(), and clogl().
Variable Documentation
pi
const long double pi = 3.14159265358979323846264338327950280e+00L static
Referenced by atan2l().
tiny
volatile long double tiny = 1.0e-300 static
Referenced by atan2l().
zero
const long double zero = 0.0 static
Referenced by atan2l().