Embedded Artistry Framework: src/stdlibs/libc/test/stdlib/calloc.c File Reference
calloc.c File Reference
#include "stdlib_tests.h"
#include <stdlib.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Macros
#define CALLOC_TEST_SIZE 1024
Functions
static void calloc_test (void **state)
int calloc_tests (void)
Macro Definition Documentation
CALLOC_TEST_SIZE
#define CALLOC_TEST_SIZE 1024
Function Documentation
calloc_test()
static void calloc_test (void ** state) static
References calloc(), CALLOC_TEST_SIZE, free(), and p.
Referenced by calloc_tests().
calloc_tests()
int calloc_tests (void)
References calloc_test(), calloc_tests(), and NULL.
Referenced by calloc_tests(), and stdlib_tests().