Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_scalbln.c File Reference
s_scalbln.c File Reference
#include "cdefs-compat.h"
#include <limits.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double scalbln (double x, long n)
OLM_DLLEXPORT float scalblnf (float x, long n)
OLM_DLLEXPORT long double scalblnl (long double x, long n)
Function Documentation
scalbln()
OLM_DLLEXPORT double scalbln (double x, long n)
References INT_MAX, INT_MIN, n, and scalbn().
Referenced by scalbln_test().
scalblnf()
OLM_DLLEXPORT float scalblnf (float x, long n)
References INT_MAX, INT_MIN, n, and scalbnf().
scalblnl()
OLM_DLLEXPORT long double scalblnl (long double x, long n)
References INT_MAX, INT_MIN, n, and scalbnl().