Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_carg.c File Reference
s_carg.c File Reference
#include "cdefs-compat.h"
#include <openlibm_complex.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double carg (double complex z)
Function Documentation
carg()
OLM_DLLEXPORT double carg (double complex z)
References atan2(), cimag(), creal(), and z.
Referenced by cpow().