Embedded Artistry Framework: src/stdlibs/libc/test/string/strndup.c File Reference
strndup.c File Reference
#include "string_tests.h"
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Functions
static void strndup_test (void **state)
int strndup_tests (void)
Function Documentation
strndup_test()
static void strndup_test (void ** state) static
References free(), NULL, SIZE_MAX, strlen(), strncmp(), and strndup().
Referenced by strndup_tests().
strndup_tests()
int strndup_tests (void)
References NULL, and strndup_test().
Referenced by string_tests().