Embedded Artistry Framework: src/stdlibs/libc/openlibm/include/openlibm_math.h File Reference
openlibm_math.h File Reference
Classes
union __infinity_un
union __nan_un
Macros
#define OPENLIBM_MATH_H
#define OLM_LONG_DOUBLE
#define __pure2
#define OLM_DLLEXPORT __attribute__ ((visibility("default")))
#define __MATH_BUILTIN_CONSTANTS
#define __MATH_BUILTIN_RELOPS
#define __ISO_C_VISIBLE 1999
#define HUGE_VAL __builtin_huge_val()
#define FP_ILOGB0 (-INT_MAX)
#define FP_ILOGBNAN INT_MAX
#define HUGE_VALF __builtin_huge_valf()
#define HUGE_VALL __builtin_huge_vall()
#define INFINITY __builtin_inff()
#define NAN __builtin_nanf("")
#define MATH_ERRNO 1
#define MATH_ERREXCEPT 2
#define math_errhandling MATH_ERREXCEPT
#define FP_FAST_FMAF 1
#define FP_INFINITE 0x01
#define FP_NAN 0x02
#define FP_NORMAL 0x04
#define FP_SUBNORMAL 0x08
#define FP_ZERO 0x10
#define fpclassify(x)
#define isfinite(x)
#define isinf(x)
#define isnan(x)
#define isnormal(x)
#define isgreater(x, y) __builtin_isgreater((x), (y))
#define isgreaterequal(x, y) __builtin_isgreaterequal((x), (y))
#define isless(x, y) __builtin_isless((x), (y))
#define islessequal(x, y) __builtin_islessequal((x), (y))
#define islessgreater(x, y) __builtin_islessgreater((x), (y))
#define isunordered(x, y) __builtin_isunordered((x), (y))
#define signbit(x)
Functions
int isopenlibm (void)
OLM_DLLEXPORT int __fpclassifyd (double) __pure2
OLM_DLLEXPORT int __fpclassifyf (float) __pure2
OLM_DLLEXPORT int __fpclassifyl (long double) __pure2
OLM_DLLEXPORT int __isfinitef (float) __pure2
OLM_DLLEXPORT int __isfinite (double) __pure2
OLM_DLLEXPORT int __isfinitel (long double) __pure2
OLM_DLLEXPORT int __isinff (float) __pure2
OLM_DLLEXPORT int __isinfl (long double) __pure2
OLM_DLLEXPORT int __isnanf (float) __pure2
OLM_DLLEXPORT int __isnanl (long double) __pure2
OLM_DLLEXPORT int __isnormalf (float) __pure2
OLM_DLLEXPORT int __isnormal (double) __pure2
OLM_DLLEXPORT int __isnormall (long double) __pure2
OLM_DLLEXPORT int __signbit (double) __pure2
OLM_DLLEXPORT int __signbitf (float) __pure2
OLM_DLLEXPORT int __signbitl (long double) __pure2
OLM_DLLEXPORT double acos (double)
OLM_DLLEXPORT double asin (double)
OLM_DLLEXPORT double atan (double)
OLM_DLLEXPORT double atan2 (double, double)
OLM_DLLEXPORT double cos (double)
OLM_DLLEXPORT double sin (double)
OLM_DLLEXPORT double tan (double)
OLM_DLLEXPORT double cosh (double)
OLM_DLLEXPORT double sinh (double)
OLM_DLLEXPORT double tanh (double)
OLM_DLLEXPORT double exp (double)
OLM_DLLEXPORT double frexp (double, int *)
OLM_DLLEXPORT double ldexp (double, int)
OLM_DLLEXPORT double log (double)
OLM_DLLEXPORT double log10 (double)
OLM_DLLEXPORT double modf (double, double *)
OLM_DLLEXPORT double pow (double, double)
OLM_DLLEXPORT double sqrt (double)
OLM_DLLEXPORT double ceil (double)
OLM_DLLEXPORT double fabs (double) __pure2
OLM_DLLEXPORT double floor (double)
OLM_DLLEXPORT double fmod (double, double)
OLM_DLLEXPORT double acosh (double)
OLM_DLLEXPORT double asinh (double)
OLM_DLLEXPORT double atanh (double)
OLM_DLLEXPORT double cbrt (double)
OLM_DLLEXPORT double erf (double)
OLM_DLLEXPORT double erfc (double)
OLM_DLLEXPORT double exp2 (double)
OLM_DLLEXPORT double expm1 (double)
OLM_DLLEXPORT double fma (double, double, double)
OLM_DLLEXPORT double hypot (double, double)
OLM_DLLEXPORT int ilogb (double) __pure2
OLM_DLLEXPORT int() isinf (double) __pure2
OLM_DLLEXPORT int() isnan (double) __pure2
OLM_DLLEXPORT double lgamma (double)
OLM_DLLEXPORT long long llrint (double)
OLM_DLLEXPORT long long llround (double)
OLM_DLLEXPORT double log1p (double)
OLM_DLLEXPORT double log2 (double)
OLM_DLLEXPORT double logb (double)
OLM_DLLEXPORT long lrint (double)
OLM_DLLEXPORT long lround (double)
OLM_DLLEXPORT double nan (const char *) __pure2
OLM_DLLEXPORT double nextafter (double, double)
OLM_DLLEXPORT double remainder (double, double)
OLM_DLLEXPORT double remquo (double, double, int *)
OLM_DLLEXPORT double rint (double)
OLM_DLLEXPORT double copysign (double, double) __pure2
OLM_DLLEXPORT double fdim (double, double)
OLM_DLLEXPORT double fmax (double, double) __pure2
OLM_DLLEXPORT double fmin (double, double) __pure2
OLM_DLLEXPORT double nearbyint (double)
OLM_DLLEXPORT double round (double)
OLM_DLLEXPORT double scalbln (double, long)
OLM_DLLEXPORT double scalbn (double, int)
OLM_DLLEXPORT double tgamma (double)
OLM_DLLEXPORT double trunc (double)
OLM_DLLEXPORT float acosf (float)
OLM_DLLEXPORT float asinf (float)
OLM_DLLEXPORT float atanf (float)
OLM_DLLEXPORT float atan2f (float, float)
OLM_DLLEXPORT float cosf (float)
OLM_DLLEXPORT float sinf (float)
OLM_DLLEXPORT float tanf (float)
OLM_DLLEXPORT float coshf (float)
OLM_DLLEXPORT float sinhf (float)
OLM_DLLEXPORT float tanhf (float)
OLM_DLLEXPORT float exp2f (float)
OLM_DLLEXPORT float expf (float)
OLM_DLLEXPORT float expm1f (float)
OLM_DLLEXPORT float frexpf (float, int *)
OLM_DLLEXPORT int ilogbf (float) __pure2
OLM_DLLEXPORT float ldexpf (float, int)
OLM_DLLEXPORT float log10f (float)
OLM_DLLEXPORT float log1pf (float)
OLM_DLLEXPORT float log2f (float)
OLM_DLLEXPORT float logf (float)
OLM_DLLEXPORT float modff (float, float *)
OLM_DLLEXPORT float powf (float, float)
OLM_DLLEXPORT float sqrtf (float)
OLM_DLLEXPORT float ceilf (float)
OLM_DLLEXPORT float fabsf (float) __pure2
OLM_DLLEXPORT float floorf (float)
OLM_DLLEXPORT float fmodf (float, float)
OLM_DLLEXPORT float roundf (float)
OLM_DLLEXPORT float erff (float)
OLM_DLLEXPORT float erfcf (float)
OLM_DLLEXPORT float hypotf (float, float)
OLM_DLLEXPORT float lgammaf (float)
OLM_DLLEXPORT float tgammaf (float)
OLM_DLLEXPORT float acoshf (float)
OLM_DLLEXPORT float asinhf (float)
OLM_DLLEXPORT float atanhf (float)
OLM_DLLEXPORT float cbrtf (float)
OLM_DLLEXPORT float logbf (float)
OLM_DLLEXPORT float copysignf (float, float) __pure2
OLM_DLLEXPORT long long llrintf (float)
OLM_DLLEXPORT long long llroundf (float)
OLM_DLLEXPORT long lrintf (float)
OLM_DLLEXPORT long lroundf (float)
OLM_DLLEXPORT float nanf (const char *) __pure2
OLM_DLLEXPORT float nearbyintf (float)
OLM_DLLEXPORT float nextafterf (float, float)
OLM_DLLEXPORT float remainderf (float, float)
OLM_DLLEXPORT float remquof (float, float, int *)
OLM_DLLEXPORT float rintf (float)
OLM_DLLEXPORT float scalblnf (float, long)
OLM_DLLEXPORT float scalbnf (float, int)
OLM_DLLEXPORT float truncf (float)
OLM_DLLEXPORT float fdimf (float, float)
OLM_DLLEXPORT float fmaf (float, float, float)
OLM_DLLEXPORT float fmaxf (float, float) __pure2
OLM_DLLEXPORT float fminf (float, float) __pure2
OLM_DLLEXPORT long double acoshl (long double)
OLM_DLLEXPORT long double acosl (long double)
OLM_DLLEXPORT long double asinhl (long double)
OLM_DLLEXPORT long double asinl (long double)
OLM_DLLEXPORT long double atan2l (long double, long double)
OLM_DLLEXPORT long double atanhl (long double)
OLM_DLLEXPORT long double atanl (long double)
OLM_DLLEXPORT long double cbrtl (long double)
OLM_DLLEXPORT long double ceill (long double)
OLM_DLLEXPORT long double copysignl (long double, long double) __pure2
OLM_DLLEXPORT long double coshl (long double)
OLM_DLLEXPORT long double cosl (long double)
OLM_DLLEXPORT long double erfcl (long double)
OLM_DLLEXPORT long double erfl (long double)
OLM_DLLEXPORT long double exp2l (long double)
OLM_DLLEXPORT long double expl (long double)
OLM_DLLEXPORT long double expm1l (long double)
OLM_DLLEXPORT long double fabsl (long double) __pure2
OLM_DLLEXPORT long double fdiml (long double, long double)
OLM_DLLEXPORT long double floorl (long double)
OLM_DLLEXPORT long double fmal (long double, long double, long double)
OLM_DLLEXPORT long double fmaxl (long double, long double) __pure2
OLM_DLLEXPORT long double fminl (long double, long double) __pure2
OLM_DLLEXPORT long double fmodl (long double, long double)
OLM_DLLEXPORT long double frexpl (long double value, int *)
OLM_DLLEXPORT long double hypotl (long double, long double)
OLM_DLLEXPORT int ilogbl (long double) __pure2
OLM_DLLEXPORT long double ldexpl (long double, int)
OLM_DLLEXPORT long double lgammal (long double)
OLM_DLLEXPORT long long llrintl (long double)
OLM_DLLEXPORT long long llroundl (long double)
OLM_DLLEXPORT long double log10l (long double)
OLM_DLLEXPORT long double log1pl (long double)
OLM_DLLEXPORT long double log2l (long double)
OLM_DLLEXPORT long double logbl (long double)
OLM_DLLEXPORT long double logl (long double)
OLM_DLLEXPORT long lrintl (long double)
OLM_DLLEXPORT long lroundl (long double)
OLM_DLLEXPORT long double modfl (long double, long double *)
OLM_DLLEXPORT long double nanl (const char *) __pure2
OLM_DLLEXPORT long double nearbyintl (long double)
OLM_DLLEXPORT long double nextafterl (long double, long double)
OLM_DLLEXPORT double nexttoward (double, long double)
OLM_DLLEXPORT float nexttowardf (float, long double)
OLM_DLLEXPORT long double nexttowardl (long double, long double)
OLM_DLLEXPORT long double powl (long double, long double)
OLM_DLLEXPORT long double remainderl (long double, long double)
OLM_DLLEXPORT long double remquol (long double, long double, int *)
OLM_DLLEXPORT long double rintl (long double)
OLM_DLLEXPORT long double roundl (long double)
OLM_DLLEXPORT long double scalblnl (long double, long)
OLM_DLLEXPORT long double scalbnl (long double, int)
OLM_DLLEXPORT long double sinhl (long double)
OLM_DLLEXPORT long double sinl (long double)
OLM_DLLEXPORT long double sqrtl (long double)
OLM_DLLEXPORT long double tanhl (long double)
OLM_DLLEXPORT long double tanl (long double)
OLM_DLLEXPORT long double tgammal (long double)
OLM_DLLEXPORT long double truncl (long double)
Variables
const union __infinity_un __infinity
const union __nan_un __nan
Class Documentation
__infinity_un
union __infinity_un
Class Members
unsigned char __uc[8]
double __ud
__nan_un
union __nan_un
Class Members
unsigned char __uc[sizeof(float)]
float __uf
Macro Definition Documentation
__ISO_C_VISIBLE
#define __ISO_C_VISIBLE 1999
__MATH_BUILTIN_CONSTANTS
#define __MATH_BUILTIN_CONSTANTS
__MATH_BUILTIN_RELOPS
#define __MATH_BUILTIN_RELOPS
__pure2
#define __pure2
FP_FAST_FMAF
#define FP_FAST_FMAF 1
FP_ILOGB0
#define FP_ILOGB0 (-INT_MAX)
FP_ILOGBNAN
#define FP_ILOGBNAN INT_MAX
FP_INFINITE
#define FP_INFINITE 0x01
FP_NAN
#define FP_NAN 0x02
FP_NORMAL
#define FP_NORMAL 0x04
FP_SUBNORMAL
#define FP_SUBNORMAL 0x08
FP_ZERO
#define FP_ZERO 0x10
fpclassify
#define fpclassify (x)
Value:
((sizeof (x) == sizeof (float)) ? __fpclassifyf(x) \
    : (sizeof (x) == sizeof (double)) ? __fpclassifyd(x) \
    : __fpclassifyl(x))
HUGE_VAL
#define HUGE_VAL __builtin_huge_val()
HUGE_VALF
#define HUGE_VALF __builtin_huge_valf()
HUGE_VALL
#define HUGE_VALL __builtin_huge_vall()
INFINITY
#define INFINITY __builtin_inff()
isfinite
#define isfinite (x)
Value:
((sizeof (x) == sizeof (float)) ? __isfinitef(x)    \
    : (sizeof (x) == sizeof (double)) ? __isfinite(x)   \
    : __isfinitel(x))
isgreater
#define isgreater (x, y) __builtin_isgreater((x), (y))
isgreaterequal
#define isgreaterequal (x, y) __builtin_isgreaterequal((x), (y))
isinf
#define isinf (x)
Value:
((sizeof (x) == sizeof (float)) ? __isinff(x)   \
    : (sizeof (x) == sizeof (double)) ? isinf(x)    \
    : __isinfl(x))
isless
#define isless (x, y) __builtin_isless((x), (y))
islessequal
#define islessequal (x, y) __builtin_islessequal((x), (y))
islessgreater
#define islessgreater (x, y) __builtin_islessgreater((x), (y))
isnan
#define isnan (x)
Value:
((sizeof (x) == sizeof (float)) ? __isnanf(x)   \
    : (sizeof (x) == sizeof (double)) ? isnan(x)    \
    : __isnanl(x))
isnormal
#define isnormal (x)
Value:
((sizeof (x) == sizeof (float)) ? __isnormalf(x)    \
    : (sizeof (x) == sizeof (double)) ? __isnormal(x)   \
    : __isnormall(x))
isunordered
#define isunordered (x, y) __builtin_isunordered((x), (y))
MATH_ERREXCEPT
#define MATH_ERREXCEPT 2
math_errhandling
#define math_errhandling MATH_ERREXCEPT
MATH_ERRNO
#define MATH_ERRNO 1
NAN
#define NAN __builtin_nanf("")
OLM_DLLEXPORT
#define OLM_DLLEXPORT __attribute__ ((visibility("default")))
OLM_LONG_DOUBLE
#define OLM_LONG_DOUBLE
OPENLIBM_MATH_H
#define OPENLIBM_MATH_H
signbit
#define signbit (x)
Value:
((sizeof (x) == sizeof (float)) ? __signbitf(x) \
    : (sizeof (x) == sizeof (double)) ? __signbit(x)    \
    : __signbitl(x))
Function Documentation
__fpclassifyd()
OLM_DLLEXPORT int __fpclassifyd (double)
References IEEEd2bits::d, FP_INFINITE, FP_NAN, FP_NORMAL, FP_SUBNORMAL, FP_ZERO, and u.
__fpclassifyf()
OLM_DLLEXPORT int __fpclassifyf (float)
References IEEEf2bits::f, FP_INFINITE, FP_NAN, FP_NORMAL, FP_SUBNORMAL, FP_ZERO, and u.
__fpclassifyl()
OLM_DLLEXPORT int __fpclassifyl (long double)
__isfinite()
OLM_DLLEXPORT int __isfinite (double)
References IEEEd2bits::d, and u.
__isfinitef()
OLM_DLLEXPORT int __isfinitef (float)
References IEEEf2bits::f, and u.
__isfinitel()
OLM_DLLEXPORT int __isfinitel (long double)
__isinff()
OLM_DLLEXPORT int __isinff (float)
References IEEEf2bits::f, and u.
__isinfl()
OLM_DLLEXPORT int __isinfl (long double)
__isnanf()
OLM_DLLEXPORT int __isnanf (float)
References IEEEf2bits::f, and u.
__isnanl()
OLM_DLLEXPORT int __isnanl (long double)
__isnormal()
OLM_DLLEXPORT int __isnormal (double)
References IEEEd2bits::d, and u.
__isnormalf()
OLM_DLLEXPORT int __isnormalf (float)
References IEEEf2bits::f, and u.
__isnormall()
OLM_DLLEXPORT int __isnormall (long double)
__signbit()
OLM_DLLEXPORT int __signbit (double)
References IEEEd2bits::d, and u.
__signbitf()
OLM_DLLEXPORT int __signbitf (float)
References IEEEf2bits::f, and u.
__signbitl()
OLM_DLLEXPORT int __signbitl (long double)
acos()
OLM_DLLEXPORT double acos (double)
Referenced by acos_test(), and main().
acosf()
OLM_DLLEXPORT float acosf (float)
acosh()
OLM_DLLEXPORT double acosh (double)
Referenced by acosh_test().
acoshf()
OLM_DLLEXPORT float acoshf (float)
acoshl()
OLM_DLLEXPORT long double acoshl (long double)
References GET_LDOUBLE_WORDS, GET_LDOUBLE_WORDS64, ln2, log1pl(), logl(), one, sqrtl(), and t.
acosl()
OLM_DLLEXPORT long double acosl (long double)
References ACOS_CONST, BIAS, LDBL_NBIT, one, p, P, pi, pio2_hi, pio2_lo, Q, r, s, sqrtl(), u, w, and z.
asin()
OLM_DLLEXPORT double asin (double)
Referenced by asin_test(), casin(), and main().
asinf()
OLM_DLLEXPORT float asinf (float)
Referenced by casinf().
asinh()
OLM_DLLEXPORT double asinh (double)
References __ieee754_log(), __ieee754_sqrt(), fabs(), GET_HIGH_WORD, huge, ln2, log1p(), one, t, and w.
Referenced by asinh_test().
asinhf()
OLM_DLLEXPORT float asinhf (float)
References __ieee754_logf(), __ieee754_sqrtf(), fabsf(), GET_FLOAT_WORD, huge, ln2, log1pf(), one, t, and w.
asinhl()
OLM_DLLEXPORT long double asinhl (long double)
References fabsl(), GET_LDOUBLE_EXP, huge, ln2, log1pl(), logl(), one, sqrtl(), t, u, and w.
asinl()
OLM_DLLEXPORT long double asinl (long double)
References ASIN_LINEAR, BIAS, fabsl(), huge, LDBL_NBIT, one, p, P, pio2_hi, pio2_lo, pio4_hi, Q, r, s, sqrtl(), t, THRESH, u, and w.
Referenced by casinl().
atan()
OLM_DLLEXPORT double atan (double)
References aT, atanhi, atanlo, fabs(), GET_HIGH_WORD, GET_LOW_WORD, huge, low, one, s1, s2, w, and z.
Referenced by __ieee754_atan2(), atan_test(), and main().
atan2()
OLM_DLLEXPORT double atan2 (double , double)
Referenced by atan2_test(), carg(), catan(), clog(), and main().
atan2f()
OLM_DLLEXPORT float atan2f (float , float)
Referenced by cargf(), catanf(), and clogf().
atan2l()
OLM_DLLEXPORT long double atan2l (long double , long double)
References atanl(), BIAS, IEEEl2bits::bits, IEEEl2bits::e, fabsl(), k, LDBL_MANT_DIG, LDBL_MAX_EXP, LDBL_NBIT, pi, pi_lo, pio2_hi, pio2_lo, tiny, IEEEl2bits::xbits, z, and zero.
Referenced by cargl(), catanl(), and clogl().
atanf()
OLM_DLLEXPORT float atanf (float)
References aT, atanhi, atanlo, fabsf(), GET_FLOAT_WORD, huge, one, s1, s2, w, and z.
Referenced by __ieee754_atan2f().
atanh()
OLM_DLLEXPORT double atanh (double)
Referenced by atanh_test().
atanhf()
OLM_DLLEXPORT float atanhf (float)
atanhl()
OLM_DLLEXPORT long double atanhl (long double)
References GET_LDOUBLE_WORDS, huge, log1pl(), one, SET_LDOUBLE_EXP, t, u, and zero.
atanl()
OLM_DLLEXPORT long double atanl (long double)
References ATAN_CONST, ATAN_LINEAR, atanhi, atanlo, BIAS, fabsl(), huge, LDBL_MAX_EXP, LDBL_NBIT, MANH_SIZE, one, s1, s2, T_even(), T_odd(), u, w, and z.
Referenced by atan2l().
cbrt()
OLM_DLLEXPORT double cbrt (double)
References B1, B2, IEEEl2bits::bits, EXTRACT_WORDS, GET_HIGH_WORD, high, INSERT_WORDS, low, P0, P1, P2, P3, P4, r, s, SET_HIGH_WORD, t, u, and w.
Referenced by cbrt_test().
cbrtf()
OLM_DLLEXPORT float cbrtf (float)
References B1, B2, GET_FLOAT_WORD, high, r, SET_FLOAT_WORD, T, and t.
cbrtl()
OLM_DLLEXPORT long double cbrtl (long double)
References B1, BIAS, IEEEl2bits::e, FP_PE, fpgetprec(), fpsetprec(), GET_FLOAT_WORD, k, LDBL_MAX_EXP, r, s, SET_FLOAT_WORD, t, u, vd, w, and IEEEl2bits::xbits.
ceil()
OLM_DLLEXPORT double ceil (double)
References EXTRACT_WORDS, huge, and INSERT_WORDS.
Referenced by ceil_test(), and neg_gam().
ceilf()
OLM_DLLEXPORT float ceilf (float)
References GET_FLOAT_WORD, huge, and SET_FLOAT_WORD.
ceill()
OLM_DLLEXPORT long double ceill (long double)
References IEEEl2bits::e, GET_LDOUBLE_WORDS, GET_LDOUBLE_WORDS64, huge, INC_MANH, LDBL_MANT_DIG, LDBL_MAX_EXP, MANH_SIZE, SET_LDOUBLE_WORDS, SET_LDOUBLE_WORDS64, and u.
copysign()
OLM_DLLEXPORT double copysign (double , double)
References GET_HIGH_WORD, and SET_HIGH_WORD.
Referenced by __exp__D(), ccosh(), copysign_test(), cproj(), csinh(), csqrt(), ctanh(), fma(), initialize(), scalbn(), and scalbnl().
copysignf()
OLM_DLLEXPORT float copysignf (float , float)
References GET_FLOAT_WORD, and SET_FLOAT_WORD.
Referenced by ccoshf(), cprojf(), csinhf(), csqrtf(), ctanhf(), and scalbnf().
copysignl()
OLM_DLLEXPORT long double copysignl (long double , long double)
References IEEEl2bits::bits, and IEEEl2bits::e.
Referenced by cprojl(), csqrtl(), fmal(), and scalbnl().
cos()
OLM_DLLEXPORT double cos (double)
References __ieee754_rem_pio2(), __kernel_cos(), __kernel_sin(), GET_HIGH_WORD, n, and z.
Referenced by __ieee754_j0(), __ieee754_j1(), __ieee754_jn(), __ieee754_y0(), __ieee754_y1(), __ieee754_yn(), __ldexp_cexp(), ccos(), ccosh(), cexp(), cos_test(), cpow(), csin(), csinh(), ctan(), ctanh(), main(), and neg_gam().
cosf()
OLM_DLLEXPORT float cosf (float)
References __ieee754_rem_pio2f(), __kernel_cosdf(), __kernel_sindf(), c1pio2, c2pio2, c3pio2, c4pio2, GET_FLOAT_WORD, and n.
Referenced by __ieee754_j0f(), __ieee754_j1f(), __ieee754_y0f(), __ieee754_y1f(), __ldexp_cexpf(), ccosf(), ccoshf(), cexpf(), cpowf(), csinf(), csinhf(), ctanf(), and ctanhf().
cosh()
OLM_DLLEXPORT double cosh (double)
Referenced by _cchsh(), cchsh(), ccosh(), cosh_test(), csinh(), and ctan().
coshf()
OLM_DLLEXPORT float coshf (float)
Referenced by _cchshf(), cchshf(), ccoshf(), csinhf(), and ctanf().
coshl()
OLM_DLLEXPORT long double coshl (long double)
References expl(), expm1l(), fabsl(), GET_LDOUBLE_WORDS, half, huge, one, ovf_thresh, t, u, and w.
Referenced by cchshl(), ccoshl(), csinhl(), ctanhl(), and ctanl().
cosl()
OLM_DLLEXPORT long double cosl (long double)
References __ieee754_rem_pio2l(), __kernel_cosl(), __kernel_sinl(), and z.
Referenced by ccoshl(), ccosl(), cexpl(), cpowl(), csinhl(), csinl(), ctanhl(), ctanl(), sin_pi(), and sincosl().
erf()
OLM_DLLEXPORT double erf (double)
References __ieee754_exp(), efx, efx8, erx, fabs(), GET_HIGH_WORD, one, P, pa0, pa1, pa2, pa3, pa4, pa5, pa6, pp0, pp1, pp2, pp3, pp4, Q, qa1, qa2, qa3, qa4, qa5, qa6, qq1, qq2, qq3, qq4, qq5, r, R, ra0, ra1, ra2, ra3, ra4, ra5, ra6, ra7, rb0, rb1, rb2, rb3, rb4, rb5, rb6, s, S, sa1, sa2, sa3, sa4, sa5, sa6, sa7, sa8, sb1, sb2, sb3, sb4, sb5, sb6, sb7, SET_LOW_WORD, tiny, and z.
Referenced by erf_test().
erfc()
OLM_DLLEXPORT double erfc (double)
References __ieee754_exp(), erx, fabs(), GET_HIGH_WORD, half, one, P, pa0, pa1, pa2, pa3, pa4, pa5, pa6, pp0, pp1, pp2, pp3, pp4, Q, qa1, qa2, qa3, qa4, qa5, qa6, qq1, qq2, qq3, qq4, qq5, r, R, ra0, ra1, ra2, ra3, ra4, ra5, ra6, ra7, rb0, rb1, rb2, rb3, rb4, rb5, rb6, s, S, sa1, sa2, sa3, sa4, sa5, sa6, sa7, sa8, sb1, sb2, sb3, sb4, sb5, sb6, sb7, SET_LOW_WORD, tiny, two, and z.
Referenced by erfc_test().
erfcf()
OLM_DLLEXPORT float erfcf (float)
References erx, expf(), F, fabsf(), GET_FLOAT_WORD, half, one, P, pa0, pa1, pa2, pa3, pp0, pp1, pp2, Q, qa1, qa2, qa3, qa4, qq1, qq2, qq3, r, R, ra0, ra1, ra2, ra3, rb0, rb1, rb2, rb3, rb4, s, S, sa1, sa2, sa3, sa4, sb1, sb2, sb3, sb4, SET_FLOAT_WORD, tiny, two, and z.
erfcl()
OLM_DLLEXPORT long double erfcl (long double)
References C13a, C13b, C14a, C14b, C15a, C15b, C16a, C16b, C17a, C17b, C18a, C18b, C19a, C19b, C20a, C20b, deval(), erfl(), erx, expl(), fabsl(), GET_LDOUBLE_WORDS, half, neval(), NRDr1, NRDr13, NRDr14, NRDr15, NRDr16, NRDr17, NRDr18, NRDr19, NRDr2, NRDr20, NRDr3, NRDr4, NRDr5, NRDr6, NRDr7, NRDr8, NRNr1, NRNr13, NRNr14, NRNr15, NRNr16, NRNr17, NRNr18, NRNr19, NRNr2, NRNr20, NRNr3, NRNr4, NRNr5, NRNr6, NRNr7, NRNr8, one, p, P, pa, pp, Q, qa, qq, r, R, ra, rb, rc, RDr1, RDr13, RDr14, RDr15, RDr16, RDr17, RDr18, RDr19, RDr2, RDr20, RDr3, RDr4, RDr5, RDr6, RDr7, RDr8, RNr1, RNr13, RNr14, RNr15, RNr16, RNr17, RNr18, RNr19, RNr2, RNr20, RNr3, RNr4, RNr5, RNr6, RNr7, RNr8, s, S, sa, sb, sc, SET_LDOUBLE_WORDS, tiny, two, u, and z.
Referenced by erfl().
erff()
OLM_DLLEXPORT float erff (float)
References efx, efx8, erx, expf(), F, fabsf(), GET_FLOAT_WORD, one, P, pa0, pa1, pa2, pa3, pp0, pp1, pp2, Q, qa1, qa2, qa3, qa4, qq1, qq2, qq3, r, R, ra0, ra1, ra2, ra3, rb0, rb1, rb2, rb3, rb4, s, S, sa1, sa2, sa3, sa4, sb1, sb2, sb3, sb4, SET_FLOAT_WORD, tiny, and z.
erfl()
OLM_DLLEXPORT long double erfl (long double)
References a, deval(), efx, efx8, erf_const, erfcl(), erx, expl(), fabsl(), GET_LDOUBLE_WORDS, neval(), NTD1, NTD2, NTN1, NTN2, one, P, pa, pp, Q, qa, qq, r, R, ra, rb, s, S, sa, sb, SET_LDOUBLE_WORDS, TD1, TD2, tiny, TN1, TN2, u, and z.
Referenced by erfcl().
exp()
OLM_DLLEXPORT double exp (double)
Referenced by __frexp_exp(), _cchsh(), cchsh(), ccosh(), cexp(), cpow(), csinh(), ctanh(), exp_test(), gethex(), main(), rvOK(), strtod(), strtodg(), strtodI(), strtof(), strtoId(), strtoIdd(), strtoIf(), strtoIg(), strtoIQ(), strtoIx(), strtoIxL(), strtopd(), strtopdd(), strtopf(), strtopQ(), strtopx(), strtopxL(), strtord(), strtordd(), strtorf(), strtorQ(), strtorx(), strtorxL(), ULtod(), ULtodd(), ULtof(), ULtoQ(), ULtox(), and ULtoxL().
exp2()
OLM_DLLEXPORT double exp2 (double)
References GET_HIGH_WORD, GET_LOW_WORD, huge, INSERT_WORDS, k, P1, P2, P3, P4, P5, r, redux, STRICT_ASSIGN, t, tbl, TBLBITS, TBLSIZE, twom1000, and z.
Referenced by _etoa(), exp2_test(), and exp2l().
exp2f()
OLM_DLLEXPORT float exp2f (float)
References exp2ft, GET_FLOAT_WORD, huge, INSERT_WORDS, k, P1, P2, P3, P4, redux, STRICT_ASSIGN, t, TBLBITS, TBLSIZE, twom100, u, and z.
exp2l()
OLM_DLLEXPORT long double exp2l (long double)
References BIAS, IEEEl2bits::e, eps, exp2(), EXPMASK, FP_PE, huge, k, LDBL_MAX_EXP, LDBL_MIN_EXP, P1, P10, P2, P3, P4, P5, P6, P7, P8, P9, r, redux, t, tbl, TBLBITS, TBLSIZE, twom10000, u, IEEEl2bits::xbits, and z.
expf()
OLM_DLLEXPORT float expf (float)
Referenced by __frexp_expf(), _cchshf(), cchshf(), ccoshf(), cexpf(), cpowf(), csinhf(), ctanhf(), erfcf(), and erff().
expl()
OLM_DLLEXPORT long double expl (long double)
References __polevll(), C1, C2, floorl(), huge, INFINITY, isnan, ldexpl(), LOG2EL, MAXLOGL, MINLOGL, n, P, Q, and twom10000.
Referenced by cchshl(), cexpl(), coshl(), cpowl(), erfcl(), erfl(), sinhl(), stirf(), and tgammal().
expm1()
OLM_DLLEXPORT double expm1 (double)
References IEEEl2bits::e, GET_HIGH_WORD, GET_LOW_WORD, huge, INSERT_WORDS, invln2, k, ln2_hi, ln2_lo, low, o_threshold, one, Q1, Q2, Q3, Q4, Q5, r1, SET_HIGH_WORD, STRICT_ASSIGN, t, and tiny.
Referenced by __ieee754_cosh(), __ieee754_sinh(), expm1_test(), and tanh().
expm1f()
OLM_DLLEXPORT float expm1f (float)
References IEEEl2bits::e, GET_FLOAT_WORD, huge, invln2, k, ln2_hi, ln2_lo, o_threshold, one, Q1, Q2, r1, SET_FLOAT_WORD, STRICT_ASSIGN, t, and tiny.
Referenced by __ieee754_coshf(), __ieee754_sinhf(), and tanhf().
expm1l()
OLM_DLLEXPORT long double expm1l (long double)
References big, C1, C2, floorl(), huge, k, ldexpl(), maxlog, MAXLOGL, minarg, P0, P1, P2, P3, P4, P5, P6, P7, Q0, Q1, Q2, Q3, Q4, Q5, Q6, Q7, and u.
Referenced by coshl(), sinhl(), and tanhl().
fabs()
OLM_DLLEXPORT double fabs (double)
References GET_HIGH_WORD, high, SET_HIGH_WORD, and u.
fabsf()
OLM_DLLEXPORT float fabsf (float)
References GET_FLOAT_WORD, SET_FLOAT_WORD, and u.
fabsl()
OLM_DLLEXPORT long double fabsl (long double)
References u.
Referenced by __kernel_tanl(), asinhl(), asinl(), atan2l(), atanl(), casinl(), cchshl(), coshl(), csqrtl(), ctanl(), ctansl(), erfcl(), erfl(), hypotl(), lgammal_r(), powl(), remquol(), sinhl(), tanhl(), and tgammal().
fdim()
OLM_DLLEXPORT double fdim (double , double)
Referenced by fdim_test().
fdimf()
OLM_DLLEXPORT float fdimf (float , float)
fdiml()
OLM_DLLEXPORT long double fdiml (long double , long double)
floor()
OLM_DLLEXPORT double floor (double)
References EXTRACT_WORDS, huge, and INSERT_WORDS.
Referenced by __kernel_rem_pio2(), floor_test(), round(), and sin_pi().
floorf()
OLM_DLLEXPORT float floorf (float)
References GET_FLOAT_WORD, huge, and SET_FLOAT_WORD.
Referenced by roundf(), and sin_pif().
floorl()
OLM_DLLEXPORT long double floorl (long double)
References IEEEl2bits::e, GET_LDOUBLE_WORDS, GET_LDOUBLE_WORDS64, huge, INC_MANH, LDBL_MANT_DIG, LDBL_MAX_EXP, MANH_SIZE, SET_LDOUBLE_WORDS, SET_LDOUBLE_WORDS64, and u.
Referenced by expl(), expm1l(), lgammal_r(), powl(), reducl(), roundl(), sin_pi(), and tgammal().
fma()
OLM_DLLEXPORT double fma (double , double , double)
References add_adjusted(), add_and_denormalize(), copysign(), DBL_MANT_DIG, DBL_MIN, dd_add(), dd_mul(), FE_DOWNWARD, FE_INEXACT, FE_TONEAREST, FE_TOWARDZERO, FE_UNDERFLOW, fegetround(), feraiseexcept(), fesetround(), frexp(), dd::hi, ilogb(), INFINITY, isfinite, isnormal, ldexp(), dd::lo, nextafter(), r, and z.
Referenced by fma_test().
fmaf()
OLM_DLLEXPORT float fmaf (float , float , float)
References EXTRACT_WORDS, FE_TONEAREST, FE_TOWARDZERO, fegetround(), fesetround(), SET_LOW_WORD, and z.
fmal()
OLM_DLLEXPORT long double fmal (long double , long double , long double)
References add_adjusted(), add_and_denormalize(), copysignl(), dd_add(), dd_mul(), FE_DOWNWARD, FE_INEXACT, FE_TONEAREST, FE_TOWARDZERO, FE_UNDERFLOW, fegetround(), feraiseexcept(), fesetround(), frexpl(), dd::hi, ilogbl(), INFINITY, isfinite, isnormal, LDBL_MANT_DIG, LDBL_MIN, ldexpl(), dd::lo, nextafterl(), r, and z.
fmax()
OLM_DLLEXPORT double fmax (double , double)
References IEEEd2bits::bits, and u.
Referenced by fmax_test().
fmaxf()
OLM_DLLEXPORT float fmaxf (float , float)
References IEEEf2bits::bits, and u.
fmaxl()
OLM_DLLEXPORT long double fmaxl (long double , long double)
References IEEEl2bits::bits, mask_nbit_l, and u.
fmin()
OLM_DLLEXPORT double fmin (double , double)
References IEEEd2bits::bits, and u.
Referenced by fmin_test().
fminf()
OLM_DLLEXPORT float fminf (float , float)
References IEEEf2bits::bits, and u.
fminl()
OLM_DLLEXPORT long double fminl (long double , long double)
References IEEEl2bits::bits, mask_nbit_l, and u.
fmod()
OLM_DLLEXPORT double fmod (double , double)
Referenced by fmod_test().
fmodf()
OLM_DLLEXPORT float fmodf (float , float)
fmodl()
OLM_DLLEXPORT long double fmodl (long double , long double)
References BIAS, IEEEl2bits::bits, IEEEl2bits::e, GET_LDOUBLE_WORDS64, HFRAC_BITS, LDBL_MAX_EXP, LDBL_MIN_EXP, LDBL_NBIT, MANL_SHIFT, n, one, p, SET_LDOUBLE_WORDS64, SET_NBIT, and Zero.
frexp()
OLM_DLLEXPORT double frexp (double , int *)
References EXTRACT_WORDS, GET_HIGH_WORD, SET_HIGH_WORD, and two54.
Referenced by fma(), and frexp_test().
frexpf()
OLM_DLLEXPORT float frexpf (float , int *)
References GET_FLOAT_WORD, SET_FLOAT_WORD, and two25.
frexpl()
OLM_DLLEXPORT long double frexpl (long double value, int *)
References u.
Referenced by fmal(), log10l(), log1pl(), log2l(), logl(), powil(), and powl().
hypot()
OLM_DLLEXPORT double hypot (double , double)
Referenced by cabs(), csqrt(), csqrtf(), hypot_test(), and main().
hypotf()
OLM_DLLEXPORT float hypotf (float , float)
Referenced by cabsf().
hypotl()
OLM_DLLEXPORT long double hypotl (long double , long double)
References a, b, IEEEl2bits::bits, DESW, IEEEl2bits::e, ESW, fabsl(), GET_HIGH_WORD, GET_LDBL_MAN, GET_LDOUBLE_EXP, GET_LDOUBLE_LSW64, GET_LDOUBLE_MSW, GET_LDOUBLE_MSW64, GET_LDOUBLE_WORDS, high, k, LDBL_NBIT, low, MANT_DIG, MAX_EXP, SET_HIGH_WORD, SET_LDOUBLE_EXP, SET_LDOUBLE_MSW64, SET_LDOUBLE_WORDS, sqrtl(), t1, t2, and w.
Referenced by cabsl(), and csqrtl().
ilogb()
OLM_DLLEXPORT int ilogb (double)
References EXTRACT_WORDS, FP_ILOGB0, FP_ILOGBNAN, and INT_MAX.
Referenced by check_float_internal(), fma(), and ilogb_test().
ilogbf()
OLM_DLLEXPORT int ilogbf (float)
References FP_ILOGB0, FP_ILOGBNAN, GET_FLOAT_WORD, and INT_MAX.
ilogbl()
OLM_DLLEXPORT int ilogbl (long double)
References b, FP_ILOGB0, FP_ILOGBNAN, INT_MAX, LDBL_MANH_SIZE, LDBL_MANL_SIZE, LDBL_MAX_EXP, LDBL_MIN_EXP, and u.
Referenced by fmal().
isinf()
OLM_DLLEXPORT int() isinf (double)
References IEEEd2bits::d, and u.
isnan()
OLM_DLLEXPORT int() isnan (double)
References IEEEd2bits::d, and u.
isopenlibm()
int isopenlibm (void)
ldexp()
OLM_DLLEXPORT double ldexp (double , int)
Referenced by add_and_denormalize(), check_float_internal(), fma(), and ldexp_test().
ldexpf()
OLM_DLLEXPORT float ldexpf (float , int)
ldexpl()
OLM_DLLEXPORT long double ldexpl (long double , int)
Referenced by expl(), expm1l(), fmal(), log10l(), log2l(), logl(), powl(), and reducl().
lgamma()
OLM_DLLEXPORT double lgamma (double)
Referenced by lgamma_test().
lgammaf()
OLM_DLLEXPORT float lgammaf (float)
lgammal()
OLM_DLLEXPORT long double lgammal (long double)
References lgammal_r(), and signgam.
Referenced by lgammal_r(), and tgammal().
llrint()
OLM_DLLEXPORT long long llrint (double)
Referenced by llrint_test(), and llround_test().
llrintf()
OLM_DLLEXPORT long long llrintf (float)
llrintl()
OLM_DLLEXPORT long long llrintl (long double)
llround()
OLM_DLLEXPORT long long llround (double)
Referenced by llround_test().
llroundf()
OLM_DLLEXPORT long long llroundf (float)
llroundl()
OLM_DLLEXPORT long long llroundl (long double)
log()
OLM_DLLEXPORT double log (double)
Referenced by catan(), clog(), cpow(), log_test(), and main().
log10()
OLM_DLLEXPORT double log10 (double)
Referenced by log10_test(), and main().
log10f()
OLM_DLLEXPORT float log10f (float)
log10l()
OLM_DLLEXPORT long double log10l (long double)
References __p1evll(), __polevll(), deval(), IEEEl2bits::e, frexpl(), GET_LDOUBLE_WORDS64, INFINITY, isnan, L102A, L102B, L10EA, L10EB, ldexpl(), neval(), P, Q, R, S, SQRTH, and z.
log1p()
OLM_DLLEXPORT double log1p (double)
References GET_HIGH_WORD, k, ln2_hi, ln2_lo, Lp1, Lp2, Lp3, Lp4, Lp5, Lp6, Lp7, R, s, SET_HIGH_WORD, STRICT_ASSIGN, two54, u, z, and zero.
Referenced by __ieee754_acosh(), __ieee754_atanh(), asinh(), and log1p_test().
log1pf()
OLM_DLLEXPORT float log1pf (float)
References GET_FLOAT_WORD, k, ln2_hi, ln2_lo, Lp1, Lp2, Lp3, Lp4, Lp5, Lp6, Lp7, R, s, SET_FLOAT_WORD, STRICT_ASSIGN, two25, u, z, and zero.
Referenced by __ieee754_acoshf(), __ieee754_atanhf(), and asinhf().
log1pl()
OLM_DLLEXPORT long double log1pl (long double)
References __p1evll(), __polevll(), C1, C2, IEEEl2bits::e, frexpl(), INFINITY, isnan, NAN, P, P0, P1, P10, P11, P12, P2, P3, P4, P5, P6, P7, P8, P9, Q, Q0, Q1, Q10, Q11, Q2, Q3, Q4, Q5, Q6, Q7, Q8, Q9, r, R, R0, R1, R2, R3, R4, R5, s, S, S0, S1, S2, S3, S4, S5, SQRTH, sqrth, u, z, and zero.
Referenced by acoshl(), asinhl(), and atanhl().
log2()
OLM_DLLEXPORT double log2 (double)
Referenced by log2_test().
log2f()
OLM_DLLEXPORT float log2f (float)
log2l()
OLM_DLLEXPORT long double log2l (long double)
References __p1evll(), __polevll(), deval(), IEEEl2bits::e, frexpl(), GET_LDOUBLE_WORDS64, INFINITY, isnan, ldexpl(), LOG2EA, NAN, neval(), P, Q, R, S, SQRTH, and z.
logb()
OLM_DLLEXPORT double logb (double)
References EXTRACT_WORDS, fabs(), GET_HIGH_WORD, and two54.
Referenced by logb_test().
logbf()
OLM_DLLEXPORT float logbf (float)
References fabsf(), GET_FLOAT_WORD, and two25.
logbl()
OLM_DLLEXPORT long double logbl (long double)
References b, LDBL_MANH_SIZE, LDBL_MANL_SIZE, LDBL_MAX_EXP, LDBL_MIN_EXP, and u.
logf()
OLM_DLLEXPORT float logf (float)
Referenced by catanf(), clogf(), and cpowf().
logl()
OLM_DLLEXPORT long double logl (long double)
References __p1evll(), __polevll(), C1, C2, IEEEl2bits::e, frexpl(), INFINITY, isnan, k, l10, l11, l12, l13, l14, l15, l3, l4, l5, l6, l7, l8, l9, ldexpl(), ln2a, ln2b, logtbl, NAN, P, Q, R, S, SQRTH, t, u, w, z, and ZERO.
Referenced by acoshl(), asinhl(), catanl(), clogl(), cpowl(), and lgammal_r().
lrint()
OLM_DLLEXPORT long lrint (double)
Referenced by lrint_test().
lrintf()
OLM_DLLEXPORT long lrintf (float)
lrintl()
OLM_DLLEXPORT long lrintl (long double)
lround()
OLM_DLLEXPORT long lround (double)
Referenced by lround_test().
lroundf()
OLM_DLLEXPORT long lroundf (float)
lroundl()
OLM_DLLEXPORT long lroundl (long double)
modf()
OLM_DLLEXPORT double modf (double , double *)
References EXTRACT_WORDS, GET_HIGH_WORD, high, INSERT_WORDS, and one.
Referenced by modf_test().
modff()
OLM_DLLEXPORT float modff (float , float *)
References GET_FLOAT_WORD, one, and SET_FLOAT_WORD.
modfl()
OLM_DLLEXPORT long double modfl (long double , long double *)
References IEEEl2bits::bits, IEEEl2bits::e, GET_LDOUBLE_WORDS, GET_LDOUBLE_WORDS64, GETFRAC, HIBITS, LDBL_MANT_DIG, LDBL_MAX_EXP, one, SET_LDOUBLE_WORDS, SET_LDOUBLE_WORDS64, and zero.
nan()
OLM_DLLEXPORT double nan (const char *)
References __scan_nan(), IEEEl2bits::bits, s, and u.
nanf()
OLM_DLLEXPORT float nanf (const char *)
References __scan_nan(), s, and u.
nanl()
OLM_DLLEXPORT long double nanl (const char *)
References __scan_nan(), IEEEl2bits::bits, s, and u.
nearbyint()
OLM_DLLEXPORT double nearbyint (double)
Referenced by nearbyint_test().
nearbyintf()
OLM_DLLEXPORT float nearbyintf (float)
nearbyintl()
OLM_DLLEXPORT long double nearbyintl (long double)
nextafter()
OLM_DLLEXPORT double nextafter (double , double)
References EXTRACT_WORDS, INSERT_WORDS, and t.
Referenced by fma(), and nextafter_test().
nextafterf()
OLM_DLLEXPORT float nextafterf (float , float)
References GET_FLOAT_WORD, SET_FLOAT_WORD, and t.
nextafterl()
OLM_DLLEXPORT long double nextafterl (long double , long double)
References IEEEl2bits::bits, IEEEl2bits::e, GET_LDOUBLE_WORDS, GET_LDOUBLE_WORDS64, LDBL_NBIT, mask_nbit_l, SET_LDOUBLE_WORDS, SET_LDOUBLE_WORDS64, t, and u.
Referenced by add_adjusted(), add_and_denormalize(), and fmal().
nexttoward()
OLM_DLLEXPORT double nexttoward (double , long double)
References IEEEl2bits::bits, IEEEl2bits::e, EXTRACT_WORDS, GET_LDOUBLE_WORDS, GET_LDOUBLE_WORDS64, INSERT_WORDS, LDBL_NBIT, t, and u.
nexttowardf()
OLM_DLLEXPORT float nexttowardf (float , long double)
References GET_FLOAT_WORD, GET_LDOUBLE_WORDS, GET_LDOUBLE_WORDS64, SET_FLOAT_WORD, and u.
nexttowardl()
OLM_DLLEXPORT long double nexttowardl (long double , long double)
pow()
OLM_DLLEXPORT double pow (double , double)
Referenced by cpow(), main(), and pow_test().
powf()
OLM_DLLEXPORT float powf (float , float)
Referenced by cpowf().
powl()
OLM_DLLEXPORT long double powl (long double , long double)
References __p1evll(), __polevll(), bp, cp, cp_h, cp_l, douba, doubb, dp_h, dp_l, IEEEl2bits::e, F, Fa, fabsl(), Fb, floorl(), frexpl(), G, Ga, Gb, H, Ha, Hb, huge, INFINITY, isfinite, isnan, k, LD, LDBL_MAX, ldexpl(), lg2, lg2_h, lg2_l, LN, LNXT, LOG2EA, MEXP, MNEXP, n, NXT, one, ovt, p, P, ieee_quad_shape_type::parts32, PD, PN, powil(), Q, r, R, reducl(), s, s2, scalbnl(), signbit, sqrtl(), t, t1, t2, tiny, two, two113, twom10000, u, ieee_quad_shape_type::value, w, ya, yb, z, and zero.
Referenced by cpowl(), and stirf().
remainder()
OLM_DLLEXPORT double remainder (double , double)
Referenced by remainder_test().
remainderf()
OLM_DLLEXPORT float remainderf (float , float)
remainderl()
OLM_DLLEXPORT long double remainderl (long double , long double)
References remquol().
remquo()
OLM_DLLEXPORT double remquo (double , double , int *)
References EXTRACT_WORDS, fabs(), GET_HIGH_WORD, INSERT_WORDS, n, SET_HIGH_WORD, and Zero.
Referenced by remquo_test().
remquof()
OLM_DLLEXPORT float remquof (float , float , int *)
References fabsf(), GET_FLOAT_WORD, n, SET_FLOAT_WORD, and Zero.
remquol()
OLM_DLLEXPORT long double remquol (long double , long double , int *)
References BIAS, IEEEl2bits::bits, IEEEl2bits::e, fabsl(), GET_LDOUBLE_EXP, GET_LDOUBLE_MSW64, GET_LDOUBLE_WORDS, GET_LDOUBLE_WORDS64, HFRAC_BITS, LDBL_MAX_EXP, LDBL_MIN, LDBL_MIN_EXP, LDBL_NBIT, MANL_SHIFT, n, p, SET_LDOUBLE_EXP, SET_LDOUBLE_MSW64, SET_LDOUBLE_WORDS, SET_LDOUBLE_WORDS64, SET_NBIT, and Zero.
Referenced by remainderl().
rint()
OLM_DLLEXPORT double rint (double)
References EXTRACT_WORDS, GET_HIGH_WORD, INSERT_WORDS, SET_HIGH_WORD, STRICT_ASSIGN, t, TWO52, and w.
Referenced by rint_test().
rintf()
OLM_DLLEXPORT float rintf (float)
References GET_FLOAT_WORD, SET_FLOAT_WORD, STRICT_ASSIGN, t, TWO23, and w.
rintl()
OLM_DLLEXPORT long double rintl (long double)
References BIAS, LDBL_MANT_DIG, LDBL_MAX_EXP, shift, u, and zero.
Referenced by tgammal().
round()
OLM_DLLEXPORT double round (double)
References floor(), GET_HIGH_WORD, and t.
Referenced by round_test().
roundf()
OLM_DLLEXPORT float roundf (float)
References floorf(), isfinite, and t.
roundl()
OLM_DLLEXPORT long double roundl (long double)
References floorl(), isfinite, and t.
scalbln()
OLM_DLLEXPORT double scalbln (double , long)
References INT_MAX, INT_MIN, n, and scalbn().
Referenced by scalbln_test().
scalblnf()
OLM_DLLEXPORT float scalblnf (float , long)
References INT_MAX, INT_MIN, n, and scalbnf().
scalblnl()
OLM_DLLEXPORT long double scalblnl (long double , long)
scalbn()
OLM_DLLEXPORT double scalbn (double , int)
References copysign(), EXTRACT_WORDS, GET_HIGH_WORD, huge, k, n, SET_HIGH_WORD, tiny, two54, and twom54.
Referenced by __exp__D(), __ieee754_pow(), __kernel_rem_pio2(), scalbln(), and scalbn_test().
scalbnf()
OLM_DLLEXPORT float scalbnf (float , int)
References copysignf(), GET_FLOAT_WORD, huge, k, n, SET_FLOAT_WORD, tiny, two25, and twom25.
Referenced by __ieee754_powf(), and scalblnf().
scalbnl()
OLM_DLLEXPORT long double scalbnl (long double , int)
References copysign(), copysignl(), huge, k, n, p, tiny, and u.
Referenced by powl().
sin()
OLM_DLLEXPORT double sin (double)
References __ieee754_rem_pio2(), __kernel_cos(), __kernel_sin(), GET_HIGH_WORD, n, and z.
Referenced by __ieee754_j0(), __ieee754_j1(), __ieee754_jn(), __ieee754_y0(), __ieee754_y1(), __ieee754_yn(), __ldexp_cexp(), ccos(), ccosh(), cexp(), cpow(), csin(), csinh(), ctan(), ctanh(), main(), neg_gam(), and sin_test().
sinf()
OLM_DLLEXPORT float sinf (float)
References __ieee754_rem_pio2f(), __kernel_cosdf(), __kernel_sindf(), GET_FLOAT_WORD, n, s1pio2, s2pio2, s3pio2, and s4pio2.
Referenced by __ieee754_j0f(), __ieee754_j1f(), __ieee754_y0f(), __ieee754_y1f(), __ldexp_cexpf(), ccosf(), ccoshf(), cexpf(), cpowf(), csinf(), csinhf(), ctanf(), and ctanhf().
sinh()
OLM_DLLEXPORT double sinh (double)
Referenced by _cchsh(), cchsh(), ccosh(), csinh(), ctan(), ctanh(), and sinh_test().
sinhf()
OLM_DLLEXPORT float sinhf (float)
Referenced by _cchshf(), cchshf(), ccoshf(), csinhf(), ctanf(), and ctanhf().
sinhl()
OLM_DLLEXPORT long double sinhl (long double)
References expl(), expm1l(), fabsl(), GET_LDOUBLE_WORDS, one, ovf_thresh, shuge, t, u, and w.
Referenced by cchshl(), ccoshl(), csinhl(), ctanhl(), and ctanl().
sinl()
OLM_DLLEXPORT long double sinl (long double)
References __ieee754_rem_pio2l(), __kernel_cosl(), __kernel_sinl(), s, and z.
Referenced by ccoshl(), ccosl(), cexpl(), cpowl(), csinhl(), csinl(), ctanhl(), ctanl(), lgammal_r(), sin_pi(), sincosl(), and tgammal().
sqrt()
OLM_DLLEXPORT double sqrt (double)
Referenced by __ieee754_acos(), __ieee754_acosh(), __ieee754_asin(), __ieee754_asinf(), __ieee754_hypot(), __ieee754_j0(), __ieee754_j1(), __ieee754_jn(), __ieee754_pow(), __ieee754_y0(), __ieee754_y1(), __ieee754_yn(), csqrt(), csqrtf(), ctanh(), sqrt_test(), and sqrtl().
sqrtf()
OLM_DLLEXPORT float sqrtf (float)
Referenced by __ieee754_acosf(), __ieee754_j0f(), __ieee754_j1f(), __ieee754_y0f(), __ieee754_y1f(), and ctanhf().
sqrtl()
OLM_DLLEXPORT long double sqrtl (long double)
References dec(), FE_INEXACT, FE_TONEAREST, FE_TOWARDZERO, FE_UPWARD, feclearexcept(), fegetround(), feholdexcept(), fesetenv(), fesetround(), fetestexcept(), feupdateenv(), inc(), k, LDBL_MAX_EXP, r, sqrt(), and u.
Referenced by acoshl(), acosl(), asinhl(), asinl(), csqrtl(), hypotl(), and powl().
tan()
OLM_DLLEXPORT double tan (double)
References __ieee754_rem_pio2(), __kernel_tan(), GET_HIGH_WORD, n, and z.
Referenced by ctanh(), main(), and tan_test().
tanf()
OLM_DLLEXPORT float tanf (float)
References __ieee754_rem_pio2f(), __kernel_tandf(), GET_FLOAT_WORD, n, t1pio2, t2pio2, t3pio2, and t4pio2.
Referenced by ctanhf().
tanh()
OLM_DLLEXPORT double tanh (double)
References expm1(), fabs(), GET_HIGH_WORD, huge, one, t, tiny, two, and z.
Referenced by tanh_test().
tanhf()
OLM_DLLEXPORT float tanhf (float)
References expm1f(), fabsf(), GET_FLOAT_WORD, huge, one, t, tiny, two, and z.
tanhl()
OLM_DLLEXPORT long double tanhl (long double)
References expm1l(), fabsl(), GET_LDOUBLE_WORDS, one, t, tiny, two, u, and z.
tanl()
OLM_DLLEXPORT long double tanl (long double)
References __ieee754_rem_pio2l(), __kernel_tanl(), s, and z.
tgamma()
OLM_DLLEXPORT double tgamma (double)
References __exp__D(), isfinite, isgreater, isgreaterequal, large_gam(), LEFT, neg_gam(), one, small_gam(), smaller_gam(), tiny, u, x0, and zero.
Referenced by neg_gam(), tgamma_test(), and tgammaf().
tgammaf()
OLM_DLLEXPORT float tgammaf (float)
References tgamma().
tgammal()
OLM_DLLEXPORT long double tgammal (long double)
References __polevll(), expl(), fabsl(), floorl(), GET_LDOUBLE_WORDS64, INFINITY, isnan, LDBL_MAX, lgammal(), MAXGAML, NAN, p, P, PIL, Q, rintl(), S, sinl(), SN, stirf(), and z.
trunc()
OLM_DLLEXPORT double trunc (double)
References EXTRACT_WORDS, huge, and INSERT_WORDS.
Referenced by rvOK(), and trunc_test().
truncf()
OLM_DLLEXPORT float truncf (float)
References F, GET_FLOAT_WORD, huge, and SET_FLOAT_WORD.
truncl()
OLM_DLLEXPORT long double truncl (long double)
References IEEEl2bits::e, GET_LDOUBLE_WORDS, GET_LDOUBLE_WORDS64, huge, LDBL_MANT_DIG, LDBL_MAX_EXP, MANH_SIZE, SET_LDOUBLE_WORDS, SET_LDOUBLE_WORDS64, u, and zero.
Variable Documentation
__infinity
const union __infinity_un __infinity
__nan
const union __nan_un __nan