Embedded Artistry libc: src/gdtoa/src/strtorQ.c File Reference
strtorQ.c File Reference
#include "gdtoaimp.h"
Functions
void ULtoQ (ULong *L, const ULong *bits, Long exp, int k)
int strtorQ (CONST char *s, char **sp, int rounding, void *L)
Function Documentation
strtorQ()
int strtorQ (CONST char * s, char ** sp, int rounding, void * L)
Definition at line 110 of file strtorQ.c.
 {
     static FPI fpi0 = {113, 1 - 16383 - 113 + 1, 32766 - 16383 - 113 + 1, 1, SI};
     FPI *fpi, fpi1;
     ULong bits[4];
     Long exp;
     int k;
     fpi = &fpi0;
     if(rounding != FPI_Round_near)
     {
         fpi1 = fpi0;
         fpi1.rounding = rounding;
         fpi = &fpi1;
     }
     k = strtodg(s, sp, fpi, &exp, bits);
     ULtoQ((ULong*)L, bits, exp, k);
     return k;
 }
References fpi1, FPI_Round_near, Long, SI, strtodg(), and ULtoQ().
ULtoQ()
void ULtoQ (ULong * L, const ULong * bits, Long exp, int k)
Definition at line 59 of file strtorQ.c.
 {
     switch(k & STRTOG_Retmask)
     {
         case STRTOG_NoNumber:
         case STRTOG_Zero:
             L[0] = L[1] = L[2] = L[3] = 0;
             break;
         case STRTOG_Normal:
         case STRTOG_NaNbits:
             L[_3] = bits[0];
             L[_2] = bits[1];
             L[_1] = bits[2];
             L[_0] = (bits[3] & (unsigned)~0x10000) | (unsigned)((exp + 0x3fff + 112) << 16);
             break;
         case STRTOG_Denormal:
             L[_3] = bits[0];
             L[_2] = bits[1];
             L[_1] = bits[2];
             L[_0] = bits[3];
             break;
         case STRTOG_Infinite:
             L[_0] = 0x7fff0000;
             L[_1] = L[_2] = L[_3] = 0;
             break;
         case STRTOG_NaN:
             L[0] = ld_QNAN0;
             L[1] = ld_QNAN1;
             L[2] = ld_QNAN2;
             L[3] = ld_QNAN3;
     }
     if(k & STRTOG_Neg)
     {
         {
             L[_0] |= 0x80000000L;
         }
     }
 }
References STRTOG_Denormal, STRTOG_Infinite, STRTOG_NaN, STRTOG_NaNbits, STRTOG_Neg, STRTOG_NoNumber, STRTOG_Normal, STRTOG_Retmask, and STRTOG_Zero.
Referenced by strtoIQ(), and strtorQ().