Embedded Artistry Framework: embvm::clk::SystemClock Class Reference
embvm::clk::SystemClock Class Reference abstract
This class defines common system clock interfaces.
#include <system_clock.hpp>
Public Types
using spin_duration_t = std::chrono::duration< uint32_t, std::micro >
Default spin increment is microseconds.
using tick_duration_t = std::chrono::duration< uint64_t, std::micro >
Public Member Functions
SystemClock ()
Default constructor.
virtual freq_hz_t::rep frequency () const =0
Get the frequency of the system clock.
virtual tick_duration_t::rep ticks () const =0
Check the ticks elapsed since boot.
virtual void spin (spin_duration_t::rep count)=0
Spin the processor for the specified number of ticks.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
SystemClock Driver Type ID.
Protected Member Functions
~SystemClock () override
Default destructor.
void start_ () override=0
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () override=0
Derived classes override the start_ method to control driver-specific startup behavior.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Detailed Description
This class defines common system clock interfaces.
Define a system clock driver
To create a system clock driver, derive from the SystemClock object:
class SimulatorSystemClock final : public SystemClock
{ ... };
Derived classes must implement the following interfaces:
frequency()
tips()
spin()
Derived classes must also implement pure virtual embvm::DriverBase functions:
start_()
stop_()
Member Typedef Documentation
spin_duration_t
using embvm::clk::SystemClock::spin_duration_t = std::chrono::duration<uint32_t, std::micro>
Default spin increment is microseconds.
tick_duration_t
using embvm::clk::SystemClock::tick_duration_t = std::chrono::duration<uint64_t, std::micro>
Constructor & Destructor Documentation
SystemClock()
embvm::clk::SystemClock::SystemClock () inline
Default constructor.
Initializes the SystemClock instance with a generic name.
~SystemClock()
SystemClock::~SystemClock () override protected default
Default destructor.
Member Function Documentation
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
frequency()
virtual freq_hz_t::rep embvm::clk::SystemClock::frequency () const pure virtual
Get the frequency of the system clock.
Returns
the frequency of the system clock, in Hz.
Implemented in embdrv::SimulatorSystemClock.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
spin()
virtual void embvm::clk::SystemClock::spin (spin_duration_t::rep count) pure virtual
Spin the processor for the specified number of ticks.
Derived classes must implement the spin() function.
Parameters
count The number of ticks to spin the processor for.
Implemented in embdrv::SimulatorSystemClock.
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void embvm::clk::SystemClock::start_ () override protected pure virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in embdrv::SimulatorSystemClock.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void embvm::clk::SystemClock::stop_ () override protected pure virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in embdrv::SimulatorSystemClock.
ticks()
virtual tick_duration_t::rep embvm::clk::SystemClock::ticks () const pure virtual
Check the ticks elapsed since boot.
Derived classes must implement the ticks() function.
Returns
ticks elapsed since boot.
Implemented in embdrv::SimulatorSystemClock.
Referenced by embvm::LoggerBase< TLock >::log().
type()
static constexpr embvm::DriverType embvm::clk::SystemClock::type () inline static
SystemClock Driver Type ID.
Returns
SystemClock type ID.
References embvm::SYSTEM_CLOCK.
Member Data Documentation
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
The documentation for this class was generated from the following files:
src/core/driver/system_clock.hpp
src/core/driver/internal/system_clock.cpp