Embedded Artistry Framework: src/stdlibs/libc/src/ctype/isblank.c File Reference
isblank.c File Reference
#include <ctype.h>
Functions
int isblank (int c)
Checks if the given character is a blank character.
Function Documentation
isblank()
int isblank (int ch)
Checks if the given character is a blank character.
Checks if the given character is a blank character using the default locale. The following characters classified as blank:
space (0x20)
horizontal tab (0x09)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a blank character, zero otherwise.
Referenced by bad_input(), good_input(), and iswblank().