Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_casinl.c File Reference
s_casinl.c File Reference
#include <float.h>
#include <openlibm_complex.h>
#include <openlibm_math.h>
Functions
long double complex casinl (long double complex z)
Variables
static const long double MACHEPL = 5.42101086242752217003726400434970855712890625E-20L
static const long double PIO2L = 1.570796326794896619231321691639751442098585L
Function Documentation
casinl()
long double complex casinl (long double complex z)
References asinl(), b, cabsl(), cimagl(), clogl(), complex, creall(), csqrtl(), fabsl(), I, MACHEPL, n, PIO2L, sum(), w, and z.
Referenced by cacosl(), and casinhl().
Variable Documentation
MACHEPL
const long double MACHEPL = 5.42101086242752217003726400434970855712890625E-20L static
Referenced by casinl().
PIO2L
const long double PIO2L = 1.570796326794896619231321691639751442098585L static
Referenced by casinl().