Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_coshf.c File Reference
e_coshf.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float __ieee754_coshf (float x)
Variables
static const float one = 1.0
static const float half =0.5
static const float huge = 1.0e30
Function Documentation
__ieee754_coshf()
OLM_DLLEXPORT float __ieee754_coshf (float x)
References __ieee754_expf(), __ldexp_expf(), expm1f(), fabsf(), GET_FLOAT_WORD, half, huge, one, t, and w.
Variable Documentation
half
const float half =0.5 static
Referenced by __ieee754_coshf().
huge
const float huge = 1.0e30 static
Referenced by __ieee754_coshf().
one
const float one = 1.0 static
Referenced by __ieee754_coshf().