Embedded Artistry Framework: src/stdlibs/libmemory/test/main.c File Reference
main.c File Reference
#include <support/memory.h>
#include <tests.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Functions
int main (void)
Function for application main entry.
Function Documentation
main()
int main (void)
Function for application main entry.
References abort_program_, aligned_malloc_tests(), allocate_memory(), embvm::VirtualPlatformBase< BlinkyDemoPlatform< THWPlatform, TDriverRegistry >, TDriverRegistry >::inst(), and malloc_tests().
Referenced by embvm::BootSequencer< TBootStrategy >::DefaultBootStrategy(), main_thread_func(), and embvm::BootSequencer< TBootStrategy >::OSXSimulatorBootStrategy().