Embedded Artistry Framework: nRFTWITranslator Class Reference
nRFTWITranslator Class Reference
#include <twi_helper.hpp>
Static Public Member Functions
static void setSCLPin (uint8_t inst, uint8_t port, uint8_t pin) noexcept
static void setSDAPin (uint8_t inst, uint8_t port, uint8_t pin) noexcept
static void setFrequency (uint8_t inst, embvm::i2c::baud freq) noexcept
static void disable (uint8_t inst) noexcept
static void enable (uint8_t inst) noexcept
static void disable_interrupts (uint8_t inst) noexcept
static void enable_interrupts (uint8_t inst) noexcept
static void set_transfer_address (uint8_t inst, uint8_t address) noexcept
static void tx_transfer (uint8_t inst, const uint8_t *data, size_t length, bool no_stop) noexcept
Blocking Transfer Implementation.
static void rx_transfer (uint8_t inst, uint8_t *data, size_t length) noexcept
static void stop_condition (uint8_t inst) noexcept
Static Public Attributes
static constexpr bool NO_STOP = true
static constexpr bool STOP = false
Private Member Functions
nRFTWITranslator ()=default
This class can't be instantiated.
~nRFTWITranslator ()=default
Constructor & Destructor Documentation
nRFTWITranslator()
nRFTWITranslator::nRFTWITranslator () private default
This class can't be instantiated.
~nRFTWITranslator()
nRFTWITranslator::~nRFTWITranslator () private default
Member Function Documentation
disable()
void nRFTWITranslator::disable (uint8_t inst) static noexcept
References disable_shortcuts_(), getTWIInst(), and embutil::volatile_store().
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::stop_().
disable_interrupts()
void nRFTWITranslator::disable_interrupts (uint8_t inst) static noexcept
References getTWIInst().
enable()
void nRFTWITranslator::enable (uint8_t inst) static noexcept
References getTWIInst(), and embutil::volatile_store().
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::start_().
enable_interrupts()
static void nRFTWITranslator::enable_interrupts (uint8_t inst) static noexcept
rx_transfer()
void nRFTWITranslator::rx_transfer (uint8_t inst, uint8_t * data, size_t length) static noexcept
References assert, check_event_(), clear_event_(), getTWIInst(), length, set_shortcuts_(), and task_trigger_().
set_transfer_address()
void nRFTWITranslator::set_transfer_address (uint8_t inst, uint8_t address) static noexcept
References getTWIInst(), and embutil::volatile_store().
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::transfer_().
setFrequency()
void nRFTWITranslator::setFrequency (uint8_t inst, embvm::i2c::baud freq) static noexcept
References getTWIFrequency(), getTWIInst(), and embutil::volatile_store().
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::baudrate_().
setSCLPin()
void nRFTWITranslator::setSCLPin (uint8_t inst, uint8_t port, uint8_t pin) static noexcept
References getTWIInst(), and embutil::volatile_store().
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::start_().
setSDAPin()
void nRFTWITranslator::setSDAPin (uint8_t inst, uint8_t port, uint8_t pin) static noexcept
References getTWIInst(), and embutil::volatile_store().
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::start_().
stop_condition()
void nRFTWITranslator::stop_condition (uint8_t inst) static noexcept
References getTWIInst(), and task_trigger_().
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::transfer_().
tx_transfer()
void nRFTWITranslator::tx_transfer (uint8_t inst, const uint8_t * data, size_t length, bool no_stop) static noexcept
Blocking Transfer Implementation.
Implementation note: If you clear the TWI_EVENET_TXDSENT event, the data that is already loaded into the TX buffer will be re-sent. You must load the next TX byte and then clear the data.
References assert, check_event_(), clear_event_(), getTWIInst(), length, set_shortcuts_(), and task_trigger_().
Member Data Documentation
NO_STOP
constexpr bool nRFTWITranslator::NO_STOP = true static
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::transfer_().
STOP
constexpr bool nRFTWITranslator::STOP = false static
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::transfer_().
The documentation for this class was generated from the following files:
src/processors/arm/nordic/drivers/helpers/twi_helper.hpp
src/processors/arm/nordic/drivers/helpers/twi_helper.cpp