Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_csinf.c File Reference
s_csinf.c File Reference
#include <openlibm_complex.h>
#include <openlibm_math.h>
Functions
static void cchshf (float xx, float *c, float *s)
float complex csinf (float complex z)
Function Documentation
cchshf()
static void cchshf (float xx, float * c, float * s) static
References coshf(), IEEEl2bits::e, expf(), fabsf(), s, and sinhf().
Referenced by csinf().
csinf()
float complex csinf (float complex z)
References cchshf(), cimagf(), complex, cosf(), crealf(), I, sinf(), w, and z.