Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_scalbnf.c File Reference
s_scalbnf.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float scalbnf (float x, int n)
__strong_reference (scalbnf, ldexpf)
Variables
static const float two25 = 3.355443200e+07
static const float twom25 = 2.9802322388e-08
static const float huge = 1.0e+30
static const float tiny = 1.0e-30
Function Documentation
__strong_reference()
__strong_reference (scalbnf , ldexpf)
scalbnf()
OLM_DLLEXPORT float scalbnf (float x, int n)
References copysignf(), GET_FLOAT_WORD, huge, k, n, SET_FLOAT_WORD, tiny, two25, and twom25.
Referenced by __ieee754_powf(), and scalblnf().
Variable Documentation
huge
const float huge = 1.0e+30 static
Referenced by scalbnf().
tiny
const float tiny = 1.0e-30 static
Referenced by scalbnf().
two25
const float two25 = 3.355443200e+07 static
Referenced by scalbnf().
twom25
const float twom25 = 2.9802322388e-08 static
Referenced by scalbnf().