Embedded Artistry Framework: src/stdlibs/libc/src/math/fabs.c File Reference
fabs.c File Reference
#include <math.h>
#include <stdint.h>
Functions
double fabs (double x)
Function Documentation
fabs()
double fabs (double x)
References u.
Referenced by __ieee754_asin(), __ieee754_atan2(), __ieee754_cosh(), __ieee754_hypot(), __ieee754_j0(), __ieee754_j1(), __ieee754_jn(), __ieee754_lgamma_r(), __ieee754_pow(), __ieee754_remainder(), __ieee754_sinh(), _cchsh(), _ctans(), asinh(), atan(), atof_test(), casin(), cchsh(), ccosh(), check_float_internal(), csinh(), csqrt(), ctan(), ctanh(), dtoa(), erf(), erfc(), fabs_test(), gdtoa(), logb(), remquo(), strtod(), strtod_test(), and tanh().