Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_j1.c File Reference
e_j1.c File Reference
#include <assert.h>
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
static double pone (double)
static double qone (double)
OLM_DLLEXPORT double __ieee754_j1 (double x)
OLM_DLLEXPORT double __ieee754_y1 (double x)
Variables
static const double huge = 1e300
static const double one = 1.0
static const double invsqrtpi = 5.64189583547756279280e-01
static const double tpi = 6.36619772367581382433e-01
static const double r00 = -6.25000000000000000000e-02
static const double r01 = 1.40705666955189706048e-03
static const double r02 = -1.59955631084035597520e-05
static const double r03 = 4.96727999609584448412e-08
static const double s01 = 1.91537599538363460805e-02
static const double s02 = 1.85946785588630915560e-04
static const double s03 = 1.17718464042623683263e-06
static const double s04 = 5.04636257076217042715e-09
static const double s05 = 1.23542274426137913908e-11
static const double zero = 0.0
static const double U0 [5]
static const double V0 [5]
static const double pr8 [6]
static const double ps8 [5]
static const double pr5 [6]
static const double ps5 [5]
static const double pr3 [6]
static const double ps3 [5]
static const double pr2 [6]
static const double ps2 [5]
static const double qr8 [6]
static const double qs8 [6]
static const double qr5 [6]
static const double qs5 [6]
static const double qr3 [6]
static const double qs3 [6]
static const double qr2 [6]
static const double qs2 [6]
Function Documentation
__ieee754_j1()
OLM_DLLEXPORT double __ieee754_j1 (double x)
References cos(), fabs(), GET_HIGH_WORD, huge, invsqrtpi, one, pone(), qone(), r, r00, r01, r02, r03, s, s01, s02, s03, s04, s05, sin(), sqrt(), u, z, and zero.
Referenced by __ieee754_jn(), and __ieee754_y1().
__ieee754_y1()
OLM_DLLEXPORT double __ieee754_y1 (double x)
References __ieee754_j1(), __ieee754_log(), cos(), EXTRACT_WORDS, invsqrtpi, one, pone(), qone(), s, sin(), sqrt(), tpi, u, U0, V0, z, and zero.
Referenced by __ieee754_yn().
pone()
static double pone (double x) static
References assert, GET_HIGH_WORD, one, p, pr2, pr3, pr5, pr8, ps2, ps3, ps5, ps8, r, s, and z.
Referenced by __ieee754_j1(), and __ieee754_y1().
qone()
static double qone (double x)
References assert, GET_HIGH_WORD, one, p, qr2, qr3, qr5, qr8, qs2, qs3, qs5, qs8, r, s, and z.
Referenced by __ieee754_j1(), and __ieee754_y1().
Variable Documentation
huge
const double huge = 1e300 static
Referenced by __ieee754_j1().
invsqrtpi
const double invsqrtpi = 5.64189583547756279280e-01 static
Referenced by __ieee754_j1(), and __ieee754_y1().
one
const double one = 1.0 static
Referenced by __ieee754_j1(), __ieee754_y1(), pone(), and qone().
pr2
const double pr2[6] static
Initial value:
= {
  1.07710830106873743082e-07,
  1.17176219462683348094e-01,
  2.36851496667608785174e+00,
  1.22426109148261232917e+01,
  1.76939711271687727390e+01,
  5.07352312588818499250e+00,
}
Referenced by pone().
pr3
const double pr3[6] static
Initial value:
= {
  3.02503916137373618024e-09,
  1.17186865567253592491e-01,
  3.93297750033315640650e+00,
  3.51194035591636932736e+01,
  9.10550110750781271918e+01,
  4.85590685197364919645e+01,
}
Referenced by pone().
pr5
const double pr5[6] static
Initial value:
= {
  1.31990519556243522749e-11,
  1.17187493190614097638e-01,
  6.80275127868432871736e+00,
  1.08308182990189109773e+02,
  5.17636139533199752805e+02,
  5.28715201363337541807e+02,
}
Referenced by pone().
pr8
const double pr8[6] static
Initial value:
= {
  0.00000000000000000000e+00,
  1.17187499999988647970e-01,
  1.32394806593073575129e+01,
  4.12051854307378562225e+02,
  3.87474538913960532227e+03,
  7.91447954031891731574e+03,
}
Referenced by pone().
ps2
const double ps2[5] static
Initial value:
= {
  2.14364859363821409488e+01,
  1.25290227168402751090e+02,
  2.32276469057162813669e+02,
  1.17679373287147100768e+02,
  8.36463893371618283368e+00,
}
Referenced by pone().
ps3
const double ps3[5] static
Initial value:
= {
  3.47913095001251519989e+01,
  3.36762458747825746741e+02,
  1.04687139975775130551e+03,
  8.90811346398256432622e+02,
  1.03787932439639277504e+02,
}
Referenced by pone().
ps5
const double ps5[5] static
Initial value:
= {
  5.92805987221131331921e+01,
  9.91401418733614377743e+02,
  5.35326695291487976647e+03,
  7.84469031749551231769e+03,
  1.50404688810361062679e+03,
}
Referenced by pone().
ps8
const double ps8[5] static
Initial value:
= {
  1.14207370375678408436e+02,
  3.65093083420853463394e+03,
  3.69562060269033463555e+04,
  9.76027935934950801311e+04,
  3.08042720627888811578e+04,
}
Referenced by pone().
qr2
const double qr2[6] static
Initial value:
= {
 -1.78381727510958865572e-07,
 -1.02517042607985553460e-01,
 -2.75220568278187460720e+00,
 -1.96636162643703720221e+01,
 -4.23253133372830490089e+01,
 -2.13719211703704061733e+01,
}
Referenced by qone().
qr3
const double qr3[6] static
Initial value:
= {
 -5.07831226461766561369e-09,
 -1.02537829820837089745e-01,
 -4.61011581139473403113e+00,
 -5.78472216562783643212e+01,
 -2.28244540737631695038e+02,
 -2.19210128478909325622e+02,
}
Referenced by qone().
qr5
const double qr5[6] static
Initial value:
= {
 -2.08979931141764104297e-11,
 -1.02539050241375426231e-01,
 -8.05644828123936029840e+00,
 -1.83669607474888380239e+02,
 -1.37319376065508163265e+03,
 -2.61244440453215656817e+03,
}
Referenced by qone().
qr8
const double qr8[6] static
Initial value:
= {
  0.00000000000000000000e+00,
 -1.02539062499992714161e-01,
 -1.62717534544589987888e+01,
 -7.59601722513950107896e+02,
 -1.18498066702429587167e+04,
 -4.84385124285750353010e+04,
}
Referenced by qone().
qs2
const double qs2[6] static
Initial value:
= {
  2.95333629060523854548e+01,
  2.52981549982190529136e+02,
  7.57502834868645436472e+02,
  7.39393205320467245656e+02,
  1.55949003336666123687e+02,
 -4.95949898822628210127e+00,
}
Referenced by qone().
qs3
const double qs3[6] static
Initial value:
= {
  4.76651550323729509273e+01,
  6.73865112676699709482e+02,
  3.38015286679526343505e+03,
  5.54772909720722782367e+03,
  1.90311919338810798763e+03,
 -1.35201191444307340817e+02,
}
Referenced by qone().
qs5
const double qs5[6] static
Initial value:
= {
  8.12765501384335777857e+01,
  1.99179873460485964642e+03,
  1.74684851924908907677e+04,
  4.98514270910352279316e+04,
  2.79480751638918118260e+04,
 -4.71918354795128470869e+03,
}
Referenced by qone().
qs8
const double qs8[6] static
Initial value:
= {
  1.61395369700722909556e+02,
  7.82538599923348465381e+03,
  1.33875336287249578163e+05,
  7.19657723683240939863e+05,
  6.66601232617776375264e+05,
 -2.94490264303834643215e+05,
}
Referenced by qone().
r00
const double r00 = -6.25000000000000000000e-02 static
Referenced by __ieee754_j1().
r01
const double r01 = 1.40705666955189706048e-03 static
Referenced by __ieee754_j1().
r02
const double r02 = -1.59955631084035597520e-05 static
Referenced by __ieee754_j1().
r03
const double r03 = 4.96727999609584448412e-08 static
Referenced by __ieee754_j1().
s01
const double s01 = 1.91537599538363460805e-02 static
Referenced by __ieee754_j1().
s02
const double s02 = 1.85946785588630915560e-04 static
Referenced by __ieee754_j1().
s03
const double s03 = 1.17718464042623683263e-06 static
Referenced by __ieee754_j1().
s04
const double s04 = 5.04636257076217042715e-09 static
Referenced by __ieee754_j1().
s05
const double s05 = 1.23542274426137913908e-11 static
Referenced by __ieee754_j1().
tpi
const double tpi = 6.36619772367581382433e-01 static
Referenced by __ieee754_y1().
U0
const double U0[5] static
Initial value:
= {
 -1.96057090646238940668e-01,
  5.04438716639811282616e-02,
 -1.91256895875763547298e-03,
  2.35252600561610495928e-05,
 -9.19099158039878874504e-08,
}
Referenced by __ieee754_y1().
V0
const double V0[5] static
Initial value:
= {
  1.99167318236649903973e-02,
  2.02552581025135171496e-04,
  1.35608801097516229404e-06,
  6.22741452364621501295e-09,
  1.66559246207992079114e-11,
}
Referenced by __ieee754_y1().
zero
const double zero = 0.0 static
Referenced by __ieee754_j1(), and __ieee754_y1().