Embedded Artistry Framework: src/stdlibs/libc/src/stdlib/heapsort.c File Reference
heapsort.c File Reference
#include <stddef.h>
#include <stdlib.h>
Macros
#define SWAP(a, b, count, size, tmp)
#define COPY(a, b, count, size, tmp1, tmp2)
#define CREATE(initval, nmemb, par_i, child_i, par, child, size, count, tmp)
#define SELECT(par_i, child_i, nmemb, par, child, size, k, count, tmp1, tmp2)
Functions
int heapsort (void *vbase, size_t nmemb, size_t size, int *compar)
Macro Definition Documentation
COPY
#define COPY (a, b, count, size, tmp1, tmp2)
Value:
{                                       \
        count = size;                       \
        tmp1 = a;                           \
        tmp2 = b;                           \
        do                                  \
        {                                   \
            *tmp1++ = *tmp2++;              \
        } while(--count);                   \
    }
CREATE
#define CREATE (initval, nmemb, par_i, child_i, par, child, size, count, tmp)
Value:
{                                                                         \
        for(par_i = initval; (child_i = par_i * 2) <= nmemb; par_i = child_i) \
        {                                                                     \
            child = base + child_i * size;                                    \
            if(child_i < nmemb && compar(child, child + size) < 0)            \
            {                                                                 \
                child += size;                                                \
                ++child_i;                                                    \
            }                                                                 \
            par = base + par_i * size;                                        \
            if(compar(child, par) <= 0)                                       \
                break;                                                        \
            SWAP(par, child, count, size, tmp);                               \
        }                                                                     \
    }
SELECT
#define SELECT (par_i, child_i, nmemb, par, child, size, k, count, tmp1, tmp2)
Value:
{                                                                         \
        for(par_i = 1; (child_i = par_i * 2) <= nmemb; par_i = child_i)       \
        {                                                                     \
            child = base + child_i * size;                                    \
            if(child_i < nmemb && compar(child, child + size) < 0)            \
            {                                                                 \
                child += size;                                                \
                ++child_i;                                                    \
            }                                                                 \
            par = base + par_i * size;                                        \
            COPY(par, child, count, size, tmp1, tmp2);                        \
        }                                                                     \
        for(;;)                                                               \
        {                                                                     \
            child_i = par_i;                                                  \
            par_i = child_i / 2;                                              \
            child = base + child_i * size;                                    \
            par = base + par_i * size;                                        \
            if(child_i == 1 || compar(k, par) < 0)                            \
            {                                                                 \
                COPY(child, k, count, size, tmp1, tmp2);                      \
                break;                                                        \
            }                                                                 \
            COPY(child, par, count, size, tmp1, tmp2);                        \
        }                                                                     \
    }
SWAP
#define SWAP (a, b, count, size, tmp)
Value:
{                                \
        count = size;                \
        do                           \
        {                            \
            tmp = *a;                \
            *a++ = *b;               \
            *b++ = tmp;              \
        } while(--count);            \
    }
Function Documentation
heapsort()
int heapsort (void* vbase, size_t nmemb, size_t size, int * compar)
References COPY, CREATE, free(), k, malloc(), NULL, p, SELECT, and t.
Referenced by char_test(), heapsort_int_test(), heapsort_string_test(), and uint64_test().