Embedded Artistry Framework: Unit Test Drivers
Unit Test Drivers
Framework Drivers
Drivers intended for use with unit test code.
Classes
class test::TestDriverBase
Test driver that enables testing DriverBase.
class test::UnitTestGPIOInput
Unit Test GPIO Input Driver.
class test::UnitTestGPIOInputWithPullup
Unit Test GPIO Input Driver, with a pullup.
class test::i2cTestDriver
I2C Master Unit Test Driver.
class test::spiTestDriver
SPI Master Unit Test Driver.
Detailed Description
Drivers intended for use with unit test code.
Class Documentation
test::TestDriverBase
class test::TestDriverBase
Test driver that enables testing DriverBase.
Public Member Functions
TestDriverBase (const char *name, uint32_t c=embvm::DriverType::Undefined)
Create a driver base.
TestDriverBase (const std::string &name, uint32_t c=embvm::DriverType::Undefined)
TestDriverBase (const std::string_view &name, uint32_t c=embvm::DriverType::Undefined)
~TestDriverBase () final
Default destructor.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
Constructor & Destructor Documentation
TestDriverBase() [1/3]
test::TestDriverBase::TestDriverBase (const char * name, uint32_t c = embvm::DriverType::Undefined) inline
Create a driver base.
Parameters
name The name of the driver base
Note
DriverBase() uses a std::string_view, so name input smust remain valid
Parameters
c The type of the driver base
TestDriverBase() [2/3]
test::TestDriverBase::TestDriverBase (const std::string & name, uint32_t c = embvm::DriverType::Undefined) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
TestDriverBase() [3/3]
test::TestDriverBase::TestDriverBase (const std::string_view & name, uint32_t c = embvm::DriverType::Undefined) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
~TestDriverBase()
TestDriverBase::~TestDriverBase () final
Default destructor.
Member Function Documentation
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void TestDriverBase::start_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void TestDriverBase::stop_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Member Data Documentation
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
test::UnitTestGPIOInput
class test::UnitTestGPIOInput
Unit Test GPIO Input Driver.
Public Member Functions
bool get () final
Get the current GPIO pin state.
gpio::pull pull () const
Get the current pull configuration.
gpio::direction direction () const
Check the direction of the GPIO pin.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
GPIO Driver Type ID.
Protected Member Functions
embvm::gpio::pull pull_ (embvm::gpio::pull p) final
Set the pull configuration in hardware.
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Member Function Documentation
direction()
gpio::direction embvm::gpio::base< TDir >::direction () const inline inherited
Check the direction of the GPIO pin.
Returns
The configured direction of this GPIO pin.
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
get()
bool UnitTestGPIOInput::get () final virtual
Get the current GPIO pin state.
Derived classes must implement the get() function.
Returns
true if the GPIO is set (logic 1), false otherwise (logic 0).
Implements embvm::gpio::input< embvm::gpio::pull::none >.
References embvm::gpio::none, embvm::gpio::input< embvm::gpio::pull::none >::pull(), embvm::gpio::pulldown, and embvm::gpio::pullup.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
pull()
gpio::pull embvm::gpio::input< TPull >::pull () const inline inherited
Get the current pull configuration.
Returns
The currently configured GPIO pull setting.
pull_()
embvm::gpio::pull UnitTestGPIOInput::pull_ (embvm::gpio::pull p) final protected virtual
Set the pull configuration in hardware.
Derived classes must implement the pull_(gpio::pull p) function.
Returns
The currently configured GPIO pull setting.
Implements embvm::gpio::input< embvm::gpio::pull::none >.
References p.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void UnitTestGPIOInput::start_ () final protected virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::gpio::input< embvm::gpio::pull::none >.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void UnitTestGPIOInput::stop_ () final protected virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::gpio::input< embvm::gpio::pull::none >.
type()
static constexpr embvm::DriverType embvm::gpio::base< TDir >::type () inline static inherited
GPIO Driver Type ID.
Returns
GPIO type ID.
Member Data Documentation
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
test::UnitTestGPIOInputWithPullup
class test::UnitTestGPIOInputWithPullup
Unit Test GPIO Input Driver, with a pullup.
Public Member Functions
bool get () final
Get the current GPIO pin state.
gpio::pull pull () const
Get the current pull configuration.
gpio::direction direction () const
Check the direction of the GPIO pin.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
GPIO Driver Type ID.
Protected Member Functions
embvm::gpio::pull pull_ (embvm::gpio::pull p) final
Set the pull configuration in hardware.
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Attributes
embvm::gpio::pull p_ = embvm::gpio::pull::pullup
Member Function Documentation
direction()
gpio::direction embvm::gpio::base< TDir >::direction () const inline inherited
Check the direction of the GPIO pin.
Returns
The configured direction of this GPIO pin.
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
get()
bool UnitTestGPIOInputWithPullup::get () final virtual
Get the current GPIO pin state.
Derived classes must implement the get() function.
Returns
true if the GPIO is set (logic 1), false otherwise (logic 0).
Implements embvm::gpio::input< embvm::gpio::pull::pullup >.
References embvm::gpio::none, embvm::gpio::input< embvm::gpio::pull::pullup >::pull(), embvm::gpio::pulldown, and embvm::gpio::pullup.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
pull()
gpio::pull embvm::gpio::input< TPull >::pull () const inline inherited
Get the current pull configuration.
Returns
The currently configured GPIO pull setting.
pull_()
embvm::gpio::pull UnitTestGPIOInputWithPullup::pull_ (embvm::gpio::pull p) final protected virtual
Set the pull configuration in hardware.
Derived classes must implement the pull_(gpio::pull p) function.
Returns
The currently configured GPIO pull setting.
Implements embvm::gpio::input< embvm::gpio::pull::pullup >.
References p, and p_.
Referenced by start_().
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void UnitTestGPIOInputWithPullup::start_ () final protected virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::gpio::input< embvm::gpio::pull::pullup >.
References p_, pull_(), and embvm::gpio::pullup.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void UnitTestGPIOInputWithPullup::stop_ () final protected virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::gpio::input< embvm::gpio::pull::pullup >.
type()
static constexpr embvm::DriverType embvm::gpio::base< TDir >::type () inline static inherited
GPIO Driver Type ID.
Returns
GPIO type ID.
Member Data Documentation
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
p_
embvm::gpio::pull test::UnitTestGPIOInputWithPullup::p_ = embvm::gpio::pull::pullup private
Referenced by pull_(), and start_().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
test::i2cTestDriver
class test::i2cTestDriver
I2C Master Unit Test Driver.
This driver can be used as a "fake" for a unit test.
You can prepare return data for a TX operation:
uint8_t expected[2] = {0xBE, 0xAE};
d.appendToRxBuffer(expected, sizeof(expected));
You can verify the data that was transmitted:
CHECK(true == d.checkTxBuffer(input, sizeof(input)));
Public Types
using cb_t = stdext::inplace_function< void(i2c::op_t, i2c::status)>
Represents the type of the callback operation.
using sweep_list_t = etl::vector< uint8_t, 128 >
using sweep_cb_t = stdext::inplace_function< void(void)>
Public Member Functions
i2cTestDriver ()
Create a generic I2C Master.
i2cTestDriver (const char *name)
Create a named I2C master.
~i2cTestDriver () final
Default destructor.
bool checkTxBuffer (uint8_t *data, size_t length)
Verify that the driver transmitted the correct data.
void clearTxBuffer ()
Clear the stored TX buffer.
void appendToRxBuffer (uint8_t *data, size_t length)
Append data to the RX buffer to be returned with the next read operation.
void clearRxBuffer ()
Clears the data stored in the RX buffer.
virtual void configure (i2c::baud baud, i2c::pullups pull=i2c::pullups::external)
Configure the I2C bus.
i2c::state state ()
Check the I2C bus status.
i2c::pullups pullups (i2c::pullups pullups)
Configure pull-ups.
i2c::pullups pullups ()
Check the pull-up configuration.
void sweep (sweep_list_t &found_list, const sweep_cb_t &cb)
Perform an I2C bus sweep to identify active devices.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
I2C Driver Type ID.
Protected Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void configure_ (embvm::i2c::pullups) final
Configure the I2C bus for operation.
embvm::i2c::status transfer_ (const embvm::i2c::op_t &op, const embvm::i2c::master::cb_t &cb) final
embvm::i2c::baud baudrate_ (embvm::i2c::baud baud) final
embvm::i2c::pullups setPullups_ (embvm::i2c::pullups pullups) final
Configure pull-ups.
Protected Attributes
i2c::pullups pullups_ = i2c::pullups::external
Tracks the active pull-up configuration.
i2c::state state_ = i2c::state::idle
Tracks the status of the I2C bus.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Attributes
std::vector< uint8_t > txBuffer_
Storage represnting the tx buffer.
std::queue< uint8_t > rxBuffer_
Storage representing the rx bufferre.
Member Typedef Documentation
cb_t
using embvm::i2c::master::cb_t = stdext::inplace_function<void(i2c::op_t, i2c::status)> inherited
Represents the type of the callback operation.
sweep_cb_t
using embvm::i2c::master::sweep_cb_t = stdext::inplace_function<void(void)> inherited
sweep_list_t
using embvm::i2c::master::sweep_list_t = etl::vector<uint8_t, 128> inherited
Constructor & Destructor Documentation
i2cTestDriver() [1/2]
test::i2cTestDriver::i2cTestDriver () inline
Create a generic I2C Master.
i2cTestDriver() [2/2]
test::i2cTestDriver::i2cTestDriver (const char * name) inline explicit
Create a named I2C master.
Parameters
name The name of this i2c instance.
~i2cTestDriver()
i2cTestDriver::~i2cTestDriver () final
Default destructor.
Member Function Documentation
appendToRxBuffer()
void test::i2cTestDriver::appendToRxBuffer (uint8_t * data, size_t length) inline
Append data to the RX buffer to be returned with the next read operation.
Parameters
data The data to append to the RX buffer
length the number of bytes to append
References length, and rxBuffer_.
baudrate_()
embvm::i2c::baud i2cTestDriver::baudrate_ (embvm::i2c::baud baud) final protected virtual
Implements embvm::i2c::master.
checkTxBuffer()
bool test::i2cTestDriver::checkTxBuffer (uint8_t * data, size_t length) inline
Verify that the driver transmitted the correct data.
Parameters
data The data buffer to check.
length The number of bytes in the input buffer to compare.
References length, and txBuffer_.
clearRxBuffer()
void test::i2cTestDriver::clearRxBuffer () inline
Clears the data stored in the RX buffer.
References rxBuffer_, and swap.
clearTxBuffer()
void test::i2cTestDriver::clearTxBuffer () inline
Clear the stored TX buffer.
References txBuffer_.
configure()
virtual void embvm::i2c::master::configure (i2c::baud baud, i2c::pullups pull = i2c::pullups::external) inline virtual inherited
Configure the I2C bus.
Configures the I2C bus for operation and sets the target baud rate and pull-ups.
Derived classes must implement the configure_() function to set up the target hardware.
Parameters
baud The target baudrate (as an i2c::baud enumeration rather than integral Hz). TODO: Tolerance - allowed relative tolerance for the resulting baudrate
pull The pullup setting, which defaults to external pull-ups (in hardware).
References embvm::i2c::master::configure_(), and embvm::i2c::master::pullups().
Referenced by embvm::i2c::activeMaster< 128 >::configure_(), and FWDemoSimulatorHWPlatform::init_().
configure_()
void i2cTestDriver::configure_ (embvm::i2c::pullups pullups) final protected virtual
Configure the I2C bus for operation.
This function is implemented by the derived class. It is responsible for configuring the target hardware for operation.
Parameters
pullups The target pull-up configuration.
Implements embvm::i2c::master.
References embvm::i2c::master::pullups().
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
pullups() [1/2]
i2c::pullups embvm::i2c::master::pullups (i2c::pullups pullups) inline inherited
Configure pull-ups.
Parameters
pullups The target pull-up setting.
Returns
The configured pull-up setting.
References embvm::i2c::master::pullups_, and embvm::i2c::master::setPullups_().
Referenced by embvm::i2c::activeMaster< 128 >::setPullups_().
pullups() [2/2]
i2c::pullups embvm::i2c::master::pullups () inline inherited
Check the pull-up configuration.
Returns
The configured pull-up setting.
References embvm::i2c::master::pullups_.
Referenced by embvm::i2c::master::configure(), configure_(), embdrv::aardvarkI2CMaster::setPullups_(), setPullups_(), nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::setPullups_(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::setPullups_().
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
setPullups_()
embvm::i2c::pullups i2cTestDriver::setPullups_ (embvm::i2c::pullups pullups) final protected virtual
Configure pull-ups.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the requested pullup setting.
Parameters
pullups The target pull-up setting.
Returns
The configured pull-up setting.
Implements embvm::i2c::master.
References embvm::i2c::master::pullups().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void i2cTestDriver::start_ () final protected virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::i2c::master.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
state()
i2c::state embvm::i2c::master::state () inline inherited
Check the I2C bus status.
Returns
the status of the I2C bus as an i2c::state enumeration.
References embvm::i2c::master::state_.
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void i2cTestDriver::stop_ () final protected virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::i2c::master.
sweep()
void embvm::i2c::master::sweep (sweep_list_t & found_list, const sweep_cb_t & cb) inherited
Perform an I2C bus sweep to identify active devices.
The sweep function pings all I2C addresses. Devices which ACK are stored in a list and returned via callback.
Parameters
[in,out] found_list Caller's memory which will contain the successfully found ping addresses
[in] cb The callback which will be called to indicate that the sweep is complete. After the cb is called, found_list is valid and can be used by the caller.
References embvm::i2c::op_t::address, embvm::i2c::busy, embvm::i2c::ok, embvm::i2c::op_t::op, and embvm::i2c::ping.
transfer_()
embvm::i2c::status i2cTestDriver::transfer_ (const embvm::i2c::op_t & op, const embvm::i2c::master::cb_t & cb) final protected virtual
Implements embvm::i2c::master.
References embvm::i2c::busy, embvm::i2c::continueWriteNoStop, embvm::i2c::continueWriteStop, embvm::i2c::ok, embvm::i2c::op_t::op, embvm::i2c::ping, embvm::i2c::read, embvm::i2c::restart, embvm::i2c::stop, embvm::i2c::write, embvm::i2c::writeNoStop, and embvm::i2c::writeRead.
type()
static constexpr embvm::DriverType embvm::i2c::master::type () inline static inherited
I2C Driver Type ID.
Returns
I2C type ID.
References embvm::I2C.
Member Data Documentation
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
pullups_
i2c::pullups embvm::i2c::master::pullups_ = i2c::pullups::external protected inherited
Tracks the active pull-up configuration.
Referenced by embvm::i2c::master::pullups().
rxBuffer_
std::queue<uint8_t> test::i2cTestDriver::rxBuffer_ private
Storage representing the rx bufferre.
Referenced by appendToRxBuffer(), and clearRxBuffer().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
state_
i2c::state embvm::i2c::master::state_ = i2c::state::idle protected inherited
Tracks the status of the I2C bus.
Referenced by embvm::i2c::master::state().
txBuffer_
std::vector<uint8_t> test::i2cTestDriver::txBuffer_ private
Storage represnting the tx buffer.
Referenced by checkTxBuffer(), and clearTxBuffer().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
test::spiTestDriver
class test::spiTestDriver
SPI Master Unit Test Driver.
This driver can be used as a "fake" for a unit test.
You can prepare return data for a TX operation:
uint8_t expected[2] = {0xBE, 0xAE};
d.appendToRxBuffer(expected, sizeof(expected));
You can verify the data that was transmitted:
CHECK(true == d.checkTxBuffer(input, sizeof(input)));
Public Member Functions
spiTestDriver (const embvm::spi::master::DispatcherFunc &dispatcher=nullptr)
Create a generic spi driver with a dispatcher.
spiTestDriver (const char *name, const embvm::spi::master::DispatcherFunc &dispatcher=nullptr)
Create a named spi driver with a dispatcher.
~spiTestDriver () final
Default destructor.
bool checkTxBuffer (uint8_t *data, size_t length)
Verify that the driver transmitted the correct data.
void clearTxBuffer ()
Clear the stored TX buffer.
void appendToRxBuffer (uint8_t *data, size_t length)
Append data to the RX buffer to be returned with the next read operation.
void clearRxBuffer ()
Clears the data stored in the RX buffer.
virtual void configure (spi::baud_t baud)
Configure the SPI bus.
spi::mode mode () const
Get the current SPI bus mode.
spi::mode mode (spi::mode mode)
Set the SPI bus mode.
spi::order order () const
Get the current SPI bus byte order.
spi::order order (spi::order order)
Set the SPI bus byte order.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
SPI Driver Type ID.
Protected Member Functions
embvm::comm::status transfer_ (const spi::op_t &op, const cb_t &cb) override=0
Protected Attributes
spi::mode mode_ = spi::mode::mode0
Stores the active SPI mode configuration.
spi::order order_ = spi::order::msbFirst
Stores the active SPI byte ordering.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void setMode_ (embvm::spi::mode mode) final
Set the SPI bus mode.
void setOrder_ (embvm::spi::order order) final
Set the SPI bus byte order.
embvm::comm::status transfer_ (const embvm::spi::op_t &op, const embvm::spi::master::cb_t &cb) final
uint32_t baudrate_ (uint32_t baud) final
void configure_ () final
Configure the SPI bus for operation.
Private Attributes
std::vector< uint8_t > txBuffer_
std::queue< uint8_t > rxBuffer_
Constructor & Destructor Documentation
spiTestDriver() [1/2]
test::spiTestDriver::spiTestDriver (const embvm::spi::master::DispatcherFunc & dispatcher = nullptr) inline explicit
Create a generic spi driver with a dispatcher.
Parameters
dispatcher The function to use as a dispatcher for callbacks.
spiTestDriver() [2/2]
test::spiTestDriver::spiTestDriver (const char * name, const embvm::spi::master::DispatcherFunc & dispatcher = nullptr) inline explicit
Create a named spi driver with a dispatcher.
Parameters
name The name of the SPI driver instance.
dispatcher The function to use as a dispatcher for callbacks.
~spiTestDriver()
spiTestDriver::~spiTestDriver () final
Default destructor.
Member Function Documentation
appendToRxBuffer()
void test::spiTestDriver::appendToRxBuffer (uint8_t * data, size_t length) inline
Append data to the RX buffer to be returned with the next read operation.
Parameters
data The data to append to the RX buffer
length the number of bytes to append
References length, and rxBuffer_.
baudrate_()
uint32_t spiTestDriver::baudrate_ (uint32_t baud) final private virtual
Implements embvm::spi::master.
checkTxBuffer()
bool test::spiTestDriver::checkTxBuffer (uint8_t * data, size_t length) inline
Verify that the driver transmitted the correct data.
Parameters
data The data buffer to check.
length The number of bytes in the input buffer to compare.
References length, and txBuffer_.
clearRxBuffer()
void test::spiTestDriver::clearRxBuffer () inline
Clears the data stored in the RX buffer.
References rxBuffer_, and swap.
clearTxBuffer()
void test::spiTestDriver::clearTxBuffer () inline
Clear the stored TX buffer.
References txBuffer_.
configure()
virtual void embvm::spi::master::configure (spi::baud_t baud) inline virtual inherited
Configure the SPI bus.
Configures the SPI bus for operation and sets the target baud rate.
Derived classes must implement the configure_() function to set up the target hardware.
Parameters
baud The target baudrate, in Hz. TODO: Tolerance - allowed relative tolerance for the resulting baudrate
References embvm::spi::master::configure_().
configure_()
void spiTestDriver::configure_ () final private virtual
Configure the SPI bus for operation.
This function is implemented by the derived class. It is responsible for configuring the target hardware for operation.
Implements embvm::spi::master.
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
mode() [1/2]
spi::mode embvm::spi::master::mode () const inline inherited
Get the current SPI bus mode.
Returns
The currently configured mode.
References embvm::spi::master::mode_.
Referenced by embvm::spi::master::mode(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setMode_(), embdrv::aardvarkSPIMaster::setMode_(), and setMode_().
mode() [2/2]
spi::mode embvm::spi::master::mode (spi::mode mode) inline inherited
Set the SPI bus mode.
Derived classes must implement the setMode_() function, which is reponsible for configuring the target hardware.
Parameters
mode The desired SPI bus mode.
Returns
The new SPI bus mode.
References embvm::spi::master::mode(), embvm::spi::master::mode_, and embvm::spi::master::setMode_().
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
order() [1/2]
spi::order embvm::spi::master::order () const inline inherited
Get the current SPI bus byte order.
Returns
The currently configured byte order.
References embvm::spi::master::order_.
Referenced by embvm::spi::master::order(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setOrder_(), embdrv::aardvarkSPIMaster::setOrder_(), and setOrder_().
order() [2/2]
spi::order embvm::spi::master::order (spi::order order) inline inherited
Set the SPI bus byte order.
Derived classes must implement the setOrder_() function, which is reponsible for configuring the target hardware.
Parameters
order The desired byte ordering.
Returns
The new byte ordering.
References embvm::spi::master::order(), embvm::spi::master::order_, and embvm::spi::master::setOrder_().
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
setMode_()
void spiTestDriver::setMode_ (embvm::spi::mode mode) final private virtual
Set the SPI bus mode.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the new mode.
Parameters
mode The desired byte ordering.
Implements embvm::spi::master.
References embvm::spi::master::mode().
setOrder_()
void spiTestDriver::setOrder_ (embvm::spi::order order) final private virtual
Set the SPI bus byte order.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the new byte ordering.
Parameters
order The desired byte ordering.
Implements embvm::spi::master.
References embvm::spi::master::order().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void spiTestDriver::start_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::spi::master.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void spiTestDriver::stop_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::spi::master.
transfer_() [1/2]
embvm::comm::status spiTestDriver::transfer_ (const embvm::spi::op_t & op, const embvm::spi::master::cb_t & cb) final private
References embvm::spi::op_t::length, embvm::comm::ok, embvm::spi::op_t::rx_buffer, rxBuffer_, embvm::spi::op_t::tx_buffer, and txBuffer_.
transfer_() [2/2]
embvm::comm::status embvm::spi::master::transfer_ (const spi::op_t & op, const cb_t & cb) override protected pure virtual inherited
type()
static constexpr embvm::DriverType embvm::spi::master::type () inline static inherited
SPI Driver Type ID.
Returns
SPI type ID.
References embvm::SPI.
Member Data Documentation
mode_
spi::mode embvm::spi::master::mode_ = spi::mode::mode0 protected inherited
Stores the active SPI mode configuration.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embvm::spi::master::mode(), and embdrv::aardvarkSPIMaster::setMode_().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
order_
spi::order embvm::spi::master::order_ = spi::order::msbFirst protected inherited
Stores the active SPI byte ordering.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embvm::spi::master::order(), and embdrv::aardvarkSPIMaster::setOrder_().
rxBuffer_
std::queue<uint8_t> test::spiTestDriver::rxBuffer_ private
Referenced by appendToRxBuffer(), clearRxBuffer(), and transfer_().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
txBuffer_
std::vector<uint8_t> test::spiTestDriver::txBuffer_ private
Referenced by checkTxBuffer(), clearTxBuffer(), and transfer_().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().