Embedded Artistry Framework: src/stdlibs/libc/src/string/strchr.c File Reference
strchr.c File Reference
#include <string.h>
Functions
char * __strchrnul (const char *, int)
char * strchr (const char *s, int c)
Finds the first occurrence of c in the null-terminated byte string pointed to by s.
Function Documentation
__strchrnul()
char* __strchrnul (const char * , int)
Referenced by strchr(), and strcspn().
strchr()
char* strchr (const char * s, int c)
Finds the first occurrence of c in the null-terminated byte string pointed to by s.
Finds the first occurrence of c (after conversion to char as if by (char)c) in the null-terminated byte string pointed to by s (each character interpreted as unsigned char). The terminating null character is considered to be a part of the string and can be found when searching for '\0'.
The behavior is undefined if s is not a pointer to a null-terminated byte string.
Parameters
s pointer to the null-terminated byte string to be analyzed
c character to search for
Returns
a pointer to the found character in s, or null pointer if no such character is found.
References __strchrnul(), r, and s.
Referenced by strchr_test().