Embedded Artistry Framework: src/stdlibs/libc/src/ctype/tolower.c File Reference
tolower.c File Reference
#include <ctype.h>
Functions
int tolower (int c)
Converts the given character to lowercase.
Function Documentation
tolower()
int tolower (int ch)
Converts the given character to lowercase.
Converts the given character to lowercase according to the character conversion rules defined by the default local, i.e. the following uppercase letters (ABCDEFGHIJKLMNOPQRSTUVWXYZ) are replaced with respective lowercase letters (abcdefghijklmnopqrstuvwxyz).
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch character to be converted.
Returns
Lowercase version of ch or unmodified ch if no lowercase version is listed in the default locale.
References isupper().
Referenced by bad_input(), good_input(), and towlower().