Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_csin.c File Reference
s_csin.c File Reference
#include <float.h>
#include <openlibm_complex.h>
#include <openlibm_math.h>
Functions
static void cchsh (double x, double *c, double *s)
double complex csin (double complex z)
Function Documentation
cchsh()
static void cchsh (double x, double * c, double * s) static
References cosh(), IEEEl2bits::e, exp(), fabs(), s, and sinh().
Referenced by csin().
csin()
double complex csin (double complex z)
References cchsh(), cimag(), complex, cos(), creal(), I, sin(), w, and z.