Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/w_cabsf.c File Reference
w_cabsf.c File Reference
#include <openlibm_complex.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float cabsf (float complex z)
Function Documentation
cabsf()
OLM_DLLEXPORT float cabsf (float complex z)
References cimagf(), crealf(), hypotf(), and z.
Referenced by clogf(), and cpowf().