Embedded Artistry Framework: src/stdlibs/libc/test/stdlib/stdlib_tests.c File Reference
stdlib_tests.c File Reference
#include "stdlib_tests.h"
#include <stdlib.h>
#include <tests.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Functions
int abs_tests (void)
int atof_tests (void)
int atoi_tests (void)
int atol_tests (void)
int atoll_tests (void)
int bsearch_tests (void)
int calloc_tests (void)
int div_tests (void)
int heapsort_r_tests (void)
int heapsort_tests (void)
int imaxabs_tests (void)
int imaxdiv_tests (void)
int labs_tests (void)
int ldiv_tests (void)
int llabs_tests (void)
int lldiv_tests (void)
int qsort_r_tests (void)
int qsort_tests (void)
int rand_tests (void)
int realloc_tests (void)
int strtod_tests (void)
int strtof_tests (void)
int strtol_tests (void)
int strtoll_tests (void)
int strtoul_tests (void)
int strtoull_tests (void)
int stdlib_tests (void)
Function Documentation
abs_tests()
int abs_tests (void)
Referenced by stdlib_tests().
atof_tests()
int atof_tests (void)
Referenced by stdlib_tests().
atoi_tests()
int atoi_tests (void)
Referenced by stdlib_tests().
atol_tests()
int atol_tests (void)
Referenced by stdlib_tests().
atoll_tests()
int atoll_tests (void)
Referenced by stdlib_tests().
bsearch_tests()
int bsearch_tests (void)
Referenced by stdlib_tests().
calloc_tests()
int calloc_tests (void)
Referenced by stdlib_tests().
div_tests()
int div_tests (void)
Referenced by stdlib_tests().
heapsort_r_tests()
int heapsort_r_tests (void)
Referenced by stdlib_tests().
heapsort_tests()
int heapsort_tests (void)
Referenced by stdlib_tests().
imaxabs_tests()
int imaxabs_tests (void)
Referenced by stdlib_tests().
imaxdiv_tests()
int imaxdiv_tests (void)
Referenced by stdlib_tests().
labs_tests()
int labs_tests (void)
Referenced by stdlib_tests().
ldiv_tests()
int ldiv_tests (void)
Referenced by stdlib_tests().
llabs_tests()
int llabs_tests (void)
Referenced by stdlib_tests().
lldiv_tests()
int lldiv_tests (void)
Referenced by stdlib_tests().
qsort_r_tests()
int qsort_r_tests (void)
Referenced by stdlib_tests().
qsort_tests()
int qsort_tests (void)
Referenced by stdlib_tests().
rand_tests()
int rand_tests (void)
Referenced by stdlib_tests().
realloc_tests()
int realloc_tests (void)
Referenced by stdlib_tests().
stdlib_tests()
int stdlib_tests (void)
References abs_tests(), atof_tests(), atoi_tests(), atol_tests(), atoll_tests(), bsearch_tests(), calloc_tests(), div_tests(), heapsort_r_tests(), heapsort_tests(), imaxabs_tests(), imaxdiv_tests(), labs_tests(), ldiv_tests(), llabs_tests(), lldiv_tests(), qsort_r_tests(), qsort_tests(), rand_tests(), realloc_tests(), strtod_tests(), strtof_tests(), strtol_tests(), strtoll_tests(), strtoul_tests(), and strtoull_tests().
Referenced by main().
strtod_tests()
int strtod_tests (void)
Referenced by stdlib_tests().
strtof_tests()
int strtof_tests (void)
Referenced by stdlib_tests().
strtol_tests()
int strtol_tests (void)
Referenced by stdlib_tests().
strtoll_tests()
int strtoll_tests (void)
Referenced by stdlib_tests().
strtoul_tests()
int strtoul_tests (void)
Referenced by stdlib_tests().
strtoull_tests()
int strtoull_tests (void)
Referenced by stdlib_tests().