Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/k_expf.c File Reference
k_expf.c File Reference
#include "cdefs-compat.h"
#include <openlibm_complex.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
static float __frexp_expf (float x, int *expt)
OLM_DLLEXPORT float __ldexp_expf (float x, int expt)
OLM_DLLEXPORT float complex __ldexp_cexpf (float complex z, int expt)
Variables
static const u_int32_t k = 235
static const float kln2 = 162.88958740F
Function Documentation
__frexp_expf()
static float __frexp_expf (float x, int * expt) static
References expf(), GET_FLOAT_WORD, k, kln2, and SET_FLOAT_WORD.
Referenced by __ldexp_cexpf(), and __ldexp_expf().
__ldexp_cexpf()
OLM_DLLEXPORT float complex __ldexp_cexpf (float complex z, int expt)
References __frexp_expf(), cimagf(), CMPLXF(), cosf(), crealf(), SET_FLOAT_WORD, sinf(), and z.
Referenced by ccoshf(), cexpf(), and csinhf().
__ldexp_expf()
OLM_DLLEXPORT float __ldexp_expf (float x, int expt)
References __frexp_expf(), and SET_FLOAT_WORD.
Referenced by __ieee754_coshf(), and __ieee754_sinhf().
Variable Documentation
k
const u_int32_t k = 235 static
Referenced by __frexp_expf().
kln2
const float kln2 = 162.88958740F static
Referenced by __frexp_expf().