Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_lrint.c File Reference
s_lrint.c File Reference
#include "cdefs-compat.h"
#include <openlibm_fenv.h>
#include <openlibm_math.h>
#include "math_private.h"
Macros
#define type double
#define roundit rint
#define dtype long
#define fn lrint
Functions
OLM_DLLEXPORT dtype fn (type x)
Macro Definition Documentation
dtype
#define dtype long
fn
#define fn lrint
roundit
#define roundit rint
type
#define type double
Function Documentation
fn()
OLM_DLLEXPORT dtype fn (type x)
References dtype, FE_INEXACT, FE_INVALID, feclearexcept(), feholdexcept(), fetestexcept(), feupdateenv(), and roundit.