Embedded Artistry libc: src/ctype/isalnum.c File Reference
isalnum.c File Reference
#include <ctype.h>
Functions
int isalnum (int c)
Function Documentation
isalnum()
int isalnum (int c)
Definition at line 5 of file isalnum.c.
References isalpha(), and isdigit().
Referenced by ispunct().
 {
     return isalpha(c) || isdigit(c);
 }