Embedded Artistry Framework: src/stdlibs/libc/test/stdlib/heapsort_r.c File Reference
heapsort_r.c File Reference
#include "stdlib_tests.h"
#include <stdlib.h>
#include <string.h>
#include <test/test.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Functions
static int scmp (void *thunk, const void *a, const void *b)
static int icmp (void *thunk, const void *a, const void *b)
static int ccmp (void *thunk, const void *a, const void *b)
static int cmp64 (void *thunk, const void *a, const void *b)
static void heapsort_r_string_test (void **state)
static void heapsort_r_int_test (void **state)
static void char_test (const char *a, const char *a_sorted, void **state)
static void heapsort_r_char_test (void **state)
static void uint64_gen (uint64_t *p, uint64_t *p_sorted, size_t num)
static void uint64_test (uint64_t *a, uint64_t *a_sorted, size_t len, void **state)
static void heapsort_r_uint64_test (void **state)
int heapsort_r_tests (void)
Variables
static const char * s []
static const char * s_sorted []
static int n []
static int n_sorted []
Function Documentation
ccmp()
static int ccmp (void * thunk, const void * a, const void * b) static
References a, and b.
Referenced by char_test().
char_test()
static void char_test (const char * a, const char * a_sorted, void ** state) static
References a, ccmp(), free(), heapsort_r(), malloc(), memcmp(), NULL, p, strcpy(), strlen(), and thunk.
Referenced by heapsort_r_char_test().
cmp64()
static int cmp64 (void * thunk, const void * a, const void * b) static
References a, and b.
Referenced by uint64_test().
heapsort_r_char_test()
static void heapsort_r_char_test (void ** state) static
References char_test().
Referenced by heapsort_r_tests().
heapsort_r_int_test()
static void heapsort_r_int_test (void ** state) static
References heapsort_r(), icmp(), n, n_sorted, NULL, and thunk.
Referenced by heapsort_r_tests().
heapsort_r_string_test()
static void heapsort_r_string_test (void ** state) static
References heapsort_r(), NULL, s, s_sorted, scmp(), strcmp(), and thunk.
Referenced by heapsort_r_tests().
heapsort_r_tests()
int heapsort_r_tests (void)
References heapsort_r_char_test(), heapsort_r_int_test(), heapsort_r_string_test(), heapsort_r_tests(), heapsort_r_uint64_test(), and NULL.
Referenced by heapsort_r_tests(), and stdlib_tests().
heapsort_r_uint64_test()
static void heapsort_r_uint64_test (void ** state) static
References p, uint64_gen(), and uint64_test().
Referenced by heapsort_r_tests().
icmp()
static int icmp (void * thunk, const void * a, const void * b) static
References a, and b.
Referenced by heapsort_r_int_test().
scmp()
static int scmp (void * thunk, const void * a, const void * b) static
References a, b, and strcmp().
Referenced by heapsort_r_string_test().
uint64_gen()
static void uint64_gen (uint64_t * p, uint64_t * p_sorted, size_t num) static
References memcpy(), p, r, test_randn(), test_randseed(), and test_shuffle().
Referenced by heapsort_r_uint64_test().
uint64_test()
static void uint64_test (uint64_t * a, uint64_t * a_sorted, size_t len, void ** state) static
References a, cmp64(), heapsort_r(), NULL, and thunk.
Referenced by heapsort_r_uint64_test().
Variable Documentation
n
int n[] static
Initial value:
= {879045, 394,  99405644, 33434, 232323, 4334, 5454,  343,
                  45545,  454,  324,      22,   34344,  233,     45345, 343,
                  848405, 3434, 3434344,  3535,  93994,  2230404, 4334}
Referenced by heapsort_r_int_test().
n_sorted
int n_sorted[] static
Initial value:
= {22,  233,    324,    343,    343,     394,    454,    3434,
                         3535,  4334,   4334,   5454,   33434,   34344,   45345,   45545,
                         93994, 232323, 848405, 879045, 2230404, 3434344, 99405644}
Referenced by heapsort_r_int_test().
s
const char* s[] static
Initial value:
= {"Bob",   "Alice", "John",   "Ceres",   "Helga",   "Drepper", "Emeralda",
                          "Zoran",  "Momo",  "Frank",  "Pema",  "Xavier",  "Yeva",  "Gedun",
                          "Irina",  "Nono",  "Wiener", "Vincent", "Tsering", "Karnica", "Lulu",
                          "Quincy", "Osama", "Riley",  "Ursula",  "Sam"}
Referenced by heapsort_r_string_test().
s_sorted
const char* s_sorted[] static
Initial value:
= {
    "Alice", "Bob",     "Ceres",  "Drepper", "Emeralda", "Frank",  "Gedun", "Helga",  "Irina",
    "John",  "Karnica", "Lulu",   "Momo",   "Nono",  "Osama",  "Pema",  "Quincy", "Riley",
    "Sam",   "Tsering", "Ursula", "Vincent", "Wiener",   "Xavier", "Yeva",  "Zoran"}
Referenced by heapsort_r_string_test().