Embedded Artistry Framework: src/stdlibs/libc/test/stdlib/stdlib_tests.h File Reference
stdlib_tests.h File Reference
Functions
int abs_tests (void)
int atof_tests (void)
int atoi_tests (void)
int atol_tests (void)
int atoll_tests (void)
int bsearch_tests (void)
int calloc_tests (void)
int div_tests (void)
int heapsort_r_tests (void)
int heapsort_tests (void)
int imaxabs_tests (void)
int imaxdiv_tests (void)
int labs_tests (void)
int ldiv_tests (void)
int llabs_tests (void)
int lldiv_tests (void)
int qsort_r_tests (void)
int qsort_tests (void)
int rand_tests (void)
int realloc_tests (void)
int strtod_tests (void)
int strtof_tests (void)
int strtol_tests (void)
int strtoll_tests (void)
int strtoul_tests (void)
int strtoull_tests (void)
Function Documentation
abs_tests()
int abs_tests (void)
References abs_test(), abs_tests(), and NULL.
Referenced by abs_tests().
atof_tests()
int atof_tests (void)
References atof_test(), atof_tests(), and NULL.
Referenced by atof_tests().
atoi_tests()
int atoi_tests (void)
References atoi_test(), atoi_tests(), and NULL.
Referenced by atoi_tests().
atol_tests()
int atol_tests (void)
References atol_test(), atol_tests(), and NULL.
Referenced by atol_tests().
atoll_tests()
int atoll_tests (void)
References atoll_test(), atoll_tests(), and NULL.
Referenced by atoll_tests().
bsearch_tests()
int bsearch_tests (void)
References bsearch_test(), bsearch_tests(), and NULL.
Referenced by bsearch_tests().
calloc_tests()
int calloc_tests (void)
References calloc_test(), calloc_tests(), and NULL.
Referenced by calloc_tests().
div_tests()
int div_tests (void)
References div_test(), div_tests(), and NULL.
Referenced by div_tests().
heapsort_r_tests()
int heapsort_r_tests (void)
References heapsort_r_char_test(), heapsort_r_int_test(), heapsort_r_string_test(), heapsort_r_tests(), heapsort_r_uint64_test(), and NULL.
Referenced by heapsort_r_tests().
heapsort_tests()
int heapsort_tests (void)
References heapsort_char_test(), heapsort_int_test(), heapsort_string_test(), heapsort_tests(), heapsort_uint64_test(), and NULL.
Referenced by heapsort_tests().
imaxabs_tests()
int imaxabs_tests (void)
References imaxabs_test(), imaxabs_tests(), and NULL.
Referenced by imaxabs_tests().
imaxdiv_tests()
int imaxdiv_tests (void)
References imaxdiv_test(), imaxdiv_tests(), and NULL.
Referenced by imaxdiv_tests().
labs_tests()
int labs_tests (void)
References labs_test(), labs_tests(), and NULL.
Referenced by labs_tests().
ldiv_tests()
int ldiv_tests (void)
References ldiv_test(), ldiv_tests(), and NULL.
Referenced by ldiv_tests().
llabs_tests()
int llabs_tests (void)
References llabs_test(), llabs_tests(), and NULL.
Referenced by llabs_tests().
lldiv_tests()
int lldiv_tests (void)
References lldiv_test(), lldiv_tests(), and NULL.
Referenced by lldiv_tests().
qsort_r_tests()
int qsort_r_tests (void)
References NULL, qsort_r_char_test(), qsort_r_int_test(), qsort_r_string_test(), qsort_r_tests(), and qsort_r_uint64_test().
Referenced by qsort_r_tests().
qsort_tests()
int qsort_tests (void)
References NULL, qsort_char_test(), qsort_int_test(), qsort_string_test(), qsort_tests(), and qsort_uint64_test().
Referenced by qsort_tests().
rand_tests()
int rand_tests (void)
References NULL, rand_test(), and rand_tests().
Referenced by rand_tests().
realloc_tests()
int realloc_tests (void)
References NULL, realloc_test(), and realloc_tests().
Referenced by realloc_tests().
strtod_tests()
int strtod_tests (void)
References NULL, and strtod_test().
strtof_tests()
int strtof_tests (void)
References NULL, and strtof_test().
strtol_tests()
int strtol_tests (void)
References NULL, and strtol_test().
strtoll_tests()
int strtoll_tests (void)
References NULL, and strtoll_test().
strtoul_tests()
int strtoul_tests (void)
References NULL, and strtoul_test().
strtoull_tests()
int strtoull_tests (void)
References NULL, and strtoull_test().