Embedded Artistry Framework: src/stdlibs/libc/test/string/memset.c File Reference
memset.c File Reference
#include "string_tests.h"
#include <string.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Macros
#define N 400
Functions
static char * aligned (void *p)
static void test_align (int align, size_t len)
static void memset_aligned_test (void **state)
static void check_input_ (char c, void **state)
static void check_input (void **state)
int memset_tests (void)
Variables
static char buf [N]
static char buf2 [N]
Macro Definition Documentation
N
#define N 400
Function Documentation
aligned()
static char* aligned (void * p) static
References p.
Referenced by test_align().
check_input()
static void check_input (void ** state) static
References check_input_(), and INT_MAX.
Referenced by memset_tests().
check_input_()
static void check_input_ (char c, void ** state) static
References buf, and memset().
Referenced by check_input().
memset_aligned_test()
static void memset_aligned_test (void ** state) static
References test_align().
Referenced by memset_tests().
memset_tests()
int memset_tests (void)
References check_input(), memset_aligned_test(), memset_tests(), and NULL.
Referenced by memset_tests(), and string_tests().
test_align()
static void test_align (int align, size_t len) static
References aligned(), buf, buf2, memset(), N, p, and s.
Referenced by memset_aligned_test().
Variable Documentation
buf
char buf[N] static
Referenced by check_input_(), and test_align().
buf2
char buf2[N] static
Referenced by test_align().