Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_asinh.c File Reference
s_asinh.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double asinh (double x)
Variables
static const double one = 1.00000000000000000000e+00
static const double ln2 = 6.93147180559945286227e-01
static const double huge = 1.00000000000000000000e+300
Function Documentation
asinh()
OLM_DLLEXPORT double asinh (double x)
References __ieee754_log(), __ieee754_sqrt(), fabs(), GET_HIGH_WORD, huge, ln2, log1p(), one, t, and w.
Referenced by asinh_test().
Variable Documentation
huge
const double huge = 1.00000000000000000000e+300 static
Referenced by asinh().
ln2
const double ln2 = 6.93147180559945286227e-01 static
Referenced by asinh().
one
const double one = 1.00000000000000000000e+00 static
Referenced by asinh().