Embedded Artistry libc: src/ctype/isupper.c File Reference
isupper.c File Reference
#include <ctype.h>
Functions
int isupper (int c)
Checks if the given character is an uppercase character.
Function Documentation
isupper()
int isupper (int ch)
Checks if the given character is an uppercase character.
Checks if the given character is an uppercase character using the default local. isupper returns true only for the uppercase letters (ABCDEFGHIJKLMNOPQRSTUVWXYZ). If isupper returns true, it is guaranteed that
See also
iscntrl,
isdigit,
ispunct,
isspace will return false for the same character in the same default locale.
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is an uppercase letter, zero otherwise.
Definition at line 5 of file isupper.c.
 {
     return (unsigned)c - 'A' < 26;
 }
Referenced by strtol(), strtoll(), strtoul(), and tolower().