Embedded Artistry Framework: src/stdlibs/libc/printf/test/test_suite.cpp File Reference
test_suite.cpp File Reference
#include "catch.hpp"
#include <string.h>
#include <math.h>
#include "../printf.h"
#include "../printf.c"
Classes
struct test::out_fct_wrap_type
Namespaces
test
Macros
#define CATCH_CONFIG_MAIN
Typedefs
typedef __builtin_va_list test::va_list
typedef __builtin_va_list test::__isoc_va_list
typedef long test::ptrdiff_t
typedef unsigned long test::size_t
typedef long test::ssize_t
typedef _Bool test::bool
Expands to _Bool.
typedef short test::int16_t
typedef int test::int32_t
typedef long long test::int64_t
typedef signed char test::int8_t
typedef unsigned short test::uint16_t
typedef unsigned int test::uint32_t
typedef unsigned long long test::uint64_t
typedef unsigned char test::uint8_t
typedef int8_t test::int_least8_t
typedef int16_t test::int_least16_t
typedef int32_t test::int_least32_t
typedef int64_t test::int_least64_t
typedef uint8_t test::uint_least8_t
typedef uint16_t test::uint_least16_t
typedef uint32_t test::uint_least32_t
typedef uint64_t test::uint_least64_t
typedef int8_t test::int_fast8_t
typedef int32_t test::int_fast16_t
typedef int32_t test::int_fast32_t
typedef int64_t test::int_fast64_t
typedef uint8_t test::uint_fast8_t
typedef uint32_t test::uint_fast16_t
typedef uint32_t test::uint_fast32_t
typedef uint64_t test::uint_fast64_t
typedef long test::intptr_t
typedef unsigned long test::uintptr_t
typedef long int test::intmax_t
typedef unsigned long long test::uintmax_t
typedef void(* test::out_fct_type) (char character, void *buffer, size_t idx, size_t maxlen)
Functions
void test::_putchar (char character)
Output a character to a custom device like UART, used by the printf() function This function is declared here only.
int test::printf_ (const char *format,...)
int test::sprintf_ (char *buffer, const char *format,...)
int test::snprintf_ (char *buffer, size_t count, const char *format,...)
int test::vsnprintf_ (char *buffer, size_t count, const char *format, va_list va)
int test::fctprintf (void(*out)(char character, void *arg), void *arg, const char *format,...)
printf with output function You may use this as dynamic alternative to printf() with its fixed _putchar() output
int test::vprintf_ (const char *format, va_list va)
static void test::_out_buffer (char character, void *buffer, size_t idx, size_t maxlen)
static void test::_out_null (char character, void *buffer, size_t idx, size_t maxlen)
static void test::_out_char (char character, void *buffer, size_t idx, size_t maxlen)
static void test::_out_fct (char character, void *buffer, size_t idx, size_t maxlen)
static unsigned int test::_strnlen_s (const char *str, size_t maxsize)
static bool test::_is_digit (char ch)
static unsigned int test::_atoi (const char **str)
static size_t test::_ntoa_format (out_fct_type out, char *buffer, size_t idx, size_t maxlen, char *buf, size_t len, bool negative, unsigned int base, unsigned int prec, unsigned int width, unsigned int flags)
static size_t test::_ntoa_long (out_fct_type out, char *buffer, size_t idx, size_t maxlen, unsigned long value, bool negative, unsigned long base, unsigned int prec, unsigned int width, unsigned int flags)
static size_t test::_ntoa_long_long (out_fct_type out, char *buffer, size_t idx, size_t maxlen, unsigned long long value, bool negative, unsigned long long base, unsigned int prec, unsigned int width, unsigned int flags)
static size_t test::_ftoa (out_fct_type out, char *buffer, size_t idx, size_t maxlen, double value, unsigned int prec, unsigned int width, unsigned int flags)
static int test::_vsnprintf (out_fct_type out, char *buffer, const size_t maxlen, const char *format, va_list va)
void _out_fct (char character, void *arg)
TEST_CASE ("printf", "[]")
TEST_CASE ("fctprintf", "[]")
TEST_CASE ("snprintf", "[]")
static void vsnprintf_builder_1 (char *buffer,...)
static void vsnprintf_builder_3 (char *buffer,...)
TEST_CASE ("vsnprintf", "[]")
TEST_CASE ("space flag", "[]")
TEST_CASE ("+ flag", "[]")
TEST_CASE ("0 flag", "[]")
TEST_CASE ("- flag", "[]")
TEST_CASE ("# flag", "[]")
TEST_CASE ("specifier", "[]")
TEST_CASE ("width", "[]")
TEST_CASE ("width 20", "[]")
TEST_CASE ("width *20", "[]")
TEST_CASE ("width -20", "[]")
TEST_CASE ("width 0-20", "[]")
TEST_CASE ("padding 20", "[]")
TEST_CASE ("padding .20", "[]")
TEST_CASE ("padding #020", "[]")
TEST_CASE ("padding #20", "[]")
TEST_CASE ("padding 20.5", "[]")
TEST_CASE ("padding neg numbers", "[]")
TEST_CASE ("float padding neg numbers", "[]")
TEST_CASE ("length", "[]")
TEST_CASE ("float", "[]")
TEST_CASE ("types", "[]")
TEST_CASE ("pointer", "[]")
TEST_CASE ("unknown flag", "[]")
TEST_CASE ("string length", "[]")
TEST_CASE ("buffer length", "[]")
TEST_CASE ("ret value", "[]")
TEST_CASE ("misc", "[]")
Variables
static char printf_buffer [100]
static size_t printf_idx = 0U
Macro Definition Documentation
CATCH_CONFIG_MAIN
#define CATCH_CONFIG_MAIN
Function Documentation
_out_fct()
void _out_fct (char character, void * arg)
TEST_CASE() [1/31]
TEST_CASE ("printf" , "" [])
TEST_CASE() [2/31]
TEST_CASE ("fctprintf" , "" [])
TEST_CASE() [3/31]
TEST_CASE ("snprintf" , "" [])
References snprintf, and strcmp().
TEST_CASE() [4/31]
TEST_CASE ("vsnprintf" , "" [])
TEST_CASE() [5/31]
TEST_CASE ("space flag" , "" [])
TEST_CASE() [6/31]
TEST_CASE ("+ flag" , "" [])
TEST_CASE() [7/31]
TEST_CASE ("0 flag" , "" [])
TEST_CASE() [8/31]
TEST_CASE ("- flag" , "" [])
References sprintf, and strcmp().
TEST_CASE() [9/31]
TEST_CASE ("# flag" , "" [])
TEST_CASE() [10/31]
TEST_CASE ("specifier" , "" [])
References sprintf, and strcmp().
TEST_CASE() [11/31]
TEST_CASE ("width" , "" [])
References sprintf, and strcmp().
TEST_CASE() [12/31]
TEST_CASE ("width 20" , "" [])
References sprintf, and strcmp().
TEST_CASE() [13/31]
TEST_CASE ("width *20" , "" [])
References sprintf, and strcmp().
TEST_CASE() [14/31]
TEST_CASE ("width -20" , "" [])
References sprintf, and strcmp().
TEST_CASE() [15/31]
TEST_CASE ("width 0-20" , "" [])
References sprintf, and strcmp().
TEST_CASE() [16/31]
TEST_CASE ("padding 20" , "" [])
References sprintf, and strcmp().
TEST_CASE() [17/31]
TEST_CASE ("padding .20" , "" [])
References sprintf, and strcmp().
TEST_CASE() [18/31]
TEST_CASE ("padding #020" , "" [])
TEST_CASE() [19/31]
TEST_CASE ("padding #20" , "" [])
References sprintf, and strcmp().
TEST_CASE() [20/31]
TEST_CASE ("padding 20.5" , "" [])
References sprintf, and strcmp().
TEST_CASE() [21/31]
TEST_CASE ("padding neg numbers" , "" [])
References sprintf, and strcmp().
TEST_CASE() [22/31]
TEST_CASE ("float padding neg numbers" , "" [])
References sprintf, and strcmp().
TEST_CASE() [23/31]
TEST_CASE ("length" , "" [])
References sprintf, and strcmp().
TEST_CASE() [24/31]
TEST_CASE ("float" , "" [])
References NAN, sprintf, and strcmp().
TEST_CASE() [25/31]
TEST_CASE ("types" , "" [])
References sprintf, strcmp(), and UL.
TEST_CASE() [26/31]
TEST_CASE ("pointer" , "" [])
References sprintf, and strcmp().
TEST_CASE() [27/31]
TEST_CASE ("unknown flag" , "" [])
References sprintf, and strcmp().
TEST_CASE() [28/31]
TEST_CASE ("string length" , "" [])
References sprintf, and strcmp().
TEST_CASE() [29/31]
TEST_CASE ("buffer length" , "" [])
References snprintf, and strcmp().
TEST_CASE() [30/31]
TEST_CASE ("ret value" , "" [])
References snprintf, strcmp(), and strlen().
TEST_CASE() [31/31]
TEST_CASE ("misc" , "" [])
References sprintf, and strcmp().
vsnprintf_builder_1()
static void vsnprintf_builder_1 (char * buffer, ...) static
vsnprintf_builder_3()
static void vsnprintf_builder_3 (char * buffer, ...) static
Variable Documentation
printf_buffer
char printf_buffer[100] static
printf_idx
size_t printf_idx = 0U static