Embedded Artistry Framework: nRFGPIOTranslator Class Reference
nRFGPIOTranslator Class Reference
Translation class which handles nRF GPIO Configuration.
#include <gpio_helper.hpp>
Static Public Member Functions
static void configure_output (uint8_t port, uint8_t pin) noexcept
static void configure_input (uint8_t port, uint8_t pin, uint8_t pull_config) noexcept
static void configure_default (uint8_t port, uint8_t pin) noexcept
static void configure_i2c (uint8_t port, uint8_t pin) noexcept
static void set (uint8_t port, uint8_t pin) noexcept
static void clear (uint8_t port, uint8_t pin) noexcept
Private Member Functions
nRFGPIOTranslator ()=default
This class can't be instantiated.
~nRFGPIOTranslator ()=default
Detailed Description
Translation class which handles nRF GPIO Configuration.
This represents a bridge pattern: the implementation of the GPIO functions is separated from the main interfaces (nRFGPIOOutput, nRFGPIOInput, etc.).
The GPIO function implementations are isolated from this header because we do not want to make the nRF headers accessible from the rest of the system.
This class cannot be directly instantiated.
Constructor & Destructor Documentation
nRFGPIOTranslator()
nRFGPIOTranslator::nRFGPIOTranslator () private default
This class can't be instantiated.
~nRFGPIOTranslator()
nRFGPIOTranslator::~nRFGPIOTranslator () private default
Member Function Documentation
clear()
void nRFGPIOTranslator::clear (uint8_t port, uint8_t pin) static noexcept
References portDecode(), UINT32_C, and embutil::volatile_store().
Referenced by nRFGPIOOutput< 0, 13 >::set().
configure_default()
void nRFGPIOTranslator::configure_default (uint8_t port, uint8_t pin) static noexcept
References configure().
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::stop_(), nRFGPIOOutput< 0, 13 >::stop_(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::stop_().
configure_i2c()
void nRFGPIOTranslator::configure_i2c (uint8_t port, uint8_t pin) static noexcept
References configure().
Referenced by nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::start_(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::start_().
configure_input()
void nRFGPIOTranslator::configure_input (uint8_t port, uint8_t pin, uint8_t pull_config) static noexcept
References configure().
configure_output()
void nRFGPIOTranslator::configure_output (uint8_t port, uint8_t pin) static noexcept
References configure().
Referenced by nRFGPIOOutput< 0, 13 >::start_().
set()
void nRFGPIOTranslator::set (uint8_t port, uint8_t pin) static noexcept
References portDecode(), UINT32_C, and embutil::volatile_store().
Referenced by nRFGPIOOutput< 0, 13 >::set().
The documentation for this class was generated from the following files:
src/processors/arm/nordic/drivers/helpers/gpio_helper.hpp
src/processors/arm/nordic/drivers/helpers/gpio_helper.cpp