Embedded Artistry libc: src/string/strdup.c File Reference
strdup.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
Functions
char * strdup (const char *str)
Duplicate the passed in string str.
Function Documentation
strdup()
char* strdup (const char * str)
Duplicate the passed in string str.
Returns a pointer to a new string which is a duplicate of the string str. Memory for the new string is obtained with malloc(3), and can be freed with free(3).
Parameters
str a pointer to a string to duplicate
Returns
a pointer to the duplicated string on success. NULL if insufficient memory was available, with errno set to indicate cause of error.
Definition at line 42 of file strdup.c.
 {
     char* copy = NULL;
     if(str)
     {
         size_t len = strlen(str) + 1;
         if((copy = malloc(len)) == NULL)
         {
             return (NULL);
         }
         memcpy(copy, str, len);
     }
     return (copy);
 }
References malloc(), memcpy(), NULL, and strlen().