Embedded Artistry Framework: src/processors/arm/nordic/nrf52840/nrf52840.cpp File Reference
nrf52840.cpp File Reference
#include "nrf52840.hpp"
#include <cassert>
#include <processor_architecture.hpp>
#include <processor_includes.hpp>
Functions
void _putchar (char c)
Output a character to a custom device like UART, used by the printf() function This function is declared here only.
static void setWEN () noexcept
static void setREN () noexcept
static void setVOUT (uint32_t setting) noexcept
static bool checkVOUT (uint32_t setting) noexcept
Variables
static const uint32_t CPU_FREQ_MHZ = UINT32_C(64)
Function Documentation
_putchar()
void _putchar (char character)
Output a character to a custom device like UART, used by the printf() function This function is declared here only.
You have to write your custom implementation somewhere
Parameters
character Character to output
Referenced by _out_char(), embvm::CircularLogBufferLogger< TBufferSize, TLock >::dump(), and putchar().
checkVOUT()
static bool checkVOUT (uint32_t setting) inline static noexcept
Referenced by nRF52840::highVoltageMode().
setREN()
static void setREN () inline static noexcept
Referenced by setVOUT().
setVOUT()
static void setVOUT (uint32_t setting) inline static noexcept
References setREN(), setWEN(), and ARMCommonArch::systemReset().
Referenced by nRF52840::highVoltageMode().
setWEN()
static void setWEN () inline static noexcept
Referenced by setVOUT().
Variable Documentation
CPU_FREQ_MHZ
const uint32_t CPU_FREQ_MHZ = UINT32_C(64) static
Referenced by nRF52840::spin().