Embedded Artistry libc: src/wchar/towlower.c File Reference
towlower.c File Reference
#include "_towcase.h"
#include <ctype.h>
Functions
wint_t towlower (wint_t wc)
Function Documentation
towlower()
wint_t towlower (wint_t wc)
Definition at line 4 of file towlower.c.
 {
     return (wint_t)(wc < 128 ? tolower((int)wc) : __towcase((wchar_t)wc, 1));
 }
References __towcase(), and tolower().
Referenced by iswupper(), and towctrans().