Embedded Artistry Framework: embvm::i2c::activeMaster< TQueueSize, TLock, TCond > Class Template Reference
embvm::i2c::activeMaster< TQueueSize, TLock, TCond > Class Template Reference final
#include <active_i2c.hpp>
Public Types
using cb_t = stdext::inplace_function< void(i2c::op_t, i2c::status)>
Represents the type of the callback operation.
using sweep_list_t = etl::vector< uint8_t, 128 >
using sweep_cb_t = stdext::inplace_function< void(void)>
Public Member Functions
activeMaster (embvm::i2c::master &m)
~activeMaster ()=default
void process_ (ao_storage pair)
virtual void configure (i2c::baud baud, i2c::pullups pull=i2c::pullups::external)
Configure the I2C bus.
i2c::state state ()
Check the I2C bus status.
i2c::pullups pullups (i2c::pullups pullups)
Configure pull-ups.
i2c::pullups pullups ()
Check the pull-up configuration.
void sweep (sweep_list_t &found_list, const sweep_cb_t &cb)
Perform an I2C bus sweep to identify active devices.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
size_t queuedCount () noexcept
Get the number of operations in the queue.
bool enqueue (embvm::i2c::ao_storage t)
Add an operation to the queue.
void shutdown ()
Shutdown the active object.
Static Public Member Functions
static constexpr embvm::DriverType type ()
I2C Driver Type ID.
Protected Attributes
i2c::pullups pullups_ = i2c::pullups::external
Tracks the active pull-up configuration.
i2c::state state_ = i2c::state::idle
Tracks the status of the I2C bus.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Types
using ao_base = embutil::activeObject< activeMaster, ao_storage, TQueueSize, TLock, TCond >
Private Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void configure_ (embvm::i2c::pullups pullup) final
Configure the I2C bus for operation.
embvm::i2c::status transfer_ (const embvm::i2c::op_t &op, const embvm::i2c::master::cb_t &cb) final
embvm::i2c::baud baudrate_ (embvm::i2c::baud baud) final
embvm::i2c::pullups setPullups_ (embvm::i2c::pullups pullups) final
Configure pull-ups.
Private Attributes
embvm::i2c::master & m_
Member Typedef Documentation
ao_base
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> using embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::ao_base = embutil::activeObject<activeMaster, ao_storage, TQueueSize, TLock, TCond> private
cb_t
using embvm::i2c::master::cb_t = stdext::inplace_function<void(i2c::op_t, i2c::status)> inherited
Represents the type of the callback operation.
sweep_cb_t
using embvm::i2c::master::sweep_cb_t = stdext::inplace_function<void(void)> inherited
sweep_list_t
using embvm::i2c::master::sweep_list_t = etl::vector<uint8_t, 128> inherited
Constructor & Destructor Documentation
activeMaster()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::activeMaster (embvm::i2c::master & m) inline explicit
~activeMaster()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::~activeMaster () default
Member Function Documentation
baudrate_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::i2c::baud embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::baudrate_ (embvm::i2c::baud baud) inline final private virtual
Implements embvm::i2c::master.
configure()
virtual void embvm::i2c::master::configure (i2c::baud baud, i2c::pullups pull = i2c::pullups::external) inline virtual inherited
Configure the I2C bus.
Configures the I2C bus for operation and sets the target baud rate and pull-ups.
Derived classes must implement the configure_() function to set up the target hardware.
Parameters
baud The target baudrate (as an i2c::baud enumeration rather than integral Hz). TODO: Tolerance - allowed relative tolerance for the resulting baudrate
pull The pullup setting, which defaults to external pull-ups (in hardware).
References embvm::i2c::master::configure_(), and embvm::i2c::master::pullups().
Referenced by embvm::i2c::activeMaster< 128 >::configure_(), and FWDemoSimulatorHWPlatform::init_().
configure_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> void embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::configure_ (embvm::i2c::pullups pullups) inline final private virtual
Configure the I2C bus for operation.
This function is implemented by the derived class. It is responsible for configuring the target hardware for operation.
Parameters
pullups The target pull-up configuration.
Implements embvm::i2c::master.
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
enqueue()
bool embutil::activeObject< embvm::i2c::activeMaster< TQueueSize, TLock, TCond > , embvm::i2c::ao_storage , TQueueSize, TLock, TCond >::enqueue (embvm::i2c::ao_storage t) inline inherited
Add an operation to the queue.
This function can be called directly, or by functions internal to the activeObject. For example, the "transfer" API enqueues transfer operations.
Parameters
t The operation data object to enqueue for later processing.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
process_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> void embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::process_ (ao_storage pair) inline
pullups() [1/2]
i2c::pullups embvm::i2c::master::pullups (i2c::pullups pullups) inline inherited
Configure pull-ups.
Parameters
pullups The target pull-up setting.
Returns
The configured pull-up setting.
References embvm::i2c::master::pullups_, and embvm::i2c::master::setPullups_().
Referenced by embvm::i2c::activeMaster< 128 >::setPullups_().
pullups() [2/2]
i2c::pullups embvm::i2c::master::pullups () inline inherited
Check the pull-up configuration.
Returns
The configured pull-up setting.
References embvm::i2c::master::pullups_.
Referenced by embvm::i2c::master::configure(), test::i2cTestDriver::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), test::i2cTestDriver::setPullups_(), nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >::setPullups_(), and nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >::setPullups_().
queuedCount()
size_t embutil::activeObject< embvm::i2c::activeMaster< TQueueSize, TLock, TCond > , embvm::i2c::ao_storage , TQueueSize, TLock, TCond >::queuedCount () inline noexcept inherited
Get the number of operations in the queue.
Returns
the number of queued operations.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
setPullups_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::i2c::pullups embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::setPullups_ (embvm::i2c::pullups pullups) inline final private virtual
Configure pull-ups.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the requested pullup setting.
Parameters
pullups The target pull-up setting.
Returns
The configured pull-up setting.
Implements embvm::i2c::master.
shutdown()
void embutil::activeObject< embvm::i2c::activeMaster< TQueueSize, TLock, TCond > , embvm::i2c::ao_storage , TQueueSize, TLock, TCond >::shutdown () inline inherited
Shutdown the active object.
Call this function in the parent class destructor to stop the AO thread operation before destroying the parent class. This will prevent memory access problems due to race conidtions during destruction.
The shutdown process is permanent and cannot be reversed without recreating the object.
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> void embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::start_ () inline final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::i2c::master.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
state()
i2c::state embvm::i2c::master::state () inline inherited
Check the I2C bus status.
Returns
the status of the I2C bus as an i2c::state enumeration.
References embvm::i2c::master::state_.
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> void embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::stop_ () inline final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::i2c::master.
sweep()
void embvm::i2c::master::sweep (sweep_list_t & found_list, const sweep_cb_t & cb) inherited
Perform an I2C bus sweep to identify active devices.
The sweep function pings all I2C addresses. Devices which ACK are stored in a list and returned via callback.
Parameters
[in,out] found_list Caller's memory which will contain the successfully found ping addresses
[in] cb The callback which will be called to indicate that the sweep is complete. After the cb is called, found_list is valid and can be used by the caller.
References embvm::i2c::op_t::address, embvm::i2c::busy, embvm::i2c::ok, embvm::i2c::op_t::op, and embvm::i2c::ping.
transfer_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::i2c::status embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::transfer_ (const embvm::i2c::op_t & op, const embvm::i2c::master::cb_t & cb) inline final private virtual
Implements embvm::i2c::master.
type()
static constexpr embvm::DriverType embvm::i2c::master::type () inline static inherited
I2C Driver Type ID.
Returns
I2C type ID.
References embvm::I2C.
Member Data Documentation
m_
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::i2c::master& embvm::i2c::activeMaster< TQueueSize, TLock, TCond >::m_ private
Referenced by embvm::i2c::activeMaster< 128 >::baudrate_(), embvm::i2c::activeMaster< 128 >::configure_(), embvm::i2c::activeMaster< 128 >::process_(), embvm::i2c::activeMaster< 128 >::setPullups_(), embvm::i2c::activeMaster< 128 >::start_(), and embvm::i2c::activeMaster< 128 >::stop_().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
pullups_
i2c::pullups embvm::i2c::master::pullups_ = i2c::pullups::external protected inherited
Tracks the active pull-up configuration.
Referenced by embvm::i2c::master::pullups().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
state_
i2c::state embvm::i2c::master::state_ = i2c::state::idle protected inherited
Tracks the status of the I2C bus.
Referenced by embvm::i2c::master::state().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
The documentation for this class was generated from the following file:
src/core/driver/active_i2c.hpp