Embedded Artistry Framework: Framework Driver Infrastructure
Framework Driver Infrastructure
Framework Core Components
Driver base classes & definitions.
Namespaces
embvm::clk
Definitions, functions, and classes related to clock devices.
embvm::comm
Definitions, functions, and classes related to communication busses.
embvm::gpio
Definitions, functions, and classes related to GPIO devices.
embvm
Embedded framework core interfaces, classes, and definitions.
embvm::i2c
Definitions, functions, and classes related to I2C communication bus devices.
embvm::led
Definitions, functions, and classes related to LED devices.
embvm::spi
Definitions, functions, and classes related to SPI communication bus devices.
embvm::tof
Definitions, functions, and classes related to Time-of-Flight sensors.
embvm::timer
Definitions, functions, and classes related to Timer devices.
Classes
class embvm::basicDisplay
This class provides an interface for a basic 2-color display device.
class embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >
Base class interface for communication bus driver types (SPI, I2C, etc.).
class embvm::DriverBase
Virtual base class for framework drivers.
class embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >
DriverRegistry base class.
Typedefs
template<typename TLockType = embutil::nop_lock>
using embvm::DynamicDriverRegistry = DriverRegistry< 0, 0, TLockType >
Declare a DriverRegistry that uses dynamic memory allocation.
template<const size_t TMaxSize = 32, const size_t TReturnSize = 4, typename TLockType = embutil::nop_lock>
using embvm::StaticDriverRegistry = DriverRegistry< TMaxSize, TReturnSize, TLockType >
Declare a DriverRegistry that uses static memory allocation.
using embvm::DriverType_t = uint32_t
Driver type used by framework interfaces.
Enumerations
enum embvm::DriverType {
embvm::Undefined = 0, embvm::GPIO, embvm::HARDWARE_TIMER, embvm::I2C,
embvm::LED, embvm::SPI, embvm::SYSTEM_CLOCK, embvm::TIME_OF_FLIGHT,
embvm::SOFTWARE_TIMER, embvm::TIMER, embvm::BASIC_DISPLAY, embvm::DRIVER_EXTENSION_START
}
Default framework driver type definitions.
Detailed Description
Driver base classes & definitions.
Class Documentation
embvm::basicDisplay
class embvm::basicDisplay
This class provides an interface for a basic 2-color display device.
The basicDisplay class defines common interfaces for basic 2-color display drivers, which can be LED or OLED.
Define an basic display driver
To create a basic display driver, derive from the basicDisplay object:
class ssd1306 final : public basicDisplay
{ ... };
Derived classes must implement the following functions:
pixel(coord_t x, coord_t y, color c, mode m), which enables the other draw functions
display()
clear()
invert()
contrast()
cursor()
screenWidth()
screenHeight()
scrollRight()
scrollLeft()
scrollVertRight()
scrollVertLeft()
scrollStop()
flipVertical()
flipHorizontal()
Derived classes must also implement pure virtual embvm::DriverBase functions:
start_()
stop_()
Turning on a dispay should be handled in the start_() function, and turning off the display should be handled in the stop_() function.
Using a basic display
The display is turned on by calling start(), and turned off by calling stop().
Most display functions update the screen buffer, which is the representation of the display buffer contents in local memory.
snprintf(tof_string_, 32, "ToF Range: %u mm\n", v);
screen0.printString(0, 0, tof_string_);
screen0.printString(0, 32, tof_mode_string_);
Changes to the screen buffer are not written to the display's hardware buffer until the display() function is called.
screen0.display();
The screen buffer can be updated incrementally. If clearing the entire buffer is desired, call the clear() function.
screen0.clear();
Public Types
enum invert : uint8_t { invert::normal = 0, invert::invert }
Display color inversion options.
enum mode : uint8_t { mode::normal = 0, mode::XOR }
Set the drawing mode, if supported by the driver.
enum color : uint8_t { color::black = 0, color::white }
Basic displays have two pixel colors: black and white.
using coord_t = uint8_t
Coordinate representation type.
Public Member Functions
virtual void clear () noexcept=0
Clear the screen contents.
virtual void display () noexcept=0
Flush the screen buffer contents to the hardware display buffer.
virtual void invert (invert inv) noexcept=0
Invert the display color.
virtual void contrast (uint8_t contrast) noexcept=0
Set contrast.
virtual void cursor (coord_t x, coord_t y) noexcept=0
Set the cusor within the screen buffer.
void pixel (coord_t x, coord_t y) noexcept
Draw a pixel in the screen buffer.
virtual void pixel (coord_t x, coord_t y, color c, mode m) noexcept=0
Draw a pixel with a specific color and mode.
void line (coord_t x0, coord_t y0, coord_t x1, coord_t y1) noexcept
Draw a line.
virtual void line (coord_t x0, coord_t y0, coord_t x1, coord_t y1, color c, mode m) noexcept=0
Draw a line with a specific color and mode.
void lineH (coord_t x, coord_t y, uint8_t width) noexcept
Draw a horizontal line.
void lineH (coord_t x, coord_t y, uint8_t width, color c, mode m) noexcept
Draw a horizontal line with a specific color and mode.
void lineV (coord_t x, coord_t y, uint8_t height) noexcept
Draw a vertical line.
void lineV (coord_t x, coord_t y, uint8_t height, color c, mode m) noexcept
Draw a vertical line with a specific color and mode.
void rect (coord_t x, coord_t y, uint8_t width, uint8_t height) noexcept
Draw a rectangle.
virtual void rect (coord_t x, coord_t y, uint8_t width, uint8_t height, color c, mode m) noexcept=0
Draw a rectangle with a specific color and mode.
void rectFill (coord_t x, coord_t y, uint8_t width, uint8_t height) noexcept
Draw a filled rectangle.
virtual void rectFill (coord_t x, coord_t y, uint8_t width, uint8_t height, color c, mode m) noexcept=0
Draw a filled rectangle with a specific color and mode.
void circle (coord_t x, coord_t y, uint8_t radius) noexcept
Draw a circle.
virtual void circle (coord_t x, coord_t y, uint8_t radius, color c, mode m) noexcept=0
Draw a circle with a specific color and mode.
void circleFill (coord_t x, coord_t y, uint8_t radius) noexcept
Draw a filled circle.
virtual void circleFill (coord_t x, coord_t y, uint8_t radius, color c, mode m) noexcept=0
Draw a filled circle with a specific color and mode.
void drawChar (coord_t x, coord_t y, uint8_t character) noexcept
Draw an ASCII character.
virtual void putchar (uint8_t c) noexcept=0
Print a character on the display.
virtual void drawChar (coord_t x, coord_t y, uint8_t character, color c, mode m) noexcept=0
Draw an ASCII character with a specific color and mode.
void printString (coord_t x, coord_t y, const char *str) noexcept
Print a string on the display.
void printString (coord_t x, coord_t y, const char *str, size_t length) noexcept
Print a string on the display.
virtual void drawBitmap (uint8_t *bitmap) noexcept=0
Replace the screen buffer with a bitmap.
virtual uint8_t screenWidth () const noexcept=0
Check the screen width.
virtual uint8_t screenHeight () const noexcept=0
Check the screen height.
void drawColor (color c) noexcept
Set color.
virtual void drawMode (mode m) noexcept
Set draw mode.
virtual void scrollRight (coord_t start, coord_t stop) noexcept=0
Enable right scrolling.
virtual void scrollLeft (coord_t start, coord_t stop) noexcept=0
Enable left scrolling.
virtual void scrollVertRight (coord_t start, coord_t stop) noexcept=0
virtual void scrollVertLeft (coord_t start, coord_t stop) noexcept=0
virtual void scrollStop () noexcept=0
Stop scrolling.
virtual void flipVertical (bool flip) noexcept=0
Vertical flip.
virtual void flipHorizontal (bool flip) noexcept=0
Horizontal flip.
void start () noexcept
Start the driver.
void stop () noexcept
Stop the driver.
void restart () noexcept
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type () noexcept
Basic Display Driver Type ID.
Protected Member Functions
basicDisplay () noexcept
Default constructor.
basicDisplay (const char *name) noexcept
Construct an basicDisplay with a name.
basicDisplay (const std::string &name) noexcept
Construct an basicDisplay with a std::string name.
basicDisplay (const std::string_view &name) noexcept
Construct an basicDisplay with a std::string_view name.
void start_ () noexcept override=0
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () noexcept override=0
Derived classes override the start_ method to control driver-specific startup behavior.
~basicDisplay () noexcept override
Default destructor.
Protected Attributes
mode mode_ = mode::normal
The current display mode setting.
color color_ = color::black
The current display color setting.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Member Typedef Documentation
coord_t
using embvm::basicDisplay::coord_t = uint8_t
Coordinate representation type.
Member Enumeration Documentation
color
enum embvm::basicDisplay::color : uint8_t strong
Basic displays have two pixel colors: black and white.
Enumerator
black
white
invert
enum embvm::basicDisplay::invert : uint8_t strong
Display color inversion options.
Enumerator
normal
Use the default display color setting.
invert
Invert the display colors.
mode
enum embvm::basicDisplay::mode : uint8_t strong
Set the drawing mode, if supported by the driver.
Enumerator
normal
Either sets or clears a pixel as requested, overwriting the value set in the screen buffer.
XOR
The pixel output in the screen buffer will be an XOR of the current value and the input value.
Constructor & Destructor Documentation
basicDisplay() [1/4]
embvm::basicDisplay::basicDisplay () inline protected noexcept
Default constructor.
Initializes the basicDisplay instance with a generic name.
basicDisplay() [2/4]
embvm::basicDisplay::basicDisplay (const char * name) inline protected noexcept
Construct an basicDisplay with a name.
Initializes the basicDisplay instance with a name.
Parameters
name The name of the display instance. basicDisplay() uses a std::string_view, so a std::string must remain valid
basicDisplay() [3/4]
embvm::basicDisplay::basicDisplay (const std::string & name) inline protected noexcept
Construct an basicDisplay with a std::string name.
Initializes the basicDisplay instance with a name.
Parameters
name The name of the display instance. basicDisplay() uses a std::string_view, so the std::string must remain valid
basicDisplay() [4/4]
embvm::basicDisplay::basicDisplay (const std::string_view & name) inline protected noexcept
Construct an basicDisplay with a std::string_view name.
Initializes the basicDisplay instance with a name.
Parameters
name The name of the display instance.
~basicDisplay()
embvm::basicDisplay::~basicDisplay () override protected default noexcept
Default destructor.
Member Function Documentation
circle() [1/2]
void embvm::basicDisplay::circle (coord_t x, coord_t y, uint8_t radius) inline noexcept
Draw a circle.
Draw a circle with center (x,y) and the specified radius using the configured color setting and draw mode in the screen buffer. Only the boundary of the circle will be drawn.
Parameters
x X-coorindate for the center of the circle.
y Y-coordinate for the center of the circle.
radius The radius of the circle.
References color_, and mode_.
circle() [2/2]
virtual void embvm::basicDisplay::circle (coord_t x, coord_t y, uint8_t radius, color c, mode m) pure virtual noexcept
Draw a circle with a specific color and mode.
Draw a circle with center (x,y) and the specified radius using a specific color setting and draw mode in the screen buffer. Only the boundary of the circle will be drawn.
Parameters
x X-coorindate for the center of the circle.
y Y-coordinate for the center of the circle.
radius The radius of the circle.
c Pixel color.
m Mode used to update the screen buffer.
Implemented in embdrv::ssd1306.
circleFill() [1/2]
void embvm::basicDisplay::circleFill (coord_t x, coord_t y, uint8_t radius) inline noexcept
Draw a filled circle.
Draw a filled circle with center (x,y) and the specified radius using the configured color setting and draw mode in the screen buffer. The interior of the circle will be filled with the specified color setting.
Parameters
x X-coorindate for the center of the circle.
y Y-coordinate for the center of the circle.
radius The radius of the circle.
References color_, and mode_.
circleFill() [2/2]
virtual void embvm::basicDisplay::circleFill (coord_t x, coord_t y, uint8_t radius, color c, mode m) pure virtual noexcept
Draw a filled circle with a specific color and mode.
Draw a filled circle with center (x,y) and the specified radius using a specific color setting and draw mode in the screen buffer. The interior of the circle will be filled with the specified color setting.
Parameters
x X-coorindate for the center of the circle.
y Y-coordinate for the center of the circle.
radius The radius of the circle.
c Pixel color.
m Mode used to update the screen buffer.
Implemented in embdrv::ssd1306.
clear()
virtual void embvm::basicDisplay::clear () pure virtual noexcept
Clear the screen contents.
Implemented in embdrv::ssd1306.
contrast()
virtual void embvm::basicDisplay::contrast (uint8_t contrast) pure virtual noexcept
Set contrast.
Parameters
contrast Target display contrast value, ranging from 0 to 255.
Implemented in embdrv::ssd1306.
cursor()
virtual void embvm::basicDisplay::cursor (coord_t x, coord_t y) pure virtual noexcept
Set the cusor within the screen buffer.
Contents in the screen buffer are not modified by setting the cursor position.
Parameters
x X-coordinate of the cursor.
y Y-coordinate of the cursor.
Implemented in embdrv::ssd1306.
Referenced by printString().
display()
virtual void embvm::basicDisplay::display () pure virtual noexcept
Flush the screen buffer contents to the hardware display buffer.
Implemented in embdrv::ssd1306.
drawBitmap()
virtual void embvm::basicDisplay::drawBitmap (uint8_t * bitmap) pure virtual noexcept
Replace the screen buffer with a bitmap.
Supply a bitmap to write to the screen buffer. If the size of the bitmap is less than the size of the screen buffer, the remainder of the screen buffer will not be modified.
Parameters
bitmap Bitmap array which will be used to overwrite the screen buffer.
Implemented in embdrv::ssd1306.
drawChar() [1/2]
void embvm::basicDisplay::drawChar (coord_t x, coord_t y, uint8_t character) inline noexcept
Draw an ASCII character.
Draw an ASCII character using the configured color and draw mode with the upper left corner of the character located at (x,y).
Parameters
x X-coordinate representing the top-left of the character.
y Y-coordinate representing the top-left of the character.
character the ASCII character to draw. Must be present in the font file. If the requested character is not present, nothing will be drawn on the screen buffer.
References color_, and mode_.
drawChar() [2/2]
virtual void embvm::basicDisplay::drawChar (coord_t x, coord_t y, uint8_t character, color c, mode m) pure virtual noexcept
Draw an ASCII character with a specific color and mode.
Draw an ASCII character using a specific color and draw mode with the upper left corner of the character located at (x,y).
Parameters
x X-coordinate representing the top-left of the character.
y Y-coordinate representing the top-left of the character.
character the ASCII character to draw. Must be present in the font file. If the requested character is not present, nothing will be drawn on the screen buffer.
c Pixel color.
m Mode used to update the screen buffer.
Implemented in embdrv::ssd1306.
drawColor()
void embvm::basicDisplay::drawColor (color c) inline noexcept
Set color.
Set the current draw's color. Only WHITE and BLACK available.
Parameters
c The desired draw color setting.
References assert, black, color_, and white.
Referenced by embdrv::ssd1306::start_().
drawMode()
virtual void embvm::basicDisplay::drawMode (mode m) inline virtual noexcept
Set draw mode.
Parameters
m Desired draw mode: NORM or XOR.
References assert, mode_, normal, and XOR.
Referenced by embdrv::ssd1306::start_().
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
flipHorizontal()
virtual void embvm::basicDisplay::flipHorizontal (bool flip) pure virtual noexcept
Horizontal flip.
Flip the graphics on the display horizontally.
Parameters
flip True enables horizontal flip, false disables horizontal flip.
Implemented in embdrv::ssd1306.
flipVertical()
virtual void embvm::basicDisplay::flipVertical (bool flip) pure virtual noexcept
Vertical flip.
Flip the graphics on the display vertically.
Parameters
flip True enables vertical flip, false disables vertical flip.
Implemented in embdrv::ssd1306.
invert()
virtual void embvm::basicDisplay::invert (invert inv) pure virtual noexcept
Invert the display color.
The WHITE color of the display will turn to BLACK and the BLACK will turn to WHITE.
Parameters
inv invert::invert uses color inversion, invert::normal uses the display standard.
Implemented in embdrv::ssd1306.
line() [1/2]
void embvm::basicDisplay::line (coord_t x0, coord_t y0, coord_t x1, coord_t y1) inline noexcept
Draw a line.
Draw a line using the configured color setting and draw mode from (x0,y0) to (x1,y1) of the screen buffer.
Parameters
x0 X-coordinate where the line originates.
y0 Y-coordinate where the line originates.
x1 X-coordinate where the line terminates.
y1 Y-coordinate where the line terminates.
References color_, mode_, and x0.
Referenced by lineH(), and lineV().
line() [2/2]
virtual void embvm::basicDisplay::line (coord_t x0, coord_t y0, coord_t x1, coord_t y1, color c, mode m) pure virtual noexcept
Draw a line with a specific color and mode.
Draw line with a specific color setting and draw mode from (x0,y0) to (x1,y1) of the screen buffer.
Parameters
x0 X-coordinate where the line originates.
y0 Y-coordinate where the line originates.
x1 X-coordinate where the line terminates.
y1 Y-coordinate where the line terminates.
c Pixel color.
m Mode used to update the screen buffer.
Implemented in embdrv::ssd1306.
lineH() [1/2]
void embvm::basicDisplay::lineH (coord_t x, coord_t y, uint8_t width) inline noexcept
Draw a horizontal line.
Draw a horizontal line using the configured color setting and draw mode from (x,y) to (x+width,y) in the screen buffer.
Parameters
x X-coordinate where the line originates.
y Y-coordinate where the line originates.
width Length of the line, in pixels. The line will terminate at coordinate (x+width, y).
References color_, and mode_.
lineH() [2/2]
void embvm::basicDisplay::lineH (coord_t x, coord_t y, uint8_t width, color c, mode m) inline noexcept
Draw a horizontal line with a specific color and mode.
Draw a horizontal line with a specific color setting and draw mode from (x,y) to (x+width,y) in the screen buffer.
Parameters
x X-coordinate where the line originates.
y Y-coordinate where the line originates.
width Length of the line, in pixels. The line will terminate at coordinate (x+width, y).
c Pixel color.
m Mode used to update the screen buffer.
References line().
lineV() [1/2]
void embvm::basicDisplay::lineV (coord_t x, coord_t y, uint8_t height) inline noexcept
Draw a vertical line.
Draw a vertical line using the configured color setting and draw mode from (x,y) to (x,y+height) in the screen buffer.
Parameters
x X-coordinate where the line originates.
y Y-coordinate where the line originates.
height Length of the line, in pixels. The line will terminate at coordinate (x, y+height).
References color_, and mode_.
lineV() [2/2]
void embvm::basicDisplay::lineV (coord_t x, coord_t y, uint8_t height, color c, mode m) inline noexcept
Draw a vertical line with a specific color and mode.
Draw a vertical line using a specific color setting and draw mode from (x,y) to (x,y+height) in the screen buffer.
Parameters
x X-coordinate where the line originates.
y Y-coordinate where the line originates.
height Length of the line, in pixels. The line will terminate at coordinate (x, y+height).
c Pixel color.
m Mode used to update the screen buffer.
References line().
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
pixel() [1/2]
void embvm::basicDisplay::pixel (coord_t x, coord_t y) inline noexcept
Draw a pixel in the screen buffer.
Draw pixel using the configured color setting and draw mode in the screen buffer's x,y position.
Parameters
x X-coordinate of the pixel.
y Y-coordinate of the pixel.
References color_, and mode_.
pixel() [2/2]
virtual void embvm::basicDisplay::pixel (coord_t x, coord_t y, color c, mode m) pure virtual noexcept
Draw a pixel with a specific color and mode.
Draw a pixel at position (x,y) with a specific color setting and draw mode.
Parameters
x X-coordinate of the pixel.
y Y-coordinate of the pixel.
c Pixel color.
m Mode used to update the screen buffer.
Implemented in embdrv::ssd1306.
printString() [1/2]
void embvm::basicDisplay::printString (coord_t x, coord_t y, const char * str) inline noexcept
Print a string on the display.
Parameters
x The x-coordinate to start the string.
y The y-coordinate to start the string.
str The string to print to the display.
References strlen().
printString() [2/2]
void embvm::basicDisplay::printString (coord_t x, coord_t y, const char * str, size_t length) inline noexcept
Print a string on the display.
Parameters
x The x-coordinate to start the string.
y The y-coordinate to start the string.
str The string to print to the display.
length The number of characters in str.
References cursor(), length, and putchar().
putchar()
virtual void embvm::basicDisplay::putchar (uint8_t c) pure virtual noexcept
Print a character on the display.
Parameters
c the character to print to the display
Implemented in embdrv::ssd1306.
Referenced by printString().
rect() [1/2]
void embvm::basicDisplay::rect (coord_t x, coord_t y, uint8_t width, uint8_t height) inline noexcept
Draw a rectangle.
Draw a rectangle using the configured color setting and draw mode from (x,y) to (x+width,y+height) in the screen buffer. Only the boundary of the rectangle will be drawn.
Parameters
x X-coordinate where the rectangle originates.
y Y-coordinate where the rectangle originates.
width Width of the rectangle, in pixels. The rectangle width spans from x to x+width.
height Height of the rectangle, in pixels. The rectangle height spans from y + y+height.
References color_, and mode_.
rect() [2/2]
virtual void embvm::basicDisplay::rect (coord_t x, coord_t y, uint8_t width, uint8_t height, color c, mode m) pure virtual noexcept
Draw a rectangle with a specific color and mode.
Draw a rectangle with a specific color setting and draw mode from (x,y) to (x+width,y+height) in the screen buffer. Only the boundary of the rectangle will be drawn.
Parameters
x X-coordinate where the rectangle originates.
y Y-coordinate where the rectangle originates.
width Width of the rectangle, in pixels. The rectangle width spans from x to x+width.
height Height of the rectangle, in pixels. The rectangle height spans from y + y+height.
c Pixel color.
m Mode used to update the screen buffer.
Implemented in embdrv::ssd1306.
rectFill() [1/2]
void embvm::basicDisplay::rectFill (coord_t x, coord_t y, uint8_t width, uint8_t height) inline noexcept
Draw a filled rectangle.
Draw a filled rectangle using the configured color setting and draw mode from (x,y) to (x+width,y+height) in the screen buffer. The interior of the rectangle will be filled with the configured color setting.
Parameters
x X-coordinate where the rectangle originates.
y Y-coordinate where the rectangle originates.
width Width of the rectangle, in pixels. The rectangle width spans from x to x+width.
height Height of the rectangle, in pixels. The rectangle height spans from y + y+height.
References color_, and mode_.
rectFill() [2/2]
virtual void embvm::basicDisplay::rectFill (coord_t x, coord_t y, uint8_t width, uint8_t height, color c, mode m) pure virtual noexcept
Draw a filled rectangle with a specific color and mode.
Draw a filled rectangle using a specific color setting and draw mode from (x,y) to (x+width,y+height) in the screen buffer. The interior of the rectangle will be filled with the specified color setting.
Parameters
x X-coordinate where the rectangle originates.
y Y-coordinate where the rectangle originates.
width Width of the rectangle, in pixels. The rectangle width spans from x to x+width.
height Height of the rectangle, in pixels. The rectangle height spans from y + y+height.
c Pixel color.
m Mode used to update the screen buffer.
Implemented in embdrv::ssd1306.
restart()
void embvm::DriverBase::restart () inline noexcept inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
screenHeight()
virtual uint8_t embvm::basicDisplay::screenHeight () const pure virtual noexcept
Check the screen height.
The drived class must implement this function.
Returns
The height of the screen in pixels.
Implemented in embdrv::ssd1306.
screenWidth()
virtual uint8_t embvm::basicDisplay::screenWidth () const pure virtual noexcept
Check the screen width.
The drived class must implement this function.
Returns
The width of the screen in pixels.
Implemented in embdrv::ssd1306.
scrollLeft()
virtual void embvm::basicDisplay::scrollLeft (coord_t start, coord_t stop) pure virtual noexcept
Enable left scrolling.
Set row start to row stop on the display to scroll left.
Parameters
start The start row index.
stop The stop row index.
Precondition
Scrolling is not enabled, stop < start.
Postcondition
The display is scrolling to the left.
Implemented in embdrv::ssd1306.
scrollRight()
virtual void embvm::basicDisplay::scrollRight (coord_t start, coord_t stop) pure virtual noexcept
Enable right scrolling.
Set row start to row stop on the display to scroll right.
Parameters
start The start row index.
stop The stop row index.
Precondition
Scrolling is not enabled, start < stop.
Postcondition
The display is scrolling to the right.
Implemented in embdrv::ssd1306.
scrollStop()
virtual void embvm::basicDisplay::scrollStop () pure virtual noexcept
Stop scrolling.
Stop the scrolling of graphics on the display.
Implemented in embdrv::ssd1306.
scrollVertLeft()
virtual void embvm::basicDisplay::scrollVertLeft (coord_t start, coord_t stop) pure virtual noexcept
Implemented in embdrv::ssd1306.
scrollVertRight()
virtual void embvm::basicDisplay::scrollVertRight (coord_t start, coord_t stop) pure virtual noexcept
Implemented in embdrv::ssd1306.
start()
void embvm::DriverBase::start () inline noexcept inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void embvm::basicDisplay::start_ () override protected pure virtual noexcept
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in embdrv::ssd1306.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline noexcept inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void embvm::basicDisplay::stop_ () override protected pure virtual noexcept
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in embdrv::ssd1306.
type()
static constexpr embvm::DriverType embvm::basicDisplay::type () inline static noexcept
Basic Display Driver Type ID.
Returns
Basic Display type ID.
References embvm::BASIC_DISPLAY.
Member Data Documentation
color_
color embvm::basicDisplay::color_ = color::black protected
The current display color setting.
Referenced by circle(), circleFill(), drawChar(), drawColor(), line(), lineH(), lineV(), pixel(), rect(), and rectFill().
mode_
mode embvm::basicDisplay::mode_ = mode::normal protected
The current display mode setting.
Referenced by circle(), circleFill(), drawChar(), drawMode(), line(), lineH(), lineV(), pixel(), rect(), and rectFill().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
embvm::commBus
class embvm::commBus
template<typename TOperation, typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status>
class embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >
Base class interface for communication bus driver types (SPI, I2C, etc.).
This class defines common interfaces and types for communication bus drivers, such as SPI, I2C, I2S.
Implementing a Communication Bus Driver
To implement your own communication bus driver, derive from this class using template parameters that represent the implementation of your bus type. For example:
  namespace spi {
    static constexpr size_t SPI_MASTER_REQD_STATIC_FUNCTION_SIZE = (sizeof(void*) * 12);
   using baud_t = uint32_t;
   struct op_t
    {
        uint8_t* tx_buffer;
        uint8_t* rx_buffer;
        size_t length;
        comm::status status;
    };
    using cb_t = stdext::inplace_function<void(op_t)>;
   using commBus = commBus<embvm::spi::op_t, embvm::spi::baud_t,
*embvm::spi::SPI_MASTER_REQD_STATIC_FUNCTION_SIZE>;
  };
  class embvm::spi::master : public embvm::DriverBase, public embvm::spi::commBus
  { ... }
Derived classes must implement the following pure virtual functions to complete comm bus behavior:
transfer_(), which initiates a bus transfer
baudrate_(), which configures the baudrate
Derived classes may implement additional functionality, especially related to initialization and configuration of the bus. However, all exchange of data should be handled within the transfer() function.
Note: Derived classes are responsible for calling callback() once a transfer is completed.
Using a Communication Bus Driver
Communication busses are based around the concept of a transfer(). A transfer operation is defined using the TOperation type.
To initiate a transfer, you need to define a TOperation object. Because the framework uses asynchronous transfers, a callback function (cb_t) is also needed so the completion and result of the transfer can be reported. The callback can be any functor.
The TOperation object and the callback function are passed into transfer(). When the operation completes, the derived driver will invoke callback() with a copy of the TOperation object and th resulting status.
Communication bus drivers are non-copyable and non-moveable.
Template Parameters
TOperation Defines the operation type for the bus. This type represents the data that will be enqueued by the driver and used to carry out a transfer. The operation is also passed to a callback upon completion of a transfer. The operation type is often a structure, for example: ``` struct op_t { uint8_t* tx_buffer; uint8_t* rx_buffer; size_t length; comm::status status; }; ```
TBaudrate The baudrate storage type. The baudrate type defaults to uint32_t. Baudrate can be set to another type, such as embvm::i2c::baud, which is an enum class.
TDispatchFunctorSize The storage space for statically-allocated functor objects. This template parameter is used in the TDispatchFunctor declaration. This can be made larger if required by the storage needs for your status/callback type.
TStatus The comm bus status type. Defaults to comm::status, but can be overridden to support custom bus statuses.
Public Types
using cb_t = stdext::inplace_function< void(TOperation, TStatus)>
Represents the type of the callback operation.
using DispatcherFunc = stdext::inplace_function< void(TDispatchFunctor &&)>
Alias for the dispatcher function's storage type.
Public Member Functions
commBus () noexcept
Default constructor.
commBus (TBaudrate baud) noexcept
Construct the bus with a baudrate.
commBus (TBaudrate baud, DispatcherFunc dispatcher) noexcept
Construct the bus with a baudrate and dispatcher.
commBus (const commBus &)=delete
Deleted copy constructor.
const commBus & operator= (const commBus &)=delete
Deleted copy assignment operator.
commBus (commBus &&)=delete
Deleted move constructor.
commBus & operator= (commBus &&)=delete
Deleted move assignment operator.
virtual TStatus transfer (TOperation &op, const cb_t &cb=nullptr) noexcept
Initiate a bus transfer.
TStatus busStatus () const noexcept
Get the current bus status.
TBaudrate baudrate () const noexcept
Get the current baudrate.
TBaudrate baudrate (TBaudrate baud) noexcept
Set a new baudrate.
Protected Member Functions
virtual ~commBus ()=default
Default destructor.
void callback (const TOperation &op, TStatus status, const cb_t &cb) noexcept
Handle callbacks.
virtual TStatus transfer_ (const TOperation &op, const cb_t &callback) noexcept=0
The derived comm class's transfer implementation.
virtual TBaudrate baudrate_ (TBaudrate baud) noexcept=0
The drived comm class's baudrate update implementation.
Protected Attributes
TStatus bus_status_
Stores the current bus status.
TBaudrate baud_
Stores the currently configured baudrate.
const DispatcherFunc dispatcher_
Stores a function which callbacks will be dispatched to.
Private Types
using TDispatchFunctor = stdext::inplace_function< void(), TDispatchFunctorSize >
The functor declaration which will be used in declaring a DispatcherFunc.
Member Typedef Documentation
cb_t
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> using embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::cb_t = stdext::inplace_function<void(TOperation, TStatus)>
Represents the type of the callback operation.
DispatcherFunc
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> using embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::DispatcherFunc = stdext::inplace_function<void(TDispatchFunctor&&)>
Alias for the dispatcher function's storage type.
TDispatchFunctor
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> using embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::TDispatchFunctor = stdext::inplace_function<void(), TDispatchFunctorSize> private
The functor declaration which will be used in declaring a DispatcherFunc.
This represents the statucally-allocated functor that stores a std::bind of the callback, operation, and status.
Constructor & Destructor Documentation
commBus() [1/5]
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::commBus () inline noexcept
Default constructor.
Initializes the comm bus status.
References embvm::comm::ok.
commBus() [2/5]
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::commBus (TBaudrate baud) inline explicit noexcept
Construct the bus with a baudrate.
Initializes the comm bus status and sets the baudrate to a default value.
Parameters
baud The default baudrate for the bus.
commBus() [3/5]
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::commBus (TBaudrate baud, DispatcherFunc dispatcher) inline explicit noexcept
Construct the bus with a baudrate and dispatcher.
Initializes the comm bus status and sets the baudrate to a default value. Also sets the dispatcher function, which will forward callbacks to a different thread of control.
Parameters
baud The default baudrate for the bus.
dispatcher The functor which callbacks will be dispatched to. This will often be paired with a dispatch queue. Example:
   embutil::DynamicDispatchQueue<> dispatch;
spi0(115200, dispatch.getBoundDispatch());
commBus() [4/5]
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::commBus (const commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus > &) delete
Deleted copy constructor.
commBus() [5/5]
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::commBus (commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus > &&) delete
Deleted move constructor.
~commBus()
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> virtual embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::~commBus () protected virtual default
Default destructor.
Member Function Documentation
baudrate() [1/2]
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> TBaudrate embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::baudrate () const inline noexcept
Get the current baudrate.
Returns
The currently configured baudrate.
baudrate() [2/2]
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> TBaudrate embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::baudrate (TBaudrate baud) inline noexcept
Set a new baudrate.
Since each comm bus driver is different, the baudrate update request is forwarded to the derived class, which must implement the pure virtual function baudrate_().
TODO: tolerance check
Parameters
baud The new baudrate for the bus.
Returns
The baudrate the bus is configured to use. The returned baudrate may not match the input under the following conditions:
Input baudrate was invalid (no update)
Input baudrate was rounded by the bus driver
baudrate_()
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> virtual TBaudrate embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::baudrate_ (TBaudrate baud) protected pure virtual noexcept
The drived comm class's baudrate update implementation.
Derived classes override this baudrate function to handle baudrate change requests.
Parameters
baud The new baudrate for the bus.
Returns
The baudrate the bus is configured to use. The returned baudrate may not match the input under the following conditions:
Input baudrate was invalid (no update)
Input baudrate was rounded by the bus driver
busStatus()
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> TStatus embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::busStatus () const inline noexcept
Get the current bus status.
Returns
The current bus status.
callback()
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> void embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::callback (const TOperation & op, TStatus status, const cb_t & cb) inline protected noexcept
Handle callbacks.
Invokes callback functions, either by pushing to a dispatch thread or by directly invoking the callback on the same thread of control.
Parameters
op The operation which was completed. This will be passed to the callback.
status The result of the operation.
cb The callback function to invoke.
operator=() [1/2]
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> const commBus& embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::operator= (const commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus > &) delete
Deleted copy assignment operator.
operator=() [2/2]
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> commBus& embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::operator= (commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus > &&) delete
Deleted move assignment operator.
transfer()
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> virtual TStatus embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::transfer (TOperation & op, const cb_t & cb = nullptr) inline virtual noexcept
Initiate a bus transfer.
Initiates a transfer of information across a comm bus. The transfer function should handle read, write, and read-write operations. Other operations may also be supported by derived classes.
The transfer request is forwarded the derived class, which must implement the pure virtual function transfer_().
This call should not block. Transfer requests are asynchronous and are not guaranteed to return immediately with a result.
If the derived driver class returns a status code other than TStatus::enqueued or TStatus::busy, the callback will be immediately invoked. If the operation was enqueued, the final status will be reported when the callback is called.
Parameters
op A bus transfer is defined by an operation (op). The derived class will use the data supplied in the op to configure the bus and transfer the data.
cb Optional callback parameter. When set, the callback will be invoked upon completion of the transfer.
Returns
The status of the bus transfer.
transfer_()
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> virtual TStatus embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::transfer_ (const TOperation & op, const cb_t & callback) protected pure virtual noexcept
The derived comm class's transfer implementation.
Derived classes override this transfer function to handle specific transfer operations for each device.
Callback is passed in for drivers which enqueue operations or use AO model. The base class handles the callback, so there is no need to worry about invoking the callback from a client driver.
Just mark your callback (void)callback if you aren't using it.
To indicate that a transfer has been enqueued for later processing, return TStatus::enqueued
Member Data Documentation
baud_
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> TBaudrate embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::baud_ protected
Stores the currently configured baudrate.
bus_status_
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> TStatus embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::bus_status_ protected
Stores the current bus status.
dispatcher_
template<typename TOperation , typename TBaudrate = uint32_t, size_t TDispatchFunctorSize = sizeof(void*) * 4, typename TStatus = comm::status> const DispatcherFunc embvm::commBus< TOperation, TBaudrate, TDispatchFunctorSize, TStatus >::dispatcher_ protected
Stores a function which callbacks will be dispatched to.
The dispatcher function receives callbacks and ops and executes them on a separate thread of control from the caller of callback().
If no dispatcher is configured by the user, the callback will be executed in the same thread of control.
embvm::DriverBase
class embvm::DriverBase
Virtual base class for framework drivers.
All framework drivers should include this class in their inheritance tree. The DriverBase provides common interfaces which apply to all drivers. Use of the DriverBase class also handles automatic registration/unregistration with the platform's DriverRegistry. Registration/unregistration occurs during construction/destruction.
Derived classes must override the following functions:
start_()
stop_()
Public Member Functions
DriverBase (const DriverBase &)=delete
Deleted copy constructor.
const DriverBase & operator= (const DriverBase &)=delete
Deleted copy assignment operator.
DriverBase (DriverBase &&)=delete
Deleted move constructor.
DriverBase & operator= (DriverBase &&)=delete
Deleted move assignment operator.
void start () noexcept
Start the driver.
void stop () noexcept
Stop the driver.
void restart () noexcept
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Protected Member Functions
DriverBase (const char *name, embvm::DriverType_t c=embvm::DriverType::Undefined) noexcept
Construct a DriverBase with a C-string name.
DriverBase (const std::string &name, embvm::DriverType_t c=embvm::DriverType::Undefined) noexcept
Construct a DriverBase with a std::string name.
DriverBase (const std::string_view &name, embvm::DriverType_t c=embvm::DriverType::Undefined) noexcept
Construct a DriverBase with a std::string_view name.
virtual ~DriverBase () noexcept
Destructor.
virtual void start_ () noexcept=0
Derived classes override the start_ method to control driver-specific startup behavior.
virtual void stop_ () noexcept=0
Derived classes override the start_ method to control driver-specific startup behavior.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Constructor & Destructor Documentation
DriverBase() [1/5]
embvm::DriverBase::DriverBase (const char * name, embvm::DriverType_t c = embvm::DriverType::Undefined) protected noexcept
Construct a DriverBase with a C-string name.
The DriverBase constructor handles automatic registration with the DriverRegistry.
Parameters
name The name of the device driver instance
c The device type
References embvm::VirtualPlatformBase< BlinkyDemoPlatform< THWPlatform, TDriverRegistry >, TDriverRegistry >::registerDriver().
DriverBase() [2/5]
embvm::DriverBase::DriverBase (const std::string & name, embvm::DriverType_t c = embvm::DriverType::Undefined) protected noexcept
Construct a DriverBase with a std::string name.
The DriverBase constructor handles automatic registration with the DriverRegistry
Parameters
name The name of the device driver instance. Note: DriverBase() uses a std::string_view, so the std::string must remain valid
c The device type
References embvm::VirtualPlatformBase< BlinkyDemoPlatform< THWPlatform, TDriverRegistry >, TDriverRegistry >::registerDriver().
DriverBase() [3/5]
embvm::DriverBase::DriverBase (const std::string_view & name, embvm::DriverType_t c = embvm::DriverType::Undefined) protected noexcept
Construct a DriverBase with a std::string_view name.
The DriverBase constructor handles automatic registration with the DriverRegistry
Parameters
name The name of the device driver instance. Note: DriverBase() uses a std::string_view, so the std::string_view must remain valid
c The device type
References embvm::VirtualPlatformBase< BlinkyDemoPlatform< THWPlatform, TDriverRegistry >, TDriverRegistry >::registerDriver().
DriverBase() [4/5]
embvm::DriverBase::DriverBase (const DriverBase &) delete
Deleted copy constructor.
DriverBase() [5/5]
embvm::DriverBase::DriverBase (DriverBase &&) delete
Deleted move constructor.
~DriverBase()
embvm::DriverBase::~DriverBase () protected virtual noexcept
Destructor.
When DriverBase is destructed, the driver is unregistered from the DriverRegistry.
References embvm::VirtualPlatformBase< BlinkyDemoPlatform< THWPlatform, TDriverRegistry >, TDriverRegistry >::unregisterDriver().
Member Function Documentation
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References type_.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept
Increment operator is a no-op, but is used for iterator compatibility.
operator=() [1/2]
const DriverBase& embvm::DriverBase::operator= (const DriverBase &) delete
Deleted copy assignment operator.
operator=() [2/2]
DriverBase& embvm::DriverBase::operator= (DriverBase &&) delete
Deleted move assignment operator.
restart()
void embvm::DriverBase::restart () inline noexcept
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References start(), and stop().
start()
void embvm::DriverBase::start () inline noexcept
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References start_(), and started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), restart(), embvm::timer::Timer::restart(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
virtual void embvm::DriverBase::start_ () protected pure virtual noexcept
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implemented in embvm::basicDisplay, embvm::i2c::master, embvm::gpio::inputOutput< TPull >, embvm::spi::master, embvm::gpio::output, embvm::timer::Timer, embvm::tof::sensor, embvm::gpio::input< TPull >, embvm::gpio::input< embvm::gpio::pull::pullup >, embvm::gpio::input< embvm::gpio::pull::none >, embvm::led::gpio< TActiveHigh >, embdrv::aardvarkAdapter, embdrv::aardvarkGPIOOutput< TPinID >, embdrv::aardvarkGPIOOutput< 5 >, embdrv::vl53l1x, embvm::gpio::base< TDir >, embvm::gpio::base< gpio::direction::in >, embvm::gpio::base< gpio::direction::inout >, embvm::gpio::base< gpio::direction::out >, embvm::led::base, embdrv::ssd1306, embdrv::SimulatorTimer, test::spiTestDriver, embvm::clk::SystemClock, test::i2cTestDriver, embdrv::aardvarkGPIOInput< TPinID, TPull >, embdrv::aardvarkGPIOInput< 3 >, embdrv::aardvarkGPIOInput< 4 >, nRFGPIOOutput< TPort, TPin >, nRFGPIOOutput< 1, 9 >, nRFGPIOOutput< 0, 16 >, nRFGPIOOutput< 0, 8 >, nRFGPIOOutput< 0, 14 >, nRFGPIOOutput< 0, 6 >, nRFGPIOOutput< 0, 15 >, nRFGPIOOutput< 0, 12 >, nRFGPIOOutput< 0, 13 >, embdrv::aardvarkI2CMaster, embdrv::aardvarkSPIMaster, nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >, nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >, embdrv::SimulatorSystemClock, embvm::i2c::activeMaster< TQueueSize, TLock, TCond >, embvm::i2c::activeMaster< 128 >, embvm::spi::activeMaster< TQueueSize, TLock, TCond >, test::TestDriverBase, test::UnitTestGPIOInputWithPullup, nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >, and test::UnitTestGPIOInput.
Referenced by start().
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline noexcept
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References started_, and stop_().
Referenced by restart(), embvm::timer::Timer::restart(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
virtual void embvm::DriverBase::stop_ () protected pure virtual noexcept
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implemented in embvm::basicDisplay, embvm::i2c::master, embvm::gpio::inputOutput< TPull >, embvm::spi::master, embvm::gpio::output, embvm::timer::Timer, embvm::tof::sensor, embvm::gpio::input< TPull >, embvm::gpio::input< embvm::gpio::pull::pullup >, embvm::gpio::input< embvm::gpio::pull::none >, embvm::led::gpio< TActiveHigh >, embdrv::aardvarkGPIOOutput< TPinID >, embdrv::aardvarkGPIOOutput< 5 >, embdrv::aardvarkAdapter, embdrv::vl53l1x, embvm::gpio::base< TDir >, embvm::gpio::base< gpio::direction::in >, embvm::gpio::base< gpio::direction::inout >, embvm::gpio::base< gpio::direction::out >, embvm::led::base, embdrv::ssd1306, embdrv::SimulatorTimer, test::spiTestDriver, embvm::clk::SystemClock, test::i2cTestDriver, embdrv::aardvarkGPIOInput< TPinID, TPull >, embdrv::aardvarkGPIOInput< 3 >, embdrv::aardvarkGPIOInput< 4 >, nRFi2cMaster< TTWIIndex, TSclPin, TSdaPin, TBlocking >, nRFi2cMaster< NordicTWIM0, nRFPinID< 0, 27 >, nRFPinID< 0, 26 > >, nRFGPIOOutput< TPort, TPin >, nRFGPIOOutput< 1, 9 >, nRFGPIOOutput< 0, 16 >, nRFGPIOOutput< 0, 8 >, nRFGPIOOutput< 0, 14 >, nRFGPIOOutput< 0, 6 >, nRFGPIOOutput< 0, 15 >, nRFGPIOOutput< 0, 12 >, nRFGPIOOutput< 0, 13 >, embdrv::aardvarkI2CMaster, embdrv::aardvarkSPIMaster, embdrv::SimulatorSystemClock, embvm::i2c::activeMaster< TQueueSize, TLock, TCond >, embvm::i2c::activeMaster< 128 >, nRF51i2cMaster_Blocking< TTWIIndex, TSclPin, TSdaPin >, embvm::spi::activeMaster< TQueueSize, TLock, TCond >, test::TestDriverBase, test::UnitTestGPIOInputWithPullup, and test::UnitTestGPIOInput.
Referenced by stop().
Member Data Documentation
name_
const std::string_view embvm::DriverBase::name_ protected
Name of the driver instance.
Referenced by name(), and name_cstr().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by start(), started(), and stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected
Type ID of the driver instance.
Referenced by DriverType().
embvm::DriverRegistry
class embvm::DriverRegistry
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock>
class embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >
DriverRegistry base class.
DriverRegistry provides a common DriverRegistry interface that supports both static and dynamic memory allocation styles. Whether dynamic or static memory is used is determined at compile-time by the template arguments.
Two convenience definitions are supplied below: DynamicDriverRegistry and StaticDriverRegistry<> These types should be used to declare DriverRegistry instances for your platform rather than directly using DriverRegistry. They are more expressive and will be easier for readers to understand.
Only one DriverRegistry should be defined for each platform & program.
Template Parameters
TMaxSize specifies the maximum number of drivers that can be stored. A value of '0' indicates that dynamic memory should be used.
TReturnSize specifies the maximum number of drivers that can be returned by find_all() A value of '0' indicates no limit (dynamic memory)
TLockType The type of lock to use with DriverRegistry. Defaults to embutil::nop_lock, which does not perform any actual locking. If you are using this DriverRegistry in a multi-threaded program and are worried about locking, you can change this to another type such as std::mutex or an interrupt_lock.
Public Member Functions
DriverRegistry ()=default
Default constructor.
~DriverRegistry () noexcept=default
Default destructor.
DriverRegistry (const DriverRegistry &)=delete
Deleted copy constructor.
const DriverRegistry & operator= (const DriverRegistry &)=delete
Deleted copy assignment operator.
DriverRegistry (DriverRegistry &&)=delete
Deleted move constructor.
DriverRegistry & operator= (DriverRegistry &&)=delete
Deleted move assignment operator.
size_t count () const noexcept
Get the registered driver count.
size_t capacity () const noexcept
Get the capacity of the registry.
void add (const TKey name, embvm::DriverBase *driver) noexcept
Register a driver.
void remove (const TKey name, embvm::DriverBase *driver) noexcept
Unregister a driver.
auto find (const TKey name) noexcept
Find a driver by name.
auto find (DriverType_t dtype) noexcept
Find a driver by type.
template<class TDriverClass >
auto find () noexcept
Find a driver by type and return casted interface pointer.
template<class TDriverClass >
auto find (const TKey name) noexcept
Find a driver by name and return casted interface pointer.
template<typename TReturn = std::list<embvm::DriverBase*>>
auto find_all (DriverType_t dtype) noexcept -> std::enable_if_t<!TReturnSize, TReturn >
Find all drivers with a given type (dynamic memory).
template<typename TReturn = etl::list<embvm::DriverBase*, TReturnSize>>
auto find_all (DriverType_t dtype) noexcept -> std::enable_if_t<(TReturnSize > 0), TReturn >
Find all drivers with a given type (static memory).
template<class TDriverClass , typename TReturn = std::list<embvm::DriverBase*>>
auto find_all () noexcept -> std::enable_if_t<!TReturnSize, TReturn >
Find all drivers with a given type and return casted interface pointers (dynamic memory).
template<class TDriverClass , typename TReturn = etl::list<embvm::DriverBase*, TReturnSize>>
auto find_all () noexcept -> std::enable_if_t<(TReturnSize > 0), TReturn >
Find all drivers with a given type and return casted interface pointers (static memory).
Private Types
using TKey = const char *
using TListType = typename std::conditional<(TMaxSize==0), embutil::DynamicInstanceList< embvm::DriverBase, TKey >, embutil::StaticInstanceList< embvm::DriverBase, TMaxSize, TKey > >::type
Private Attributes
TListType list_
TLockType lock_
Member Typedef Documentation
TKey
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> using embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::TKey = const char* private
TListType
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> using embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::TListType = typename std::conditional< (TMaxSize == 0), embutil::DynamicInstanceList<embvm::DriverBase, TKey>, embutil::StaticInstanceList<embvm::DriverBase, TMaxSize, TKey> >::type private
Constructor & Destructor Documentation
DriverRegistry() [1/3]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::DriverRegistry () default
Default constructor.
~DriverRegistry()
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::~DriverRegistry () default noexcept
Default destructor.
DriverRegistry() [2/3]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::DriverRegistry (const DriverRegistry< TMaxSize, TReturnSize, TLockType > &) delete
Deleted copy constructor.
DriverRegistry() [3/3]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::DriverRegistry (DriverRegistry< TMaxSize, TReturnSize, TLockType > &&) delete
Deleted move constructor.
Member Function Documentation
add()
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> void embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::add (const TKey name, embvm::DriverBase * driver) inline noexcept
Register a driver.
Adds a driver to the DriverRegistry.
Parameters
name The name of the driver instance being added. Name is used as a key during lookups.
driver Pointer to the embvm::DriverBase object. A pointer is used because there are any number of potential derived classes which will be tracked. To prevent slicing, a pointer to the base class is stored.
References embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_, and embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::lock_.
capacity()
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> size_t embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::capacity () const inline noexcept
Get the capacity of the registry.
The capacity represents the total number of drivers which may be registered.
Returns
the capacity of the driver registry.
References embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_.
count()
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> size_t embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::count () const inline noexcept
Get the registered driver count.
Returns
the number of drivers currently registered.
References embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_.
find() [1/4]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> auto embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find (const TKey name) inline noexcept
Find a driver by name.
Performs a driver lookup by name. If the driver is found, the embvm::DriverBase for that object will be returned to the user. If no driver is found, an empty object will be returned.
If multiple objects are registered with the same name, the first one found will be returned.
Parameters
name The name of the driver instance to search for.
Returns
an type_safe::optional_ref to the embvm::DriverBase object. If the driver was not found, the optional_ref will be empty. The caller must cast to the appropriate type.
References embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_.
find() [2/4]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> auto embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find (DriverType_t dtype) inline noexcept
Find a driver by type.
Performs a driver lookup by type. If the driver is found, the embvm::DriverBase for that object will be returned to the user. If no driver is found, an empty object will be returned.
If multiple objects are registered with the same type, the first one found will be returned.
Parameters
dtype The type of the driver instance to search for.
Returns
an type_safe::optional_ref to the embvm::DriverBase object. If the driver was not found, the optional_ref will be empty.
References dtype, and embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_.
find() [3/4]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> template<class TDriverClass > auto embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find () inline noexcept
Find a driver by type and return casted interface pointer.
Performs a driver lookup by type. If the driver is found, the embvm::DriverBase will be casted to the requested driver interface. If no driver is found, an empty object will be returned.
To perform the lookup, the requested driver classes's type() static member function will be used.
If multiple objects are registered with the same type, the first one found will be returned.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Returns
an type_safe::optional_ref to the embvm::DriverBase object. If the driver was not found, the optional_ref will be empty.
References type.
Referenced by embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find().
find() [4/4]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> template<class TDriverClass > auto embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find (const TKey name) inline noexcept
Find a driver by name and return casted interface pointer.
Performs a driver lookup by name. If the driver is found, the embvm::DriverBase will be casted to the requested driver interface. If no driver is found, an empty object will be returned.
If multiple objects are registered with the same name, the first one found will be returned.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Parameters
name The name of the driver instance to search for.
Returns
an type_safe::optional_ref to the embvm::DriverBase object. If the driver was not found, the optional_ref will be empty.
References embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find().
find_all() [1/4]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> template<typename TReturn = std::list<embvm::DriverBase*>> auto embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find_all (DriverType_t dtype) -> std::enable_if_t<!TReturnSize, TReturn> inline noexcept
Find all drivers with a given type (dynamic memory).
Performs a driver lookup by type and creates a list of all drivers found with the matching type. If no driver is found, an empty list will be returned.
Template Parameters
TReturn The return type provided to the caller. Most users do not need to change the type.
Parameters
dtype The type of the driver instance to search for.
Returns
a TReturn type (default std::list) of pointers to Dembvm::DriverBase objects with the requested driver type. An empty list will be returned if no drivers are found.
References dtype, embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_, and t.
find_all() [2/4]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> template<typename TReturn = etl::list<embvm::DriverBase*, TReturnSize>> auto embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find_all (DriverType_t dtype) -> std::enable_if_t<(TReturnSize > 0), TReturn> inline noexcept
Find all drivers with a given type (static memory).
Performs a driver lookup by type and creates a list of all drivers found with the matching type. If no driver is found, an empty list will be returned.
Template Parameters
TReturn The return type provided to the caller. Most users do not need to change the type.
Parameters
dtype The type of the driver instance to search for.
Returns
a TReturn type (default etl::list) of pointers to Dembvm::DriverBase objects with the requested driver type. An empty list will be returned if no drivers are found.
References dtype, embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_, and t.
find_all() [3/4]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> template<class TDriverClass , typename TReturn = std::list<embvm::DriverBase*>> auto embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find_all () -> std::enable_if_t<!TReturnSize, TReturn> inline noexcept
Find all drivers with a given type and return casted interface pointers (dynamic memory).
Performs a driver lookup by type and creates a list of all drivers found with the matching type. If no driver is found, an empty list will be returned.
To perform the lookup, the requested driver classes's type() static member function will be used.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
TReturn The return type provided to the caller. Most users do not need to change the type.
Returns
a TReturn type (default std::list) of pointers to Dembvm::DriverBase objects with the requested driver type. An empty list will be returned if no drivers are found.
References embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_, t, and type.
find_all() [4/4]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> template<class TDriverClass , typename TReturn = etl::list<embvm::DriverBase*, TReturnSize>> auto embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find_all () -> std::enable_if_t<(TReturnSize > 0), TReturn> inline noexcept
Find all drivers with a given type and return casted interface pointers (static memory).
Performs a driver lookup by type and creates a list of all drivers found with the matching type. If no driver is found, an empty list will be returned.
To perform the lookup, the requested driver classes's type() static member function will be used.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
TReturn The return type provided to the caller. Most users do not need to change the type.
Returns
a TReturn type (default etl::list) of pointers to Dembvm::DriverBase objects with the requested driver type. An empty list will be returned if no drivers are found.
References embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_, t, and type.
operator=() [1/2]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> const DriverRegistry& embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::operator= (const DriverRegistry< TMaxSize, TReturnSize, TLockType > &) delete
Deleted copy assignment operator.
operator=() [2/2]
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> DriverRegistry& embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::operator= (DriverRegistry< TMaxSize, TReturnSize, TLockType > &&) delete
Deleted move assignment operator.
remove()
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> void embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::remove (const TKey name, embvm::DriverBase * driver) inline noexcept
Unregister a driver.
Removes a driver from the DriverRegistry.
Parameters
name The name of the driver instance being removed.
driver Pointer to the embvm::DriverBase object being removed.
References embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_, and embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::lock_.
Member Data Documentation
list_
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> TListType embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::list_ private
Referenced by embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::add(), embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::capacity(), embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::count(), embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find(), embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::find_all(), and embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::remove().
lock_
template<const size_t TMaxSize, const size_t TReturnSize, typename TLockType = embutil::nop_lock> TLockType embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::lock_ private
Referenced by embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::add(), and embvm::DriverRegistry< TMaxSize, TReturnSize, TLockType >::remove().
Typedef Documentation
DriverType_t
using embvm::DriverType_t = typedef uint32_t
Driver type used by framework interfaces.
The driver type ID is stored as a uint32_t rather than a DriverType to work with custom user-defined types. Enforcing a DriverType return value would prevent clients from defining and using their own custom types enums and would create template headaches.
DynamicDriverRegistry
template<typename TLockType = embutil::nop_lock> using embvm::DynamicDriverRegistry = typedef DriverRegistry<0, 0, TLockType>
Declare a DriverRegistry that uses dynamic memory allocation.
A DynamicDriverRegistry utilizes dynamic memory allocation and can grow to the limit that memory allows. This type is useful for host-based simulation platforms, as well as embedded platforms which allow dynamic memory allocation.
Template Parameters
TLockType The type of lock to use with DynamicDriverRegistry. See DriverRegistry for more information.
StaticDriverRegistry
template<const size_t TMaxSize = 32, const size_t TReturnSize = 4, typename TLockType = embutil::nop_lock> using embvm::StaticDriverRegistry = typedef DriverRegistry<TMaxSize, TReturnSize, TLockType>
Declare a DriverRegistry that uses static memory allocation.
The size and memory allocation of the StaticDriverRegistry is known at compile-time. No dynamic memory allocations are used.
In addition, the number of drivers returned by the find_all() function is fixed.
Template Parameters
TMaxSize specifies the maximum number of drivers that can be stored
TReturnSize specifies the maximum number of drivers that can be returned by find_all()
TLockType The type of lock to use with StaticDriverRegistry. See DriverRegistry for more information.
Enumeration Type Documentation
DriverType
enum embvm::DriverType
Default framework driver type definitions.
Default framework driver type definitions. These definitions are defined because the framework provides driver interfaces for these types. Additional types can be defined by clients as needed.
To add your own driver types, create an enum in your project code and use DRIVER_EXTENSION_START as the first value
Enumerator
Undefined
The type of the driver is undefined, no assumptions can be made about it.
GPIO
Represents a GPIO peripheral.
HARDWARE_TIMER
Represents a hardware timer peripheral.
I2C
Represents an I2C communication bus.
LED
Represents an LED driver.
SPI
Represents a SPI communication bus.
SYSTEM_CLOCK
Represents a master system clock, which can be a hardware device or software interface.
TIME_OF_FLIGHT
Represents a Time of Flight Range-finding sensor.
SOFTWARE_TIMER
Represents a software timer.
TIMER
Represents a hardware timer.
BASIC_DISPLAY
Represents a basic display without a range of colors, such as a small 2-color OLED display.
DRIVER_EXTENSION_START
To extend with your own driver types, start the count using this value.