Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_ctanl.c File Reference
s_ctanl.c File Reference
#include <float.h>
#include <openlibm_complex.h>
#include <openlibm_math.h>
Functions
static long double redupil (long double x)
static long double ctansl (long double complex z)
long double complex ctanl (long double complex z)
Variables
static const long double MACHEPL = 5.42101086242752217003726400434970855712890625E-20L
static const long double PIL = 3.141592653589793238462643383279502884197169L
static const long double DP1 = 3.14159265358979323829596852490908531763125L
static const long double DP2 = 1.6667485837041756656403424829301998703007e-19L
static const long double DP3 = 1.8830410776607851167459095484560349402753e-39L
Function Documentation
ctanl()
long double complex ctanl (long double complex z)
References cimagl(), complex, coshl(), cosl(), creall(), ctansl(), fabsl(), I, LDBL_MAX, sinhl(), sinl(), w, and z.
ctansl()
static long double ctansl (long double complex z) static
References cimagl(), creall(), fabsl(), MACHEPL, redupil(), t, and z.
Referenced by ctanl().
redupil()
static long double redupil (long double x) static
References DP1, DP2, DP3, PIL, and t.
Referenced by ctansl().
Variable Documentation
DP1
const long double DP1 = 3.14159265358979323829596852490908531763125L static
Referenced by redupil().
DP2
const long double DP2 = 1.6667485837041756656403424829301998703007e-19L static
Referenced by redupil().
DP3
const long double DP3 = 1.8830410776607851167459095484560349402753e-39L static
Referenced by redupil().
MACHEPL
const long double MACHEPL = 5.42101086242752217003726400434970855712890625E-20L static
Referenced by ctansl().
PIL
const long double PIL = 3.141592653589793238462643383279502884197169L static
Referenced by redupil().