Embedded Artistry Framework: src/stdlibs/libc/test/ctype/isalpha.c File Reference
isalpha.c File Reference
#include "ctype_tests.h"
#include <ctype.h>
#include <limits.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Functions
static void good_input (void **state)
static void bad_input (void **state)
int isalpha_tests (void)
Function Documentation
bad_input()
static void bad_input (void ** state) static
References INT_MAX, and isalpha().
Referenced by isalpha_tests().
good_input()
static void good_input (void ** state) static
References isalpha().
Referenced by isalpha_tests().
isalpha_tests()
int isalpha_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().