Embedded Artistry libc: include/crt.h File Reference
crt.h File Reference
Macros
#define CRT_HAS_INITFINI_ARRAY
Functions
void CRTStartup (void)
void __libc_init_array (void)
void __libc_fini_array (void)
Macro Definition Documentation
CRT_HAS_INITFINI_ARRAY
#define CRT_HAS_INITFINI_ARRAY
Definition at line 4 of file crt.h.
Function Documentation
__libc_fini_array()
void __libc_fini_array (void)
Definition at line 30 of file crt.c.
 {
     size_t count = __fini_array_end - __fini_array_start;
     for(size_t i = count - 1; i > 0; i--)
     {
         __fini_array_start[i]();
     }
 }
__libc_init_array()
void __libc_init_array (void)
Referenced by CRTStartup().
CRTStartup()
void CRTStartup (void)
Definition at line 39 of file crt.c.
 {
     memset(&__bss_start__, 0, (uintptr_t)&__bss_end__ - (uintptr_t)&__bss_start__);
     __libc_init_array();
     // TODO: handle relocs?
 }
References __bss_end__, __bss_start__, __libc_init_array(), and memset().