Embedded Artistry Framework: Framework Drivers
Framework Drivers
Drivers provided by the framework.
Modules
Unit Test Drivers
Drivers intended for use with unit test code.
Simulator Drivers
Drivers intended for use with simulator applications (run on host machine)
Classes
class embdrv::ssd1306
Driver for the SSD1306 Display Driver.
class embdrv::vl53l1x
ST VL53L1X Time-of-Flight Sensor Driver.
Detailed Description
Drivers provided by the framework.
Class Documentation
embdrv::ssd1306
class embdrv::ssd1306
Driver for the SSD1306 Display Driver.
This implementation only supports I2C, though the part supports SPI and Parallel modes To implement that support, please use a state pattern and adjust the i2cWrite function to be a more generic write. This single function can be swapped out for the particular data mode.
The screen size is hard-coded to be 64 x 48 with an offset of 32. Adjustments are needed to make the screen size specification generic.
Public Types
enum invert : uint8_t { invert::normal = 0, invert::invert }
Display color inversion options.
enum mode : uint8_t { mode::normal = 0, mode::XOR }
Set the drawing mode, if supported by the driver.
enum color : uint8_t { color::black = 0, color::white }
Basic displays have two pixel colors: black and white.
using coord_t = uint8_t
Coordinate representation type.
Public Member Functions
ssd1306 (embvm::i2c::master &i2c, uint8_t i2c_addr=0x3C)
Address is 0x3D if DC pin is set to 1.
void clear () final
Clear the screen contents.
void clearAndDisplay ()
void invert (enum invert inv) final
Invert the display color.
void contrast (uint8_t contrast) final
Set contrast.
void cursor (coord_t x, coord_t y) final
Set the cusor within the screen buffer.
void pixel (coord_t x, coord_t y, color c, mode m) final
Draw a pixel with a specific color and mode.
void line (coord_t x0, coord_t y0, coord_t x1, coord_t y1, color c, mode m) final
Draw a line with a specific color and mode.
void rect (coord_t x, coord_t y, uint8_t width, uint8_t height, color c, mode m) final
Draw a rectangle with a specific color and mode.
void rectFill (coord_t x, coord_t y, uint8_t width, uint8_t height, color c, mode m) final
Draw a filled rectangle with a specific color and mode.
void circle (coord_t x, coord_t y, uint8_t radius, color c, mode m) final
Draw a circle with a specific color and mode.
void circleFill (coord_t x, coord_t y, uint8_t radius, color c, mode m) final
Draw a filled circle with a specific color and mode.
void drawChar (coord_t x, coord_t y, uint8_t character, color c, mode m) final
Draw an ASCII character with a specific color and mode.
void drawBitmap (uint8_t *bitmap) final
Replace the screen buffer with a bitmap.
uint8_t screenWidth () final
Check the screen width.
uint8_t screenHeight () final
Check the screen height.
void scrollRight (coord_t start, coord_t stop) final
Enable right scrolling.
void scrollLeft (coord_t start, coord_t stop) final
Enable left scrolling.
void scrollVertRight (coord_t start, coord_t stop) final
void scrollVertLeft (coord_t start, coord_t stop) final
void scrollStop () final
Stop scrolling.
void flipVertical (bool flip) final
Vertical flip.
void flipHorizontal (bool flip) final
Horizontal flip.
void display () final
Flush the screen buffer contents to the hardware display buffer.
uint8_t fontType (uint8_t type)
Set the font type.
uint8_t fontType ()
Get the current font type.
uint8_t fontWidth ()
Get the font width.
uint8_t fontHeight ()
Get the font height.
uint8_t totalFonts ()
Get the total number of supported fonts.
uint8_t fontStartChar ()
Get the starting character for the font.
uint8_t fontTotalChar ()
Get the total number of characters supported by the font.
void putchar (uint8_t c) final
Print a character on the display.
void pixel (coord_t x, coord_t y)
Draw a pixel in the screen buffer.
void line (coord_t x0, coord_t y0, coord_t x1, coord_t y1)
Draw a line.
void lineH (coord_t x, coord_t y, uint8_t width)
Draw a horizontal line.
void lineH (coord_t x, coord_t y, uint8_t width, color c, mode m)
Draw a horizontal line with a specific color and mode.
void lineV (coord_t x, coord_t y, uint8_t height)
Draw a vertical line.
void lineV (coord_t x, coord_t y, uint8_t height, color c, mode m)
Draw a vertical line with a specific color and mode.
void rect (coord_t x, coord_t y, uint8_t width, uint8_t height)
Draw a rectangle.
void rectFill (coord_t x, coord_t y, uint8_t width, uint8_t height)
Draw a filled rectangle.
void circle (coord_t x, coord_t y, uint8_t radius)
Draw a circle.
void circleFill (coord_t x, coord_t y, uint8_t radius)
Draw a filled circle.
void drawChar (coord_t x, coord_t y, uint8_t character)
Draw an ASCII character.
void printString (coord_t x, coord_t y, const char *str)
Print a string on the display.
void printString (coord_t x, coord_t y, const char *str, size_t length)
Print a string on the display.
void drawColor (color c)
Set color.
virtual void drawMode (mode m)
Set draw mode.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
Basic Display Driver Type ID.
Protected Attributes
mode mode_ = mode::normal
The current display mode setting.
color color_ = color::black
The current display color setting.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void i2c_write (const uint8_t *buffer, uint8_t size, const embvm::i2c::master::cb_t &cb)
Helper function which performs an I2C write.
void clear (uint8_t c)
Clear the display and initialize buffer bytes with the target value.
void command (uint8_t c)
Send a command to the display driver hardware.
void command (uint8_t cmd, uint8_t arg1)
Send a command with one argument to the display driver hardware.
void command (uint8_t cmd, uint8_t arg1, uint8_t arg2)
Send a command with two arguments to the display driver hardware.
void data (uint8_t c)
Send a data byte to the display driver hardware.
void setColumnAddress (uint8_t add)
Set the column address.
void setPageAddress (uint8_t add)
Set the page address.
void drawCharSingleRow (coord_t x, coord_t y, uint8_t character, color c, mode m)
void drawCharMultiRow (coord_t x, coord_t y, uint8_t character, color c, mode m)
Private Attributes
uint8_t fontWidth_ = 0
uint8_t fontHeight_ = 0
uint8_t fontType_ = 0
uint8_t fontStartChar_ = 0
uint8_t fontTotalChar_ = 0
uint16_t fontMapWidth_ = 0
uint8_t cursorX_ = 0
X-axies position of the cursor.
uint8_t cursorY_ = 0
Y-axis position of the cursor.
embvm::i2c::master & i2c_
The i2c instance this display driver is attached to.
uint8_t i2c_addr_
The I2C address for this dispaly.
etl::variant_pool< 128, uint8_t, uint16_t, uint32_t > i2c_pool_ {}
Static memory pool which is used for display I2C transactions.
uint8_t display_buffer_ [SCREEN_BUFFER_SIZE+1] = {0}
OLED screen buffer.
uint8_t *const screen_buffer_ = &display_buffer_[1]
Pointer alias to the display_buffer_ which accounts for the single byte reserved for the DATA command value.
Static Private Attributes
static constexpr uint8_t SCREEN_WIDTH = 64
The width of the scren in pixels.
static constexpr uint8_t SCREEN_HEIGHT = 48
The height of the screen in pixels.
static constexpr size_t SCREEN_BUFFER_SIZE = ((SCREEN_WIDTH * SCREEN_HEIGHT) / 8)
The size of the screen buffer We divide by 8 because each byte controls the state of 8 pixels.
static constexpr uint8_t COLUMN_OFFSET = 32
The number of columns offset into the display where the active display area starts.
static const uint8_t * fonts_ [] = {font5x7, font8x16}
Array of fonts supported by this driver.
Member Typedef Documentation
coord_t
using embvm::basicDisplay::coord_t = uint8_t inherited
Coordinate representation type.
Member Enumeration Documentation
color
enum embvm::basicDisplay::color : uint8_t strong inherited
Basic displays have two pixel colors: black and white.
Enumerator
black
white
invert
enum embvm::basicDisplay::invert : uint8_t strong inherited
Display color inversion options.
Enumerator
normal
Use the default display color setting.
invert
Invert the display colors.
mode
enum embvm::basicDisplay::mode : uint8_t strong inherited
Set the drawing mode, if supported by the driver.
Enumerator
normal
Either sets or clears a pixel as requested, overwriting the value set in the screen buffer.
XOR
The pixel output in the screen buffer will be an XOR of the current value and the input value.
Constructor & Destructor Documentation
ssd1306()
embdrv::ssd1306::ssd1306 (embvm::i2c::master & i2c, uint8_t i2c_addr = 0x3C) inline explicit
Address is 0x3D if DC pin is set to 1.
References display_buffer_.
Member Function Documentation
circle() [1/2]
void ssd1306::circle (coord_t x, coord_t y, uint8_t radius, color c, mode m) final virtual
Draw a circle with a specific color and mode.
Draw a circle with center (x,y) and the specified radius using a specific color setting and draw mode in the screen buffer. Only the boundary of the circle will be drawn.
Parameters
x X-coorindate for the center of the circle.
y Y-coordinate for the center of the circle.
radius The radius of the circle.
c Pixel color.
m Mode used to update the screen buffer.
Implements embvm::basicDisplay.
References pixel().
circle() [2/2]
void embvm::basicDisplay::circle (coord_t x, coord_t y, uint8_t radius) inline inherited
Draw a circle.
Draw a circle with center (x,y) and the specified radius using the configured color setting and draw mode in the screen buffer. Only the boundary of the circle will be drawn.
Parameters
x X-coorindate for the center of the circle.
y Y-coordinate for the center of the circle.
radius The radius of the circle.
References embvm::basicDisplay::color_, and embvm::basicDisplay::mode_.
circleFill() [1/2]
void ssd1306::circleFill (coord_t x, coord_t y, uint8_t radius, color c, mode m) final virtual
Draw a filled circle with a specific color and mode.
Draw a filled circle with center (x,y) and the specified radius using a specific color setting and draw mode in the screen buffer. The interior of the circle will be filled with the specified color setting.
Parameters
x X-coorindate for the center of the circle.
y Y-coordinate for the center of the circle.
radius The radius of the circle.
c Pixel color.
m Mode used to update the screen buffer.
Implements embvm::basicDisplay.
References pixel(), and embvm::basicDisplay::XOR.
circleFill() [2/2]
void embvm::basicDisplay::circleFill (coord_t x, coord_t y, uint8_t radius) inline inherited
Draw a filled circle.
Draw a filled circle with center (x,y) and the specified radius using the configured color setting and draw mode in the screen buffer. The interior of the circle will be filled with the specified color setting.
Parameters
x X-coorindate for the center of the circle.
y Y-coordinate for the center of the circle.
radius The radius of the circle.
References embvm::basicDisplay::color_, and embvm::basicDisplay::mode_.
clear() [1/2]
void ssd1306::clear () final virtual
Clear the screen contents.
Implements embvm::basicDisplay.
Referenced by clearAndDisplay(), and start_().
clear() [2/2]
void ssd1306::clear (uint8_t c) private
Clear the display and initialize buffer bytes with the target value.
Parameters
c The value to initialize the bytes of the screen buffe rwith.
References memset(), screen_buffer_, and SCREEN_BUFFER_SIZE.
clearAndDisplay()
void ssd1306::clearAndDisplay ()
References clear(), and display().
command() [1/3]
void ssd1306::command (uint8_t c) private
Send a command to the display driver hardware.
Parameters
c the command byte.
References I2C_COMMAND_REG, i2c_pool_, and i2c_write().
Referenced by contrast(), flipHorizontal(), flipVertical(), invert(), scrollRight(), scrollStop(), start_(), and stop_().
command() [2/3]
void ssd1306::command (uint8_t cmd, uint8_t arg1) private
Send a command with one argument to the display driver hardware.
Parameters
cmd the command byte.
arg1 The argument to send with the command byte.
References I2C_COMMAND_REG, i2c_pool_, and i2c_write().
command() [3/3]
void ssd1306::command (uint8_t cmd, uint8_t arg1, uint8_t arg2) private
Send a command with two arguments to the display driver hardware.
Parameters
cmd the command byte.
arg1 The first argument to send with the command byte.
arg2 The second argumet to send with the command byte.
References I2C_COMMAND_REG, i2c_pool_, and i2c_write().
contrast()
void ssd1306::contrast (uint8_t contrast) final virtual
Set contrast.
Parameters
contrast Target display contrast value, ranging from 0 to 255.
Implements embvm::basicDisplay.
References command().
cursor()
void ssd1306::cursor (coord_t x, coord_t y) final virtual
Set the cusor within the screen buffer.
Contents in the screen buffer are not modified by setting the cursor position.
Parameters
x X-coordinate of the cursor.
y Y-coordinate of the cursor.
Implements embvm::basicDisplay.
References cursorX_, and cursorY_.
Referenced by start_().
data()
void ssd1306::data (uint8_t c) private
Send a data byte to the display driver hardware.
Parameters
c The data byte to send to the display.
References i2c_data_byte_, i2c_pool_, and i2c_write().
display()
void ssd1306::display () final virtual
Flush the screen buffer contents to the hardware display buffer.
Implements embvm::basicDisplay.
References display_buffer_, i2c_, i2c_addr_, t, and embvm::i2c::write.
Referenced by clearAndDisplay(), and start_().
drawBitmap()
void ssd1306::drawBitmap (uint8_t * bitmap) final virtual
Replace the screen buffer with a bitmap.
Supply a bitmap to write to the screen buffer. If the size of the bitmap is less than the size of the screen buffer, the remainder of the screen buffer will not be modified.
Parameters
bitmap Bitmap array which will be used to overwrite the screen buffer.
Implements embvm::basicDisplay.
References memcpy(), screen_buffer_, and SCREEN_BUFFER_SIZE.
drawChar() [1/2]
void ssd1306::drawChar (coord_t x, coord_t y, uint8_t character, color c, mode m) final virtual
Draw an ASCII character with a specific color and mode.
Draw an ASCII character using a specific color and draw mode with the upper left corner of the character located at (x,y).
Parameters
x X-coordinate representing the top-left of the character.
y Y-coordinate representing the top-left of the character.
character the ASCII character to draw. Must be present in the font file. If the requested character is not present, nothing will be drawn on the screen buffer.
c Pixel color.
m Mode used to update the screen buffer.
Implements embvm::basicDisplay.
References assert, drawCharMultiRow(), drawCharSingleRow(), fontHeight_, fontStartChar_, and fontTotalChar_.
Referenced by putchar().
drawChar() [2/2]
void embvm::basicDisplay::drawChar (coord_t x, coord_t y, uint8_t character) inline inherited
Draw an ASCII character.
Draw an ASCII character using the configured color and draw mode with the upper left corner of the character located at (x,y).
Parameters
x X-coordinate representing the top-left of the character.
y Y-coordinate representing the top-left of the character.
character the ASCII character to draw. Must be present in the font file. If the requested character is not present, nothing will be drawn on the screen buffer.
References embvm::basicDisplay::color_, and embvm::basicDisplay::mode_.
drawCharMultiRow()
void ssd1306::drawCharMultiRow (coord_t x, coord_t y, uint8_t character, color c, mode m) private
References embvm::basicDisplay::black, FONT_HEADER_SIZE, fontHeight_, fontMapWidth_, fonts_, fontType_, fontWidth_, pixel(), and embvm::basicDisplay::white.
Referenced by drawChar().
drawCharSingleRow()
void ssd1306::drawCharSingleRow (coord_t x, coord_t y, uint8_t character, color c, mode m) private
References embvm::basicDisplay::black, FONT_HEADER_SIZE, fonts_, fontType_, fontWidth_, pixel(), and embvm::basicDisplay::white.
Referenced by drawChar().
drawColor()
void embvm::basicDisplay::drawColor (color c) inline inherited
Set color.
Set the current draw's color. Only WHITE and BLACK available.
Parameters
c The desired draw color setting.
References assert, embvm::basicDisplay::black, embvm::basicDisplay::color_, and embvm::basicDisplay::white.
Referenced by start_().
drawMode()
virtual void embvm::basicDisplay::drawMode (mode m) inline virtual inherited
Set draw mode.
Parameters
m Desired draw mode: NORM or XOR.
References assert, embvm::basicDisplay::mode_, embvm::basicDisplay::normal, and embvm::basicDisplay::XOR.
Referenced by start_().
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
flipHorizontal()
void ssd1306::flipHorizontal (bool flip) final virtual
Horizontal flip.
Flip the graphics on the display horizontally.
Parameters
flip True enables horizontal flip, false disables horizontal flip.
Implements embvm::basicDisplay.
References command(), and x0.
flipVertical()
void ssd1306::flipVertical (bool flip) final virtual
Vertical flip.
Flip the graphics on the display vertically.
Parameters
flip True enables vertical flip, false disables vertical flip.
Implements embvm::basicDisplay.
References command().
fontHeight()
uint8_t embdrv::ssd1306::fontHeight () inline
Get the font height.
Returns
the height of the currently selected font in pixels
References fontHeight_.
fontStartChar()
uint8_t embdrv::ssd1306::fontStartChar () inline
Get the starting character for the font.
Returns
the starting ASCII character for the currently selected font
References fontStartChar_.
fontTotalChar()
uint8_t embdrv::ssd1306::fontTotalChar () inline
Get the total number of characters supported by the font.
Returns
the number of characters supported by the currently selected font
References fontTotalChar_.
fontType() [1/2]
uint8_t ssd1306::fontType (uint8_t type)
Set the font type.
Parameters
type Index for the font to use
Returns
the currently selected font.
References assert, font_count_, fontHeight_, fontMapWidth_, fonts_, fontStartChar_, fontTotalChar_, fontType_, fontWidth_, and embvm::basicDisplay::type().
fontType() [2/2]
uint8_t embdrv::ssd1306::fontType () inline
Get the current font type.
Returns
the currently selected font.
References fontType_.
Referenced by start_().
fontWidth()
uint8_t embdrv::ssd1306::fontWidth () inline
Get the font width.
Returns
the width of the currently selected font in pixels
References fontWidth_.
i2c_write()
void ssd1306::i2c_write (const uint8_t * buffer, uint8_t size, const embvm::i2c::master::cb_t & cb) private
Helper function which performs an I2C write.
Parameters
buffer The transaction buffer.
size The size of the write.
cb The callback function to invoke when the write completes.
References i2c_, i2c_addr_, t, and embvm::i2c::write.
Referenced by command(), and data().
invert()
void ssd1306::invert (enum invert inv) final virtual
Invert the display color.
The WHITE color of the display will turn to BLACK and the BLACK will turn to WHITE.
Parameters
inv invert::invert uses color inversion, invert::normal uses the display standard.
Implements embvm::basicDisplay.
References command(), and embvm::basicDisplay::normal.
line() [1/2]
void ssd1306::line (coord_t x0, coord_t y0, coord_t x1, coord_t y1, color c, mode m) final virtual
Draw a line with a specific color and mode.
Draw line with a specific color setting and draw mode from (x0,y0) to (x1,y1) of the screen buffer.
Parameters
x0 X-coordinate where the line originates.
y0 Y-coordinate where the line originates.
x1 X-coordinate where the line terminates.
y1 Y-coordinate where the line terminates.
c Pixel color.
m Mode used to update the screen buffer.
Implements embvm::basicDisplay.
References abs(), pixel(), swap, and x0.
line() [2/2]
void embvm::basicDisplay::line (coord_t x0, coord_t y0, coord_t x1, coord_t y1) inline inherited
Draw a line.
Draw a line using the configured color setting and draw mode from (x0,y0) to (x1,y1) of the screen buffer.
Parameters
x0 X-coordinate where the line originates.
y0 Y-coordinate where the line originates.
x1 X-coordinate where the line terminates.
y1 Y-coordinate where the line terminates.
References embvm::basicDisplay::color_, embvm::basicDisplay::mode_, and x0.
Referenced by embvm::basicDisplay::lineH(), and embvm::basicDisplay::lineV().
lineH() [1/2]
void embvm::basicDisplay::lineH (coord_t x, coord_t y, uint8_t width) inline inherited
Draw a horizontal line.
Draw a horizontal line using the configured color setting and draw mode from (x,y) to (x+width,y) in the screen buffer.
Parameters
x X-coordinate where the line originates.
y Y-coordinate where the line originates.
width Length of the line, in pixels. The line will terminate at coordinate (x+width, y).
References embvm::basicDisplay::color_, and embvm::basicDisplay::mode_.
Referenced by rect().
lineH() [2/2]
void embvm::basicDisplay::lineH (coord_t x, coord_t y, uint8_t width, color c, mode m) inline inherited
Draw a horizontal line with a specific color and mode.
Draw a horizontal line with a specific color setting and draw mode from (x,y) to (x+width,y) in the screen buffer.
Parameters
x X-coordinate where the line originates.
y Y-coordinate where the line originates.
width Length of the line, in pixels. The line will terminate at coordinate (x+width, y).
c Pixel color.
m Mode used to update the screen buffer.
References embvm::basicDisplay::line().
lineV() [1/2]
void embvm::basicDisplay::lineV (coord_t x, coord_t y, uint8_t height) inline inherited
Draw a vertical line.
Draw a vertical line using the configured color setting and draw mode from (x,y) to (x,y+height) in the screen buffer.
Parameters
x X-coordinate where the line originates.
y Y-coordinate where the line originates.
height Length of the line, in pixels. The line will terminate at coordinate (x, y+height).
References embvm::basicDisplay::color_, and embvm::basicDisplay::mode_.
Referenced by rect(), and rectFill().
lineV() [2/2]
void embvm::basicDisplay::lineV (coord_t x, coord_t y, uint8_t height, color c, mode m) inline inherited
Draw a vertical line with a specific color and mode.
Draw a vertical line using a specific color setting and draw mode from (x,y) to (x,y+height) in the screen buffer.
Parameters
x X-coordinate where the line originates.
y Y-coordinate where the line originates.
height Length of the line, in pixels. The line will terminate at coordinate (x, y+height).
c Pixel color.
m Mode used to update the screen buffer.
References embvm::basicDisplay::line().
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
pixel() [1/2]
void ssd1306::pixel (coord_t x, coord_t y, color c, mode m) final virtual
Draw a pixel with a specific color and mode.
Draw a pixel at position (x,y) with a specific color setting and draw mode.
Parameters
x X-coordinate of the pixel.
y Y-coordinate of the pixel.
c Pixel color.
m Mode used to update the screen buffer.
Implements embvm::basicDisplay.
References screen_buffer_, SCREEN_HEIGHT, SCREEN_WIDTH, SET_BIT, embvm::basicDisplay::white, and embvm::basicDisplay::XOR.
Referenced by circle(), circleFill(), drawCharMultiRow(), drawCharSingleRow(), and line().
pixel() [2/2]
void embvm::basicDisplay::pixel (coord_t x, coord_t y) inline inherited
Draw a pixel in the screen buffer.
Draw pixel using the configured color setting and draw mode in the screen buffer's x,y position.
Parameters
x X-coordinate of the pixel.
y Y-coordinate of the pixel.
References embvm::basicDisplay::color_, and embvm::basicDisplay::mode_.
printString() [1/2]
void embvm::basicDisplay::printString (coord_t x, coord_t y, const char * str) inline inherited
Print a string on the display.
Parameters
x The x-coordinate to start the string.
y The y-coordinate to start the string.
str The string to print to the display.
References strlen().
printString() [2/2]
void embvm::basicDisplay::printString (coord_t x, coord_t y, const char * str, size_t length) inline inherited
Print a string on the display.
Parameters
x The x-coordinate to start the string.
y The y-coordinate to start the string.
str The string to print to the display.
length The number of characters in str.
References embvm::basicDisplay::cursor(), length, and embvm::basicDisplay::putchar().
putchar()
void ssd1306::putchar (uint8_t c) final virtual
Print a character on the display.
Parameters
c the character to print to the display
Implements embvm::basicDisplay.
References embvm::basicDisplay::color_, cursorX_, cursorY_, drawChar(), fontHeight_, fontWidth_, embvm::basicDisplay::mode_, and SCREEN_WIDTH.
rect() [1/2]
void ssd1306::rect (coord_t x, coord_t y, uint8_t width, uint8_t height, color c, mode m) final virtual
Draw a rectangle with a specific color and mode.
Draw a rectangle with a specific color setting and draw mode from (x,y) to (x+width,y+height) in the screen buffer. Only the boundary of the rectangle will be drawn.
Parameters
x X-coordinate where the rectangle originates.
y Y-coordinate where the rectangle originates.
width Width of the rectangle, in pixels. The rectangle width spans from x to x+width.
height Height of the rectangle, in pixels. The rectangle height spans from y + y+height.
c Pixel color.
m Mode used to update the screen buffer.
Implements embvm::basicDisplay.
References embvm::basicDisplay::lineH(), and embvm::basicDisplay::lineV().
rect() [2/2]
void embvm::basicDisplay::rect (coord_t x, coord_t y, uint8_t width, uint8_t height) inline inherited
Draw a rectangle.
Draw a rectangle using the configured color setting and draw mode from (x,y) to (x+width,y+height) in the screen buffer. Only the boundary of the rectangle will be drawn.
Parameters
x X-coordinate where the rectangle originates.
y Y-coordinate where the rectangle originates.
width Width of the rectangle, in pixels. The rectangle width spans from x to x+width.
height Height of the rectangle, in pixels. The rectangle height spans from y + y+height.
References embvm::basicDisplay::color_, and embvm::basicDisplay::mode_.
rectFill() [1/2]
void ssd1306::rectFill (coord_t x, coord_t y, uint8_t width, uint8_t height, color c, mode m) final virtual
Draw a filled rectangle with a specific color and mode.
Draw a filled rectangle using a specific color setting and draw mode from (x,y) to (x+width,y+height) in the screen buffer. The interior of the rectangle will be filled with the specified color setting.
Parameters
x X-coordinate where the rectangle originates.
y Y-coordinate where the rectangle originates.
width Width of the rectangle, in pixels. The rectangle width spans from x to x+width.
height Height of the rectangle, in pixels. The rectangle height spans from y + y+height.
c Pixel color.
m Mode used to update the screen buffer.
Implements embvm::basicDisplay.
References embvm::basicDisplay::lineV().
rectFill() [2/2]
void embvm::basicDisplay::rectFill (coord_t x, coord_t y, uint8_t width, uint8_t height) inline inherited
Draw a filled rectangle.
Draw a filled rectangle using the configured color setting and draw mode from (x,y) to (x+width,y+height) in the screen buffer. The interior of the rectangle will be filled with the configured color setting.
Parameters
x X-coordinate where the rectangle originates.
y Y-coordinate where the rectangle originates.
width Width of the rectangle, in pixels. The rectangle width spans from x to x+width.
height Height of the rectangle, in pixels. The rectangle height spans from y + y+height.
References embvm::basicDisplay::color_, and embvm::basicDisplay::mode_.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
screenHeight()
uint8_t ssd1306::screenHeight () final virtual
Check the screen height.
The drived class must implement this function.
Returns
The height of the screen in pixels.
Implements embvm::basicDisplay.
References SCREEN_HEIGHT.
screenWidth()
uint8_t ssd1306::screenWidth () final virtual
Check the screen width.
The drived class must implement this function.
Returns
The width of the screen in pixels.
Implements embvm::basicDisplay.
References SCREEN_WIDTH.
scrollLeft()
void ssd1306::scrollLeft (coord_t start, coord_t stop) final virtual
Enable left scrolling.
Set row start to row stop on the display to scroll left.
Parameters
start The start row index.
stop The stop row index.
Precondition
Scrolling is not enabled, stop < start.
Postcondition
The display is scrolling to the left.
Implements embvm::basicDisplay.
References assert, embvm::DriverBase::start(), and embvm::DriverBase::stop().
scrollRight()
void ssd1306::scrollRight (coord_t start, coord_t stop) final virtual
Enable right scrolling.
Set row start to row stop on the display to scroll right.
Parameters
start The start row index.
stop The stop row index.
Precondition
Scrolling is not enabled, start < stop.
Postcondition
The display is scrolling to the right.
Implements embvm::basicDisplay.
References assert, command(), scrollStop(), embvm::DriverBase::start(), and embvm::DriverBase::stop().
scrollStop()
void ssd1306::scrollStop () final virtual
Stop scrolling.
Stop the scrolling of graphics on the display.
Implements embvm::basicDisplay.
References command().
Referenced by scrollRight().
scrollVertLeft()
void ssd1306::scrollVertLeft (coord_t start, coord_t stop) final virtual
Implements embvm::basicDisplay.
References assert, embvm::DriverBase::start(), and embvm::DriverBase::stop().
scrollVertRight()
void ssd1306::scrollVertRight (coord_t start, coord_t stop) final virtual
Implements embvm::basicDisplay.
References assert, embvm::DriverBase::start(), and embvm::DriverBase::stop().
setColumnAddress()
void embdrv::ssd1306::setColumnAddress (uint8_t add) private
Set the column address.
Parameters
add The address of the column.
setPageAddress()
void embdrv::ssd1306::setPageAddress (uint8_t add) private
Set the page address.
Parameters
add The address of the page.
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), scrollLeft(), scrollRight(), scrollVertLeft(), scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void ssd1306::start_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Display init sequence These values were inherited from Sparkfun's example
Implements embvm::basicDisplay.
References clear(), COLUMN_OFFSET, command(), cursor(), display(), embvm::basicDisplay::drawColor(), embvm::basicDisplay::drawMode(), fontType(), embvm::basicDisplay::normal, SCREEN_WIDTH, embvm::basicDisplay::white, and x0.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), scrollLeft(), scrollRight(), scrollVertLeft(), scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void ssd1306::stop_ () final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::basicDisplay.
References command().
totalFonts()
uint8_t ssd1306::totalFonts ()
Get the total number of supported fonts.
Returns
the number of supported fonts
References font_count_.
type()
static constexpr embvm::DriverType embvm::basicDisplay::type () inline static inherited
Basic Display Driver Type ID.
Returns
Basic Display type ID.
References embvm::BASIC_DISPLAY.
Referenced by fontType().
Member Data Documentation
color_
color embvm::basicDisplay::color_ = color::black protected inherited
The current display color setting.
Referenced by embvm::basicDisplay::circle(), embvm::basicDisplay::circleFill(), embvm::basicDisplay::drawChar(), embvm::basicDisplay::drawColor(), embvm::basicDisplay::line(), embvm::basicDisplay::lineH(), embvm::basicDisplay::lineV(), embvm::basicDisplay::pixel(), putchar(), embvm::basicDisplay::rect(), and embvm::basicDisplay::rectFill().
COLUMN_OFFSET
constexpr uint8_t embdrv::ssd1306::COLUMN_OFFSET = 32 static private
The number of columns offset into the display where the active display area starts.
Referenced by start_().
cursorX_
uint8_t embdrv::ssd1306::cursorX_ = 0 private
X-axies position of the cursor.
Referenced by cursor(), and putchar().
cursorY_
uint8_t embdrv::ssd1306::cursorY_ = 0 private
Y-axis position of the cursor.
Referenced by cursor(), and putchar().
display_buffer_
uint8_t embdrv::ssd1306::display_buffer_[SCREEN_BUFFER_SIZE+1] = {0} private
OLED screen buffer.
Page buffer is required because in SPI and I2C mode, the host cannot read the SSD1306's GDRAM of the controller. This page buffer serves as a scratch RAM for graphical functions. All drawing function will first be drawn on this page buffer, only upon calling display() function will transfer the page buffer to the actual LCD controller's memory.
The additional byte is to represent the data word byte, which allows us to send the entire buffer in one shot
Referenced by display(), and ssd1306().
fontHeight_
uint8_t embdrv::ssd1306::fontHeight_ = 0 private
Referenced by drawChar(), drawCharMultiRow(), fontHeight(), fontType(), and putchar().
fontMapWidth_
uint16_t embdrv::ssd1306::fontMapWidth_ = 0 private
Referenced by drawCharMultiRow(), and fontType().
fonts_
const uint8_t * ssd1306::fonts_ = {font5x7, font8x16} static private
Array of fonts supported by this driver.
NOTE: the SSD1306 DOES NOT WORK WITH A REPEATED START CONDITION There must be no start between the data byte and the data stream.
Referenced by drawCharMultiRow(), drawCharSingleRow(), and fontType().
fontStartChar_
uint8_t embdrv::ssd1306::fontStartChar_ = 0 private
Referenced by drawChar(), fontStartChar(), and fontType().
fontTotalChar_
uint8_t embdrv::ssd1306::fontTotalChar_ = 0 private
Referenced by drawChar(), fontTotalChar(), and fontType().
fontType_
uint8_t embdrv::ssd1306::fontType_ = 0 private
Referenced by drawCharMultiRow(), drawCharSingleRow(), and fontType().
fontWidth_
uint8_t embdrv::ssd1306::fontWidth_ = 0 private
Referenced by drawCharMultiRow(), drawCharSingleRow(), fontType(), fontWidth(), and putchar().
i2c_
embvm::i2c::master& embdrv::ssd1306::i2c_ private
The i2c instance this display driver is attached to.
Referenced by display(), and i2c_write().
i2c_addr_
uint8_t embdrv::ssd1306::i2c_addr_ private
The I2C address for this dispaly.
Referenced by display(), and i2c_write().
i2c_pool_
etl::variant_pool<128, uint8_t, uint16_t, uint32_t> embdrv::ssd1306::i2c_pool_ {} private
Static memory pool which is used for display I2C transactions.
Referenced by command(), and data().
mode_
mode embvm::basicDisplay::mode_ = mode::normal protected inherited
The current display mode setting.
Referenced by embvm::basicDisplay::circle(), embvm::basicDisplay::circleFill(), embvm::basicDisplay::drawChar(), embvm::basicDisplay::drawMode(), embvm::basicDisplay::line(), embvm::basicDisplay::lineH(), embvm::basicDisplay::lineV(), embvm::basicDisplay::pixel(), putchar(), embvm::basicDisplay::rect(), and embvm::basicDisplay::rectFill().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
screen_buffer_
uint8_t* const embdrv::ssd1306::screen_buffer_ = &display_buffer_[1] private
Pointer alias to the display_buffer_ which accounts for the single byte reserved for the DATA command value.
Referenced by clear(), drawBitmap(), and pixel().
SCREEN_BUFFER_SIZE
constexpr size_t embdrv::ssd1306::SCREEN_BUFFER_SIZE = ((SCREEN_WIDTH * SCREEN_HEIGHT) / 8) static private
The size of the screen buffer We divide by 8 because each byte controls the state of 8 pixels.
Referenced by clear(), and drawBitmap().
SCREEN_HEIGHT
constexpr uint8_t embdrv::ssd1306::SCREEN_HEIGHT = 48 static private
The height of the screen in pixels.
Referenced by pixel(), and screenHeight().
SCREEN_WIDTH
constexpr uint8_t embdrv::ssd1306::SCREEN_WIDTH = 64 static private
The width of the scren in pixels.
Referenced by pixel(), putchar(), screenWidth(), and start_().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
embdrv::vl53l1x
class embdrv::vl53l1x
ST VL53L1X Time-of-Flight Sensor Driver.
This driver is configured to work with I2C. You must initialize the device with an I2C Master.
embdrv::vl53l1x tof0{i2c0, SPARKFUN_VL53L1X_ADDR};
Public Types
using rate_cb_t = stdext::inplace_function< void(uint16_t)>
Alias for signalRate() callback function.
using status_cb_t = stdext::inplace_function< void(embvm::tof::status)>
Alias for the rangeStatus() callback function.
using read_cb_t = stdext::inplace_function< void(uint16_t)>
ToF Callback function which retuns distance in mm.
Public Member Functions
vl53l1x (embvm::i2c::master &i2c, uint8_t address=VL53L1X_DEFAULT_I2C_ADDR)
Create a VL53L1X device.
void read () final
Trigger a sensor read.
void reset () final
Reset the ToF sensor.
embvm::tof::distance_t getMaxRangeForModeDark (embvm::tof::mode m) const final
Check the maximum range in the dark.
embvm::tof::distance_t getMaxRangeForModeStrongLight (embvm::tof::mode m) const final
Check the maximum range in strong light conditions.
embvm::tof::mode mode (embvm::tof::mode m) final
Set the ToF ranging mode.
void signalRate ()
Get the current signal rate.
void rangeStatus ()
Get the ranging status When called, registered range status callbacks will be invoked with the signal rate.
void registerReadCallback (const read_cb_t &cb) final
Register a callback for the read() function.
void registerReadCallback (read_cb_t &&cb) final
Register a callback for the read() function.
void registerSignalRateCallback (const rate_cb_t &cb)
Register a callback for use with the signalRate() function.
void registerSignalRateCallback (rate_cb_t &&cb)
void registerStatusCallback (const status_cb_t &cb)
Register a callback for use with the rangeStatus() function.
void registerStatusCallback (status_cb_t &&cb)
tof::mode mode () const noexcept
Get the ToF ranging mode.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
ToF Driver Type ID.
Protected Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
Protected Attributes
tof::mode mode_ = tof::mode::defaultRange
The configured ranging mode for the ToF sensor.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Member Functions
void readReg (const uint16_t *reg_buf, uint8_t *rx_buffer, size_t rx_size, const embvm::i2c::master::cb_t &cb)
Convenience function to read a register from the VL51L1X device.
void writeReg (uint16_t reg, const uint8_t *tx_buffer, size_t tx_size, const embvm::i2c::master::cb_t &cb)
Convenience function to write to a register on the VL51L1X device.
void checkModelID ()
Check the model ID of the VL53L1X sensor.
void readTrim ()
Read the trim values of the sensor and update the config_block_.
void startMeasurement ()
Trigger a range measurement.
void readOscillatorCal ()
Read the oscillator calibration and store it in the private variable osc_calibrate_val_.
void clearInterrupt ()
Clear the VL53L1X pending interrupt.
void dataReady ()
Check if the range data is ready.
void readData ()
Read the range data from the device.
void dataReadyCb (embvm::i2c::op_t op, embvm::i2c::status status)
Local driver callback which is invoked when data is ready.
void kickoffMeasurementOnceFirmwareReady ()
Function that starts the sensor firmware and begins measurements.
void rangeStatusCb (uint8_t status)
Private callback function to get the range status.
embvm::tof::status convertStatus (uint8_t status)
Convert the raw range status code to the framework ToF statuses.
template<typename TData >
void destroy (const TData *ptr)
template<typename TData >
TData * create (TData input=0)
Private Attributes
embvm::i2c::master & i2c_
The I2C master bus that this device is connected to.
const uint8_t address_
The I2C address for the VL53L1X.
uint8_t model_id_ = 0
The model ID for the VL53L1X, read from the device during start().
uint16_t osc_calibrate_val_ = 0
etl::generic_pool< sizeof(uint32_t), alignof(uint32_t), 64 > i2c_pool_ {}
Static memory pool used for I2C transactions.
std::mutex lock_ {}
etl::list< read_cb_t, 2 > read_cb_list_ {}
List that stores the read() callback functions.
etl::list< status_cb_t, 2 > status_cb_list_ {}
List that stores the rangeStatus() callback functions.
etl::list< rate_cb_t, 2 > rate_cb_list_ {}
List that stores the signalRate() callback functions.
std::array< uint8_t, 137 > config_block_
Member Typedef Documentation
rate_cb_t
using embdrv::vl53l1x::rate_cb_t = stdext::inplace_function<void(uint16_t)>
Alias for signalRate() callback function.
read_cb_t
using embvm::tof::sensor::read_cb_t = stdext::inplace_function<void(uint16_t)> inherited
ToF Callback function which retuns distance in mm.
status_cb_t
using embdrv::vl53l1x::status_cb_t = stdext::inplace_function<void(embvm::tof::status)>
Alias for the rangeStatus() callback function.
Constructor & Destructor Documentation
vl53l1x()
embdrv::vl53l1x::vl53l1x (embvm::i2c::master & i2c, uint8_t address = VL53L1X_DEFAULT_I2C_ADDR) inline explicit
Create a VL53L1X device.
Parameters
i2c The i2c master driver that this device is connected to.
address The i2c address of the sensor.
Member Function Documentation
checkModelID()
void vl53l1x::checkModelID () private
Check the model ID of the VL53L1X sensor.
References assert, create(), MODEL_ID, model_id_, r, and readReg().
Referenced by start_().
clearInterrupt()
void vl53l1x::clearInterrupt () private
Clear the VL53L1X pending interrupt.
References create(), VL53L1_INT_CLR, and writeReg().
Referenced by readData().
convertStatus()
embvm::tof::status vl53l1x::convertStatus (uint8_t status) private
Convert the raw range status code to the framework ToF statuses.
Parameters
status The raw sensor status code.
Returns
The equivalent framework standard status code.
References embvm::tof::crosstalkSignalError, embvm::tof::hardwareError, embvm::tof::invalidRoi, embvm::tof::noChange, embvm::tof::notReady, embvm::tof::ok, embvm::tof::outOfBoundsError, embvm::tof::processingError, embvm::tof::rangeValidMergedPulse, embvm::tof::rangeValidMinRangeClipped, embvm::tof::sigmaError, embvm::tof::signalError, VL53L1_DEVICEERROR_ALGOOVERFLOW, VL53L1_DEVICEERROR_ALGOUNDERFLOW, VL53L1_DEVICEERROR_EVENTCONSISTENCY, VL53L1_DEVICEERROR_GPHSTREAMCOUNT0READY, VL53L1_DEVICEERROR_MINCLIP, VL53L1_DEVICEERROR_MINSIGNALEVENTCHECK, VL53L1_DEVICEERROR_MSRCNOTARGET, VL53L1_DEVICEERROR_MULTCLIPFAIL, VL53L1_DEVICEERROR_NOVHVVALUEFOUND, VL53L1_DEVICEERROR_PHASECONSISTENCY, VL53L1_DEVICEERROR_RANGECOMPLETE, VL53L1_DEVICEERROR_RANGECOMPLETE_MERGED_PULSE, VL53L1_DEVICEERROR_RANGECOMPLETE_NO_WRAP_CHECK, VL53L1_DEVICEERROR_RANGEIGNORETHRESHOLD, VL53L1_DEVICEERROR_RANGEPHASECHECK, VL53L1_DEVICEERROR_REFSPADCHARLESSTHANTARGET, VL53L1_DEVICEERROR_REFSPADCHARMORETHANTARGET, VL53L1_DEVICEERROR_REFSPADCHARNOTENOUGHDPADS, VL53L1_DEVICEERROR_SIGMATHRESHOLDCHECK, VL53L1_DEVICEERROR_USERROICLIP, VL53L1_DEVICEERROR_VCSELCONTINUITYTESTFAILURE, and VL53L1_DEVICEERROR_VCSELWATCHDOGTESTFAILURE.
Referenced by rangeStatusCb().
create()
template<typename TData > TData* embdrv::vl53l1x::create (TData input = 0) inline private
References i2c_pool_, r, VL53L1X_LOCK, and VL53L1X_UNLOCK.
Referenced by checkModelID(), clearInterrupt(), dataReady(), kickoffMeasurementOnceFirmwareReady(), rangeStatus(), readData(), readOscillatorCal(), readTrim(), signalRate(), and writeReg().
dataReady()
void vl53l1x::dataReady () private
Check if the range data is ready.
References create(), dataReadyCb(), and readReg().
Referenced by dataReadyCb(), and read().
dataReadyCb()
void vl53l1x::dataReadyCb (embvm::i2c::op_t op, embvm::i2c::status status) private
Local driver callback which is invoked when data is ready.
References dataReady(), embvm::i2c::ok, readData(), embvm::i2c::op_t::rx_buffer, and embvm::i2c::op_t::tx_buffer.
Referenced by dataReady().
destroy()
template<typename TData > void embdrv::vl53l1x::destroy (const TData * ptr) inline private
References i2c_pool_, VL53L1X_LOCK, and VL53L1X_UNLOCK.
Referenced by kickoffMeasurementOnceFirmwareReady(), mode(), rangeStatus(), and reset().
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
getMaxRangeForModeDark()
embvm::tof::distance_t vl53l1x::getMaxRangeForModeDark (embvm::tof::mode m) const final virtual
Check the maximum range in the dark.
Returns
the sensor's maximum distance capability (in mm) in the dark.
Implements embvm::tof::sensor.
References embvm::tof::defaultRange, embvm::tof::INVALID_RANGE, embvm::tof::longRange, embvm::tof::medRange, and embvm::tof::shortRange.
getMaxRangeForModeStrongLight()
embvm::tof::distance_t vl53l1x::getMaxRangeForModeStrongLight (embvm::tof::mode m) const final virtual
Check the maximum range in strong light conditions.
Returns
the sensor's maximum distance capability (in mm) in strong light.
Implements embvm::tof::sensor.
References embvm::tof::defaultRange, embvm::tof::INVALID_RANGE, embvm::tof::longRange, embvm::tof::medRange, and embvm::tof::shortRange.
kickoffMeasurementOnceFirmwareReady()
void vl53l1x::kickoffMeasurementOnceFirmwareReady () private
Function that starts the sensor firmware and begins measurements.
References create(), destroy(), embvm::i2c::ok, r, readReg(), and startMeasurement().
mode() [1/2]
embvm::tof::mode vl53l1x::mode (embvm::tof::mode m) final virtual
Set the ToF ranging mode.
Parameters
m The desired ToF ranging mode.
Returns
the active ToF mode.
Implements embvm::tof::sensor.
References embvm::tof::defaultRange, destroy(), embvm::tof::longRange, embvm::tof::medRange, embvm::tof::shortRange, and writeReg().
Referenced by FWDemoSimulatorHWPlatform::readAndSetToFMode().
mode() [2/2]
tof::mode embvm::tof::sensor::mode () const inline noexcept inherited
Get the ToF ranging mode.
Returns
the currently configured ToF ranging mode.
References embvm::tof::sensor::mode_.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
rangeStatus()
void vl53l1x::rangeStatus ()
Get the ranging status When called, registered range status callbacks will be invoked with the signal rate.
To register a callback, use registerStatusCallback().
References create(), destroy(), embvm::i2c::ok, r, rangeStatusCb(), and readReg().
rangeStatusCb()
void vl53l1x::rangeStatusCb (uint8_t status) private
Private callback function to get the range status.
References convertStatus(), s, and status_cb_list_.
Referenced by rangeStatus().
read()
void vl53l1x::read () final virtual
Trigger a sensor read.
Trigger an asynchronous read of the ToF sensor. The result will be provided to consumers through a callback function. When the read() operation completes, the callback will be invoked with the result.
Implements embvm::tof::sensor.
References dataReady().
readData()
void vl53l1x::readData () private
Read the range data from the device.
References clearInterrupt(), create(), embvm::i2c::ok, r, read_cb_list_, and readReg().
Referenced by dataReadyCb().
readOscillatorCal()
void vl53l1x::readOscillatorCal () private
Read the oscillator calibration and store it in the private variable osc_calibrate_val_.
References create(), osc_calibrate_val_, r, and readReg().
Referenced by start_().
readReg()
void vl53l1x::readReg (const uint16_t * reg_buf, uint8_t * rx_buffer, size_t rx_size, const embvm::i2c::master::cb_t & cb) private
Convenience function to read a register from the VL51L1X device.
Parameters
reg_buf the buffer containing the TX register data.
rx_buffer The buffer to store the received contents into.
rx_size the number of expected RX bytes.
cb The callback function to invoke when the register read completes.
References address_, i2c_, t, and embvm::i2c::writeRead.
Referenced by checkModelID(), dataReady(), kickoffMeasurementOnceFirmwareReady(), rangeStatus(), readData(), readOscillatorCal(), readTrim(), and signalRate().
readTrim()
void vl53l1x::readTrim () private
Read the trim values of the sensor and update the config_block_.
References embutil::byteswap(), config_block_, create(), r, and readReg().
Referenced by start_().
registerReadCallback() [1/2]
void embdrv::vl53l1x::registerReadCallback (const read_cb_t & cb) inline final virtual
Register a callback for the read() function.
The read() function works asynchronously, and the result will be provided to consumers through a callback function. When the read() operation completes, the callback will be invoked with the result.
This function must be implemented by the derived class.
Parameters
cb The functor which will be called when read() completes.
Implements embvm::tof::sensor.
References read_cb_list_.
registerReadCallback() [2/2]
void embdrv::vl53l1x::registerReadCallback (read_cb_t && cb) inline final virtual
Register a callback for the read() function.
The read() function works asynchronously, and the result will be provided to consumers through a callback function. When the read() operation completes, the callback will be invoked with the result.
This function must be implemented by the derived class.
Parameters
cb The functor which will be called when read() completes.
Implements embvm::tof::sensor.
References read_cb_list_.
registerSignalRateCallback() [1/2]
void embdrv::vl53l1x::registerSignalRateCallback (const rate_cb_t & cb) inline
Register a callback for use with the signalRate() function.
Parameters
cb The callback to invoke hen signalRate() completes.
References rate_cb_list_.
registerSignalRateCallback() [2/2]
void embdrv::vl53l1x::registerSignalRateCallback (rate_cb_t && cb) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References rate_cb_list_.
registerStatusCallback() [1/2]
void embdrv::vl53l1x::registerStatusCallback (const status_cb_t & cb) inline
Register a callback for use with the rangeStatus() function.
Parameters
cb The callback to invoke when rangeStatus() completes.
References status_cb_list_.
registerStatusCallback() [2/2]
void embdrv::vl53l1x::registerStatusCallback (status_cb_t && cb) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References status_cb_list_.
reset()
void vl53l1x::reset () final virtual
Reset the ToF sensor.
Implements embvm::tof::sensor.
References destroy(), embvm::i2c::ok, UINT8_C, and writeReg().
Referenced by start_().
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
signalRate()
void vl53l1x::signalRate ()
Get the current signal rate.
When called, registered signal rate callbacks will be invoked with the signal rate. To register a callback, use registerSignalRateCallback().
References create(), embvm::i2c::ok, r, rate_cb_list_, and readReg().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void vl53l1x::start_ () final protected virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::tof::sensor.
References checkModelID(), i2c_, readOscillatorCal(), readTrim(), reset(), embvm::DriverBase::start(), and embvm::DriverBase::started().
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
startMeasurement()
void vl53l1x::startMeasurement () private
Trigger a range measurement.
References address_, config_block_, i2c_, t, and embvm::i2c::write.
Referenced by kickoffMeasurementOnceFirmwareReady().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void vl53l1x::stop_ () final protected virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::tof::sensor.
type()
static constexpr embvm::DriverType embvm::tof::sensor::type () inline static inherited
ToF Driver Type ID.
Returns
ToF type ID.
References embvm::TIME_OF_FLIGHT.
writeReg()
void vl53l1x::writeReg (uint16_t reg, const uint8_t * tx_buffer, size_t tx_size, const embvm::i2c::master::cb_t & cb) private
Convenience function to write to a register on the VL51L1X device.
Parameters
reg The register to write to.
tx_buffer The buffer containing the tx data to send to the target register.
tx_size The number of bytes to transmit
cb The callback function to invoke when the register write completes.
References address_, embutil::byteswap(), create(), i2c_, t, and embvm::i2c::write.
Referenced by clearInterrupt(), mode(), and reset().
Member Data Documentation
address_
const uint8_t embdrv::vl53l1x::address_ private
The I2C address for the VL53L1X.
Referenced by readReg(), startMeasurement(), and writeReg().
config_block_
std::array<uint8_t, 137> embdrv::vl53l1x::config_block_ private
Initial value:
= {
        0x00, 0x00, 0x29, 0x02, 0x10, 0x00, 0x28, 0xBC, 0x7A, 0x81,
        0x80, 0x07, 0x95, 0x00, 0xED, 0xFF, 0xF7, 0xFD,
        0x9E, 0x0E, 0x00, 0x10, 0x01, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x34, 0x00,
        0x28, 0x00, 0x0D, 0x0A, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x11,
        0x02, 0x00, 0x02, 0x08, 0x00, 0x08, 0x10, 0x01,
        0x01, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x02,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x0B, 0x00,
        0x00, 0x02, 0x0A, 0x21, 0x00, 0x00, 0x02, 0x00,
        0x00, 0x00, 0x00, 0xC8, 0x00, 0x00, 0x38, 0xFF,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x91, 0x0F,
        0x00, 0xA5, 0x0D, 0x00, 0x80, 0x00, 0x0C, 0x08,
        0xB8, 0x00, 0x00, 0x00, 0x00, 0x0E, 0x10, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x0F,
        0x0D, 0x0E, 0x0E, 0x01, 0x00, 0x02, 0xC7, 0xFF,
        0x8B, 0x00, 0x00, 0x00, 0x01, 0x01, 0x40
    }
Referenced by readTrim(), and startMeasurement().
i2c_
embvm::i2c::master& embdrv::vl53l1x::i2c_ private
The I2C master bus that this device is connected to.
Referenced by readReg(), start_(), startMeasurement(), and writeReg().
i2c_pool_
etl::generic_pool<sizeof(uint32_t), alignof(uint32_t), 64> embdrv::vl53l1x::i2c_pool_ {} private
Static memory pool used for I2C transactions.
Referenced by create(), and destroy().
lock_
std::mutex embdrv::vl53l1x::lock_ {} private
mode_
tof::mode embvm::tof::sensor::mode_ = tof::mode::defaultRange protected inherited
The configured ranging mode for the ToF sensor.
Referenced by embvm::tof::sensor::mode().
model_id_
uint8_t embdrv::vl53l1x::model_id_ = 0 private
The model ID for the VL53L1X, read from the device during start().
Referenced by checkModelID().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
osc_calibrate_val_
uint16_t embdrv::vl53l1x::osc_calibrate_val_ = 0 private
Referenced by readOscillatorCal().
rate_cb_list_
etl::list<rate_cb_t, 2> embdrv::vl53l1x::rate_cb_list_ {} private
List that stores the signalRate() callback functions.
Referenced by registerSignalRateCallback(), and signalRate().
read_cb_list_
etl::list<read_cb_t, 2> embdrv::vl53l1x::read_cb_list_ {} private
List that stores the read() callback functions.
Referenced by readData(), and registerReadCallback().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
status_cb_list_
etl::list<status_cb_t, 2> embdrv::vl53l1x::status_cb_list_ {} private
List that stores the rangeStatus() callback functions.
Referenced by rangeStatusCb(), and registerStatusCallback().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().