Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/k_cosf.c File Reference
k_cosf.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float __kernel_cosdf (double x)
Variables
static const double one = 1.0
static const double C0 = -0x1ffffffd0c5e81.0p-54
static const double C1 = 0x155553e1053a42.0p-57
static const double C2 = -0x16c087e80f1e27.0p-62
static const double C3 = 0x199342e0ee5069.0p-68
Function Documentation
__kernel_cosdf()
OLM_DLLEXPORT float __kernel_cosdf (double x)
References C0, C1, C2, C3, one, r, w, and z.
Referenced by cosf(), sin_pif(), and sinf().
Variable Documentation
C0
const double C0 = -0x1ffffffd0c5e81.0p-54 static
Referenced by __kernel_cosdf().
C1
const double C1 = 0x155553e1053a42.0p-57 static
Referenced by __kernel_cosdf().
C2
const double C2 = -0x16c087e80f1e27.0p-62 static
Referenced by __kernel_cosdf().
C3
const double C3 = 0x199342e0ee5069.0p-68 static
Referenced by __kernel_cosdf().
one
const double one = 1.0 static
Referenced by __kernel_cosdf().