Embedded Artistry Framework: src/drivers/aardvark/vendor/aardvark.h File Reference
aardvark.h File Reference
#include <stdint.h>
Classes
struct AardvarkVersion
struct AardvarkExt
Macros
#define TOTALPHASE_DATA_TYPES
#define AA_DEBUG 0
#define AA_HEADER_VERSION 0x050a /* v5.10 */
#define AA_PORT_NOT_FREE 0x8000
#define AA_FEATURE_SPI 0x00000001
#define AA_FEATURE_I2C 0x00000002
#define AA_FEATURE_GPIO 0x00000008
#define AA_FEATURE_I2C_MONITOR 0x00000010
#define AA_LOG_STDOUT 1
#define AA_LOG_STDERR 2
#define AA_CONFIG_SPI_MASK 0x00000001
#define AA_CONFIG_I2C_MASK 0x00000002
#define AA_TARGET_POWER_NONE 0x00
#define AA_TARGET_POWER_BOTH 0x03
#define AA_TARGET_POWER_QUERY 0x80
#define AA_ASYNC_NO_DATA 0x00000000
#define AA_ASYNC_I2C_READ 0x00000001
#define AA_ASYNC_I2C_WRITE 0x00000002
#define AA_ASYNC_SPI 0x00000004
#define AA_ASYNC_I2C_MONITOR 0x00000008
#define AA_I2C_MONITOR_DATA 0x00ff
#define AA_I2C_MONITOR_NACK 0x0100
#define AA_I2C_MONITOR_CMD_START 0xff00
#define AA_I2C_MONITOR_CMD_STOP 0xff01
#define AA_I2C_PULLUP_NONE 0x00
#define AA_I2C_PULLUP_BOTH 0x03
#define AA_I2C_PULLUP_QUERY 0x80
#define AA_GPIO_DIR_INPUT 0
#define AA_GPIO_DIR_OUTPUT 1
#define AA_GPIO_PULLUP_OFF 0
#define AA_GPIO_PULLUP_ON 1
Typedefs
typedef uint8_t u08
typedef uint16_t u16
typedef uint32_t u32
typedef uint64_t u64
typedef int8_t s08
typedef int16_t s16
typedef int32_t s32
typedef int64_t s64
typedef float f32
typedef double f64
typedef enum AardvarkStatus AardvarkStatus
typedef int Aardvark
typedef u08 aa_u08
typedef u16 aa_u16
typedef u32 aa_u32
typedef s08 aa_s08
typedef s16 aa_s16
typedef s32 aa_s32
typedef struct AardvarkVersion AardvarkVersion
typedef struct AardvarkExt AardvarkExt
typedef enum AardvarkConfig AardvarkConfig
typedef enum AardvarkI2cFlags AardvarkI2cFlags
typedef enum AardvarkI2cStatus AardvarkI2cStatus
typedef enum AardvarkSpiPolarity AardvarkSpiPolarity
typedef enum AardvarkSpiPhase AardvarkSpiPhase
typedef enum AardvarkSpiBitorder AardvarkSpiBitorder
typedef enum AardvarkSpiSSPolarity AardvarkSpiSSPolarity
typedef enum AardvarkGpioBits AardvarkGpioBits
Enumerations
enum AardvarkStatus {
AA_OK = 0, AA_UNABLE_TO_LOAD_LIBRARY = -1, AA_UNABLE_TO_LOAD_DRIVER = -2, AA_UNABLE_TO_LOAD_FUNCTION = -3,
AA_INCOMPATIBLE_LIBRARY = -4, AA_INCOMPATIBLE_DEVICE = -5, AA_COMMUNICATION_ERROR = -6, AA_UNABLE_TO_OPEN = -7,
AA_UNABLE_TO_CLOSE = -8, AA_INVALID_HANDLE = -9, AA_CONFIG_ERROR = -10, AA_I2C_NOT_AVAILABLE = -100,
AA_I2C_NOT_ENABLED = -101, AA_I2C_READ_ERROR = -102, AA_I2C_WRITE_ERROR = -103, AA_I2C_SLAVE_BAD_CONFIG = -104,
AA_I2C_SLAVE_READ_ERROR = -105, AA_I2C_SLAVE_TIMEOUT = -106, AA_I2C_DROPPED_EXCESS_BYTES = -107, AA_I2C_BUS_ALREADY_FREE = -108,
AA_SPI_NOT_AVAILABLE = -200, AA_SPI_NOT_ENABLED = -201, AA_SPI_WRITE_ERROR = -202, AA_SPI_SLAVE_READ_ERROR = -203,
AA_SPI_SLAVE_TIMEOUT = -204, AA_SPI_DROPPED_EXCESS_BYTES = -205, AA_GPIO_NOT_AVAILABLE = -400, AA_I2C_MONITOR_NOT_AVAILABLE = -500,
AA_I2C_MONITOR_NOT_ENABLED = -501
}
enum AardvarkConfig {
AA_CONFIG_GPIO_ONLY = 0x00, AA_CONFIG_SPI_GPIO = 0x01, AA_CONFIG_GPIO_I2C = 0x02, AA_CONFIG_SPI_I2C = 0x03,
AA_CONFIG_QUERY = 0x80
}
enum AardvarkI2cFlags {
AA_I2C_NO_FLAGS = 0x00, AA_I2C_10_BIT_ADDR = 0x01, AA_I2C_COMBINED_FMT = 0x02, AA_I2C_NO_STOP = 0x04,
AA_I2C_SIZED_READ = 0x10, AA_I2C_SIZED_READ_EXTRA1 = 0x20
}
enum AardvarkI2cStatus {
AA_I2C_STATUS_OK = 0, AA_I2C_STATUS_BUS_ERROR = 1, AA_I2C_STATUS_SLA_ACK = 2, AA_I2C_STATUS_SLA_NACK = 3,
AA_I2C_STATUS_DATA_NACK = 4, AA_I2C_STATUS_ARB_LOST = 5, AA_I2C_STATUS_BUS_LOCKED = 6, AA_I2C_STATUS_LAST_DATA_ACK = 7
}
enum AardvarkSpiPolarity { AA_SPI_POL_RISING_FALLING = 0, AA_SPI_POL_FALLING_RISING = 1 }
enum AardvarkSpiPhase { AA_SPI_PHASE_SAMPLE_SETUP = 0, AA_SPI_PHASE_SETUP_SAMPLE = 1 }
enum AardvarkSpiBitorder { AA_SPI_BITORDER_MSB = 0, AA_SPI_BITORDER_LSB = 1 }
enum AardvarkSpiSSPolarity { AA_SPI_SS_ACTIVE_LOW = 0, AA_SPI_SS_ACTIVE_HIGH = 1 }
enum AardvarkGpioBits {
AA_GPIO_SCL = 0x01, AA_GPIO_SDA = 0x02, AA_GPIO_MISO = 0x04, AA_GPIO_SCK = 0x08,
AA_GPIO_MOSI = 0x10, AA_GPIO_SS = 0x20
}
Functions
int aa_find_devices (int num_devices, u16 *devices)
int aa_find_devices_ext (int num_devices, u16 *devices, int num_ids, u32 *unique_ids)
Aardvark aa_open (int port_number)
Aardvark aa_open_ext (int port_number, AardvarkExt *aa_ext)
int aa_close (Aardvark aardvark)
int aa_port (Aardvark aardvark)
int aa_features (Aardvark aardvark)
u32 aa_unique_id (Aardvark aardvark)
const char * aa_status_string (int status)
int aa_log (Aardvark aardvark, int level, int handle)
int aa_version (Aardvark aardvark, AardvarkVersion *version)
int aa_configure (Aardvark aardvark, AardvarkConfig config)
int aa_target_power (Aardvark aardvark, u08 power_mask)
u32 aa_sleep_ms (u32 milliseconds)
int aa_async_poll (Aardvark aardvark, int timeout)
int aa_i2c_free_bus (Aardvark aardvark)
int aa_i2c_bitrate (Aardvark aardvark, int bitrate_khz)
int aa_i2c_bus_timeout (Aardvark aardvark, u16 timeout_ms)
int aa_i2c_read (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, u08 *data_in)
int aa_i2c_read_ext (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, u08 *data_in, u16 *num_read)
int aa_i2c_write (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, const u08 *data_out)
int aa_i2c_write_ext (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, const u08 *data_out, u16 *num_written)
int aa_i2c_write_read (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 out_num_bytes, const u08 *out_data, u16 *num_written, u16 in_num_bytes, u08 *in_data, u16 *num_read)
int aa_i2c_slave_enable (Aardvark aardvark, u08 addr, u16 maxTxBytes, u16 maxRxBytes)
int aa_i2c_slave_disable (Aardvark aardvark)
int aa_i2c_slave_set_response (Aardvark aardvark, u08 num_bytes, const u08 *data_out)
int aa_i2c_slave_write_stats (Aardvark aardvark)
int aa_i2c_slave_read (Aardvark aardvark, u08 *addr, u16 num_bytes, u08 *data_in)
int aa_i2c_slave_write_stats_ext (Aardvark aardvark, u16 *num_written)
int aa_i2c_slave_read_ext (Aardvark aardvark, u08 *addr, u16 num_bytes, u08 *data_in, u16 *num_read)
int aa_i2c_monitor_enable (Aardvark aardvark)
int aa_i2c_monitor_disable (Aardvark aardvark)
int aa_i2c_monitor_read (Aardvark aardvark, u16 num_bytes, u16 *data)
int aa_i2c_pullup (Aardvark aardvark, u08 pullup_mask)
int aa_spi_bitrate (Aardvark aardvark, int bitrate_khz)
int aa_spi_configure (Aardvark aardvark, AardvarkSpiPolarity polarity, AardvarkSpiPhase phase, AardvarkSpiBitorder bitorder)
int aa_spi_write (Aardvark aardvark, u16 out_num_bytes, const u08 *data_out, u16 in_num_bytes, u08 *data_in)
int aa_spi_slave_enable (Aardvark aardvark)
int aa_spi_slave_disable (Aardvark aardvark)
int aa_spi_slave_set_response (Aardvark aardvark, u08 num_bytes, const u08 *data_out)
int aa_spi_slave_read (Aardvark aardvark, u16 num_bytes, u08 *data_in)
int aa_spi_master_ss_polarity (Aardvark aardvark, AardvarkSpiSSPolarity polarity)
int aa_gpio_direction (Aardvark aardvark, u08 direction_mask)
int aa_gpio_pullup (Aardvark aardvark, u08 pullup_mask)
int aa_gpio_get (Aardvark aardvark)
int aa_gpio_set (Aardvark aardvark, u08 value)
int aa_gpio_change (Aardvark aardvark, u16 timeout)
Class Documentation
AardvarkVersion
struct AardvarkVersion
Class Members
u16 api_req_by_sw
u16 firmware
u16 fw_req_by_sw
u16 hardware
u16 software
u16 sw_req_by_fw
AardvarkExt
struct AardvarkExt
Class Members
int features
AardvarkVersion version
Macro Definition Documentation
AA_ASYNC_I2C_MONITOR
#define AA_ASYNC_I2C_MONITOR 0x00000008
AA_ASYNC_I2C_READ
#define AA_ASYNC_I2C_READ 0x00000001
AA_ASYNC_I2C_WRITE
#define AA_ASYNC_I2C_WRITE 0x00000002
AA_ASYNC_NO_DATA
#define AA_ASYNC_NO_DATA 0x00000000
AA_ASYNC_SPI
#define AA_ASYNC_SPI 0x00000004
AA_CONFIG_I2C_MASK
#define AA_CONFIG_I2C_MASK 0x00000002
AA_CONFIG_SPI_MASK
#define AA_CONFIG_SPI_MASK 0x00000001
AA_DEBUG
#define AA_DEBUG 0
AA_FEATURE_GPIO
#define AA_FEATURE_GPIO 0x00000008
AA_FEATURE_I2C
#define AA_FEATURE_I2C 0x00000002
AA_FEATURE_I2C_MONITOR
#define AA_FEATURE_I2C_MONITOR 0x00000010
AA_FEATURE_SPI
#define AA_FEATURE_SPI 0x00000001
AA_GPIO_DIR_INPUT
#define AA_GPIO_DIR_INPUT 0
AA_GPIO_DIR_OUTPUT
#define AA_GPIO_DIR_OUTPUT 1
AA_GPIO_PULLUP_OFF
#define AA_GPIO_PULLUP_OFF 0
AA_GPIO_PULLUP_ON
#define AA_GPIO_PULLUP_ON 1
AA_HEADER_VERSION
#define AA_HEADER_VERSION 0x050a /* v5.10 */
AA_I2C_MONITOR_CMD_START
#define AA_I2C_MONITOR_CMD_START 0xff00
AA_I2C_MONITOR_CMD_STOP
#define AA_I2C_MONITOR_CMD_STOP 0xff01
AA_I2C_MONITOR_DATA
#define AA_I2C_MONITOR_DATA 0x00ff
AA_I2C_MONITOR_NACK
#define AA_I2C_MONITOR_NACK 0x0100
AA_I2C_PULLUP_BOTH
#define AA_I2C_PULLUP_BOTH 0x03
AA_I2C_PULLUP_NONE
#define AA_I2C_PULLUP_NONE 0x00
AA_I2C_PULLUP_QUERY
#define AA_I2C_PULLUP_QUERY 0x80
AA_LOG_STDERR
#define AA_LOG_STDERR 2
AA_LOG_STDOUT
#define AA_LOG_STDOUT 1
AA_PORT_NOT_FREE
#define AA_PORT_NOT_FREE 0x8000
AA_TARGET_POWER_BOTH
#define AA_TARGET_POWER_BOTH 0x03
AA_TARGET_POWER_NONE
#define AA_TARGET_POWER_NONE 0x00
AA_TARGET_POWER_QUERY
#define AA_TARGET_POWER_QUERY 0x80
TOTALPHASE_DATA_TYPES
#define TOTALPHASE_DATA_TYPES
Typedef Documentation
aa_s08
typedef s08 aa_s08
aa_s16
typedef s16 aa_s16
aa_s32
typedef s32 aa_s32
aa_u08
typedef u08 aa_u08
aa_u16
typedef u16 aa_u16
aa_u32
typedef u32 aa_u32
Aardvark
typedef int Aardvark
AardvarkConfig
typedef enum AardvarkConfig AardvarkConfig
AardvarkExt
typedef struct AardvarkExt AardvarkExt
AardvarkGpioBits
typedef enum AardvarkGpioBits AardvarkGpioBits
AardvarkI2cFlags
typedef enum AardvarkI2cFlags AardvarkI2cFlags
AardvarkI2cStatus
typedef enum AardvarkI2cStatus AardvarkI2cStatus
AardvarkSpiBitorder
typedef enum AardvarkSpiBitorder AardvarkSpiBitorder
AardvarkSpiPhase
typedef enum AardvarkSpiPhase AardvarkSpiPhase
AardvarkSpiPolarity
typedef enum AardvarkSpiPolarity AardvarkSpiPolarity
AardvarkSpiSSPolarity
typedef enum AardvarkSpiSSPolarity AardvarkSpiSSPolarity
AardvarkStatus
typedef enum AardvarkStatus AardvarkStatus
AardvarkVersion
typedef struct AardvarkVersion AardvarkVersion
f32
typedef float f32
f64
typedef double f64
s08
typedef int8_t s08
s16
typedef int16_t s16
s32
typedef int32_t s32
s64
typedef int64_t s64
u08
typedef uint8_t u08
u16
typedef uint16_t u16
u32
typedef uint32_t u32
u64
typedef uint64_t u64
Enumeration Type Documentation
AardvarkConfig
enum AardvarkConfig
Enumerator
AA_CONFIG_GPIO_ONLY
AA_CONFIG_SPI_GPIO
AA_CONFIG_GPIO_I2C
AA_CONFIG_SPI_I2C
AA_CONFIG_QUERY
AardvarkGpioBits
enum AardvarkGpioBits
Enumerator
AA_GPIO_SCL
AA_GPIO_SDA
AA_GPIO_MISO
AA_GPIO_SCK
AA_GPIO_MOSI
AA_GPIO_SS
AardvarkI2cFlags
enum AardvarkI2cFlags
Enumerator
AA_I2C_NO_FLAGS
AA_I2C_10_BIT_ADDR
AA_I2C_COMBINED_FMT
AA_I2C_NO_STOP
AA_I2C_SIZED_READ
AA_I2C_SIZED_READ_EXTRA1
AardvarkI2cStatus
enum AardvarkI2cStatus
Enumerator
AA_I2C_STATUS_OK
AA_I2C_STATUS_BUS_ERROR
AA_I2C_STATUS_SLA_ACK
AA_I2C_STATUS_SLA_NACK
AA_I2C_STATUS_DATA_NACK
AA_I2C_STATUS_ARB_LOST
AA_I2C_STATUS_BUS_LOCKED
AA_I2C_STATUS_LAST_DATA_ACK
AardvarkSpiBitorder
enum AardvarkSpiBitorder
Enumerator
AA_SPI_BITORDER_MSB
AA_SPI_BITORDER_LSB
AardvarkSpiPhase
enum AardvarkSpiPhase
Enumerator
AA_SPI_PHASE_SAMPLE_SETUP
AA_SPI_PHASE_SETUP_SAMPLE
AardvarkSpiPolarity
enum AardvarkSpiPolarity
Enumerator
AA_SPI_POL_RISING_FALLING
AA_SPI_POL_FALLING_RISING
AardvarkSpiSSPolarity
enum AardvarkSpiSSPolarity
Enumerator
AA_SPI_SS_ACTIVE_LOW
AA_SPI_SS_ACTIVE_HIGH
AardvarkStatus
enum AardvarkStatus
Enumerator
AA_OK
AA_UNABLE_TO_LOAD_LIBRARY
AA_UNABLE_TO_LOAD_DRIVER
AA_UNABLE_TO_LOAD_FUNCTION
AA_INCOMPATIBLE_LIBRARY
AA_INCOMPATIBLE_DEVICE
AA_COMMUNICATION_ERROR
AA_UNABLE_TO_OPEN
AA_UNABLE_TO_CLOSE
AA_INVALID_HANDLE
AA_CONFIG_ERROR
AA_I2C_NOT_AVAILABLE
AA_I2C_NOT_ENABLED
AA_I2C_READ_ERROR
AA_I2C_WRITE_ERROR
AA_I2C_SLAVE_BAD_CONFIG
AA_I2C_SLAVE_READ_ERROR
AA_I2C_SLAVE_TIMEOUT
AA_I2C_DROPPED_EXCESS_BYTES
AA_I2C_BUS_ALREADY_FREE
AA_SPI_NOT_AVAILABLE
AA_SPI_NOT_ENABLED
AA_SPI_WRITE_ERROR
AA_SPI_SLAVE_READ_ERROR
AA_SPI_SLAVE_TIMEOUT
AA_SPI_DROPPED_EXCESS_BYTES
AA_GPIO_NOT_AVAILABLE
AA_I2C_MONITOR_NOT_AVAILABLE
AA_I2C_MONITOR_NOT_ENABLED
Function Documentation
aa_async_poll()
int aa_async_poll (Aardvark aardvark, int timeout)
References _loadFunction(), and c_aa_async_poll.
Referenced by dump().
aa_close()
int aa_close (Aardvark aardvark)
References _loadFunction(), and c_aa_close.
Referenced by main(), and embdrv::aardvarkAdapter::stop_().
aa_configure()
int aa_configure (Aardvark aardvark, AardvarkConfig config)
References _loadFunction(), and c_aa_configure.
Referenced by main(), and embdrv::aardvarkAdapter::mode().
aa_features()
int aa_features (Aardvark aardvark)
References _loadFunction(), and c_aa_features.
aa_find_devices()
int aa_find_devices (int num_devices, u16 * devices)
References _loadFunction(), and c_aa_find_devices.
aa_find_devices_ext()
int aa_find_devices_ext (int num_devices, u16 * devices, int num_ids, u32 * unique_ids)
References _loadFunction(), and c_aa_find_devices_ext.
aa_gpio_change()
int aa_gpio_change (Aardvark aardvark, u16 timeout)
References _loadFunction(), and c_aa_gpio_change.
Referenced by main().
aa_gpio_direction()
int aa_gpio_direction (Aardvark aardvark, u08 direction_mask)
References _loadFunction(), and c_aa_gpio_direction.
Referenced by main(), and embdrv::aardvarkGPIOOutput< 5 >::start_().
aa_gpio_get()
int aa_gpio_get (Aardvark aardvark)
References _loadFunction(), and c_aa_gpio_get.
Referenced by embdrv::aardvarkGPIOInput< 4 >::get(), and main().
aa_gpio_pullup()
int aa_gpio_pullup (Aardvark aardvark, u08 pullup_mask)
References _loadFunction(), and c_aa_gpio_pullup.
Referenced by main(), and embdrv::aardvarkAdapter::pullup().
aa_gpio_set()
int aa_gpio_set (Aardvark aardvark, u08 value)
References _loadFunction(), and c_aa_gpio_set.
Referenced by main(), and embdrv::aardvarkGPIOOutput< 5 >::set().
aa_i2c_bitrate()
int aa_i2c_bitrate (Aardvark aardvark, int bitrate_khz)
References _loadFunction(), and c_aa_i2c_bitrate.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), and main().
aa_i2c_bus_timeout()
int aa_i2c_bus_timeout (Aardvark aardvark, u16 timeout_ms)
References _loadFunction(), and c_aa_i2c_bus_timeout.
Referenced by embdrv::aardvarkI2CMaster::configure_(), and main().
aa_i2c_free_bus()
int aa_i2c_free_bus (Aardvark aardvark)
References _loadFunction(), and c_aa_i2c_free_bus.
Referenced by embdrv::aardvarkI2CMaster::process_().
aa_i2c_monitor_disable()
int aa_i2c_monitor_disable (Aardvark aardvark)
References _loadFunction(), and c_aa_i2c_monitor_disable.
aa_i2c_monitor_enable()
int aa_i2c_monitor_enable (Aardvark aardvark)
References _loadFunction(), and c_aa_i2c_monitor_enable.
aa_i2c_monitor_read()
int aa_i2c_monitor_read (Aardvark aardvark, u16 num_bytes, u16 * data)
References _loadFunction(), and c_aa_i2c_monitor_read.
aa_i2c_pullup()
int aa_i2c_pullup (Aardvark aardvark, u08 pullup_mask)
References _loadFunction(), and c_aa_i2c_pullup.
Referenced by embdrv::aardvarkAdapter::i2cPullups(), main(), and embdrv::aardvarkAdapter::targetPower().
aa_i2c_read()
int aa_i2c_read (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, u08 * data_in)
References _loadFunction(), c_aa_i2c_read, and data_in.
Referenced by _readMemory().
aa_i2c_read_ext()
int aa_i2c_read_ext (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, u08 * data_in, u16 * num_read)
References _loadFunction(), c_aa_i2c_read_ext, and data_in.
Referenced by embdrv::aardvarkI2CMaster::process_().
aa_i2c_slave_disable()
int aa_i2c_slave_disable (Aardvark aardvark)
References _loadFunction(), and c_aa_i2c_slave_disable.
Referenced by main().
aa_i2c_slave_enable()
int aa_i2c_slave_enable (Aardvark aardvark, u08 addr, u16 maxTxBytes, u16 maxRxBytes)
References _loadFunction(), and c_aa_i2c_slave_enable.
Referenced by main().
aa_i2c_slave_read()
int aa_i2c_slave_read (Aardvark aardvark, u08 * addr, u16 num_bytes, u08 * data_in)
References _loadFunction(), c_aa_i2c_slave_read, and data_in.
Referenced by dump().
aa_i2c_slave_read_ext()
int aa_i2c_slave_read_ext (Aardvark aardvark, u08 * addr, u16 num_bytes, u08 * data_in, u16 * num_read)
References _loadFunction(), c_aa_i2c_slave_read_ext, and data_in.
aa_i2c_slave_set_response()
int aa_i2c_slave_set_response (Aardvark aardvark, u08 num_bytes, const u08 * data_out)
References _loadFunction(), and c_aa_i2c_slave_set_response.
Referenced by main().
aa_i2c_slave_write_stats()
int aa_i2c_slave_write_stats (Aardvark aardvark)
References _loadFunction(), and c_aa_i2c_slave_write_stats.
Referenced by dump().
aa_i2c_slave_write_stats_ext()
int aa_i2c_slave_write_stats_ext (Aardvark aardvark, u16 * num_written)
References _loadFunction(), and c_aa_i2c_slave_write_stats_ext.
aa_i2c_write()
int aa_i2c_write (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, const u08 * data_out)
References _loadFunction(), and c_aa_i2c_write.
Referenced by _readMemory(), _writeMemory(), and flash_lights().
aa_i2c_write_ext()
int aa_i2c_write_ext (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, const u08 * data_out, u16 * num_written)
References _loadFunction(), and c_aa_i2c_write_ext.
Referenced by embdrv::aardvarkI2CMaster::process_().
aa_i2c_write_read()
int aa_i2c_write_read (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 out_num_bytes, const u08 * out_data, u16 * num_written, u16 in_num_bytes, u08 * in_data, u16 * num_read)
References _loadFunction(), and c_aa_i2c_write_read.
Referenced by embdrv::aardvarkI2CMaster::process_().
aa_log()
int aa_log (Aardvark aardvark, int level, int handle)
References _loadFunction(), and c_aa_log.
Referenced by main().
aa_open()
Aardvark aa_open (int port_number)
References _loadFunction(), and c_aa_open.
Referenced by main(), and embdrv::aardvarkAdapter::start_().
aa_open_ext()
Aardvark aa_open_ext (int port_number, AardvarkExt * aa_ext)
References _loadFunction(), and c_aa_open_ext.
Referenced by main().
aa_port()
int aa_port (Aardvark aardvark)
References _loadFunction(), and c_aa_port.
aa_sleep_ms()
u32 aa_sleep_ms (u32 milliseconds)
References _loadFunction(), and c_aa_sleep_ms.
Referenced by _writeMemory(), and flash_lights().
aa_spi_bitrate()
int aa_spi_bitrate (Aardvark aardvark, int bitrate_khz)
References _loadFunction(), and c_aa_spi_bitrate.
Referenced by embdrv::aardvarkSPIMaster::baudrate_(), and main().
aa_spi_configure()
int aa_spi_configure (Aardvark aardvark, AardvarkSpiPolarity polarity, AardvarkSpiPhase phase, AardvarkSpiBitorder bitorder)
References _loadFunction(), and c_aa_spi_configure.
Referenced by embdrv::aardvarkSPIMaster::configure_(), and main().
aa_spi_master_ss_polarity()
int aa_spi_master_ss_polarity (Aardvark aardvark, AardvarkSpiSSPolarity polarity)
References _loadFunction(), and c_aa_spi_master_ss_polarity.
aa_spi_slave_disable()
int aa_spi_slave_disable (Aardvark aardvark)
References _loadFunction(), and c_aa_spi_slave_disable.
Referenced by main().
aa_spi_slave_enable()
int aa_spi_slave_enable (Aardvark aardvark)
References _loadFunction(), and c_aa_spi_slave_enable.
Referenced by main().
aa_spi_slave_read()
int aa_spi_slave_read (Aardvark aardvark, u16 num_bytes, u08 * data_in)
References _loadFunction(), c_aa_spi_slave_read, and data_in.
Referenced by dump().
aa_spi_slave_set_response()
int aa_spi_slave_set_response (Aardvark aardvark, u08 num_bytes, const u08 * data_out)
References _loadFunction(), and c_aa_spi_slave_set_response.
Referenced by main().
aa_spi_write()
int aa_spi_write (Aardvark aardvark, u16 out_num_bytes, const u08 * data_out, u16 in_num_bytes, u08 * data_in)
References _loadFunction(), c_aa_spi_write, and data_in.
Referenced by _readMemory(), _writeMemory(), and embdrv::aardvarkSPIMaster::process_().
aa_status_string()
const char* aa_status_string (int status)
References _loadFunction(), and c_aa_status_string.
Referenced by _readMemory(), dump(), and main().
aa_target_power()
int aa_target_power (Aardvark aardvark, u08 power_mask)
References _loadFunction(), and c_aa_target_power.
Referenced by main(), and embdrv::aardvarkAdapter::targetPower().
aa_unique_id()
u32 aa_unique_id (Aardvark aardvark)
References _loadFunction(), and c_aa_unique_id.
aa_version()
int aa_version (Aardvark aardvark, AardvarkVersion * version)
References _loadFunction(), and c_aa_version.