Embedded Artistry Framework: src/core/boot/boot_sequencer.hpp File Reference
boot_sequencer.hpp File Reference
#include <type_traits>
Classes
class embvm::BootSequencer< TBootStrategy >
Boot sequencer with customizable boot strategy.
Namespaces
embvm
Embedded framework core interfaces, classes, and definitions.
Functions
int main ()
Function for application main entry.
void entry ()
Prototype for our function entry point; can also be an asm symbol.
void CRTStartup ()
We declare this function here because we don't want to include crt.h and Add a dependency on our libc for the test code.
template<class TPlatform >
void main_thread_func () noexcept
Function Documentation
main()
int main ()
Function for application main entry.
References a, abort_program_, aligned_malloc_tests(), allocate_memory(), assert, b, ccheck(), ctype_tests(), U::d, dalign, DEFAULT_TOF_READ_DELAY, fclose(), fopen(), fprintf(), fzcheck(), icheck(), INFINITY, embvm::VirtualPlatformBase< BlinkyDemoPlatform< THWPlatform, TDriverRegistry >, TDriverRegistry >::inst(), isinf, U::L, Lcheck(), logdebug, main2(), malloc_tests(), printf, r, embvm::this_thread::sleep_for(), stdlib_tests(), string_tests(), t, u, and UL.
Referenced by bootSystem(), embvm::BootSequencer< TBootStrategy >::DefaultBootStrategy(), main_thread_func(), and embvm::BootSequencer< TBootStrategy >::OSXSimulatorBootStrategy().