Embedded Artistry Framework: src/stdlibs/libc/openlibm/powerpc/fenv.c File Reference
fenv.c File Reference
#include <openlibm_fenv.h>
Macros
#define __fenv_static
Functions
int feclearexcept (int __excepts)
int fegetexceptflag (fexcept_t *__flagp, int __excepts)
int fesetexceptflag (const fexcept_t *__flagp, int __excepts)
int feraiseexcept (int __excepts)
int fetestexcept (int __excepts)
int fegetround (void)
int fesetround (int __round)
int fegetenv (fenv_t *__envp)
int feholdexcept (fenv_t *__envp)
int fesetenv (const fenv_t *__envp)
int feupdateenv (const fenv_t *__envp)
Variables
const fenv_t __fe_dfl_env = 0x00000000
Macro Definition Documentation
__fenv_static
#define __fenv_static
Function Documentation
feclearexcept()
int feclearexcept (int __excepts) inline
References __fpscr::__bits, __cfc1, __ctc1, __fpscr::__d, __fldenv, __fnclex, __fnstenv, __HAS_SSE, __ldmxcsr, __mffs, __mtfsf, __rfs, __softfloat_float_exception_flags, fenv_t::__status, __stmxcsr, __wfs, _FCSR_CAUSE_SHIFT, FE_ALL_EXCEPT, FE_ALL_INVALID, and FE_INVALID.
fegetenv()
int fegetenv (fenv_t * __envp) inline
References __fpscr::__bits, __cfc1, fenv_t::__control, __fpscr::__d, __fldcw, __fnstenv, __HAS_SSE, __mffs, fenv_t::__mxcsr, __rfs, __set_mxcsr, __softfloat_float_exception_flags, __softfloat_float_exception_mask, __softfloat_float_rounding_mode, __stmxcsr, and fenv_t::__x87.
Referenced by feholdexcept().
fegetexceptflag()
int fegetexceptflag (fexcept_t * __flagp, int __excepts) inline
References __fpscr::__bits, __cfc1, __fpscr::__d, __fnstsw, __HAS_SSE, __mffs, __rfs, __softfloat_float_exception_flags, __stmxcsr, and FE_ALL_EXCEPT.
fegetround()
int fegetround (void) inline
References __fpscr::__bits, __cfc1, __fpscr::__d, __fnstcw, __mffs, __softfloat_float_rounding_mode, and _ROUND_MASK.
feholdexcept()
int feholdexcept (fenv_t * __envp) inline
References __fpscr::__bits, __cfc1, __ctc1, __fpscr::__d, __fnclex, __fnstenv, __HAS_SSE, __ldmxcsr, __mffs, __mtfsf, fenv_t::__mxcsr, __rfs, __set_mxcsr, __softfloat_float_exception_flags, __softfloat_float_exception_mask, __stmxcsr, __wfs, fenv_t::__x87, _ENABLE_MASK, _SSE_EMASK_SHIFT, FE_ALL_EXCEPT, and fegetenv().
feraiseexcept()
int feraiseexcept (int __excepts) inline
References __fpscr::__bits, __cfc1, __ctc1, __fpscr::__d, __fwait, __mffs, __mtfsf, __softfloat_float_raise(), _FCSR_CAUSE_SHIFT, FE_ALL_EXCEPT, FE_INVALID, FE_VXSOFT, and fesetexceptflag().
Referenced by feupdateenv().
fesetenv()
int fesetenv (const fenv_t * __envp) inline
References __fpscr::__bits, __ctc1, __fpscr::__d, __fldenvx, __get_mxcsr, __HAS_SSE, __ldmxcsr, __mtfsf, fenv_t::__mxcsr, __set_mxcsr, __softfloat_float_exception_flags, __softfloat_float_exception_mask, __softfloat_float_rounding_mode, __wfs, and fenv_t::__x87.
Referenced by feupdateenv().
fesetexceptflag()
int fesetexceptflag (const fexcept_t * __flagp, int __excepts) inline
References __fpscr::__bits, __cfc1, __ctc1, __fpscr::__d, __fldenv, __fnstenv, __HAS_SSE, __ldmxcsr, __mffs, __mtfsf, fenv_t::__mxcsr, __rfs, __softfloat_float_exception_flags, fenv_t::__status, __stmxcsr, __wfs, fenv_t::__x87, FE_ALL_EXCEPT, and FE_INVALID.
Referenced by feraiseexcept().
fesetround()
int fesetround (int __round) inline
References __fpscr::__bits, __cfc1, __ctc1, __fpscr::__d, __fldcw, __fnstcw, __HAS_SSE, __ldmxcsr, __mffs, __mtfsf, __softfloat_float_rounding_mode, __stmxcsr, _ROUND_MASK, and _SSE_ROUND_SHIFT.
fetestexcept()
int fetestexcept (int __excepts) inline
References __fpscr::__bits, __cfc1, __fpscr::__d, __fnstsw, __HAS_SSE, __mffs, __rfs, __softfloat_float_exception_flags, __stmxcsr, and FE_ALL_EXCEPT.
feupdateenv()
int feupdateenv (const fenv_t * __envp) inline
References __fpscr::__bits, __cfc1, __fpscr::__d, __fnstsw, __HAS_SSE, __mffs, __mtfsf, __rfs, __softfloat_float_exception_flags, __stmxcsr, __wfs, FE_ALL_EXCEPT, feraiseexcept(), and fesetenv().
Variable Documentation
__fe_dfl_env
const fenv_t __fe_dfl_env = 0x00000000