Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_logf.c File Reference
e_logf.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float __ieee754_logf (float x)
Variables
static const float ln2_hi = 6.9313812256e-01
static const float ln2_lo = 9.0580006145e-06
static const float two25 = 3.355443200e+07
static const float Lg1 = 0xaaaaaa.0p-24
static const float Lg2 = 0xccce13.0p-25
static const float Lg3 = 0x91e9ee.0p-25
static const float Lg4 = 0xf89e26.0p-26
static const float zero = 0.0
Function Documentation
__ieee754_logf()
OLM_DLLEXPORT float __ieee754_logf (float x)
References GET_FLOAT_WORD, k, Lg1, Lg2, Lg3, Lg4, ln2_hi, ln2_lo, R, s, SET_FLOAT_WORD, t1, t2, two25, w, z, and zero.
Referenced by __ieee754_acoshf(), __ieee754_jnf(), __ieee754_lgammaf_r(), __ieee754_y0f(), __ieee754_y1f(), and asinhf().
Variable Documentation
Lg1
const float Lg1 = 0xaaaaaa.0p-24 static
Referenced by __ieee754_logf().
Lg2
const float Lg2 = 0xccce13.0p-25 static
Referenced by __ieee754_logf().
Lg3
const float Lg3 = 0x91e9ee.0p-25 static
Referenced by __ieee754_logf().
Lg4
const float Lg4 = 0xf89e26.0p-26 static
Referenced by __ieee754_logf().
ln2_hi
const float ln2_hi = 6.9313812256e-01 static
Referenced by __ieee754_logf().
ln2_lo
const float ln2_lo = 9.0580006145e-06 static
Referenced by __ieee754_logf().
two25
const float two25 = 3.355443200e+07 static
Referenced by __ieee754_logf().
zero
const float zero = 0.0 static
Referenced by __ieee754_logf().