Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_rem_pio2f.c File Reference
e_rem_pio2f.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
__inline int __ieee754_rem_pio2f (float x, double *y)
Variables
static const double invpio2 = 6.36619772367581382433e-01
static const double pio2_1 = 1.57079631090164184570e+00
static const double pio2_1t = 1.58932547735281966916e-08
Function Documentation
__ieee754_rem_pio2f()
__inline int __ieee754_rem_pio2f (float x, double * y)
References __kernel_rem_pio2(), fn, GET_FLOAT_WORD, invpio2, n, pio2_1, pio2_1t, r, SET_FLOAT_WORD, STRICT_ASSIGN, w, and z.
Referenced by cosf(), sincosf(), sinf(), and tanf().
Variable Documentation
invpio2
const double invpio2 = 6.36619772367581382433e-01 static
Referenced by __ieee754_rem_pio2f().
pio2_1
const double pio2_1 = 1.57079631090164184570e+00 static
Referenced by __ieee754_rem_pio2f().
pio2_1t
const double pio2_1t = 1.58932547735281966916e-08 static
Referenced by __ieee754_rem_pio2f().