Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_copysignf.c File Reference
s_copysignf.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float copysignf (float x, float y)
Function Documentation
copysignf()
OLM_DLLEXPORT float copysignf (float x, float y)
References GET_FLOAT_WORD, and SET_FLOAT_WORD.
Referenced by ccoshf(), cprojf(), csinhf(), csqrtf(), ctanhf(), and scalbnf().