Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_nextafterl.c File Reference
s_nextafterl.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "fpmath.h"
#include "math_private.h"
Functions
OLM_DLLEXPORT long double nextafterl (long double x, long double y)
__strong_reference (nextafterl, nexttowardl)
Function Documentation
__strong_reference()
__strong_reference (nextafterl , nexttowardl)
nextafterl()
OLM_DLLEXPORT long double nextafterl (long double x, long double y)
References IEEEl2bits::bits, IEEEl2bits::e, LDBL_NBIT, mask_nbit_l, and t.
Referenced by add_adjusted(), add_and_denormalize(), and fmal().