Embedded Artistry Framework: src/stdlibs/libc/openlibm/test/libm-test.c File Reference
libm-test.c File Reference
#include "libm-test-ulps.h"
#include <float.h>
#include <openlibm.h>
#include <limits.h>
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
Macros
#define _GNU_SOURCE
#define NO_EXCEPTION 0x0
#define INVALID_EXCEPTION 0x1
#define DIVIDE_BY_ZERO_EXCEPTION 0x2
#define INVALID_EXCEPTION_OK 0x4
#define DIVIDE_BY_ZERO_EXCEPTION_OK 0x8
#define EXCEPTIONS_OK INVALID_EXCEPTION_OK+DIVIDE_BY_ZERO_EXCEPTION_OK
#define IGNORE_ZERO_INF_SIGN 0x10
#define M_PI_6l .52359877559829887307710723054658383L
#define M_E2l 7.389056098930650227230427460575008L
#define M_E3l 20.085536923187667740928529654581719L
#define M_2_SQRT_PIl 3.5449077018110320545963349666822903L /* 2 sqrt (M_PIl) */
#define M_SQRT_PIl 1.7724538509055160272981674833411451L /* sqrt (M_PIl) */
#define M_LOG_SQRT_PIl 0.57236494292470008707171367567652933L /* log(sqrt(M_PIl)) */
#define M_LOG_2_SQRT_PIl 1.265512123484645396488945797134706L /* log(2*sqrt(M_PIl)) */
#define M_PI_34l (M_PIl - M_PI_4l) /* 3*pi/4 */
#define M_PI_34_LOG10El (M_PIl - M_PI_4l) * M_LOG10El
#define M_PI2_LOG10El M_PI_2l * M_LOG10El
#define M_PI4_LOG10El M_PI_4l * M_LOG10El
#define M_PI_LOG10El M_PIl * M_LOG10El
#define M_El 2.7182818284590452353602874713526625L /* e */
#define M_LOG2El 1.4426950408889634073599246810018922L /* log_2 e */
#define M_LOG10El 0.4342944819032518276511289189166051L /* log_10 e */
#define M_LN2l 0.6931471805599453094172321214581766L /* log_e 2 */
#define M_LN10l 2.3025850929940456840179914546843642L /* log_e 10 */
#define M_PIl 3.1415926535897932384626433832795029L /* pi */
#define M_PI_2l 1.5707963267948966192313216916397514L /* pi/2 */
#define M_PI_4l 0.7853981633974483096156608458198757L /* pi/4 */
#define M_1_PIl 0.3183098861837906715377675267450287L /* 1/pi */
#define M_2_PIl 0.6366197723675813430755350534900574L /* 2/pi */
#define M_2_SQRTPIl 1.1283791670955125738961589031215452L /* 2/sqrt(pi) */
#define M_SQRT2l 1.4142135623730950488016887242096981L /* sqrt(2) */
#define M_SQRT1_2l 0.7071067811865475244008443621048490L /* 1/sqrt(2) */
#define MANT_DIG
#define gamma lgamma /* XXX scp XXX */
#define gammaf lgammaf /* XXX scp XXX */
Functions
void FUNC() sincos (FLOAT x, FLOAT *s, FLOAT *c)
static void init_max_error (void)
static void set_max_error (FLOAT current, FLOAT *curr_max_error)
static int print_screen (int ok, int xfail)
static int print_screen_max_error (int ok, int xfail)
static void update_stats (int ok, int xfail)
static void print_ulps (const char *test_name, FLOAT ulp)
static void print_function_ulps (const char *function_name, FLOAT ulp)
static void print_max_error (const char *func_name, FLOAT allowed, int xfail)
static void test_single_exception (const char *test_name, int exception, int exc_flag, int fe_flag, const char *flag_name)
static void test_exceptions (const char *test_name, int exception)
static void check_float_internal (const char *test_name, FLOAT computed, FLOAT expected, FLOAT max_ulp, int xfail, int exceptions, FLOAT *curr_max_error)
static void check_float (const char *test_name, FLOAT computed, FLOAT expected, FLOAT max_ulp, int xfail, int exceptions)
static void check_int (const char *test_name, int computed, int expected, int max_ulp, int xfail, int exceptions)
static void check_long (const char *test_name, long int computed, long int expected, long int max_ulp, int xfail, int exceptions)
static void check_bool (const char *test_name, int computed, int expected, long int max_ulp, int xfail, int exceptions)
static void check_longlong (const char *test_name, long long int computed, long long int expected, long long int max_ulp, int xfail, int exceptions)
static void acos_test (void)
static void acosh_test (void)
static void asin_test (void)
static void asinh_test (void)
static void atan_test (void)
static void atanh_test (void)
static void atan2_test (void)
static void cbrt_test (void)
static void ceil_test (void)
static void copysign_test (void)
static void cos_test (void)
static void cosh_test (void)
static void erf_test (void)
static void erfc_test (void)
static void exp_test (void)
static void exp2_test (void)
static void expm1_test (void)
static void fabs_test (void)
static void fdim_test (void)
static void floor_test (void)
static void fma_test (void)
static void fmax_test (void)
static void fmin_test (void)
static void fmod_test (void)
static void fpclassify_test (void)
static void frexp_test (void)
static void gamma_test (void)
static void hypot_test (void)
static void ilogb_test (void)
static void isfinite_test (void)
static void isnormal_test (void)
static void j0_test (void)
static void j1_test (void)
static void jn_test (void)
static void ldexp_test (void)
static void lgamma_test (void)
static void lrint_test (void)
static void llrint_test (void)
static void log_test (void)
static void log10_test (void)
static void log1p_test (void)
static void log2_test (void)
static void logb_test (void)
static void lround_test (void)
static void llround_test (void)
static void modf_test (void)
static void nearbyint_test (void)
static void nextafter_test (void)
static void pow_test (void)
static void remainder_test (void)
static void remquo_test (void)
static void rint_test (void)
static void round_test (void)
static void scalbn_test (void)
static void scalbln_test (void)
static void signbit_test (void)
static void sin_test (void)
static void sincos_test (void)
static void sinh_test (void)
static void sqrt_test (void)
static void tan_test (void)
static void tanh_test (void)
static void tgamma_test (void)
static void trunc_test (void)
static void y0_test (void)
static void y1_test (void)
static void yn_test (void)
static void initialize (void)
int main (int argc, char **argv)
Variables
static FILE * ulps_file
static int output_ulps
static int noErrors
static int noTests
static int noExcTests
static int noXFails
static int noXPasses
static int verbose
static int output_max_error
static int output_points
static int ignore_max_ulp
static FLOAT minus_zero
static FLOAT plus_zero
static FLOAT plus_infty
static FLOAT minus_infty
static FLOAT nan_value
static FLOAT max_error
static FLOAT real_max_error
static FLOAT imag_max_error
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
DIVIDE_BY_ZERO_EXCEPTION
#define DIVIDE_BY_ZERO_EXCEPTION 0x2
DIVIDE_BY_ZERO_EXCEPTION_OK
#define DIVIDE_BY_ZERO_EXCEPTION_OK 0x8
EXCEPTIONS_OK
#define EXCEPTIONS_OK INVALID_EXCEPTION_OK+DIVIDE_BY_ZERO_EXCEPTION_OK
gamma
#define gamma lgamma /* XXX scp XXX */
gammaf
#define gammaf lgammaf /* XXX scp XXX */
IGNORE_ZERO_INF_SIGN
#define IGNORE_ZERO_INF_SIGN 0x10
INVALID_EXCEPTION
#define INVALID_EXCEPTION 0x1
INVALID_EXCEPTION_OK
#define INVALID_EXCEPTION_OK 0x4
M_1_PIl
#define M_1_PIl 0.3183098861837906715377675267450287L /* 1/pi */
M_2_PIl
#define M_2_PIl 0.6366197723675813430755350534900574L /* 2/pi */
M_2_SQRT_PIl
#define M_2_SQRT_PIl 3.5449077018110320545963349666822903L /* 2 sqrt (M_PIl) */
M_2_SQRTPIl
#define M_2_SQRTPIl 1.1283791670955125738961589031215452L /* 2/sqrt(pi) */
M_E2l
#define M_E2l 7.389056098930650227230427460575008L
M_E3l
#define M_E3l 20.085536923187667740928529654581719L
M_El
#define M_El 2.7182818284590452353602874713526625L /* e */
M_LN10l
#define M_LN10l 2.3025850929940456840179914546843642L /* log_e 10 */
M_LN2l
#define M_LN2l 0.6931471805599453094172321214581766L /* log_e 2 */
M_LOG10El
#define M_LOG10El 0.4342944819032518276511289189166051L /* log_10 e */
M_LOG2El
#define M_LOG2El 1.4426950408889634073599246810018922L /* log_2 e */
M_LOG_2_SQRT_PIl
#define M_LOG_2_SQRT_PIl 1.265512123484645396488945797134706L /* log(2*sqrt(M_PIl)) */
M_LOG_SQRT_PIl
#define M_LOG_SQRT_PIl 0.57236494292470008707171367567652933L /* log(sqrt(M_PIl)) */
M_PI2_LOG10El
#define M_PI2_LOG10El M_PI_2l * M_LOG10El
M_PI4_LOG10El
#define M_PI4_LOG10El M_PI_4l * M_LOG10El
M_PI_2l
#define M_PI_2l 1.5707963267948966192313216916397514L /* pi/2 */
M_PI_34_LOG10El
#define M_PI_34_LOG10El (M_PIl - M_PI_4l) * M_LOG10El
M_PI_34l
#define M_PI_34l (M_PIl - M_PI_4l) /* 3*pi/4 */
M_PI_4l
#define M_PI_4l 0.7853981633974483096156608458198757L /* pi/4 */
M_PI_6l
#define M_PI_6l .52359877559829887307710723054658383L
M_PI_LOG10El
#define M_PI_LOG10El M_PIl * M_LOG10El
M_PIl
#define M_PIl 3.1415926535897932384626433832795029L /* pi */
M_SQRT1_2l
#define M_SQRT1_2l 0.7071067811865475244008443621048490L /* 1/sqrt(2) */
M_SQRT2l
#define M_SQRT2l 1.4142135623730950488016887242096981L /* sqrt(2) */
M_SQRT_PIl
#define M_SQRT_PIl 1.7724538509055160272981674833411451L /* sqrt (M_PIl) */
MANT_DIG
#define MANT_DIG
Value:
CHOOSE ((LDBL_MANT_DIG-1), (DBL_MANT_DIG-1), (FLT_MANT_DIG-1),  \
                         (LDBL_MANT_DIG-1), (DBL_MANT_DIG-1), (FLT_MANT_DIG-1))
NO_EXCEPTION
#define NO_EXCEPTION 0x0
Function Documentation
acos_test()
static void acos_test (void) static
References acos(), check_float(), DELTAacos, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, M_PI_2l, M_PI_6l, M_PIl, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
acosh_test()
static void acosh_test (void) static
References acosh(), check_float(), DELTA16, DELTAacosh, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, minus_infty, nan_value, plus_infty, and print_max_error().
Referenced by main().
asin_test()
static void asin_test (void) static
References asin(), check_float(), DELTA24, DELTA25, DELTA26, DELTA27, DELTA28, DELTAasin, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, M_PI_2l, M_PI_6l, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
asinh_test()
static void asinh_test (void) static
References asinh(), check_float(), DELTA34, DELTAasinh, ENOSYS, errno, FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
atan2_test()
static void atan2_test (void) static
References atan2(), check_float(), DELTA74, DELTA78, DELTAatan2, ENOSYS, errno, FUNC, init_max_error(), M_PI_2l, M_PI_34l, M_PI_4l, M_PIl, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
atan_test()
static void atan_test (void) static
References atan(), check_float(), DELTA42, DELTAatan, ENOSYS, errno, FUNC, init_max_error(), M_PI_2l, M_PI_4l, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
atanh_test()
static void atanh_test (void) static
References atanh(), check_float(), DELTA50, DELTAatanh, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
cbrt_test()
static void cbrt_test (void) static
References cbrt(), check_float(), DELTA347, DELTA349, DELTA350, DELTA351, DELTAcbrt, ENOSYS, errno, FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
ceil_test()
static void ceil_test (void) static
References ceil(), check_float(), FUNC, init_max_error(), M_PIl, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
check_bool()
static void check_bool (const char * test_name, int computed, int expected, long int max_ulp, int xfail, int exceptions) static
References noTests, print_screen(), printf, test_exceptions(), and update_stats().
Referenced by isfinite_test(), isnormal_test(), and signbit_test().
check_float()
static void check_float (const char * test_name, FLOAT computed, FLOAT expected, FLOAT max_ulp, int xfail, int exceptions) static
References check_float_internal(), and max_error.
Referenced by acos_test(), acosh_test(), asin_test(), asinh_test(), atan2_test(), atan_test(), atanh_test(), cbrt_test(), ceil_test(), copysign_test(), cos_test(), cosh_test(), erf_test(), erfc_test(), exp2_test(), exp_test(), expm1_test(), fabs_test(), fdim_test(), floor_test(), fma_test(), fmax_test(), fmin_test(), fmod_test(), frexp_test(), gamma_test(), hypot_test(), j0_test(), j1_test(), jn_test(), ldexp_test(), lgamma_test(), log10_test(), log1p_test(), log2_test(), log_test(), logb_test(), modf_test(), nearbyint_test(), nextafter_test(), pow_test(), remainder_test(), remquo_test(), rint_test(), round_test(), scalbln_test(), scalbn_test(), sin_test(), sincos_test(), sinh_test(), sqrt_test(), tan_test(), tanh_test(), tgamma_test(), trunc_test(), y0_test(), y1_test(), and yn_test().
check_float_internal()
static void check_float_internal (const char * test_name, FLOAT computed, FLOAT expected, FLOAT max_ulp, int xfail, int exceptions, FLOAT * curr_max_error) static
References diff(), fabs(), FLOAT, FUNC, ignore_max_ulp, IGNORE_ZERO_INF_SIGN, ilogb(), isinf, isnan, ldexp(), MANT_DIG, print_screen(), print_ulps(), printf, PRINTF_EXPR, PRINTF_NEXPR, PRINTF_XEXPR, set_max_error(), signbit, test_exceptions(), ulp(), and update_stats().
Referenced by check_float().
check_int()
static void check_int (const char * test_name, int computed, int expected, int max_ulp, int xfail, int exceptions) static
References abs(), diff(), noTests, print_screen(), print_ulps(), printf, test_exceptions(), and update_stats().
Referenced by fpclassify_test(), frexp_test(), gamma_test(), ilogb_test(), lgamma_test(), and remquo_test().
check_long()
static void check_long (const char * test_name, long int computed, long int expected, long int max_ulp, int xfail, int exceptions) static
References diff(), labs(), noTests, print_screen(), print_ulps(), printf, test_exceptions(), and update_stats().
Referenced by lrint_test(), and lround_test().
check_longlong()
static void check_longlong (const char * test_name, long long int computed, long long int expected, long long int max_ulp, int xfail, int exceptions) static
References diff(), llabs(), noTests, print_screen(), print_ulps(), printf, test_exceptions(), and update_stats().
Referenced by llrint_test(), and llround_test().
copysign_test()
static void copysign_test (void) static
References check_float(), copysign(), FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
cos_test()
static void cos_test (void) static
References check_float(), cos(), DELTA582, DELTA583, DELTA584, DELTA585, DELTAcos, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, M_PI_2l, M_PI_6l, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
cosh_test()
static void cosh_test (void) static
References check_float(), cosh(), DELTA591, DELTAcosh, ENOSYS, errno, FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
erf_test()
static void erf_test (void) static
References check_float(), ENOSYS, erf(), errno, FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
erfc_test()
static void erfc_test (void) static
References check_float(), DELTA817, DELTA818, DELTA819, DELTA820, DELTA821, DELTAerfc, ENOSYS, erfc(), errno, FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
exp2_test()
static void exp2_test (void) static
References check_float(), DELTA852, DELTAexp2, ENOSYS, errno, exp2(), FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
exp_test()
static void exp_test (void) static
References check_float(), DELTA830, DELTA831, DELTA832, DELTAexp, ENOSYS, errno, exp(), FUNC, init_max_error(), M_E2l, M_E3l, M_El, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
expm1_test()
static void expm1_test (void) static
References check_float(), DELTA859, DELTAexpm1, ENOSYS, errno, expm1(), FUNC, init_max_error(), M_El, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
fabs_test()
static void fabs_test (void) static
References check_float(), fabs(), FLOAT, FUNC, init_max_error(), M_El, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
fdim_test()
static void fdim_test (void) static
References check_float(), fdim(), FUNC, init_max_error(), minus_infty, nan_value, plus_infty, and print_max_error().
Referenced by main().
floor_test()
static void floor_test (void) static
References check_float(), floor(), FUNC, init_max_error(), M_PIl, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
fma_test()
static void fma_test (void) static
References check_float(), fma(), FUNC, init_max_error(), INVALID_EXCEPTION, INVALID_EXCEPTION_OK, minus_infty, nan_value, plus_infty, and print_max_error().
Referenced by main().
fmax_test()
static void fmax_test (void) static
References check_float(), fmax(), FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
fmin_test()
static void fmin_test (void) static
References check_float(), fmin(), FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
fmod_test()
static void fmod_test (void) static
References check_float(), DELTA972, DELTA973, DELTA974, DELTA975, DELTAfmod, ENOSYS, errno, fmod(), FUNC, init_max_error(), INVALID_EXCEPTION, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
fpclassify_test()
static void fpclassify_test (void) static
References check_int(), FP_INFINITE, FP_NAN, FP_NORMAL, FP_ZERO, fpclassify, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, plus_zero, and print_max_error().
Referenced by main().
frexp_test()
static void frexp_test (void) static
References check_float(), check_int(), frexp(), FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
gamma_test()
static void gamma_test (void) static
References check_float(), check_int(), DELTA1004, DELTAgamma, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FE_ALL_EXCEPT, feclearexcept(), FUNC, gamma, init_max_error(), M_LN2l, M_LOG_2_SQRT_PIl, M_LOG_SQRT_PIl, minus_infty, nan_value, plus_infty, print_max_error(), and signgam.
Referenced by main().
hypot_test()
static void hypot_test (void) static
References check_float(), DELTA1013, DELTA1014, DELTA1015, DELTA1016, DELTA1017, DELTA1018, DELTA1019, DELTA1020, DELTA1024, DELTAhypot, ENOSYS, errno, FUNC, hypot(), IGNORE_ZERO_INF_SIGN, init_max_error(), minus_infty, nan_value, plus_infty, and print_max_error().
Referenced by main().
ilogb_test()
static void ilogb_test (void) static
References check_int(), EXCEPTIONS_OK, FP_ILOGB0, FP_ILOGBNAN, FUNC, ilogb(), init_max_error(), INT_MAX, M_El, minus_infty, nan_value, plus_infty, and print_max_error().
Referenced by main().
init_max_error()
static void init_max_error (void) static
References FE_ALL_EXCEPT, feclearexcept(), imag_max_error, max_error, and real_max_error.
Referenced by acos_test(), acosh_test(), asin_test(), asinh_test(), atan2_test(), atan_test(), atanh_test(), cbrt_test(), ceil_test(), copysign_test(), cos_test(), cosh_test(), erf_test(), erfc_test(), exp2_test(), exp_test(), expm1_test(), fabs_test(), fdim_test(), floor_test(), fma_test(), fmax_test(), fmin_test(), fmod_test(), fpclassify_test(), frexp_test(), gamma_test(), hypot_test(), ilogb_test(), isfinite_test(), isnormal_test(), j0_test(), j1_test(), jn_test(), lgamma_test(), llrint_test(), llround_test(), log10_test(), log1p_test(), log2_test(), log_test(), logb_test(), lrint_test(), lround_test(), modf_test(), nearbyint_test(), nextafter_test(), pow_test(), remainder_test(), remquo_test(), rint_test(), round_test(), scalbln_test(), scalbn_test(), signbit_test(), sin_test(), sincos_test(), sinh_test(), sqrt_test(), tan_test(), tanh_test(), tgamma_test(), trunc_test(), y0_test(), y1_test(), and yn_test().
initialize()
static void initialize (void) static
References CHOOSE, copysign(), FE_ALL_EXCEPT, feclearexcept(), FUNC, HUGE_VAL, HUGE_VALF, HUGE_VALL, minus_infty, minus_zero, nan_value, plus_infty, and plus_zero.
Referenced by main().
isfinite_test()
static void isfinite_test (void) static
References check_bool(), init_max_error(), isfinite, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
isnormal_test()
static void isnormal_test (void) static
References check_bool(), init_max_error(), isnormal, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
j0_test()
static void j0_test (void) static
References check_float(), DELTA1053, DELTA1054, DELTA1055, DELTAj0, ENOSYS, errno, FLOAT, FUNC, init_max_error(), nan_value, plus_infty, print_max_error(), s, and sincos().
Referenced by main().
j1_test()
static void j1_test (void) static
References check_float(), DELTA1064, DELTA1065, DELTA1066, DELTAj1, ENOSYS, errno, FLOAT, FUNC, init_max_error(), nan_value, plus_infty, print_max_error(), s, and sincos().
Referenced by main().
jn_test()
static void jn_test (void) static
References check_float(), DELTA1075, DELTA1076, DELTA1077, DELTA1086, DELTA1087, DELTA1088, DELTA1091, DELTA1093, DELTA1094, DELTA1095, DELTA1096, DELTA1097, DELTA1100, DELTA1102, DELTA1103, DELTA1104, DELTA1105, DELTA1106, DELTAjn, ENOSYS, errno, FLOAT, FUNC, init_max_error(), nan_value, plus_infty, print_max_error(), s, and sincos().
Referenced by main().
ldexp_test()
static void ldexp_test (void) static
References check_float(), FUNC, ldexp(), minus_infty, minus_zero, nan_value, and plus_infty.
Referenced by main().
lgamma_test()
static void lgamma_test (void) static
References check_float(), check_int(), DELTA1126, DELTA1128, DELTA1130, DELTAlgamma, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FE_ALL_EXCEPT, feclearexcept(), FUNC, init_max_error(), lgamma(), M_LN2l, M_LOG_2_SQRT_PIl, M_LOG_SQRT_PIl, minus_infty, nan_value, plus_infty, print_max_error(), and signgam.
Referenced by main().
llrint_test()
static void llrint_test (void) static
References check_longlong(), FUNC, init_max_error(), llrint(), minus_zero, and print_max_error().
Referenced by main().
llround_test()
static void llround_test (void) static
References check_longlong(), FUNC, init_max_error(), llrint(), llround(), minus_zero, and print_max_error().
Referenced by main().
log10_test()
static void log10_test (void) static
References check_float(), DELTA1178, DELTA1179, DELTAlog10, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, log10(), M_El, M_LOG10El, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
log1p_test()
static void log1p_test (void) static
References check_float(), DELTA1186, DELTA1187, DELTAlog1p, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, log1p(), M_El, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
log2_test()
static void log2_test (void) static
References check_float(), DELTA1198, DELTAlog2, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, log2(), M_El, M_LOG2El, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
log_test()
static void log_test (void) static
References check_float(), DELTA1163, DELTA1164, DELTA1167, DELTAlog, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, log(), M_El, M_LN10l, M_LN2l, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
logb_test()
static void logb_test (void) static
References check_float(), DIVIDE_BY_ZERO_EXCEPTION, FUNC, init_max_error(), logb(), M_El, minus_infty, minus_zero, nan_value, plus_infty, and print_max_error().
Referenced by main().
lrint_test()
static void lrint_test (void) static
References check_long(), FUNC, init_max_error(), lrint(), minus_zero, and print_max_error().
Referenced by main().
lround_test()
static void lround_test (void) static
References check_long(), FUNC, init_max_error(), lround(), minus_zero, and print_max_error().
Referenced by main().
main()
int main (int argc, char ** argv)
References acos_test(), acosh_test(), asin_test(), asinh_test(), atan2_test(), atan_test(), atanh_test(), cbrt_test(), ceil_test(), copysign_test(), cos_test(), cosh_test(), erf_test(), erfc_test(), exit(), EXIT_FAILURE, exp2_test(), exp_test(), expm1_test(), fabs_test(), fclose(), fdim_test(), floor_test(), fma_test(), fmax_test(), fmin_test(), fmod_test(), fopen(), fpclassify_test(), fprintf(), frexp_test(), gamma_test(), hypot_test(), ignore_max_ulp, ilogb_test(), initialize(), isfinite_test(), isnormal_test(), j0_test(), j1_test(), jn_test(), ldexp_test(), lgamma_test(), llrint_test(), llround_test(), log10_test(), log1p_test(), log2_test(), log_test(), logb_test(), lrint_test(), lround_test(), modf_test(), nearbyint_test(), nextafter_test(), noErrors, noExcTests, noTests, noXFails, noXPasses, NULL, output_max_error, output_points, output_ulps, perror(), pow_test(), printf, remainder_test(), remquo_test(), rint_test(), round_test(), scalbln_test(), scalbn_test(), signbit_test(), sin_test(), sincos_test(), sinh_test(), sqrt_test(), tan_test(), tanh_test(), TEST_MSG, tgamma_test(), trunc_test(), ulps_file, verbose, y0_test(), y1_test(), and yn_test().
modf_test()
static void modf_test (void) static
References check_float(), FLOAT, FUNC, init_max_error(), minus_infty, minus_zero, modf(), nan_value, plus_infty, and print_max_error().
Referenced by main().
nearbyint_test()
static void nearbyint_test (void) static
References check_float(), FUNC, init_max_error(), minus_infty, minus_zero, nan_value, nearbyint(), plus_infty, and print_max_error().
Referenced by main().
nextafter_test()
static void nextafter_test (void) static
References check_float(), FUNC, init_max_error(), minus_infty, minus_zero, nan_value, nextafter(), plus_infty, and print_max_error().
Referenced by main().
pow_test()
static void pow_test (void) static
References check_float(), DELTA1398, DELTApow, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, minus_infty, minus_zero, nan_value, plus_infty, pow(), and print_max_error().
Referenced by main().
print_function_ulps()
static void print_function_ulps (const char * function_name, FLOAT ulp) static
References CHOOSE, fprintf(), output_ulps, PRINTF_NEXPR, ulp(), and ulps_file.
Referenced by print_max_error().
print_max_error()
static void print_max_error (const char * func_name, FLOAT allowed, int xfail) static
References ignore_max_ulp, max_error, print_function_ulps(), print_screen_max_error(), printf, PRINTF_NEXPR, and update_stats().
Referenced by acos_test(), acosh_test(), asin_test(), asinh_test(), atan2_test(), atan_test(), atanh_test(), cbrt_test(), ceil_test(), copysign_test(), cos_test(), cosh_test(), erf_test(), erfc_test(), exp2_test(), exp_test(), expm1_test(), fabs_test(), fdim_test(), floor_test(), fma_test(), fmax_test(), fmin_test(), fmod_test(), fpclassify_test(), frexp_test(), gamma_test(), hypot_test(), ilogb_test(), isfinite_test(), isnormal_test(), j0_test(), j1_test(), jn_test(), lgamma_test(), llrint_test(), llround_test(), log10_test(), log1p_test(), log2_test(), log_test(), logb_test(), lrint_test(), lround_test(), modf_test(), nearbyint_test(), nextafter_test(), pow_test(), remainder_test(), remquo_test(), rint_test(), round_test(), scalbln_test(), scalbn_test(), signbit_test(), sin_test(), sincos_test(), sinh_test(), sqrt_test(), tan_test(), tanh_test(), tgamma_test(), trunc_test(), y0_test(), y1_test(), and yn_test().
print_screen()
static int print_screen (int ok, int xfail) static
References output_points, and verbose.
Referenced by check_bool(), check_float_internal(), check_int(), check_long(), check_longlong(), and test_single_exception().
print_screen_max_error()
static int print_screen_max_error (int ok, int xfail) static
References output_max_error, and verbose.
Referenced by print_max_error().
print_ulps()
static void print_ulps (const char * test_name, FLOAT ulp) static
References CHOOSE, fprintf(), output_ulps, PRINTF_NEXPR, ulp(), and ulps_file.
Referenced by check_float_internal(), check_int(), check_long(), and check_longlong().
remainder_test()
static void remainder_test (void) static
References check_float(), ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and remainder().
Referenced by main().
remquo_test()
static void remquo_test (void) static
References check_float(), check_int(), ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and remquo().
Referenced by main().
rint_test()
static void rint_test (void) static
References check_float(), FUNC, init_max_error(), minus_infty, minus_zero, plus_infty, print_max_error(), and rint().
Referenced by main().
round_test()
static void round_test (void) static
References check_float(), FUNC, init_max_error(), minus_zero, print_max_error(), and round().
Referenced by main().
scalbln_test()
static void scalbln_test (void) static
References check_float(), FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and scalbln().
Referenced by main().
scalbn_test()
static void scalbn_test (void) static
References check_float(), FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and scalbn().
Referenced by main().
set_max_error()
static void set_max_error (FLOAT current, FLOAT * curr_max_error) static
Referenced by check_float_internal().
signbit_test()
static void signbit_test (void) static
References check_bool(), init_max_error(), minus_infty, minus_zero, plus_infty, print_max_error(), and signbit.
Referenced by main().
sin_test()
static void sin_test (void) static
References check_float(), DELTA1524, DELTAsin, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, M_PI_2l, M_PI_6l, minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and sin().
Referenced by main().
sincos()
void FUNC() sincos (FLOAT x, FLOAT * s, FLOAT * c)
Referenced by j0_test(), j1_test(), jn_test(), sincos_test(), y0_test(), y1_test(), and yn_test().
sincos_test()
static void sincos_test (void) static
References check_float(), DELTA1536, DELTA1539, DELTA1540, DELTA1541, DELTA1542, DELTAsincos, ENOSYS, errno, FLOAT, FUNC, init_max_error(), INVALID_EXCEPTION, M_PI_2l, M_PI_6l, minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and sincos().
Referenced by main().
sinh_test()
static void sinh_test (void) static
References check_float(), DELTA1548, DELTAsinh, ENOSYS, errno, FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and sinh().
Referenced by main().
sqrt_test()
static void sqrt_test (void) static
References check_float(), DELTA1562, DELTAsqrt, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, M_SQRT2l, minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and sqrt().
Referenced by main().
tan_test()
static void tan_test (void) static
References check_float(), DELTA1569, DELTA1570, DELTAtan, ENOSYS, errno, FUNC, init_max_error(), INVALID_EXCEPTION, M_PI_4l, minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and tan().
Referenced by main().
tanh_test()
static void tanh_test (void) static
References check_float(), DELTA1576, DELTA1577, DELTAtanh, ENOSYS, errno, FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and tanh().
Referenced by main().
test_exceptions()
static void test_exceptions (const char * test_name, int exception) static
References DIVIDE_BY_ZERO_EXCEPTION, DIVIDE_BY_ZERO_EXCEPTION_OK, FE_ALL_EXCEPT, FE_DIVBYZERO, FE_INVALID, feclearexcept(), INVALID_EXCEPTION, INVALID_EXCEPTION_OK, noExcTests, and test_single_exception().
Referenced by check_bool(), check_float_internal(), check_int(), check_long(), and check_longlong().
test_single_exception()
static void test_single_exception (const char * test_name, int exception, int exc_flag, int fe_flag, const char * flag_name) static
References fetestexcept(), noErrors, print_screen(), and printf.
Referenced by test_exceptions().
tgamma_test()
static void tgamma_test (void) static
References check_float(), DELTA1587, DELTA1588, DELTA1590, DELTA1591, DELTAtgamma, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FE_ALL_EXCEPT, feclearexcept(), FUNC, init_max_error(), INVALID_EXCEPTION, M_2_SQRT_PIl, M_SQRT_PIl, minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and tgamma().
Referenced by main().
trunc_test()
static void trunc_test (void) static
References check_float(), FUNC, init_max_error(), minus_infty, minus_zero, nan_value, plus_infty, print_max_error(), and trunc().
Referenced by main().
update_stats()
static void update_stats (int ok, int xfail) static
References noErrors, noTests, noXFails, and noXPasses.
Referenced by check_bool(), check_float_internal(), check_int(), check_long(), check_longlong(), and print_max_error().
y0_test()
static void y0_test (void) static
References check_float(), DELTA1614, DELTA1615, DELTA1616, DELTA1617, DELTA1618, DELTA1619, DELTA1620, DELTAy0, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FLOAT, FUNC, init_max_error(), INVALID_EXCEPTION, minus_infty, nan_value, plus_infty, print_max_error(), s, and sincos().
Referenced by main().
y1_test()
static void y1_test (void) static
References check_float(), DELTA1625, DELTA1626, DELTA1627, DELTA1628, DELTA1629, DELTA1630, DELTA1631, DELTAy1, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FLOAT, FUNC, init_max_error(), INVALID_EXCEPTION, minus_infty, nan_value, plus_infty, print_max_error(), s, and sincos().
Referenced by main().
yn_test()
static void yn_test (void) static
References check_float(), DELTA1636, DELTA1637, DELTA1638, DELTA1639, DELTA1640, DELTA1641, DELTA1642, DELTA1647, DELTA1648, DELTA1649, DELTA1650, DELTA1651, DELTA1652, DELTA1653, DELTA1656, DELTA1657, DELTA1659, DELTA1660, DELTA1663, DELTA1664, DELTA1665, DELTA1666, DELTA1667, DELTAyn, DIVIDE_BY_ZERO_EXCEPTION, ENOSYS, errno, FLOAT, FUNC, init_max_error(), INVALID_EXCEPTION, minus_infty, nan_value, plus_infty, print_max_error(), s, and sincos().
Referenced by main().
Variable Documentation
ignore_max_ulp
int ignore_max_ulp static
Referenced by check_float_internal(), main(), and print_max_error().
imag_max_error
FLOAT imag_max_error static
Referenced by init_max_error().
max_error
FLOAT max_error static
Referenced by check_float(), init_max_error(), and print_max_error().
minus_infty
FLOAT minus_infty static
Referenced by acos_test(), acosh_test(), asin_test(), asinh_test(), atan2_test(), atan_test(), atanh_test(), cbrt_test(), ceil_test(), copysign_test(), cos_test(), cosh_test(), erf_test(), erfc_test(), exp2_test(), exp_test(), expm1_test(), fabs_test(), fdim_test(), floor_test(), fma_test(), fmax_test(), fmin_test(), fmod_test(), fpclassify_test(), frexp_test(), gamma_test(), hypot_test(), ilogb_test(), initialize(), isfinite_test(), isnormal_test(), ldexp_test(), lgamma_test(), log10_test(), log1p_test(), log2_test(), log_test(), logb_test(), modf_test(), nearbyint_test(), nextafter_test(), pow_test(), remainder_test(), remquo_test(), rint_test(), scalbln_test(), scalbn_test(), signbit_test(), sin_test(), sincos_test(), sinh_test(), sqrt_test(), tan_test(), tanh_test(), tgamma_test(), trunc_test(), y0_test(), y1_test(), and yn_test().
minus_zero
FLOAT minus_zero static
Referenced by acos_test(), asin_test(), asinh_test(), atan2_test(), atan_test(), atanh_test(), cbrt_test(), ceil_test(), copysign_test(), cos_test(), cosh_test(), erf_test(), erfc_test(), exp2_test(), exp_test(), expm1_test(), fabs_test(), floor_test(), fmax_test(), fmin_test(), fmod_test(), fpclassify_test(), frexp_test(), initialize(), isfinite_test(), isnormal_test(), ldexp_test(), llrint_test(), llround_test(), log10_test(), log1p_test(), log2_test(), log_test(), logb_test(), lrint_test(), lround_test(), modf_test(), nearbyint_test(), nextafter_test(), pow_test(), remainder_test(), remquo_test(), rint_test(), round_test(), scalbln_test(), scalbn_test(), signbit_test(), sin_test(), sincos_test(), sinh_test(), sqrt_test(), tan_test(), tanh_test(), tgamma_test(), and trunc_test().
nan_value
FLOAT nan_value static
Referenced by acos_test(), acosh_test(), asin_test(), asinh_test(), atan2_test(), atan_test(), atanh_test(), cbrt_test(), ceil_test(), copysign_test(), cos_test(), cosh_test(), erf_test(), erfc_test(), exp2_test(), exp_test(), expm1_test(), fabs_test(), fdim_test(), floor_test(), fma_test(), fmax_test(), fmin_test(), fmod_test(), fpclassify_test(), frexp_test(), gamma_test(), hypot_test(), ilogb_test(), initialize(), isfinite_test(), isnormal_test(), j0_test(), j1_test(), jn_test(), ldexp_test(), lgamma_test(), log10_test(), log1p_test(), log2_test(), log_test(), logb_test(), modf_test(), nearbyint_test(), nextafter_test(), pow_test(), remainder_test(), remquo_test(), scalbln_test(), scalbn_test(), sin_test(), sincos_test(), sinh_test(), sqrt_test(), tan_test(), tanh_test(), tgamma_test(), trunc_test(), y0_test(), y1_test(), and yn_test().
noErrors
int noErrors static
Referenced by main(), test_single_exception(), and update_stats().
noExcTests
int noExcTests static
Referenced by main(), and test_exceptions().
noTests
int noTests static
Referenced by check_bool(), check_int(), check_long(), check_longlong(), main(), and update_stats().
noXFails
int noXFails static
Referenced by main(), and update_stats().
noXPasses
int noXPasses static
Referenced by main(), and update_stats().
output_max_error
int output_max_error static
Referenced by main(), and print_screen_max_error().
output_points
int output_points static
Referenced by main(), and print_screen().
output_ulps
int output_ulps static
Referenced by main(), print_function_ulps(), and print_ulps().
plus_infty
FLOAT plus_infty static
Referenced by acos_test(), acosh_test(), asin_test(), asinh_test(), atan2_test(), atan_test(), atanh_test(), cbrt_test(), ceil_test(), copysign_test(), cos_test(), cosh_test(), erf_test(), erfc_test(), exp2_test(), exp_test(), expm1_test(), fabs_test(), fdim_test(), floor_test(), fma_test(), fmax_test(), fmin_test(), fmod_test(), fpclassify_test(), frexp_test(), gamma_test(), hypot_test(), ilogb_test(), initialize(), isfinite_test(), isnormal_test(), j0_test(), j1_test(), jn_test(), ldexp_test(), lgamma_test(), log10_test(), log1p_test(), log2_test(), log_test(), logb_test(), modf_test(), nearbyint_test(), nextafter_test(), pow_test(), remainder_test(), remquo_test(), rint_test(), scalbln_test(), scalbn_test(), signbit_test(), sin_test(), sincos_test(), sinh_test(), sqrt_test(), tan_test(), tanh_test(), tgamma_test(), trunc_test(), y0_test(), y1_test(), and yn_test().
plus_zero
FLOAT plus_zero static
Referenced by fpclassify_test(), and initialize().
real_max_error
FLOAT real_max_error static
Referenced by init_max_error().
ulps_file
FILE* ulps_file static
Referenced by main(), print_function_ulps(), and print_ulps().
verbose
int verbose static
Referenced by main(), print_screen(), and print_screen_max_error().