Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_tan.c File Reference
s_tan.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double tan (double x)
Function Documentation
tan()
OLM_DLLEXPORT double tan (double x)
References __ieee754_rem_pio2(), __kernel_tan(), GET_HIGH_WORD, n, and z.
Referenced by ctanh(), main(), and tan_test().