Embedded Artistry libc: src/stdlib/strtoul.c File Reference
strtoul.c File Reference
#include <ctype.h>
#include <limits.h>
#include <stdlib.h>
Functions
unsigned long strtoul (char *nptr, char **endptr, int base) const
Function Documentation
strtoul()
unsigned long strtoul (char* nptr, char** endptr, int base) const
Definition at line 78 of file strtoul.c.
 {
     register const char* s = nptr;
     register unsigned long acc;
     register int c;
     register unsigned long cutoff;
     register int neg = 0, any, cutlim;
     /*
      * See strtol for comments as to the logic used.
      */
     do
     {
         c = *s++;
     } while(isspace(c));
     if(c == '-')
     {
         neg = 1;
         c = *s++;
     }
     else if(c == '+')
     {
         c = *s++;
     }
     if((base == 0 || base == 16) && c == '0' && (*s == 'x' || *s == 'X'))
     {
         c = s[1];
         s += 2;
         base = 16;
     }
     else if((base == 0 || base == 2) && c == '0' && (*s == 'b' || *s == 'B'))
     {
         c = s[1];
         s += 2;
         base = 2;
     }
     if(base == 0)
     {
         {
             base = c == '0' ? 8 : 10;
         }
     }
     cutoff = (unsigned long)ULONG_MAX / (unsigned long)base;
     cutlim = (int)((unsigned long)ULONG_MAX % (unsigned long)base);
     for(acc = 0, any = 0;; c = *s++)
     {
         if(isdigit(c))
         {
             c -= '0';
         }
         else if(isalpha(c))
         {
             c -= isupper(c) ? 'A' - 10 : 'a' - 10;
         }
         else
         {
             break;
         }
         if(c >= base)
         {
             break;
         }
         if(any < 0 || acc > cutoff || (acc == cutoff && c > cutlim))
         {
             any = -1;
         }
         else
         {
             any = 1;
             acc *= (unsigned long)base;
             acc += (unsigned long)c;
         }
     }
     if(any < 0)
     {
         acc = ULONG_MAX;
         //      errno = ERANGE;
     }
     else if(neg)
     {
         acc = -acc;
     }
     if(endptr != 0)
     {
         *endptr = (char*)(uintptr_t)(any ? s - 1 : nptr);
     }
     return (acc);
 }
References isalpha(), isdigit(), isspace(), isupper(), and ULONG_MAX.