Embedded Artistry Framework: embvm::gpio::base< TDir > Class Template Reference
embvm::gpio::base< TDir > Class Template Reference abstract
This class defines the common GPIO interfaces.
#include <gpio.hpp>
Public Member Functions
base ()
Default constructor.
base (const char *name)
Construct an gpio::base with a C-string name.
base (const std::string &name)
Construct an gpio::base with a std::string name.
base (const std::string_view &name)
Construct an gpio::base with a std::string_view name.
gpio::direction direction () const
Check the direction of the GPIO pin.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
GPIO Driver Type ID.
Protected Member Functions
~base () override=default
Default destructor.
void start_ () override=0
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () override=0
Derived classes override the start_ method to control driver-specific startup behavior.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Detailed Description
template<gpio::direction TDir>
class embvm::gpio::base< TDir >
This class defines the common GPIO interfaces.
The gpio::base class defines interfaces which are common to all GPIO objects. This class is not intended to be used directly for implementing GPIO drivers. Instead, additional specializations are provided:
gpio::input
gpio::output
gpio::inputOutput
Derived classes must implement pure virtual embvm::DriverBase functions:
start_()
stop_()
Template Parameters
TDir The direction of the GPIO pin (e.g. input, output).
TPull The pull setting for the GPIO pin.
Constructor & Destructor Documentation
base() [1/4]
template<gpio::direction TDir> embvm::gpio::base< TDir >::base () inline
Default constructor.
Initializes the gpio::base instance with a generic name.
base() [2/4]
template<gpio::direction TDir> embvm::gpio::base< TDir >::base (const char * name) inline explicit
Construct an gpio::base with a C-string name.
Initializes the gpio::base instance with a name.
Parameters
name The name of the GPIO instance.
base() [3/4]
template<gpio::direction TDir> embvm::gpio::base< TDir >::base (const std::string & name) inline explicit
Construct an gpio::base with a std::string name.
Initializes the gpio::base instance with a name.
Parameters
name The name of the GPIO instance. gpio::base() uses a std::string_view, so the std::string must remain valid
base() [4/4]
template<gpio::direction TDir> embvm::gpio::base< TDir >::base (const std::string_view & name) inline explicit
Construct an gpio::base with a std::string_view name.
Initializes the gpio::base instance with a name.
Parameters
name The name of the GPIO instance.
~base()
template<gpio::direction TDir> embvm::gpio::base< TDir >::~base () override protected default
Default destructor.
Member Function Documentation
direction()
template<gpio::direction TDir> gpio::direction embvm::gpio::base< TDir >::direction () const inline
Check the direction of the GPIO pin.
Returns
The configured direction of this GPIO pin.
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
template<gpio::direction TDir> void embvm::gpio::base< TDir >::start_ () override protected pure virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in embvm::gpio::inputOutput< TPull >, embvm::gpio::output, embvm::gpio::input< TPull >, embvm::gpio::input< embvm::gpio::pull::pullup >, embvm::gpio::input< embvm::gpio::pull::none >, embdrv::aardvarkGPIOOutput< TPinID >, embdrv::aardvarkGPIOOutput< 5 >, embdrv::aardvarkGPIOInput< TPinID, TPull >, embdrv::aardvarkGPIOInput< 3 >, embdrv::aardvarkGPIOInput< 4 >, nRFGPIOOutput< TPort, TPin >, nRFGPIOOutput< 1, 9 >, nRFGPIOOutput< 0, 16 >, nRFGPIOOutput< 0, 8 >, nRFGPIOOutput< 0, 14 >, nRFGPIOOutput< 0, 6 >, nRFGPIOOutput< 0, 15 >, nRFGPIOOutput< 0, 12 >, nRFGPIOOutput< 0, 13 >, test::UnitTestGPIOInputWithPullup, and test::UnitTestGPIOInput.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
template<gpio::direction TDir> void embvm::gpio::base< TDir >::stop_ () override protected pure virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in embvm::gpio::inputOutput< TPull >, embvm::gpio::output, embvm::gpio::input< TPull >, embvm::gpio::input< embvm::gpio::pull::pullup >, embvm::gpio::input< embvm::gpio::pull::none >, embdrv::aardvarkGPIOOutput< TPinID >, embdrv::aardvarkGPIOOutput< 5 >, embdrv::aardvarkGPIOInput< TPinID, TPull >, embdrv::aardvarkGPIOInput< 3 >, embdrv::aardvarkGPIOInput< 4 >, nRFGPIOOutput< TPort, TPin >, nRFGPIOOutput< 1, 9 >, nRFGPIOOutput< 0, 16 >, nRFGPIOOutput< 0, 8 >, nRFGPIOOutput< 0, 14 >, nRFGPIOOutput< 0, 6 >, nRFGPIOOutput< 0, 15 >, nRFGPIOOutput< 0, 12 >, nRFGPIOOutput< 0, 13 >, test::UnitTestGPIOInputWithPullup, and test::UnitTestGPIOInput.
type()
template<gpio::direction TDir> static constexpr embvm::DriverType embvm::gpio::base< TDir >::type () inline static
GPIO Driver Type ID.
Returns
GPIO type ID.
Member Data Documentation
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
The documentation for this class was generated from the following file:
src/core/driver/gpio.hpp