Embedded Artistry Framework: NRF52DongleHWPlatform Class Reference
NRF52DongleHWPlatform Class Reference
#include <nrf52_dongle_hw_platform.hpp>
Public Member Functions
NRF52DongleHWPlatform ()
Default constructor.
~NRF52DongleHWPlatform ()
Default destructor.
void init_ () noexcept
void initProcessor_ () noexcept
void soft_reset_ () noexcept
void hard_reset_ () noexcept
void leds_off () noexcept
void startBlink () noexcept
constexpr const std::string_view & name () const noexcept
Returns the Virtual HW Platform's name.
constexpr const char * name_cstr () const noexcept
Returns the platform name as a cstring for C API compatibility.
void initProcessor () noexcept
Initialize the processor.
void init () noexcept
Initialize the hardware platform.
void soft_reset () noexcept
Perform a soft reset of the system (chip reset)
void hard_reset () noexcept
Perform a hard reset of the system (power cycle)
void shutdown () noexcept
Shutdown the system.
Static Public Member Functions
static void earlyInitHook_ () noexcept
static void earlyInitHook () noexcept
Perform any special initialization steps.
Private Types
using PlatformBase = embvm::VirtualHwPlatformBase< NRF52DongleHWPlatform >
Private Attributes
nRF52840 processor
nRFGPIOOutput< 0, 6 > led1_g_pin {}
nRFGPIOOutput< 0, 8 > led2_r_pin {}
nRFGPIOOutput< 1, 9 > led2_g_pin {}
nRFGPIOOutput< 0, 12 > led2_b_pin {}
embvm::led::gpioActiveLow led1 {led1_g_pin, "led1"}
embvm::led::gpioActiveLow led2_r {led2_r_pin, "led2r"}
embvm::led::gpioActiveLow led2_g {led2_g_pin, "led2g"}
embvm::led::gpioActiveLow led2_b {led2_b_pin, "led2b"}
Member Typedef Documentation
PlatformBase
using NRF52DongleHWPlatform::PlatformBase = embvm::VirtualHwPlatformBase<NRF52DongleHWPlatform> private
Constructor & Destructor Documentation
NRF52DongleHWPlatform()
NRF52DongleHWPlatform::NRF52DongleHWPlatform () inline
Default constructor.
~NRF52DongleHWPlatform()
NRF52DongleHWPlatform::~NRF52DongleHWPlatform () noexcept
Default destructor.
Member Function Documentation
earlyInitHook()
static void embvm::VirtualHwPlatformBase< NRF52DongleHWPlatform >::earlyInitHook () inline static noexcept inherited
Perform any special initialization steps.
The earlyInitHook_() function must be implemented by the derived class as a static function.
These functions run before the C Run-time setup functions are called, and normal functionality (e.g. OS concepts) are not available.
Early initialization steps represent any super early code that needs to execute. For example, DRAM might need to be initialized before the boot process can relocate memory to its proper location in memory.
These functions are declared static to prevent you from easily using drivers within their confines
earlyInitHook_()
void NRF52DongleHWPlatform::earlyInitHook_ () static noexcept
References __HeapBase, __HeapLimit, and malloc_addblock().
hard_reset()
void embvm::VirtualHwPlatformBase< NRF52DongleHWPlatform >::hard_reset () inline noexcept inherited
Perform a hard reset of the system (power cycle)
The hard_reset_() function must be implemented by the derived class.
A hard reset is intended to perform a full power cycle of the system.
Platforms which do not support a hard reset should default to calling soft_reset().
hard_reset_()
void NRF52DongleHWPlatform::hard_reset_ () inline noexcept
References soft_reset_().
init()
void embvm::VirtualHwPlatformBase< NRF52DongleHWPlatform >::init () inline noexcept inherited
Initialize the hardware platform.
The init_() function must be implemented by the derived class.
Perform any hardware platform initialization steps, such as preparing peripherals for use, setting up callbacks, etc.
init_()
void NRF52DongleHWPlatform::init_ () noexcept
References nRF52840::highVoltageMode(), led1, led2_b, led2_g, led2_r, processor, and embvm::DriverBase::start().
initProcessor()
void embvm::VirtualHwPlatformBase< NRF52DongleHWPlatform >::initProcessor () inline noexcept inherited
Initialize the processor.
The initProcessor_() function must be implemented by the derived class.
Perform any steps necessary for initializing the processor & processor peripheral devices for use.
Note that this is only intended to be processor initialization. Platform initialization nis handled by the init() function.
This function will likely invoke the VirtualProcessor::init() function, but the order and actual initialization process is left to the derived class.
initProcessor_()
void NRF52DongleHWPlatform::initProcessor_ () inline noexcept
leds_off()
void NRF52DongleHWPlatform::leds_off () inline noexcept
References led1, led2_b, led2_g, led2_r, and embvm::led::gpio< TActiveHigh >::off().
name()
constexpr const std::string_view& embvm::VirtualHwPlatformBase< NRF52DongleHWPlatform >::name () const inline noexcept inherited
Returns the Virtual HW Platform's name.
name_cstr()
constexpr const char* embvm::VirtualHwPlatformBase< NRF52DongleHWPlatform >::name_cstr () const inline noexcept inherited
Returns the platform name as a cstring for C API compatibility.
shutdown()
void embvm::VirtualHwPlatformBase< NRF52DongleHWPlatform >::shutdown () inline noexcept inherited
Shutdown the system.
The shutdown_() function must be implemented by the derived class.
If your platform supports shutdown capability, take the proper steps to initiate a shutdown.
If the platform does not support shutdown capability, implement your shutdown_() function as an assert to notify users trying to call this API. You could also leave the shutdown_() function undefined. Anyone who calls the shutdown() function on a platform with an undefined shutdown_() function will encounter a compiler error.
The shutdown function is not expected to return.
soft_reset()
void embvm::VirtualHwPlatformBase< NRF52DongleHWPlatform >::soft_reset () inline noexcept inherited
Perform a soft reset of the system (chip reset)
The soft_reset_() function must be implemnted by the derived class.
A soft reset is intended to reset the program to the beginning without performing a full power cycle.
A good strategy is to just call virtual processor's reset() function, if one is provided.
soft_reset_()
void NRF52DongleHWPlatform::soft_reset_ () inline noexcept
Referenced by hard_reset_().
startBlink()
void NRF52DongleHWPlatform::startBlink () inline noexcept
References led1, led2_b, led2_g, led2_r, processor, and nRF52840::spin().
Member Data Documentation
led1
embvm::led::gpioActiveLow NRF52DongleHWPlatform::led1 {led1_g_pin, "led1"} private
Referenced by init_(), leds_off(), and startBlink().
led1_g_pin
nRFGPIOOutput<0, 6> NRF52DongleHWPlatform::led1_g_pin {} private
led2_b
embvm::led::gpioActiveLow NRF52DongleHWPlatform::led2_b {led2_b_pin, "led2b"} private
Referenced by init_(), leds_off(), and startBlink().
led2_b_pin
nRFGPIOOutput<0, 12> NRF52DongleHWPlatform::led2_b_pin {} private
led2_g
embvm::led::gpioActiveLow NRF52DongleHWPlatform::led2_g {led2_g_pin, "led2g"} private
Referenced by init_(), leds_off(), and startBlink().
led2_g_pin
nRFGPIOOutput<1, 9> NRF52DongleHWPlatform::led2_g_pin {} private
led2_r
embvm::led::gpioActiveLow NRF52DongleHWPlatform::led2_r {led2_r_pin, "led2r"} private
Referenced by init_(), leds_off(), and startBlink().
led2_r_pin
nRFGPIOOutput<0, 8> NRF52DongleHWPlatform::led2_r_pin {} private
processor
nRF52840 NRF52DongleHWPlatform::processor private
Referenced by init_(), and startBlink().
The documentation for this class was generated from the following files:
src/hw_platforms/nordic/nrf52840_dongle/nrf52_dongle_hw_platform.hpp
src/hw_platforms/nordic/nrf52840_dongle/nrf52_dongle_hw_platform.cpp