Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_catan.c File Reference
s_catan.c File Reference
#include <float.h>
#include <openlibm_complex.h>
#include <openlibm_math.h>
Macros
#define MAXNUM 1.0e308
Functions
static double _redupi (double x)
double complex catan (double complex z)
Variables
static const double DP1 = 3.14159265160560607910E0
static const double DP2 = 1.98418714791870343106E-9
static const double DP3 = 1.14423774522196636802E-17
Macro Definition Documentation
MAXNUM
#define MAXNUM 1.0e308
Function Documentation
_redupi()
static double _redupi (double x) static
References DP1, DP2, DP3, and t.
Referenced by catan().
catan()
double complex catan (double complex z)
References _redupi(), a, atan2(), cimag(), complex, creal(), I, log(), MAXNUM, t, w, and z.
Referenced by catanh().
Variable Documentation
DP1
const double DP1 = 3.14159265160560607910E0 static
Referenced by _redupi().
DP2
const double DP2 = 1.98418714791870343106E-9 static
Referenced by _redupi().
DP3
const double DP3 = 1.14423774522196636802E-17 static
Referenced by _redupi().