Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_csqrtl.c File Reference
s_csqrtl.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_complex.h>
#include <openlibm_math.h>
#include "math_private.h"
Macros
#define THRESH (LDBL_MAX / 2.414213562373095048801688724209698L)
Functions
OLM_DLLEXPORT long double complex csqrtl (long double complex z)
Macro Definition Documentation
THRESH
#define THRESH (LDBL_MAX / 2.414213562373095048801688724209698L)
Function Documentation
csqrtl()
OLM_DLLEXPORT long double complex csqrtl (long double complex z)
References a, b, cimagl(), CMPLXL(), complex, copysignl(), creall(), fabsl(), hypotl(), INFINITY, isinf, isnan, signbit, sqrtl(), t, THRESH, and z.
Referenced by casinl().