Embedded Artistry libc: src/ctype/isdigit.c File Reference
isdigit.c File Reference
#include <ctype.h>
Functions
int isdigit (int c)
Checks if the given character is a numeric character.
Function Documentation
isdigit()
int isdigit (int ch)
Checks if the given character is a numeric character.
Checks if the given character is a numeric character (0123456789).
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a numeric character, zero otherwise.
Definition at line 5 of file isdigit.c.
 {
     return (unsigned)c - '0' < 10;
 }
Referenced by atoi(), atol(), atoll(), isalnum(), isxdigit(), strtol(), strtoll(), and strtoul().