Embedded Artistry Framework: src/stdlibs/libc/src/string/strcspn.c File Reference
strcspn.c File Reference
#include "strchrnul.h"
#include <stdint.h>
#include <string.h>
Macros
#define BITOP(a, b, op) ((a)[(size_t)(b) / (8 * sizeof *(a))] op(size_t) 1 << ((size_t)(b) % (8 * sizeof *(a))))
Functions
size_t strcspn (const char *s, const char *c)
Macro Definition Documentation
BITOP
#define BITOP (a, b, op) ((a)[(size_t)(b) / (8 * sizeof *(a))] op(size_t) 1 << ((size_t)(b) % (8 * sizeof *(a))))
Function Documentation
strcspn()
size_t strcspn (const char * s, const char * c)
References __strchrnul(), a, BITOP, memset(), and s.
Referenced by strpbrk().