Embedded Artistry Framework: src/stdlibs/libc/test/stdlib/atoll.c File Reference
atoll.c File Reference
#include "stdlib_tests.h"
#include <stdlib.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Functions
static void atoll_test (void **state)
int atoll_tests (void)
Function Documentation
atoll_test()
static void atoll_test (void ** state) static
References atoll().
Referenced by atoll_tests().
atoll_tests()
int atoll_tests (void)
References atoll_test(), atoll_tests(), and NULL.
Referenced by atoll_tests(), and stdlib_tests().