Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_scalbn.c File Reference
s_scalbn.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double scalbn (double x, int n)
__strong_reference (scalbn, ldexp)
Variables
static const double two54 = 1.80143985094819840000e+16
static const double twom54 = 5.55111512312578270212e-17
static const double huge = 1.0e+300
static const double tiny = 1.0e-300
Function Documentation
__strong_reference()
__strong_reference (scalbn , ldexp)
scalbn()
OLM_DLLEXPORT double scalbn (double x, int n)
References copysign(), EXTRACT_WORDS, GET_HIGH_WORD, huge, k, n, SET_HIGH_WORD, tiny, two54, and twom54.
Referenced by __exp__D(), __ieee754_pow(), __kernel_rem_pio2(), scalbln(), and scalbn_test().
Variable Documentation
huge
const double huge = 1.0e+300 static
Referenced by scalbn().
tiny
const double tiny = 1.0e-300 static
Referenced by scalbn().
two54
const double two54 = 1.80143985094819840000e+16 static
Referenced by scalbn().
twom54
const double twom54 = 5.55111512312578270212e-17 static
Referenced by scalbn().