Embedded Artistry Framework: src/stdlibs/libc/openlibm/ld80/e_log10l.c File Reference
e_log10l.c File Reference
#include <openlibm_math.h>
#include "math_private.h"
Macros
#define L102A 0.3125L
#define L102B -1.1470004336018804786261e-2L
#define L10EA 0.5L
#define L10EB -6.5705518096748172348871e-2L
#define SQRTH 0.70710678118654752440L
Functions
long double log10l (long double x)
Variables
static long double P []
static long double Q []
static long double R [4]
static long double S [4]
Macro Definition Documentation
L102A
#define L102A 0.3125L
L102B
#define L102B -1.1470004336018804786261e-2L
L10EA
#define L10EA 0.5L
L10EB
#define L10EB -6.5705518096748172348871e-2L
SQRTH
#define SQRTH 0.70710678118654752440L
Function Documentation
log10l()
long double log10l (long double x)
References __p1evll(), __polevll(), IEEEl2bits::e, frexpl(), INFINITY, isnan, L102A, L102B, L10EA, L10EB, ldexpl(), P, Q, R, S, SQRTH, and z.
Variable Documentation
P
long double P[] static
Initial value:
= {
 4.9962495940332550844739E-1L,
 1.0767376367209449010438E1L,
 7.7671073698359539859595E1L,
 2.5620629828144409632571E2L,
 4.2401812743503691187826E2L,
 3.4258224542413922935104E2L,
 1.0747524399916215149070E2L,
}
Referenced by log10l().
Q
long double Q[] static
Initial value:
= {
 2.3479774160285863271658E1L,
 1.9444210022760132894510E2L,
 7.7952888181207260646090E2L,
 1.6911722418503949084863E3L,
 2.0307734695595183428202E3L,
 1.2695660352705325274404E3L,
 3.2242573199748645407652E2L,
}
Referenced by log10l().
R
long double R[4] static
Initial value:
= {
 1.9757429581415468984296E-3L,
-7.1990767473014147232598E-1L,
 1.0777257190312272158094E1L,
-3.5717684488096787370998E1L,
}
Referenced by log10l().
S
long double S[4] static
Initial value:
= {
-2.6201045551331104417768E1L,
 1.9361891836232102174846E2L,
-4.2861221385716144629696E2L,
}
Referenced by log10l().