Embedded Artistry libc: src/gdtoa/src/dmisc.c File Reference
dmisc.c File Reference
#include "gdtoaimp.h"
Functions
char * rv_alloc (int i)
char * nrv_alloc (char *s, char **rve, int n)
void freedtoa (char *s)
int quorem (Bigint *b, Bigint *S)
Variables
char * dtoa_result
Function Documentation
freedtoa()
void freedtoa (char * s)
Definition at line 99 of file dmisc.c.
 {
     Bigint* b = (Bigint*)((void*)(s - sizeof(int*)));
     b->maxwds = 1 << (b->k = *(int*)b);
     Bfree(b);
 #ifndef MULTIPLE_THREADS
     if(s == dtoa_result)
     {
         dtoa_result = 0;
     }
 #endif
 }
References Bfree(), dtoa_result, Bigint::k, and Bigint::maxwds.
Referenced by dtoa(), g__fmt(), and gdtoa().
nrv_alloc()
char* nrv_alloc (char * s, char ** rve, int n)
Definition at line 68 of file dmisc.c.
 {
     char *rv, *t;
     t = rv = rv_alloc(n);
     while((*t = *s++) != 0)
     {
         {
             t++;
         }
     }
     if(rve)
     {
         {
             *rve = t;
         }
     }
     return rv;
 }
References rv_alloc().
Referenced by dtoa(), and gdtoa().
quorem()
int quorem (Bigint * b, Bigint * S)
Definition at line 118 of file dmisc.c.
 {
     int n;
     ULong *bx, *bxe, q, *sx, *sxe;
 #ifdef ULLong
     ULLong borrow, carry, y, ys;
 #else
     ULong borrow, carry, y, ys;
 #ifdef Pack_32
     ULong si, z, zs;
 #endif
 #endif
     n = S->wds;
 #ifdef DEBUG
     /*debug*/ if(b->wds > n)
         /*debug*/ Bug("oversize b in quorem");
 #endif
     if(b->wds < n)
     {
         {
             return 0;
         }
     }
     sx = S->x;
     sxe = sx + --n;
     bx = b->x;
     bxe = bx + n;
     q = *bxe / (*sxe + 1); /* ensure q <= true quotient */
 #ifdef DEBUG
     /*debug*/ if(q > 9)
         /*debug*/ Bug("oversized quotient in quorem");
 #endif
     if(q)
     {
         borrow = 0;
         carry = 0;
         do
         {
 #ifdef ULLong
             ys = *sx++ * (ULLong)q + carry;
             carry = ys >> 32;
             y = *bx - (ys & 0xffffffffUL) - borrow;
             borrow = y >> 32 & 1UL;
             *bx++ = y & 0xffffffffUL;
 #else
 #ifdef Pack_32
             si = *sx++;
             ys = (si & 0xffff) * q + carry;
             zs = (si >> 16) * q + (ys >> 16);
             carry = zs >> 16;
             y = (*bx & 0xffff) - (ys & 0xffff) - borrow;
             borrow = (y & 0x10000) >> 16;
             z = (*bx >> 16) - (zs & 0xffff) - borrow;
             borrow = (z & 0x10000) >> 16;
             Storeinc(bx, z, y);
 #else
             ys = *sx++ * q + carry;
             carry = ys >> 16;
             y = *bx - (ys & 0xffff) - borrow;
             borrow = (y & 0x10000) >> 16;
             *bx++ = y & 0xffff;
 #endif
 #endif
         } while(sx <= sxe);
         if(!*bxe)
         {
             bx = b->x;
             while(--bxe > bx && !*bxe)
             {
                 --n;
             }
             b->wds = n;
         }
     }
     if(cmp(b, S) >= 0)
     {
         q++;
         borrow = 0;
         carry = 0;
         bx = b->x;
         sx = S->x;
         do
         {
 #ifdef ULLong
             ys = *sx++ + carry;
             carry = ys >> 32;
             y = *bx - (ys & 0xffffffffUL) - borrow;
             borrow = y >> 32 & 1UL;
             *bx++ = y & 0xffffffffUL;
 #else
 #ifdef Pack_32
             si = *sx++;
             ys = (si & 0xffff) + carry;
             zs = (si >> 16) + (ys >> 16);
             carry = zs >> 16;
             y = (*bx & 0xffff) - (ys & 0xffff) - borrow;
             borrow = (y & 0x10000) >> 16;
             z = (*bx >> 16) - (zs & 0xffff) - borrow;
             borrow = (z & 0x10000) >> 16;
             Storeinc(bx, z, y);
 #else
             ys = *sx++ + carry;
             carry = ys >> 16;
             y = *bx - (ys & 0xffff) - borrow;
             borrow = (y & 0x10000) >> 16;
             *bx++ = y & 0xffff;
 #endif
 #endif
         } while(sx <= sxe);
         bx = b->x;
         bxe = bx + n;
         if(!*bxe)
         {
             while(--bxe > bx && !*bxe)
             {
                 --n;
             }
             b->wds = n;
         }
     }
     // TODO: why is an int being returned?
     return (int)q;
 }
References cmp(), Storeinc, UL, ULLong, Bigint::wds, and Bigint::x.
Referenced by dtoa(), and gdtoa().
rv_alloc()
char* rv_alloc (int i)
Definition at line 42 of file dmisc.c.
 {
     int k, *r;
     size_t j;
     j = sizeof(ULong);
     for(k = 0; sizeof(Bigint) - sizeof(ULong) - sizeof(int) + j <= (size_t)i; j <<= 1)
     {
         k++;
     }
     r = (int*)Balloc(k);
     *r = k;
     return
 #ifndef MULTIPLE_THREADS
         dtoa_result =
 #endif
             (char*)(r + 1);
 }
References Balloc(), and dtoa_result.
Referenced by dtoa(), gdtoa(), and nrv_alloc().
Variable Documentation
dtoa_result
char* dtoa_result
Definition at line 35 of file dmisc.c.
Referenced by freedtoa(), and rv_alloc().