Embedded Artistry Framework: POSIX OS Types
POSIX OS Types
Supported Framework Operating Systems
Virtual OS implementation for POSIX systems.
Classes
class os::posix::posixOSFactory_impl
Implementation of the POSIX OS Factory For API documentation, see embvm::embvm::VirtualOSFactory.
class os::posix::EventFlag
POSIX Event Flag Implementation.
class os::posix::MessageQueue< TType >
Posix Message Queue implementation for Linux.
class os::posix::Mutex
POSIX Mutex Implementation.
class os::posix::Semaphore
Create a POSIX semaphore (OSX variant)
class os::posix::Thread
Create a POSIX thread.
Enumerations
enum os::posix::pthread_priority : uint8_t {
os::posix::pthread_priority::panic = 99, os::posix::pthread_priority::interrupt = 99, os::posix::pthread_priority::realtime = 99, os::posix::pthread_priority::veryHigh = 50,
os::posix::pthread_priority::high = 40, os::posix::pthread_priority::aboveNormal = 30, os::posix::pthread_priority::normal = 20, os::posix::pthread_priority::belowNormal = 10,
os::posix::pthread_priority::low = 5, os::posix::pthread_priority::lowest = 1, os::posix::pthread_priority::idle = 0
}
PThread priority values.
Functions
constexpr posix::pthread_priority os::posix::convert_to_pthread_priority (embvm::thread::priority p) noexcept
Convert between framework thread priorities and PThread priorities.
Detailed Description
Virtual OS implementation for POSIX systems.
Class Documentation
os::posix::posixOSFactory_impl
class os::posix::posixOSFactory_impl
Implementation of the POSIX OS Factory For API documentation, see embvm::embvm::VirtualOSFactory.
Public Member Functions
posixOSFactory_impl ()=default
~posixOSFactory_impl ()=default
Static Public Member Functions
static embvm::VirtualConditionVariable * createConditionVariable_impl () noexcept
static embvm::VirtualThread * createThread_impl (std::string_view name, embvm::thread::func_t f, embvm::thread::input_t input, embvm::thread::priority p, size_t stack_size, void *stack_ptr) noexcept
static embvm::VirtualMutex * createMutex_impl (embvm::mutex::type type=embvm::mutex::type::defaultType, embvm::mutex::mode mode=embvm::mutex::mode::defaultMode) noexcept
static embvm::VirtualSemaphore * createSemaphore_impl (embvm::semaphore::mode mode, embvm::semaphore::count_t ceiling, embvm::semaphore::count_t initial_count) noexcept
template<typename TType >
static embvm::VirtualMessageQueue< TType > * createMessageQueue_impl (size_t queue_length) noexcept
static embvm::VirtualEventFlag * createEventFlag_impl () noexcept
static void destroy_impl (embvm::VirtualThread *item) noexcept
static void destroy_impl (embvm::VirtualMutex *item) noexcept
static void destroy_impl (embvm::VirtualSemaphore *item) noexcept
static void destroy_impl (embvm::VirtualEventFlag *item) noexcept
static void destroy_impl (embvm::VirtualConditionVariable *item) noexcept
Constructor & Destructor Documentation
posixOSFactory_impl()
os::posix::posixOSFactory_impl::posixOSFactory_impl () default
~posixOSFactory_impl()
os::posix::posixOSFactory_impl::~posixOSFactory_impl () default
Member Function Documentation
createConditionVariable_impl()
static embvm::VirtualConditionVariable* os::posix::posixOSFactory_impl::createConditionVariable_impl () inline static noexcept
createEventFlag_impl()
static embvm::VirtualEventFlag* os::posix::posixOSFactory_impl::createEventFlag_impl () inline static noexcept
createMessageQueue_impl()
template<typename TType > static embvm::VirtualMessageQueue<TType>* os::posix::posixOSFactory_impl::createMessageQueue_impl (size_t queue_length) inline static noexcept
createMutex_impl()
static embvm::VirtualMutex* os::posix::posixOSFactory_impl::createMutex_impl (embvm::mutex::type type = embvm::mutex::type::defaultType, embvm::mutex::mode mode = embvm::mutex::mode::defaultMode) inline static noexcept
References type.
createSemaphore_impl()
static embvm::VirtualSemaphore* os::posix::posixOSFactory_impl::createSemaphore_impl (embvm::semaphore::mode mode, embvm::semaphore::count_t ceiling, embvm::semaphore::count_t initial_count) inline static noexcept
createThread_impl()
static embvm::VirtualThread* os::posix::posixOSFactory_impl::createThread_impl (std::string_view name, embvm::thread::func_t f, embvm::thread::input_t input, embvm::thread::priority p, size_t stack_size, void * stack_ptr) inline static noexcept
References p.
destroy_impl() [1/5]
static void os::posix::posixOSFactory_impl::destroy_impl (embvm::VirtualThread * item) inline static noexcept
destroy_impl() [2/5]
static void os::posix::posixOSFactory_impl::destroy_impl (embvm::VirtualMutex * item) inline static noexcept
destroy_impl() [3/5]
static void os::posix::posixOSFactory_impl::destroy_impl (embvm::VirtualSemaphore * item) inline static noexcept
destroy_impl() [4/5]
static void os::posix::posixOSFactory_impl::destroy_impl (embvm::VirtualEventFlag * item) inline static noexcept
destroy_impl() [5/5]
static void os::posix::posixOSFactory_impl::destroy_impl (embvm::VirtualConditionVariable * item) inline static noexcept
os::posix::EventFlag
class os::posix::EventFlag
POSIX Event Flag Implementation.
Public Member Functions
EventFlag ()=default
~EventFlag () noexcept
Default destructor which cleans up the event flag group.
embvm::eventflag::flag_t get (embvm::eventflag::flag_t bits_wait, embvm::eventflag::option opt=embvm::eventflag::option::OR, bool clearOnExit=true, const embvm::os_timeout_t &timeout=embvm::OS_WAIT_FOREVER) noexcept final
Get (or wait for) event flags.
void set (embvm::eventflag::flag_t bits) noexcept final
Set event flags.
void setFromISR (embvm::eventflag::flag_t bits) noexcept final
Set event flags from an ISR.
void clear () noexcept final
Clear all event flag bits.
embvm::eventflag::handle_t native_handle () const noexcept final
Get the native handle for the event flags group object.
Private Member Functions
embvm::eventflag::flag_t checkAndClearFlags (embvm::eventflag::flag_t bits_wait, embvm::eventflag::option opt, bool clearOnExit) noexcept
Helper function which evaluates flags and returns the matching value.
Private Attributes
std::atomic< embvm::eventflag::flag_t > flags_ = 0
The storage type for the event flag group's flags.
posix::ConditionVariable cv_
Condition variable which is used to wake threads waiting on this group.
posix::Mutex mutex_
Mutex which protects the flags.
Constructor & Destructor Documentation
EventFlag()
os::posix::EventFlag::EventFlag () default
~EventFlag()
EventFlag::~EventFlag () noexcept
Default destructor which cleans up the event flag group.
Member Function Documentation
checkAndClearFlags()
embvm::eventflag::flag_t os::posix::EventFlag::checkAndClearFlags (embvm::eventflag::flag_t bits_wait, embvm::eventflag::option opt, bool clearOnExit) inline private noexcept
Helper function which evaluates flags and returns the matching value.
Parameters
bits_wait The bits the caller is waiting for, specified as a bitmask
opt The comparison option (AND or OR)
clearOnExit If true, matching flags will be cleared from flag_ when the function exits
Returns
the resulting event flag bits, compared to bits_wait and with the selected option (opt).
Postcondition
If clearOnExit is true:
All flags set in bits_wait will be cleared from flag_ if AND option is used.
Flags set in both btis_wait and flags_ will be cleared from flag_ if OR option is used.
References flags_, and embvm::eventflag::OR.
Referenced by get().
clear()
void os::posix::EventFlag::clear () inline final virtual noexcept
Clear all event flag bits.
Postcondition
Event flag group value is reset to '0'.
Implements embvm::VirtualEventFlag.
References flags_, os::posix::Mutex::lock(), mutex_, and os::posix::Mutex::unlock().
get()
embvm::eventflag::flag_t os::posix::EventFlag::get (embvm::eventflag::flag_t bits_wait, embvm::eventflag::option opt = embvm::eventflag::option::OR, bool clearOnExit = true, const embvm::os_timeout_t & timeout = embvm::OS_WAIT_FOREVER) inline final virtual noexcept
Get (or wait for) event flags.
Get the event flag bits. If the required event flags are not set, this function will block the calling thread until the flags are set or the timeout expires.
To see all bits currently set, set bits_wait to ~0 and timeout_t to the minimal value (timeout_t(1)).
Parameters
bits_wait A bitmask of bits to wait for in the event flags group.
opt The wait option, which is combined with bits_wait to control the behavior of get(). embvm::eventflag::option::OR will return once any of the bits specified in bits_wait are set in the event flag group. embvm::eventflag::option::AND will only return once ALL of the bits specified in bits_wait are set in the event flag group.
clearOnExit If true, all event flags that were specified in bits_wait and set in the event flag group will be set to 0. If false, event flag bits will not be modified.
timeout Specify a timeout for the get operation. If OS_WAIT_FOREVER is supplied, this call will block until the event flags are set. Otherwise, the function will timeout after the elapsed time if flags are not set.
Returns
0 if timeout, or flags that were currently set according to bits_wait
Implements embvm::VirtualEventFlag.
References checkAndClearFlags(), cv_, os::posix::Mutex::lock(), mutex_, os::posix::Mutex::unlock(), and os::posix::ConditionVariable::wait().
native_handle()
embvm::eventflag::handle_t os::posix::EventFlag::native_handle () const inline final virtual noexcept
Get the native handle for the event flags group object.
Returns
the native handle for this event flags object. The handle will always return the handle_t and it must be cast to the native handle type by the user.
Implements embvm::VirtualEventFlag.
set()
void os::posix::EventFlag::set (embvm::eventflag::flag_t bits) inline final virtual noexcept
Set event flags.
Set event flags from a threaded context. Threads waiting on event flags (via get()) will be notified.
Parameters
bits A bitmask representing the bits to set in the event flag group.
Implements embvm::VirtualEventFlag.
References os::posix::ConditionVariable::broadcast(), cv_, flags_, os::posix::Mutex::lock(), mutex_, and os::posix::Mutex::unlock().
setFromISR()
void os::posix::EventFlag::setFromISR (embvm::eventflag::flag_t bits) inline final virtual noexcept
Set event flags from an ISR.
Set event flags from an interrupt context. This call must not use a lock. Threads waiting on event flags (via get()) will be notified.
Parameters
bits A bitmask representing the bits to set in the event flag group.
Implements embvm::VirtualEventFlag.
References os::posix::ConditionVariable::broadcast(), cv_, flags_, os::posix::Mutex::lock(), mutex_, and os::posix::Mutex::unlock().
Member Data Documentation
cv_
posix::ConditionVariable os::posix::EventFlag::cv_ private
Condition variable which is used to wake threads waiting on this group.
Referenced by get(), set(), and setFromISR().
flags_
std::atomic<embvm::eventflag::flag_t> os::posix::EventFlag::flags_ = 0 private
The storage type for the event flag group's flags.
Referenced by checkAndClearFlags(), clear(), set(), and setFromISR().
mutex_
posix::Mutex os::posix::EventFlag::mutex_ private
Mutex which protects the flags.
Referenced by clear(), get(), set(), and setFromISR().
os::posix::MessageQueue
class os::posix::MessageQueue
template<typename TType>
class os::posix::MessageQueue< TType >
Posix Message Queue implementation for Linux.
Template Parameters
TType The type of data to be stored in the message queue
Public Member Functions
MessageQueue (std::string_view name, size_t queue_length) noexcept
Construct a message queue with name and length.
~MessageQueue () noexcept
Default destructor.
bool push (TType val, embvm::os_timeout_t timeout=embvm::OS_WAIT_FOREVER) noexcept final
Post a message to the queue.
TType pop (embvm::os_timeout_t timeout=embvm::OS_WAIT_FOREVER) noexcept final
Retrieve a message from the queue.
size_t size () const noexcept final
Get the current size of the message queue.
void reset () noexcept final
Reset the message queue to an empty state.
bool empty () const noexcept final
Check if the message queue is empty.
bool full () const noexcept final
Check if the message queue is full.
virtual embvm::msgqueue::handle_t native_handle () const noexcept=0
Get the native handle for the message queue object.
Private Attributes
std::string_view name_
The name of this message queue instance.
mqd_t handle_
The message queue instance handle.
Constructor & Destructor Documentation
MessageQueue()
template<typename TType > os::posix::MessageQueue< TType >::MessageQueue (std::string_view name, size_t queue_length) inline explicit noexcept
Construct a message queue with name and length.
Parameters
name The name associated with the message queue.
Note
A std::string input must remain valid for the lifetime of this object, since std::string_view is used to store the name.
Parameters
queue_length The maximum size of the message queue.
References assert, os::posix::MessageQueue< TType >::handle_, and os::posix::MessageQueue< TType >::name_.
~MessageQueue()
template<typename TType > os::posix::MessageQueue< TType >::~MessageQueue () inline noexcept
Default destructor.
References os::posix::MessageQueue< TType >::handle_.
Member Function Documentation
empty()
template<typename TType > bool os::posix::MessageQueue< TType >::empty () const inline final virtual noexcept
Check if the message queue is empty.
Returns
true if the queue is empty, false otherwise.
Implements embvm::VirtualMessageQueue< TType >.
References assert, os::posix::MessageQueue< TType >::handle_, and r.
full()
template<typename TType > bool os::posix::MessageQueue< TType >::full () const inline final virtual noexcept
Check if the message queue is full.
Returns
true if the queue is full, false otherwise.
Implements embvm::VirtualMessageQueue< TType >.
References assert, os::posix::MessageQueue< TType >::handle_, and r.
native_handle()
template<typename TType > virtual embvm::msgqueue::handle_t embvm::VirtualMessageQueue< TType >::native_handle () const pure virtual noexcept inherited
Get the native handle for the message queue object.
Returns
the native handle for this message queue object. The handle will always return the handle_t and it must be cast to the native handle type by the user.
Implemented in os::freertos::MessageQueue< TType >.
pop()
template<typename TType > TType os::posix::MessageQueue< TType >::pop (embvm::os_timeout_t timeout = embvm::OS_WAIT_FOREVER) inline final virtual noexcept
Retrieve a message from the queue.
Retrieve a message from the queue. This function blocks the calling thread until a message is received (if OS_WAIT_FOREVER is specified as a timeout), or until the timeout expires.
Parameters
timeout The time to wait for a new message. A value of OS_WAIT_FOREVER indicates that the thread should block until a new message is posted.
Returns
an optional value. Use has_value() member function to determine if the value is valid. A valid value is only returned on success.
Implements embvm::VirtualMessageQueue< TType >.
References assert, and os::posix::MessageQueue< TType >::handle_.
push()
template<typename TType > bool os::posix::MessageQueue< TType >::push (TType val, embvm::os_timeout_t timeout = embvm::OS_WAIT_FOREVER) inline final virtual noexcept
Post a message to the queue.
Post a message to the queue. This function blocks the calling thread until there is an available slot (if OS_WAIT_FOREVER is specified as a timeout), or until the timeout expires.
Posting a message to the queue will notify all threads waiting on a new message (via pop()).
Parameters
val The data value to post to the queue.
timeout The time to wait for a new message. A value of OS_WAIT_FOREVER indicates that the thread should block until a new message is posted.
Returns
true if the message was successfully posted, false otherwise.
Implements embvm::VirtualMessageQueue< TType >.
reset()
template<typename TType > void os::posix::MessageQueue< TType >::reset () inline final virtual noexcept
Reset the message queue to an empty state.
Postcondition
The message queue is emptied, with size 0.
Implements embvm::VirtualMessageQueue< TType >.
References os::posix::MessageQueue< TType >::handle_.
size()
template<typename TType > size_t os::posix::MessageQueue< TType >::size () const inline final virtual noexcept
Get the current size of the message queue.
Size represents the number of elements stored, rather than the maximum size (aka capacity).
Returns
the current number of elements stored in the message queue.
Implements embvm::VirtualMessageQueue< TType >.
References assert, os::posix::MessageQueue< TType >::handle_, and r.
Member Data Documentation
handle_
template<typename TType > mqd_t os::posix::MessageQueue< TType >::handle_ private
The message queue instance handle.
Referenced by os::posix::MessageQueue< TType >::empty(), os::posix::MessageQueue< TType >::full(), os::posix::MessageQueue< TType >::MessageQueue(), os::posix::MessageQueue< TType >::pop(), os::posix::MessageQueue< TType >::reset(), os::posix::MessageQueue< TType >::size(), and os::posix::MessageQueue< TType >::~MessageQueue().
name_
template<typename TType > std::string_view os::posix::MessageQueue< TType >::name_ private
The name of this message queue instance.
Referenced by os::posix::MessageQueue< TType >::MessageQueue().
os::posix::Mutex
class os::posix::Mutex
POSIX Mutex Implementation.
Useful reference documentation:
posix mutex API: https://docs.oracle.com/cd/E19455-01/806-5257/6je9h032o/index.html
posix mutex attributes: https://docs.oracle.com/cd/E19683-01/806-6867/6jfpgdcnf/index.html
Public Member Functions
Mutex (embvm::mutex::type type=embvm::mutex::type::defaultType, embvm::mutex::mode mode=embvm::mutex::mode::defaultMode) noexcept
Construct a POSIX mutex.
~Mutex () noexcept
Default destructor.
void lock () noexcept final
Lock the mutex.
void unlock () noexcept final
Unlock the mutex.
bool trylock () noexcept final
Try to lock the mutex.
embvm::mutex::handle_t native_handle () const noexcept final
Private Attributes
pthread_mutex_t handle_
The pthread handle associated with this mutex;.
Constructor & Destructor Documentation
Mutex()
os::posix::Mutex::Mutex (embvm::mutex::type type = embvm::mutex::type::defaultType, embvm::mutex::mode mode = embvm::mutex::mode::defaultMode) inline explicit noexcept
Construct a POSIX mutex.
Parameters
type The mutex type to create (normal, recursive)
mode The mutex poperating mode, which controls priority inheritance behaviors.
References assert, handle_, embvm::mutex::none, embvm::mutex::normal, embvm::mutex::priorityInherit, embvm::mutex::protect, r, embvm::mutex::recursive, and type.
~Mutex()
Mutex::~Mutex () noexcept
Default destructor.
References assert, handle_, and r.
Member Function Documentation
lock()
void os::posix::Mutex::lock () inline final virtual noexcept
Lock the mutex.
Attempts to lock the mutex. If successful, the function returns with the calling thread owning the lock. If the lock is already owned, the calling thread will block until the lock is available.
Postcondition
The mutex is locked and owned by the calling thread.
Implements embvm::VirtualMutex.
References assert, handle_, and r.
Referenced by os::posix::EventFlag::clear(), os::posix::EventFlag::get(), os::posix::EventFlag::set(), and os::posix::EventFlag::setFromISR().
native_handle()
embvm::mutex::handle_t os::posix::Mutex::native_handle () const inline final virtual noexcept
Implements embvm::VirtualMutex.
References handle_.
trylock()
bool os::posix::Mutex::trylock () inline final virtual noexcept
Try to lock the mutex.
Try to lock the mutex, but don't block the thread if the mutex is already owned.
Postcondition
If the mutex is unowned, the mutex will be locked and owned by the calling thread.
Returns
true if the mutex is successfully locked, false if another thread owns the mutex.
Implements embvm::VirtualMutex.
References assert, EBUSY, handle_, and r.
unlock()
void os::posix::Mutex::unlock () inline final virtual noexcept
Unlock the mutex.
Precondition
The mutex is locked and owned by the calling thread.
Postcondition
The mutex is unlocked.
Implements embvm::VirtualMutex.
References assert, handle_, and r.
Referenced by os::posix::EventFlag::clear(), os::posix::EventFlag::get(), os::posix::EventFlag::set(), and os::posix::EventFlag::setFromISR().
Member Data Documentation
handle_
pthread_mutex_t os::posix::Mutex::handle_ private
The pthread handle associated with this mutex;.
Referenced by lock(), Mutex(), native_handle(), trylock(), unlock(), and ~Mutex().
os::posix::Semaphore
class os::posix::Semaphore
Create a POSIX semaphore (OSX variant)
Useful reference documenation:
POSIX semaphore APIs: https://docs.oracle.com/cd/E19120-01/open.solaris/817-4415/svipc-75667/index.html
Public Member Functions
Semaphore (embvm::semaphore::mode mode=embvm::semaphore::mode::counting, embvm::semaphore::count_t ceiling=1, embvm::semaphore::count_t initial_count=-1) noexcept
~Semaphore ()
void give () noexcept final
Increment count Return a resource to the semaphore, incrementing the count.
void giveFromISR () noexcept final
Increment count from an ISR Return a resource to the semaphore, incrementing the count.
bool take (embvm::os_timeout_t timeout=embvm::OS_WAIT_FOREVER) noexcept final
embvm::semaphore::count_t count () noexcept final
embvm::semaphore::handle_t native_handle () const noexcept final
virtual bool take (const embvm::os_timeout_t &timeout=embvm::OS_WAIT_FOREVER) noexcept=0
Decrement count Take a resource from the semaphore, decrementing the count.
virtual embvm::semaphore::count_t count () const noexcept=0
Check the count of the semaphore.
Private Attributes
sem_t handle_
Constructor & Destructor Documentation
Semaphore()
os::posix::Semaphore::Semaphore (embvm::semaphore::mode mode = embvm::semaphore::mode::counting, embvm::semaphore::count_t ceiling = 1, embvm::semaphore::count_t initial_count = -1) inline explicit noexcept
References assert, embvm::semaphore::binary, handle_, r, and take().
~Semaphore()
Semaphore::~Semaphore () noexcept
References assert, handle_, and r.
Member Function Documentation
count() [1/2]
virtual embvm::semaphore::count_t embvm::VirtualSemaphore::count () const pure virtual noexcept inherited
Check the count of the semaphore.
Returns
The current semaphore count.
Implemented in os::freertos::Semaphore.
count() [2/2]
embvm::semaphore::count_t os::posix::Semaphore::count () inline final noexcept
References assert, handle_, and r.
give()
void os::posix::Semaphore::give () inline final virtual noexcept
Increment count Return a resource to the semaphore, incrementing the count.
Implements embvm::VirtualSemaphore.
References assert, handle_, and r.
giveFromISR()
void os::posix::Semaphore::giveFromISR () inline final virtual noexcept
Increment count from an ISR Return a resource to the semaphore, incrementing the count.
This function variant is safe to call from an interrupt routine. No locking can be used inside this variant.
Implements embvm::VirtualSemaphore.
References assert, handle_, and r.
native_handle()
embvm::semaphore::handle_t os::posix::Semaphore::native_handle () const inline final virtual noexcept
Implements embvm::VirtualSemaphore.
References handle_.
take() [1/2]
virtual bool embvm::VirtualSemaphore::take (const embvm::os_timeout_t & timeout = embvm::OS_WAIT_FOREVER) pure virtual noexcept inherited
Decrement count Take a resource from the semaphore, decrementing the count.
Parameters
timeout The time to wait for a semaphore resource. A value of WAIT_FOREVER indicates that the thread should block until the semaphore can be acquired.
Returns
true if take was successful, false if a timeout occurred.
Implemented in os::freertos::Semaphore.
take() [2/2]
bool os::posix::Semaphore::take (embvm::os_timeout_t timeout = embvm::OS_WAIT_FOREVER) inline final noexcept
References assert, handle_, and r.
Referenced by Semaphore().
Member Data Documentation
handle_
sem_t os::posix::Semaphore::handle_ private
Referenced by count(), give(), giveFromISR(), native_handle(), Semaphore(), take(), and ~Semaphore().
os::posix::Thread
class os::posix::Thread
Create a POSIX thread.
Public Member Functions
Thread (std::string_view name, embvm::thread::func_t func, embvm::thread::input_t arg, embvm::thread::priority p=embvm::thread::priority::normal, size_t stack_size=PTHREAD_STACK_MIN, void *stack_ptr=nullptr) noexcept
Construct a POSIX thread.
~Thread () noexcept
Default destructor, cleans up thread on deletion.
void start () noexcept final
Start the thread, if it is not auto-started.
void terminate () noexcept final
Terminate a running thread.
void join () noexcept final
Join a running thread.
int detach () noexcept
std::string_view name () const noexcept final
View the thread's name.
embvm::thread::state state () const noexcept final
Get the thread state.
embvm::thread::handle_t native_handle () const noexcept final
Get the native handle for the thread.
Private Member Functions
void * thread_func () noexcept
Thread handling wrapper to support thread canceling.
Private Attributes
std::string_view name_
THe name of this thread instance.
pthread_t handle_
The pthread handle corresponding to this thread instance.
embvm::thread::input_t arg_
Thread input arguments.
embvm::thread::func_t func_
The functor which will be invokd by the thread.
std::atomic< embvm::thread::state > state_ = embvm::thread::state::ready
Constructor & Destructor Documentation
Thread()
os::posix::Thread::Thread (std::string_view name, embvm::thread::func_t func, embvm::thread::input_t arg, embvm::thread::priority p = embvm::thread::priority::normal, size_t stack_size = PTHREAD_STACK_MIN, void * stack_ptr = nullptr) inline explicit noexcept
Construct a POSIX thread.
Parameters
name The name associated with the mutex.
Note
A std::string input must remain valid for the lifetime of this object, since std::string_view is used to store the name.
Parameters
func The thread function to execute; can be any functor type.
arg The thread's optional input argument. This value is passed to the thread when it is created.
p The thread priority setting.
stack_size The thread stack size.
stack_ptr The thread stack pointer. If stack_ptr is nullptr, then memory will be allocated by the pthread library.
References assert, BOUNCE, os::posix::convert_to_pthread_priority(), handle_, embutil::is_aligned(), NULL, p, PTHREAD_STACK_MIN, r, embvm::thread::ready, state_, and thread_func().
~Thread()
Thread::~Thread () noexcept
Default destructor, cleans up thread on deletion.
References embvm::thread::completed, join(), state_, terminate(), and embvm::thread::terminated.
Member Function Documentation
detach()
int os::posix::Thread::detach () inline noexcept
References handle_.
join()
void os::posix::Thread::join () inline final virtual noexcept
Join a running thread.
Joins a running thread, blocking the calling thread until the joined thread completes.
Precondition
The thread has not exited.
Postcondition
The thread has exited.
Implements embvm::VirtualThread.
References assert, EDEADLK, EINVAL, handle_, and r.
Referenced by ~Thread().
name()
std::string_view os::posix::Thread::name () const inline final virtual noexcept
View the thread's name.
Storage for the thread name is implementation defined. For example, the name may be stored in the RTOS memory, or it may require internal object storage.
Returns
The thread object's name.
Implements embvm::VirtualThread.
References name_.
native_handle()
embvm::thread::handle_t os::posix::Thread::native_handle () const inline final virtual noexcept
Get the native handle for the thread.
If custom extensions or behaviors are needed, the thread handle can be retrieved and manipulated directly.
Returns
the native thread object handle as a void*. The user must cast appropriately.
Implements embvm::VirtualThread.
References handle_.
start()
void os::posix::Thread::start () inline final virtual noexcept
Start the thread, if it is not auto-started.
Implements embvm::VirtualThread.
state()
embvm::thread::state os::posix::Thread::state () const inline final virtual noexcept
Get the thread state.
Returns
The state of the thread.
Implements embvm::VirtualThread.
References state_.
terminate()
void os::posix::Thread::terminate () inline final virtual noexcept
Terminate a running thread.
Precondition
The thread is running.
Postcondition
The thread is aborted.
Implements embvm::VirtualThread.
References assert, handle_, r, state_, and embvm::thread::terminated.
Referenced by ~Thread().
thread_func()
void* os::posix::Thread::thread_func () inline private noexcept
Thread handling wrapper to support thread canceling.
We wrap the thread to enable canceling, and so we can gracefully tell if the thread has completed successfully
References arg_, assert, embvm::thread::completed, embvm::thread::executing, func_, r, and state_.
Referenced by Thread().
Member Data Documentation
arg_
embvm::thread::input_t os::posix::Thread::arg_ private
Thread input arguments.
Referenced by thread_func().
func_
embvm::thread::func_t os::posix::Thread::func_ private
The functor which will be invokd by the thread.
Referenced by thread_func().
handle_
pthread_t os::posix::Thread::handle_ private
The pthread handle corresponding to this thread instance.
Referenced by detach(), join(), native_handle(), terminate(), and Thread().
name_
std::string_view os::posix::Thread::name_ private
THe name of this thread instance.
Referenced by name().
state_
std::atomic<embvm::thread::state> os::posix::Thread::state_ = embvm::thread::state::ready private
Referenced by state(), terminate(), Thread(), thread_func(), and ~Thread().
Enumeration Type Documentation
pthread_priority
enum os::posix::pthread_priority : uint8_t strong
PThread priority values.
Note
For PThreads: higher number = higher priority
Enumerator
panic
interrupt
realtime
veryHigh
high
aboveNormal
normal
belowNormal
low
lowest
idle
Function Documentation
convert_to_pthread_priority()
constexpr posix::pthread_priority os::posix::convert_to_pthread_priority (embvm::thread::priority p) noexcept
Convert between framework thread priorities and PThread priorities.
References os::posix::aboveNormal, embvm::thread::aboveNormal, assert, os::posix::belowNormal, embvm::thread::belowNormal, os::posix::high, embvm::thread::high, os::posix::idle, embvm::thread::idle, os::posix::interrupt, embvm::thread::interrupt, os::posix::low, embvm::thread::low, os::posix::lowest, embvm::thread::lowest, os::posix::normal, embvm::thread::normal, p, os::posix::panic, embvm::thread::panic, os::posix::realtime, embvm::thread::realtime, os::posix::veryHigh, and embvm::thread::veryHigh.
Referenced by os::posix::Thread::Thread().