Embedded Artistry Framework: src/stdlibs/libc/src/ctype/isalpha.c File Reference
isalpha.c File Reference
#include <ctype.h>
Functions
int isalpha (int c)
Checks if the given character is an alphabetic character.
Function Documentation
isalpha()
int isalpha (int ch)
Checks if the given character is an alphabetic character.
Checks if the given character is an alphabetic character, i.e. either an uppercase letter (ABCDEFGHIJKLMNOPQRSTUVWXYZ), or a lowercase letter (abcdefghijklmnopqrstuvwxyz)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is an alphabetic character, zero otherwise.
Referenced by bad_input(), good_input(), isalnum(), strtol(), strtoll(), and strtoul().