Embedded Artistry Framework: src/stdlibs/libc/openlibm/include/openlibm_complex.h File Reference
openlibm_complex.h File Reference
Macros
#define OPENLIBM_COMPLEX_H
#define complex _Complex
#define _Complex_I 1.0fi
#define I _Complex_I
Functions
static float complex CMPLXF (float x, float y)
static double complex CMPLX (double x, double y)
static long double complex CMPLXL (long double x, long double y)
double complex cacos (double complex)
double complex casin (double complex)
double complex catan (double complex)
double complex ccos (double complex)
double complex csin (double complex)
double complex ctan (double complex)
double complex cacosh (double complex)
double complex casinh (double complex)
double complex catanh (double complex)
double complex ccosh (double complex)
double complex csinh (double complex)
double complex ctanh (double complex)
double complex cexp (double complex)
double complex clog (double complex)
double cabs (double complex)
double complex cpow (double complex, double complex)
double complex csqrt (double complex)
double carg (double complex)
double cimag (double complex)
double complex conj (double complex)
double complex cproj (double complex)
double creal (double complex)
float complex cacosf (float complex)
float complex casinf (float complex)
float complex catanf (float complex)
float complex ccosf (float complex)
float complex csinf (float complex)
float complex ctanf (float complex)
float complex cacoshf (float complex)
float complex casinhf (float complex)
float complex catanhf (float complex)
float complex ccoshf (float complex)
float complex csinhf (float complex)
float complex ctanhf (float complex)
float complex cexpf (float complex)
float complex clogf (float complex)
float cabsf (float complex)
float complex cpowf (float complex, float complex)
float complex csqrtf (float complex)
float cargf (float complex)
float cimagf (float complex)
float complex conjf (float complex)
float complex cprojf (float complex)
float crealf (float complex)
long double complex cacosl (long double complex)
long double complex casinl (long double complex)
long double complex catanl (long double complex)
long double complex ccosl (long double complex)
long double complex csinl (long double complex)
long double complex ctanl (long double complex)
long double complex cacoshl (long double complex)
long double complex casinhl (long double complex)
long double complex catanhl (long double complex)
long double complex ccoshl (long double complex)
long double complex csinhl (long double complex)
long double complex ctanhl (long double complex)
long double complex cexpl (long double complex)
long double complex clogl (long double complex)
long double cabsl (long double complex)
long double complex cpowl (long double complex, long double complex)
long double complex csqrtl (long double complex)
long double cargl (long double complex)
long double cimagl (long double complex)
long double complex conjl (long double complex)
long double complex cprojl (long double complex)
long double creall (long double complex)
Macro Definition Documentation
_Complex_I
#define _Complex_I 1.0fi
complex
#define complex _Complex
I
#define I _Complex_I
OPENLIBM_COMPLEX_H
#define OPENLIBM_COMPLEX_H
Function Documentation
cabs()
double cabs (double complex)
References cimag(), creal(), hypot(), and z.
Referenced by clog(), and cpow().
cabsf()
float cabsf (float complex)
References cimagf(), crealf(), hypotf(), and z.
Referenced by clogf(), and cpowf().
cabsl()
long double cabsl (long double complex)
References cimagl(), creall(), hypotl(), and z.
Referenced by casinl(), clogl(), and cpowl().
cacos()
double complex cacos (double complex)
References casin(), cimag(), complex, creal(), I, w, and z.
Referenced by cacosh().
cacosf()
float complex cacosf (float complex)
References casinf(), cimagf(), complex, crealf(), I, w, and z.
Referenced by cacoshf().
cacosh()
double complex cacosh (double complex)
References cacos(), complex, I, w, and z.
cacoshf()
float complex cacoshf (float complex)
References cacosf(), complex, I, w, and z.
cacoshl()
long double complex cacoshl (long double complex)
References cacosl(), complex, I, w, and z.
cacosl()
long double complex cacosl (long double complex)
References casinl(), cimagl(), complex, creall(), I, PIO2L, w, and z.
Referenced by cacoshl().
carg()
double carg (double complex)
References atan2(), cimag(), creal(), and z.
Referenced by cpow().
cargf()
float cargf (float complex)
References atan2f(), cimagf(), crealf(), and z.
Referenced by cpowf().
cargl()
long double cargl (long double complex)
References atan2l(), cimagl(), creall(), and z.
Referenced by cpowl().
casin()
double complex casin (double complex)
References asin(), cimag(), clog(), complex, creal(), csqrt(), fabs(), I, w, and z.
Referenced by cacos(), and casinh().
casinf()
float complex casinf (float complex)
References asinf(), cimagf(), clogf(), complex, crealf(), csqrtf(), fabsf(), I, w, and z.
Referenced by cacosf(), and casinhf().
casinh()
double complex casinh (double complex)
References casin(), complex, I, w, and z.
casinhf()
float complex casinhf (float complex)
References casinf(), complex, I, w, and z.
casinhl()
long double complex casinhl (long double complex)
References casinl(), complex, I, w, and z.
casinl()
long double complex casinl (long double complex)
References asinl(), b, cabsl(), cimagl(), clogl(), complex, creall(), csqrtl(), fabsl(), I, MACHEPL, n, PIO2L, sum(), w, and z.
Referenced by cacosl(), and casinhl().
catan()
double complex catan (double complex)
References _redupi(), a, atan2(), cimag(), complex, creal(), I, log(), MAXNUM, t, w, and z.
Referenced by catanh().
catanf()
float complex catanf (float complex)
References _redupif(), a, atan2f(), cimagf(), complex, crealf(), I, logf(), MAXNUMF, t, w, and z.
Referenced by catanhf().
catanh()
double complex catanh (double complex)
References catan(), complex, I, w, and z.
catanhf()
float complex catanhf (float complex)
References catanf(), complex, I, w, and z.
catanhl()
long double complex catanhl (long double complex)
References catanl(), complex, I, w, and z.
catanl()
long double complex catanl (long double complex)
References a, atan2l(), cimagl(), complex, creall(), I, LDBL_MAX, logl(), redupil(), t, w, and z.
Referenced by catanhl().
ccos()
double complex ccos (double complex)
References _cchsh(), ccosh(), cimag(), CMPLX(), complex, cos(), creal(), I, sin(), w, and z.
ccosf()
float complex ccosf (float complex)
References _cchshf(), ccoshf(), cimagf(), CMPLXF(), complex, cosf(), crealf(), I, sinf(), w, and z.
ccosh()
double complex ccosh (double complex)
References __ldexp_cexp(), cimag(), CMPLX(), copysign(), cos(), cosh(), creal(), exp(), EXTRACT_WORDS, fabs(), huge, sin(), sinh(), and z.
Referenced by ccos().
ccoshf()
float complex ccoshf (float complex)
References __ldexp_cexpf(), cimagf(), CMPLXF(), copysignf(), cosf(), coshf(), crealf(), expf(), fabsf(), GET_FLOAT_WORD, huge, sinf(), sinhf(), and z.
Referenced by ccosf().
ccoshl()
long double complex ccoshl (long double complex)
References cimagl(), complex, coshl(), cosl(), creall(), I, sinhl(), sinl(), w, and z.
ccosl()
long double complex ccosl (long double complex)
References cchshl(), cimagl(), complex, cosl(), creall(), I, sinl(), w, and z.
cexp()
double complex cexp (double complex)
References __ldexp_cexp(), cexp_ovfl, cimag(), CMPLX(), cos(), creal(), exp(), exp_ovfl, EXTRACT_WORDS, sin(), and z.
cexpf()
float complex cexpf (float complex)
References __ldexp_cexpf(), cexp_ovfl, cimagf(), CMPLXF(), cosf(), crealf(), exp_ovfl, expf(), GET_FLOAT_WORD, sinf(), and z.
cexpl()
long double complex cexpl (long double complex)
References cimagl(), complex, cosl(), creall(), expl(), I, r, sinl(), w, and z.
cimag()
double cimag (double complex)
References z.
Referenced by __ldexp_cexp(), _ctans(), cabs(), cacos(), carg(), casin(), catan(), ccos(), ccosh(), cexp(), clog(), conj(), cpow(), cproj(), csin(), csinh(), csqrt(), ctan(), and ctanh().
cimagf()
float cimagf (float complex)
References z.
Referenced by __ldexp_cexpf(), _ctansf(), cabsf(), cacosf(), cargf(), casinf(), catanf(), ccosf(), ccoshf(), cexpf(), clogf(), conjf(), cpowf(), cprojf(), csinf(), csinhf(), csqrtf(), ctanf(), and ctanhf().
cimagl()
long double cimagl (long double complex)
References z.
Referenced by cabsl(), cacosl(), cargl(), casinl(), catanl(), ccoshl(), ccosl(), cexpl(), clogl(), conjl(), cpowl(), cprojl(), csinhl(), csinl(), csqrtl(), ctanhl(), ctanl(), and ctansl().
clog()
double complex clog (double complex)
References atan2(), cabs(), cimag(), complex, creal(), I, log(), p, w, and z.
Referenced by casin().
clogf()
float complex clogf (float complex)
References atan2f(), cabsf(), cimagf(), complex, crealf(), I, logf(), p, w, and z.
Referenced by casinf().
clogl()
long double complex clogl (long double complex)
References atan2l(), cabsl(), cimagl(), complex, creall(), I, logl(), p, w, and z.
Referenced by casinl().
CMPLX()
static double complex CMPLX (double x, double y) inline static
References a, complex, and z.
Referenced by __ldexp_cexp(), ccos(), ccosh(), cexp(), conj(), cproj(), csin(), csinh(), csqrt(), ctan(), and ctanh().
CMPLXF()
static float complex CMPLXF (float x, float y) inline static
References a, complex, and z.
Referenced by __ldexp_cexpf(), ccosf(), ccoshf(), cexpf(), conjf(), cprojf(), csinf(), csinhf(), csqrtf(), ctanf(), and ctanhf().
CMPLXL()
static long double complex CMPLXL (long double x, long double y) inline static
References a, complex, and z.
Referenced by conjl(), cprojl(), and csqrtl().
conj()
double complex conj (double complex)
References cimag(), CMPLX(), creal(), and z.
conjf()
float complex conjf (float complex)
References cimagf(), CMPLXF(), crealf(), and z.
conjl()
long double complex conjl (long double complex)
References cimagl(), CMPLXL(), creall(), and z.
cpow()
double complex cpow (double complex, double complex)
References a, cabs(), carg(), cimag(), complex, cos(), creal(), exp(), I, log(), pow(), r, sin(), w, and z.
cpowf()
float complex cpowf (float complex, float complex)
References a, cabsf(), cargf(), cimagf(), complex, cosf(), crealf(), expf(), I, logf(), powf(), r, sinf(), w, and z.
cpowl()
long double complex cpowl (long double complex, long double complex)
References a, cabsl(), cargl(), cimagl(), complex, cosl(), creall(), expl(), I, logl(), powl(), r, sinl(), w, and z.
cproj()
double complex cproj (double complex)
References cimag(), CMPLX(), copysign(), creal(), INFINITY, isinf, and z.
cprojf()
float complex cprojf (float complex)
References cimagf(), CMPLXF(), copysignf(), crealf(), INFINITY, isinf, and z.
cprojl()
long double complex cprojl (long double complex)
References cimagl(), CMPLXL(), copysignl(), creall(), INFINITY, isinf, and z.
creal()
double creal (double complex)
References z.
Referenced by __ldexp_cexp(), _ctans(), cabs(), cacos(), carg(), casin(), catan(), ccos(), ccosh(), cexp(), clog(), conj(), cpow(), cproj(), csin(), csinh(), csqrt(), ctan(), and ctanh().
crealf()
float crealf (float complex)
References z.
Referenced by __ldexp_cexpf(), _ctansf(), cabsf(), cacosf(), cargf(), casinf(), catanf(), ccosf(), ccoshf(), cexpf(), clogf(), conjf(), cpowf(), cprojf(), csinf(), csinhf(), csqrtf(), ctanf(), and ctanhf().
creall()
long double creall (long double complex)
References z.
Referenced by cabsl(), cacosl(), cargl(), casinl(), catanl(), ccoshl(), ccosl(), cexpl(), clogl(), conjl(), cpowl(), cprojl(), csinhl(), csinl(), csqrtl(), ctanhl(), ctanl(), and ctansl().
csin()
double complex csin (double complex)
References cchsh(), cimag(), CMPLX(), complex, cos(), creal(), csinh(), I, sin(), w, and z.
csinf()
float complex csinf (float complex)
References cchshf(), cimagf(), CMPLXF(), complex, cosf(), crealf(), csinhf(), I, sinf(), w, and z.
csinh()
double complex csinh (double complex)
References __ldexp_cexp(), cimag(), CMPLX(), copysign(), cos(), cosh(), creal(), exp(), EXTRACT_WORDS, fabs(), huge, INFINITY, sin(), sinh(), and z.
Referenced by csin().
csinhf()
float complex csinhf (float complex)
References __ldexp_cexpf(), cimagf(), CMPLXF(), copysignf(), cosf(), coshf(), crealf(), expf(), fabsf(), GET_FLOAT_WORD, huge, INFINITY, sinf(), sinhf(), and z.
Referenced by csinf().
csinhl()
long double complex csinhl (long double complex)
References cimagl(), complex, coshl(), cosl(), creall(), I, sinhl(), sinl(), w, and z.
csinl()
long double complex csinl (long double complex)
References cchshl(), cimagl(), complex, cosl(), creall(), I, sinl(), w, and z.
csqrt()
double complex csqrt (double complex)
References a, b, cimag(), CMPLX(), complex, copysign(), creal(), fabs(), hypot(), INFINITY, isinf, isnan, signbit, sqrt(), t, THRESH, and z.
Referenced by casin().
csqrtf()
float complex csqrtf (float complex)
References a, b, cimagf(), CMPLXF(), copysignf(), crealf(), fabsf(), hypot(), INFINITY, isinf, isnan, signbit, sqrt(), t, and z.
Referenced by casinf().
csqrtl()
long double complex csqrtl (long double complex)
References a, b, cimagl(), CMPLXL(), complex, copysignl(), creall(), fabsl(), hypotl(), INFINITY, isinf, isnan, signbit, sqrtl(), t, THRESH, and z.
Referenced by casinl().
ctan()
double complex ctan (double complex)
References _ctans(), cimag(), CMPLX(), complex, cos(), cosh(), creal(), ctanh(), fabs(), I, MAXNUM, sin(), sinh(), w, and z.
ctanf()
float complex ctanf (float complex)
References _ctansf(), cimagf(), CMPLXF(), complex, cosf(), coshf(), crealf(), ctanhf(), fabsf(), I, MAXNUMF, sinf(), sinhf(), w, and z.
ctanh()
double complex ctanh (double complex)
References cimag(), CMPLX(), copysign(), cos(), creal(), exp(), EXTRACT_WORDS, fabs(), isfinite, isinf, s, SET_HIGH_WORD, sin(), sinh(), sqrt(), t, tan(), and z.
Referenced by ctan().
ctanhf()
float complex ctanhf (float complex)
References cimagf(), CMPLXF(), copysignf(), cosf(), crealf(), expf(), fabsf(), GET_FLOAT_WORD, isfinite, isinf, s, SET_FLOAT_WORD, sinf(), sinhf(), sqrtf(), t, tanf(), and z.
Referenced by ctanf().
ctanhl()
long double complex ctanhl (long double complex)
References cimagl(), complex, coshl(), cosl(), creall(), I, sinhl(), sinl(), w, and z.
ctanl()
long double complex ctanl (long double complex)
References cimagl(), complex, coshl(), cosl(), creall(), ctansl(), fabsl(), I, LDBL_MAX, sinhl(), sinl(), w, and z.