Embedded Artistry Framework: os::posix::ConditionVariable Class Reference
os::posix::ConditionVariable Class Reference final
#include <posix_condition_variable.hpp>
Public Member Functions
ConditionVariable ()=default
~ConditionVariable ()
bool wait (embvm::VirtualMutex *mutex) noexcept final
Blocks the current thread until the condition variable is woken up or after the specified timeout duration.
bool wait (embvm::VirtualMutex *mutex, const embvm::os_timeout_t &timeout) noexcept final
bool timed_wait (embvm::VirtualMutex *mutex, timespec timeout) noexcept
void signal () noexcept final
notifies one waiting thread
void broadcast () noexcept final
Notify all waiting threads.
embvm::cv::handle_t native_handle () const noexcept final
bool wait (embvm::VirtualMutex *mutex, const embvm::cv::func_t &predicate) noexcept
bool wait (embvm::VirtualMutex *mutex, const embvm::cv::func_t &predicate, const embvm::os_timeout_t &timeout=embvm::OS_WAIT_FOREVER) noexcept
void notify_one () noexcept
Alias for signal so we can work with STL types.
void notify_all () noexcept
Alias for broadcast so we can work with STL types.
Private Attributes
pthread_cond_t handle_ = PTHREAD_COND_INITIALIZER
Constructor & Destructor Documentation
ConditionVariable()
os::posix::ConditionVariable::ConditionVariable () default
~ConditionVariable()
os::posix::ConditionVariable::~ConditionVariable () inline
References assert, handle_, and r.
Member Function Documentation
broadcast()
void os::posix::ConditionVariable::broadcast () inline final virtual noexcept
Notify all waiting threads.
Implements embvm::VirtualConditionVariable.
References assert, handle_, and r.
Referenced by os::posix::EventFlag::set(), and os::posix::EventFlag::setFromISR().
native_handle()
embvm::cv::handle_t os::posix::ConditionVariable::native_handle () const inline final virtual noexcept
Implements embvm::VirtualConditionVariable.
References handle_.
notify_all()
void embvm::VirtualConditionVariable::notify_all () inline noexcept inherited
Alias for broadcast so we can work with STL types.
References embvm::VirtualConditionVariable::broadcast().
notify_one()
void embvm::VirtualConditionVariable::notify_one () inline noexcept inherited
Alias for signal so we can work with STL types.
References embvm::VirtualConditionVariable::signal().
signal()
void os::posix::ConditionVariable::signal () inline final virtual noexcept
notifies one waiting thread
Implements embvm::VirtualConditionVariable.
References assert, handle_, and r.
timed_wait()
bool os::posix::ConditionVariable::timed_wait (embvm::VirtualMutex * mutex, timespec timeout) inline noexcept
References handle_.
Referenced by wait().
wait() [1/4]
bool os::posix::ConditionVariable::wait (embvm::VirtualMutex * mutex) inline final virtual noexcept
Blocks the current thread until the condition variable is woken up or after the specified timeout duration.
Implements embvm::VirtualConditionVariable.
References assert, handle_, and r.
Referenced by os::posix::EventFlag::get(), and wait().
wait() [2/4]
bool os::posix::ConditionVariable::wait (embvm::VirtualMutex * mutex, const embvm::os_timeout_t & timeout) inline final virtual noexcept
Implements embvm::VirtualConditionVariable.
References embvm::OS_WAIT_FOREVER, timed_wait(), embutil::timepointToTimespec(), and wait().
wait() [3/4]
bool embvm::VirtualConditionVariable::wait (embvm::VirtualMutex * mutex, const embvm::cv::func_t & predicate) inline noexcept inherited
References embvm::VirtualConditionVariable::wait().
wait() [4/4]
bool embvm::VirtualConditionVariable::wait (embvm::VirtualMutex * mutex, const embvm::cv::func_t & predicate, const embvm::os_timeout_t & timeout = embvm::OS_WAIT_FOREVER) inline noexcept inherited
We break when the predicate is true or when we've timed out
References embvm::VirtualConditionVariable::wait().
Member Data Documentation
handle_
pthread_cond_t os::posix::ConditionVariable::handle_ = PTHREAD_COND_INITIALIZER private
Referenced by broadcast(), native_handle(), signal(), timed_wait(), wait(), and ~ConditionVariable().
The documentation for this class was generated from the following file:
src/os/posix/posix_condition_variable.hpp