Embedded Artistry libc: src/gdtoa/src/smisc.c File Reference
smisc.c File Reference
#include "gdtoaimp.h"
Functions
Bigint * s2b (CONST char *s, int nd0, int nd, ULong y9)
double ratio (Bigint *a, Bigint *b)
void copybits (ULong *c, int n, Bigint *b)
ULong any_on (Bigint *b, int k)
Function Documentation
any_on()
ULong any_on (Bigint * b, int k)
Definition at line 210 of file smisc.c.
 {
     int n, nwds;
     ULong *x, *x0, x1, x2;
     x = b->x;
     nwds = b->wds;
     n = k >> kshift;
     if(n > nwds)
     {
         {
             n = nwds;
         }
     }
     else if(n < nwds && (k &= kmask))
     {
         x1 = x2 = x[n];
         x1 >>= k;
         x1 <<= k;
         if(x1 != x2)
         {
             {
                 return 1;
             }
         }
     }
     x0 = x;
     x += n;
     while(x > x0)
     {
         {
             if(*--x)
             {
                 {
                     return 1;
                 }
             }
         }
     }
     return 0;
 }
References kmask, kshift, Bigint::wds, and Bigint::x.
Referenced by gethex(), and rvOK().
copybits()
void copybits (ULong * c, int n, Bigint * b)
Definition at line 171 of file smisc.c.
 {
     ULong *ce, *x, *xe;
 #ifdef Pack_16
     int nw, nw1;
 #endif
     ce = c + ((n - 1) >> kshift) + 1;
     x = b->x;
 #ifdef Pack_32
     xe = x + b->wds;
     while(x < xe)
     {
         {
             *c++ = *x++;
         }
     }
 #else
     nw = b->wds;
     nw1 = nw & 1;
     for(xe = x + (nw - nw1); x < xe; x += 2)
         Storeinc(c, x[1], x[0]);
     if(nw1)
         *c++ = *x;
 #endif
     while(c < ce)
     {
         {
             *c++ = 0;
         }
     }
 }
References kshift, Storeinc, Bigint::wds, and Bigint::x.
Referenced by rvOK(), strtod(), and strtodg().
ratio()
double ratio (Bigint * a, Bigint * b)
Definition at line 96 of file smisc.c.
 {
     double da, db;
     int k, ka, kb;
     dval(da) = b2d(a, &ka);
     dval(db) = b2d(b, &kb);
     k = ka - kb + ULbits * (a->wds - b->wds);
 #ifdef IBM
     if(k > 0)
     {
         word0(da) += (k >> 2) * Exp_msk1;
         if(k &= 3)
             dval(da) *= 1 << k;
     }
     else
     {
         k = -k;
         word0(db) += (k >> 2) * Exp_msk1;
         if(k &= 3)
             dval(db) *= 1 << k;
     }
 #else
     if(k > 0)
     {
         {
             word0(da) += (unsigned)(k * Exp_msk1);
         }
     }
     else
     {
         k = -k;
         word0(db) += (unsigned)(k * Exp_msk1);
     }
 #endif
     return dval(da) / dval(db);
 }
References b2d(), dval, Exp_msk1, ULbits, Bigint::wds, and word0.
Referenced by strtod(), and strtodg().
s2b()
Bigint* s2b (CONST char * s, int nd0, int nd, ULong y9)
Definition at line 40 of file smisc.c.
 {
     Bigint* b;
     int i, k;
     Long x, y;
     x = (nd + 8) / 9;
     for(k = 0, y = 1; x > y; y <<= 1, k++)
     {
         {
             ;
         }
     }
 #ifdef Pack_32
     b = Balloc(k);
     b->x[0] = y9;
     b->wds = 1;
 #else
     b = Balloc(k + 1);
     b->x[0] = y9 & 0xffff;
     b->wds = (b->x[1] = y9 >> 16) ? 2 : 1;
 #endif
     i = 9;
     if(9 < nd0)
     {
         s += 9;
         do
         {
             {
                 b = multadd(b, 10, *s++ - '0');
             }
         } while(++i < nd0);
         s++;
     }
     else
     {
         {
             s += 10;
         }
     }
     for(; i < nd; i++)
     {
         {
             b = multadd(b, 10, *s++ - '0');
         }
     }
     return b;
 }
References Balloc(), Long, multadd(), Bigint::wds, and Bigint::x.
Referenced by strtod(), and strtodg().