Embedded Artistry Framework: src/stdlibs/libc/src/ctype/islower.c File Reference
islower.c File Reference
#include <ctype.h>
Functions
int islower (int c)
Checks if the given character is classified as a lowercase character.
Function Documentation
islower()
int islower (int ch)
Checks if the given character is classified as a lowercase character.
Checks if the given character is classified as a lowercase character using the default local. islower returns true only for the lowercase letters (abcdefghijklmnopqrstuvwxyz). If islower returns true, it is guaranteed that
See also
iscntrl,
isdigit,
ispunct,
isspace will return false for the same character in the same default locale.
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a lowercase letter, zero otherwise.
Referenced by bad_input(), good_input(), and toupper().