Embedded Artistry Framework: src/stdlibs/libc/src/ctype/isxdigit.c File Reference
isxdigit.c File Reference
#include <ctype.h>
Functions
int isxdigit (int c)
Checks if the given character is a hexadecimal numeric character.
Function Documentation
isxdigit()
int isxdigit (int ch)
Checks if the given character is a hexadecimal numeric character.
Checks if the given character is a hexadecimal numeric character (0123456789).
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is an hexadecimal numeric character, zero otherwise.
References isdigit().
Referenced by __scan_nan(), bad_input(), and good_input().