Embedded Artistry Framework: src/stdlibs/libc/openlibm/test/inf_torture.c File Reference
inf_torture.c File Reference
#include <stdio.h>
#include <math.h>
Functions
int main ()
Function for application main entry.
int main2 ()
int main3 ()
int main4 ()
Function Documentation
main()
int main (void)
Function for application main entry.
References INFINITY, isinf, main2(), and printf.
main2()
int main2 ()
References INFINITY, isinf, main3(), and printf.
Referenced by main().
main3()
int main3 ()
References isnan, main4(), NAN, and printf.
Referenced by main2().
main4()
int main4 ()
References isnan, NAN, and printf.
Referenced by main3().