Embedded Artistry Framework: src/drivers/aardvark/vendor/examples/aaspi_eeprom.c File Reference
aaspi_eeprom.c File Reference
#include "aardvark.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define PAGE_SIZE 32
Functions
static void _writeMemory (Aardvark handle, u16 addr, u16 length, int zero)
static void _readMemory (Aardvark handle, u16 addr, u16 length)
int main (int argc, char *argv[])
Macro Definition Documentation
PAGE_SIZE
#define PAGE_SIZE 32
Function Documentation
_readMemory()
static void _readMemory (Aardvark handle, u16 addr, u16 length) static
References aa_spi_write(), aa_status_string(), data_in, free(), length, malloc(), memset(), and printf.
Referenced by main().
_writeMemory()
static void _writeMemory (Aardvark handle, u16 addr, u16 length, int zero) static
References aa_sleep_ms(), aa_spi_write(), data_in, length, n, PAGE_SIZE, and zero.
Referenced by main().
main()
int main (int argc, char * argv[])
References _readMemory(), _writeMemory(), aa_close(), AA_CONFIG_SPI_I2C, aa_configure(), aa_open(), AA_SPI_BITORDER_MSB, aa_spi_bitrate(), aa_spi_configure(), aa_target_power(), AA_TARGET_POWER_BOTH, atoi(), length, printf, strcmp(), and strtol().