Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_copysignl.c File Reference
s_copysignl.c File Reference
#include <openlibm_math.h>
#include "fpmath.h"
#include "math_private.h"
Functions
OLM_DLLEXPORT long double copysignl (long double x, long double y)
Function Documentation
copysignl()
OLM_DLLEXPORT long double copysignl (long double x, long double y)
References IEEEl2bits::bits, and IEEEl2bits::e.
Referenced by cprojl(), csqrtl(), fmal(), and scalbnl().