Embedded Artistry Framework: src/stdlibs/libc/include/math.h File Reference
math.h File Reference
#include <openlibm_fenv.h>
#include <openlibm_math.h>
Typedefs
typedef float float_t
typedef double double_t
Functions
double fabs (double)
float fabsf (float)
Typedef Documentation
double_t
typedef double double_t
float_t
typedef float float_t
Function Documentation
fabs()
double fabs (double)
Referenced by __ieee754_asin(), __ieee754_atan2(), __ieee754_cosh(), __ieee754_hypot(), __ieee754_j0(), __ieee754_j1(), __ieee754_jn(), __ieee754_lgamma_r(), __ieee754_pow(), __ieee754_remainder(), __ieee754_sinh(), _cchsh(), _ctans(), asinh(), atan(), atof_test(), casin(), cchsh(), ccosh(), check_float_internal(), csinh(), csqrt(), ctan(), ctanh(), dtoa(), erf(), erfc(), fabs_test(), gdtoa(), logb(), remquo(), strtod(), strtod_test(), and tanh().
fabsf()
float fabsf (float)
Referenced by __ieee754_asinf(), __ieee754_atan2f(), __ieee754_coshf(), __ieee754_hypotf(), __ieee754_j0f(), __ieee754_j1f(), __ieee754_jnf(), __ieee754_lgammaf_r(), __ieee754_powf(), __ieee754_remainderf(), __ieee754_sinhf(), _cchshf(), _ctansf(), asinhf(), atanf(), casinf(), cchshf(), ccoshf(), csinhf(), csqrtf(), ctanf(), ctanhf(), erfcf(), erff(), logbf(), remquof(), strtof_test(), and tanhf().