Embedded Artistry libc: src/stdlib/realloc.c File Reference
realloc.c File Reference
#include <stdlib.h>
#include <string.h>
Functions
void * realloc (void *ptr, size_t size)
Reallocates the given area of memory.
void * reallocf (void *ptr, size_t size)
Reallocates the given area of memory.
Function Documentation
realloc()
void* realloc (void * ptr, size_t size)
Reallocates the given area of memory.
Reallocates the given area of memory. It must be previously allocated by
See also
malloc,
calloc or
realloc and not yet freed with a call to
free or
realloc. Otherwise, the results are undefined.
The reallocation is done by either: 1) expanding or contracting the existing area pointed to by ptr, if possible. The contents of the area remain unchanged up to the lesser of the new and old sizes. If the area is expanded, the contents of the new part of the array are undefined. 2) allocating a new memory block of size size bytes, copying memory area with size equal the lesser of the new and the old sizes, and freeing the old block.
If there is not enough memory, the old memory block is not freed and null pointer is returned. If ptr is NULL, the behavior is the same as calling malloc(size).
Parameters
ptr pointer to the memory area to be reallocated
size new size of the array
Returns
pointer to new memory allocation. If size is zero (e.g. realloc(ptr,0)) then returns NULL
Definition at line 4 of file realloc.c.
 {
     void* new_data = NULL;
     if(size)
     {
         if(!ptr)
         {
             return malloc(size);
         }
         new_data = malloc(size);
         if(new_data)
         {
             memcpy(new_data, ptr, size); // TODO: unsafe copy...
             free(ptr); // we always move the data. free.
         }
     }
     return new_data;
 }
References free(), malloc(), memcpy(), and NULL.
Referenced by reallocf().
reallocf()
void* reallocf (void * ptr, size_t size)
Reallocates the given area of memory.
Reallocates the given area of memory. It must be previously allocated by
See also
malloc,
calloc or
realloc and not yet freed with a call to
free or
realloc. Otherwise, the results are undefined.
reallocf is a FreeBSD extension to realloc that frees the input pointer if an error occurrs
This library does not handle the BSD case where realloc(ptr,0) frees the ptr
Parameters
ptr pointer to the memory area to be reallocated
size new size of the array
Returns
pointer to new memory allocation. If size is zero (e.g. realloc(ptr,0)) then returns NULL
Definition at line 26 of file realloc.c.
 {
     void* p = realloc(ptr, size);
     if((p == NULL) && (ptr != NULL))
     {
         free(ptr);
     }
     return p;
 }
References free(), NULL, and realloc().