Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/polevll.c File Reference
polevll.c File Reference
#include <openlibm_math.h>
#include "math_private.h"
Functions
long double __polevll (long double x, void *PP, int n)
long double __p1evll (long double x, void *PP, int n)
Function Documentation
__p1evll()
long double __p1evll (long double x, void * PP, int n)
References n, and P.
Referenced by log10l(), log1pl(), log2l(), logl(), and powl().
__polevll()
long double __polevll (long double x, void * PP, int n)
References n, and P.
Referenced by expl(), log10l(), log1pl(), log2l(), logl(), powl(), stirf(), and tgammal().