Embedded Artistry Framework: src/stdlibs/libmemory/test/tests.h File Reference
tests.h File Reference
Functions
int malloc_tests (void)
int aligned_malloc_tests (void)
Function Documentation
aligned_malloc_tests()
int aligned_malloc_tests (void)
References aligned_malloc_test(), aligned_malloc_tests(), NULL, and posix_memalign_test().
Referenced by aligned_malloc_tests(), and main().
malloc_tests()
int malloc_tests (void)
References malloc_test(), and NULL.
Referenced by main().