Embedded Artistry Framework: Framework Boot Sequencing
Framework Boot Sequencing
Framework Core Components
Components to control the system/program boot process.
Classes
class embvm::BootSequencer< TBootStrategy >
Boot sequencer with customizable boot strategy.
Functions
void entry ()
Prototype for our function entry point; can also be an asm symbol.
void CRTStartup ()
We declare this function here because we don't want to include crt.h and Add a dependency on our libc for the test code.
template<class TPlatform >
void main_thread_func () noexcept
void bootSystem ()
Each platform declares this to control the boot sequence.
template<class TPlatform >
void DefaultBootStrategy () noexcept
Default Framework Boot Strategy.
template<class TPlatform >
void BootOSWithMainThreadStrategy () noexcept
Continue Setup in Main Thread Framework Boot Strategy.
template<class TPlatform >
void OSXSimulatorBootStrategy () noexcept
OSX Simulator Boot Strategy.
Detailed Description
Components to control the system/program boot process.
Class Documentation
embvm::BootSequencer
class embvm::BootSequencer
template<void TBootStrategy>
class embvm::BootSequencer< TBootStrategy >
Boot sequencer with customizable boot strategy.
The boot sequencer is a static class which handles booting logic supplied by a strategy function. You do not need to declare an instance. Instead, define a PlatformBootSequencer in your platform's platform.hpp file:
using PlatformBootSequencer = embvm::BootSequencer<embvm::DefaultBootStrategy<VirtualPlatform>>;
The framework will take care of the rest.
Template Parameters
TBootStrategy The function which describes the platform's boot sequence. See DefaultBootStrategy() for an example.
Public Member Functions
BootSequencer ()=delete
Deleted Default Constructor.
~BootSequencer ()=delete
Deleted Default Destructor.
BootSequencer (const BootSequencer &)=delete
Deleted copy constructor.
const BootSequencer & operator= (const BootSequencer &)=delete
Deleted copy assignment operator.
BootSequencer (BootSequencer &&)=delete
Deleted move constructor.
BootSequencer & operator= (BootSequencer &&)=delete
Deleted move assignment operator.
Static Public Member Functions
static void boot () noexcept
Execute the boot strategy to boot the system.
Related Functions
(Note that these are not member functions.)
void bootSystem ()
Each platform declares this to control the boot sequence.
template<class TPlatform >
void DefaultBootStrategy () noexcept
Default Framework Boot Strategy.
template<class TPlatform >
void BootOSWithMainThreadStrategy () noexcept
Continue Setup in Main Thread Framework Boot Strategy.
template<class TPlatform >
void OSXSimulatorBootStrategy () noexcept
OSX Simulator Boot Strategy.
Constructor & Destructor Documentation
BootSequencer() [1/3]
template<void TBootStrategy> embvm::BootSequencer< TBootStrategy >::BootSequencer () delete
Deleted Default Constructor.
~BootSequencer()
template<void TBootStrategy> embvm::BootSequencer< TBootStrategy >::~BootSequencer () delete
Deleted Default Destructor.
BootSequencer() [2/3]
template<void TBootStrategy> embvm::BootSequencer< TBootStrategy >::BootSequencer (const BootSequencer< TBootStrategy > &) delete
Deleted copy constructor.
BootSequencer() [3/3]
template<void TBootStrategy> embvm::BootSequencer< TBootStrategy >::BootSequencer (BootSequencer< TBootStrategy > &&) delete
Deleted move constructor.
Member Function Documentation
boot()
template<void TBootStrategy> static void embvm::BootSequencer< TBootStrategy >::boot () inline static noexcept
Execute the boot strategy to boot the system.
Referenced by bootSystem().
operator=() [1/2]
template<void TBootStrategy> const BootSequencer& embvm::BootSequencer< TBootStrategy >::operator= (const BootSequencer< TBootStrategy > &) delete
Deleted copy assignment operator.
operator=() [2/2]
template<void TBootStrategy> BootSequencer& embvm::BootSequencer< TBootStrategy >::operator= (BootSequencer< TBootStrategy > &&) delete
Deleted move assignment operator.
Function Documentation
BootOSWithMainThreadStrategy()
template<class TPlatform > void BootOSWithMainThreadStrategy () related
Continue Setup in Main Thread Framework Boot Strategy.
call earlyInitHook();
Setup the C/C++ runtime
Setup the OS, which will terminate the current call chain and start a new thread. This new thread will continue execution:
Setup the processor
Setup the hardware pltaform
Setup the platform
Jump to main
References CRTStartup().
bootSystem()
template<void TBootStrategy> void bootSystem () related
Each platform declares this to control the boot sequence.
Referenced by __attribute__(), and entry().
CRTStartup()
void CRTStartup ()
We declare this function here because we don't want to include crt.h and Add a dependency on our libc for the test code.
Referenced by embvm::BootSequencer< TBootStrategy >::BootOSWithMainThreadStrategy(), and embvm::BootSequencer< TBootStrategy >::DefaultBootStrategy().
DefaultBootStrategy()
template<class TPlatform > void DefaultBootStrategy () related
Default Framework Boot Strategy.
call earlyInitHook();
Setup the C/C++ runtime
Setup the OS
Setup the processor
Setup the hardware pltaform
Setup the platform
Jump to main
References CRTStartup(), and main().
entry()
void entry ()
Prototype for our function entry point; can also be an asm symbol.
References embvm::BootSequencer< TBootStrategy >::bootSystem().
Referenced by embvm::TimerManager< 0, std::mutex >::clearExpiredTimers(), and list_del().
main_thread_func()
template<class TPlatform > void main_thread_func () noexcept
References main().
Referenced by nRF52DK_FrameworkDemoPlatform::initOS_().
OSXSimulatorBootStrategy()
template<class TPlatform > void OSXSimulatorBootStrategy () related
OSX Simulator Boot Strategy.
Boots framework pieces, but lets OSX take care of CRT & OS initialization during the dynamic loading process.
call earlyInitHook();
Setup the processor
Setup the hardware pltaform
Setup the platform
Jump to main
References main().