Embedded Artistry Framework: src/stdlibs/libc/test/string/memcpy.c File Reference
memcpy.c File Reference
#include "string_tests.h"
#include <string.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Macros
#define N 80
Functions
static void * aligned (void *p)
static void test_align (unsigned dalign, unsigned salign, size_t len)
static void memcpy_aligned_test (void **state)
int memcpy_tests (void)
Variables
static char buf [512]
Macro Definition Documentation
N
#define N 80
Function Documentation
aligned()
static void* aligned (void * p) static
References p.
Referenced by test_align().
memcpy_aligned_test()
static void memcpy_aligned_test (void ** state) static
References k, and test_align().
Referenced by memcpy_tests().
memcpy_tests()
int memcpy_tests (void)
References memcpy_aligned_test(), memcpy_tests(), and NULL.
Referenced by memcpy_tests(), and string_tests().
test_align()
static void test_align (unsigned dalign, unsigned salign, size_t len) static
References aligned(), buf, dalign, memcpy(), N, and p.
Referenced by memcpy_aligned_test().
Variable Documentation
buf
char buf[512] static
Referenced by _ftoa(), _ntoa_format(), _ntoa_long(), _ntoa_long_long(), _out_rev(), asctime(), asctime_r(), os::freertos::EventFlag::EventFlag(), g_ddfmt(), g_dfmt(), g_ffmt(), g_Qfmt(), g_xfmt(), g_xLfmt(), strnstr_test(), strnstr_test_null(), and test_align().