Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_sin.c File Reference
s_sin.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double sin (double x)
Function Documentation
sin()
OLM_DLLEXPORT double sin (double x)
References __ieee754_rem_pio2(), __kernel_cos(), __kernel_sin(), GET_HIGH_WORD, n, and z.
Referenced by __ieee754_j0(), __ieee754_j1(), __ieee754_jn(), __ieee754_y0(), __ieee754_y1(), __ieee754_yn(), __ldexp_cexp(), ccos(), ccosh(), cexp(), cpow(), csin(), csinh(), ctan(), ctanh(), main(), neg_gam(), and sin_test().