Embedded Artistry Framework: NordicNVIC Class Reference
NordicNVIC Class Reference
Nordic NVIC Controller Interface Expansion.
#include <nordic_nvic.hpp>
Static Public Member Functions
template<typename TPeripheralType >
static uint32_t priority (const TPeripheralType *peripheral) noexcept
template<typename TPeripheralType >
static uint32_t priority (const TPeripheralType *peripheral, uint32_t p) noexcept
template<typename TPeripheralType >
static void enable (const TPeripheralType *peripheral) noexcept
template<typename TPeripheralType >
static void disable (const TPeripheralType *peripheral) noexcept
template<typename TPeripheralType >
static bool enabled (const TPeripheralType *peripheral) noexcept
template<typename TPeripheralType >
static bool pending (const TPeripheralType *peripheral) noexcept
template<typename TPeripheralType >
static void trigger (const TPeripheralType *peripheral) noexcept
template<typename TPeripheralType >
static void clear (const TPeripheralType *peripheral) noexcept
template<typename TPeripheralType >
static uintptr_t handler (const TPeripheralType *peripheral, uintptr_t func) noexcept
template<typename TPeripheralType >
static uintptr_t handler (const TPeripheralType *peripheral) noexcept
Private Member Functions
NordicNVIC ()=default
~NordicNVIC ()=default
Detailed Description
Nordic NVIC Controller Interface Expansion.
This class can be used instead of the ARM controller to provide support for enabling IRQs using a peripheral base pointer
This class is not meant to be instantiated directly. Instead, use the static methods.
Constructor & Destructor Documentation
NordicNVIC()
NordicNVIC::NordicNVIC () private default
~NordicNVIC()
NordicNVIC::~NordicNVIC () private default
Member Function Documentation
clear()
template<typename TPeripheralType > static void NordicNVIC::clear (const TPeripheralType * peripheral) inline static noexcept
References InterruptManagerBase< NVICControl, int32_t, uint32_t >::clear(), and get_peripheral_id().
disable()
template<typename TPeripheralType > static void NordicNVIC::disable (const TPeripheralType * peripheral) inline static noexcept
References InterruptManagerBase< NVICControl, int32_t, uint32_t >::disable(), and get_peripheral_id().
Referenced by nRFTWIMTranslator::disable_interrupts().
enable()
template<typename TPeripheralType > static void NordicNVIC::enable (const TPeripheralType * peripheral) inline static noexcept
References InterruptManagerBase< NVICControl, int32_t, uint32_t >::enable(), and get_peripheral_id().
Referenced by nRFTWIMTranslator::enable_interrupts().
enabled()
template<typename TPeripheralType > static bool NordicNVIC::enabled (const TPeripheralType * peripheral) inline static noexcept
References InterruptManagerBase< NVICControl, int32_t, uint32_t >::enabled(), and get_peripheral_id().
handler() [1/2]
template<typename TPeripheralType > static uintptr_t NordicNVIC::handler (const TPeripheralType * peripheral, uintptr_t func) inline static noexcept
References get_peripheral_id(), and InterruptManagerBase< NVICControl, int32_t, uint32_t >::handler().
handler() [2/2]
template<typename TPeripheralType > static uintptr_t NordicNVIC::handler (const TPeripheralType * peripheral) inline static noexcept
References get_peripheral_id(), and InterruptManagerBase< NVICControl, int32_t, uint32_t >::handler().
pending()
template<typename TPeripheralType > static bool NordicNVIC::pending (const TPeripheralType * peripheral) inline static noexcept
References get_peripheral_id(), and InterruptManagerBase< NVICControl, int32_t, uint32_t >::pending().
priority() [1/2]
template<typename TPeripheralType > static uint32_t NordicNVIC::priority (const TPeripheralType * peripheral) inline static noexcept
References get_peripheral_id(), and InterruptManagerBase< NVICControl, int32_t, uint32_t >::priority().
Referenced by nRFTWIMTranslator::set_interrupt_priority().
priority() [2/2]
template<typename TPeripheralType > static uint32_t NordicNVIC::priority (const TPeripheralType * peripheral, uint32_t p) inline static noexcept
References get_peripheral_id(), p, and InterruptManagerBase< NVICControl, int32_t, uint32_t >::priority().
trigger()
template<typename TPeripheralType > static void NordicNVIC::trigger (const TPeripheralType * peripheral) inline static noexcept
References get_peripheral_id(), and NVICControl::trigger().
The documentation for this class was generated from the following file:
src/processors/arm/nordic/drivers/nordic_nvic.hpp