Embedded Artistry libc: src/gdtoa/src/arithchk.c File Reference
arithchk.c File Reference
#include <stdio.h>
Classes
struct Akind
Typedefs
typedef struct Akind Akind
Functions
static Akind * Lcheck ()
static Akind * icheck ()
static Akind * ccheck ()
static int fzcheck ()
int main ()
Variables
static int dalign
static Akind IEEE_8087 = { "IEEE_8087", 1 }
static Akind IEEE_MC68k = { "IEEE_MC68k", 2 }
static Akind IBM = { "IBM", 3 }
static Akind VAX = { "VAX", 4 }
static Akind CRAY = { "CRAY", 5}
Class Documentation
Akind
struct Akind
Definition at line 30 of file arithchk.c.
Class Members
int kind
char * name
Typedef Documentation
Akind
typedef struct Akind Akind
Function Documentation
ccheck()
static Akind* ccheck () static
Definition at line 98 of file arithchk.c.
References CRAY.
Referenced by main().
 {
     union {
         double d;
         long L;
         } u;
     long Cray1;
     /* Cray1 = 4617762693716115456 -- without overflow on non-Crays */
     Cray1 = printf("") < 0 ? 0 : 4617762;
     if (printf("%ld", Cray1) >= 0)
         Cray1 = 1000000*Cray1 + 693716;
     if (printf("%ld", Cray1) >= 0)
         Cray1 = 1000000*Cray1 + 115456;
     u.d = 1e13;
     if (u.L == Cray1)
         return &CRAY;
     return 0;
     }
fzcheck()
static int fzcheck () static
Definition at line 119 of file arithchk.c.
Referenced by main().
 {
     double a, b;
     int i;
     a = 1.;
     b = .1;
     for(i = 155;; b *= b, i >>= 1) {
         if (i & 1) {
             a *= b;
             if (i == 1)
                 break;
             }
         }
     b = a * a;
     return b == 0.;
     }
icheck()
static Akind* icheck () static
Definition at line 71 of file arithchk.c.
References dalign, IBM, IEEE_8087, IEEE_MC68k, VAX, and Bigint::x.
Referenced by main().
 {
     union {
         double d;
         int L[2];
         } u;
     struct {
         double d;
         int L;
         } x[2];
     if (sizeof(x) > 2*(sizeof(double) + sizeof(int)))
         dalign = 1;
     u.L[0] = u.L[1] = 0;
     u.d = 1e13;
     if (u.L[0] == 1117925532 && u.L[1] == -448790528)
         return &IEEE_MC68k;
     if (u.L[1] == 1117925532 && u.L[0] == -448790528)
         return &IEEE_8087;
     if (u.L[0] == -2065213935 && u.L[1] == 10752)
         return &VAX;
     if (u.L[0] == 1267827943 && u.L[1] == 704643072)
         return &IBM;
     return 0;
     }
Lcheck()
static Akind* Lcheck () static
Definition at line 44 of file arithchk.c.
References dalign, IBM, IEEE_8087, IEEE_MC68k, VAX, and Bigint::x.
Referenced by main().
 {
     union {
         double d;
         long L[2];
         } u;
     struct {
         double d;
         long L;
         } x[2];
     if (sizeof(x) > 2*(sizeof(double) + sizeof(long)))
         dalign = 1;
     u.L[0] = u.L[1] = 0;
     u.d = 1e13;
     if (u.L[0] == 1117925532 && u.L[1] == -448790528)
         return &IEEE_MC68k;
     if (u.L[1] == 1117925532 && u.L[0] == -448790528)
         return &IEEE_8087;
     if (u.L[0] == -2065213935 && u.L[1] == 10752)
         return &VAX;
     if (u.L[0] == 1267827943 && u.L[1] == 704643072)
         return &IBM;
     return 0;
     }
main()
int main (void)
Definition at line 138 of file arithchk.c.
References ccheck(), dalign, fzcheck(), icheck(), Akind::kind, Lcheck(), and Akind::name.
Referenced by strtok().
 {
     Akind *a = 0;
     int Ldef = 0;
     FILE *f;
 #ifdef WRITE_ARITH_H    /* for Symantec's buggy "make" */
     f = fopen("arith.h", "w");
     if (!f) {
         printf("Cannot open arith.h\n");
         return 1;
         }
 #else
     f = stdout;
 #endif
     if (sizeof(double) == 2*sizeof(long))
         a = Lcheck();
     else if (sizeof(double) == 2*sizeof(int)) {
         Ldef = 1;
         a = icheck();
         }
     else if (sizeof(double) == sizeof(long))
         a = ccheck();
     if (a) {
         fprintf(f, "#define %s\n#define Arith_Kind_ASL %d\n",
             a->name, a->kind);
         if (Ldef)
             fprintf(f, "#define Long int\n#define Intcast (int)(long)\n");
         if (dalign)
             fprintf(f, "#define Double_Align\n");
         if (sizeof(char*) == 8)
             fprintf(f, "#define X64_bit_pointers\n");
 #ifndef NO_LONG_LONG
         if (sizeof(long long) < 8)
 #endif
             fprintf(f, "#define NO_LONG_LONG\n");
         if (a->kind <= 2 && fzcheck())
             fprintf(f, "#define Sudden_Underflow\n");
         return 0;
         }
     fprintf(f, "/* Unknown arithmetic */\n");
     return 1;
     }
Variable Documentation
CRAY
Akind CRAY = { "CRAY", 5} static
Definition at line 41 of file arithchk.c.
Referenced by ccheck().
dalign
int dalign static
Definition at line 29 of file arithchk.c.
Referenced by icheck(), Lcheck(), and main().
IBM
Akind IBM = { "IBM", 3 } static
Definition at line 39 of file arithchk.c.
Referenced by icheck(), Lcheck(), and strtod().
IEEE_8087
Akind IEEE_8087 = { "IEEE_8087", 1 } static
Definition at line 37 of file arithchk.c.
Referenced by icheck(), and Lcheck().
IEEE_MC68k
Akind IEEE_MC68k = { "IEEE_MC68k", 2 } static
Definition at line 38 of file arithchk.c.
Referenced by icheck(), and Lcheck().
VAX
Akind VAX = { "VAX", 4 } static
Definition at line 40 of file arithchk.c.
Referenced by icheck(), and Lcheck().