Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/k_sinf.c File Reference
k_sinf.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float __kernel_sindf (double x)
Variables
static const double S1 = -0x15555554cbac77.0p-55
static const double S2 = 0x111110896efbb2.0p-59
static const double S3 = -0x1a00f9e2cae774.0p-65
static const double S4 = 0x16cd878c3b46a7.0p-71
Function Documentation
__kernel_sindf()
OLM_DLLEXPORT float __kernel_sindf (double x)
References r, s, S1, S2, S3, S4, w, and z.
Referenced by cosf(), sin_pif(), and sinf().
Variable Documentation
S1
const double S1 = -0x15555554cbac77.0p-55 static
Referenced by __kernel_sindf().
S2
const double S2 = 0x111110896efbb2.0p-59 static
Referenced by __kernel_sindf().
S3
const double S3 = -0x1a00f9e2cae774.0p-65 static
Referenced by __kernel_sindf().
S4
const double S4 = 0x16cd878c3b46a7.0p-71 static
Referenced by __kernel_sindf().