Embedded Artistry Framework: src/stdlibs/libc/src/wchar/towccase.c File Reference
towccase.c File Reference
#include "_towcase.h"
Macros
#define CASEMAP(u1, u2, l)
#define CASELACE(u1, u2) CASEMAP((u1), (u2), (u1) + 1)
Functions
wchar_t __towcase (wchar_t wc, int lower)
Variables
struct {
unsigned short upper
signed char lower
unsigned char len
} casemaps []
static const unsigned short pairs [][2]
Macro Definition Documentation
CASELACE
#define CASELACE (u1, u2) CASEMAP((u1), (u2), (u1) + 1)
CASEMAP
#define CASEMAP (u1, u2, l)
Value:
{                                     \
        (u1), (l) - (u1), (u2) - (u1) + 1 \
    }
Function Documentation
__towcase()
wchar_t __towcase (wchar_t wc, int lower)
References casemaps, iswalpha(), and pairs.
Referenced by towlower(), and towupper().
Variable Documentation
casemaps
const { ... } casemaps[]
Referenced by __towcase().
pairs
const unsigned short pairs[][2] static
Referenced by __towcase().