Embedded Artistry libc: src/wchar/iswctype.c File Reference
iswctype.c File Reference
#include <string.h>
#include <wctype.h>
Functions
int iswctype (wint_t wc, wctype_t type)
Function Documentation
iswctype()
int iswctype (wint_t wc, wctype_t type)
Definition at line 4 of file iswctype.c.
 {
     switch(type)
     {
         case WCTYPE_ALNUM:
             return iswalnum(wc);
         case WCTYPE_ALPHA:
             return iswalpha(wc);
         case WCTYPE_BLANK:
             return iswblank(wc);
         case WCTYPE_CNTRL:
             return iswcntrl(wc);
         case WCTYPE_DIGIT:
             return iswdigit(wc);
         case WCTYPE_GRAPH:
             return iswgraph(wc);
         case WCTYPE_LOWER:
             return iswlower(wc);
         case WCTYPE_PRINT:
             return iswprint(wc);
         case WCTYPE_PUNCT:
             return iswpunct(wc);
         case WCTYPE_SPACE:
             return iswspace(wc);
         case WCTYPE_UPPER:
             return iswupper(wc);
         case WCTYPE_XDIGIT:
             return iswxdigit(wc);
     }
     return 0;
 }
References iswalnum(), iswalpha(), iswblank(), iswcntrl(), iswdigit(), iswgraph(), iswlower(), iswprint(), iswpunct(), iswspace(), iswupper(), iswxdigit(), WCTYPE_ALNUM, WCTYPE_ALPHA, WCTYPE_BLANK, WCTYPE_CNTRL, WCTYPE_DIGIT, WCTYPE_GRAPH, WCTYPE_LOWER, WCTYPE_PRINT, WCTYPE_PUNCT, WCTYPE_SPACE, WCTYPE_UPPER, and WCTYPE_XDIGIT.