Embedded Artistry Framework: src/stdlibs/libc/src/gdtoa/src/gdtoa.c File Reference
gdtoa.c File Reference
#include "gdtoaimp.h"
#include <float.h>
#include <math.h>
Functions
static Bigint * bitstob (ULong *bits, int nbits, int *bbits)
char * gdtoa (FPI *fpi, int be, ULong *bits, int *kindp, int mode, int ndigits, int *decpt, char **rve)
Function Documentation
bitstob()
static Bigint* bitstob (ULong * bits, int nbits, int * bbits) static
References ALL_ON, b, Balloc(), hi0bits, k, kshift, ULbits, and x0.
Referenced by gdtoa().
gdtoa()
char* gdtoa (FPI * fpi, int be, ULong * bits, int * kindp, int mode, int ndigits, int * decpt, char ** rve)
References b, b1, b2, b2d(), Balloc(), Bcopy, Bfree(), bigtens, bitstob(), Bletch, cmp(), DBL_EPSILON, diff(), dtoa_result, dval, FPI::emin, eps, Exp_11, Exp_msk1, Exp_shift, fabs(), Frac_mask1, freedtoa(), hi0bits, i2b(), Int_max, k, Long, lshift(), mult(), multadd(), FPI::nbits, nrv_alloc(), NULL, P, pow5mult(), Quick_max, quorem(), ROUND_BIASED, FPI::rounding, rshift(), rv_alloc(), s, S, s0, s2, s5, Bigint::sign, STRTOG_Denormal, STRTOG_Inexact, STRTOG_Inexhi, STRTOG_Inexlo, STRTOG_Infinite, STRTOG_NaN, STRTOG_Neg, STRTOG_Normal, STRTOG_Retmask, STRTOG_Zero, Ten_pmax, tens, trailz(), and word0.
Referenced by g_ddfmt(), g_dfmt(), g_ffmt(), g_Qfmt(), g_xfmt(), and g_xLfmt().