Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_tanf.c File Reference
s_tanf.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float tanf (float x)
Variables
static const double t1pio2 = 1*M_PI_2
static const double t2pio2 = 2*M_PI_2
static const double t3pio2 = 3*M_PI_2
static const double t4pio2 = 4*M_PI_2
Function Documentation
tanf()
OLM_DLLEXPORT float tanf (float x)
References __ieee754_rem_pio2f(), __kernel_tandf(), GET_FLOAT_WORD, n, t1pio2, t2pio2, t3pio2, and t4pio2.
Referenced by ctanhf().
Variable Documentation
t1pio2
const double t1pio2 = 1*M_PI_2 static
Referenced by tanf().
t2pio2
const double t2pio2 = 2*M_PI_2 static
Referenced by tanf().
t3pio2
const double t3pio2 = 3*M_PI_2 static
Referenced by tanf().
t4pio2
const double t4pio2 = 4*M_PI_2 static
Referenced by tanf().