Embedded Artistry Framework: src/processors/arm/nordic/drivers/helpers/twim_helper_.hpp File Reference
twim_helper_.hpp File Reference
#include <nordic_utils.hpp>
#include <processor_includes.hpp>
#include <volatile/volatile.hpp>
Enumerations
enum twi_task_t {
TWIM_TASK_STARTRX = offsetof(NRF_TWIM_Type, TASKS_STARTRX), TWIM_TASK_STARTTX = offsetof(NRF_TWIM_Type, TASKS_STARTTX), TWIM_TASK_STOP = offsetof(NRF_TWIM_Type, TASKS_STOP), TWIM_TASK_SUSPEND = offsetof(NRF_TWIM_Type, TASKS_SUSPEND),
TWIM_TASK_RESUME = offsetof(NRF_TWIM_Type, TASKS_RESUME)
}
enum twi_event_t {
TWIM_EVENT_STOPPED = offsetof(NRF_TWIM_Type, EVENTS_STOPPED), TWIM_EVENT_ERROR = offsetof(NRF_TWIM_Type, EVENTS_ERROR), TWIM_EVENT_SUSPENDED, TWIM_EVENT_RXSTARTED = offsetof(NRF_TWIM_Type, EVENTS_RXSTARTED),
TWIM_EVENT_TXSTARTED = offsetof(NRF_TWIM_Type, EVENTS_TXSTARTED), TWIM_EVENT_LASTRX = offsetof(NRF_TWIM_Type, EVENTS_LASTRX), TWIM_EVENT_LASTTX = offsetof(NRF_TWIM_Type, EVENTS_LASTTX)
}
Functions
static void interrupts_disable_ (NRF_TWIM_Type *twi) noexcept
static void interrupts_enable_ (NRF_TWIM_Type *twi, uint32_t mask) noexcept
static void disable_shortcuts_ (NRF_TWIM_Type *twi) noexcept
static void set_shortcuts_ (NRF_TWIM_Type *twi, uint32_t mask) noexcept
static void clear_event_ (NRF_TWIM_Type *twi, twi_event_t event) noexcept
static bool check_event_ (NRF_TWIM_Type *twi, twi_event_t event) noexcept
static void task_trigger_ (NRF_TWIM_Type *twi, twi_task_t task) noexcept
static void set_tx_buffer_ (NRF_TWIM_Type *twi, const uint8_t *tx_data, size_t length) noexcept
static size_t get_txd_amount_ (NRF_TWIM_Type *twi) noexcept
static void set_rx_buffer_ (NRF_TWIM_Type *twi, uint8_t *rx_data, size_t length) noexcept
static size_t get_rxd_amount_ (NRF_TWIM_Type *twi) noexcept
static void tx_list_enable_ (NRF_TWIM_Type *twi) noexcept
static void tx_list_disable_ (NRF_TWIM_Type *twi) noexcept
static void rx_list_enable_ (NRF_TWIM_Type *twi) noexcept
static void rx_list_disable_ (NRF_TWIM_Type *twi) noexcept
static void handle_error_event_ (NRF_TWIM_Type *twi) noexcept
static void block_until_complete (NRF_TWIM_Type *twi, twi_event_t exit_event) noexcept
static void clear_events_prior_to_kickoff (NRF_TWIM_Type *twi) noexcept
static twi_event_t kickoff_rx (NRF_TWIM_Type *twi) noexcept
static twi_event_t kickoff_tx (NRF_TWIM_Type *twi, bool no_stop) noexcept
static twi_event_t kickoff_txrx (NRF_TWIM_Type *twi) noexcept
static uint32_t get_errorsrc_ (NRF_TWIM_Type *twi) noexcept
Variables
constexpr uint32_t ALL_INTS_MASK
All TWI interrupts.
constexpr uint32_t ALL_SHORTCUTS_MASK
All TWI shortcuts.
Enumeration Type Documentation
twi_event_t
enum twi_event_t
Enumerator
TWIM_EVENT_STOPPED
TWI stopped.
TWIM_EVENT_ERROR
TWI error.
TWIM_EVENT_SUSPENDED
TWI entered the suspended state. //0x148 - they hardcoded??
TWIM_EVENT_RXSTARTED
TWIM_EVENT_TXSTARTED
TWIM_EVENT_LASTRX
TWIM_EVENT_LASTTX
twi_task_t
enum twi_task_t
Enumerator
TWIM_TASK_STARTRX
Start TWI receive sequence.
TWIM_TASK_STARTTX
Start TWI transmit sequence.
TWIM_TASK_STOP
Stop TWI transaction.
TWIM_TASK_SUSPEND
Suspend TWI transaction.
TWIM_TASK_RESUME
Resume TWI transaction.
Function Documentation
block_until_complete()
static void block_until_complete (NRF_TWIM_Type * twi, twi_event_t exit_event) static noexcept
References check_event_(), embvm::logger::error, handle_error_event_(), TWIM_EVENT_ERROR, and TWIM_EVENT_STOPPED.
Referenced by nRFTWIMTranslator::rx_transfer_blocking(), nRFTWIMTranslator::tx_transfer_blocking(), and nRFTWIMTranslator::txrx_transfer_blocking().
check_event_()
static bool check_event_ (NRF_TWIM_Type * twi, twi_event_t event) inline static noexcept
References embutil::volatile_load().
Referenced by block_until_complete(), handle_error_event_(), nRFTWITranslator::rx_transfer(), twim_irq_handler_(), and nRFTWITranslator::tx_transfer().
clear_event_()
static void clear_event_ (NRF_TWIM_Type * twi, twi_event_t event) inline static noexcept
References UINT32_C, embutil::volatile_load(), and embutil::volatile_store().
Referenced by clear_events_prior_to_kickoff(), handle_error_event_(), kickoff_tx(), nRFTWITranslator::rx_transfer(), twim_irq_handler_(), and nRFTWITranslator::tx_transfer().
clear_events_prior_to_kickoff()
static void clear_events_prior_to_kickoff (NRF_TWIM_Type * twi) inline static noexcept
References clear_event_(), TWIM_EVENT_ERROR, and TWIM_EVENT_STOPPED.
Referenced by kickoff_rx(), kickoff_tx(), and kickoff_txrx().
disable_shortcuts_()
static void disable_shortcuts_ (NRF_TWIM_Type * twi) inline static noexcept
References ALL_SHORTCUTS_MASK, embutil::volatile_load(), and embutil::volatile_store().
Referenced by nRFTWITranslator::disable(), nRFTWIMTranslator::disable(), and twim_irq_handler_().
get_errorsrc_()
static uint32_t get_errorsrc_ (NRF_TWIM_Type * twi) inline static noexcept
References embvm::logger::error, embutil::volatile_load(), and embutil::volatile_store().
Referenced by get_converted_error().
get_rxd_amount_()
static size_t get_rxd_amount_ (NRF_TWIM_Type * twi) inline static noexcept
References embutil::volatile_load().
get_txd_amount_()
static size_t get_txd_amount_ (NRF_TWIM_Type * twi) inline static noexcept
References embutil::volatile_load().
handle_error_event_()
static void handle_error_event_ (NRF_TWIM_Type * twi) static noexcept
References check_event_(), clear_event_(), task_trigger_(), TWIM_EVENT_ERROR, TWIM_EVENT_STOPPED, TWIM_TASK_RESUME, and TWIM_TASK_STOP.
Referenced by block_until_complete(), and twim_irq_handler_().
interrupts_disable_()
static void interrupts_disable_ (NRF_TWIM_Type * twi) inline static noexcept
References ALL_INTS_MASK, and embutil::volatile_store().
Referenced by nRFTWIMTranslator::disable(), nRFTWIMTranslator::rx_transfer(), twim_irq_handler_(), nRFTWIMTranslator::tx_transfer(), and nRFTWIMTranslator::txrx_transfer().
interrupts_enable_()
static void interrupts_enable_ (NRF_TWIM_Type * twi, uint32_t mask) inline static noexcept
References embutil::volatile_store().
Referenced by nRFTWIMTranslator::rx_transfer(), twim_irq_handler_(), nRFTWIMTranslator::tx_transfer(), and nRFTWIMTranslator::txrx_transfer().
kickoff_rx()
static twi_event_t kickoff_rx (NRF_TWIM_Type * twi) static noexcept
References clear_events_prior_to_kickoff(), set_shortcuts_(), task_trigger_(), TWIM_EVENT_STOPPED, TWIM_TASK_RESUME, and TWIM_TASK_STARTRX.
Referenced by nRFTWIMTranslator::rx_transfer(), and nRFTWIMTranslator::rx_transfer_blocking().
kickoff_tx()
static twi_event_t kickoff_tx (NRF_TWIM_Type * twi, bool no_stop) static noexcept
References clear_event_(), clear_events_prior_to_kickoff(), set_shortcuts_(), task_trigger_(), TWIM_EVENT_STOPPED, TWIM_EVENT_SUSPENDED, TWIM_TASK_RESUME, and TWIM_TASK_STARTTX.
Referenced by nRFTWIMTranslator::tx_transfer(), and nRFTWIMTranslator::tx_transfer_blocking().
kickoff_txrx()
static twi_event_t kickoff_txrx (NRF_TWIM_Type * twi) static noexcept
References clear_events_prior_to_kickoff(), set_shortcuts_(), task_trigger_(), TWIM_EVENT_STOPPED, TWIM_TASK_RESUME, and TWIM_TASK_STARTTX.
Referenced by nRFTWIMTranslator::txrx_transfer(), and nRFTWIMTranslator::txrx_transfer_blocking().
rx_list_disable_()
static void rx_list_disable_ (NRF_TWIM_Type * twi) inline static noexcept
References UINT32_C, and embutil::volatile_store().
rx_list_enable_()
static void rx_list_enable_ (NRF_TWIM_Type * twi) inline static noexcept
References UINT32_C, and embutil::volatile_store().
set_rx_buffer_()
static void set_rx_buffer_ (NRF_TWIM_Type * twi, uint8_t * rx_data, size_t length) inline static noexcept
References assert, is_in_nordic_ram(), length, and embutil::volatile_store().
Referenced by nRFTWIMTranslator::rx_transfer(), nRFTWIMTranslator::rx_transfer_blocking(), nRFTWIMTranslator::txrx_transfer(), and nRFTWIMTranslator::txrx_transfer_blocking().
set_shortcuts_()
static void set_shortcuts_ (NRF_TWIM_Type * twi, uint32_t mask) inline static noexcept
References embutil::volatile_store().
Referenced by kickoff_rx(), kickoff_tx(), kickoff_txrx(), nRFTWITranslator::rx_transfer(), and nRFTWITranslator::tx_transfer().
set_tx_buffer_()
static void set_tx_buffer_ (NRF_TWIM_Type * twi, const uint8_t * tx_data, size_t length) inline static noexcept
References assert, is_in_nordic_ram(), length, and embutil::volatile_store().
Referenced by nRFTWIMTranslator::tx_transfer(), nRFTWIMTranslator::tx_transfer_blocking(), nRFTWIMTranslator::txrx_transfer(), and nRFTWIMTranslator::txrx_transfer_blocking().
task_trigger_()
static void task_trigger_ (NRF_TWIM_Type * twi, twi_task_t task) inline static noexcept
References UINT32_C, and embutil::volatile_store().
Referenced by handle_error_event_(), kickoff_rx(), kickoff_tx(), kickoff_txrx(), nRFTWITranslator::rx_transfer(), nRFTWITranslator::stop_condition(), nRFTWIMTranslator::stop_condition(), and nRFTWITranslator::tx_transfer().
tx_list_disable_()
static void tx_list_disable_ (NRF_TWIM_Type * twi) inline static noexcept
References UINT32_C, and embutil::volatile_store().
tx_list_enable_()
static void tx_list_enable_ (NRF_TWIM_Type * twi) inline static noexcept
References UINT32_C, and embutil::volatile_store().
Variable Documentation
ALL_INTS_MASK
constexpr uint32_t ALL_INTS_MASK
Initial value:
= static_cast<uint32_t>(
    TWIM_INTENSET_STOPPED_Msk | TWIM_INTENSET_ERROR_Msk | TWIM_INTENSET_SUSPENDED_Msk |
    TWIM_INTENSET_RXSTARTED_Msk | TWIM_INTENSET_TXSTARTED_Msk | TWIM_INTENSET_LASTRX_Msk |
    TWIM_INTENSET_LASTTX_Msk)
All TWI interrupts.
Referenced by interrupts_disable_().
ALL_SHORTCUTS_MASK
constexpr uint32_t ALL_SHORTCUTS_MASK
Initial value:
= static_cast<uint32_t>(
    TWIM_SHORTS_LASTTX_STARTRX_Msk | TWIM_SHORTS_LASTTX_SUSPEND_Msk | TWIM_SHORTS_LASTTX_STOP_Msk |
    TWIM_SHORTS_LASTRX_STARTTX_Msk | TWIM_SHORTS_LASTRX_STOP_Msk)
All TWI shortcuts.
Referenced by disable_shortcuts_().