Embedded Artistry Framework: os::freertos::details::MessageQueueMediator Class Reference
os::freertos::details::MessageQueueMediator Class Reference
#include <freertos_msg_queue.hpp>
Static Public Member Functions
static embvm::msgqueue::handle_t create (size_t length, size_t item_size)
static void destroy (embvm::msgqueue::handle_t handle)
static bool full (embvm::msgqueue::handle_t handle, size_t max_length)
static bool empty (embvm::msgqueue::handle_t handle)
static void reset (embvm::msgqueue::handle_t handle)
static size_t size (embvm::msgqueue::handle_t handle)
static bool pop (embvm::msgqueue::handle_t handle, void *buffer, embvm::os_timeout_t timeout)
static bool push (embvm::msgqueue::handle_t handle, const void *buffer, embvm::os_timeout_t timeout)
Member Function Documentation
create()
embvm::msgqueue::handle_t MessageQueueMediator::create (size_t length, size_t item_size) static noexcept
References length.
Referenced by os::freertos::MessageQueue< TType >::MessageQueue().
destroy()
static void os::freertos::details::MessageQueueMediator::destroy (embvm::msgqueue::handle_t handle) static
Referenced by os::freertos::MessageQueue< TType >::~MessageQueue().
empty()
bool MessageQueueMediator::empty (embvm::msgqueue::handle_t handle) static noexcept
Referenced by os::freertos::MessageQueue< TType >::empty().
full()
bool MessageQueueMediator::full (embvm::msgqueue::handle_t handle, size_t max_length) static noexcept
Referenced by os::freertos::MessageQueue< TType >::full().
pop()
bool MessageQueueMediator::pop (embvm::msgqueue::handle_t handle, void * buffer, embvm::os_timeout_t timeout) static noexcept
References convert_timeout().
Referenced by os::freertos::MessageQueue< TType >::pop().
push()
bool MessageQueueMediator::push (embvm::msgqueue::handle_t handle, const void * buffer, embvm::os_timeout_t timeout) static noexcept
References convert_timeout().
Referenced by os::freertos::MessageQueue< TType >::push().
reset()
void MessageQueueMediator::reset (embvm::msgqueue::handle_t handle) static noexcept
Referenced by os::freertos::MessageQueue< TType >::reset().
size()
size_t MessageQueueMediator::size (embvm::msgqueue::handle_t handle) static noexcept
Referenced by os::freertos::MessageQueue< TType >::size().
The documentation for this class was generated from the following files:
src/os/freertos/freertos_msg_queue.hpp
src/os/freertos/freertos_msg_queue.cpp