Embedded Artistry Framework: src/stdlibs/libc/test/stdlib/strtof.c File Reference
strtof.c File Reference
#include "stdlib_tests.h"
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Macros
#define length(x) (sizeof(x) / sizeof *(x))
Functions
static void strtof_test (void **state)
int strtof_tests (void)
Variables
struct {
char * s
float f
} t []
Macro Definition Documentation
length
#define length (x) (sizeof(x) / sizeof *(x))
Function Documentation
strtof_test()
static void strtof_test (void ** state) static
References fabsf(), FLT_EPSILON, length, p, s, strtof(), and t.
Referenced by strtof_tests().
strtof_tests()
int strtof_tests (void)
References NULL, and strtof_test().
Referenced by stdlib_tests().
Variable Documentation
t
struct { ... } t[]
Initial value:
= {
    {".7006492321624085354618647916449580656401309709382578858785341419448955413429303e-45", 0},
    {".7006492321624085354618647916449580656401309709382578858785341419448955413429304e-45",
     0x1p-149},
    {".2101947696487225606385594374934874196920392912814773657635602425834686624028790e-44",
     0x1p-149},
    {".2101947696487225606385594374934874196920392912814773657635602425834686624028791e-44",
     0x1p-148},
    {".1175494420887210724209590083408724842314472120785184615334540294131831453944281e-37",
     0x1p-126},
    {".1175494420887210724209590083408724842314472120785184615334540294131831453944282e-37",
     0x1.000002p-126},
    {"340282356779733661637539395458142568447.9999999999999999999", 0x1.fffffep127},
}
Referenced by strtof_test().