Embedded Artistry Framework: src/drivers/aardvark/vendor/examples/aagpio.c File Reference
aagpio.c File Reference
#include "aardvark.h"
#include <stdio.h>
#include <stdlib.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References aa_close(), AA_CONFIG_GPIO_ONLY, AA_CONFIG_SPI_I2C, aa_configure(), aa_gpio_change(), aa_gpio_direction(), aa_gpio_get(), AA_GPIO_MISO, AA_GPIO_MOSI, aa_gpio_pullup(), AA_GPIO_SCK, AA_GPIO_SCL, aa_gpio_set(), AA_GPIO_SS, aa_i2c_pullup(), AA_I2C_PULLUP_BOTH, AA_I2C_PULLUP_NONE, aa_open_ext(), atoi(), AardvarkExt::features, and printf.