Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_crealf.c File Reference
s_crealf.c File Reference
#include <openlibm_complex.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float crealf (float complex z)
Function Documentation
crealf()
OLM_DLLEXPORT float crealf (float complex z)
References z.
Referenced by __ldexp_cexpf(), _ctansf(), cabsf(), cacosf(), cargf(), casinf(), catanf(), ccosf(), ccoshf(), cexpf(), clogf(), conjf(), cpowf(), cprojf(), csinf(), csinhf(), csqrtf(), ctanf(), and ctanhf().