Embedded Artistry Framework: src/drivers/aardvark/vendor/examples/aai2c_eeprom.c File Reference
aai2c_eeprom.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "aardvark.h"
Macros
#define PAGE_SIZE 8
#define BUS_TIMEOUT 150
Functions
static void _writeMemory (Aardvark handle, u08 device, u08 addr, u16 length, int zero)
static void _readMemory (Aardvark handle, u08 device, u08 addr, u16 length)
int main (int argc, char *argv[])
Macro Definition Documentation
BUS_TIMEOUT
#define BUS_TIMEOUT 150
PAGE_SIZE
#define PAGE_SIZE 8
Function Documentation
_readMemory()
static void _readMemory (Aardvark handle, u08 device, u08 addr, u16 length) static
References AA_I2C_NO_FLAGS, AA_I2C_NO_STOP, aa_i2c_read(), aa_i2c_write(), aa_status_string(), data_in, free(), length, malloc(), and printf.
Referenced by main().
_writeMemory()
static void _writeMemory (Aardvark handle, u08 device, u08 addr, u16 length, int zero) static
References AA_I2C_NO_FLAGS, aa_i2c_write(), aa_sleep_ms(), length, n, PAGE_SIZE, and zero.
Referenced by main().
main()
int main (int argc, char * argv[])
References _readMemory(), _writeMemory(), aa_close(), AA_CONFIG_SPI_I2C, aa_configure(), aa_i2c_bitrate(), aa_i2c_bus_timeout(), aa_i2c_pullup(), AA_I2C_PULLUP_BOTH, aa_open(), aa_target_power(), AA_TARGET_POWER_BOTH, atoi(), BUS_TIMEOUT, length, printf, strcmp(), and strtol().