Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_sqrtl.c File Reference
e_sqrtl.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_fenv.h>
#include <openlibm_math.h>
#include "fpmath.h"
#include "math_private.h"
Functions
static long double inc (long double x)
static long double dec (long double x)
OLM_DLLEXPORT long double sqrtl (long double x)
Function Documentation
dec()
static long double dec (long double x) inline static
References LDBL_NBIT, and u.
Referenced by sqrtl().
inc()
static long double inc (long double x) inline static
References LDBL_NBIT, and u.
Referenced by htinit(), and sqrtl().
sqrtl()
OLM_DLLEXPORT long double sqrtl (long double x)
References dec(), FE_INEXACT, FE_TONEAREST, FE_TOWARDZERO, FE_UPWARD, feclearexcept(), fegetround(), feholdexcept(), fesetenv(), fesetround(), fetestexcept(), feupdateenv(), inc(), k, LDBL_MAX_EXP, r, sqrt(), and u.
Referenced by acoshl(), acosl(), asinhl(), asinl(), csqrtl(), hypotl(), and powl().