Embedded Artistry Framework: nRF52840 Class Reference
nRF52840 Class Reference
#include <nrf52840.hpp>
Public Member Functions
nRF52840 () noexcept
Default constructor.
~nRF52840 ()
Default destructor.
void init_ () noexcept
void reset_ () noexcept
void spin (unsigned int usecs) noexcept
bool highVoltageMode () noexcept
bool highVoltageMode (bool en) noexcept
Function for configuring UICR_REGOUT0 register to set GPIO output voltage to 3.0V.
constexpr const std::string_view & name () const noexcept
Returns the Virtual HW Platform's name.
constexpr const char * name_cstr () const noexcept
Returns the platform name as a cstring for C API compatibility.
void init () noexcept
Initialize the processor.
void reset () noexcept
Reset the chip.
Static Public Member Functions
static void earlyInitHook_ () noexcept
static void earlyInitHook () noexcept
Perform any special initialization steps.
Private Types
using ProcessorBase = embvm::VirtualProcessorBase< nRF52840 >
Member Typedef Documentation
ProcessorBase
using nRF52840::ProcessorBase = embvm::VirtualProcessorBase<nRF52840> private
Constructor & Destructor Documentation
nRF52840()
nRF52840::nRF52840 () inline noexcept
Default constructor.
~nRF52840()
nRF52840::~nRF52840 ()
Default destructor.
Member Function Documentation
earlyInitHook()
static void embvm::VirtualProcessorBase< nRF52840 >::earlyInitHook () inline static noexcept inherited
Perform any special initialization steps.
The earlyInitHook_() function must be implemented by the derived class as a static function.
These functions run before the C Run-time setup functions are called, and normal functionality (e.g. OS concepts) are not available.
Early initialization steps represent any super early code that needs to execute. For example, DRAM might need to be initialized before the boot process can relocate memory to its proper location in memory.
These functions are declared static to prevent you from easily using drivers within their confines
earlyInitHook_()
static void nRF52840::earlyInitHook_ () inline static noexcept
highVoltageMode() [1/2]
bool nRF52840::highVoltageMode () noexcept
Referenced by NRF52DongleHWPlatform::init_().
highVoltageMode() [2/2]
bool nRF52840::highVoltageMode (bool en) noexcept
Function for configuring UICR_REGOUT0 register to set GPIO output voltage to 3.0V.
This function will reset the microcontroller if the requested setting was applied. The UICR registers require this.
References checkVOUT(), and setVOUT().
init()
void embvm::VirtualProcessorBase< nRF52840 >::init () inline noexcept inherited
Initialize the processor.
The initProcessor_() function must be implemented by the derived class.
Perform any steps necessary for initializing the processor & processor peripheral devices for use.
Note that this is only intended to be processor initialization. Platform initialization nis handled by the init() function.
This function will likely invoke the VirtualProcessor::init() function, but the order and actual initialization process is left to the derived class.
init_()
void nRF52840::init_ () noexcept
name()
constexpr const std::string_view& embvm::VirtualProcessorBase< nRF52840 >::name () const inline noexcept inherited
Returns the Virtual HW Platform's name.
name_cstr()
constexpr const char* embvm::VirtualProcessorBase< nRF52840 >::name_cstr () const inline noexcept inherited
Returns the platform name as a cstring for C API compatibility.
reset()
void embvm::VirtualProcessorBase< nRF52840 >::reset () inline noexcept inherited
Reset the chip.
The reset_() function must be implemnted by the derived class.
A soft reset is intended to reset the program to the beginning without performing a full power cycle.
reset_()
void nRF52840::reset_ () noexcept
References ARMCommonArch::systemReset().
spin()
void nRF52840::spin (unsigned int usecs) noexcept
References CPU_FREQ_MHZ.
Referenced by NRF52DKHWPlatform::startBlink(), and NRF52DongleHWPlatform::startBlink().
The documentation for this class was generated from the following files:
src/processors/arm/nordic/nrf52840/nrf52840.hpp
src/processors/arm/nordic/nrf52840/nrf52840.cpp