Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_cimagl.c File Reference
s_cimagl.c File Reference
#include <openlibm_complex.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT long double cimagl (long double complex z)
Function Documentation
cimagl()
OLM_DLLEXPORT long double cimagl (long double complex z)
References z.
Referenced by cabsl(), cacosl(), cargl(), casinl(), catanl(), ccoshl(), ccosl(), cexpl(), clogl(), conjl(), cpowl(), cprojl(), csinhl(), csinl(), csqrtl(), ctanhl(), ctanl(), and ctansl().