Embedded Artistry Framework: embutil::InterruptCondition< TWaitOp, TNotifyOp > Class Template Reference
embutil::InterruptCondition< TWaitOp, TNotifyOp > Class Template Reference
Generic interrupt condition concept.
#include <interrupt_condition.hpp>
Public Member Functions
InterruptCondition (const TWaitOp &w)
Construct an InterruptCondition with a wait op.
InterruptCondition (const TWaitOp &w, const TNotifyOp &n)
Construct an InterruptCondition with a wait op and notify op.
InterruptCondition (const InterruptCondition &)=delete
Deleted copy constructor.
const InterruptCondition & operator= (const InterruptCondition &)=delete
Deleted copy assignment operator.
InterruptCondition (InterruptCondition &&)=delete
Deleted move constructor.
InterruptCondition & operator= (InterruptCondition &&)=delete
Deleted move assignment operator.
template<typename TLock >
void wait (TLock &lock)
Initiate a wait state.
void notify ()
Notify the processor to wake up.
void set_notify_op (TNotifyOp &&n)
Set the notify operation.
Private Attributes
TNotifyOp notify_
(optional) notification operation functor
TWaitOp wait_
Wait operaton functor.
Detailed Description
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>>
class embutil::InterruptCondition< TWaitOp, TNotifyOp >
Generic interrupt condition concept.
Provides a condition-variable class for use on an embedded system which does not have threading, but wants to use interrupts for notifications (e.g. with ARM's WFI instruction). ` If we think about interrupt and non-interrupt execution modes as two threads, locking in a non-interrupt thread is equivalent to disabling interrupts; waiting for condition variable to be notified is the equivalent for waiting for interrupts.
Clients supply one or two operations:
wait(), which puts the processor in a mode to wait for interrupts (e.g., wfi)
notify(), which pulls the processor out of the wait mode
Note
Some scenarios, like wfi, do not require a function to be called. Instead, the wfi state exit is equivalent to notify(). Clients do not need to supply the notify operation in such scenarios.
This class is designed to be used with an InterruptLock.
Template Parameters
TWaitOp Represents the storage type (std::function, stdext::inplace_function) and prototype for the wait operation.
TNotifyOp Represents the storage type (std::function, stdext::inplace_function) and prototype for the notify operation.
Constructor & Destructor Documentation
InterruptCondition() [1/4]
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> embutil::InterruptCondition< TWaitOp, TNotifyOp >::InterruptCondition (const TWaitOp & w) inline explicit
Construct an InterruptCondition with a wait op.
Parameters
[in] w The wait operation functor.
InterruptCondition() [2/4]
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> embutil::InterruptCondition< TWaitOp, TNotifyOp >::InterruptCondition (const TWaitOp & w, const TNotifyOp & n) inline explicit
Construct an InterruptCondition with a wait op and notify op.
Parameters
[in] w The wait operation functor.
[in] n The notify operation functor.
InterruptCondition() [3/4]
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> embutil::InterruptCondition< TWaitOp, TNotifyOp >::InterruptCondition (const InterruptCondition< TWaitOp, TNotifyOp > &) delete
Deleted copy constructor.
InterruptCondition() [4/4]
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> embutil::InterruptCondition< TWaitOp, TNotifyOp >::InterruptCondition (InterruptCondition< TWaitOp, TNotifyOp > &&) delete
Deleted move constructor.
Member Function Documentation
notify()
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> void embutil::InterruptCondition< TWaitOp, TNotifyOp >::notify () inline
Notify the processor to wake up.
This function is used to notify condition that wait should be terminated. If nothing needs to be done (e.g. WFI), then client classes do not need to supply a notify function.
References embutil::InterruptCondition< TWaitOp, TNotifyOp >::notify_.
operator=() [1/2]
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> const InterruptCondition& embutil::InterruptCondition< TWaitOp, TNotifyOp >::operator= (const InterruptCondition< TWaitOp, TNotifyOp > &) delete
Deleted copy assignment operator.
operator=() [2/2]
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> InterruptCondition& embutil::InterruptCondition< TWaitOp, TNotifyOp >::operator= (InterruptCondition< TWaitOp, TNotifyOp > &&) delete
Deleted move assignment operator.
set_notify_op()
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> void embutil::InterruptCondition< TWaitOp, TNotifyOp >::set_notify_op (TNotifyOp && n) inline
Set the notify operation.
Parameters
[in] n The operation to call to notify() the processor that the wait is completed.
References n, and embutil::InterruptCondition< TWaitOp, TNotifyOp >::notify_.
wait()
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> template<typename TLock > void embutil::InterruptCondition< TWaitOp, TNotifyOp >::wait (TLock & lock) inline
Initiate a wait state.
Receives the reference to lockable object (has lock() and unlock() member functions) that is already locked.
The behavior of this function matches std::condition_variable:
locked lock is received
unlock the lock
wait for notification to wake up
re-acquire the lock and return control to the caller
Template Parameters
TLock the type of the lock. The compiler deduces this template parameter.
Parameters
lock The lock instance.
Precondition
lock is already locked.
Postcondition
lock is locked.
References embutil::InterruptCondition< TWaitOp, TNotifyOp >::wait_.
Member Data Documentation
notify_
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> TNotifyOp embutil::InterruptCondition< TWaitOp, TNotifyOp >::notify_ private
(optional) notification operation functor
Referenced by embutil::InterruptCondition< TWaitOp, TNotifyOp >::notify(), and embutil::InterruptCondition< TWaitOp, TNotifyOp >::set_notify_op().
wait_
template<typename TWaitOp = stdext::inplace_function<void()>, typename TNotifyOp = stdext::inplace_function<void()>> TWaitOp embutil::InterruptCondition< TWaitOp, TNotifyOp >::wait_ private
Wait operaton functor.
Referenced by embutil::InterruptCondition< TWaitOp, TNotifyOp >::wait().
The documentation for this class was generated from the following file:
src/utilities/interrupt_condition/interrupt_condition.hpp