Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_floor.c File Reference
s_floor.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double floor (double x)
Variables
static const double huge = 1.0e300
Function Documentation
floor()
OLM_DLLEXPORT double floor (double x)
References EXTRACT_WORDS, huge, and INSERT_WORDS.
Referenced by __kernel_rem_pio2(), floor_test(), round(), and sin_pi().
Variable Documentation
huge
const double huge = 1.0e300 static
Referenced by floor().