Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_log.c File Reference
e_log.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double __ieee754_log (double x)
Variables
static const double ln2_hi = 6.93147180369123816490e-01
static const double ln2_lo = 1.90821492927058770002e-10
static const double two54 = 1.80143985094819840000e+16
static const double Lg1 = 6.666666666666735130e-01
static const double Lg2 = 3.999999999940941908e-01
static const double Lg3 = 2.857142874366239149e-01
static const double Lg4 = 2.222219843214978396e-01
static const double Lg5 = 1.818357216161805012e-01
static const double Lg6 = 1.531383769920937332e-01
static const double Lg7 = 1.479819860511658591e-01
static const double zero = 0.0
Function Documentation
__ieee754_log()
OLM_DLLEXPORT double __ieee754_log (double x)
References EXTRACT_WORDS, GET_HIGH_WORD, k, Lg1, Lg2, Lg3, Lg4, Lg5, Lg6, Lg7, ln2_hi, ln2_lo, R, s, SET_HIGH_WORD, t1, t2, two54, w, z, and zero.
Referenced by __ieee754_acosh(), __ieee754_jn(), __ieee754_lgamma_r(), __ieee754_y0(), __ieee754_y1(), and asinh().
Variable Documentation
Lg1
const double Lg1 = 6.666666666666735130e-01 static
Referenced by __ieee754_log().
Lg2
const double Lg2 = 3.999999999940941908e-01 static
Referenced by __ieee754_log().
Lg3
const double Lg3 = 2.857142874366239149e-01 static
Referenced by __ieee754_log().
Lg4
const double Lg4 = 2.222219843214978396e-01 static
Referenced by __ieee754_log().
Lg5
const double Lg5 = 1.818357216161805012e-01 static
Referenced by __ieee754_log().
Lg6
const double Lg6 = 1.531383769920937332e-01 static
Referenced by __ieee754_log().
Lg7
const double Lg7 = 1.479819860511658591e-01 static
Referenced by __ieee754_log().
ln2_hi
const double ln2_hi = 6.93147180369123816490e-01 static
Referenced by __ieee754_log().
ln2_lo
const double ln2_lo = 1.90821492927058770002e-10 static
Referenced by __ieee754_log().
two54
const double two54 = 1.80143985094819840000e+16 static
Referenced by __ieee754_log().
zero
const double zero = 0.0 static
Referenced by __ieee754_log().