Embedded Artistry Framework: src/stdlibs/libc/openlibm/ld80/e_expl.c File Reference
e_expl.c File Reference
#include <openlibm_math.h>
#include "math_private.h"
Functions
long double expl (long double x)
Variables
static long double P [3]
static long double Q [4]
static const long double C1 = 6.9314575195312500000000E-1L
static const long double C2 = 1.4286068203094172321215E-6L
static const long double MAXLOGL = 1.1356523406294143949492E4L
static const long double MINLOGL = -1.13994985314888605586758E4L
static const long double LOG2EL = 1.4426950408889634073599E0L
Function Documentation
expl()
long double expl (long double x)
References __polevll(), C1, C2, floorl(), INFINITY, isnan, ldexpl(), LOG2EL, MAXLOGL, MINLOGL, n, P, and Q.
Referenced by cchshl(), cexpl(), coshl(), cpowl(), erfcl(), erfl(), sinhl(), stirf(), and tgammal().
Variable Documentation
C1
const long double C1 = 6.9314575195312500000000E-1L static
Referenced by expl().
C2
const long double C2 = 1.4286068203094172321215E-6L static
Referenced by expl().
LOG2EL
const long double LOG2EL = 1.4426950408889634073599E0L static
Referenced by expl().
MAXLOGL
const long double MAXLOGL = 1.1356523406294143949492E4L static
Referenced by expl().
MINLOGL
const long double MINLOGL = -1.13994985314888605586758E4L static
Referenced by expl().
P
long double P[3] static
Initial value:
= {
 1.2617719307481059087798E-4L,
 3.0299440770744196129956E-2L,
 9.9999999999999999991025E-1L,
}
Referenced by expl().
Q
long double Q[4] static
Initial value:
= {
 3.0019850513866445504159E-6L,
 2.5244834034968410419224E-3L,
 2.2726554820815502876593E-1L,
 2.0000000000000000000897E0L,
}
Referenced by expl().