Embedded Artistry Framework: nRFGPIOOutput< TPort, TPin > Class Template Reference
nRFGPIOOutput< TPort, TPin > Class Template Reference final
#include <nrf_gpio.hpp>
Public Member Functions
nRFGPIOOutput ()
Construct a generic GPIO output.
nRFGPIOOutput (const char *name)
Construct a named GPIO output.
~nRFGPIOOutput () final=default
Default destructor.
void set (bool v) final
Set the current GPIO pin state.
gpio::direction direction () const
Check the direction of the GPIO pin.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
GPIO Driver Type ID.
Protected Attributes
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
Constructor & Destructor Documentation
nRFGPIOOutput() [1/2]
template<uint8_t TPort, uint8_t TPin> nRFGPIOOutput< TPort, TPin >::nRFGPIOOutput () inline explicit
Construct a generic GPIO output.
nRFGPIOOutput() [2/2]
template<uint8_t TPort, uint8_t TPin> nRFGPIOOutput< TPort, TPin >::nRFGPIOOutput (const char * name) inline explicit
Construct a named GPIO output.
Parameters
name The name of the GPIO pin
~nRFGPIOOutput()
template<uint8_t TPort, uint8_t TPin> nRFGPIOOutput< TPort, TPin >::~nRFGPIOOutput () final default
Default destructor.
Member Function Documentation
direction()
gpio::direction embvm::gpio::base< TDir >::direction () const inline inherited
Check the direction of the GPIO pin.
Returns
The configured direction of this GPIO pin.
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
set()
template<uint8_t TPort, uint8_t TPin> void nRFGPIOOutput< TPort, TPin >::set (bool v) inline final virtual
Set the current GPIO pin state.
Derived classes must implement the set() function.
Parameters
v The desired GPIO state. True for logic 1, false for logic 0.
Implements embvm::gpio::output.
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
template<uint8_t TPort, uint8_t TPin> void nRFGPIOOutput< TPort, TPin >::start_ () inline final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::gpio::output.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
template<uint8_t TPort, uint8_t TPin> void nRFGPIOOutput< TPort, TPin >::stop_ () inline final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::gpio::output.
type()
static constexpr embvm::DriverType embvm::gpio::base< TDir >::type () inline static inherited
GPIO Driver Type ID.
Returns
GPIO type ID.
Member Data Documentation
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
The documentation for this class was generated from the following file:
src/processors/arm/nordic/drivers/nrf_gpio.hpp