Embedded Artistry Framework: src/stdlibs/libc/src/ctype/ispunct.c File Reference
ispunct.c File Reference
#include <ctype.h>
Functions
int ispunct (int c)
Checks if the given character is a punctuation character.
Function Documentation
ispunct()
int ispunct (int ch)
Checks if the given character is a punctuation character.
Checks if the given character is a punctuation character using the default local. The following characters are classified as punctuation character:
(!"#$%&'()*+,-./:;<=>?@[]^_`{|}~)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is a punctuation character, zero otherwise.
References isalnum(), and isgraph().
Referenced by bad_input(), and good_input().