Embedded Artistry Framework: UnitTestPlatform Class Reference
UnitTestPlatform Class Reference
This platform exists for use in the framework unit tests.
#include <platform.hpp>
Public Member Functions
UnitTestPlatform () noexcept
Default constructor with a supplied platform name.
UnitTestPlatform (const char *name) noexcept
Specify unit test platform by const char* to test the platform base APIs.
UnitTestPlatform (const std::string &name) noexcept
Specify unit test platform by std::string to test the platform base APIs.
UnitTestPlatform (const std::string_view &name) noexcept
Specify unit test platform by std::string_view to test the platform base APIs.
~UnitTestPlatform ()=default
void init_ () noexcept
void initProcessor_ () noexcept
void initHWPlatform_ () noexcept
auto hwPlatformName () noexcept
auto hwPlatformName_cstr () noexcept
void init () noexcept
Initialize the platform.
void initProcessor () noexcept
Initialize the processor.
void initHWPlatform () noexcept
Initialize the hardware platform.
constexpr const std::string_view & name () const noexcept
Access the platform's name.
constexpr const char * name_cstr () const noexcept
Access the platform name as a cstring for C API compatibility.
auto findDriver (const std::string_view &name) noexcept
Access a device driver in the registry by name.
auto findDriver (embvm::DriverType_t type) noexcept
Access a device driver in the registry by type.
auto findDriver () noexcept
Access a device driver in the registry by type, cast as the appropriate base class.
auto findDriver (const std::string_view &name) noexcept
Access a device driver in the registry by name, cast as the appropriate base class.
auto findAllDrivers (embvm::DriverType_t type) noexcept
Get a list of all device drivers in the registry by type.
auto findAllDrivers () noexcept
Get a list of all device drivers in the registry by type, cast as the appropriate base class.
size_t driverCount () const noexcept
Get the count of drivers registered with the platform.
auto getBoundDispatch () noexcept
Get std::bind object corresponding dispatch(const&) function.
auto getBoundMoveDispatch () noexcept
Get std::bind object corresponding dispatch(&&) function.
void dispatch (const TFunc &op) noexcept
Dispatch an operation.
void dispatch (TFunc &&op) noexcept
Dispatch an operation.
auto subscribeToEvent (event_sig_t sig, const event_cb_t &cb) noexcept
Subscribe to an event.
auto subscribeToEvent (event_sig_t sig, event_cb_t &&cb) noexcept
void unsubscribeFromEvent (typename PlatformEventCenter ::EventHandle &handle) noexcept
Unsubscribe from an event.
void signal (event_sig_t sig) noexcept
Forwards a signal to the event manager.
void publishEvent (EventBase event) noexcept
Forwards an event to the event manager.
Static Public Member Functions
static void earlyInitHook_ () noexcept
static UnitTestPlatform & inst () noexcept
Get the global platform instance.
static void earlyInitHook () noexcept
Call early-initialization code.
static void initOS () noexcept
Initialize the OS.
static void initOS (void(*main_thread)()) noexcept
Initialize the with a function to use as the main thread.
static void registerDriver (const std::string_view &name, embvm::DriverBase *driver) noexcept
Platform-level API for registering a new device driver.
static void unregisterDriver (const std::string_view &name, embvm::DriverBase *driver) noexcept
Platform-level API for unregistering a new device driver.
Protected Attributes
const std::string_view name_
PlatformDispatchQueue dispatch_queue_
PlatformEventCenter event_manager_
The instance of the event manager that belongs to the platform.
Private Types
using VirtualPlatform = embvm::VirtualPlatformBase< UnitTestPlatform, PlatformDriverRegistry >
Private Attributes
UnitTestHWPlatform hw_platform_
Detailed Description
This platform exists for use in the framework unit tests.
Member Typedef Documentation
VirtualPlatform
using UnitTestPlatform::VirtualPlatform = embvm::VirtualPlatformBase<UnitTestPlatform, PlatformDriverRegistry> private
Constructor & Destructor Documentation
UnitTestPlatform() [1/4]
UnitTestPlatform::UnitTestPlatform () inline noexcept
Default constructor with a supplied platform name.
UnitTestPlatform() [2/4]
UnitTestPlatform::UnitTestPlatform (const char * name) inline explicit noexcept
Specify unit test platform by const char* to test the platform base APIs.
UnitTestPlatform() [3/4]
UnitTestPlatform::UnitTestPlatform (const std::string & name) inline explicit noexcept
Specify unit test platform by std::string to test the platform base APIs.
UnitTestPlatform() [4/4]
UnitTestPlatform::UnitTestPlatform (const std::string_view & name) inline explicit noexcept
Specify unit test platform by std::string_view to test the platform base APIs.
~UnitTestPlatform()
UnitTestPlatform::~UnitTestPlatform () default
Member Function Documentation
dispatch() [1/2]
void embvm::PlatformDispatcher< PlatformDispatchQueue >::dispatch (const TFunc & op) inline noexcept inherited
Dispatch an operation.
Dispatch an operation to the queue. Forwards the function object to the underlying dispatch queue.
Parameters
op The function object containing the operation that will be dispatched to the queue.
dispatch() [2/2]
void embvm::PlatformDispatcher< PlatformDispatchQueue >::dispatch (TFunc && op) inline noexcept inherited
Dispatch an operation.
Dispatch an operation to the queue. Forwards the function object to the underlying dispatch queue.
Parameters
op The function object containing the operation that will be dispatched to the queue.
driverCount()
size_t embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::driverCount () const inline noexcept inherited
Get the count of drivers registered with the platform.
returns Number of drivers currently registered with the platform DriverRegistry.
earlyInitHook()
static void embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::earlyInitHook () inline static noexcept inherited
Call early-initialization code.
Call early initialization code, which is to be run before C runtime initialization, memory relocations, OS initialization, etc. This call is used to handle early setup code that the rest of the initialization process might depend on, such as DRAM initialization.
This function forwards the call to the derived class for the actual implementation.
earlyInitHook_()
static void UnitTestPlatform::earlyInitHook_ () inline static noexcept
References embvm::VirtualHwPlatformBase< UnitTestHWPlatform >::earlyInitHook().
findAllDrivers() [1/2]
auto embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::findAllDrivers (embvm::DriverType_t type) inline noexcept inherited
Get a list of all device drivers in the registry by type.
The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Parameters
type The type of driver being requested (embvm::i2c::master, SystemClock).
Returns
A list of embvm::DriverBase instances. If no matching types are found, an empty list will be returned. The caller must cast to the appropriate type.
findAllDrivers() [2/2]
auto embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::findAllDrivers () inline noexcept inherited
Get a list of all device drivers in the registry by type, cast as the appropriate base class.
The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Returns
A list of driver instances cast as TDriverClass types. If no matching types are found, an empty list will be returned.
findDriver() [1/4]
auto embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::findDriver (const std::string_view & name) inline noexcept inherited
Access a device driver in the registry by name.
Find a driver by name.
This call forwards the information to the DriverRegistry instance.
Returns
An optional_ref to the embvm::DriverBase instance. If no instance is found, the optional reference will be invalid. The caller must cast to the appropriate type.
findDriver() [2/4]
auto embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::findDriver (embvm::DriverType_t type) inline noexcept inherited
Access a device driver in the registry by type.
Find a driver by type. If multiple drivers are found for a type, the first one found will be returned.
This call forwards the information to the DriverRegistry instance.
Returns
An optional_ref to the embvm::DriverBase instance. If no instance is found, the optional reference will be invalid. The caller must cast to the appropriate type.
findDriver() [3/4]
auto embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::findDriver () inline noexcept inherited
Access a device driver in the registry by type, cast as the appropriate base class.
If multiple drivers are found for a type, the first one found will be returned. The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Returns
an type_safe::optional_ref cast to the TDriverClass type. If the driver was not found, the optional_ref will be empty.
findDriver() [4/4]
auto embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::findDriver (const std::string_view & name) inline noexcept inherited
Access a device driver in the registry by name, cast as the appropriate base class.
The type will be returned as the appropriate base class (instead of embvm::DriverBase).
This call forwards the information to the DriverRegistry instance.
Template Parameters
TDriverClass The class of driver being requested (embvm::i2c::master, SystemClock).
Returns
an type_safe::optional_ref cast to the TDriverClass type. If the driver was not found, the optional_ref will be empty.
getBoundDispatch()
auto embvm::PlatformDispatcher< PlatformDispatchQueue >::getBoundDispatch () inline noexcept inherited
Get std::bind object corresponding dispatch(const&) function.
If you need to get the function dispatch(const&) variant for use with another class, (e.g., passing dispatch() as a callback), use this function.
Returns
A std::bind object corresponding to the dispatch(const&) function.
getBoundMoveDispatch()
auto embvm::PlatformDispatcher< PlatformDispatchQueue >::getBoundMoveDispatch () inline noexcept inherited
Get std::bind object corresponding dispatch(&&) function.
If you need to get the function dispatch(&&) variant for use with another class, (e.g., passing dispatch() as a callback), use this function.
Returns
A std::bind object corresponding to the dispatch(&&) function.
hwPlatformName()
auto UnitTestPlatform::hwPlatformName () inline noexcept
References hw_platform_, and embvm::VirtualHwPlatformBase< THWPlatform >::name().
hwPlatformName_cstr()
auto UnitTestPlatform::hwPlatformName_cstr () inline noexcept
References hw_platform_, and embvm::VirtualHwPlatformBase< THWPlatform >::name_cstr().
init()
void embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::init () inline noexcept inherited
Initialize the platform.
This function is responsible for initializing the platform.
This function forwards the call to the derived class for the actual implementation.
init_()
void UnitTestPlatform::init_ () inline noexcept
initHWPlatform()
void embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::initHWPlatform () inline noexcept inherited
Initialize the hardware platform.
Performs steps necessary to initialize the hardware platform for use by the platform. In many cases, this call should just invoke the hardware platform's init() function. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the hardware platform in situations where non-default values are used.
This function forwards the call to the derived class for the actual implementation.
initHWPlatform_()
void UnitTestPlatform::initHWPlatform_ () inline noexcept
References hw_platform_, and embvm::VirtualHwPlatformBase< THWPlatform >::init().
initOS() [1/2]
static void embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::initOS () inline static noexcept inherited
Initialize the OS.
Performs steps necessary to initialize the OS for use by the platform. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the OS, since each OS has different startup requirements
This function forwards the call to the derived class for the actual implementation.
initOS() [2/2]
static void embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::initOS (void(*)() main_thread) inline static noexcept inherited
Initialize the with a function to use as the main thread.
Performs steps necessary to initialize the OS for use by the platform. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the OS, since each OS has different startup requirements
This function forwards the call to the derived class for the actual implementation.
Parameters
main_thread a function pointer to use as the main thread routine. This version of initOS should be used for OSes such as FreeRTOS which kill execution of the current thread when the scheduler is started.
initProcessor()
void embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::initProcessor () inline noexcept inherited
Initialize the processor.
Performs steps necessary to initialize the processor for use by the platform. In many cases, this call should just invoke the processor's init() function. Control of this function is placed in the platform layer to allow for platform-specific customization & initialization of the processor in situations where non-default values are used.
This function forwards the call to the derived class for the actual implementation.
initProcessor_()
void UnitTestPlatform::initProcessor_ () inline noexcept
References hw_platform_, and embvm::VirtualHwPlatformBase< THWPlatform >::initProcessor().
inst()
static UnitTestPlatform & embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::inst () inline static noexcept inherited
Get the global platform instance.
Static declaration of the VirtualPlatformBase instance. We use this function to avoid the static initializatio order 'fiasco'. See more: https://isocpp.org/wiki/faq/ctors#static-init-order
name()
constexpr const std::string_view& embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::name () const inline noexcept inherited
Access the platform's name.
Returns
Platform name std::string_view reference.
name_cstr()
constexpr const char* embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::name_cstr () const inline noexcept inherited
Access the platform name as a cstring for C API compatibility.
Returns
Platform name as a C-string.
publishEvent()
void embvm::PlatformEventManagement< PlatformEventCenter >::publishEvent (EventBase event) inline noexcept inherited
Forwards an event to the event manager.
Parameters
event The event to publish to the platform event manager.
registerDriver()
static void embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::registerDriver (const std::string_view & name, embvm::DriverBase * driver) inline static noexcept inherited
Platform-level API for registering a new device driver.
Register a device driver with the platform's driver registry.
This call forwards the information to the DriverRegistry instance.
Parameters
name The name (used as a key) the driver will be registered under.
driver Pointer to the embvm::DriverBase object. A pointer is used because there are any number of potential derived classes which will be tracked. To prevent slicing, a pointer to the base class is stored.
signal()
void embvm::PlatformEventManagement< PlatformEventCenter >::signal (event_sig_t sig) inline noexcept inherited
Forwards a signal to the event manager.
Parameters
sig The signal to raise to the platform event manager.
subscribeToEvent() [1/2]
auto embvm::PlatformEventManagement< PlatformEventCenter >::subscribeToEvent (event_sig_t sig, const event_cb_t & cb) inline noexcept inherited
Subscribe to an event.
Parameters
sig The signal to subscribe to.
cb The callback function to invoke when the signal is raised.
Returns
A handle to the event subscription. The handle must remain within scope for the subscription to be valid. Whent he handle leaves scope, the
subscribeToEvent() [2/2]
auto embvm::PlatformEventManagement< PlatformEventCenter >::subscribeToEvent (event_sig_t sig, event_cb_t && cb) inline noexcept inherited
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
unregisterDriver()
static void embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::unregisterDriver (const std::string_view & name, embvm::DriverBase * driver) inline static noexcept inherited
Platform-level API for unregistering a new device driver.
Unregister a device driver with the platform's driver registry.
This call forwards the information to the DriverRegistry instance.
Parameters
name The name of the driver to remove.
driver Pointer to the embvm::DriverBase object being removed.
unsubscribeFromEvent()
void embvm::PlatformEventManagement< PlatformEventCenter >::unsubscribeFromEvent (typename PlatformEventCenter ::EventHandle & handle) inline noexcept inherited
Unsubscribe from an event.
Parameters
handle The event handle to unsubscribe.
Member Data Documentation
dispatch_queue_
PlatformDispatchQueue embvm::PlatformDispatcher< PlatformDispatchQueue >::dispatch_queue_ protected inherited
event_manager_
PlatformEventCenter embvm::PlatformEventManagement< PlatformEventCenter >::event_manager_ protected inherited
The instance of the event manager that belongs to the platform.
hw_platform_
UnitTestHWPlatform UnitTestPlatform::hw_platform_ private
Referenced by hwPlatformName(), hwPlatformName_cstr(), initHWPlatform_(), and initProcessor_().
name_
const std::string_view embvm::VirtualPlatformBase< UnitTestPlatform , PlatformDriverRegistry >::name_ protected inherited
The documentation for this class was generated from the following file:
src/platforms/unit_test/platform.hpp