Embedded Artistry libc: src/gdtoa/src/ulp.c File Reference
ulp.c File Reference
#include "gdtoaimp.h"
Functions
double ulp (double x)
Function Documentation
ulp()
double ulp (double x)
Definition at line 39 of file ulp.c.
References Exp_mask, Exp_msk1, Exp_shift, Long, P, word0, and word1.
Referenced by strtod(), strtodI(), and ulpdown().
 {
     Long L;
     double a;
     L = (word0(x) & Exp_mask) - (P-1)*Exp_msk1;
 #ifndef Sudden_Underflow
     if (L > 0) {
 #endif
 #ifdef IBM
         L |= Exp_msk1 >> 4;
 #endif
         word0(a) = L;
         word1(a) = 0;
 #ifndef Sudden_Underflow
         }
     else {
         L = -L >> Exp_shift;
         if (L < Exp_shift) {
             word0(a) = 0x80000 >> L;
             word1(a) = 0;
             }
         else {
             word0(a) = 0;
             L -= Exp_shift;
             word1(a) = L >= 31 ? 1 : 1 << (31 - L);
             }
         }
 #endif
     return a;
     }