Embedded Artistry Framework: src/stdlibs/libc/test/ctype/ctype_tests.c File Reference
ctype_tests.c File Reference
#include "ctype_tests.h"
#include <stdlib.h>
#include <tests.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Functions
int ctype_tests (void)
Function Documentation
ctype_tests()
int ctype_tests (void)
References isalnum_tests(), isalpha_tests(), isascii_tests(), isblank_tests(), iscntrl_tests(), isdigit_tests(), isgraph_tests(), islower_tests(), isprint_tests(), ispunct_tests(), isspace_tests(), isupper_tests(), isxdigit_tests(), toascii_tests(), tolower_tests(), and toupper_tests().
Referenced by main().