Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_jn.c File Reference
e_jn.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double __ieee754_jn (int n, double x)
OLM_DLLEXPORT double __ieee754_yn (int n, double x)
Variables
static const double invsqrtpi = 5.64189583547756279280e-01
static const double two = 2.00000000000000000000e+00
static const double one = 1.00000000000000000000e+00
static const double zero = 0.00000000000000000000e+00
Function Documentation
__ieee754_jn()
OLM_DLLEXPORT double __ieee754_jn (int n, double x)
References __ieee754_j0(), __ieee754_j1(), __ieee754_log(), a, b, cos(), IEEEl2bits::e, EXTRACT_WORDS, fabs(), invsqrtpi, k, n, one, sin(), sqrt(), t, two, w, z, and zero.
__ieee754_yn()
OLM_DLLEXPORT double __ieee754_yn (int n, double x)
References __ieee754_y0(), __ieee754_y1(), a, b, cos(), EXTRACT_WORDS, GET_HIGH_WORD, high, invsqrtpi, n, one, sin(), sqrt(), and zero.
Variable Documentation
invsqrtpi
const double invsqrtpi = 5.64189583547756279280e-01 static
Referenced by __ieee754_jn(), and __ieee754_yn().
one
const double one = 1.00000000000000000000e+00 static
Referenced by __ieee754_jn(), and __ieee754_yn().
two
const double two = 2.00000000000000000000e+00 static
Referenced by __ieee754_jn().
zero
const double zero = 0.00000000000000000000e+00 static
Referenced by __ieee754_jn(), and __ieee754_yn().