Embedded Artistry Framework: src/drivers/aardvark/vendor/examples/aalights.c File Reference
aalights.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "aardvark.h"
Macros
#define I2C_BITRATE 100
Functions
static int flash_lights (Aardvark handle)
int main (int argc, char *argv[])
Macro Definition Documentation
I2C_BITRATE
#define I2C_BITRATE 100
Function Documentation
flash_lights()
static int flash_lights (Aardvark handle) static
References AA_I2C_NO_FLAGS, aa_i2c_write(), aa_sleep_ms(), and printf.
Referenced by main().
main()
int main (int argc, char * argv[])
References aa_close(), AA_CONFIG_SPI_I2C, aa_configure(), aa_i2c_bitrate(), aa_i2c_pullup(), AA_I2C_PULLUP_BOTH, aa_log(), aa_open(), aa_status_string(), aa_target_power(), AA_TARGET_POWER_BOTH, atoi(), fclose(), flash_lights(), fopen(), I2C_BITRATE, and printf.