Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_ccosh.c File Reference
s_ccosh.c File Reference
#include "cdefs-compat.h"
#include <openlibm_complex.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT double complex ccosh (double complex z)
OLM_DLLEXPORT double complex ccos (double complex z)
Variables
static const double huge = 0x1p1023
Function Documentation
ccos()
OLM_DLLEXPORT double complex ccos (double complex z)
References ccosh(), cimag(), CMPLX(), creal(), and z.
ccosh()
OLM_DLLEXPORT double complex ccosh (double complex z)
References __ldexp_cexp(), cimag(), CMPLX(), copysign(), cos(), cosh(), creal(), exp(), EXTRACT_WORDS, fabs(), huge, sin(), sinh(), and z.
Referenced by ccos().
Variable Documentation
huge
const double huge = 0x1p1023 static
Referenced by ccosh().