Embedded Artistry Framework: src/stdlibs/libc/openlibm/mips/fenv-softfloat.h File Reference
fenv-softfloat.h File Reference
Functions
void __softfloat_float_raise (int)
__fenv_static int feclearexcept (int __excepts)
__fenv_static int fegetexceptflag (fexcept_t *__flagp, int __excepts)
__fenv_static int fesetexceptflag (const fexcept_t *__flagp, int __excepts)
__fenv_static int feraiseexcept (int __excepts)
__fenv_static int fetestexcept (int __excepts)
__fenv_static int fegetround (void)
__fenv_static int fesetround (int __round)
__fenv_static int fegetenv (fenv_t *__envp)
__fenv_static int feholdexcept (fenv_t *__envp)
__fenv_static int fesetenv (const fenv_t *__envp)
__fenv_static int feupdateenv (const fenv_t *__envp)
Variables
int __softfloat_float_exception_flags
int __softfloat_float_exception_mask
int __softfloat_float_rounding_mode
Function Documentation
__softfloat_float_raise()
void __softfloat_float_raise (int)
Referenced by feraiseexcept().
feclearexcept()
__fenv_static int feclearexcept (int __excepts) inline
References __rfs, __softfloat_float_exception_flags, and __wfs.
Referenced by fn(), gamma_test(), init_max_error(), initialize(), lgamma_test(), sqrtl(), test_exceptions(), and tgamma_test().
fegetenv()
__fenv_static int fegetenv (fenv_t * __envp) inline
References fenv_t::__control, __fldcw, __fnstenv, fenv_t::__mxcsr, __softfloat_float_exception_flags, __softfloat_float_exception_mask, __softfloat_float_rounding_mode, __stmxcsr, and fenv_t::__x87.
Referenced by feholdexcept().
fegetexceptflag()
__fenv_static int fegetexceptflag (fexcept_t * __flagp, int __excepts) inline
References __fnstsw, __softfloat_float_exception_flags, and __stmxcsr.
fegetround()
__fenv_static int fegetround (void) inline
References __fnstcw, __softfloat_float_rounding_mode, and _ROUND_MASK.
Referenced by fma(), fmaf(), fmal(), sqrtl(), and strtod().
feholdexcept()
__fenv_static int feholdexcept (fenv_t * __envp) inline
References __fnclex, __fnstenv, __ldmxcsr, fenv_t::__mxcsr, __softfloat_float_exception_flags, __softfloat_float_exception_mask, __stmxcsr, fenv_t::__x87, _SSE_EMASK_SHIFT, FE_ALL_EXCEPT, and fegetenv().
Referenced by fn(), and sqrtl().
feraiseexcept()
__fenv_static int feraiseexcept (int __excepts) inline
References __fwait, __softfloat_float_raise(), and fesetexceptflag().
Referenced by feupdateenv(), fma(), fmal(), and fn().
fesetenv()
__fenv_static int fesetenv (const fenv_t * __envp) inline
References __fldenvx, __ldmxcsr, fenv_t::__mxcsr, __softfloat_float_exception_flags, __softfloat_float_exception_mask, __softfloat_float_rounding_mode, and fenv_t::__x87.
Referenced by feupdateenv(), and sqrtl().
fesetexceptflag()
__fenv_static int fesetexceptflag (const fexcept_t * __flagp, int __excepts) inline
References __fldenv, __fnstenv, __ldmxcsr, fenv_t::__mxcsr, __softfloat_float_exception_flags, fenv_t::__status, __stmxcsr, and fenv_t::__x87.
Referenced by feraiseexcept().
fesetround()
__fenv_static int fesetround (int __round) inline
References __fldcw, __fnstcw, __ldmxcsr, __softfloat_float_rounding_mode, __stmxcsr, _ROUND_MASK, and _SSE_ROUND_SHIFT.
Referenced by fma(), fmaf(), fmal(), and sqrtl().
fetestexcept()
__fenv_static int fetestexcept (int __excepts) inline
References __rfs, and __softfloat_float_exception_flags.
Referenced by fn(), sqrtl(), and test_single_exception().
feupdateenv()
__fenv_static int feupdateenv (const fenv_t * __envp) inline
References __fnstsw, __softfloat_float_exception_flags, __stmxcsr, FE_ALL_EXCEPT, feraiseexcept(), and fesetenv().
Referenced by fn(), and sqrtl().
Variable Documentation
__softfloat_float_exception_flags
int __softfloat_float_exception_flags
Referenced by feclearexcept(), fegetenv(), fegetexceptflag(), feholdexcept(), fesetenv(), fesetexceptflag(), fetestexcept(), and feupdateenv().
__softfloat_float_exception_mask
int __softfloat_float_exception_mask
Referenced by fegetenv(), feholdexcept(), and fesetenv().
__softfloat_float_rounding_mode
int __softfloat_float_rounding_mode
Referenced by fegetenv(), fegetround(), fesetenv(), and fesetround().