Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_sinl.c File Reference
s_sinl.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "math_private.h"
#include "../ld80/e_rem_pio2l.h"
Functions
OLM_DLLEXPORT long double sinl (long double x)
Function Documentation
sinl()
OLM_DLLEXPORT long double sinl (long double x)
References __ieee754_rem_pio2l(), __kernel_cosl(), __kernel_sinl(), s, and z.
Referenced by ccoshl(), ccosl(), cexpl(), cpowl(), csinhl(), csinl(), ctanhl(), ctanl(), lgammal_r(), sin_pi(), sincosl(), and tgammal().