Embedded Artistry Framework: os::freertos Namespace Reference
os::freertos Namespace Reference
Namespaces
details
Classes
class ConditionVariable
class EventFlag
FreeRTOS Event Flag Implementation.
class freertosOSFactory_impl
Implementation of the FreeRTOS OS Factory For API documentation, see embvm::embvm::VirtualOSFactory.
class Heap
class MessageQueue
FreeRTOS Message Queue implementation for OSX.
class Mutex
FreeRTOS Mutex Implementation.
class Semaphore
Create a FreeRTOS semaphore (OSX variant)
class Thread
Create a FreeRTOS thread.
Typedefs
using thread_exit_t = void(*)(void *)
Functions
uint32_t frameworkTimeoutToTicks (const embvm::os_timeout_t &timeout) noexcept
void register_threadexit_func (thread_exit_t atexit) noexcept
void startScheduler () noexcept
Call this function to start the FreeRTOS scheduler.
Variables
static constexpr size_t FREERTOS_STACK_MIN = (1 * 1024)
Function Documentation
frameworkTimeoutToTicks()
uint32_t os::freertos::frameworkTimeoutToTicks (const embvm::os_timeout_t & timeout) inline noexcept
References embvm::OS_WAIT_FOREVER, and portMAX_DELAY.
Referenced by os::freertos::EventFlag::get(), embvm::this_thread::sleep_for(), and os::freertos::ConditionVariable::wait().