Embedded Artistry Framework: embvm::spi::master Class Reference
embvm::spi::master Class Reference abstract
This class provides the SPI master interface definition.
#include <spi.hpp>
Public Member Functions
master (const spi::commBus::DispatcherFunc &dispatcher=nullptr)
Default constructor.
master (const char *name, const spi::commBus::DispatcherFunc &dispatcher=nullptr)
Construct a SPI master with a C-string name.
master (const std::string &name, const spi::commBus::DispatcherFunc &dispatcher=nullptr)
Construct a SPI master with a std::string name.
master (const std::string_view &name, const spi::commBus::DispatcherFunc &dispatcher=nullptr)
Construct a SPI master with a std::string_view name.
virtual void configure (spi::baud_t baud)
Configure the SPI bus.
spi::mode mode () const
Get the current SPI bus mode.
spi::mode mode (spi::mode mode)
Set the SPI bus mode.
spi::order order () const
Get the current SPI bus byte order.
spi::order order (spi::order order)
Set the SPI bus byte order.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
SPI Driver Type ID.
Protected Member Functions
virtual void setMode_ (spi::mode mode)=0
Set the SPI bus mode.
virtual void setOrder_ (spi::order order)=0
Set the SPI bus byte order.
virtual void configure_ ()=0
Configure the SPI bus for operation.
~master () override
Default destructor.
void start_ () override=0
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () override=0
Derived classes override the start_ method to control driver-specific startup behavior.
spi::baud_t baudrate_ (spi::baud_t baud) override=0
embvm::comm::status transfer_ (const spi::op_t &op, const cb_t &cb) override=0
Protected Attributes
spi::mode mode_ = spi::mode::mode0
Stores the active SPI mode configuration.
spi::order order_ = spi::order::msbFirst
Stores the active SPI byte ordering.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Detailed Description
This class provides the SPI master interface definition.
This class defines common interfaces and types for SPI master devices.
Implementing a spi::master Driver
To implement your own SPI master device, simply inherit from this class type:
class aardvarkSPIMaster final : public spi::master
{...}
Derived classes must imlement the following pure virtual functions to complete SPI master behavior:
setOrder_(), to set byte ordering
setMode_(), to set bus mode
configure_(), to configure the target hardware for operation
Derived classes must also implement pure virtual functions required by the comm bus, such as:
transfer_(), which initiates a bus transfer
baudrate_(), which configures the baudrate
Using a spi::master Driver
spi::master usage follows this general pattern:
Declare a spi::master device
Configure the device
Initialize a transfer
Declare a spi::master device
Derived classes will have their own specific constructor schemes. In all cases you will use a derived class for the declaration.
aardvarkAdapter aardvark{aardvarkMode::SPI};
aardvarkSPIMaster d{aardvark, "spi0"};
Configure a spi::master device
After the device has been declared, the object can be used to configure the SPI bus. Initial configuration will happen with the configure() function, which sets up the SPI device with the target baudrate.
The mode() function is used to change the SPI bus mode (spi::mode). The order() function can be used to change the order bytes are sent over the bus (spi::order).
Initialize a Transfer
All transfers require an op structure instance with the proper settings:
uint8_t input[2] = {0xAA, 0xBB};
uint8_t output[2];
spi::op_t op = {input, output, 2};
You should also prepare a callback function to handle the transfer completion:
void spi_callback(spi::op_t input, embvm::comm::status status)
{
...
}
To initiate a transfer, call transfer() with the op and callback:
auto err = d.transfer(op, spi_callback);
When the transfer completes, the callback function will be called with a copy of the op struct and the result of the transfer.
Using with a Dispatch Queue
commBus devices support dispatching callbacks. You can construct a spi::master instance with a dispatcher function:
embutil::DynamicDispatchQueue<> dispatch;
spi0(dispatch.getBoundDispatch());
If a dispatcher has been configured, callbacks will be invoked on the dispatch thread instead of the spi::master's local thread. We recommend using dispatchers when possible for improved responsiveness.
Constructor & Destructor Documentation
master() [1/4]
embvm::spi::master::master (const spi::commBus::DispatcherFunc & dispatcher = nullptr) inline explicit
Default constructor.
Initializes the spi::master device with a generic name and optional dispatcher.
Parameters
dispatcher The functor which callbacks will be dispatched to. This will often be paired with a dispatch queue. Example:
   embutil::DynamicDispatchQueue<> dispatch;
spi0(dispatch.getBoundDispatch());
master() [2/4]
embvm::spi::master::master (const char * name, const spi::commBus::DispatcherFunc & dispatcher = nullptr) inline explicit
Construct a SPI master with a C-string name.
Initializes the spi::master instance with a name and optional dispatcher.
Parameters
name C-string name for the SPI master instance.
dispatcher The functor which callbacks will be dispatched to. This will often be paired with a dispatch queue. Example:
   embutil::DynamicDispatchQueue<> dispatch;
spi0("spi0", dispatch.getBoundDispatch());
master() [3/4]
embvm::spi::master::master (const std::string & name, const spi::commBus::DispatcherFunc & dispatcher = nullptr) inline explicit
Construct a SPI master with a std::string name.
Initializes the spi::master instance with a name and optional dispatcher.
Parameters
name std::string name for the SPI master instance. Note: spi::master() uses a std::string_view, so the std::string must remain valid
dispatcher The functor which callbacks will be dispatched to. This will often be paired with a dispatch queue. Example:
   embutil::DynamicDispatchQueue<> dispatch;
spi0("spi0", dispatch.getBoundDispatch());
master() [4/4]
embvm::spi::master::master (const std::string_view & name, const spi::commBus::DispatcherFunc & dispatcher = nullptr) inline explicit
Construct a SPI master with a std::string_view name.
Initializes the spi::master instance with a name and optional dispatcher.
Parameters
name std::string_view name for the SPI master instance. Note: spi::master() uses a std::string_view, so the original string must remain valid
dispatcher The functor which callbacks will be dispatched to. This will often be paired with a dispatch queue. Example:
   embutil::DynamicDispatchQueue<> dispatch;
spi0("spi0", dispatch.getBoundDispatch());
~master()
embvm::spi::master::~master () override protected default
Default destructor.
Member Function Documentation
baudrate_()
spi::baud_t embvm::spi::master::baudrate_ (spi::baud_t baud) override protected pure virtual
Implemented in test::spiTestDriver, embvm::spi::activeMaster< TQueueSize, TLock, TCond >, and embdrv::aardvarkSPIMaster.
configure()
virtual void embvm::spi::master::configure (spi::baud_t baud) inline virtual
Configure the SPI bus.
Configures the SPI bus for operation and sets the target baud rate.
Derived classes must implement the configure_() function to set up the target hardware.
Parameters
baud The target baudrate, in Hz. TODO: Tolerance - allowed relative tolerance for the resulting baudrate
References configure_().
configure_()
virtual void embvm::spi::master::configure_ () protected pure virtual
Configure the SPI bus for operation.
This function is implemented by the derived class. It is responsible for configuring the target hardware for operation.
Implemented in test::spiTestDriver, embdrv::aardvarkSPIMaster, and embvm::spi::activeMaster< TQueueSize, TLock, TCond >.
Referenced by configure().
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
mode() [1/2]
spi::mode embvm::spi::master::mode () const inline
Get the current SPI bus mode.
Returns
The currently configured mode.
References mode_.
Referenced by mode(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setMode_(), embdrv::aardvarkSPIMaster::setMode_(), and test::spiTestDriver::setMode_().
mode() [2/2]
spi::mode embvm::spi::master::mode (spi::mode mode) inline
Set the SPI bus mode.
Derived classes must implement the setMode_() function, which is reponsible for configuring the target hardware.
Parameters
mode The desired SPI bus mode.
Returns
The new SPI bus mode.
References mode(), mode_, and setMode_().
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
order() [1/2]
spi::order embvm::spi::master::order () const inline
Get the current SPI bus byte order.
Returns
The currently configured byte order.
References order_.
Referenced by order(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setOrder_(), embdrv::aardvarkSPIMaster::setOrder_(), and test::spiTestDriver::setOrder_().
order() [2/2]
spi::order embvm::spi::master::order (spi::order order) inline
Set the SPI bus byte order.
Derived classes must implement the setOrder_() function, which is reponsible for configuring the target hardware.
Parameters
order The desired byte ordering.
Returns
The new byte ordering.
References order(), order_, and setOrder_().
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
setMode_()
virtual void embvm::spi::master::setMode_ (spi::mode mode) protected pure virtual
Set the SPI bus mode.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the new mode.
Parameters
mode The desired byte ordering.
Implemented in test::spiTestDriver, embdrv::aardvarkSPIMaster, and embvm::spi::activeMaster< TQueueSize, TLock, TCond >.
Referenced by mode().
setOrder_()
virtual void embvm::spi::master::setOrder_ (spi::order order) protected pure virtual
Set the SPI bus byte order.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the new byte ordering.
Parameters
order The desired byte ordering.
Implemented in test::spiTestDriver, embdrv::aardvarkSPIMaster, and embvm::spi::activeMaster< TQueueSize, TLock, TCond >.
Referenced by order().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void embvm::spi::master::start_ () override protected pure virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in test::spiTestDriver, embdrv::aardvarkSPIMaster, and embvm::spi::activeMaster< TQueueSize, TLock, TCond >.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void embvm::spi::master::stop_ () override protected pure virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in test::spiTestDriver, embdrv::aardvarkSPIMaster, and embvm::spi::activeMaster< TQueueSize, TLock, TCond >.
transfer_()
embvm::comm::status embvm::spi::master::transfer_ (const spi::op_t & op, const cb_t & cb) override protected pure virtual
type()
static constexpr embvm::DriverType embvm::spi::master::type () inline static
SPI Driver Type ID.
Returns
SPI type ID.
References embvm::SPI.
Member Data Documentation
mode_
spi::mode embvm::spi::master::mode_ = spi::mode::mode0 protected
Stores the active SPI mode configuration.
Referenced by embdrv::aardvarkSPIMaster::configure_(), mode(), and embdrv::aardvarkSPIMaster::setMode_().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
order_
spi::order embvm::spi::master::order_ = spi::order::msbFirst protected
Stores the active SPI byte ordering.
Referenced by embdrv::aardvarkSPIMaster::configure_(), order(), and embdrv::aardvarkSPIMaster::setOrder_().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
The documentation for this class was generated from the following files:
src/core/driver/spi.hpp
src/core/driver/internal/spi.cpp