Embedded Artistry Framework: src/stdlibs/libc/src/string/strndup.c File Reference
strndup.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
Functions
char * strndup (const char *str, size_t n)
Duplicate n bytes of the passed in string str.
Function Documentation
strndup()
char* strndup (const char * str, size_t n)
Duplicate n bytes of the passed in string str.
strndup is similar to
See also
strdup, but copies at most n bytes. If str is longer than n, only n bytes are copied, and a terminating null byte ('\0') is added.
Parameters
str a pointer to a string to duplicate
n maximum number of bytes to copy
Returns
a pointer to the duplicated string on success. NULL if insufficient memory was available, with errno set to indicate cause of error.
References malloc(), memcpy(), n, and NULL.
Referenced by strndup_test().