Embedded Artistry Framework: src/processors/arm/nordic/freertos/nrf52/port_cmsis.c File Reference
port_cmsis.c File Reference
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portCORTEX_M4_r0p1_ID (0x410FC241UL)
#define portFIRST_USER_INTERRUPT_NUMBER (16)
#define portMAX_8_BIT_VALUE ((uint8_t)0xff)
#define portTOP_BIT_OF_BYTE ((uint8_t)0x80)
#define portINITIAL_XPSR (((xPSR_Type){.b.T = 1}).w)
#define portINITIAL_EXEC_RETURN (0xfffffffd)
#define portTASK_RETURN_ADDRESS prvTaskExitError
Functions
void vPortSetupTimerInterrupt (void)
void xPortSysTickHandler (void)
void vPortStartFirstTask (void)
static void vPortEnableVFP (void)
static void prvTaskExitError (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
Variables
static UBaseType_t uxCriticalNesting = 0
Macro Definition Documentation
portCORTEX_M4_r0p1_ID
#define portCORTEX_M4_r0p1_ID (0x410FC241UL)
portFIRST_USER_INTERRUPT_NUMBER
#define portFIRST_USER_INTERRUPT_NUMBER (16)
portINITIAL_EXEC_RETURN
#define portINITIAL_EXEC_RETURN (0xfffffffd)
portINITIAL_XPSR
#define portINITIAL_XPSR (((xPSR_Type){.b.T = 1}).w)
portMAX_8_BIT_VALUE
#define portMAX_8_BIT_VALUE ((uint8_t)0xff)
portTASK_RETURN_ADDRESS
#define portTASK_RETURN_ADDRESS prvTaskExitError
portTOP_BIT_OF_BYTE
#define portTOP_BIT_OF_BYTE ((uint8_t)0x80)
Function Documentation
prvTaskExitError()
static void prvTaskExitError (void) static
References portDISABLE_INTERRUPTS, UL, and uxCriticalNesting.
Referenced by xPortStartScheduler().
pxPortInitialiseStack()
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
References portINITIAL_EXEC_RETURN, portINITIAL_XPSR, and portTASK_RETURN_ADDRESS.
vPortEnableVFP()
static void vPortEnableVFP (void) static
Referenced by xPortStartScheduler().
vPortEndScheduler()
void vPortEndScheduler (void)
References UL, and uxCriticalNesting.
vPortEnterCritical()
void vPortEnterCritical (void)
References portDISABLE_INTERRUPTS, and uxCriticalNesting.
vPortExitCritical()
void vPortExitCritical (void)
References portENABLE_INTERRUPTS, portPendSVSchedule, and uxCriticalNesting.
vPortSetupTimerInterrupt()
void vPortSetupTimerInterrupt (void)
References configKERNEL_INTERRUPT_PRIORITY, configSYSTICK_CLOCK_HZ, configTICK_RATE_HZ, portNVIC_SYSTICK_CLK_BIT, ROUNDED_DIV, and UL.
vPortStartFirstTask()
void vPortStartFirstTask (void)
xPortStartScheduler()
BaseType_t xPortStartScheduler (void)
References configKERNEL_INTERRUPT_PRIORITY, configMAX_SYSCALL_INTERRUPT_PRIORITY, portCORTEX_M4_r0p1_ID, portMAX_8_BIT_VALUE, portTOP_BIT_OF_BYTE, prvTaskExitError(), uxCriticalNesting, vPortEnableVFP(), vPortSetupTimerInterrupt(), and vPortStartFirstTask().
xPortSysTickHandler()
void xPortSysTickHandler (void)
References portCLEAR_INTERRUPT_MASK_FROM_ISR, and portSET_INTERRUPT_MASK_FROM_ISR.
Variable Documentation
uxCriticalNesting
UBaseType_t uxCriticalNesting = 0 static
Referenced by prvTaskExitError(), vPortEndScheduler(), vPortEnterCritical(), vPortExitCritical(), and xPortStartScheduler().