Embedded Artistry Framework: src/stdlibs/libmemory/test/support/memory.h File Reference
memory.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
Functions
void allocate_memory (void)
uintptr_t block_start_addr (void)
size_t block_size (void)
uintptr_t block_end_addr (void)
bool memory_allocated (void)
Function Documentation
allocate_memory()
void allocate_memory (void)
References allocated, malloc_addblock(), mem_block, and memblock_size.
Referenced by aligned_malloc_test(), main(), and malloc_test().
block_end_addr()
uintptr_t block_end_addr (void)
References mem_block_addr_end.
Referenced by aligned_malloc_test(), and malloc_test().
block_size()
size_t block_size (void)
References memblock_size.
Referenced by aligned_malloc_test(), and malloc_test().
block_start_addr()
uintptr_t block_start_addr (void)
References mem_block_addr.
Referenced by aligned_malloc_test(), and malloc_test().
memory_allocated()
bool memory_allocated (void)
References allocated.
Referenced by aligned_malloc_test(), and malloc_test().