Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_floorl.c File Reference
s_floorl.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include <stdint.h>
#include "fpmath.h"
#include "math_private.h"
Macros
#define MANH_SIZE LDBL_MANH_SIZE
#define INC_MANH(u, c)
Functions
OLM_DLLEXPORT long double floorl (long double x)
Variables
static const long double huge = 1.0e300
Macro Definition Documentation
INC_MANH
#define INC_MANH (u, c)
Value:
do {                    \
    uint64_t o = u.bits.manh;               \
    u.bits.manh += (c);                 \
    if (u.bits.manh < o) {                  \
        u.bits.exp++;                   \
        u.bits.manh |= 1llu << (LDBL_MANH_SIZE - 1);    \
    }                           \
} while (0)
MANH_SIZE
#define MANH_SIZE LDBL_MANH_SIZE
Function Documentation
floorl()
OLM_DLLEXPORT long double floorl (long double x)
References IEEEl2bits::e, huge, INC_MANH, LDBL_MANT_DIG, LDBL_MAX_EXP, MANH_SIZE, and u.
Referenced by expl(), expm1l(), lgammal_r(), powl(), reducl(), roundl(), sin_pi(), and tgammal().
Variable Documentation
huge
const long double huge = 1.0e300 static
Referenced by floorl().