Embedded Artistry Framework: src/drivers/aardvark/vendor/aardvark.c File Reference
aardvark.c File Reference
#include "aardvark.h"
Macros
#define AA_CFILE_VERSION 0x050a /* v5.10 */
#define AA_REQ_SW_VERSION 0x050a /* v5.10 */
#define API_NAME "aardvark"
#define API_DEBUG AA_DEBUG
#define API_OK AA_OK
#define API_UNABLE_TO_LOAD_LIBRARY AA_UNABLE_TO_LOAD_LIBRARY
#define API_INCOMPATIBLE_LIBRARY AA_INCOMPATIBLE_LIBRARY
#define API_UNABLE_TO_LOAD_FUNCTION AA_UNABLE_TO_LOAD_FUNCTION
#define API_HEADER_VERSION AA_HEADER_VERSION
#define API_REQ_SW_VERSION AA_REQ_SW_VERSION
Functions
static void * _loadFunction (const char *name, int *result)
int aa_find_devices (int num_devices, u16 *devices)
int aa_find_devices_ext (int num_devices, u16 *devices, int num_ids, u32 *unique_ids)
Aardvark aa_open (int port_number)
Aardvark aa_open_ext (int port_number, AardvarkExt *aa_ext)
int aa_close (Aardvark aardvark)
int aa_port (Aardvark aardvark)
int aa_features (Aardvark aardvark)
u32 aa_unique_id (Aardvark aardvark)
const char * aa_status_string (int status)
int aa_log (Aardvark aardvark, int level, int handle)
int aa_version (Aardvark aardvark, AardvarkVersion *version)
int aa_configure (Aardvark aardvark, AardvarkConfig config)
int aa_target_power (Aardvark aardvark, u08 power_mask)
u32 aa_sleep_ms (u32 milliseconds)
int aa_async_poll (Aardvark aardvark, int timeout)
int aa_i2c_free_bus (Aardvark aardvark)
int aa_i2c_bitrate (Aardvark aardvark, int bitrate_khz)
int aa_i2c_bus_timeout (Aardvark aardvark, u16 timeout_ms)
int aa_i2c_read (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, u08 *data_in)
int aa_i2c_read_ext (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, u08 *data_in, u16 *num_read)
int aa_i2c_write (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, const u08 *data_out)
int aa_i2c_write_ext (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, const u08 *data_out, u16 *num_written)
int aa_i2c_write_read (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 out_num_bytes, const u08 *out_data, u16 *num_written, u16 in_num_bytes, u08 *in_data, u16 *num_read)
int aa_i2c_slave_enable (Aardvark aardvark, u08 addr, u16 maxTxBytes, u16 maxRxBytes)
int aa_i2c_slave_disable (Aardvark aardvark)
int aa_i2c_slave_set_response (Aardvark aardvark, u08 num_bytes, const u08 *data_out)
int aa_i2c_slave_write_stats (Aardvark aardvark)
int aa_i2c_slave_read (Aardvark aardvark, u08 *addr, u16 num_bytes, u08 *data_in)
int aa_i2c_slave_write_stats_ext (Aardvark aardvark, u16 *num_written)
int aa_i2c_slave_read_ext (Aardvark aardvark, u08 *addr, u16 num_bytes, u08 *data_in, u16 *num_read)
int aa_i2c_monitor_enable (Aardvark aardvark)
int aa_i2c_monitor_disable (Aardvark aardvark)
int aa_i2c_monitor_read (Aardvark aardvark, u16 num_bytes, u16 *data)
int aa_i2c_pullup (Aardvark aardvark, u08 pullup_mask)
int aa_spi_bitrate (Aardvark aardvark, int bitrate_khz)
int aa_spi_configure (Aardvark aardvark, AardvarkSpiPolarity polarity, AardvarkSpiPhase phase, AardvarkSpiBitorder bitorder)
int aa_spi_write (Aardvark aardvark, u16 out_num_bytes, const u08 *data_out, u16 in_num_bytes, u08 *data_in)
int aa_spi_slave_enable (Aardvark aardvark)
int aa_spi_slave_disable (Aardvark aardvark)
int aa_spi_slave_set_response (Aardvark aardvark, u08 num_bytes, const u08 *data_out)
int aa_spi_slave_read (Aardvark aardvark, u16 num_bytes, u08 *data_in)
int aa_spi_master_ss_polarity (Aardvark aardvark, AardvarkSpiSSPolarity polarity)
int aa_gpio_direction (Aardvark aardvark, u08 direction_mask)
int aa_gpio_pullup (Aardvark aardvark, u08 pullup_mask)
int aa_gpio_get (Aardvark aardvark)
int aa_gpio_set (Aardvark aardvark, u08 value)
int aa_gpio_change (Aardvark aardvark, u16 timeout)
Variables
static int(* c_aa_find_devices)(int, u16 *)=0
static int(* c_aa_find_devices_ext)(int, u16 *, int, u32 *)=0
static Aardvark(* c_aa_open)(int)=0
static Aardvark(* c_aa_open_ext)(int, AardvarkExt *)=0
static int(* c_aa_close)(Aardvark)=0
static int(* c_aa_port)(Aardvark)=0
static int(* c_aa_features)(Aardvark)=0
static u32(* c_aa_unique_id)(Aardvark)=0
static const char *(* c_aa_status_string)(int)=0
static int(* c_aa_log)(Aardvark, int, int)=0
static int(* c_aa_version)(Aardvark, AardvarkVersion *)=0
static int(* c_aa_configure)(Aardvark, AardvarkConfig)=0
static int(* c_aa_target_power)(Aardvark, u08)=0
static u32(* c_aa_sleep_ms)(u32)=0
static int(* c_aa_async_poll)(Aardvark, int)=0
static int(* c_aa_i2c_free_bus)(Aardvark)=0
static int(* c_aa_i2c_bitrate)(Aardvark, int)=0
static int(* c_aa_i2c_bus_timeout)(Aardvark, u16)=0
static int(* c_aa_i2c_read)(Aardvark, u16, AardvarkI2cFlags, u16, u08 *)=0
static int(* c_aa_i2c_read_ext)(Aardvark, u16, AardvarkI2cFlags, u16, u08 *, u16 *)=0
static int(* c_aa_i2c_write)(Aardvark, u16, AardvarkI2cFlags, u16, const u08 *)=0
static int(* c_aa_i2c_write_ext)(Aardvark, u16, AardvarkI2cFlags, u16, const u08 *, u16 *)=0
static int(* c_aa_i2c_write_read)(Aardvark, u16, AardvarkI2cFlags, u16, const u08 *, u16 *, u16, u08 *, u16 *)=0
static int(* c_aa_i2c_slave_enable)(Aardvark, u08, u16, u16)=0
static int(* c_aa_i2c_slave_disable)(Aardvark)=0
static int(* c_aa_i2c_slave_set_response)(Aardvark, u08, const u08 *)=0
static int(* c_aa_i2c_slave_write_stats)(Aardvark)=0
static int(* c_aa_i2c_slave_read)(Aardvark, u08 *, u16, u08 *)=0
static int(* c_aa_i2c_slave_write_stats_ext)(Aardvark, u16 *)=0
static int(* c_aa_i2c_slave_read_ext)(Aardvark, u08 *, u16, u08 *, u16 *)=0
static int(* c_aa_i2c_monitor_enable)(Aardvark)=0
static int(* c_aa_i2c_monitor_disable)(Aardvark)=0
static int(* c_aa_i2c_monitor_read)(Aardvark, u16, u16 *)=0
static int(* c_aa_i2c_pullup)(Aardvark, u08)=0
static int(* c_aa_spi_bitrate)(Aardvark, int)=0
static int(* c_aa_spi_configure)(Aardvark, AardvarkSpiPolarity, AardvarkSpiPhase, AardvarkSpiBitorder)=0
static int(* c_aa_spi_write)(Aardvark, u16, const u08 *, u16, u08 *)=0
static int(* c_aa_spi_slave_enable)(Aardvark)=0
static int(* c_aa_spi_slave_disable)(Aardvark)=0
static int(* c_aa_spi_slave_set_response)(Aardvark, u08, const u08 *)=0
static int(* c_aa_spi_slave_read)(Aardvark, u16, u08 *)=0
static int(* c_aa_spi_master_ss_polarity)(Aardvark, AardvarkSpiSSPolarity)=0
static int(* c_aa_gpio_direction)(Aardvark, u08)=0
static int(* c_aa_gpio_pullup)(Aardvark, u08)=0
static int(* c_aa_gpio_get)(Aardvark)=0
static int(* c_aa_gpio_set)(Aardvark, u08)=0
static int(* c_aa_gpio_change)(Aardvark, u16)=0
Macro Definition Documentation
AA_CFILE_VERSION
#define AA_CFILE_VERSION 0x050a /* v5.10 */
AA_REQ_SW_VERSION
#define AA_REQ_SW_VERSION 0x050a /* v5.10 */
API_DEBUG
#define API_DEBUG AA_DEBUG
API_HEADER_VERSION
#define API_HEADER_VERSION AA_HEADER_VERSION
API_INCOMPATIBLE_LIBRARY
#define API_INCOMPATIBLE_LIBRARY AA_INCOMPATIBLE_LIBRARY
API_NAME
#define API_NAME "aardvark"
API_OK
#define API_OK AA_OK
API_REQ_SW_VERSION
#define API_REQ_SW_VERSION AA_REQ_SW_VERSION
API_UNABLE_TO_LOAD_FUNCTION
#define API_UNABLE_TO_LOAD_FUNCTION AA_UNABLE_TO_LOAD_FUNCTION
API_UNABLE_TO_LOAD_LIBRARY
#define API_UNABLE_TO_LOAD_LIBRARY AA_UNABLE_TO_LOAD_LIBRARY
Function Documentation
_loadFunction()
static void* _loadFunction (const char * name, int * result) static
References API_HEADER_VERSION, API_INCOMPATIBLE_LIBRARY, API_OK, API_REQ_SW_VERSION, API_UNABLE_TO_LOAD_FUNCTION, API_UNABLE_TO_LOAD_LIBRARY, and fprintf().
Referenced by aa_async_poll(), aa_close(), aa_configure(), aa_features(), aa_find_devices(), aa_find_devices_ext(), aa_gpio_change(), aa_gpio_direction(), aa_gpio_get(), aa_gpio_pullup(), aa_gpio_set(), aa_i2c_bitrate(), aa_i2c_bus_timeout(), aa_i2c_free_bus(), aa_i2c_monitor_disable(), aa_i2c_monitor_enable(), aa_i2c_monitor_read(), aa_i2c_pullup(), aa_i2c_read(), aa_i2c_read_ext(), aa_i2c_slave_disable(), aa_i2c_slave_enable(), aa_i2c_slave_read(), aa_i2c_slave_read_ext(), aa_i2c_slave_set_response(), aa_i2c_slave_write_stats(), aa_i2c_slave_write_stats_ext(), aa_i2c_write(), aa_i2c_write_ext(), aa_i2c_write_read(), aa_log(), aa_open(), aa_open_ext(), aa_port(), aa_sleep_ms(), aa_spi_bitrate(), aa_spi_configure(), aa_spi_master_ss_polarity(), aa_spi_slave_disable(), aa_spi_slave_enable(), aa_spi_slave_read(), aa_spi_slave_set_response(), aa_spi_write(), aa_status_string(), aa_target_power(), aa_unique_id(), and aa_version().
aa_async_poll()
int aa_async_poll (Aardvark aardvark, int timeout)
References _loadFunction(), and c_aa_async_poll.
Referenced by dump().
aa_close()
int aa_close (Aardvark aardvark)
References _loadFunction(), and c_aa_close.
Referenced by main(), and embdrv::aardvarkAdapter::stop_().
aa_configure()
int aa_configure (Aardvark aardvark, AardvarkConfig config)
References _loadFunction(), and c_aa_configure.
Referenced by main(), and embdrv::aardvarkAdapter::mode().
aa_features()
int aa_features (Aardvark aardvark)
References _loadFunction(), and c_aa_features.
aa_find_devices()
int aa_find_devices (int num_devices, u16 * devices)
References _loadFunction(), and c_aa_find_devices.
aa_find_devices_ext()
int aa_find_devices_ext (int num_devices, u16 * devices, int num_ids, u32 * unique_ids)
References _loadFunction(), and c_aa_find_devices_ext.
aa_gpio_change()
int aa_gpio_change (Aardvark aardvark, u16 timeout)
References _loadFunction(), and c_aa_gpio_change.
Referenced by main().
aa_gpio_direction()
int aa_gpio_direction (Aardvark aardvark, u08 direction_mask)
References _loadFunction(), and c_aa_gpio_direction.
Referenced by main(), and embdrv::aardvarkGPIOOutput< 5 >::start_().
aa_gpio_get()
int aa_gpio_get (Aardvark aardvark)
References _loadFunction(), and c_aa_gpio_get.
Referenced by embdrv::aardvarkGPIOInput< 4 >::get(), and main().
aa_gpio_pullup()
int aa_gpio_pullup (Aardvark aardvark, u08 pullup_mask)
References _loadFunction(), and c_aa_gpio_pullup.
Referenced by main(), and embdrv::aardvarkAdapter::pullup().
aa_gpio_set()
int aa_gpio_set (Aardvark aardvark, u08 value)
References _loadFunction(), and c_aa_gpio_set.
Referenced by main(), and embdrv::aardvarkGPIOOutput< 5 >::set().
aa_i2c_bitrate()
int aa_i2c_bitrate (Aardvark aardvark, int bitrate_khz)
References _loadFunction(), and c_aa_i2c_bitrate.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), and main().
aa_i2c_bus_timeout()
int aa_i2c_bus_timeout (Aardvark aardvark, u16 timeout_ms)
References _loadFunction(), and c_aa_i2c_bus_timeout.
Referenced by embdrv::aardvarkI2CMaster::configure_(), and main().
aa_i2c_free_bus()
int aa_i2c_free_bus (Aardvark aardvark)
References _loadFunction(), and c_aa_i2c_free_bus.
Referenced by embdrv::aardvarkI2CMaster::process_().
aa_i2c_monitor_disable()
int aa_i2c_monitor_disable (Aardvark aardvark)
References _loadFunction(), and c_aa_i2c_monitor_disable.
aa_i2c_monitor_enable()
int aa_i2c_monitor_enable (Aardvark aardvark)
References _loadFunction(), and c_aa_i2c_monitor_enable.
aa_i2c_monitor_read()
int aa_i2c_monitor_read (Aardvark aardvark, u16 num_bytes, u16 * data)
References _loadFunction(), and c_aa_i2c_monitor_read.
aa_i2c_pullup()
int aa_i2c_pullup (Aardvark aardvark, u08 pullup_mask)
References _loadFunction(), and c_aa_i2c_pullup.
Referenced by embdrv::aardvarkAdapter::i2cPullups(), main(), and embdrv::aardvarkAdapter::targetPower().
aa_i2c_read()
int aa_i2c_read (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, u08 * data_in)
References _loadFunction(), c_aa_i2c_read, and data_in.
Referenced by _readMemory().
aa_i2c_read_ext()
int aa_i2c_read_ext (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, u08 * data_in, u16 * num_read)
References _loadFunction(), c_aa_i2c_read_ext, and data_in.
Referenced by embdrv::aardvarkI2CMaster::process_().
aa_i2c_slave_disable()
int aa_i2c_slave_disable (Aardvark aardvark)
References _loadFunction(), and c_aa_i2c_slave_disable.
Referenced by main().
aa_i2c_slave_enable()
int aa_i2c_slave_enable (Aardvark aardvark, u08 addr, u16 maxTxBytes, u16 maxRxBytes)
References _loadFunction(), and c_aa_i2c_slave_enable.
Referenced by main().
aa_i2c_slave_read()
int aa_i2c_slave_read (Aardvark aardvark, u08 * addr, u16 num_bytes, u08 * data_in)
References _loadFunction(), c_aa_i2c_slave_read, and data_in.
Referenced by dump().
aa_i2c_slave_read_ext()
int aa_i2c_slave_read_ext (Aardvark aardvark, u08 * addr, u16 num_bytes, u08 * data_in, u16 * num_read)
References _loadFunction(), c_aa_i2c_slave_read_ext, and data_in.
aa_i2c_slave_set_response()
int aa_i2c_slave_set_response (Aardvark aardvark, u08 num_bytes, const u08 * data_out)
References _loadFunction(), and c_aa_i2c_slave_set_response.
Referenced by main().
aa_i2c_slave_write_stats()
int aa_i2c_slave_write_stats (Aardvark aardvark)
References _loadFunction(), and c_aa_i2c_slave_write_stats.
Referenced by dump().
aa_i2c_slave_write_stats_ext()
int aa_i2c_slave_write_stats_ext (Aardvark aardvark, u16 * num_written)
References _loadFunction(), and c_aa_i2c_slave_write_stats_ext.
aa_i2c_write()
int aa_i2c_write (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, const u08 * data_out)
References _loadFunction(), and c_aa_i2c_write.
Referenced by _readMemory(), _writeMemory(), and flash_lights().
aa_i2c_write_ext()
int aa_i2c_write_ext (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 num_bytes, const u08 * data_out, u16 * num_written)
References _loadFunction(), and c_aa_i2c_write_ext.
Referenced by embdrv::aardvarkI2CMaster::process_().
aa_i2c_write_read()
int aa_i2c_write_read (Aardvark aardvark, u16 slave_addr, AardvarkI2cFlags flags, u16 out_num_bytes, const u08 * out_data, u16 * num_written, u16 in_num_bytes, u08 * in_data, u16 * num_read)
References _loadFunction(), and c_aa_i2c_write_read.
Referenced by embdrv::aardvarkI2CMaster::process_().
aa_log()
int aa_log (Aardvark aardvark, int level, int handle)
References _loadFunction(), and c_aa_log.
Referenced by main().
aa_open()
Aardvark aa_open (int port_number)
References _loadFunction(), and c_aa_open.
Referenced by main(), and embdrv::aardvarkAdapter::start_().
aa_open_ext()
Aardvark aa_open_ext (int port_number, AardvarkExt * aa_ext)
References _loadFunction(), and c_aa_open_ext.
Referenced by main().
aa_port()
int aa_port (Aardvark aardvark)
References _loadFunction(), and c_aa_port.
aa_sleep_ms()
u32 aa_sleep_ms (u32 milliseconds)
References _loadFunction(), and c_aa_sleep_ms.
Referenced by _writeMemory(), and flash_lights().
aa_spi_bitrate()
int aa_spi_bitrate (Aardvark aardvark, int bitrate_khz)
References _loadFunction(), and c_aa_spi_bitrate.
Referenced by embdrv::aardvarkSPIMaster::baudrate_(), and main().
aa_spi_configure()
int aa_spi_configure (Aardvark aardvark, AardvarkSpiPolarity polarity, AardvarkSpiPhase phase, AardvarkSpiBitorder bitorder)
References _loadFunction(), and c_aa_spi_configure.
Referenced by embdrv::aardvarkSPIMaster::configure_(), and main().
aa_spi_master_ss_polarity()
int aa_spi_master_ss_polarity (Aardvark aardvark, AardvarkSpiSSPolarity polarity)
References _loadFunction(), and c_aa_spi_master_ss_polarity.
aa_spi_slave_disable()
int aa_spi_slave_disable (Aardvark aardvark)
References _loadFunction(), and c_aa_spi_slave_disable.
Referenced by main().
aa_spi_slave_enable()
int aa_spi_slave_enable (Aardvark aardvark)
References _loadFunction(), and c_aa_spi_slave_enable.
Referenced by main().
aa_spi_slave_read()
int aa_spi_slave_read (Aardvark aardvark, u16 num_bytes, u08 * data_in)
References _loadFunction(), c_aa_spi_slave_read, and data_in.
Referenced by dump().
aa_spi_slave_set_response()
int aa_spi_slave_set_response (Aardvark aardvark, u08 num_bytes, const u08 * data_out)
References _loadFunction(), and c_aa_spi_slave_set_response.
Referenced by main().
aa_spi_write()
int aa_spi_write (Aardvark aardvark, u16 out_num_bytes, const u08 * data_out, u16 in_num_bytes, u08 * data_in)
References _loadFunction(), c_aa_spi_write, and data_in.
Referenced by _readMemory(), _writeMemory(), and embdrv::aardvarkSPIMaster::process_().
aa_status_string()
const char* aa_status_string (int status)
References _loadFunction(), and c_aa_status_string.
Referenced by _readMemory(), dump(), and main().
aa_target_power()
int aa_target_power (Aardvark aardvark, u08 power_mask)
References _loadFunction(), and c_aa_target_power.
Referenced by main(), and embdrv::aardvarkAdapter::targetPower().
aa_unique_id()
u32 aa_unique_id (Aardvark aardvark)
References _loadFunction(), and c_aa_unique_id.
aa_version()
int aa_version (Aardvark aardvark, AardvarkVersion * version)
References _loadFunction(), and c_aa_version.
Variable Documentation
c_aa_async_poll
int(* c_aa_async_poll) (Aardvark, int)=0 static
Referenced by aa_async_poll().
c_aa_close
int(* c_aa_close) (Aardvark)=0 static
Referenced by aa_close().
c_aa_configure
int(* c_aa_configure) (Aardvark, AardvarkConfig)=0 static
Referenced by aa_configure().
c_aa_features
int(* c_aa_features) (Aardvark)=0 static
Referenced by aa_features().
c_aa_find_devices
int(* c_aa_find_devices) (int, u16 *)=0 static
Referenced by aa_find_devices().
c_aa_find_devices_ext
int(* c_aa_find_devices_ext) (int, u16 *, int, u32 *)=0 static
Referenced by aa_find_devices_ext().
c_aa_gpio_change
int(* c_aa_gpio_change) (Aardvark, u16)=0 static
Referenced by aa_gpio_change().
c_aa_gpio_direction
int(* c_aa_gpio_direction) (Aardvark, u08)=0 static
Referenced by aa_gpio_direction().
c_aa_gpio_get
int(* c_aa_gpio_get) (Aardvark)=0 static
Referenced by aa_gpio_get().
c_aa_gpio_pullup
int(* c_aa_gpio_pullup) (Aardvark, u08)=0 static
Referenced by aa_gpio_pullup().
c_aa_gpio_set
int(* c_aa_gpio_set) (Aardvark, u08)=0 static
Referenced by aa_gpio_set().
c_aa_i2c_bitrate
int(* c_aa_i2c_bitrate) (Aardvark, int)=0 static
Referenced by aa_i2c_bitrate().
c_aa_i2c_bus_timeout
int(* c_aa_i2c_bus_timeout) (Aardvark, u16)=0 static
Referenced by aa_i2c_bus_timeout().
c_aa_i2c_free_bus
int(* c_aa_i2c_free_bus) (Aardvark)=0 static
Referenced by aa_i2c_free_bus().
c_aa_i2c_monitor_disable
int(* c_aa_i2c_monitor_disable) (Aardvark)=0 static
Referenced by aa_i2c_monitor_disable().
c_aa_i2c_monitor_enable
int(* c_aa_i2c_monitor_enable) (Aardvark)=0 static
Referenced by aa_i2c_monitor_enable().
c_aa_i2c_monitor_read
int(* c_aa_i2c_monitor_read) (Aardvark, u16, u16 *)=0 static
Referenced by aa_i2c_monitor_read().
c_aa_i2c_pullup
int(* c_aa_i2c_pullup) (Aardvark, u08)=0 static
Referenced by aa_i2c_pullup().
c_aa_i2c_read
int(* c_aa_i2c_read) (Aardvark, u16, AardvarkI2cFlags, u16, u08 *)=0 static
Referenced by aa_i2c_read().
c_aa_i2c_read_ext
int(* c_aa_i2c_read_ext) (Aardvark, u16, AardvarkI2cFlags, u16, u08 *, u16 *)=0 static
Referenced by aa_i2c_read_ext().
c_aa_i2c_slave_disable
int(* c_aa_i2c_slave_disable) (Aardvark)=0 static
Referenced by aa_i2c_slave_disable().
c_aa_i2c_slave_enable
int(* c_aa_i2c_slave_enable) (Aardvark, u08, u16, u16)=0 static
Referenced by aa_i2c_slave_enable().
c_aa_i2c_slave_read
int(* c_aa_i2c_slave_read) (Aardvark, u08 *, u16, u08 *)=0 static
Referenced by aa_i2c_slave_read().
c_aa_i2c_slave_read_ext
int(* c_aa_i2c_slave_read_ext) (Aardvark, u08 *, u16, u08 *, u16 *)=0 static
Referenced by aa_i2c_slave_read_ext().
c_aa_i2c_slave_set_response
int(* c_aa_i2c_slave_set_response) (Aardvark, u08, const u08 *)=0 static
Referenced by aa_i2c_slave_set_response().
c_aa_i2c_slave_write_stats
int(* c_aa_i2c_slave_write_stats) (Aardvark)=0 static
Referenced by aa_i2c_slave_write_stats().
c_aa_i2c_slave_write_stats_ext
int(* c_aa_i2c_slave_write_stats_ext) (Aardvark, u16 *)=0 static
Referenced by aa_i2c_slave_write_stats_ext().
c_aa_i2c_write
int(* c_aa_i2c_write) (Aardvark, u16, AardvarkI2cFlags, u16, const u08 *)=0 static
Referenced by aa_i2c_write().
c_aa_i2c_write_ext
int(* c_aa_i2c_write_ext) (Aardvark, u16, AardvarkI2cFlags, u16, const u08 *, u16 *)=0 static
Referenced by aa_i2c_write_ext().
c_aa_i2c_write_read
int(* c_aa_i2c_write_read) (Aardvark, u16, AardvarkI2cFlags, u16, const u08 *, u16 *, u16, u08 *, u16 *)=0 static
Referenced by aa_i2c_write_read().
c_aa_log
int(* c_aa_log) (Aardvark, int, int)=0 static
Referenced by aa_log().
c_aa_open
Aardvark(* c_aa_open) (int)=0 static
Referenced by aa_open().
c_aa_open_ext
Aardvark(* c_aa_open_ext) (int, AardvarkExt *)=0 static
Referenced by aa_open_ext().
c_aa_port
int(* c_aa_port) (Aardvark)=0 static
Referenced by aa_port().
c_aa_sleep_ms
u32(* c_aa_sleep_ms) (u32)=0 static
Referenced by aa_sleep_ms().
c_aa_spi_bitrate
int(* c_aa_spi_bitrate) (Aardvark, int)=0 static
Referenced by aa_spi_bitrate().
c_aa_spi_configure
int(* c_aa_spi_configure) (Aardvark, AardvarkSpiPolarity, AardvarkSpiPhase, AardvarkSpiBitorder)=0 static
Referenced by aa_spi_configure().
c_aa_spi_master_ss_polarity
int(* c_aa_spi_master_ss_polarity) (Aardvark, AardvarkSpiSSPolarity)=0 static
Referenced by aa_spi_master_ss_polarity().
c_aa_spi_slave_disable
int(* c_aa_spi_slave_disable) (Aardvark)=0 static
Referenced by aa_spi_slave_disable().
c_aa_spi_slave_enable
int(* c_aa_spi_slave_enable) (Aardvark)=0 static
Referenced by aa_spi_slave_enable().
c_aa_spi_slave_read
int(* c_aa_spi_slave_read) (Aardvark, u16, u08 *)=0 static
Referenced by aa_spi_slave_read().
c_aa_spi_slave_set_response
int(* c_aa_spi_slave_set_response) (Aardvark, u08, const u08 *)=0 static
Referenced by aa_spi_slave_set_response().
c_aa_spi_write
int(* c_aa_spi_write) (Aardvark, u16, const u08 *, u16, u08 *)=0 static
Referenced by aa_spi_write().
c_aa_status_string
const char*(* c_aa_status_string) (int)=0 static
Referenced by aa_status_string().
c_aa_target_power
int(* c_aa_target_power) (Aardvark, u08)=0 static
Referenced by aa_target_power().
c_aa_unique_id
u32(* c_aa_unique_id) (Aardvark)=0 static
Referenced by aa_unique_id().
c_aa_version
int(* c_aa_version) (Aardvark, AardvarkVersion *)=0 static
Referenced by aa_version().