Embedded Artistry libc: src/gdtoa/src/strtord.c File Reference
strtord.c File Reference
#include "gdtoaimp.h"
Functions
void ULtod (ULong *L, const ULong *bits, Long exp, int k)
int strtord (CONST char *s, char **sp, int rounding, double *d)
Function Documentation
strtord()
int strtord (CONST char * s, char ** sp, int rounding, double * d)
Definition at line 86 of file strtord.c.
 {
     static FPI fpi0 = {53, 1 - 1023 - 53 + 1, 2046 - 1023 - 53 + 1, 1, SI};
     FPI *fpi, fpi1;
     ULong bits[2];
     Long exp;
     int k;
     fpi = &fpi0;
     if(rounding != FPI_Round_near)
     {
         fpi1 = fpi0;
         fpi1.rounding = rounding;
         fpi = &fpi1;
     }
     k = strtodg(s, sp, fpi, &exp, bits);
     ULtod((ULong*)d, bits, exp, k);
     return k;
 }
References fpi1, FPI_Round_near, Long, SI, strtodg(), and ULtod().
ULtod()
void ULtod (ULong * L, const ULong * bits, Long exp, int k)
Definition at line 41 of file strtord.c.
 {
     switch(k & STRTOG_Retmask)
     {
         case STRTOG_NoNumber:
         case STRTOG_Zero:
             L[0] = L[1] = 0;
             break;
         case STRTOG_Denormal:
             L[_1] = bits[0];
             L[_0] = bits[1];
             break;
         case STRTOG_Normal:
         case STRTOG_NaNbits:
             L[_1] = bits[0];
             L[_0] = (bits[1] & (unsigned)~0x100000) | (unsigned)((exp + 0x3ff + 52) << 20);
             break;
         case STRTOG_Infinite:
             L[_0] = 0x7ff00000;
             L[_1] = 0;
             break;
         case STRTOG_NaN:
             L[0] = d_QNAN0;
             L[1] = d_QNAN1;
     }
     if(k & STRTOG_Neg)
     {
         {
             L[_0] |= 0x80000000L;
         }
     }
 }
References STRTOG_Denormal, STRTOG_Infinite, STRTOG_NaN, STRTOG_NaNbits, STRTOG_Neg, STRTOG_NoNumber, STRTOG_Normal, STRTOG_Retmask, and STRTOG_Zero.
Referenced by strtod(), strtoId(), strtopd(), and strtord().