Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_ilogb.c File Reference
s_ilogb.c File Reference
#include "cdefs-compat.h"
#include <limits.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT int ilogb (double x)
Function Documentation
ilogb()
OLM_DLLEXPORT int ilogb (double x)
References EXTRACT_WORDS, FP_ILOGB0, FP_ILOGBNAN, and INT_MAX.
Referenced by check_float_internal(), fma(), and ilogb_test().