Embedded Artistry Framework: src/stdlibs/libc/openlibm/ld80/s_log1pl.c File Reference
s_log1pl.c File Reference
#include <openlibm_math.h>
#include "math_private.h"
Macros
#define SQRTH 0.70710678118654752440L
Functions
long double log1pl (long double xm1)
Variables
static long double P []
static long double Q []
static long double R [4]
static long double S [4]
static const long double C1 = 6.9314575195312500000000E-1L
static const long double C2 = 1.4286068203094172321215E-6L
Macro Definition Documentation
SQRTH
#define SQRTH 0.70710678118654752440L
Function Documentation
log1pl()
long double log1pl (long double xm1)
References __p1evll(), __polevll(), C1, C2, IEEEl2bits::e, frexpl(), INFINITY, isnan, NAN, P, Q, R, S, SQRTH, and z.
Referenced by acoshl(), asinhl(), and atanhl().
Variable Documentation
C1
const long double C1 = 6.9314575195312500000000E-1L static
Referenced by log1pl().
C2
const long double C2 = 1.4286068203094172321215E-6L static
Referenced by log1pl().
P
long double P[] static
Initial value:
= {
 4.5270000862445199635215E-5L,
 4.9854102823193375972212E-1L,
 6.5787325942061044846969E0L,
 2.9911919328553073277375E1L,
 6.0949667980987787057556E1L,
 5.7112963590585538103336E1L,
 2.0039553499201281259648E1L,
}
Referenced by log1pl().
Q
long double Q[] static
Initial value:
= {
 1.5062909083469192043167E1L,
 8.3047565967967209469434E1L,
 2.2176239823732856465394E2L,
 3.0909872225312059774938E2L,
 2.1642788614495947685003E2L,
 6.0118660497603843919306E1L,
}
Referenced by log1pl().
R
long double R[4] static
Initial value:
= {
 1.9757429581415468984296E-3L,
-7.1990767473014147232598E-1L,
 1.0777257190312272158094E1L,
-3.5717684488096787370998E1L,
}
Referenced by log1pl().
S
long double S[4] static
Initial value:
= {
-2.6201045551331104417768E1L,
 1.9361891836232102174846E2L,
-4.2861221385716144629696E2L,
}
Referenced by log1pl().