Embedded Artistry Framework: src/stdlibs/libc/test/stdlib/strtod.c File Reference
strtod.c File Reference
#include "stdlib_tests.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <cmocka.h>
Macros
#define length(x) (sizeof(x) / sizeof *(x))
Functions
static void strtod_test (void **state)
int strtod_tests (void)
Variables
struct {
char * s
double f
} t []
static const double epsilon = (double)0.000000000000001
Macro Definition Documentation
length
#define length (x) (sizeof(x) / sizeof *(x))
Function Documentation
strtod_test()
static void strtod_test (void ** state) static
References epsilon, fabs(), length, p, s, strtod(), and t.
Referenced by strtod_tests().
strtod_tests()
int strtod_tests (void)
References NULL, and strtod_test().
Referenced by stdlib_tests().
Variable Documentation
epsilon
const double epsilon = (double)0.000000000000001 static
Referenced by strtod_test().
t
struct { ... } t[]
Referenced by strtod_test().