Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_hypotl.c File Reference
e_hypotl.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "fpmath.h"
#include "math_private.h"
Macros
#define GET_LDBL_MAN(h, l, v)
#define GET_HIGH_WORD(i, v) GET_LDBL_EXPSIGN(i, v)
#define SET_HIGH_WORD(v, i) SET_LDBL_EXPSIGN(v, i)
#define DESW(exp) (exp) /* delta expsign word */
#define ESW(exp) (MAX_EXP - 1 + (exp)) /* expsign word */
#define MANT_DIG LDBL_MANT_DIG
#define MAX_EXP LDBL_MAX_EXP
Typedefs
typedef u_int32_t man_t
Functions
OLM_DLLEXPORT long double hypotl (long double x, long double y)
Macro Definition Documentation
DESW
#define DESW (exp) (exp) /* delta expsign word */
ESW
#define ESW (exp) (MAX_EXP - 1 + (exp)) /* expsign word */
GET_HIGH_WORD
#define GET_HIGH_WORD (i, v) GET_LDBL_EXPSIGN(i, v)
GET_LDBL_MAN
#define GET_LDBL_MAN (h, l, v)
Value:
do {    \
    union IEEEl2bits uv;        \
                    \
    uv.e = v;           \
    h = uv.bits.manh;       \
    l = uv.bits.manl;       \
} while (0)
MANT_DIG
#define MANT_DIG LDBL_MANT_DIG
MAX_EXP
#define MAX_EXP LDBL_MAX_EXP
SET_HIGH_WORD
#define SET_HIGH_WORD (v, i) SET_LDBL_EXPSIGN(v, i)
Typedef Documentation
man_t
typedef u_int32_t man_t
Function Documentation
hypotl()
OLM_DLLEXPORT long double hypotl (long double x, long double y)
References a, b, IEEEl2bits::bits, DESW, IEEEl2bits::e, ESW, fabsl(), GET_HIGH_WORD, GET_LDBL_MAN, high, k, LDBL_NBIT, MANT_DIG, MAX_EXP, SET_HIGH_WORD, sqrtl(), t1, t2, and w.
Referenced by cabsl(), and csqrtl().