Embedded Artistry Framework: embvm::timer::Timer Class Reference
embvm::timer::Timer Class Reference abstract
This class provides generic Timer interface definitions.
#include <timer.hpp>
Public Member Functions
Timer ()
Default constructor.
Timer (const char *name)
Construct an Timer with a C-string name.
Timer (const std::string &name)
Construct an Timer with a std::string name.
Timer (const std::string_view &name)
Construct an Timer with a std::string_view name.
timer_period_t period () const
Get the current timer period.
timer_period_t period (timer_period_t period)
Set the timer period.
virtual void registerCallback (const timer::cb_t &cb)=0
Register a timer callback.
virtual void registerCallback (timer::cb_t &&cb)=0
Register a timer callback.
virtual void restart (const timer_period_t period)
Restart the timer with a specific period.
void restart (const timer_period_t::rep period)
Restart the timer with a specific period.
void restart ()
Restart the timer with the currently configured period.
virtual timer::state state () const
Check the state of the timer.
virtual timer::config config () const
Check the configuration of the timer.
virtual timer::config config (timer::config c)
Set the timer configuration.
virtual timer_period_t count ()=0
Read the current timer count.
void start ()
Start the driver.
void stop ()
Stop the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
Static Public Member Functions
static constexpr embvm::DriverType type ()
Timer Driver Type ID.
Protected Member Functions
~Timer () override
Default destructor.
void start_ () override=0
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () override=0
Derived classes override the start_ method to control driver-specific startup behavior.
Protected Attributes
timer_period_t period_ {0}
The configured timer period.
timer::state state_ = timer::state::stopped
The current state of the timer.
timer::config config_ = timer::config::oneshot
The timer configuratoin.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Detailed Description
This class provides generic Timer interface definitions.
The Timer class defines the common interfaces for Timer drivers. This class can be inherited to provide specific Timer implementations.
Timers can be used with the embvm::TimerManager<> class to provide software timer support.
Define a Timer driver
To create a specialized Timer driver, derive from the Timer object:
class SimulatorTimer final : public timer::Timer
{ ... };
Derived classes must implement the following interfaces:
registerCallback()
Derived classes must also implement pure virtual embvm::DriverBase functions:
start_()
stop_()
The start_() function must implement the steps for starting the timer hardware. The stop_() function is responsible for stopping the timer hardware.
Using a Timer driver
Timers should be configured with a period(). If the default one-shot configuration is not desired, the config() can be used to change the timer operational mode.
A callback should be registered with the registerCallback() function. When the timer expires, the callback will be invoked. If the timer is configured as a one-shot, the timer will remain expired until start() or restart() is called. If a timer is configured as periodic, the timer will reload the period and re-arm itself.
A timer can be restarted (even while running) using the existing period or with a new period.
Timers can be stopped while they are running using the stop() function.
Software Timers with embvm::TimerManager<>
Timers can be used with the embvm::TimerManager<> class to provide software timer support.
SimulatorTimer timer;
embvm::TimerManager tm(timer);
The embvm::TimerManager will use the timer hardware driver as a master timer, enabling multiple software timers to be created and used while consuming only a single hardware resource.
Constructor & Destructor Documentation
Timer() [1/4]
embvm::timer::Timer::Timer () inline
Default constructor.
Initializes the Timer instance with a generic name.
Timer() [2/4]
embvm::timer::Timer::Timer (const char * name) inline explicit
Construct an Timer with a C-string name.
Initializes the Timer instance with a name.
Parameters
name The name of the Timer instance.
Timer() [3/4]
embvm::timer::Timer::Timer (const std::string & name) inline explicit
Construct an Timer with a std::string name.
Initializes the Timer instance with a name.
Parameters
name The name of the Timer instance. Timer() uses a std::string_view, so the std::string must remain valid
Timer() [4/4]
embvm::timer::Timer::Timer (const std::string_view & name) inline explicit
Construct an Timer with a std::string_view name.
Initializes the Timer instance with a name.
Parameters
name The name of the Timer instance.
~Timer()
Timer::~Timer () override protected default
Default destructor.
Member Function Documentation
config() [1/2]
virtual timer::config embvm::timer::Timer::config () const inline virtual
Check the configuration of the timer.
Returns
the current timer configuration.
References config_.
Referenced by embdrv::SimulatorTimer::SimulatorTimer().
config() [2/2]
virtual timer::config embvm::timer::Timer::config (timer::config c) inline virtual
Set the timer configuration.
Parameters
c The desired timer configuration (periodic or oneshot).
Returns
the current timer configuration.
References config_.
count()
virtual timer_period_t embvm::timer::Timer::count () pure virtual
Read the current timer count.
Returns
the current count of the timer
Implemented in embdrv::SimulatorTimer.
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
period() [1/2]
timer_period_t embvm::timer::Timer::period () const inline
Get the current timer period.
Returns
the currently configured timer period.
References period_.
Referenced by period(), restart(), and embdrv::SimulatorTimer::SimulatorTimer().
period() [2/2]
timer_period_t embvm::timer::Timer::period (timer_period_t period) inline
Set the timer period.
If the timer is currently running, this call has no effect. Use restart() instead.
Parameters
period the desired timer period.
Returns
the currently configured timer period.
References period(), and period_.
registerCallback() [1/2]
virtual void embvm::timer::Timer::registerCallback (const timer::cb_t & cb) pure virtual
Register a timer callback.
The timer callback function is called whenever the timer expires.
Derived classes must implement this function. Derived classes can choose to support either a single callback or multiple callbacks.
Parameters
cb A callback to invoke when the timer expires.
Implemented in embdrv::SimulatorTimer.
registerCallback() [2/2]
virtual void embvm::timer::Timer::registerCallback (timer::cb_t && cb) pure virtual
Register a timer callback.
The timer callback function is called whenever the timer expires.
Derived classes must implement this function. Derived classes can choose to support either a single callback or multiple callbacks.
Parameters
cb A callback to invoke when the timer expires.
Implemented in embdrv::SimulatorTimer.
restart() [1/3]
virtual void embvm::timer::Timer::restart (const timer_period_t period) inline virtual
Restart the timer with a specific period.
Parameters
period The desired timer period to reset the timer to use. Accepts a std::chrono value.
References period(), period_, embvm::DriverBase::start(), and embvm::DriverBase::stop().
restart() [2/3]
void embvm::timer::Timer::restart (const timer_period_t::rep period) inline
Restart the timer with a specific period.
Parameters
period The desired timer period to reset the timer to use. Accepts an integral count representing the period in microseonds.
References period(), and restart().
restart() [3/3]
void embvm::timer::Timer::restart () inline
Restart the timer with the currently configured period.
References period_.
Referenced by restart().
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
void embvm::timer::Timer::start_ () override protected pure virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in embdrv::SimulatorTimer.
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
state()
virtual timer::state embvm::timer::Timer::state () const inline virtual
Check the state of the timer.
Returns
the current timer state.
References state_.
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
void embvm::timer::Timer::stop_ () override protected pure virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::DriverBase.
Implemented in embdrv::SimulatorTimer.
type()
static constexpr embvm::DriverType embvm::timer::Timer::type () inline static
Timer Driver Type ID.
Returns
Timer type ID.
References embvm::TIMER.
Member Data Documentation
config_
timer::config embvm::timer::Timer::config_ = timer::config::oneshot protected
The timer configuratoin.
Referenced by config(), embdrv::SimulatorTimer::SimulatorTimer(), and embdrv::SimulatorTimer::timer_thread().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
period_
timer_period_t embvm::timer::Timer::period_ {0} protected
The configured timer period.
Referenced by period(), restart(), embdrv::SimulatorTimer::SimulatorTimer(), and embdrv::SimulatorTimer::timer_thread().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
state_
timer::state embvm::timer::Timer::state_ = timer::state::stopped protected
The current state of the timer.
Referenced by embdrv::SimulatorTimer::start_(), state(), embdrv::SimulatorTimer::stop_(), and embdrv::SimulatorTimer::timer_thread().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
The documentation for this class was generated from the following files:
src/core/driver/timer.hpp
src/core/driver/internal/timer.cpp