Embedded Artistry libc: src/gdtoa/src/hd_init.c File Reference
hd_init.c File Reference
#include "gdtoaimp.h"
Macros
#define USC (unsigned char *)
Functions
static void htinit (unsigned char *h, unsigned char *s, int inc)
void hexdig_init_D2A (Void)
Variables
unsigned char hexdig [256]
Macro Definition Documentation
USC
#define USC (unsigned char *)
Referenced by hexdig_init_D2A().
Function Documentation
hexdig_init_D2A()
void hexdig_init_D2A (Void)
Definition at line 49 of file hd_init.c.
References hexdig, htinit(), and USC.
Referenced by gethex(), and hexnan().
 {
 #define USC (unsigned char *)
     htinit(hexdig, USC "0123456789", 0x10);
     htinit(hexdig, USC "abcdef", 0x10 + 10);
     htinit(hexdig, USC "ABCDEF", 0x10 + 10);
     }
htinit()
static void htinit (unsigned char * h, unsigned char * s, int inc) static
Definition at line 40 of file hd_init.c.
Referenced by hexdig_init_D2A().
 {
     int i, j;
     for(i = 0; (j = s[i]) !=0; i++)
         h[j] = i + inc;
     }
Variable Documentation
hexdig
unsigned char hexdig[256]
Definition at line 34 of file hd_init.c.
Referenced by hexdig_init_D2A().