Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_frexpl.c File Reference
s_frexpl.c File Reference
#include <float.h>
#include <openlibm_math.h>
#include "fpmath.h"
#include "math_private.h"
Functions
OLM_DLLEXPORT long double frexpl (long double x, int *ex)
Function Documentation
frexpl()
OLM_DLLEXPORT long double frexpl (long double x, int * ex)
References u.
Referenced by fmal(), log10l(), log1pl(), log2l(), logl(), powil(), and powl().