Embedded Artistry Framework: src/stdlibs/libc/src/ctype/isalnum.c File Reference
isalnum.c File Reference
#include <ctype.h>
Functions
int isalnum (int c)
Checks if the given character is an alphanumeric character.
Function Documentation
isalnum()
int isalnum (int ch)
Checks if the given character is an alphanumeric character.
Checks if the given character is an alphanumeric character using the default locale. The following characters are alphanumeric:
digits (0123456789)
uppercase letters (ABCDEFGHIJKLMNOPQRSTUVWXYZ)
lowercase letters (abcdefghijklmnopqrstuvwxyz)
The behavior is undefined if the value of ch is not representable as unsigned char and is not equal to EOF.
Parameters
ch The character to classify
Returns
Non-zero value if the character is an alphanumeric character, 0 otherwise.
References isalpha(), and isdigit().
Referenced by bad_input(), good_input(), and ispunct().