Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_rem_pio2.c File Reference
e_rem_pio2.c File Reference
#include "cdefs-compat.h"
#include <float.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
__inline int __ieee754_rem_pio2 (double x, double *y)
Variables
static const double zero = 0.00000000000000000000e+00
static const double two24 = 1.67772160000000000000e+07
static const double invpio2 = 6.36619772367581382433e-01
static const double pio2_1 = 1.57079632673412561417e+00
static const double pio2_1t = 6.07710050650619224932e-11
static const double pio2_2 = 6.07710050630396597660e-11
static const double pio2_2t = 2.02226624879595063154e-21
static const double pio2_3 = 2.02226624871116645580e-21
static const double pio2_3t = 8.47842766036889956997e-32
Function Documentation
__ieee754_rem_pio2()
__inline int __ieee754_rem_pio2 (double x, double * y)
References __kernel_rem_pio2(), fn, GET_HIGH_WORD, GET_LOW_WORD, high, INSERT_WORDS, invpio2, low, n, pio2_1, pio2_1t, pio2_2, pio2_2t, pio2_3, pio2_3t, r, STRICT_ASSIGN, t, two24, w, z, and zero.
Referenced by cos(), sin(), sincos(), and tan().
Variable Documentation
invpio2
const double invpio2 = 6.36619772367581382433e-01 static
Referenced by __ieee754_rem_pio2().
pio2_1
const double pio2_1 = 1.57079632673412561417e+00 static
Referenced by __ieee754_rem_pio2().
pio2_1t
const double pio2_1t = 6.07710050650619224932e-11 static
Referenced by __ieee754_rem_pio2().
pio2_2
const double pio2_2 = 6.07710050630396597660e-11 static
Referenced by __ieee754_rem_pio2().
pio2_2t
const double pio2_2t = 2.02226624879595063154e-21 static
Referenced by __ieee754_rem_pio2().
pio2_3
const double pio2_3 = 2.02226624871116645580e-21 static
Referenced by __ieee754_rem_pio2().
pio2_3t
const double pio2_3t = 8.47842766036889956997e-32 static
Referenced by __ieee754_rem_pio2().
two24
const double two24 = 1.67772160000000000000e+07 static
Referenced by __ieee754_rem_pio2().
zero
const double zero = 0.00000000000000000000e+00 static
Referenced by __ieee754_rem_pio2().