Embedded Artistry Framework: src/stdlibs/libc/test/ctype/ctype_tests.h File Reference
ctype_tests.h File Reference
Functions
int isalnum_tests (void)
int isalpha_tests (void)
int isascii_tests (void)
int isblank_tests (void)
int isdigit_tests (void)
int isgraph_tests (void)
int iscntrl_tests (void)
int islower_tests (void)
int ispunct_tests (void)
int isspace_tests (void)
int isupper_tests (void)
int isxdigit_tests (void)
int toascii_tests (void)
int tolower_tests (void)
int toupper_tests (void)
int isprint_tests (void)
Function Documentation
isalnum_tests()
int isalnum_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
isalpha_tests()
int isalpha_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
isascii_tests()
int isascii_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
isblank_tests()
int isblank_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
iscntrl_tests()
int iscntrl_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
isdigit_tests()
int isdigit_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
isgraph_tests()
int isgraph_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
islower_tests()
int islower_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
isprint_tests()
int isprint_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
ispunct_tests()
int ispunct_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
isspace_tests()
int isspace_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
isupper_tests()
int isupper_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
isxdigit_tests()
int isxdigit_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
toascii_tests()
int toascii_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
tolower_tests()
int tolower_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().
toupper_tests()
int toupper_tests (void)
References bad_input(), good_input(), and NULL.
Referenced by ctype_tests().