Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_ccoshl.c File Reference
s_ccoshl.c File Reference
#include <openlibm_complex.h>
#include <openlibm_math.h>
Functions
long double complex ccoshl (long double complex z)
Function Documentation
ccoshl()
long double complex ccoshl (long double complex z)
References cimagl(), complex, coshl(), cosl(), creall(), I, sinhl(), sinl(), w, and z.