Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_ctan.c File Reference
s_ctan.c File Reference
#include <float.h>
#include <openlibm_complex.h>
#include <openlibm_math.h>
Macros
#define MACHEP 1.1e-16
#define MAXNUM 1.0e308
Functions
static double _redupi (double x)
static double _ctans (double complex z)
double complex ctan (double complex z)
Variables
static const double DP1 = 3.14159265160560607910E0
static const double DP2 = 1.98418714791870343106E-9
static const double DP3 = 1.14423774522196636802E-17
Macro Definition Documentation
MACHEP
#define MACHEP 1.1e-16
MAXNUM
#define MAXNUM 1.0e308
Function Documentation
_ctans()
static double _ctans (double complex z) static
References _redupi(), cimag(), creal(), fabs(), MACHEP, t, and z.
Referenced by ctan().
_redupi()
static double _redupi (double x) static
References DP1, DP2, DP3, and t.
Referenced by _ctans().
ctan()
double complex ctan (double complex z)
References _ctans(), cimag(), complex, cos(), cosh(), creal(), fabs(), I, MAXNUM, sin(), sinh(), w, and z.
Variable Documentation
DP1
const double DP1 = 3.14159265160560607910E0 static
Referenced by _redupi().
DP2
const double DP2 = 1.98418714791870343106E-9 static
Referenced by _redupi().
DP3
const double DP3 = 1.14423774522196636802E-17 static
Referenced by _redupi().