Embedded Artistry Framework: src/drivers/aardvark/vendor/examples/aai2c_slave.c File Reference
aai2c_slave.c File Reference
#include "aardvark.h"
#include <stdio.h>
#include <stdlib.h>
Macros
#define BUFFER_SIZE 65535
#define SLAVE_RESP_SIZE 26
#define INTERVAL_TIMEOUT 500
Functions
static void dump (Aardvark handle, int timeout_ms)
int main (int argc, char *argv[])
Variables
static u08 data_in [BUFFER_SIZE]
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 65535
INTERVAL_TIMEOUT
#define INTERVAL_TIMEOUT 500
SLAVE_RESP_SIZE
#define SLAVE_RESP_SIZE 26
Function Documentation
dump()
static void dump (Aardvark handle, int timeout_ms) static
References AA_ASYNC_I2C_READ, AA_ASYNC_I2C_WRITE, AA_ASYNC_NO_DATA, aa_async_poll(), aa_i2c_slave_read(), aa_i2c_slave_write_stats(), aa_status_string(), BUFFER_SIZE, data_in, INTERVAL_TIMEOUT, and printf.
Referenced by main().
main()
int main (int argc, char * argv[])
References aa_close(), AA_CONFIG_SPI_I2C, aa_configure(), aa_i2c_slave_disable(), aa_i2c_slave_enable(), aa_i2c_slave_set_response(), aa_open(), aa_target_power(), AA_TARGET_POWER_NONE, atoi(), dump(), printf, SLAVE_RESP_SIZE, and strtol().
Variable Documentation
data_in
u08 data_in[BUFFER_SIZE] static
Referenced by _readMemory(), _writeMemory(), aa_i2c_read(), aa_i2c_read_ext(), aa_i2c_slave_read(), aa_i2c_slave_read_ext(), aa_spi_slave_read(), aa_spi_write(), and dump().