Embedded Artistry Framework: src/stdlibs/libc/src/gdtoa/src/strtoIQ.c File Reference
strtoIQ.c File Reference
#include "gdtoaimp.h"
Functions
int strtoIQ (CONST char *s, char **sp, void *a, void *b)
Function Documentation
strtoIQ()
int strtoIQ (CONST char * s, char ** sp, void * a, void * b)
References a, b, B, Balloc(), Bfree(), exp(), k, Long, s, SI, strtoIg(), and ULtoQ().