Embedded Artistry lic: src/string/strtok.c File Reference
strtok.c File Reference
#include <stddef.h>
#include <string.h>
Functions
char * __strtok_r (char *, const char *, char **)
char * strtok (char *s, const char *delim)
Function Documentation
__strtok_r()
char * __strtok_r (char * s, const char * delim, char ** last)
Definition at line 43 of file strtok.c.
References NULL.
Referenced by strtok().
 {
     char *spanp, *tok;
     int c, sc;
     if(s == NULL && (s = *last) == NULL)
         return (NULL);
 /*
  * Skip (span) leading delimiters (s += strspn(s, delim), sort of).
  */
 cont:
     c = *s++;
     for(spanp = (char*)delim; (sc = *spanp++) != 0;)
     {
         if(c == sc)
             goto cont;
     }
     if(c == 0)
     { /* no non-delimiter characters */
         *last = NULL;
         return (NULL);
     }
     tok = s - 1;
     /*
      * Scan token (scan for delimiters: s += strcspn(s, delim), sort of).
      * Note that delim must have one NUL; we stop if we see that, too.
      */
     for(;;)
     {
         c = *s++;
         spanp = (char*)delim;
         do
         {
             if((sc = *spanp++) == c)
             {
                 if(c == 0)
                     s = NULL;
                 else
                     s[-1] = '\0';
                 *last = s;
                 return (tok);
             }
         } while(sc != 0);
     }
     /* NOTREACHED */
 }
strtok()
char* strtok (char * s, const char * delim)
Definition at line 93 of file strtok.c.
References __strtok_r(), main(), NULL, and strcpy().
 {
     static char* last;
     return (__strtok_r(s, delim, &last));
 }