Embedded Artistry Framework: src/stdlibs/libc/src/stdlib/imaxabs.c File Reference
imaxabs.c File Reference
#include <stdlib.h>
Functions
intmax_t imaxabs (intmax_t j)
Computes the absolute value of an intmax_t number.
Function Documentation
imaxabs()
intmax_t imaxabs (intmax_t j)
Computes the absolute value of an intmax_t number.
Computes the absolute value of an intmax_t number. The behavior is undefined if the result cannot be represented by the return type.
Parameters
j value
Returns
The absolute value of n (i.e. |n|), if it is representable.
Referenced by imaxabs_test(), labs_test(), and llabs_test().