Embedded Artistry lic: src/ctype/isspace.c File Reference
isspace.c File Reference
#include <ctype.h>
Functions
int isspace (int c)
Function Documentation
isspace()
int isspace (int c)
Definition at line 5 of file isspace.c.
Referenced by atol(), atoll(), strtol(), strtoll(), strtoul(), and strtoull().
 {
     return c == ' ' || (unsigned)c - '\t' < 5;
 }