Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/e_jnf.c File Reference
e_jnf.c File Reference
#include "cdefs-compat.h"
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float __ieee754_jnf (int n, float x)
OLM_DLLEXPORT float __ieee754_ynf (int n, float x)
Variables
static const float two = 2.0000000000e+00
static const float one = 1.0000000000e+00
static const float zero = 0.0000000000e+00
Function Documentation
__ieee754_jnf()
OLM_DLLEXPORT float __ieee754_jnf (int n, float x)
References __ieee754_j0f(), __ieee754_j1f(), __ieee754_logf(), a, b, IEEEl2bits::e, fabsf(), GET_FLOAT_WORD, k, n, one, t, two, w, z, and zero.
__ieee754_ynf()
OLM_DLLEXPORT float __ieee754_ynf (int n, float x)
References __ieee754_y0f(), __ieee754_y1f(), a, b, GET_FLOAT_WORD, n, one, and zero.
Variable Documentation
one
const float one = 1.0000000000e+00 static
Referenced by __ieee754_jnf(), and __ieee754_ynf().
two
const float two = 2.0000000000e+00 static
Referenced by __ieee754_jnf().
zero
const float zero = 0.0000000000e+00 static
Referenced by __ieee754_jnf(), and __ieee754_ynf().