Embedded Artistry Framework: os::freertos::ConditionVariable Class Reference
os::freertos::ConditionVariable Class Reference final
#include <freertos_condition_variable.hpp>
Public Member Functions
ConditionVariable ()=default
~ConditionVariable ()
bool wait (embvm::VirtualMutex *mutex) noexcept final
Blocks the current thread until the condition variable is woken up or after the specified timeout duration.
bool wait (embvm::VirtualMutex *mutex, const embvm::os_timeout_t &timeout) noexcept final
bool wait (embvm::VirtualMutex *mutex, const timespec &timeout) noexcept
void signal () noexcept final
notifies one waiting thread
void broadcast () noexcept final
Notify all waiting threads.
embvm::cv::handle_t native_handle () const noexcept final
bool wait (embvm::VirtualMutex *mutex, const embvm::cv::func_t &predicate) noexcept
bool wait (embvm::VirtualMutex *mutex, const embvm::cv::func_t &predicate, const embvm::os_timeout_t &timeout=embvm::OS_WAIT_FOREVER) noexcept
void notify_one () noexcept
Alias for signal so we can work with STL types.
void notify_all () noexcept
Alias for broadcast so we can work with STL types.
Private Types
using TQueueType = typename std::conditional<(FREERTOS_NUM_THREADS_PER_CV==0), std::queue< embvm::thread::handle_t >, etl::queue< embvm::thread::handle_t, FREERTOS_NUM_THREADS_PER_CV > >::type
Private Member Functions
bool freertos_wait (embvm::VirtualMutex *mutex, uint32_t ticks_timeout)
void pop_and_notify ()
Private Attributes
os::freertos::Semaphore sem_ {embvm::semaphore::mode::binary}
TQueueType q_
Member Typedef Documentation
TQueueType
using os::freertos::ConditionVariable::TQueueType = typename std::conditional< (FREERTOS_NUM_THREADS_PER_CV == 0), std::queue<embvm::thread::handle_t>, etl::queue<embvm::thread::handle_t, FREERTOS_NUM_THREADS_PER_CV> >::type private
Constructor & Destructor Documentation
ConditionVariable()
os::freertos::ConditionVariable::ConditionVariable () default
~ConditionVariable()
ConditionVariable::~ConditionVariable ()
References assert, and q_.
Member Function Documentation
broadcast()
void ConditionVariable::broadcast () final virtual noexcept
Notify all waiting threads.
Implements embvm::VirtualConditionVariable.
References os::freertos::Semaphore::give(), pop_and_notify(), q_, sem_, and os::freertos::Semaphore::take().
freertos_wait()
bool ConditionVariable::freertos_wait (embvm::VirtualMutex * mutex, uint32_t ticks_timeout) private
References embvm::this_thread::get_handle(), os::freertos::Semaphore::give(), embvm::VirtualMutex::lock(), NULL, portMAX_DELAY, q_, r, sem_, os::freertos::Semaphore::take(), and embvm::VirtualMutex::unlock().
native_handle()
embvm::cv::handle_t os::freertos::ConditionVariable::native_handle () const inline final virtual noexcept
Implements embvm::VirtualConditionVariable.
References os::freertos::Semaphore::native_handle(), and sem_.
notify_all()
void embvm::VirtualConditionVariable::notify_all () inline noexcept inherited
Alias for broadcast so we can work with STL types.
References embvm::VirtualConditionVariable::broadcast().
notify_one()
void embvm::VirtualConditionVariable::notify_one () inline noexcept inherited
Alias for signal so we can work with STL types.
References embvm::VirtualConditionVariable::signal().
pop_and_notify()
void ConditionVariable::pop_and_notify () private
References q_.
Referenced by broadcast(), and signal().
signal()
void ConditionVariable::signal () final virtual noexcept
notifies one waiting thread
Implements embvm::VirtualConditionVariable.
References os::freertos::Semaphore::give(), NULL, pop_and_notify(), q_, sem_, and os::freertos::Semaphore::take().
wait() [1/5]
bool ConditionVariable::wait (embvm::VirtualMutex * mutex) final virtual noexcept
Blocks the current thread until the condition variable is woken up or after the specified timeout duration.
Implements embvm::VirtualConditionVariable.
References portMAX_DELAY.
wait() [2/5]
bool ConditionVariable::wait (embvm::VirtualMutex * mutex, const embvm::os_timeout_t & timeout) final virtual noexcept
Implements embvm::VirtualConditionVariable.
References os::freertos::frameworkTimeoutToTicks().
wait() [3/5]
bool ConditionVariable::wait (embvm::VirtualMutex * mutex, const timespec & timeout) noexcept
References os::freertos::frameworkTimeoutToTicks(), and embutil::timespecToDuration().
wait() [4/5]
bool embvm::VirtualConditionVariable::wait (embvm::VirtualMutex * mutex, const embvm::cv::func_t & predicate) inline noexcept inherited
References embvm::VirtualConditionVariable::wait().
wait() [5/5]
bool embvm::VirtualConditionVariable::wait (embvm::VirtualMutex * mutex, const embvm::cv::func_t & predicate, const embvm::os_timeout_t & timeout = embvm::OS_WAIT_FOREVER) inline noexcept inherited
We break when the predicate is true or when we've timed out
References embvm::VirtualConditionVariable::wait().
Member Data Documentation
q_
TQueueType os::freertos::ConditionVariable::q_ private
Referenced by broadcast(), freertos_wait(), pop_and_notify(), signal(), and ~ConditionVariable().
sem_
os::freertos::Semaphore os::freertos::ConditionVariable::sem_ {embvm::semaphore::mode::binary} private
Referenced by broadcast(), freertos_wait(), native_handle(), and signal().
The documentation for this class was generated from the following files:
src/os/freertos/freertos_condition_variable.hpp
src/os/freertos/freertos_condition_variable.cpp