Embedded Artistry Framework: src/stdlibs/libc/openlibm/src/s_ctanhf.c File Reference
s_ctanhf.c File Reference
#include "cdefs-compat.h"
#include <openlibm_complex.h>
#include <openlibm_math.h>
#include "math_private.h"
Functions
OLM_DLLEXPORT float complex ctanhf (float complex z)
OLM_DLLEXPORT float complex ctanf (float complex z)
Function Documentation
ctanf()
OLM_DLLEXPORT float complex ctanf (float complex z)
References cimagf(), CMPLXF(), crealf(), ctanhf(), and z.
ctanhf()
OLM_DLLEXPORT float complex ctanhf (float complex z)
References cimagf(), CMPLXF(), copysignf(), cosf(), crealf(), expf(), fabsf(), GET_FLOAT_WORD, isfinite, isinf, s, SET_FLOAT_WORD, sinf(), sinhf(), sqrtf(), t, tanf(), and z.
Referenced by ctanf().