Embedded Artistry Framework: embvm::spi::activeMaster< TQueueSize, TLock, TCond > Class Template Reference
embvm::spi::activeMaster< TQueueSize, TLock, TCond > Class Template Reference final abstract
#include <active_spi.hpp>
Public Member Functions
activeMaster (embvm::spi::master &m)
~activeMaster ()=default
void process_ (ao_storage pair)
virtual void configure (spi::baud_t baud)
Configure the SPI bus.
spi::mode mode () const
Get the current SPI bus mode.
spi::mode mode (spi::mode mode)
Set the SPI bus mode.
spi::order order () const
Get the current SPI bus byte order.
spi::order order (spi::order order)
Set the SPI bus byte order.
void start ()
Start the driver.
void stop ()
Stop the driver.
void restart ()
Restart the driver.
type_safe::boolean started () const noexcept
Check if the driver has been started.
constexpr embvm::DriverType_t DriverType () const noexcept
Returns the registered type ID of the driver.
constexpr const std::string_view & name () const noexcept
Provides a string_view reference of the driver name.
constexpr const char * name_cstr () const noexcept
Provides a c-string version of the driver name.
virtual DriverBase & operator++ () noexcept
Increment operator is a no-op, but is used for iterator compatibility.
size_t queuedCount () noexcept
Get the number of operations in the queue.
bool enqueue (embvm::spi::ao_storage t)
Add an operation to the queue.
void shutdown ()
Shutdown the active object.
Static Public Member Functions
static constexpr embvm::DriverType type ()
SPI Driver Type ID.
Protected Member Functions
embvm::comm::status transfer_ (const spi::op_t &op, const cb_t &cb) override=0
Protected Attributes
spi::mode mode_ = spi::mode::mode0
Stores the active SPI mode configuration.
spi::order order_ = spi::order::msbFirst
Stores the active SPI byte ordering.
type_safe::boolean started_ = false
Tracks the driver state.
const std::string_view name_
Name of the driver instance.
const embvm::DriverType_t type_
Type ID of the driver instance.
Private Types
using ao_base = embutil::activeObject< activeMaster, ao_storage, TQueueSize, TLock, TCond >
Private Member Functions
void start_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void stop_ () final
Derived classes override the start_ method to control driver-specific startup behavior.
void configure_ () final
Configure the SPI bus for operation.
void setMode_ (embvm::spi::mode mode) final
Set the SPI bus mode.
void setOrder_ (embvm::spi::order order) final
Set the SPI bus byte order.
embvm::spi::status transfer_ (const embvm::spi::op_t &op, const embvm::spi::master::cb_t &cb) final
embvm::spi::baud_t baudrate_ (embvm::spi::baud_t baud) final
Private Attributes
embvm::spi::master & m_
Member Typedef Documentation
ao_base
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> using embvm::spi::activeMaster< TQueueSize, TLock, TCond >::ao_base = embutil::activeObject<activeMaster, ao_storage, TQueueSize, TLock, TCond> private
Constructor & Destructor Documentation
activeMaster()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::spi::activeMaster< TQueueSize, TLock, TCond >::activeMaster (embvm::spi::master & m) inline explicit
~activeMaster()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::spi::activeMaster< TQueueSize, TLock, TCond >::~activeMaster () default
Member Function Documentation
baudrate_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::spi::baud_t embvm::spi::activeMaster< TQueueSize, TLock, TCond >::baudrate_ (embvm::spi::baud_t baud) inline final private virtual
Implements embvm::spi::master.
References embvm::spi::activeMaster< TQueueSize, TLock, TCond >::m_.
configure()
virtual void embvm::spi::master::configure (spi::baud_t baud) inline virtual inherited
Configure the SPI bus.
Configures the SPI bus for operation and sets the target baud rate.
Derived classes must implement the configure_() function to set up the target hardware.
Parameters
baud The target baudrate, in Hz. TODO: Tolerance - allowed relative tolerance for the resulting baudrate
References embvm::spi::master::configure_().
configure_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> void embvm::spi::activeMaster< TQueueSize, TLock, TCond >::configure_ () inline final private virtual
Configure the SPI bus for operation.
This function is implemented by the derived class. It is responsible for configuring the target hardware for operation.
Implements embvm::spi::master.
DriverType()
constexpr embvm::DriverType_t embvm::DriverBase::DriverType () const inline noexcept inherited
Returns the registered type ID of the driver.
When using DriverBase interfaces, clients can retrieve the registered driver type in order to up-cast to the correct interface.
The type is returned as a embvm::DriverType_t rather than a embvm::DriverType enum to work with custom user-defined types. Enforcing a embvm::DriverType return value would prevent clients from defining and using their own custom types.
Returns
the registered driver type as a embvm::DriverType_t value
References embvm::DriverBase::type_.
enqueue()
bool embutil::activeObject< embvm::spi::activeMaster< TQueueSize, TLock, TCond > , embvm::spi::ao_storage , TQueueSize, TLock, TCond >::enqueue (embvm::spi::ao_storage t) inline inherited
Add an operation to the queue.
This function can be called directly, or by functions internal to the activeObject. For example, the "transfer" API enqueues transfer operations.
Parameters
t The operation data object to enqueue for later processing.
mode() [1/2]
spi::mode embvm::spi::master::mode () const inline inherited
Get the current SPI bus mode.
Returns
The currently configured mode.
References embvm::spi::master::mode_.
Referenced by embvm::spi::master::mode(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setMode_(), embdrv::aardvarkSPIMaster::setMode_(), and test::spiTestDriver::setMode_().
mode() [2/2]
spi::mode embvm::spi::master::mode (spi::mode mode) inline inherited
Set the SPI bus mode.
Derived classes must implement the setMode_() function, which is reponsible for configuring the target hardware.
Parameters
mode The desired SPI bus mode.
Returns
The new SPI bus mode.
References embvm::spi::master::mode(), embvm::spi::master::mode_, and embvm::spi::master::setMode_().
name()
constexpr const std::string_view& embvm::DriverBase::name () const inline noexcept inherited
Provides a string_view reference of the driver name.
Returns
std::string_view ref containing the driver name.
References embvm::DriverBase::name_.
name_cstr()
constexpr const char* embvm::DriverBase::name_cstr () const inline noexcept inherited
Provides a c-string version of the driver name.
Returns
c-string containing the driver name
References embvm::DriverBase::name_.
operator++()
virtual DriverBase& embvm::DriverBase::operator++ () inline virtual noexcept inherited
Increment operator is a no-op, but is used for iterator compatibility.
order() [1/2]
spi::order embvm::spi::master::order () const inline inherited
Get the current SPI bus byte order.
Returns
The currently configured byte order.
References embvm::spi::master::order_.
Referenced by embvm::spi::master::order(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setOrder_(), embdrv::aardvarkSPIMaster::setOrder_(), and test::spiTestDriver::setOrder_().
order() [2/2]
spi::order embvm::spi::master::order (spi::order order) inline inherited
Set the SPI bus byte order.
Derived classes must implement the setOrder_() function, which is reponsible for configuring the target hardware.
Parameters
order The desired byte ordering.
Returns
The new byte ordering.
References embvm::spi::master::order(), embvm::spi::master::order_, and embvm::spi::master::setOrder_().
process_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> void embvm::spi::activeMaster< TQueueSize, TLock, TCond >::process_ (ao_storage pair) inline
References embvm::spi::activeMaster< TQueueSize, TLock, TCond >::m_, r, and embvm::this_thread::sleep_for().
queuedCount()
size_t embutil::activeObject< embvm::spi::activeMaster< TQueueSize, TLock, TCond > , embvm::spi::ao_storage , TQueueSize, TLock, TCond >::queuedCount () inline noexcept inherited
Get the number of operations in the queue.
Returns
the number of queued operations.
restart()
void embvm::DriverBase::restart () inline inherited
Restart the driver.
Calls stop() and then start() on the driver. If the driver is not started, then it will be started after the start() function is invoked.
References embvm::DriverBase::start(), and embvm::DriverBase::stop().
setMode_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> void embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setMode_ (embvm::spi::mode mode) inline final private virtual
Set the SPI bus mode.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the new mode.
Parameters
mode The desired byte ordering.
Implements embvm::spi::master.
References embvm::spi::activeMaster< TQueueSize, TLock, TCond >::m_, and embvm::spi::master::mode().
setOrder_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> void embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setOrder_ (embvm::spi::order order) inline final private virtual
Set the SPI bus byte order.
This function is implemented by the derived class. It is responsible for configuring the target hardware to use the new byte ordering.
Parameters
order The desired byte ordering.
Implements embvm::spi::master.
References embvm::spi::activeMaster< TQueueSize, TLock, TCond >::m_, and embvm::spi::master::order().
shutdown()
void embutil::activeObject< embvm::spi::activeMaster< TQueueSize, TLock, TCond > , embvm::spi::ao_storage , TQueueSize, TLock, TCond >::shutdown () inline inherited
Shutdown the active object.
Call this function in the parent class destructor to stop the AO thread operation before destroying the parent class. This will prevent memory access problems due to race conidtions during destruction.
The shutdown process is permanent and cannot be reversed without recreating the object.
start()
void embvm::DriverBase::start () inline inherited
Start the driver.
If the driver is not started, call the start_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::start_(), and embvm::DriverBase::started_.
Referenced by NRF52DongleHWPlatform::init_(), NRF52DKHWPlatform::init_(), BlinkySimulatorHWPlatform::init_(), FWDemoSimulatorHWPlatform::init_(), FrameworkDemoSimPlatform::initHWPlatform_(), embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), embvm::i2c::activeMaster< 128 >::start_(), embdrv::aardvarkSPIMaster::start_(), embdrv::aardvarkI2CMaster::start_(), embdrv::aardvarkGPIOInput< 4 >::start_(), embdrv::vl53l1x::start_(), embdrv::aardvarkGPIOOutput< 5 >::start_(), embvm::led::gpio< TActiveHigh >::start_(), BlinkySimulatorHWPlatform::startBlink(), and FWDemoSimulatorHWPlatform::startLEDTimer().
start_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> void embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_ () inline final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::spi::master.
References embvm::spi::activeMaster< TQueueSize, TLock, TCond >::m_, and embvm::DriverBase::start().
started()
type_safe::boolean embvm::DriverBase::started () const inline noexcept inherited
Check if the driver has been started.
Returns
true if the driver is running (started), false if not running (stopped).
References embvm::DriverBase::started_.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embdrv::aardvarkGPIOInput< 4 >::get(), embdrv::aardvarkGPIOOutput< 5 >::set(), embdrv::vl53l1x::start_(), embdrv::aardvarkAdapter::start_(), and embdrv::aardvarkAdapter::stop_().
stop()
void embvm::DriverBase::stop () inline inherited
Stop the driver.
If the driver has been started, call the stop_() function defined by the derived class. (Template Method Pattern)
References embvm::DriverBase::started_, and embvm::DriverBase::stop_().
Referenced by embvm::DriverBase::restart(), embvm::timer::Timer::restart(), embdrv::ssd1306::scrollLeft(), embdrv::ssd1306::scrollRight(), embdrv::ssd1306::scrollVertLeft(), embdrv::ssd1306::scrollVertRight(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_(), embvm::i2c::activeMaster< 128 >::stop_(), embdrv::aardvarkSPIMaster::stop_(), embdrv::aardvarkI2CMaster::stop_(), embdrv::aardvarkGPIOInput< 4 >::stop_(), embdrv::aardvarkGPIOOutput< 5 >::stop_(), embvm::led::gpio< TActiveHigh >::stop_(), FWDemoSimulatorHWPlatform::~FWDemoSimulatorHWPlatform(), and embdrv::SimulatorTimer::~SimulatorTimer().
stop_()
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> void embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_ () inline final private virtual
Derived classes override the start_ method to control driver-specific startup behavior.
(Template Method Pattern)
Implements embvm::spi::master.
References embvm::spi::activeMaster< TQueueSize, TLock, TCond >::m_, and embvm::DriverBase::stop().
transfer_() [1/2]
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::spi::status embvm::spi::activeMaster< TQueueSize, TLock, TCond >::transfer_ (const embvm::spi::op_t & op, const embvm::spi::master::cb_t & cb) inline final private
References embutil::activeObject< TDerivedClass, TStorageType, TQueueSize, TLock, TCond >::enqueue().
transfer_() [2/2]
embvm::comm::status embvm::spi::master::transfer_ (const spi::op_t & op, const cb_t & cb) override protected pure virtual inherited
type()
static constexpr embvm::DriverType embvm::spi::master::type () inline static inherited
SPI Driver Type ID.
Returns
SPI type ID.
References embvm::SPI.
Member Data Documentation
m_
template<size_t TQueueSize = 0, typename TLock = std::mutex, typename TCond = std::condition_variable> embvm::spi::master& embvm::spi::activeMaster< TQueueSize, TLock, TCond >::m_ private
Referenced by embvm::spi::activeMaster< TQueueSize, TLock, TCond >::baudrate_(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::process_(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setMode_(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::setOrder_(), embvm::spi::activeMaster< TQueueSize, TLock, TCond >::start_(), and embvm::spi::activeMaster< TQueueSize, TLock, TCond >::stop_().
mode_
spi::mode embvm::spi::master::mode_ = spi::mode::mode0 protected inherited
Stores the active SPI mode configuration.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embvm::spi::master::mode(), and embdrv::aardvarkSPIMaster::setMode_().
name_
const std::string_view embvm::DriverBase::name_ protected inherited
Name of the driver instance.
Referenced by embvm::DriverBase::DriverBase(), embvm::DriverBase::name(), and embvm::DriverBase::name_cstr().
order_
spi::order embvm::spi::master::order_ = spi::order::msbFirst protected inherited
Stores the active SPI byte ordering.
Referenced by embdrv::aardvarkSPIMaster::configure_(), embvm::spi::master::order(), and embdrv::aardvarkSPIMaster::setOrder_().
started_
type_safe::boolean embvm::DriverBase::started_ = false protected inherited
Tracks the driver state.
True if the driver has been started, false if it has been stopped or not yet started.
Referenced by embdrv::aardvarkI2CMaster::baudrate_(), embdrv::aardvarkI2CMaster::configure_(), embdrv::aardvarkI2CMaster::setPullups_(), embvm::DriverBase::start(), embvm::DriverBase::started(), and embvm::DriverBase::stop().
type_
const embvm::DriverType_t embvm::DriverBase::type_ protected inherited
Type ID of the driver instance.
Referenced by embvm::DriverBase::DriverType().
The documentation for this class was generated from the following file:
src/core/driver/active_spi.hpp